var indikatoren = [{"title":"Beurteilung der Chancengleichheit",
"subtitle":"«Die Chancengleichheit wird von den Behörden zielstrebig vorangetrieben.»",
"kuerzel":"I.50.1.0020",
"kuerzelKunde":"2.2.03",
"image":"images/I.50.1.0020.jpg",
"description":"Beurteilung der Chancengleichheit",
"id":"4858",
"thema":"50 Befragungen",
"unterthema":"Bevölkerungsbefragung",
"kennzahlenset":"Gesellschaftlicher Zusammenhalt",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Geschlecht","Verwaltung","Grosser Rat","Beurteilung"],
"stufe1":"2 Verbundenheit",
"stufe2":"2.2 Vertrauen in Institutionen",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"2015 zeigten sich 51,9% der Befragten mit der Aussage, dass die kantonalen Behörden die Chancengleichheit von Männern und Frauen zielstrebig vorantreiben, eher oder sehr einverstanden. Somit ist die Zustimmung seit 2007 (44,5% eher oder sehr Einverstandene) beständig gestiegen.",
"erlaeuterungen":"",
"template":"befragungenProzent001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung: F16a_7"]
}];
