var indikatoren = [{"title":"Es gibt zu viele Menschen aus dem Ausland in Basel-Stadt",
"subtitle":"«Grundsätzlich gibt es einfach zu viele Menschen aus dem Ausland bei uns.»",
"kuerzel":"I.50.1.0014",
"kuerzelKunde":"1.3.02",
"image":"images/I.50.1.0014.jpg",
"description":"Es gibt zu viele Menschen aus dem Ausland in Basel-Stadt",
"id":"4855",
"thema":"50 Befragungen",
"unterthema":"Bevölkerungsbefragung",
"kennzahlenset":"Gesellschaftlicher Zusammenhalt",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Ausländer","Ausland"],
"stufe1":"1 Soziale Beziehungen",
"stufe2":"1.3 Akzeptanz von Diversität",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"2011 waren 53,1% der Befragten der Meinung, es gäbe grundsätzlich zu viele Menschen aus dem Ausland im Kanton Basel-Stadt. Dieser Wert hat sich 2015 auf 46,7% reduziert.",
"erlaeuterungen":"",
"template":"befragungenProzent001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung: F18b"]
}];
