var indikatoren = [{"title":"Segregationsindex nach Staatsangehörigkeit seit 2006",
"subtitle":"",
"kuerzel":"I.01.1.0021",
"kuerzelKunde":"2-1",
"image":"images/I.01.1.0021.jpg",
"description":"Segregationsindex nach Staatsangehörigkeit seit 2006",
"id":"4465",
"thema":"01 Bevölkerung",
"unterthema":"Bestand und Struktur ",
"kennzahlenset":"Integration kompakt",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Ausländer","Bevölkerung","Ausland","Migration","Segregation","Index","Schweiz","Wanderung"],
"stufe1":"2 Wohnortwahl",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"2015 war die ausländische Bevölkerung weniger stark auf einzelne Gemeinden und Wohnviertel konzentriert als noch 2006. Der Segregationsindex, ein Mass zur Beschreibung räumlicher Ungleichverteilungen von Bevölkerungsgruppen, sank für die Ausländer zwischen 2006 und 2015 von 24,5 auf 18,7. Von den hier ausgewählten Bevölkerungsgruppen wiesen Ende 2015 Personen aus dem ehemaligen Jugoslawien und Türken die höchsten Segregationsindices auf (32,7 und 30,8). Der niedrigste Index ergab sich für die Deutschen (7,7).",
"erlaeuterungen":"Der Segregationsindex misst hier, wie stark die Verteilung einer Bevölkerungsgruppe über das Kantonsgebiet von einer Gleichverteilung abweicht, wobei 0 absolute Gleichverteilung und 100 maximale Segregation bedeutet. Der Wert des Segregationsindexes lässt sich auch als Prozentanteil der betracheten Gruppe interpretieren, der umziehen müsste, um gleich über ein Gebiet verteilt zu sein wie die übrige Bevölkerung. Ein Segregationsindex von 0 würde bedeuten, dass der Anteil Personen einer Gruppe am Total der Bevölkerung in jedem Teilgebiet gleich gross wäre.",
"template":"line001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Bevölkerungsstatistik"]
}];
