var indikatoren = [{"title":"Anteil Konfessionslose",
"subtitle":"",
"kuerzel":"I.01.7.0001",
"kuerzelKunde":"GS-3",
"image":"images/I.01.7.0001.jpg",
"description":"Anteil Konfessionslose",
"id":"4824",
"thema":"01 Bevölkerung",
"unterthema":"Religionen",
"kennzahlenset":"Wohnviertel",
"raeumlicheGliederung":["Wohnviertel"],
"aktualisierungsdatum":"2016-06-30T00:00:00.000",
"schlagwort":["Religion"],
"stufe1":"1 Gesellschaft und Soziales",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"",
"erlaeuterungen":"Anteil der konfessionslosen Personen an der gesamten Wohnbevölkerung des Wohnviertels in Prozent. Stand: 2015",
"template":"dotplot",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Bevölkerungsstatistik"]
}];
