var indikatoren = [{"title":"Anteil Personen, welche zu Hause «deutsch» oder «schweizerdeutsch» sprechen nach Staatsangehörigkeit 2010 bis 2014",
"subtitle":"",
"kuerzel":"I.01.8.0001",
"kuerzelKunde":"1-8",
"image":"images/I.01.8.0001.jpg",
"description":"Anteil Personen, welche zu Hause «deutsch» oder «schweizerdeutsch» sprechen nach Staatsangehörigkeit 2010 bis 2014",
"id":"4463",
"thema":"01 Bevölkerung",
"unterthema":"Sprachen",
"kennzahlenset":"Integration kompakt",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Heimat","Haushalt","Ausländer","Quote","Ausland","Migrationshintergrund","Migration","Deutsch"],
"stufe1":"1 Struktur der Bevölkerung",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Die Grafik zeigt den Anteil der Bevölkerung über 15 Jahre in Basel-Stadt, der zu Hause Deutsch spricht, gruppiert nach verschiedenen Herkunftsländern. Rund 94% der Schweizer in Basel-Stadt geben im Jahr 2014 an, zu Hause unter anderem deutsch zu sprechen (die Angabe von mehreren Sprachen ist möglich). Bei den Personen aus Deutschland, Österreich und Liechtenstein sind es etwa 97%. 42% der Personen aus anderen Herkunftsländern sprechen zu Hause deutsch.",
"erlaeuterungen":"Die Strukturerhebung ist eine Stichprobenerhebung bei rund 5 000 in Basel-Stadt wohnhaften Personen im Alter über 15 Jahren.",
"template":"line001",
"option":"options001",
"quellenangabe":["Bundesamt für Statistik BFS, Strukturerhebung (SE)"]
}];
