var indikatoren = [{"title":"Jugendquotient nach Staatsangehörigkeit 2015",
"subtitle":"",
"kuerzel":"I.01.1.0015",
"kuerzelKunde":"1-3",
"image":"images/I.01.1.0015.jpg",
"description":"Jugendquotient nach Staatsangehörigkeit 2015",
"id":"4218",
"thema":"01 Bevölkerung",
"unterthema":"Bestand und Struktur ",
"kennzahlenset":"Integration kompakt",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Alter","Quote","Ausland","Alter","Schweiz"],
"stufe1":"1 Struktur der Bevölkerung",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Der Jugendquotient für Personen aus dem ehemaligen Jugoslawien und aus der Türkei liegt über der 30%-Grenze und damit über dem Jugendquotient der Schweizer (27%)  Die kleinsten Anteile an 0- bis 19-Jährigen weisen Personen aus den EU-Oststaaten und Deutschland auf.",
"erlaeuterungen":"Der Jugendquotient wird wie folgt berechnet: Anzahl Personen im Alter von 0 bis 19 Jahren geteilt durch Anzahl Personen im Alter zwischen 20 und 64 Jahren.",
"template":"template001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Bevölkerungsstatistik"]
}];
