var indikatoren = [{"title":"Sesshaftigkeit",
"subtitle":"",
"kuerzel":"I.01.1.0040",
"kuerzelKunde":"GS-7",
"image":"images/I.01.1.0040.jpg",
"description":"Sesshaftigkeit",
"id":"4828",
"thema":"01 Bevölkerung",
"unterthema":"Bestand und Struktur ",
"kennzahlenset":"Wohnviertel",
"raeumlicheGliederung":["Wohnviertel"],
"aktualisierungsdatum":"2016-06-30T00:00:00.000",
"schlagwort":["Wohndauer"],
"stufe1":"1 Gesellschaft und Soziales",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"",
"erlaeuterungen":"Anteil der seit mindestens 10 Jahren am gleichen Wohnsitz wohnenden Personen an der gesamten Wohnbevölkerung des Wohnviertels in Prozent. Stand: 2015",
"template":"dotplot",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Bevölkerungsstatistik"]
}];
