var indikatoren = [{"title":"Ausländische Bevölkerung nach Wohndauer und Geburtsort seit 2006",
"subtitle":"",
"kuerzel":"I.01.1.0043",
"kuerzelKunde":"2-3b",
"image":"images/I.01.1.0043.jpg",
"description":"Ausländische Bevölkerung nach Wohndauer und Geburtsort seit 2006",
"id":"4905",
"thema":"01 Bevölkerung",
"unterthema":"Bestand und Struktur ",
"kennzahlenset":"Integration kompakt",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Heimat","Bevölkerung","Ausland","Niederlassung","Migration","Wohndauer","Schweiz","Geburtsort","Staatsangehörigkeit"],
"stufe1":"",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Rund 20% der Ausländer wohnen seit mindestens 12 Jahren im selben Wohnviertel resp. derselben Landgemeinde.",
"erlaeuterungen":"",
"template":"template001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Bevölkerungsstatistik"]
}];
