var indikatoren = [{"title":"Erwachsene Einwohner mit Hauptwohnsitz im Kanton Basel-Stadt",
"subtitle":"",
"kuerzel":"I.01.1.0025",
"kuerzelKunde":"2.2.a",
"image":"images/I.01.1.0025.jpg",
"description":"Erwachsene Einwohner mit Hauptwohnsitz im Kanton Basel-Stadt",
"id":"4148",
"thema":"01 Bevölkerung",
"unterthema":"Bestand und Struktur ",
"kennzahlenset":"Wohnraumentwicklung",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Gebäude","Haushalt"],
"stufe1":"2 Fiskalpolitik",
"stufe2":"2.2 Anteil an Hauptwohnsitznehmern",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Die Anzahl volljähriger Personen mit Hauptwohnsitz in Basel-Stadt nimmt stetig leicht zu. Diese Personen versteuern ihr Einkommen oder ihre Vermögenswerte, falls vorhanden, in der Regel in Basel-Stadt.",
"erlaeuterungen":"",
"template":"line001",
"option":"options001",
"quellenangabe":["Bundesamt für Statistik BFS, STATPOP"]
}];
