var indikatoren = [{"title":"Anteil Grünflächen",
"subtitle":"",
"kuerzel":"I.02.1.0016",
"kuerzelKunde":"RU-3",
"image":"images/I.02.1.0016.jpg",
"description":"Anteil Grünflächen",
"id":"4832",
"thema":"02 Raum, Umwelt",
"unterthema":"Räumliche Gliederung und Bodennutzung",
"kennzahlenset":"Wohnviertel",
"raeumlicheGliederung":["Wohnviertel"],
"aktualisierungsdatum":"2016-06-30T00:00:00.000",
"schlagwort":["Grünflächen"],
"stufe1":"2 Raum und Umwelt",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"",
"erlaeuterungen":"Anteil der Grünfläche an der gesamten Fläche des Wohnviertels in Prozent. Stand: 2014",
"template":"dotplot",
"option":"options001",
"quellenangabe":["Grundbuch- und Vermessungsamt  Basel-Stadt"]
}];
