var indikatoren = [{"title":"Arbeitsplätze pro Kopf",
"subtitle":"",
"kuerzel":"I.03.2.0002",
"kuerzelKunde":"WA-4",
"image":"images/I.03.2.0002.jpg",
"description":"Arbeitsplätze pro Kopf",
"id":"4838",
"thema":"03 Erwerbsleben",
"unterthema":"Beschäftigte ",
"kennzahlenset":"Wohnviertel",
"raeumlicheGliederung":["Wohnviertel"],
"aktualisierungsdatum":"2016-06-30T00:00:00.000",
"schlagwort":["Erwerb"],
"stufe1":"3 Wirtschaft und Arbeit",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"",
"erlaeuterungen":"Anzahl Arbeitsplätze (Beschäftigtenzahl in Vollzeitäquivalenten einschliesslich Beschäftigter, die nicht im Kanton wohnen, aber hier arbeiten) an der gesamten Wohnbevölkerung des Wohnviertels. Stand: 2013",
"template":"dotplot",
"option":"options001",
"quellenangabe":["Bundesamt für Statistik BFS, STATENT"]
}];
