var indikatoren = [{"title":"Arbeitslosenquote",
"subtitle":"",
"kuerzel":"I.03.4.0003",
"kuerzelKunde":"WA-5",
"image":"images/I.03.4.0003.jpg",
"description":"Arbeitslosenquote",
"id":"4839",
"thema":"03 Erwerbsleben",
"unterthema":"Arbeitslose ",
"kennzahlenset":"Wohnviertel",
"raeumlicheGliederung":["Wohnviertel"],
"aktualisierungsdatum":"2016-06-30T00:00:00.000",
"schlagwort":["Arbeit","Erwerb"],
"stufe1":"3 Wirtschaft und Arbeit",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"",
"erlaeuterungen":"Anteil als arbeitslos gemeldeter Personen am Total der Erwerbspersonen (16 bis 64 Jahre) in Prozent, jeweils Ende Jahr. Erwerbspersonen aus den Jahren 2010 - 2014, Hochrechnung auf Basis einer Stichprobe von 5 000 Personen pro Jahr. Aufgrund der Grösse wird Bettingen zusammen mit Riehen ausgewertet. Stand: 2015",
"template":"dotplot",
"option":"options001",
"quellenangabe":["Bundesamt für Statistik BFS, Strukturerhebung (SE)","Staatssekretariat für Wirtschaft SECO, Arbeitslosenstatistik"]
}];
