var indikatoren = [{"title":"Anzahl Betreibungen seit 1974",
"subtitle":"",
"kuerzel":"I.06.3.0001",
"kuerzelKunde":"",
"image":"images/I.06.3.0001.jpg",
"description":"Anzahl Betreibungen seit 1974",
"id":"4912",
"thema":"06 Produktion, Handel",
"unterthema":"Betreibungen und Konkurse",
"kennzahlenset":"",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Einkommen","Konsum","Konkurs"],
"stufe1":"",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Seit den 1990er-Jahren hat sich die Anzahl Betreibungen im Kanton Basel-Stadt von 40 000 auf knapp 80 000 Fälle im Jahr verdoppelt.",
"erlaeuterungen":"",
"template":"line001",
"option":"options001",
"quellenangabe":["Beitreibungs- und Konkursamt Basel-Stadt"]
}];
