var indikatoren = [{"title":"Anzahl Leerwohnungen und Leerwohnungsquote nach Wohnflächenkategorie",
"subtitle":"",
"kuerzel":"I.09.4.0005",
"kuerzelKunde":"1.2.f-2",
"image":"images/I.09.4.0005.jpg",
"description":"Anzahl Leerwohnungen und Leerwohnungsquote nach Wohnflächenkategorie",
"id":"4139",
"thema":"09 Bau-, Wohnungswesen",
"unterthema":"Leerstand",
"kennzahlenset":"Wohnraumentwicklung",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Gebäude","Haushalt"],
"stufe1":"1 Gesellschaftspolitik",
"stufe2":"1.2 Wohnraum erhalten und erneuern",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Die höchste Leerwohnungsquote wiesen 2013 Wohnungen mit weniger als 30 Quadratmetern auf. Seit 2014 waren es stets grosse Logis zwischen 100 und 149 oder mit mehr als 150 Quadratmeter.",
"erlaeuterungen":"",
"template":"template001",
"option":"options001",
"quellenangabe":["Bundesamt für Statistik BFS, STATENT","Statistisches Amt Basel-Stadt, Leerstandserhebung"]
}];
