var indikatoren = [{"title":"Umbausaldo nach Art des Umbaus",
"subtitle":"",
"kuerzel":"I.09.1.0005",
"kuerzelKunde":"1.2.c-2",
"image":"images/I.09.1.0005.jpg",
"description":"Umbausaldo nach Art des Umbaus",
"id":"4136",
"thema":"09 Bau-, Wohnungswesen",
"unterthema":"Gebäude und Wohnungen",
"kennzahlenset":"Wohnraumentwicklung",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Gebäude","Haushalt"],
"stufe1":"1 Gesellschaftspolitik",
"stufe2":"1.2 Wohnraum erhalten und erneuern",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Seit 2011 ist der Umbausaldo positiv. Der sprunghafte Anstieg 2014 ist auf die grosse Anzahl Umnutzungen gewerblich genutzter Räume (Büros) zu Wohnungen zurückzuführen. 2015 prägten neben Dachstockausbauten viele Zweckentfremdungen von Wohnungen den Umbausaldo.",
"erlaeuterungen":"",
"template":"template001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Gebäude- und Wohnungsstatistik"]
}];
