var indikatoren = [{"title":"Baujahr Wohngebäude",
"subtitle":"",
"kuerzel":"I.09.1.0009",
"kuerzelKunde":"RU-1",
"image":"images/I.09.1.0009.jpg",
"description":"Baujahr Wohngebäude",
"id":"4830",
"thema":"09 Bau-, Wohnungswesen",
"unterthema":"Gebäude und Wohnungen",
"kennzahlenset":"Wohnviertel",
"raeumlicheGliederung":["Wohnviertel"],
"aktualisierungsdatum":"2016-06-30T00:00:00.000",
"schlagwort":["Gebäude","Alter"],
"stufe1":"2 Raum und Umwelt",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"",
"erlaeuterungen":"Mittleres Baujahr der Wohngebäude des Wohnviertels (ungewichtetes arithmetisches Mittel des Baujahres über alle Wohngebäude). Stand: 2015",
"template":"dotplot",
"option":"options001",
"quellenangabe":["Kantonale Baustatistik"]
}];
