var indikatoren = [{"title":"Anzahl neu erstellte Wohnungen",
"subtitle":"",
"kuerzel":"I.09.1.0026",
"kuerzelKunde":"1.2.e",
"image":"images/I.09.1.0026.jpg",
"description":"Anzahl neu erstellte Wohnungen",
"id":"4137",
"thema":"09 Bau-, Wohnungswesen",
"unterthema":"Gebäude und Wohnungen",
"kennzahlenset":"Wohnraumentwicklung",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Gebäude","Haushalt"],
"stufe1":"1 Gesellschaftspolitik",
"stufe2":"1.2 Wohnraum erhalten und erneuern",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Es werden nur neu erstellte Wohnungen in Neubauten berücksichtigt. Neue Wohnungen aus Umbauten sind demnach nicht enthalten. Dank der Grossprojekte im Gebiet Erlenmatt West wurden im Jahr 2015 an die 800 Wohnungen neu erstellt. Der Zehnjahresdurchschnitt steigt damit auf rund 350.",
"erlaeuterungen":"",
"template":"template001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Gebäude- und Wohnungsstatistik"]
}];
