var indikatoren = [{"title":"Wohnfläche pro Person",
"subtitle":"",
"kuerzel":"I.09.1.0006",
"kuerzelKunde":"1.3.a",
"image":"images/I.09.1.0006.jpg",
"description":"Wohnfläche pro Person",
"id":"4140",
"thema":"09 Bau-, Wohnungswesen",
"unterthema":"Gebäude und Wohnungen",
"kennzahlenset":"Wohnraumentwicklung",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Gebäude","Haushalt"],
"stufe1":"1 Gesellschaftspolitik",
"stufe2":"1.3 Wohnraumnutzung",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Die Wohnfläche pro Kopf nahm von 1980 bis 2010 um sechs Quadratmeter zu. Seither liegt die Zahl bei rund 42 Quadratmetern.",
"erlaeuterungen":"",
"template":"line001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Gebäude- und Wohnungsstatistik"]
}];
