var indikatoren = [{"title":"Motorisierungsgrad: private PW nach Wohnviertel",
"subtitle":"",
"kuerzel":"I.11.1.0040",
"kuerzelKunde":"",
"image":"images/I.11.1.0040.jpg",
"description":"Motorisierungsgrad: private PW nach Wohnviertel",
"id":"4917",
"thema":"11 Verkehr",
"unterthema":"Motorfahrzeuge",
"kennzahlenset":"",
"raeumlicheGliederung":["Wohnviertel","Gemeinde"],
"aktualisierungsdatum":"",
"schlagwort":["Quote","Bevölkerung","Auto"],
"stufe1":"",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"",
"erlaeuterungen":"Der Motorisierungsgrad zeigt die Anzahl privater Personenwagen auf 1000 Einwohner.",
"template":"dotplot",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt; Motorfahrzeugkontrolle Basel-Stadt"]
}];
