var indikatoren = [{"title":"Grundpfandbelastung in Mio. Franken seit 1990",
"subtitle":"",
"kuerzel":"I.12.1.0001",
"kuerzelKunde":"",
"image":"images/I.12.1.0001.jpg",
"description":"Grundpfandbelastung in Mio. Franken seit 1990",
"id":"4919",
"thema":"12 Finanzmärkte",
"unterthema":"Grundpfandbelastung",
"kennzahlenset":"",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Schulden","Boden"],
"stufe1":"",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Seit 1990 hat sich die Summe der Grundpfandverschreibungen von 14 auf 28 Millionen verdoppelt.",
"erlaeuterungen":"Zur Sicherung einer Forderung kann ein Grundstück mit einem Grundpfandrecht verpfändet werden. In Basel-Stadt kann dies in Form eines Schuldbriefs oder einer Grundpfandverschreibung erfolgen.",
"template":"line001",
"option":"options001",
"quellenangabe":["Grundbuch- und Vermessungsamt  Basel-Stadt"]
}];
