var indikatoren = [{"title":"Ausbezahlte Familienmietzinsbeiträge",
"subtitle":"",
"kuerzel":"I.13.2.0003",
"kuerzelKunde":"4.1.b",
"image":"images/I.13.2.0003.jpg",
"description":"Ausbezahlte Familienmietzinsbeiträge",
"id":"4153",
"thema":"13 Soziale Sicherheit",
"unterthema":"Sozialleistungen",
"kennzahlenset":"Wohnraumentwicklung",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Familie"],
"stufe1":"4 Sozialpolitik",
"stufe2":"4.1 Unterstützung Benachteiligter",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Die ausbezahlten Familienmietzinsbeiträge sind seit 2007 stark angestiegen. Der durchschnittliche Beitrag pro Haushalt wuchs in diesem Zeitraum von knapp 3 000 Franken auf rund 4 800 Franken. Seit 2013 verflachte der Anstieg.",
"erlaeuterungen":"",
"template":"line001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, Amt für Sozialbeiträge Basel-Stadt"]
}];
