var indikatoren = [{"title":"Bestand an Notwohnungen und ihre Belegung",
"subtitle":"",
"kuerzel":"I.13.3.0002",
"kuerzelKunde":"4.1.e",
"image":"images/I.13.3.0002.jpg",
"description":"Bestand an Notwohnungen und ihre Belegung",
"id":"4154",
"thema":"13 Soziale Sicherheit",
"unterthema":"Sozialhilfe und Notwohnen",
"kennzahlenset":"Wohnraumentwicklung",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Gebäude","Haushalt"],
"stufe1":"4 Sozialpolitik",
"stufe2":"4.1 Unterstützung Benachteiligter",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Die wenigen Notwohnungen – 2015 machten sie 0,17% des Wohnungsbestandes aus – waren immer zu über 90% belegt. Durch Aufstockungen bestehender Blockrandsiedlungen konnte das Angebot seit 2013 um 50 Logis erhöht werden.",
"erlaeuterungen":"Aufgrund diverser Umbauten (Aufstockungen mit 32 zusätzlichen Notwohnungen) verbunden mit zwischenzeitlichen Umplazierungen liegen für 2014 und 2015 keine vergleichbaren Zahlen für die Belegung vor.",
"template":"template001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, Sozialhilfe Basel"]
}];
