var indikatoren = [{"title":"Sozialhilfequote",
"subtitle":"",
"kuerzel":"I.13.3.0004",
"kuerzelKunde":"GS-1",
"image":"images/I.13.3.0004.jpg",
"description":"Sozialhilfequote",
"id":"4822",
"thema":"13 Soziale Sicherheit",
"unterthema":"Sozialhilfe und Notwohnen",
"kennzahlenset":"Wohnviertel",
"raeumlicheGliederung":["Wohnviertel"],
"aktualisierungsdatum":"2016-06-30T00:00:00.000",
"schlagwort":["Quote"],
"stufe1":"1 Gesellschaft und Soziales",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"",
"erlaeuterungen":"Anteil Sozialhilfeempfänger an der Wohnbevölkerung des Wohnviertels in Prozent. Stand: 2015",
"template":"dotplot",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Sozialhilfestatistik"]
}];
