var indikatoren = [{"title":"Hospitalisierungen und Pflegetage nach Hauptkostenstelle",
"subtitle":"",
"kuerzel":"I.14.1.0006",
"kuerzelKunde":"",
"image":"images/I.14.1.0006.jpg",
"description":"Hospitalisierungen und Pflegetage nach Hauptkostenstelle",
"id":"5010",
"thema":"14 Gesundheit",
"unterthema":"Spitäler",
"kennzahlenset":"",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"2016-11-22T00:00:00.000",
"schlagwort":["Patient"],
"stufe1":"",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"",
"erlaeuterungen":"",
"template":"line001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Gesundheitsstatistik"]
}];
