var indikatoren = [{"title":"Pflegetage in baselstädtischen Spitälern nach Hauptbereich",
"subtitle":"",
"kuerzel":"I.14.1.0003",
"kuerzelKunde":"",
"image":"images/I.14.1.0003.jpg",
"description":"Pflegetage in baselstädtischen Spitälern nach Hauptbereich",
"id":"4948",
"thema":"14 Gesundheit",
"unterthema":"Spitäler",
"kennzahlenset":"",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Spital","Patient"],
"stufe1":"",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Die Anzahl Pflegetage im Hauptbereich Geriatrie gingen von 2008 bis 2014 um über 30% auf 91 000 zurück. In den übrigen Hauptbereichen wurde im selben Zeitraum eine Zunahme der Pflegetage verzeichnet. Das grösste Plus wurde im Bereich Rehabilitation (+20%) registriert.",
"erlaeuterungen":"Gezählt werden stationäre Austritte innerhalb eines Jahres.",
"template":"template001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Gesundheitsstatistik","Bundesamt für Statistik BFS, medizinische Statistik der Krankenhäuser"]
}];
