var indikatoren = [{"title":"Hospitalisierungen in baselstädtischen Spitälern nach Hauptbereich",
"subtitle":"",
"kuerzel":"I.14.1.0002",
"kuerzelKunde":"",
"image":"images/I.14.1.0002.jpg",
"description":"Hospitalisierungen in baselstädtischen Spitälern nach Hauptbereich",
"id":"4947",
"thema":"14 Gesundheit",
"unterthema":"Spitäler",
"kennzahlenset":"",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Spital","Patient"],
"stufe1":"",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Die akutsomatischen Fälle in baselstädtischen Spitälern nahmen von 2008 bis 2014 um 15% auf 63 000 zu. Mit einer Zunahme von 32% verzeichnete der Hauptbereicih Rehabilitation die grösste Veränderung im Beobachtungszeitraum.",
"erlaeuterungen":"Gezählt werden stationäre Austritte innerhalb eines Jahres.",
"template":"template001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Gesundheitsstatistik","Bundesamt für Statistik BFS, medizinische Statistik der Krankenhäuser"]
}];
