var indikatoren = [{"title":"Gymnasialquote nach Staatsangehörigkeit seit 2006",
"subtitle":"",
"kuerzel":"I.15.6.0001",
"kuerzelKunde":"3-1",
"image":"images/I.15.6.0001.jpg",
"description":"Gymnasialquote nach Staatsangehörigkeit seit 2006",
"id":"4739",
"thema":"15 Bildung",
"unterthema":"Bildungsniveau",
"kennzahlenset":"Integration kompakt",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Ausländer","Quote","Ausland","Staatsangehörigkeit","Bildung","Gymnasium","Gymnasialquote","Schule"],
"stufe1":"3 Bildung und Erwerbstätigkeit",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Mit Ausnahme von 2014 liegt die Gymnasialquote der Schweizer mindestens doppelt so hoch wie diejenige der Ausländer; tendenziell nähern sich die beiden Quoten allerdings an. Die Quote der Schüler mit deutscher Staatsbürgerschaft liegt deutlich höher als diejenige der Schweizer. Der Abstand verringerte sich seit 2014 allerdings deutlich. Die übrigen Staatsangehörigkeiten, deren Schülerzahl eine noch aussagekräftige Berechnungsbasis bildet, folgen mit grossem Abstand nach Deutschland und der Schweiz.",
"erlaeuterungen":"Die Gymnasialquote weist den Anteil Gymnasiasten an allen Schülern des 8. und 9. Schuljahres (nach HarmoS-Zählweise der Stufen 10 und 11) aus. Es werden nur Jugendliche berücksichtigt, deren Eltern im Kanton Basel-Stadt wohnen. Für einzelne Ländergruppen konnte aufgrund zu kleiner Fallzahlen keine Gymnasialquote errechnet werden. Jährliche Schwankungen (Bsp. Spanien) können zum Teil ebenfalls damit begründet werden.",
"template":"line001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, Bildungsstatistik"]
}];
