var indikatoren = [{"title":"Einkommenssteuer pro Veranlagung",
"subtitle":"",
"kuerzel":"I.18.2.0003",
"kuerzelKunde":"WA-2",
"image":"images/I.18.2.0003.jpg",
"description":"Einkommenssteuer pro Veranlagung",
"id":"4836",
"thema":"18 Öffentliche Finanzen",
"unterthema":"Steuern",
"kennzahlenset":"Wohnviertel",
"raeumlicheGliederung":["Wohnviertel"],
"aktualisierungsdatum":"2016-06-30T00:00:00.000",
"schlagwort":["Bevölkerung"],
"stufe1":"3 Wirtschaft und Arbeit",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"",
"erlaeuterungen":"Mittlere Einkommenssteuer der steuerpflichtigen Personen im Wohnviertel (ordentliche Veranlagungen, totaler Steuerertrag geteilt durch die Anzahl Veranlagungen) in Franken. Stand: Steuerjahr 2013",
"template":"dotplot",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Steuerstatistik"]
}];
