var indikatoren = [{"title":"Anzahl Anzeigen, die das Strafgesetzbuch (StGB) betreffen, pro 1000 Einwohner im Alter von 18 und mehr Jahren",
"subtitle":"",
"kuerzel":"I.19.1.0001",
"kuerzelKunde":"3.2.01",
"image":"images/I.19.1.0001.jpg",
"description":"Anzahl Anzeigen, die das Strafgesetzbuch (StGB) betreffen, pro 1000 Einwohner im Alter von 18 und mehr Jahren",
"id":"4866",
"thema":"19 Rechtspflege",
"unterthema":"Polizei",
"kennzahlenset":"Gesellschaftlicher Zusammenhalt",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Verbrechen"],
"stufe1":"3 Gemeinwohlorientierung",
"stufe2":"3.2 Anerkennung sozialer Regeln",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Die Zahl der angezeigten Straftaten pro 1000 Einwohner ab 18 Jahren war von 2008 bis 2010 relativ stabil, sie bewegte sich zwischen 121,2 und 125,3. Danach stieg die Quote und erreichte 2012 163,5. Die beiden letzten Jahre zeigen nun wieder einen Rückgang der Anzahl Straftaten pro 1000 Einwohner.",
"erlaeuterungen":"",
"template":"template001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Bevölkerungsstatistik","Bundesamt für Statistik BFS, Polizeiliche Kriminalstatistik (PKS)"]
}];
