var indikatoren = [{"title":"Beurteilung des Wohnquartiers",
"subtitle":"«Wie gerne leben Sie in Ihrem Wohnquartier?»",
"kuerzel":"I.50.1.0017",
"kuerzelKunde":"2.1.02",
"image":"images/I.50.1.0017.jpg",
"description":"Beurteilung des Wohnquartiers",
"id":"4721",
"thema":"50 Befragungen",
"unterthema":"Bevölkerungsbefragung",
"kennzahlenset":"Gesellschaftlicher Zusammenhalt",
"raeumlicheGliederung":["Gemeinde"],
"aktualisierungsdatum":"",
"schlagwort":["Zufriedenheit","Niederlassung","Nachbarschaft","Beurteilung"],
"stufe1":"2 Verbundenheit",
"stufe2":"2.1 Identifikation",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Mit einem Anteil von 96,9% wohnten 2015 mehr Leute sehr oder eher gerne in ihrem Wohnquartier als 2011 (94,8%). Am tiefsten lag die insgesamte Zustimmung (eher und sehr gerne) 2005 mit 91%.",
"erlaeuterungen":"Gefragt wurden nur Personen, die in der Stadt Basel wohnen.",
"template":"befragungenProzent001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung: F2b"]
}];
