var indikatoren = [{"title":"Zufriedenheit mit Einrichtungen und Angeboten für behinderte Menschen",
"subtitle":"«Wie zufrieden sind Sie mit den Einrichtungen und Angeboten für behinderte Menschen?»",
"kuerzel":"I.50.1.0009",
"kuerzelKunde":"4.2.a",
"image":"images/I.50.1.0009.jpg",
"description":"Zufriedenheit mit Einrichtungen und Angeboten für behinderte Menschen",
"id":"4155",
"thema":"50 Befragungen",
"unterthema":"Bevölkerungsbefragung",
"kennzahlenset":"Wohnraumentwicklung",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Zufriedenheit"],
"stufe1":"4 Sozialpolitik",
"stufe2":"4.2 Wohnraum für Betagte und Behinderte",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Fast 60% der Befragten sind 2015 mit den Einrichtungen und dem Angebot für Behinderte eher bis sehr zufrieden. Dieser Wert lag 2007 noch bei 40%.",
"erlaeuterungen":"",
"template":"befragungen001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung: F6_19"]
}];
