var indikatoren = [{"title":"Engagement in Organisationen und Vereinen",
"subtitle":"«Engagierst Du Dich in einer Organisation, in einem Verein oder ähnlichem?»",
"kuerzel":"I.50.3.0002",
"kuerzelKunde":"3.3.01",
"image":"images/I.50.3.0002.jpg",
"description":"Engagement in Organisationen und Vereinen",
"id":"4870",
"thema":"50 Befragungen",
"unterthema":"Jugendbefragung",
"kennzahlenset":"Gesellschaftlicher Zusammenhalt",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Jugend"],
"stufe1":"3 Gemeinwohlorientierung",
"stufe2":"3.3 Gesellschaftliche Teilhabe",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"2013 gaben ein Viertel der Befragten Jugendlichen an, dass sie sich in einer Organisation, in einem Verein oder ähnlichem engagieren, 2011 lag dieser Wert noch bei 12,0%.",
"erlaeuterungen":"",
"template":"befragungenProzent001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Jugendbefragung: F28"]
}];
