var indikatoren = [{"title":"Zufriedenheit mit dem Austausch mit der Nachbarschaft",
"subtitle":"«Wie zufrieden sind Sie am aktuellen Wohnort mit dem Austausch mit den Nachbarn?»",
"kuerzel":"I.50.4.0005",
"kuerzelKunde":"1.1.06",
"image":"images/I.50.4.0005.jpg",
"description":"Zufriedenheit mit dem Austausch mit der Nachbarschaft",
"id":"4851",
"thema":"50 Befragungen",
"unterthema":"Befragung 55 plus",
"kennzahlenset":"Gesellschaftlicher Zusammenhalt",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Zufriedenheit","Nachbarschaft"],
"stufe1":"1 Soziale Beziehungen",
"stufe2":"1.1 Soziale Netze",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"2011 waren 85,3% der Befragten zufrieden mit dem Austausch mit den Nachbarn, 2015 betrug die Zufriedenheit 87,8%, wobei der Anteil sehr zufriedener Personen im Vergleich zu 2011 um 4,2 Prozentpunkte höher lag. Gleichzeitig reduzierte sich der Anteil derjenigen Personen, die keine Antwort geben konnten oder wollten, von 2011 auf 2015 um 2,5 Prozentpunkte.",
"erlaeuterungen":"Gefragt wurde: «Wie zufrieden sind Sie am aktuellen Wohnort mit dem Austausch mit den Nachbarn?»",
"template":"befragungenProzent001",
"option":"options001",
"quellenangabe":["Statistisches Amt Basel-Stadt, kantonale Befragung 55plus: F10f"]
}];
