var indikatoren = [{"title":"Entwicklung der besucherstärksten Messen in der Stadt Basel",
"subtitle":"",
"kuerzel":"Test_LP.1.02.2",
"kuerzelKunde":"",
"image":"images/doesntmatter.jpg",
"description":"Beschreibung: Entwicklung der besucherstärksten Messen in der Stadt Basel",
"id":"dontknowyet",
"thema":"04 Volkswirtschaft",
"unterthema":"Test",
"kennzahlenset":"Test",
"raeumlicheGliederung":["Schweiz", "Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Heimat","Ausländer","Quote","Bevölkerung","Ausland"],
"stufe1":"1 Struktur der Bevölkerung",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Blabla",
"erlaeuterungen":"Blablabla test",
"template":"template001",
"option":"options001",
"quellenangabe":["Test Quelle"]
}];
