var indikatoren = [{"title":"Wachstum des realen BIP BS in % gegenüber Vorjahr im Vergleich mit ZH, GE, CH",
"subtitle":"",
"kuerzel":"Test_LP.1.03.2",
"kuerzelKunde":"Test_LP.1.03.2",
"image":"images/doesntmatter.jpg",
"description":"Wachstum des realen BIP BS in % gegenüber Vorjahr im Vergleich mit ZH, GE, CH",
"id":"dontknowyet",
"thema":"04 Volkswirtschaft",
"unterthema":"Test",
"kennzahlenset":"Test",
"raeumlicheGliederung":["Schweiz", "Kanton"],
"aktualisierungsdatum":"",
"schlagwort":["Heimat","Ausländer","Quote","Bevölkerung","Ausland"],
"stufe1":"1 Struktur der Bevölkerung",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Blabla",
"erlaeuterungen":"Blablabla test",
"template":"line001",
"option":"options001",
"quellenangabe":["Test Quelle"]
}];
