var indikatorensetData = [
	{
		"template": "map_gemeinden_print",
		"data-id": 8095,
		"chart-id": 8095,
		"filter": "",
		"parentId": "7952",
		"children": [],
		"title": "Perimeter der trinationalen Agglomeration Basel",
		"subtitle": "",
		"lesehilfe": "Die trinationale Agglomeration Basel umfasst 203 Gemeinden. Sie besteht aus der Kernstadt Basel, 106 weiteren Gemeinden in der Schweiz, 24 in Deutschland und 72 in Frankreich.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Perimeter der trinationalen Agglomeration Basel",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08095",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "1.1",
		"stufe1": "1. Einführung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_001",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:09:06",
		"id": 8095
	},
	{
		"template": "template001_print",
		"data-id": 8096,
		"chart-id": 8096,
		"filter": "",
		"parentId": "7953",
		"children": [],
		"title": "Gesamtbevölkerung",
		"subtitle": "2021",
		"lesehilfe": "Die trinationale Agglomeration Basel zählt 2021 rund 867 400 Einwohnerinnen und Einwohner und ist damit die drittgrösste Agglomeration der Schweiz, nach Zürich und Genf (grenzüberschreitend). Ein Fünftel der Bevölkerung wohnt in der Kernstadt Basel, 44% in den weiteren Schweizer Gemeinden, 25% in Deutschland und 11% in Frankreich. Der Anteil der in der Kernstadt wohnenden Bevölkerung ist in Basel (20%) sowie in Genf (22%) kleiner als in Zürich (30%), Bern oder Lausanne (je 32%).",
		"erlaeuterungen": "Hier ist die ständige Wohnbevölkerung dargestellt. Die Agglomerationen sind gemäss Typologie «Raum mit städtischem Charakter 2012» des BFS definiert. Eine Agglomeration besteht aus einer Kernstadt und den übrigen Agglomerationsgemeinden. Die Agglomerationen Basel und Genf sind grenzüberschreitend.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Gesamtbevölkerung",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08096",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "2.1",
		"stufe1": "2. Bevölkerungsstruktur",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:09:12",
		"id": 8096
	},
	{
		"template": "map_gemeinden_print",
		"data-id": 8097,
		"chart-id": 8097,
		"filter": "",
		"parentId": "7954",
		"children": [],
		"title": "Bevölkerungsdichte nach Gemeinde",
		"subtitle": "trinationale Agglomeration Basel, 2021",
		"lesehilfe": "Mit 7 290 Einwohnerinnen und Einwohnern pro Quadratkilometer ist die Kernstadt Basel die Gemeinde mit der höchsten Bevölkerungsdichte. In den Agglomerationsteilen zeigen folgende Gemeinden die höchste Bevölkerungsdichte: Birsfelden (4 142) in der Schweiz; Huningue (2 372) in Frankreich; Weil am Rhein (1 542) in Deutschland.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Bevölkerungsdichte nach Gemeinde",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08097",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "2.3",
		"stufe1": "2. Bevölkerungsstruktur",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_004",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:09:17",
		"id": 8097
	},
	{
		"template": "template001_print",
		"data-id": 8098,
		"chart-id": 8098,
		"filter": "",
		"parentId": "7955",
		"children": [],
		"title": "Jugendquotient",
		"subtitle": "2021",
		"lesehilfe": "Die Anzahl Jugendlicher unter 20 Jahren pro 100 Personen im Alter von 20 bis 64 Jahren ist in den Kernstädten tiefer als in den jeweiligen weiteren Agglomerationsgemeinden. Der Jugendquotient ist vor allem im französischen Teil der Agglomerationen Basel (38,9) und Genf (43,2) hoch. In der gesamten Agglomeration ist der Jugendquotient in Genf am höchsten.",
		"erlaeuterungen": "Der Jugendquotient beschreibt das Verhältnis der Personen im Alter von 19 oder weniger Jahren zu jenen im erwerbsfähigen Alter zwischen 20 und 64 Jahren. Das Verhältnis wird pro 100 Personen zwischen 20 und 64 Jahren ausgewiesen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Jugendquotient",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08098",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "2.4",
		"stufe1": "2. Bevölkerungsstruktur",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:09:18",
		"id": 8098
	},
	{
		"template": "template001_print",
		"data-id": 8100,
		"chart-id": 8100,
		"filter": "",
		"parentId": "7957",
		"children": [],
		"title": "Altersquotient",
		"subtitle": "2021",
		"lesehilfe": "Die Bevölkerung der Agglomeration Basel ist vergleichsweise alt: Der Altersquotient ist mit 34,6 im Jahr 2021 deutlich höher als in den Agglomerationen Genf, Lausanne oder Zürich. Dies ist auf die relativ ältere Bevölkerung in allen Teilen der Agglomeration zurückzuführen. Nach Basel weist die Agglomeration Bern den höchsten Altersquotienten auf (34,0).",
		"erlaeuterungen": "Der Altersquotient beschreibt das Verhältnis der Personen im Alter von 65 oder mehr Jahren zu jenen im erwerbsfähigen Alter zwischen 20 und 64 Jahren. Das Verhältnis wird pro 100 Personen zwischen 20 und 64 Jahren ausgewiesen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Altersquotient",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08100",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "2.5",
		"stufe1": "2. Bevölkerungsstruktur",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:09:26",
		"id": 8100
	},
	{
		"template": "template001_print",
		"data-id": 8101,
		"chart-id": 8101,
		"filter": "",
		"parentId": "7958",
		"children": [],
		"title": "Ausländeranteil",
		"subtitle": "2021",
		"lesehilfe": "Den grössten Ausländeranteil weist die Kernstadt Genf (48,3%) auf. Ausländeranteile von nur gerade rund 16% werden hingegen in den Agglomerationsgemeinden (ohne Kernstadt) von Bern sowie in den deutschen und französischen Gemeinden der Agglomeration Basel registriert. Als gesamte Agglomeration betrachtet haben nur Lausanne und Genf einen Ausländeranteil von über 30%, in Basel liegt der Anteil bei 23,8%.",
		"erlaeuterungen": "Anteil der ständigen ausländischen Wohnbevölkerung an der gesamten ständigen Wohnbevölkerung in Prozent.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Ausländeranteil",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08101",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "2.7",
		"stufe1": "2. Bevölkerungsstruktur",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:09:30",
		"id": 8101
	},
	{
		"template": "template001_print",
		"data-id": 8102,
		"chart-id": 8102,
		"filter": "",
		"parentId": "7959",
		"children": [],
		"title": "Geburten und Sterbefälle",
		"subtitle": "Saldo (pro 1000 Einwohner), 2021",
		"lesehilfe": "Der Saldo aus Geburten und Sterbefällen pro 1000 Einwohner ist 2021 in Basel leicht negativ (-0,2), während dieser in Bern, Genf, Lausanne und auch in Zürich positiv ausfällt. Für den tiefen Wert in der Agglomeration Basel sind insbesondere die Gemeinden in Deutschland (Saldo -1,9) verantwortlich. In den französischen Gemeinden liegt der Saldo bei 1,2. Am grössten ist der Saldo im französischen Teil der Agglomeration Genf (6,6).",
		"erlaeuterungen": "Der ausgewiesene Saldo ergibt sich aus der Differenz von Geburten und Sterbefällen jeweils pro 1000 Einwohner.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Geburten und Sterbefälle",
		"thema": "01 Bevölkerung",
		"unterthema": "Geburten und Todesfälle",
		"kuerzel": "I.01.3.08102",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "2.8",
		"stufe1": "2. Bevölkerungsstruktur",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:09:33",
		"id": 8102
	},
	{
		"template": "template001_print",
		"data-id": 8104,
		"chart-id": 8104,
		"filter": "",
		"parentId": "7961",
		"children": [],
		"title": "Anteil der Privathaushalte mit minderjährigen Kindern",
		"subtitle": "2021",
		"lesehilfe": "Der Anteil der Privathaushalte mit Kindern unter 18 Jahren beträgt in der Agglomeration Basel 25,1%. Über alle Agglomerationen verglichen, ist deren Anteil in den deutschen Gemeinden der Agglomeration Basel mit 34,3% am höchsten. In jeder Agglomeration ist der Anteil der Privathaushalte mit minderjährigen Kindern in der Kernstadt kleiner als in den jeweiligen übrigen Agglomerationsgemeinden.",
		"erlaeuterungen": "Privathaushalte sind alle Haushalte ausser Kollektivhaushalte (z. B. Alters- und Pflegeheime).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Anteil der Privathaushalte mit minderjährigen Kindern",
		"thema": "01 Bevölkerung",
		"unterthema": "Haushalte",
		"kuerzel": "I.01.2.08104",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "3.1",
		"stufe1": "3. Familienhaushalte und Bildung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:09:33",
		"id": 8104
	},
	{
		"template": "template001_print",
		"data-id": 8105,
		"chart-id": 8105,
		"filter": "",
		"parentId": "7962",
		"children": [],
		"title": "Anteil der privaten Einelternhaushalte",
		"subtitle": "mit Kindern unter 18 Jahren, 2021",
		"lesehilfe": "Der Anteil der Einelternhaushalte mit Kindern am Total der privaten Haushalte variiert 2021 zwischen 2,6% in der Agglomeration Bern und 5,2% in Genf. In den französischen Gemeinden der Agglomeration Genf liegt er bei 6,2%. In der Agglomeration Basel haben 3,5% der Haushalte alleinerziehende Eltern, wobei dieser Anteil in den französischen und in den deutschen Agglomerationsgemeinden grösser ist als im Schweizer Teil der Agglomeration.",
		"erlaeuterungen": "Privathaushalte sind alle Haushalte ausser Kollektivhaushalte (z. B. Alters- und Pflegeheime).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Anteil der privaten Einelternhaushalte",
		"thema": "01 Bevölkerung",
		"unterthema": "Haushalte",
		"kuerzel": "I.01.2.08105",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "3.2",
		"stufe1": "3. Familienhaushalte und Bildung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:09:42",
		"id": 8105
	},
	{
		"template": "befragungen001_print",
		"data-id": 8106,
		"chart-id": 8106,
		"filter": "",
		"parentId": "7963",
		"children": [],
		"title": "Bildungsniveau der Bevölkerung",
		"subtitle": "nach höchster abgeschlossener Ausbildung, 2021",
		"lesehilfe": "In der Agglomeration Basel weisen 42,8% der Bevölkerung zwischen 25 und 64 Jahren im Jahr 2021 als höchste abgeschlossene Ausbildung einen Sekundarstufe II-Abschluss auf. Am höchsten ist der Anteil der Sekundarstufe II-Abschlüsse in den Agglomerationsgemeinden von Deutschland (53,9%). Der Anteil der Bevölkerung mit tertiärer Ausbildung ist in der Agglomeration Basel (42,7%) tiefer als in den Vergleichsagglomerationen.",
		"erlaeuterungen": "Bevölkerung (25- bis 64-jährig) ohne nachobligatorische Ausbildung (ISCED Stufen 1 oder 2), mit Sekundarstufe II (ISCED Stufen 3 oder 4) oder mit tertiärer Ausbildung (ISCED Stufen 5 bis 8) als höchstem Bildungsabschluss.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Bildungsniveau der Bevölkerung",
		"thema": "15 Bildung",
		"unterthema": "Bildungsniveau",
		"kuerzel": "I.15.6.08106",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "3.4",
		"stufe1": "3. Familienhaushalte und Bildung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_013",
		"darstellungsart": "Diagramm",
		"printformat": "large",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:09:46",
		"id": 8106
	},
	{
		"template": "template001_print",
		"data-id": 8108,
		"chart-id": 8108,
		"filter": "",
		"parentId": "7965",
		"children": [],
		"title": "Nettoerwerbsquote der 15- bis 64-Jährigen",
		"subtitle": "2021",
		"lesehilfe": "Die Nettoerwerbsquote in der Agglomeration Basel liegt 2021 bei 77,7%. Am höchsten ist die Erwerbsquote in den Agglomerationen Bern (83,2%) und Zürich (82,3%). Es gibt allgemein nur kleine Unterschiede zwischen Kernstadt und Rest der Agglomeration, ausser in Genf, wo die Erwerbsquote im französischen Teil der Agglomeration höher als in der Kernstadt ist.",
		"erlaeuterungen": "Die Nettoerwerbsquote enspricht der Anzahl Erwerbspersonen geteilt durch die 15- bis 64-jährige Bevölkerung, in Prozent. Die Erwerbspersonen sind die Summe der Erwerbstätigen und der Erwerbslosen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Nettoerwerbsquote der 15- bis 64-Jährigen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.08108",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "4.1",
		"stufe1": "4. Arbeitsmarkt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_014",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:09:55",
		"id": 8108
	},
	{
		"template": "template001_print",
		"data-id": 8109,
		"chart-id": 8109,
		"filter": "",
		"parentId": "7966",
		"children": [],
		"title": "Erwerbstätige im Alter von 20 bis 64 Jahren",
		"subtitle": "2021",
		"lesehilfe": "Rund 397 000 Einwohnerinnen und Einwohner der Agglomeration Basel im Alter von 20 bis 64 Jahren sind erwerbstätig, fast so viele wie in der Agglomeration Genf. Davon wohnen 36% im ausländischen Teil der Agglomeration Basel (Genf  40%). Lediglich rund ein Fünftel der Erwerbstätigen der Agglomerationen Basel und Genf wohnt in der Kernstadt, während dieser Anteil in den Agglomerationen Bern, Lausanne und Zürich zwischen 32% und 34% liegt.",
		"erlaeuterungen": "Als Erwerbstätige werden Personen definiert, die eine entlohnte Berufstätigkeit ausüben (selbständig oder angestellt). Sie werden am Wohnort (nicht am Arbeitsort) erfasst.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Erwerbstätige im Alter von 20 bis 64 Jahren",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.08109",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "4.2",
		"stufe1": "4. Arbeitsmarkt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_015",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:09:56",
		"id": 8109
	},
	{
		"template": "template001_print",
		"data-id": 8110,
		"chart-id": 8110,
		"filter": "",
		"parentId": "7967",
		"children": [],
		"title": "Erwerbstätigenquote der 20- bis 64-Jährigen",
		"subtitle": "2021",
		"lesehilfe": "Von den Einwohnerinnen und Einwohnern im Alter von 20 bis 64 Jahren sind in der Agglomeration Basel rund 78% erwerbstätig. Im Schweizer Agglomerationsgürtel und in den deutschen Gemeinden ist die Quote höher als in der Kernstadt und in den französischen Agglomerationsgemeinden. Die Erwerbstätigenquote in der Agglomeration Basel ist höher als in Genf und Lausanne, aber tiefer als in Bern und Zürich.",
		"erlaeuterungen": "Anteil der Erwerbstätigen an der ständigen Wohnbevölkerung von 20 bis 64 Jahren.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Erwerbstätigenquote der 20- bis 64-Jährigen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.08110",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "4.3",
		"stufe1": "4. Arbeitsmarkt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_016",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:09:59",
		"id": 8110
	},
	{
		"template": "befragungen001_print",
		"data-id": 8111,
		"chart-id": 8111,
		"filter": "",
		"parentId": "7968",
		"children": [],
		"title": "Beschäftigte nach Wirtschaftssektor",
		"subtitle": "2021",
		"lesehilfe": "Der Anteil des sekundären Sektors am Total der Beschäftigten ist in der Agglomeration Basel mit 24,7% deutlich höher als in den Vergleichsagglomerationen. Am wichtigsten ist der sekundäre Sektor im deutschen Teil der Agglomeration Basel (35,4%), aber auch in der Kernstadt ist dieser Sektor überdurchschnittlich vertreten (18,4%), was für eine Stadt aussergewöhnlich ist. Der hohe Anteil des sekundären Sektors in Basel ist auf die wichtige Rolle der pharmazeutischen Industrie zurückzuführen.",
		"erlaeuterungen": "Der 1. Sektor beinhaltet die Land- und Forstwirtschaft. Der 2. Sektor ist das Aggregat von verarbeitendem Gewerbe, Energie- und Wasserversorgung sowie Baugewerbe. Der 3. Sektor fasst alle Dienstleistungen zusammen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Beschäftigte nach Wirtschaftssektor",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08111",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "4.7",
		"stufe1": "4. Arbeitsmarkt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_020",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:10:12",
		"id": 8111
	},
	{
		"template": "template001_print",
		"data-id": 8112,
		"chart-id": 8112,
		"filter": "",
		"parentId": "7969",
		"children": [],
		"title": "Beschäftigtendichte",
		"subtitle": "Beschäftigte pro Einwohner, 2021",
		"lesehilfe": "Die Beschäftigtendichte, auch als Arbeitsstellendichte bezeichnet, ist in den Kernstädten am höchsten: Die Städte Bern (1,4), Zürich (1,2) und Basel (1,1) weisen mehr als eine Arbeitsstelle pro Einwohnerin oder Einwohner auf. In den Städten Genf und Lausanne ist der Wert leicht tiefer (0,9). In den französischen bzw. deutschen Teilen der Agglomerationen Genf und Basel ist die Beschäftigtendichte am tiefsten.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Beschäftigtendichte",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08112",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "4.6",
		"stufe1": "4. Arbeitsmarkt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_019",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:10:11",
		"id": 8112
	},
	{
		"template": "template001_print",
		"data-id": 8113,
		"chart-id": 8113,
		"filter": "",
		"parentId": "7970",
		"children": [],
		"title": "Personenwagen",
		"subtitle": "pro 1000 Einwohner, 2021",
		"lesehilfe": "2021 sind in der Agglomeration Basel 516 Personenwagen pro 1000 Einwohner registriert. Nur in Genf ist der Wert so hoch. Es sind deutliche Unterschiede zwischen den Agglomerationsteilen zu beobachten: Die Stadt Basel (319) weist den tiefsten Wert aller Kernstädte aus. Deutlich höher ist er in den deutschen (600) und in den französischen (654) Gemeinden der Agglomeration Basel. Auch in der Agglomeration Genf ist der Motorisierungsgrad im französischen Teil höher als in den Schweizer Gemeinden.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Personenwagen",
		"thema": "11 Verkehr",
		"unterthema": "Motorfahrzeuge",
		"kuerzel": "I.11.1.08113",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "5.1",
		"stufe1": "5. Verkehr und Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_021",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:10:19",
		"id": 8113
	},
	{
		"template": "template001_print",
		"data-id": 8114,
		"chart-id": 8114,
		"filter": "",
		"parentId": "7971",
		"children": [],
		"title": "Hotelübernachtungen",
		"subtitle": "pro Einwohner, 2021",
		"lesehilfe": "Im Jahr 2021 waren die Übernachtungszahlen in allen Agglomerationen leicht höher als 2020, aber immer noch deutlich tiefer als in den Jahren vor der Pandemie. Am meisten Hotelübernachtungen pro Einwohner werden 2021 in der Kernstadt Genf (5,4) registriert. In der Agglomeration Basel zeigen die Kernstadt (4,5 Hotelübernachtungen pro Einwohner) und die deutschen Gemeinden (2,7) eine höhere touristische Attraktivität als die übrige Agglomeration.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Hotelübernachtungen",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "5.2",
		"stufe1": "5. Verkehr und Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_022",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-21T06:57:40",
		"id": 8114
	},
	{
		"template": "template001_print",
		"data-id": 8115,
		"chart-id": 8115,
		"filter": "",
		"parentId": "7993",
		"children": [],
		"title": "Beschäftigte",
		"subtitle": "2021",
		"lesehilfe": "In der trinationalen Agglomeration Basel sind 2021 insgesamt rund 471 000 Beschäftigte tätig. Fast 79% davon arbeiten in der Schweiz (je zur Hälfte in der Kernstadt und in den übrigen Gemeinden), rund 15% im deutschen Teil der Agglomeration und 6% im französischen Teil. Die Beschäftigtenzahl in der Agglomeration Basel ist geringfügig tiefer als in Genf.",
		"erlaeuterungen": "Der Begriff Beschäftigte bezeichnet die Anzahl der besetzten Stellen. Die Erfassung erfolgt am Arbeitsort.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beschäftigte",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08115",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "4.4",
		"stufe1": "4. Arbeitsmarkt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_017",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:10:05",
		"id": 8115
	},
	{
		"template": "template001_print",
		"data-id": 9203,
		"chart-id": 9203,
		"filter": "",
		"parentId": "9192",
		"children": [],
		"title": "Gesamtbevölkerung und Frauenanteil",
		"subtitle": "2021",
		"lesehilfe": "Gemessen an der Gesamtbevölkerung haben Basel (trinational) und die anderen Schweizer Agglomerationen deutlich weniger Einwohnerinnen und Einwohner als die europäischen Metropolen Paris, Madrid, Barcelona oder Mailand. Vergleichbar mit Basel (867 400 Personen) sind die Agglomerationen Genf (grenzüberschreitend), Karlsruhe, Strassburg und Bologna. Der Frauenanteil liegt in fast allen Vergleichsagglomerationen zwischen 50% und 52%.",
		"erlaeuterungen": "Hier ist die ständige Wohnbevölkerung in den Agglomerationen dargestellt. Unterschiedlicher Datenstand (französischer Agglomerationen: 2020).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics",
			"Eurostat"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Gesamtbevölkerung und Frauenanteil",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.09203",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "6.1",
		"stufe1": "6. Internationaler Vergleich",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_024",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:10:33",
		"id": 9203
	},
	{
		"template": "template001_print",
		"data-id": 9204,
		"chart-id": 9204,
		"filter": "",
		"parentId": "9193",
		"children": [],
		"title": "Jugend- und Altersquotient",
		"subtitle": "2021",
		"lesehilfe": "Die Altersstruktur der Basler Bevölkerung ist, mit einem Jugendquotienten von 32,3 und einem Altersquotienten von 34,6, vergleichbar mit Bern, den deutschen Agglomerationen und Porto. In den französischen Agglomerationen ist die Bevölkerung jünger, mit einem Jugendquotienten von 40 oder mehr (ausser in Metz). Die italienischen Agglomerationen und Lissabon zeigen im Gegensatz dazu einen hohen Altersquotienten.",
		"erlaeuterungen": "Jugendquotient: Der Jugendquotient beschreibt das Verhältnis der Personen im Alter von 19 oder weniger Jahren zu jenen im erwerbsfähigen Alter zwischen 20 und 64 Jahren. Das Verhältnis wird pro 100 Personen zwischen 20 und 64 Jahren ausgewiesen. Altersquotient: Der Altersquotient beschreibt das Verhältnis der Personen im Alter von 65 oder mehr Jahren zu jenen im erwerbsfähigen Alter zwischen 20 und 64 Jahren. Das Verhältnis wird pro 100 Personen zwischen 20 und 64 Jahren ausgewiesen. Hier sind die Agglomerationen dargestellt. Unterschiedlicher Datenstand (zwischen 2018 und 2021).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics",
			"Eurostat"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Jugend- und Altersquotient",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.09204",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "6.2",
		"stufe1": "6. Internationaler Vergleich",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_025",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:10:36",
		"id": 9204
	},
	{
		"template": "template001_print",
		"data-id": 9205,
		"chart-id": 9205,
		"filter": "",
		"parentId": "9194",
		"children": [],
		"title": "Geburten- und Sterberate",
		"subtitle": "Fälle pro 1000 Einwohner, 2021",
		"lesehilfe": "Die französischen Agglomerationen Lille, Lyon und Paris verzeichnen die höchsten Geburtenraten und dabei tiefe Sterberaten. Das führt zu einem hohen Geburtenüberschuss. Ein ähnliches Bild zeigen die Agglomerationen Genf, Lausanne und Zürich. In den italienischen, portugiesischen und spanischen Agglomerationen gibt es hingegen mehr Sterbefälle als Geburten. In Basel sowie in Frankfurt und Metz gibt es ähnlich viel Geburte wie Todesfälle.",
		"erlaeuterungen": "Anzahl Geburten bzw. Sterbefälle pro 1000 Einwohner. Hier sind die Agglomerationen dargestellt. Unterschiedlicher Datenstand (zwischen 2020 und 2021).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics",
			"Eurostat"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Geburten- und Sterberate",
		"thema": "01 Bevölkerung",
		"unterthema": "Geburten und Todesfälle",
		"kuerzel": "I.01.3.09205",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "6.3",
		"stufe1": "6. Internationaler Vergleich",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_026",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:10:37",
		"id": 9205
	},
	{
		"template": "template001_print",
		"data-id": 9206,
		"chart-id": 9206,
		"filter": "",
		"parentId": "9195",
		"children": [],
		"title": "Bildungsniveau der Bevölkerung",
		"subtitle": "nach höchster abgeschlossener Ausbildung, 2021",
		"lesehilfe": "Die Bevölkerung von 25 bis 64 Jahren weist in den deutschen Agglomerationen Frankfurt, Freiburg und Karlsruhe sowie in Mailand einen Sekundarstufe II-Anteil von über 44% auf. In der grenzüberschreitenden Agglomeration Basel ist dieser Anteil mit 43% ebenfalls relativ hoch. Der Anteil der Bevölkerung mit tertiärer Ausbildung ist in vielen Agglomerationen grösser als 40%, in den italienischen und portugiesischen Agglomerationen allerdings deutlich tiefer. Ein hoher Bevölkerungsanteil ohne nachobligatorische Ausbildung fällt bei den portugiesischen Agglomerationen auf.",
		"erlaeuterungen": "Bevölkerung (25- bis 64-jährig) ohne nachobligatorische Ausbildung (ISCED Stufe 1 oder 2), mit Diplom auf Sekundarstufe II (ISCED Stufe 3 oder 4) oder mit tertiärer Ausbildung (ISCED Stufen 5 bis 8) als höchstem Bildungsabschluss. Unterschiedlicher Datenstand (2020 und 2021).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics",
			"Eurostat"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Bildungsniveau der Bevölkerung",
		"thema": "15 Bildung",
		"unterthema": "Bildungsniveau",
		"kuerzel": "I.15.6.09206",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "6.4",
		"stufe1": "6. Internationaler Vergleich",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_027",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:10:40",
		"id": 9206
	},
	{
		"template": "template001_print",
		"data-id": 9207,
		"chart-id": 9207,
		"filter": "",
		"parentId": "9197",
		"children": [],
		"title": "Beschäftigte nach Wirtschaftssektor",
		"subtitle": "Anteile an der Gesamtbeschäftigung, 2021",
		"lesehilfe": "Fast ein Viertel der Beschäftigten in der Agglomeration Basel ist im 2. Sektor (Industrie und Baugewerbe) tätig. Das ist für eine Agglomeration ein eher hoher Wert. Höher ist dieser Anteil nur in Stuttgart, Mailand, Bologna und Lissabon. In der Agglomeration Paris arbeiten 87% der Beschäftigten im tertiären Sektor (Dienstleistungen).",
		"erlaeuterungen": "Beschäftigte am Arbeitsort. Hier sind die Agglomerationen dargestellt. Unterschiedlicher Datenstand (zwischen 2020 und 2021; italienische Agglomerationen: 2011).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics",
			"Eurostat"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Beschäftigte nach Wirtschaftssektor",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09207",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "6.6",
		"stufe1": "6. Internationaler Vergleich",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_029",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:10:49",
		"id": 9207
	},
	{
		"template": "template001_print",
		"data-id": 9208,
		"chart-id": 9208,
		"filter": "",
		"parentId": "9199",
		"children": [],
		"title": "Erwerbstätigenquote nach Geschlecht",
		"subtitle": "2021",
		"lesehilfe": "In der trinationalen Agglomeration Basel sind 73,5% der Frauen von 20 bis 64 Jahren erwerbstätig. Bei den Männern liegt die Quote bei 81,6%. Am höchsten ist die Erwerbstätigenquote sowohl bei den Frauen als auch bei den Männern in Bern, Zürich und in den deutschen Agglomerationen. In Mailand und Bologna ist der Quotenunterschied zwischen Frauen und Männern am grössten.",
		"erlaeuterungen": "Anteil der Erwerbstätigen an der ständigen Wohnbevölkerung von 20 bis 64 Jahren. Hier sind die Agglomerationen dargestellt. Unterschiedlicher Datenstand (zwischen 2018 und 2021; Portugal: 2011).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics",
			"Eurostat"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Erwerbstätigenquote nach Geschlecht",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.09208",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "6.5",
		"stufe1": "6. Internationaler Vergleich",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_028",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:10:48",
		"id": 9208
	},
	{
		"template": "template001_print",
		"data-id": 9209,
		"chart-id": 9209,
		"filter": "",
		"parentId": "9200",
		"children": [],
		"title": "Beschäftigtendichte",
		"subtitle": "2021",
		"lesehilfe": "Die Beschäftigtendichte ist in den Agglomerationen Bern, Lausanne und Zürich am höchsten. Das heisst, hier sind am meisten Beschäftigte pro Einwohner tätig. Es folgen München, Karlsruhe und Stuttgart. Basel positioniert sich mit einem Wert von 0,54 eher im Mittelfeld.",
		"erlaeuterungen": "Beschäftigte (am Arbeitsort) pro Einwohner. Hier sind die Agglomerationen dargestellt. Unterschiedlicher Datenstand (2020 oder 2021).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics",
			"Eurostat"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Beschäftigtendichte",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09209",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "6.7",
		"stufe1": "6. Internationaler Vergleich",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_030",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:10:52",
		"id": 9209
	},
	{
		"template": "template001_print",
		"data-id": 9481,
		"chart-id": 9481,
		"filter": "",
		"parentId": "9406",
		"children": [],
		"title": "Entwicklung der Gesamtbevölkerung",
		"subtitle": "durchschnittliche jährliche Veränderungsrate, 2016 bis 2021",
		"lesehilfe": "Zwischen 2016 und 2021 ist die Gesamtbevölkerung der Agglomeration Basel (+0,5% pro Jahr) deutlich weniger gewachsen als die Bevölkerung in den Vergleichsagglomerationen Genf, Lausanne und Zürich. Am tiefsten ist das Bevölkerungswachstum in den Agglomerationsgemeinden in Deutschland, am höchsten in den französischen Gemeinden.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung der Gesamtbevölkerung",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.09481",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "2.2",
		"stufe1": "2. Bevölkerungsstruktur",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:09:15",
		"id": 9481
	},
	{
		"template": "map_gemeinden_print",
		"data-id": 9482,
		"chart-id": 9482,
		"filter": "",
		"parentId": "9407",
		"children": [],
		"title": "Jugendquotient nach Gemeinde",
		"subtitle": "trinationale Agglomeration Basel, 2021",
		"lesehilfe": "Die Anzahl Jugendlicher pro 100 Personen zwischen 20 und 64 Jahren ist in den Gemeinden der grenzüberschreitenden Agglomeration Basel mit 24 in Augst und Hemmiken (Schweiz) am tiefsten; mit 54 ist sie in Vieux-Ferrette (Frankreich) am höchsten. Die Quotienten sind in den meisten Gemeinden in Frankreich höher als in der Schweiz und in Deutschland. Den höchsten Jugendquotienten in der Schweiz weist Zullwil auf (43), in Deutschland Rümmingen (40). In der Kernstadt Basel leben 26 Jugendliche pro 100 20- bis 64-Jährige.",
		"erlaeuterungen": "Der Jugendquotient beschreibt das Verhältnis der Personen im Alter von 19 oder weniger Jahren zu jenen im erwerbsfähigen Alter zwischen 20 und 64 Jahren. Das Verhältnis wird pro 100 Personen zwischen 20 und 64 Jahren ausgewiesen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Jugendquotient nach Gemeinde",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.09482",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "2.6",
		"stufe1": "2. Bevölkerungsstruktur",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_007",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:09:27",
		"id": 9482
	},
	{
		"template": "template001_print",
		"data-id": 9483,
		"chart-id": 9483,
		"filter": "",
		"parentId": "9409",
		"children": [],
		"title": "Entwicklung der Beschäftigtenzahl",
		"subtitle": "durchschnittliche jährliche Veränderungsrate, 2016 bis 2021",
		"lesehilfe": "Zwischen 2016 und 2021 war das Wachstum der Beschäftigtenzahl in der Agglomeration Basel (+0,3% im Jahresdurchschnitt) geringer als in den Vergleichsagglomerationen. Innerhalb der Agglomeration Basel gab es grosse Unterschiede: Während im französischen Teil ein Wachstum verzeichnet wurde (+0,7% pro Jahr), ging die Beschäftigung in der Kernstadt leicht zurück (-0,2% pro Jahr).",
		"erlaeuterungen": "Der Begriff Beschäftigte bezeichnet die Anzahl der besetzten Stellen. Die Erfassung erfolgt am Arbeitsort.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung der Beschäftigtenzahl",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09483",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "4.5",
		"stufe1": "4. Arbeitsmarkt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_018",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:10:08",
		"id": 9483
	},
	{
		"template": "map_gemeinden_print",
		"data-id": 9484,
		"chart-id": 9484,
		"filter": "",
		"parentId": "9410",
		"children": [],
		"title": "Anteil der Einpersonenhaushalte nach Gemeinde",
		"subtitle": "trinationale Agglomeration Basel, 2021",
		"lesehilfe": "Der Anteil der Haushalte mit nur einer Person ist in der Kernstadt Basel mit 48,9% bei weitem der höchste in der trinationalen Agglomeration. Anteile von über 40% verzeichnen ausser Basel nur noch Birsfelden und Augst in der Schweiz, Lörrach in Deutschland sowie Huningue, Saint-Louis und Ferrette in Frankreich.",
		"erlaeuterungen": "Privathaushalte sind alle Haushalte ausser Kollektivhaushalte (z. B. Alters- und Pflegeheime).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil der Einpersonenhaushalte nach Gemeinde",
		"thema": "01 Bevölkerung",
		"unterthema": "Haushalte",
		"kuerzel": "I.01.2.09484",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "3.3",
		"stufe1": "3. Familienhaushalte und Bildung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_012",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:09:44",
		"id": 9484
	},
	{
		"template": "map_gemeinden_print",
		"data-id": 9485,
		"chart-id": 9485,
		"filter": "",
		"parentId": "9411",
		"children": [],
		"title": "Personenwagen nach Gemeinde",
		"subtitle": "trinationale Agglomeration Basel, pro 1000 Einwohner, 2021",
		"lesehilfe": "Die Stadt Basel weist mit 319 Personenwagen pro 1000 Einwohner mit Abstand den tiefsten Motorisierungsgrad in der Agglomeration auf. Es folgen die Nachbargemeinden Riehen und Birsfelden mit je fast 400 Autos pro 1000 Einwohner. In der gesamten Agglomeration gibt es viele Gemeinden mit mehr als 700 Autos pro 1000 Einwohner, wobei sich die grosse Mehrheit davon in Frankreich befindet. Den Rekordwert erreicht die französische Gemeinde Bettlach (810).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Personenwagen nach Gemeinde",
		"thema": "11 Verkehr",
		"unterthema": "Motorfahrzeuge",
		"kuerzel": "I.11.1.09485",
		"kennzahlenset": "City-Statistics (Print)",
		"kuerzelKunde": "5.3",
		"stufe1": "5. Verkehr und Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "99_00_00_00_00_023",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-23T08:10:32",
		"id": 9485
	}
];