var indikatorensetData = [
	{
		"template": "line001",
		"data-id": 10031,
		"chart-id": 10031,
		"filter": "",
		"parentId": "9919",
		"children": [],
		"title": "Quote der Ergänzungsleistungen und Beihilfen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "69% der Personen mit IV erhielten zum Jahresende 2022 Ergänzungsleistungen (EL), 41% werden mittels Beihilfen zur IV unterstützt. Bei den Personen mit AHV liegen diese Quoten bei 21% bzw. 13%.",
		"erlaeuterungen": "Die Quote der Leistungsbeziehenden entspricht dem Verhältnis der Beziehenden von Ergänzungsleistungen (EL) bzw. Beihilfen zur Gesamtheit der Beziehenden von AHV- bzw. IV-Renten per Ende Jahr.",
		"quellenangabe": [
			"Amt für Sozialbeiträge Basel-Stadt, Abteilung Ergänzungsleistungen",
			"Bundesamt für Sozialversicherungen (BSV)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Quote der Ergänzungsleistungen und Beihilfen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.10031",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.1.4",
		"stufe1": "Leben",
		"stufe2": "1.1 Armut",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_105",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:33",
		"id": 10031
	},
	{
		"template": "template001",
		"data-id": 10032,
		"chart-id": 10032,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Nichtbezug von bedarfsabhängigen Sozialleistungen und Sozialhilfe",
		"subtitle": "Stadt Basel",
		"lesehilfe": "23% der im Jahr 2015 Anspruchsberechtigten haben keine Familienmietzinsbeiträge bezogen. Die Nichtbezugsquote bei den Ergänzungsleistungen (EL) zur AHV lag 2015 bei 29%, jene der Prämienverbilligung bei 19%. Rund 30% der Personen mit Anspruch auf Sozialhilfe haben diesen nicht geltend gemacht.",
		"erlaeuterungen": "Die Berner Fachhochschule hat im Auftrag des Amts für Sozialbeiträge des Kantons Basel-Stadt für das Jahr 2015 die Nichtbezugsquoten für die Ergänzungsleistungen, Familienmietzinsbeiträge und Prämienverbilligung berechnet. In einem weiteren Projekt im Auftrag der Sozialhilfe Basel-Stadt wurde die Nichtbezugsquote auch für den Bezug von Sozialhilfe für die Jahre 2016 bis 2020 berechnet. Die Berechnungen basieren auf kantonalen Registerdaten.<br>Mietzinsbeiträge: Familienmietzinsbeiträge",
		"quellenangabe": [
			"Berner Fachhochschule (BFH)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nichtbezug von bedarfsabhängigen Sozialleistungen und Sozialhilfe",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.10032",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.1.5",
		"stufe1": "Leben",
		"stufe2": "1.1 Armut",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_106",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:33",
		"id": 10032
	},
	{
		"template": "template001",
		"data-id": 10033,
		"chart-id": 9373,
		"filter": "",
		"parentId": "9373",
		"children": [],
		"title": "Anteil Personen, die in einem Haushalt mit Betreibungen, Zahlungsrückständen oder Kontoüberziehungen leben",
		"subtitle": "Nordwestschweiz",
		"lesehilfe": "2021 lebten von der Bevölkerung in der Nordwestschweiz: 8,2% in einem Haushalt mit mindestens einer Art von Zahlungsrückstand. 2020 lebten: 5,5% in einem Haushalt, in dem mindestens eine Person eine Betreibung oder einen Verlustschein hatte; 5,9% in einem Haushalt mit mindestens einer Kontoüberziehung oder einer unbezahlten Kreditkartenrechnung.",
		"erlaeuterungen": "Folgende Arten von Zahlungsrückständen, d. h. in den letzten zwölf Monaten aus finanziellen Gründen nicht fristgerecht beglichene Rechnungen, werden berücksichtigt: Miete oder Hypothekarzinsen;  laufende Rechnungen für Wasser, Strom, Gas, Heizung; Kreditrückzahlungen oder Kreditkartenrechnungen; Krankenkassenprämien; Steuern. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe und sind folglich mit einer gewissen Unsicherheit behaftet. Das Konfidenzintervall (schwarzer Fehlerbalken) gibt den Bereich an, welcher den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Die Ergebnisse zu Betreibungen und Verlustscheinen sowie Kontoüberziehungen und unbezahlten Kreditkartenrechnungen beziehen sich auf das Modul «Verschuldung», das Bestandteil der Erhebungen 2013, 2017 und 2020 war.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Erhebung über die Einkommen und Lebensbedingungen (SILC)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil Personen, die in einem Haushalt mit Betreibungen, Zahlungsrückständen oder Kontoüberziehungen leben",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.10033",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.1.8",
		"stufe1": "Leben",
		"stufe2": "1.1 Armut",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_109",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:35",
		"id": 10033
	},
	{
		"template": "befragungen001",
		"data-id": 10034,
		"chart-id": 4852,
		"filter": "",
		"parentId": "4852",
		"children": [],
		"title": "Sicherheitsgefühl im Alltag",
		"subtitle": "«Wie sicher fühlen Sie sich ganz allgemein im Alltag?», Basel-Stadt",
		"lesehilfe": "2023 fühlten sich 45,2% der Bevölkerung im Alltag sehr sicher und 44,3% eher sicher. Im Vergleich zu den früheren Befragungen fühlten sich zwar weniger Personen sehr sicher, aber das alltägliche Sicherheitsempfinden insgesamt blieb in etwa auf gleichem Niveau.",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: Ab 2019 in schriftlicher Form (Papier- bzw. Onlinefragebogen), zuvor telefonisch; Ab 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppen (2011, 2015 und 2019 wurden nachgewichtet, die Werte weichen daher von früher publizierten ab).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Sicherheitsgefühl im Alltag",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.10034",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.2.5",
		"stufe1": "Leben",
		"stufe2": "1.2 Psychische Gesundheit",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_205",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:40",
		"id": 10034
	},
	{
		"template": "line001",
		"data-id": 10035,
		"chart-id": 10035,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Jugendliche ausserhalb des Bildungssystems",
		"subtitle": "Basel-Stadt und Schweiz",
		"lesehilfe": "Der Anteil der Jugendlichen ausserhalb des Bildungssystems betrug in Basel-Stadt im Mittel der Jahre 2019 bis 2021 9,9%. Das 95%-Konfidenzintervall dieses Anteils liegt zwischen 7,9% und 11,8%. Somit ist der Anteil Jugendlicher ausserhalb des Bildungssystems in Basel-Stadt signifikant höher als der durchschnittliche Anteil in der Schweiz (6,3%, 95%-Konfidenzintervall: 6,1% - 6,5%).",
		"erlaeuterungen": "Anteil der Personen an der Wohnbevölkerung zwischen 18 und 24 Jahren, welche höchstens die obligatorische Schule abgeschlossen haben. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe und sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau (Bereich, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst). Um eine grössere Stichprobe zu erhalten, werden die Daten aus jeweils drei Jahren zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese drei Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die neueren Ergebnisse nur bedingt mit jenen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Jugendliche ausserhalb des Bildungssystems",
		"thema": "15 Bildung",
		"unterthema": "Bildungsniveau",
		"kuerzel": "I.15.6.10035",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.3.1",
		"stufe1": "Leben",
		"stufe2": "1.3 Chancengleichheit",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_301",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:41",
		"id": 10035
	},
	{
		"template": "befragungen001",
		"data-id": 10036,
		"chart-id": 4858,
		"filter": "",
		"parentId": "4858",
		"children": [],
		"title": "Beurteilung der Chancengleichheit",
		"subtitle": "«Wie stehen Sie zu folgender Aussage: Die Chancengleichheit wird von den Behörden zielstrebig vorangetrieben.», Basel-Stadt",
		"lesehilfe": "Mit der Aussage, dass die kantonalen Behörden die Chancengleichheit für Frauen und Männer zielstrebig vorantreiben würden, sind 9,7% der im Jahr 2019 Befragten sehr und 30,7% eher einverstanden. Der Anteil Befragter, welche diese Aussage nicht beurteilt haben ist im Vergleich zu den Vorjahren gestiegen.",
		"erlaeuterungen": "Alle vier Jahre (bis 2007 alle zwei) wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beurteilung der Chancengleichheit",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.10036",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.3.2",
		"stufe1": "Leben",
		"stufe2": "1.3 Chancengleichheit",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_303",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:42",
		"id": 10036
	},
	{
		"template": "line001",
		"data-id": 10037,
		"chart-id": 10037,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Personen mit Diskriminierungs- oder Gewalterfahrung",
		"subtitle": "",
		"lesehilfe": "40% der in Basel-Stadt Befragten gaben 2022 an, Diskriminierungs- oder Gewalterfarungen gemacht zu haben. Die statistische Unsicherheit reicht jedoch von einem Anteil von 27% bis 53%, womit kein statistisch signifikanter Unterschied gegenüber den Werten der Schweiz (30%; +/- 1,7 Prozentpunkte) festgestellt werden kann. Einzig 2020 kann ein statistisch signifikant höherer Anteil für Basel-Stadt gegenüber den Werten der Schweiz beobachtet werden.",
		"erlaeuterungen": "Grundgesamtheit: Ständige Wohnbevölkerung im Alter von 15 bis 88 Jahren.<br>Die Werte für den Kanton Basel-Stadt beruhen jeweils auf weniger als 30 Antworten und unterliegen daher einer grossen statistischen Unsicherheit. Die Fehlerbalken geben jeweils den statistischen Fehlerbereich (95%-Vertrauensintervall) der geschätzten Anteile wieder. Nur, wenn sich die Fehlerbalken zwischen zwei Kategorien nicht überschneiden, kann ein statistisch signifikanter Unterschied zwischen diesen festgestellt werden.<br>Die dargestellten Zahlen zeigen den Anteil der Bevölkerung der erklärt hat, aufgrund einer Gruppenzugehörigkeit Opfer von Diskriminierung oder Gewalt geworden zu sein. Selbstdeklaration der befragten Personen. Die dargestellten Anteile entsprechen nicht den Fällen von Diskriminierung oder Gewalt, die in den Beratungs- oder Meldstellen erfasst werden bzw. den Sanktionen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Erhebung zum Zusammenleben in der Schweiz (ZidS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Personen mit Diskriminierungs- oder Gewalterfahrung",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.10037",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.3.5",
		"stufe1": "Leben",
		"stufe2": "1.3 Chancengleichheit",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_307",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:44",
		"id": 10037
	},
	{
		"template": "line001",
		"data-id": 10038,
		"chart-id": 10038,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Ausbildungsbeiträge nach Aufenthaltsrecht",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2022 haben insgesamt 669 ausländische Personen Stipendien bezogen. Davon verfügen 336 Personen über eine Bewilligung für Niedergelassene. Seit 2019 nimmt die Anzahl Stipendien für diese Gruppe ab, während eine steigende Anzahl Stipenden für Aufenthalter sowie Vorläufig Aufgenommene gesprochen wird.",
		"erlaeuterungen": "Durch den Kanton vergebene Stipendien.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der kantonalen Stipendien und Darlehen (STIP)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Ausbildungsbeiträge nach Aufenthaltsrecht",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.3.6",
		"stufe1": "Leben",
		"stufe2": "1.3 Chancengleichheit",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_308",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:45",
		"id": 10038
	},
	{
		"template": "template001",
		"data-id": 10039,
		"chart-id": 10039,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil Primärsprachen",
		"subtitle": "Häufigste Fremdsprachen im Kanton Basel-Stadt",
		"lesehilfe": "In Basel-Stadt gaben im Mittel der Jahre 2019 bis 2021 12,1% der Bevölkerung Englisch als ihre Primärsprache an. Das Konfidenzintervall dieses Anteils liegt zwischen 11,5% und 12,6%. Im Zeitraum von 2010 bis 2021 beobachten wir eine signifikante Zunahme der englischsprachigen Bevölkerung.",
		"erlaeuterungen": "Für jede Person werden bis zu drei Hauptsprachen, d. h. Sprachen, in denen man denkt und die man am besten beherrscht, erfasst. Dies führt dazu, dass sich die Prozentzahlen auf über 100% addieren können. Dargestellt sind die acht häufigsten Sprachen ausser Deutsch. Die Daten stammen aus der Strukturerhebung des Bundesamtes für Statistik. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe von jährlich rund 5 000 in Basel-Stadt wohnhaften Personen ab 15 Jahren und sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Die Daten von jeweils drei Jahren werden zusammen ausgewertet, um eine grössere Stichprobe zu erhalten (gepoolte Daten). Die Zahlen können als Mittelwert über diese drei Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil Primärsprachen",
		"thema": "01 Bevölkerung",
		"unterthema": "Sprachen",
		"kuerzel": "I.01.8.10039",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "2.1.1",
		"stufe1": "Zusammenhalt",
		"stufe2": "2.1 Kulturelles Erbe und Identitäten",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_402",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:51",
		"id": 10039
	},
	{
		"template": "template001",
		"data-id": 10040,
		"chart-id": 4722,
		"filter": "",
		"parentId": "4722",
		"children": [],
		"title": "Anzahl eingebürgerte Ausländer und Einbürgerungsziffer",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2022 liessen sich 1 465 ausländische Staatsangehörige einbürgern. Dies entspricht einer Einbürgerungsziffer von 18,9 Einbürgerungen pro 1000 ausländischen Staatsangehörigen.",
		"erlaeuterungen": "Ausländische Staatsangehörige, die zehn Jahre in der Schweiz gelebt haben und eine Niederlassungsbewilligung C besitzen, können sich um die ordentliche Einbürgerung bewerben. Die im Alter von 8 bis 18 in der Schweiz verbrachten Jahre zählen doppelt. Unter bestimmten Voraussetzungen ist nach kürzerer Aufenthaltsdauer eine erleichterte Einbürgerung möglich, z. B. nach fünf Jahren Aufenthalt und drei Jahren Ehe mit einer Schweizerin bzw. einem Schweizer. Auch in der Schweiz geborene ausländische Staatsangehörige der dritten Generation können sich bis zum Alter von 25 Jahren erleichtert einbürgern lassen, falls ein Grosseltern- und ein Elternteil in der Schweiz gelebt haben. Bis 2017 galten teilweise andere Bestimmungen, die bei bis zu diesem Zeitpunkt eingereichten Einbürgerungsgesuchen zum Tragen kamen. Neben den ordentlichen und den erleichterten Einbürgerungen gibt es weitere Einbürgerungen (beispielsweise infolge Adoption, Wiedereinbürgerung oder Feststellung der Schweizer Staatsangehörigkeit), die hier ebenfalls berücksichtigt werden. Die Einbürgerungsziffer ergibt sch aus der Anzahl Einbürgerungen pro 1000 ausländische Staatsangehörige am Jahresende.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl eingebürgerte Ausländer und Einbürgerungsziffer",
		"thema": "01 Bevölkerung",
		"unterthema": "Einbürgerungen",
		"kuerzel": "I.01.6.10040",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "2.1.3",
		"stufe1": "Zusammenhalt",
		"stufe2": "2.1 Kulturelles Erbe und Identitäten",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_404",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:52",
		"id": 10040
	},
	{
		"template": "template001",
		"data-id": 10041,
		"chart-id": 6215,
		"filter": "",
		"parentId": "6215",
		"children": [],
		"title": "Wohnbevölkerung gemäss Bevölkerungsszenarien",
		"subtitle": "Bevölkerungsszenarien Basel-Stadt, 2024",
		"lesehilfe": "Bis zum Jahr 2045 erhöht sich die kantonale Wohnbevölkerung im Mittleren Szenario von 206 308 am Ende des Jahres 2023 um 9,2% auf rund 225 000 Einwohner.",
		"erlaeuterungen": "Resultat der Bevölkerungsszenarien 2024. Bevölkerungsbestand am Jahresende. Die Bevölkerungszahl setzt sich zusammen aus der ständigen und nichtständigen Wohnbevölkerung und Personen am Nebenwohnsitz.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsszenarien"
		],
		"externalLinks": [
			"Detaillierte Informationen zu den Bevölkerungsszenarien und der angewandten Methodik finden Sie auf der <a href = 'https://www.statistik.bs.ch/analysen-berichte/gesellschaft-soziales/bevoelkerungsszenarien.html' target = '_blank'>Internetseite zu den Bevölkerungsszenarien</a>."
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnbevölkerung gemäss Bevölkerungsszenarien",
		"thema": "01 Bevölkerung",
		"unterthema": "Szenarien",
		"kuerzel": "",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "2.1.4",
		"stufe1": "Zusammenhalt",
		"stufe2": "2.1 Kulturelles Erbe und Identitäten",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_405",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-07-15T08:14:07",
		"id": 10041
	},
	{
		"template": "befragungen001",
		"data-id": 10044,
		"chart-id": 4872,
		"filter": "",
		"parentId": "4872",
		"children": [],
		"title": "Interesse an der Politik in Basel-Stadt",
		"subtitle": "«Wie stark interessieren Sie sich für die Politik im Kanton Basel-Stadt?», Basel-Stadt",
		"lesehilfe": "15,0% der im Jahr 2019 Befragten interessieren sich sehr und 37,2% eher für die Politik im Kanton Basel-Stadt. 32,9% interessieren sich dafür eher nicht und 12,0% überhaupt nicht.",
		"erlaeuterungen": "Alle vier Jahre (bis 2007 alle zwei) wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Interesse an der Politik in Basel-Stadt",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.10044",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "2.2.2",
		"stufe1": "Zusammenhalt",
		"stufe2": "2.2 Dialog, Nachbarschaft und Kooperationen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_503",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:56",
		"id": 10044
	},
	{
		"template": "befragungen001",
		"data-id": 10045,
		"chart-id": 4724,
		"filter": "",
		"parentId": "4724",
		"children": [],
		"title": "Vertretung der Anliegen der Bevölkerung durch Parlament und Regierung",
		"subtitle": "«Wie gut vertreten Ihrer Meinung nach die Behörden, also der Regierungsrat und der Grosse Rat, die Anliegen der Bevölkerung?», Basel-Stadt",
		"lesehilfe": "2019 fühlten sich 50% der befragten Personen sehr oder eher gut von den Behörden vertreten. Im Vergleich zu 2015 entspricht dies einem Rückgang um 18 Prozentpunkte. Der Anteil der Befragten, die sich gar nicht gut vertreten fühlen, ist hingegen grösser geworden.",
		"erlaeuterungen": "Alle vier Jahre (bis 2007 alle zwei) wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) statt wie zuvor telefonisch durchgeführt. Dieser Methodenwechsel kann einen Einfluss auf die Vergleichbarkeit der Ergebnisse haben (weitere Informationen: <a href='https://www.statistik.bs.ch/befragungen' target='_blank'>www.statistik.bs.ch/befragungen</a>). Die Daten werden 2023 nach Geschlecht, Staatsangehörigkeit und Altersgruppen gewichtet. Die Daten der Befragungen 2011, 2015 und 2019 wurden nach den identischen Faktoren nachgewichtet. Die Werte dieser drei Jahre weichen daher von früher publizierten ab.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Vertretung der Anliegen der Bevölkerung durch Parlament und Regierung",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.10045",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "2.2.3",
		"stufe1": "Zusammenhalt",
		"stufe2": "2.2 Dialog, Nachbarschaft und Kooperationen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_504",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:56",
		"id": 10045
	},
	{
		"template": "line001",
		"data-id": 10047,
		"chart-id": 10047,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Gestört fühlen durch als «anders» empfundene Personen",
		"subtitle": "",
		"lesehilfe": "21% der in Basel-Stadt Befragten gaben 2022 an, sich durch als «anders» empfundene Personen gestört zu fühlen. Die statistische Unsicherheit reicht jedoch von einem Anteil von 10% bis 31%, womit kein statistisch signifikanter Unterschied gegenüber dem Wert der Schweiz (31%; +/- 1,7 Prozentpunkte) festgestellt werden kann. 2018 und 2020 kann jeweils ein statistisch signifikant tieferer Anteil für Basel-Stadt gegenüber den Werten der Schweiz beobachtet werden.",
		"erlaeuterungen": "Grundgesamtheit: Ständige Wohnbevölkerung im Alter von 15 bis 88 Jahren.<br>Die Werte für den Kanton Basel-Stadt beruhen jeweils auf weniger als 30 Antworten und unterliegen daher einer grossen statistischen Unsicherheit. Die Fehlerbalken geben jeweils den statistischen Fehlerbereich (95%-Vertrauensintervall) der geschätzten Anteile wieder. Nur, wenn sich die Fehlerbalken zwischen zwei Kategorien nicht überschneiden, kann ein statistisch signifikanter Unterschied zwischen diesen festgestellt werden.<br>Die dargestellte Zahlen zeigen den Anteil der Bevölkerung der sich in mindestens einem sozialen Umfeld (Alltag, Arbeit, Nachbarschaft) und durch mindestens ein Personenmerkmal (Hautfarbe, Sprache, Religion, Nationalität) gestört fühlt.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Erhebung zum Zusammenleben in der Schweiz (ZidS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Gestört fühlen durch als «anders» empfundene Personen",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.10047",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "2.2.7",
		"stufe1": "Zusammenhalt",
		"stufe2": "2.2 Dialog, Nachbarschaft und Kooperationen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_510",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:05:00",
		"id": 10047
	},
	{
		"template": "befragungenGrundauswertung001",
		"data-id": 10048,
		"chart-id": 9738,
		"filter": "",
		"parentId": "9738",
		"children": [],
		"title": "Wissen um CO<sub>2</sub>-Fussabdruck",
		"subtitle": "«Kennen Sie Ihren CO<sub>2</sub>-Fussabdruck?», Basel-Stadt, 2023",
		"lesehilfe": "5,6% der Bevölkerung kennen ihren CO<sub>2</sub>-Fussabdruck. Bei den 50-59 Jährigen beträgt der Ja-Anteil 8,9%.",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wissen um CO<sub>2</sub>-Fussabdruck",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.10048",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.4.1",
		"stufe1": "Leben",
		"stufe2": "1.4 Erhalt der Lebensgrundlagen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_04_00_00_00_601",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:46",
		"id": 10048
	},
	{
		"template": "line001",
		"data-id": 10049,
		"chart-id": 9390,
		"filter": "",
		"parentId": "9390",
		"children": [],
		"title": "Tropennächte",
		"subtitle": "Anzahl Nächte, Basel-Stadt",
		"lesehilfe": "Im Jahr 2023 wurden an der Messstation Feldbergstrasse im Stadtzentrum von Basel 24 Tropennächte registriert, während an der vorstädtischen Station Basel-Binningen nur 3 Tropennächte verzeichnet wurden.",
		"erlaeuterungen": "Tropennächte sind Nächte, in denen die Temperatur nicht unter 20 °C sinkt. Die Temperaturmessungen erfolgen an verschiedenen Messstationen in der Region Basel. Gewisse Abweichungen zu den validierten MeteoSchweiz-Daten aufgrund unterschiedlicher Methodik sind möglich. Infolge der unterschiedlichen Lagen der Messstationen ist auch die Anzahl Tropennächte verschieden stark ausgeprägt. Im innerstädtischen Umfeld mit schlechter Durchlüftung und dichter Bebauung ist die thermische Belastung nachts besonders hoch, wohingegen in vorstädtischer Lage (offene Bebauung) oder bei viel Vegetation (Kühlung durch Verdunstung) die nächtliche Abkühlung besser erfolgen kann.",
		"quellenangabe": [
			"Universität Basel",
			"Lufthygieneamt beider Basel",
			"Meteorologischer Verein der Region Basel",
			"MeteoSchweiz"
		],
		"externalLinks": [
			"Weitere Informationen zum Indikator und den einzelnen Messstationen: <a href = 'http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-08-0815' target = '_blank'>Umweltbericht beider Basel</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Tropennächte",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Klima",
		"kuerzel": "I.02.12.10049",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.4.2",
		"stufe1": "Leben",
		"stufe2": "1.4 Erhalt der Lebensgrundlagen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_04_00_00_00_602",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:46",
		"id": 10049
	},
	{
		"template": "befragungen001",
		"data-id": 10050,
		"chart-id": 6028,
		"filter": "",
		"parentId": "6028",
		"children": [],
		"title": "Anteile der Verkehrsmittel",
		"subtitle": "",
		"lesehilfe": "Der Anteil der zu Fuss zurückgelegten Etappen liegt 2021 in Basel-Stadt bei rund 53%, gemessen an der Tagesunterwegszeit bei etwa 50%. Die zu Fuss zurückgelegten Strecken machen 11% der gesamten Tagesdistanz aus. Rund 46% der täglich zurückgelegten Distanz werden mit dem motorisierten Individualverkehr (MIV), also mit dem Auto oder mit motorisierten Zweirädern bewältigt. Der öffentliche Verkehr (Bahn, Bus, Tram, Postauto) kommt auf einen Anteil von 31%.",
		"erlaeuterungen": "Die Ergebnisse von 2021 basieren auf der Hochrechnung einer Stichprobenerhebung von 975 Zielpersonen (2015: 1 241 Zielpersonen; 2010: 1 253 Zielpersonen) mit Wohnort im Kanton Basel-Stadt. Da die Erhebung im Jahr 2021 stattfand, war sie wesentlich von der COVID-19-Pandemie geprägt. Eine Etappe beginnt mit jedem Verkehrsmittelwechsel (auch beim Umsteigen) oder bei einem neuen Verkehrszweck. Bei der Tagesunterwegszeit werden Warte- und Umsteigezeiten nicht mitgerechnet.",
		"quellenangabe": [
			"Bundesamt für Statistik und Bundesamt für Raumentwicklung, Mikrozensus Mobilität und Verkehr"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteile der Verkehrsmittel",
		"thema": "11 Verkehr",
		"unterthema": "Öffentlicher Verkehr",
		"kuerzel": "I.11.2.10050",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.4.3",
		"stufe1": "Leben",
		"stufe2": "1.4 Erhalt der Lebensgrundlagen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_04_00_00_00_603",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:47",
		"id": 10050
	},
	{
		"template": "template001",
		"data-id": 10051,
		"chart-id": 9008,
		"filter": "",
		"parentId": "9008",
		"children": [],
		"title": "Endenergieverbrauch nach Verbrauchergruppe",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Der Endenergieverbrauch hat zwischen 2010 und 2020 um rund 27% abgenommen. Auf die Kategorie Wohnen (Anteil 2020: 35,2%) entfällt dabei 2020 etwa der gleiche Energieeinsatz wie 2010, während in diesem Zeitraum die Energiebezugsfläche zugenommen hat. Stark zurückgegangen ist der Verbrauch in der Kategorie Nichtwohnen (Anteil 2020: 49,7%), nämlich von 3 061 GWh auf 1 953 GWh, was einer Reduktion um etwa 36% entspricht. In der Kategorie Verkehr (Anteil 2020: 15,1%) ist 2020 gegenüber 2018 ein starker Rückgang ersichtlich, wobei dieser vor allem aufgrund des methodischen Bruchs infolge des aktualisierten Gesamtverkehrsmodells zustandegekommen ist.",
		"erlaeuterungen": "Endenergie ist der nach Energiewandlungs- und Übertragungsverlusten übriggebliebene Teil der Bruttoenergie, welcher von den Energienutzern verbraucht wird. Bei den Verbrauchergruppen wird zwischen «Verkehr», «Wohnen» und «Nichtwohnen» unterschieden, wobei zum Wohnen die privaten Haushalte und zum Nichtwohnen Gewerbe, Handel, Dienstleistungen und Industrie gehören. Verteilverluste, statistische Differenzen sowie Exporte bleiben in dieser Betrachtung unberücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [
			"<a href = 'https://www.statistik.bs.ch/analysen-berichte/raum-umwelt/energiestatistik.html' target = '_blank'>Energiestatistik Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Endenergieverbrauch nach Verbrauchergruppe",
		"thema": "",
		"unterthema": "Verbrauch",
		"kuerzel": "",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.4.4",
		"stufe1": "Leben",
		"stufe2": "1.4 Erhalt der Lebensgrundlagen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_04_00_00_00_604",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:48",
		"id": 10051
	},
	{
		"template": "template001",
		"data-id": 10052,
		"chart-id": 6163,
		"filter": "",
		"parentId": "6163",
		"children": [],
		"title": "Siedlungsabfälle, Wertstoffsammlungen, Recyclingquote",
		"subtitle": "in kg pro Kopf resp. Prozent, Basel-Stadt",
		"lesehilfe": "Die Siedlungsabfälle reduzierten sich zwischen 2000 und 2022 von 194 auf 152 kg pro Kopf. Die Recyclingquote liegt aktuell bei 40,3%.",
		"erlaeuterungen": "Grundlage ist die kantonale Abfallstatistik. Bei der Wertstoffsammlung sind berücksichtigt: Altpapier und Karton, Altglas, Altmetall/Alu/Weissblech, Grüngut, Textilien sowie Sonderabfälle. Die Recyclingquote entspricht dem Anteil der Wertstoffsammlungen an der Gesamtmenge der Siedlungsabfälle.",
		"quellenangabe": [
			"Amt für Umwelt und Energie Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Siedlungsabfälle, Wertstoffsammlungen, Recyclingquote",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Entsorgung",
		"kuerzel": "I.02.6.10052",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.4.6",
		"stufe1": "Leben",
		"stufe2": "1.4 Erhalt der Lebensgrundlagen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_04_00_00_00_606",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:49",
		"id": 10052
	},
	{
		"template": "template001",
		"data-id": 10054,
		"chart-id": 10054,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Biotopwert Wald",
		"subtitle": "Anzahl Kontrollstichproben nach Biotopwert-Klasse, Basel-Stadt",
		"lesehilfe": "Von den 429 Kontrollstichproben, welche im Jahr 2017 aufgenommen wurden, wiesen 133 einen hohen Biotopwert auf. Nur eine Stichprobenfläche lag in der tiefsten Biotopwertklasse.",
		"erlaeuterungen": "Der Biotopwert umschreibt die ökologische Bedeutung eines Baumbestandes anhand der drei Hauptkriterien Baumartenvielfalt, Strukturvielfalt (Entwicklungsstufe, Schichtung, Schlussgrad) und Naturnähe des Bestandes. Er ist eine ökologische Masszahl zur Beurteilung von Wäldern als Lebensraum für einheimische Tier- und Pflanzenarten. Ein Wald mit einem hohen Biotopwert zeichnet sich wie folgt aus: Es ist eine grosse Anzahl an Baumarten anzutreffen; Auch ökologisch besonders wertvolle Arten wie beispielsweise Weiden oder Eichen sind nachzuweisen; Der Bestand ist mehrschichtig aufgebaut, ist lückig und weist einen Anteil an Altholz auf; Der Nadelholzanteil, insbesondere der Fichtenanteil, überschreitet einen der Pflanzengesellschaft angepassten Anteil nicht. Die Bewertung erfolgt gemäss Biotopwert-Modell der Forschungsanstalt für Wald, Schnee und Landschaft (Brändli, 2001). Eine Kontrollstichprobe umfasst eine Aufnahmefläche von 3 Aren.",
		"quellenangabe": [
			"Amt für Wald beider Basel"
		],
		"externalLinks": [
			"Weitere Erläuterungen: <a href = 'http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-15-1509' target = '_blank'>Biotopwert</a> im Umweltbericht beider Basel"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Biotopwert Wald",
		"thema": "07 Landwirtschaft",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.4.7",
		"stufe1": "Leben",
		"stufe2": "1.4 Erhalt der Lebensgrundlagen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_04_00_00_00_703",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:50",
		"id": 10054
	},
	{
		"template": "befragungen001",
		"data-id": 10263,
		"chart-id": 4849,
		"filter": "",
		"parentId": "4849",
		"children": [],
		"title": "Beurteilung des Verhältnisses zur Nachbarschaft",
		"subtitle": "«Wie stehen Sie zu folgender Aussage: Ich habe ein gutes Verhältnis mit der Mehrheit meiner Nachbarinnen und Nachbarn.», Basel-Stadt",
		"lesehilfe": "2009 gaben 90,4%, 2013 89,6% und 2017 91,4% der Familien an, ein gutes Verhältnis zu ihren Nachbarinnen und Nachbarn zu pflegen.",
		"erlaeuterungen": "Die Familienbefragung wurde 2009 als kantonale Befragung eingeführt. Sie findet alle vier Jahre statt. Von insgesamt 5 000 zufällig ermittelten und angeschriebenen Familien haben 2017 1 665 Familien an der schriftlichen Befragung teilgenommen. Als Familie wird ein Haushalt definiert, in welchem mindestens ein Elternteil mit mindestens einem Kind unter 18 Jahren gemeinsam lebt. Ausgewählt werden zudem nur Familien, die seit mindestens einem Jahr im Kanton Basel-Stadt wohnen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Familienbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beurteilung des Verhältnisses zur Nachbarschaft",
		"thema": "50 Befragungen",
		"unterthema": "Familienbefragung",
		"kuerzel": "I.50.2.10263",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "2.2.4",
		"stufe1": "Zusammenhalt",
		"stufe2": "2.2 Dialog, Nachbarschaft und Kooperationen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_506",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:57",
		"id": 10263
	},
	{
		"template": "befragungen001",
		"data-id": 10264,
		"chart-id": 4719,
		"filter": "",
		"parentId": "4719",
		"children": [],
		"title": "Beurteilung von gesellschaftlicher Vielfalt",
		"subtitle": "«Wie stehen Sie zu folgender Aussage: Die kulturelle Vielfalt im Kanton Basel-Stadt erlebe ich als grosse Bereicherung.», Basel-Stadt",
		"lesehilfe": "42,3% bzw. 29,3% stimmen 2023 dieser Aussage sehr oder eher zu. Insgesamt 9,4% der Bevölkerung stimmen der Aussage eher oder überhaupt nicht zu.",
		"erlaeuterungen": "Alle vier Jahre (bis 2007 alle zwei) wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) statt wie zuvor telefonisch durchgeführt. Die Daten werden 2023 nach Geschlecht, Staatsangehörigkeit und Altersgruppen gewichtet. Die Daten der Befragung 2019 wurden nach den identischen Faktoren nachgewichtet. Die Werte weichen daher von früher publizierten ab.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beurteilung von gesellschaftlicher Vielfalt",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.10264",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "2.1.5",
		"stufe1": "Zusammenhalt",
		"stufe2": "2.1 Kulturelles Erbe und Identitäten",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_406",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:54",
		"id": 10264
	},
	{
		"template": "mappie001",
		"data-id": 8241,
		"chart-id": 8241,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sozialhilfequote und Sozialhilfebeziehende",
		"subtitle": "Nach Wohnviertel, Basel-Stadt, 2022",
		"lesehilfe": "Die tiefste Sozialhilfequote im Kanton Basel-Stadt weist das Bruderholz mit 1,5% auf. In der Altstadt Grossbasel, Bettingen und dem Bachletten liegt sie ebenfalls unter 2%. Klybeck und Kleinhüningen sind mit 10,6% respektive 10,3% die Wohnviertel mit der höchsten Sozialhilfequote.",
		"erlaeuterungen": "Die Sozialhilfequote zeigt den prozentualen Anteil der Sozialhilfebeziehenden an der jeweiligen Bevölkerungsgruppe gemäss Stand am Ende des Jahres. Als Sozialhilfebeziehende werden alle Personen gezählt, die im Verlaufe eines Jahres mindestens eine Leistung der Sozialhilfe erhalten haben. Es werden alle Beziehenden mit Dossiertyp Sozialhilfefall sowie Anerkannte Flüchtlinge (FL), Vorläufig Aufgenommene (VA) und Vorläufig aufgenommene Flüchtlinge (VA FL) mit einer Aufenthaltsdauer von mehr als fünf bzw. sieben Jahren (FL 5+, VA 7+, VA FL 7+) berücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Sozialhilfequote und Sozialhilfebeziehende",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe",
		"kuerzel": "I.13.3.08241",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.1.1",
		"stufe1": "Leben",
		"stufe2": "1.1 Armut",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_101",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:30",
		"id": 8241
	},
	{
		"template": "template001",
		"data-id": 8242,
		"chart-id": 8242,
		"filter": "",
		"parentId": null,
		"children": [
			8513
		],
		"title": "Sozialhilfefälle nach Fallstruktur",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Ende 2022 waren in Basel-Stadt 4 620 Sozialhilfefälle registriert. Bei 3 421 (74%) davon handelt es sich um eine unterstützte Einzelperson. 765 (17%) sind Einelternfamilien und 294 (6%) Ehe- resp. Konkubinatspaare mit Kindern. Paare ohne Kinder machen 3% der Fälle aus.",
		"erlaeuterungen": "Nur Sozialhilfedossiers im engeren Sinne. Die Dossiertypen Asyl und Flüchtling sowie Asylsuchende mit Nichteintretens- oder Negativentscheid (NEE-NE-Dossiers) sind nicht berücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Sozialhilfefälle nach Fallstruktur",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe",
		"kuerzel": "I.13.3.08242",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.1.2",
		"stufe1": "Leben",
		"stufe2": "1.1 Armut",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_102",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:31",
		"id": 8242
	},
	{
		"template": "line001",
		"data-id": 8251,
		"chart-id": 8251,
		"filter": "",
		"parentId": null,
		"children": [
			8522
		],
		"title": "Arbeitslosenquote nach Alter",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die durchschnittliche Arbeitslosenquote in Basel-Stadt hat sich von 3,0% im Jahr 2022 auf 3,1% im Jahr 2023 kaum verändert. Während die Arbeitslosenquote für Arbeitslose unter 50 Jahre von 2022 auf 2023 leicht gestiegen ist, so war sie für die Arbeitslosen ab 50 Jahren leicht rückläufig. Die Arbeitslosenquote für Menschen über 60 Jahre ist beispielsweise von 3,1% im Jahr 2022 auf 2,8% im Jahr 2023 gesunken.",
		"erlaeuterungen": "Als Arbeitslose gelten Personen, welche bei einem Regionalen Arbeitsvermittlungszentrum (RAV) gemeldet sind, keine Stelle haben und sofort vermittelbar sind. Die Arbeitslosenquote berechnet sich aus der Anzahl Arbeitslosen, geteilt durch die Erwerbspersonen. In der Grafik sind die Jahresdurchschnitte abgebildet.",
		"quellenangabe": [
			"Staatssekretariat für Wirtschaft SECO, Arbeitslosenstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitslosenquote nach Alter",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Arbeitslose",
		"kuerzel": "I.03.4.08251",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.1.6",
		"stufe1": "Leben",
		"stufe2": "1.1 Armut",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_107",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:34",
		"id": 8251
	},
	{
		"template": "line001",
		"data-id": 8252,
		"chart-id": 8252,
		"filter": "",
		"parentId": "2424",
		"children": [],
		"title": "Arbeitslosenquote nach Herkunft und Geschlecht",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Ausländerinnen und Ausländer sind stärker von Arbeitslosigkeit betroffen als Schweizerinnen und Schweizer. Die Arbeitslosenquote der ausländischen Männer ist stark von saisonalen Schwankungen geprägt. Sie ist von 4,5% im Sommer auf 6,1% im Dezember 2023 gestiegen. Bei den ausländischen Frauen ist die Quote zum Jahresende 2023 auf 4,5% gestiegen.",
		"erlaeuterungen": "Als Arbeitslose gelten Personen, welche bei einem Regionalen Arbeitsvermittlungszentrum (RAV) gemeldet sind, keine Stelle haben und sofort vermittelbar sind. Die Arbeitslosenquote berechnet sich aus der Anzahl der Arbeitslosen, geteilt durch die Erwerbspersonen. Abgebildet sind Monatswerte.",
		"quellenangabe": [
			"Staatssekretariat für Wirtschaft SECO, Arbeitslosenstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitslosenquote nach Herkunft und Geschlecht",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Arbeitslose",
		"kuerzel": "I.03.4.08252",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.1.7",
		"stufe1": "Leben",
		"stufe2": "1.1 Armut",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_108",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:35",
		"id": 8252
	},
	{
		"template": "template001",
		"data-id": 8255,
		"chart-id": 8255,
		"filter": "",
		"parentId": "6071",
		"children": [],
		"title": "Ausländische Bevölkerung nach Art der Bewilligung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Mehrheit der ausländischen Bevölkerung (2023: 42 896) im Kanton Basel-Stadt ist im Besitz einer zeitlich unbeschränkten und an keine Bedingungen geknüpften Niederlassungsbewilligung. 30 302 Personen besitzen 2023 eine Aufenthaltsbewilligung.",
		"erlaeuterungen": "Bewilligungsarten: C: Niederlassungsbewilligung, B: Aufenthaltsbewilligung, F: vorläufig aufgenommene Ausländer, L: Kurzaufenthaltsbewilligung, N: Asylsuchende. Übrige seit 2022 einschliesslich Schutzsuchende (Status S) aus der Ukraine.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Ausländische Bevölkerung nach Art der Bewilligung",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08255",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "2.1.2",
		"stufe1": "Zusammenhalt",
		"stufe2": "2.1 Kulturelles Erbe und Identitäten",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_403",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:52",
		"id": 8255
	},
	{
		"template": "template001",
		"data-id": 8263,
		"chart-id": 8263,
		"filter": "",
		"parentId": null,
		"children": [
			8534
		],
		"title": "Anteil Personen mit mittlerer bis starker psychischer Belastung",
		"subtitle": "in %, Grossregion Nordwestschweiz",
		"lesehilfe": "Im Jahr 2022 gab mit 17,6% ein höherer Anteil Personen an, mittel bis stark psychisch belastet zu sein als im Jahr 2017 mit 14,1%. Die am stärksten von psychischer Belastung betroffene Altergruppe im Jahr 2022 stellen mit 19,7% die Befragten zwischen 35 und 49 Jahren dar.",
		"erlaeuterungen": "Der Indikator basiert auf mehreren Fragen aus dem Bereich «Psychische Gesundheit» der Schweizerischen Gesundheitsbefragung der Jahre 2017 und 2022. Aufgrund der geringen Anzahl an Befragten ist eine repräsentative Auswertung für den Kanton Basel-Stadt nicht möglich. Daher wird die Grossregion Nordwestschweiz abgebildet, welche sich aus den Kantonen Basel-Stadt, Basel-Landschaft und Aargau zusammensetzt.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Schweizerische Gesundheitsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Grossregion"
		],
		"description": "Anteil Personen mit mittlerer bis starker psychischer Belastung",
		"thema": "14 Gesundheit",
		"unterthema": "Prävention, Praxen, Rettung",
		"kuerzel": "I.14.4.08263",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.2.1",
		"stufe1": "Leben",
		"stufe2": "1.2 Psychische Gesundheit",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_201",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:37",
		"id": 8263
	},
	{
		"template": "template001",
		"data-id": 8264,
		"chart-id": 8264,
		"filter": "",
		"parentId": null,
		"children": [
			8535
		],
		"title": "Anteil Personen mit depressiven Symptomen",
		"subtitle": "in %, Grossregion Nordwestschweiz",
		"lesehilfe": "Im Jahr 2022 litten gemäss Schweizerischer Gesundheitsbefragung 10% der Personen unter mittelschweren bis schweren Depressionssymptomen. Personen mit obligatorischer Schulbildung sind davon gemäss Befragung statistisch signifikant häufiger betroffen als Personen mit einem tertiären Bildungsabschluss.",
		"erlaeuterungen": "Der Indikator basiert auf verschiedenen Fragen aus dem Bereich «Psychische Gesundheit» der Schweizerischen Gesundheitsbefragung 2017 und 2022. Der Indikator gibt den Anteil Personen mit mittelschweren bis schweren depressiven Symptomen an. Aufgrund der geringen Anzahl an Befragten ist eine repräsentative Auswertung für den Kanton Basel-Stadt nicht möglich. Daher wird die Grossregion Nordwestschweiz abgebildet, welche sich aus den Kantonen Basel-Stadt, Basel-Landschaft und Aargau zusammensetzt.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Schweizerische Gesundheitsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Grossregion"
		],
		"description": "Anteil Personen mit depressiven Symptomen",
		"thema": "14 Gesundheit",
		"unterthema": "Prävention, Praxen, Rettung",
		"kuerzel": "I.14.4.08264",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.2.2",
		"stufe1": "Leben",
		"stufe2": "1.2 Psychische Gesundheit",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_202",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:38",
		"id": 8264
	},
	{
		"template": "template001",
		"data-id": 8265,
		"chart-id": 8265,
		"filter": "",
		"parentId": null,
		"children": [
			8536
		],
		"title": "Anteil Personen mit Einsamkeitsgefühlen",
		"subtitle": "in %, Grossregion Nordwestschweiz",
		"lesehilfe": "Im Jahr 2022 gaben 41,1% der Befragten an, sich manchmal bis sehr häufig einsam zu fühlen. Frauen sind von Einsamkeit stärker betroffen als Männer.",
		"erlaeuterungen": "Der Indikator basiert auf der Frage «Wie häufig kommt es vor, dass Sie sich einsam fühlen? Kommt das … vor?» (mögliche Antwortkategorien: «manchmal», «ziemlich häufig» oder «sehr häufig») in der Schweizerischen Gesundheitsbefragung 2017 und 2022. Aufgrund der geringen Anzahl an Befragten ist eine repräsentative Auswertung für den Kanton Basel-Stadt nicht möglich. Daher wird die Grossregion Nordwestschweiz abgebildet, welche sich aus den Kantonen Basel-Stadt, Basel-Landschaft und Aargau zusammensetzt.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Schweizerische Gesundheitsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Grossregion"
		],
		"description": "Anteil Personen mit Einsamkeitsgefühlen",
		"thema": "14 Gesundheit",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.2.3",
		"stufe1": "Leben",
		"stufe2": "1.2 Psychische Gesundheit",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_203",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:39",
		"id": 8265
	},
	{
		"template": "line001",
		"data-id": 8278,
		"chart-id": 8278,
		"filter": "",
		"parentId": null,
		"children": [
			8549
		],
		"title": "Lehrabbruchquote nach Herkunft und Geschlecht",
		"subtitle": "in Prozent",
		"lesehilfe": "Die Quote der Lernenden mit ausländischem Pass liegt über der Quote der Schweizerinnen und Schweizer. Männliche Lernende weisen insbesondere bei ausländischer Staatsangehörigkeit höhere Quoten auf als ihre Kolleginnen.",
		"erlaeuterungen": "Die Lehrabbruchquote zeigt den Anteil der Lehrvertragsauflösungen an den Basler Berufsfachschulen gemessen an allen abgeschlossenen Lehrverträgen. Es werden sämtliche Lehrabbrüche gezählt, unabhängig vom Wohnort der Absolventinnen und Absolventen. Nur Lernende mit Lehrverträgen von Lehrbetrieben im Kanton Basel-Stadt; berücksichtigt werden Eidgenössisches Berufsattest EBA und Eidgenössisches Fähigkeitszeugnis EFZ.",
		"quellenangabe": [
			"Erziehungsdepartement Basel-Stadt, Fachstelle Lehraufsicht"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Lehrabbruchquote nach Herkunft und Geschlecht",
		"thema": "15 Bildung",
		"unterthema": "Berufsfachschulen",
		"kuerzel": "I.15.3.08278",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.3.3",
		"stufe1": "Leben",
		"stufe2": "1.3 Chancengleichheit",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_304",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:43",
		"id": 8278
	},
	{
		"template": "befragungenGrundauswertung001",
		"data-id": 8279,
		"chart-id": 8279,
		"filter": "",
		"parentId": null,
		"children": [
			8550
		],
		"title": "Zufriedenheit mit Angeboten für Jugendliche",
		"subtitle": "«Wie zufrieden sind Sie mit den Einrichtungen und Angeboten für Jugendliche?», Basel-Stadt, 2019",
		"lesehilfe": "41,6% der im Jahr 2019 Befragten sind sehr oder eher zufrieden mit den Angeboten für Jugendliche. 42,3% haben mit «Weiss nicht» geantwortet. Dieser Anteil ist aufgrund des Methodenwechsels deutlich höher als in den Vorjahren.",
		"erlaeuterungen": "Alle vier Jahre (bis 2007 alle zwei) wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit Angeboten für Jugendliche",
		"thema": "50 Befragungen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "2.2.5",
		"stufe1": "Zusammenhalt",
		"stufe2": "2.2 Dialog, Nachbarschaft und Kooperationen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_507",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:58",
		"id": 8279
	},
	{
		"template": "mappie001",
		"data-id": 8281,
		"chart-id": 8281,
		"filter": "",
		"parentId": null,
		"children": [
			8552
		],
		"title": "Sozialhilfequote der Minderjährigen",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2022",
		"lesehilfe": "Die Sozialhilfequote der Minderjährigen ist in Klybeck und Kleinhüningen mit je 17,5% am höchsten. Auf dem Bruderholz und in der Altstadt Grossbasel beträgt sie 1,7%.",
		"erlaeuterungen": "Die Sozialhilfequote zeigt den prozentualen Anteil der Sozialhilfebeziehenden an der jeweiligen Bevölkerungsgruppe gemäss Stand am Ende des Jahres. Als Sozialhilfebeziehende werden alle Personen gezählt, die im Verlaufe eines Jahres mindestens eine Leistung der Sozialhilfe erhalten haben. Es werden alle Beziehenden mit Dossiertyp Sozialhilfefall sowie Anerkannte Flüchtlinge (FL), Vorläufig Aufgenommene (VA) und Vorläufig aufgenommene Flüchtlinge (VA FL) mit einer Aufenthaltsdauer von mehr als fünf bzw. sieben Jahren (FL 5+, VA 7+, VA FL 7+) berücksichtigt<br>Die Berechnungsmethode wurde 2022 für die Jahre ab 2017 rückwirkend angepasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Sozialhilfequote der Minderjährigen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe",
		"kuerzel": "I.13.3.08281",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.1.3",
		"stufe1": "Leben",
		"stufe2": "1.1 Armut",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_103",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:32",
		"id": 8281
	},
	{
		"template": "dotplot",
		"data-id": 8283,
		"chart-id": 8283,
		"filter": "",
		"parentId": "4834",
		"children": [],
		"title": "Wohnfläche pro Kopf",
		"subtitle": "in m<sup>2</sup>, nach Wohnviertel, Basel-Stadt, 2023",
		"lesehilfe": "Im Wohnviertel Klybeck verfügen die Bewohner mit 33&nbsp;m<sup>2</sup> durchschnittlich über die geringste Wohnfläche pro Kopf, im Wohnviertel Altstadt Grossbasel mit 54&nbsp;m<sup>2</sup> über die höchste.",
		"erlaeuterungen": "Die mittlere Wohnfläche pro Kopf wird folgendermassen definiert: Gesamte Wohnfläche der durch Privatpersonen belegten Wohnungen und Mansarden geteilt durch das Total der dort wohnenden Personen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [
			"Diese Daten finden Sie auch im interaktiven <a href = 'https://basleratlas.ch/#c=indicator&i=09_bauwohnungswesen.mean_wfpk&view=map2' target = '_blank'>Basler Atlas</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnfläche pro Kopf",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.08283",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.4.5",
		"stufe1": "Leben",
		"stufe2": "1.4 Erhalt der Lebensgrundlagen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_04_00_00_00_605",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-05-06T07:28:42",
		"id": 8283
	},
	{
		"template": "mappie001",
		"data-id": 8285,
		"chart-id": 8285,
		"filter": "",
		"parentId": null,
		"children": [
			8556
		],
		"title": "Erreichbarkeit von Angeboten der Kinder- und Jugendarbeit",
		"subtitle": "Kinder mit Angeboten in Gehdistanz, nach Wohnviertel, Stadt Basel, 2020",
		"lesehilfe": "In den Kleinbasler Wohnvierteln Kleinhüningen, Klybeck, Matthäus, Clara und Altstadt Kleinbasel können 2020 über 90% aller Kinder und Jugendlichen ein altersspezifisches Angebot der offenen Kinder- und Jugendarbeit Basel-Stadt (OKJA) innerhalb von 10 Minuten zu Fuss erreichen. In den Wohnvierteln Bruderholz, St. Alban und Breite ist dies nur für weniger als 20% gegeben.",
		"erlaeuterungen": "Summe und Anteil der Kinder (5 bis 12 Jahre) und Jugendlichen (13 bis 17 Jahre) pro Wohnviertel (Stand Ende 2020), für welche die Angebote der OKJA (Stand Mai 2020) in Gehdistanz erreichbar sind. Berücksichtigt sind Angebote, welche mindestens zwei Tage und sechs Stunden pro Woche zur Verfügung stehen. Für jedes Angebot wurde entlang des Strassen- und Wegenetzes des Kantons Basel-Stadt ein Kerneinzugsgebiet berechnet, innerhalb dessen das zielgruppenspezifische Angebot für die jeweilige Zielgruppe gut zu Fuss erreichbar ist (Gehdistanz = innerhalb von ca. 10 Minuten zurücklegbare Distanz: Kinder: 600 m; Jugendliche: 850 m).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Erreichbarkeit von Angeboten der Kinder- und Jugendarbeit",
		"thema": "16 Kultur und Sport",
		"unterthema": "",
		"kuerzel": "I.16.TRPR.08285",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "2.2.8",
		"stufe1": "Zusammenhalt",
		"stufe2": "2.2 Dialog, Nachbarschaft und Kooperationen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_511",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:05:00",
		"id": 8285
	},
	{
		"template": "befragungenGrundauswertung001",
		"data-id": 8286,
		"chart-id": 8286,
		"filter": "",
		"parentId": null,
		"children": [
			8557
		],
		"title": "Zufriedenheit mit familienspezifischen Beratungs- und Bildungsangeboten",
		"subtitle": "«Wie zufrieden sind Sie mit den familienspezifischen Beratungs- oder Bildungsangeboten im Kanton Basel-Stadt?», Basel-Stadt, 2017",
		"lesehilfe": "Knapp 70% der befragten Familien sind mit den familienspezifischen Beratungs-/Bildungsangeboten «Eher zufrieden» oder «Sehr zufrieden». Gegenüber den Familienbefragungen von 2009 (56,3%) und 2013 (62,8%) ist dieser Anteil deutlich gestiegen.",
		"erlaeuterungen": "Die Familienbefragung wurde 2009 als kantonale Befragung eingeführt. Sie findet alle vier Jahre statt. Von insgesamt 5 000 zufällig ermittelten und angeschriebenen Familien haben 2017 1 665 Familien an der schriftlichen Befragung teilgenommen. Als Familie wird ein Haushalt definiert, in welchem mindestens ein Elternteil mit mindestens einem Kind unter 18 Jahren gemeinsam lebt. Ausgewählt werden zudem nur Familien, die seit mindestens einem Jahr im Kanton Basel-Stadt wohnen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Familienbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit familienspezifischen Beratungs- und Bildungsangeboten",
		"thema": "50 Befragungen",
		"unterthema": "Familienbefragung",
		"kuerzel": "I.50.2.08286",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.3.4",
		"stufe1": "Leben",
		"stufe2": "1.3 Chancengleichheit",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_305",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:43",
		"id": 8286
	},
	{
		"template": "line001",
		"data-id": 8287,
		"chart-id": 8287,
		"filter": "",
		"parentId": null,
		"children": [
			8558
		],
		"title": "Anzahl Straftaten im Bereich häusliche Gewalt",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2022 wurden 720 Straftaten im Bereich der häuslichen Gewalt polizeilich registriert.",
		"erlaeuterungen": "Unter häuslicher Gewalt wird die Anwendung oder Androhung von Gewalt unter Paaren in bestehender oder aufgelöster ehelicher oder partnerschaftlicher Beziehung, zwischen Eltern (auch Stief-/Pflegeeltern) und Kind oder zwischen weiteren Verwandten verstanden. Für die statistische Erfassung der häuslichen Gewalt wird in einer Auswahl von für den häuslichen Bereich relevanten Straftaten die Beziehung zwischen der beschuldigten und der geschädigten Person erfasst.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Polizeiliche Kriminalstatistik (PKS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Straftaten im Bereich häusliche Gewalt",
		"thema": "19 Kriminalität und Strafrecht",
		"unterthema": "Polizei",
		"kuerzel": "I.19.1.08287",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.2.4",
		"stufe1": "Leben",
		"stufe2": "1.2 Psychische Gesundheit",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_204",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:40",
		"id": 8287
	},
	{
		"template": "template001",
		"data-id": 8314,
		"chart-id": 8314,
		"filter": "",
		"parentId": null,
		"children": [
			8585
		],
		"title": "Sozialindex",
		"subtitle": "nach Wohnviertel, Stadt Basel",
		"lesehilfe": "Das Wohnviertel Bruderholz weist im Jahr 2021 mit 4,2 den höchsten Indexwert auf, das Wohnviertel Klybeck mit -4,6 den tiefsten.",
		"erlaeuterungen": "Der aus fünf ausgewählten Indikatoren berechnete Index erlaubt relative Vergleiche zwischen den verschiedenen Wohnvierteln und über die Zeit: Je weiter auseinander die Indexwerte der Wohnviertel liegen, desto unterschiedlicher sind die Wohnviertel bezüglich der fünf Indikatoren. <br>Der Index wird mittels Hauptkomponentenanalyse aus den folgenden Indikatoren ermittelt: Je höher der Anteil deutschsprachiger Personen und der Median des Reineinkommens und je tiefer die Arbeitslosen-, die Sozialhilfe- und die Prämienverbilligungsquote in einem Wohnviertel sind, desto höher ist der Indexwert. Die absoluten Werte des Index sind für einzelne Wohnviertel und Zeitstände ohne Vergleich mit anderen Wohnvierteln oder Zeitständen nicht interpretierbar.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt",
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)",
			"Staatssekretariat für Wirtschaft SECO, Arbeitslosenstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Sozialindex",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe",
		"kuerzel": "I.13.3.08314",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "1.1.9",
		"stufe1": "Leben",
		"stufe2": "1.1 Armut",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_110",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:36",
		"id": 8314
	},
	{
		"template": "befragungenGrundauswertung001",
		"data-id": 8325,
		"chart-id": 8325,
		"filter": "",
		"parentId": null,
		"children": [
			8596
		],
		"title": "Zufriedenheit mit Angeboten für ältere Menschen",
		"subtitle": "«Wie zufrieden sind Sie am aktuellen Wohnort mit den Angeboten und Einrichtungen für ältere Menschen?» Basel-Stadt, 2019",
		"lesehilfe": "58% der Befragten sind 2019 mit den Angeboten und Einrichtungen für ältere Menschen sehr oder eher zufrieden, 2011 waren es mit 56% etwas weniger.",
		"erlaeuterungen": "Seit 2011 wird alle vier Jahre im Kanton Basel-Stadt eine Bevölkerungsbefragung 55plus durchgeführt. Die Befragung richtet sich an Personen im Alter von mindestens 55 Jahren mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Befragung 55plus"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit Angeboten für ältere Menschen",
		"thema": "50 Befragungen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "CMS Kennzahlen Soziales",
		"kuerzelKunde": "2.2.6",
		"stufe1": "Zusammenhalt",
		"stufe2": "2.2 Dialog, Nachbarschaft und Kooperationen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_508",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-12T12:04:59",
		"id": 8325
	}
];