var indikatorensetData = [
	{
		"template": "map002",
		"data-id": 6373,
		"chart-id": 6373,
		"filter": "",
		"parentId": "4828",
		"children": [
			6385
		],
		"title": "Sesshaftigkeit",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2022",
		"lesehilfe": "In den Wohnvierteln Bruderholz (43,1%) und Bachletten (41,2%) sowie den Gemeinden Riehen (41,1%) und Bettingen (40,5%) sind die grössten Anteile sesshafter Personen zu finden. Die kleinsten Anteile gibt es  in den Wohnvierteln Altstadt Kleinbasel (28,0%), Vorstädte (27,4%) und Rosental (19,2%).",
		"erlaeuterungen": "Anteil der seit mindestens zehn Jahren an der gleichen Adresse wohnenden Personen an der gesamten Wohnbevölkerung des Wohnviertels in Prozent. Ohne Personen an administrativen Meldeadressen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [
			"Diese Daten finden Sie auch im interaktiven <a href = 'https://basleratlas.ch/#c=indicator&i=bevsess.anteil_sess10&view=map2' target = '_blank'>Basler Atlas</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Sesshaftigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.06373",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "C1-4",
		"stufe1": "kontinuierlich klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_004",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-05-09T08:26:50",
		"id": 6373
	},
	{
		"template": "map002",
		"data-id": 6374,
		"chart-id": 6374,
		"filter": "",
		"parentId": null,
		"children": [
			6386
		],
		"title": "Reinvermögen",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2020",
		"lesehilfe": "Der höchste Median des Reinvermögens 2020 wird mit rund 90 900 Franken in der Einwohnergemeinde Bettingen verzeichnet. Der Median für den ganzen Kanton beträgt ca. 21 600 Franken.",
		"erlaeuterungen": "Daten aus der Ordentlichen Veranlagung der natürlichen Personen in Basel-Stadt, Steuerjahr 2020; ohne Wochenaufenthalter, Unterjährige und Auswärtige. Eine Veranlagung kann zwei Personen umfassen. In Basel-Stadt wohnhafte Quellenbesteuerte mit Einkünften von unter 120 000 Franken pro Kalenderjahr sind in der Regel in den Auswertungen nicht erfasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik",
			"Kartengrundlage: Geodaten Kanton Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Reinvermögen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06374",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "C18-2",
		"stufe1": "kontinuierlich klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_012",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-07-31T11:05:05",
		"id": 6374
	},
	{
		"template": "mappie001",
		"data-id": 6375,
		"chart-id": 6375,
		"filter": "",
		"parentId": null,
		"children": [
			6387
		],
		"title": "Unter 20-Jährige nach Wohnviertel",
		"subtitle": "Basel-Stadt, 2022",
		"lesehilfe": "Am höchsten ist der Anteil der Personen unter 20 Jahren an der Gesamtbevölkerung im Wohnviertel Bruderholz (22,4%), am niedrigsten im Wohnviertel Altstadt Kleinbasel (9,3%).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Unter 20-Jährige nach Wohnviertel",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.06375",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "C1-1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_001",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-20T08:32:09",
		"id": 6375
	},
	{
		"template": "mappie001",
		"data-id": 6376,
		"chart-id": 6376,
		"filter": "",
		"parentId": null,
		"children": [
			6388
		],
		"title": "Über 64-Jährige nach Wohnviertel",
		"subtitle": "Basel-Stadt, 2022",
		"lesehilfe": "Den höchsten Anteil 65-Jähriger und Älterer an der Gesamtbevölkerung weist die Gemeinde Riehen (25,3%) auf, den niedrigsten das Wohnviertel Rosental (9,4%).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Über 64-Jährige nach Wohnviertel",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.06376",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "C1-2",
		"stufe1": "kontinuierlich klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_002",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-20T08:32:09",
		"id": 6376
	},
	{
		"template": "mappie001",
		"data-id": 6377,
		"chart-id": 6377,
		"filter": "",
		"parentId": null,
		"children": [
			6389
		],
		"title": "Gebäudedichte nach Wohnviertel",
		"subtitle": "Basel-Stadt, 2022",
		"lesehilfe": "Die grösste Gebäudedichte verzeichnet das Wohnviertel Gotthelf mit 20 bewohnbaren Gebäuden pro Hektare. Am geringsten fällt sie im Wohnviertel Kleinhüningen mit gut einem Gebäude pro Hektare aus. Ein hoher Anteil an Reiheneinfamilienhäusern im Gotthelfquartier sowie ein hoher Anteil an grossen Mehrfamilienhäusern wie auch an Industrie- und Gewerbebauten im Wohnviertel Kleinhüningen sind die Hauptgründe.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik",
			"Kartengrundlage: Geodaten Kanton Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Gebäudedichte nach Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.06377",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "C9-1",
		"stufe1": "kontinuierlich klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_007",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-23T08:27:47",
		"id": 6377
	},
	{
		"template": "mappie001",
		"data-id": 6378,
		"chart-id": 6378,
		"filter": "",
		"parentId": null,
		"children": [
			6390
		],
		"title": "Wohnungsdichte nach Wohnviertel",
		"subtitle": "Basel-Stadt, 2023",
		"lesehilfe": "Das Wohnviertel Matthäus weist mit rund 150 Wohnungen pro Hektare die höchste Wohnungsdichte auf. In der Einwohnergemeinde Bettingen ist die Dichte mit gut 2 Wohnungen pro Hektare am geringsten.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik",
			"Kartengrundlage: Geodaten Kanton Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnungsdichte nach Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.06378",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "C9-2",
		"stufe1": "kontinuierlich klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_008",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-11T08:32:39",
		"id": 6378
	},
	{
		"template": "mappie001",
		"data-id": 6379,
		"chart-id": 6379,
		"filter": "",
		"parentId": null,
		"children": [
			6391,
			8275,
			8546
		],
		"title": "Leerwohnungen nach Gemeinde und Wohnviertel",
		"subtitle": "Basel-Stadt, 2024",
		"lesehilfe": "Die höchste Leerwohnungsquote aller Wohnviertel wurde 2024 im Wohnviertel Altstadt Grossbasel (1,3%) beobachtet, die tiefste in der Gemeinde Bettingen (0,2%).",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Leerwohnungen nach Gemeinde und Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.06379",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "C9-3",
		"stufe1": "kontinuierlich klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_009",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-16T09:26:01",
		"id": 6379
	},
	{
		"template": "mappie001",
		"data-id": 6380,
		"chart-id": 6380,
		"filter": "",
		"parentId": null,
		"children": [
			6392
		],
		"title": "Sozialhilfequote und Sozialhilfebeziehende",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2023",
		"lesehilfe": "Die tiefste Sozialhilfequote im Kanton Basel-Stadt weist das Bruderholz mit 1,2% auf. Klybeck und Kleinhüningen sind mit je 9,8% die Wohnviertel mit der höchsten Sozialhilfequote.",
		"erlaeuterungen": "Die Sozialhilfequote zeigt den prozentualen Anteil der Sozialhilfebeziehenden an der jeweiligen Bevölkerungsgruppe gemäss Stand am Ende des Jahres. Als Sozialhilfebeziehende werden alle Personen gezählt, die im Verlaufe eines Jahres mindestens eine Leistung der Sozialhilfe erhalten haben. Es werden alle Beziehenden mit Dossiertyp Sozialhilfefall sowie Anerkannte Flüchtlinge (FL), Vorläufig Aufgenommene (VA) und Vorläufig aufgenommene Flüchtlinge (VA FL) mit einer Aufenthaltsdauer von mehr als fünf bzw. sieben Jahren (FL 5+, VA 7+, VA FL 7+) berücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Sozialhilfequote und Sozialhilfebeziehende",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe",
		"kuerzel": "I.13.3.06380",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "C13-1",
		"stufe1": "kontinuierlich klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_010",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-05-03T08:44:51",
		"id": 6380
	},
	{
		"template": "mappie002",
		"data-id": 6381,
		"chart-id": 6381,
		"filter": "",
		"parentId": null,
		"children": [
			6778
		],
		"title": "Ausländische Bevölkerung nach Wohnviertel",
		"subtitle": "Basel-Stadt, 2023",
		"lesehilfe": "Ende 2023 war der Ausländeranteil in den Wohnvierteln Rosental (58%),  Klybeck (53%) und Kleinhüningen (52%) am höchsten. Den niedrigsten Ausländeranteil wiesen die Wohnviertel Bachletten (24%),  Bruderholz (25%) sowie die Gemeinde Bettingen auf (25%). In den Wohnvierteln Klybeck und  Kleinhüningen bildeteten Italiener die grösste ausländische Bevölkerungsgruppe, in den übrigen Gemeinden und Wohnvierteln waren es Personen mit deutscher Staatsangehörigkeit.",
		"erlaeuterungen": "Ohne Personen an administrativen Meldeadressen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Kartengrundlage: Geodaten Kanton Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Ausländische Bevölkerung nach Wohnviertel",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.06381",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "C1-3",
		"stufe1": "kontinuierlich klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_003",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-04T11:56:32",
		"id": 6381
	},
	{
		"template": "map002",
		"data-id": 6382,
		"chart-id": 6382,
		"filter": "",
		"parentId": null,
		"children": [
			6394,
			8294,
			8565
		],
		"title": "Reineinkommen",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2020",
		"lesehilfe": "Der höchste Median des Reineinkommens 2020 liegt in der Einwohnergemeinde Bettingen vor und beträgt rund 72 800 Franken. Mit ca. 36 800 Franken verzeichnet das Wohnviertel Klybeck den tiefsten Wert.",
		"erlaeuterungen": "Daten aus der Ordentlichen Veranlagung der natürlichen Personen in Basel-Stadt, Steuerjahr 2020; ohne Wochenaufenthalter, Unterjährige und Auswärtige. Eine Veranlagung kann zwei Personen umfassen. In Basel-Stadt wohnhafte Quellenbesteuerte mit Einkünften von unter 120 000 Franken pro Kalenderjahr sind in der Regel in den Auswertungen nicht erfasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik",
			"Kartengrundlage: Geodaten Kanton Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Reineinkommen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06382",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "C18-1",
		"stufe1": "kontinuierlich klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_011",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-07-31T11:05:05",
		"id": 6382
	},
	{
		"template": "mappie001",
		"data-id": 6383,
		"chart-id": 6383,
		"filter": "",
		"parentId": null,
		"children": [
			6395
		],
		"title": "Arbeitsstätten nach Wohnviertel",
		"subtitle": "Basel-Stadt, 2021",
		"lesehilfe": "Das Wohnviertel Altstadt Grossbasel weist mit rund 57 Arbeitsstätten pro 100 Einwohner den höchsten Wert auf, das Wohnviertel Hirzbrunnen mit rund 3 Arbeitsstätten pro 100 Einwohner den tiefsten.",
		"erlaeuterungen": "Eine Arbeitsstätte ist ein an einem bestimmten Ort gelegenes Unternehmen (Einzelunternehmen) oder Teil eines Unternehmens (z. B. Werkstatt, Werk, Verkaufsladen, Büro, Dienststelle, Lager). An diesem Ort arbeiten eine oder mehrere Personen für dasselbe Unternehmen. Berücksichtigt werden alle Arbeitsstätten, die der AHV-Beitragspflicht unterstehen (ab 2 300 Franken Jahreslohn). Bei Unternehmen mit mehreren Arbeitsstätten wird die Struktur gemäss Angaben der Unternehmen erfasst. Dabei ist nicht auszuschliessen, dass es sich bei der Verteilung auf die verschiedenen Arbeitsstätten teilweise um rein administrative Zuordnungen handeln kann und nicht alle effektiv vorhandenen Arbeitsstätten abgebildet sind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt",
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)",
			"Kartengrundlage: Geodaten Kanton Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Arbeitsstätten nach Wohnviertel",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.06383",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "C3-2",
		"stufe1": "kontinuierlich klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_006",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-12-20T09:16:18",
		"id": 6383
	},
	{
		"template": "mappie001",
		"data-id": 6384,
		"chart-id": 6384,
		"filter": "",
		"parentId": null,
		"children": [
			6396
		],
		"title": "Beschäftigte nach Wohnviertel",
		"subtitle": "Basel-Stadt, 2021",
		"lesehilfe": "Das Wohnviertel Vorstädte weist mit rund 604 Beschäftigten pro 100 Einwohner den höchsten Wert auf, das Wohnviertel Bruderholz mit rund 19 Beschäftigten pro 100 Einwohner den tiefsten.",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und dafür einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Referenzperiode ist jeweils der Dezember des Jahres. Bei Unternehmen mit mehreren Arbeitsstätten werden die Beschäftigten gemäss Angaben der Unternehmen auf die verschiedenen Arbeitsstätten verteilt. Dabei ist nicht auszuschliessen, dass es sich teilweise um rein administrative Zuordnungen handeln kann und nicht alle Beschäftigten effektiv an dieser Arbeitsstätte bzw. Adresse tätig sind. Im Wohnviertel St. Johann sind auch die Beschäftigten im Schweizer Sektor des EuroAirports enthalten.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt",
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)",
			"Kartengrundlage: Geodaten Kanton Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Beschäftigte nach Wohnviertel",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.06384",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "C3-1",
		"stufe1": "kontinuierlich klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_005",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-12-20T09:16:17",
		"id": 6384
	},
	{
		"template": "map002",
		"data-id": 6385,
		"chart-id": 6385,
		"filter": "",
		"parentId": "6373",
		"children": [],
		"title": "Sesshaftigkeit",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2022",
		"lesehilfe": "In den Wohnvierteln Bruderholz (43,1%) und Bachletten (41,2%) sowie den Gemeinden Riehen (41,1%) und Bettingen (40,5%) sind die grössten Anteile sesshafter Personen zu finden. Die kleinsten Anteile gibt es  in den Wohnvierteln Altstadt Kleinbasel (28,0%), Vorstädte (27,4%) und Rosental (19,2%).",
		"erlaeuterungen": "Anteil der seit mindestens zehn Jahren an der gleichen Adresse wohnenden Personen an der gesamten Wohnbevölkerung des Wohnviertels in Prozent. Ohne Personen an administrativen Meldeadressen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [
			"Diese Daten finden Sie auch im interaktiven <a href = 'https://basleratlas.ch/#c=indicator&i=bevsess.anteil_sess10&view=map2' target = '_blank'>Basler Atlas</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Sesshaftigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.06385",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "K1-4",
		"stufe1": "kategoriell klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_004",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-05-09T08:26:59",
		"id": 6385
	},
	{
		"template": "map002",
		"data-id": 6386,
		"chart-id": 6386,
		"filter": "",
		"parentId": "6374",
		"children": [],
		"title": "Reinvermögen",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2020",
		"lesehilfe": "Der höchste Median des Reinvermögens 2020 wird mit rund 90 900 Franken in der Einwohnergemeinde Bettingen verzeichnet. Der Median für den ganzen Kanton beträgt ca. 21 600 Franken.",
		"erlaeuterungen": "Daten aus der Ordentlichen Veranlagung der natürlichen Personen in Basel-Stadt, Steuerjahr 2020; ohne Wochenaufenthalter, Unterjährige und Auswärtige. Eine Veranlagung kann zwei Personen umfassen. In Basel-Stadt wohnhafte Quellenbesteuerte mit Einkünften von unter 120 000 Franken pro Kalenderjahr sind in der Regel in den Auswertungen nicht erfasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik",
			"Kartengrundlage: Geodaten Kanton Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Reinvermögen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06386",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "K18-2",
		"stufe1": "kategoriell klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_012",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-07-31T11:05:06",
		"id": 6386
	},
	{
		"template": "mappie001",
		"data-id": 6387,
		"chart-id": 6387,
		"filter": "",
		"parentId": "6375",
		"children": [],
		"title": "Unter 20-Jährige nach Wohnviertel",
		"subtitle": "Basel-Stadt, 2022",
		"lesehilfe": "Am höchsten ist der Anteil der Personen unter 20 Jahren an der Gesamtbevölkerung im Wohnviertel Bruderholz (22,4%), am niedrigsten im Wohnviertel Altstadt Kleinbasel (9,3%).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Unter 20-Jährige nach Wohnviertel",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.06387",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "K1-1",
		"stufe1": "kategoriell klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_001",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-20T08:32:11",
		"id": 6387
	},
	{
		"template": "mappie001",
		"data-id": 6388,
		"chart-id": 6388,
		"filter": "",
		"parentId": "6376",
		"children": [],
		"title": "Über 64-Jährige nach Wohnviertel",
		"subtitle": "Basel-Stadt, 2022",
		"lesehilfe": "Den höchsten Anteil 65-Jähriger und Älterer an der Gesamtbevölkerung weist die Gemeinde Riehen (25,3%) auf, den niedrigsten das Wohnviertel Rosental (9,4%).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Über 64-Jährige nach Wohnviertel",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.06388",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "K1-2",
		"stufe1": "kategoriell klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_002",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-20T08:32:11",
		"id": 6388
	},
	{
		"template": "mappie001",
		"data-id": 6389,
		"chart-id": 6389,
		"filter": "",
		"parentId": "6377",
		"children": [],
		"title": "Gebäudedichte nach Wohnviertel",
		"subtitle": "Basel-Stadt, 2022",
		"lesehilfe": "Die grösste Gebäudedichte verzeichnet das Wohnviertel Gotthelf mit 20 bewohnbaren Gebäuden pro Hektare. Am geringsten fällt sie im Wohnviertel Kleinhüningen mit gut einem Gebäude pro Hektare aus. Ein hoher Anteil an Reiheneinfamilienhäusern im Gotthelfquartier sowie ein hoher Anteil an grossen Mehrfamilienhäusern wie auch an Industrie- und Gewerbebauten im Wohnviertel Kleinhüningen sind die Hauptgründe.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik",
			"Kartengrundlage: Geodaten Kanton Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Gebäudedichte nach Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.06389",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "K9-1",
		"stufe1": "kategoriell klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_007",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-23T08:27:52",
		"id": 6389
	},
	{
		"template": "mappie001",
		"data-id": 6390,
		"chart-id": 6390,
		"filter": "",
		"parentId": "6378",
		"children": [],
		"title": "Wohnungsdichte nach Wohnviertel",
		"subtitle": "Basel-Stadt, 2023",
		"lesehilfe": "Das Wohnviertel Matthäus weist mit rund 150 Wohnungen pro Hektare die höchste Wohnungsdichte auf. In der Einwohnergemeinde Bettingen ist die Dichte mit gut 2 Wohnungen pro Hektare am geringsten.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik",
			"Kartengrundlage: Geodaten Kanton Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnungsdichte nach Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.06390",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "K9-2",
		"stufe1": "kategoriell klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_008",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-11T08:32:40",
		"id": 6390
	},
	{
		"template": "mappie001",
		"data-id": 6391,
		"chart-id": 6391,
		"filter": "",
		"parentId": "6379",
		"children": [],
		"title": "Leerwohnungen nach Gemeinde und Wohnviertel",
		"subtitle": "Basel-Stadt, 2024",
		"lesehilfe": "Die höchste Leerwohnungsquote aller Wohnviertel wurde 2024 im Wohnviertel Altstadt Grossbasel (1,3%) beobachtet, die tiefste in der Gemeinde Bettingen (0,2%).",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Leerwohnungen nach Gemeinde und Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "K9-3",
		"stufe1": "kategoriell klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_009",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-16T10:22:46",
		"id": 6391
	},
	{
		"template": "mappie001",
		"data-id": 6392,
		"chart-id": 6392,
		"filter": "",
		"parentId": "6380",
		"children": [
			8241,
			8512
		],
		"title": "Sozialhilfequote und Sozialhilfebeziehende",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2022",
		"lesehilfe": "Die tiefste Sozialhilfequote im Kanton Basel-Stadt weist das Bruderholz mit 1,5% auf. In der Altstadt Grossbasel, Bettingen und dem Bachletten liegt sie ebenfalls unter 2%. Klybeck und Kleinhüningen sind mit 10,6% respektive 10,3% die Wohnviertel mit der höchsten Sozialhilfequote.",
		"erlaeuterungen": "Die Sozialhilfequote zeigt den prozentualen Anteil der Sozialhilfebeziehenden an der jeweiligen Bevölkerungsgruppe gemäss Stand am Ende des Jahres. Als Sozialhilfebeziehende werden alle Personen gezählt, die im Verlaufe eines Jahres mindestens eine Leistung der Sozialhilfe erhalten haben. Es werden alle Beziehenden mit Dossiertyp Sozialhilfefall sowie Anerkannte Flüchtlinge (FL), Vorläufig Aufgenommene (VA) und Vorläufig aufgenommene Flüchtlinge (VA FL) mit einer Aufenthaltsdauer von mehr als fünf bzw. sieben Jahren (FL 5+, VA 7+, VA FL 7+) berücksichtigt.<br>Die Berechnungsmethode wurde 2022 für die Jahre ab 2017 rückwirkend angepasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Sozialhilfequote und Sozialhilfebeziehende",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe und Notwohnen",
		"kuerzel": "I.13.3.06392",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "K13-1",
		"stufe1": "kategoriell klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_010",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-05-25T07:08:48",
		"id": 6392
	},
	{
		"template": "map002",
		"data-id": 6394,
		"chart-id": 6394,
		"filter": "",
		"parentId": "6382",
		"children": [],
		"title": "Reineinkommen",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2020",
		"lesehilfe": "Der höchste Median des Reineinkommens 2020 liegt in der Einwohnergemeinde Bettingen vor und beträgt rund 72 800 Franken. Mit ca. 36 800 Franken verzeichnet das Wohnviertel Klybeck den tiefsten Wert.",
		"erlaeuterungen": "Daten aus der Ordentlichen Veranlagung der natürlichen Personen in Basel-Stadt, Steuerjahr 2020; ohne Wochenaufenthalter, Unterjährige und Auswärtige. Eine Veranlagung kann zwei Personen umfassen. In Basel-Stadt wohnhafte Quellenbesteuerte mit Einkünften von unter 120 000 Franken pro Kalenderjahr sind in der Regel in den Auswertungen nicht erfasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik",
			"Kartengrundlage: Geodaten Kanton Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Reineinkommen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06394",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "K18-1",
		"stufe1": "kategoriell klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_011",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-07-31T11:05:06",
		"id": 6394
	},
	{
		"template": "mappie001",
		"data-id": 6395,
		"chart-id": 6395,
		"filter": "",
		"parentId": "6383",
		"children": [],
		"title": "Arbeitsstätten nach Wohnviertel",
		"subtitle": "Basel-Stadt, 2021",
		"lesehilfe": "Das Wohnviertel Altstadt Grossbasel weist mit rund 57 Arbeitsstätten pro 100 Einwohner den höchsten Wert auf, das Wohnviertel Hirzbrunnen mit rund 3 Arbeitsstätten pro 100 Einwohner den tiefsten.",
		"erlaeuterungen": "Eine Arbeitsstätte ist ein an einem bestimmten Ort gelegenes Unternehmen (Einzelunternehmen) oder Teil eines Unternehmens (z. B. Werkstatt, Werk, Verkaufsladen, Büro, Dienststelle, Lager). An diesem Ort arbeiten eine oder mehrere Personen für dasselbe Unternehmen. Berücksichtigt werden alle Arbeitsstätten, die der AHV-Beitragspflicht unterstehen (ab 2 300 Franken Jahreslohn). Bei Unternehmen mit mehreren Arbeitsstätten wird die Struktur gemäss Angaben der Unternehmen erfasst. Dabei ist nicht auszuschliessen, dass es sich bei der Verteilung auf die verschiedenen Arbeitsstätten teilweise um rein administrative Zuordnungen handeln kann und nicht alle effektiv vorhandenen Arbeitsstätten abgebildet sind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt",
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)",
			"Kartengrundlage: Geodaten Kanton Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Arbeitsstätten nach Wohnviertel",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.06395",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "K3-2",
		"stufe1": "kategoriell klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_006",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-12-20T09:16:20",
		"id": 6395
	},
	{
		"template": "mappie001",
		"data-id": 6396,
		"chart-id": 6396,
		"filter": "",
		"parentId": "6384",
		"children": [],
		"title": "Beschäftigte nach Wohnviertel",
		"subtitle": "Basel-Stadt, 2021",
		"lesehilfe": "Das Wohnviertel Vorstädte weist mit rund 604 Beschäftigten pro 100 Einwohner den höchsten Wert auf, das Wohnviertel Bruderholz mit rund 19 Beschäftigten pro 100 Einwohner den tiefsten.",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und dafür einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Referenzperiode ist jeweils der Dezember des Jahres. Bei Unternehmen mit mehreren Arbeitsstätten werden die Beschäftigten gemäss Angaben der Unternehmen auf die verschiedenen Arbeitsstätten verteilt. Dabei ist nicht auszuschliessen, dass es sich teilweise um rein administrative Zuordnungen handeln kann und nicht alle Beschäftigten effektiv an dieser Arbeitsstätte bzw. Adresse tätig sind. Im Wohnviertel St. Johann sind auch die Beschäftigten im Schweizer Sektor des EuroAirports enthalten.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt",
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)",
			"Kartengrundlage: Geodaten Kanton Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Beschäftigte nach Wohnviertel",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.06396",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "K3-1",
		"stufe1": "kategoriell klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_005",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-12-20T09:16:19",
		"id": 6396
	},
	{
		"template": "mappie002",
		"data-id": 6778,
		"chart-id": 6778,
		"filter": "",
		"parentId": "6381",
		"children": [],
		"title": "Ausländische Bevölkerung nach Wohnviertel",
		"subtitle": "Basel-Stadt, 2023",
		"lesehilfe": "Ende 2023 war der Ausländeranteil in den Wohnvierteln Rosental (58%),  Klybeck (53%) und Kleinhüningen (52%) am höchsten. Den niedrigsten Ausländeranteil wiesen die Wohnviertel Bachletten (24%),  Bruderholz (25%) sowie die Gemeinde Bettingen auf (25%). In den Wohnvierteln Klybeck und  Kleinhüningen bildeteten Italiener die grösste ausländische Bevölkerungsgruppe, in den übrigen Gemeinden und Wohnvierteln waren es Personen mit deutscher Staatsangehörigkeit.",
		"erlaeuterungen": "Ohne Personen an administrativen Meldeadressen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Kartengrundlage: Geodaten Kanton Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Ausländische Bevölkerung nach Wohnviertel",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.06778",
		"kennzahlenset": "Gefragte Karten",
		"kuerzelKunde": "K1-3",
		"stufe1": "kategoriell klassifiziert",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_003",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-04T11:56:33",
		"id": 6778
	}
];