var indikatorensetData = [
	{
		"template": "template001",
		"data-id": 4947,
		"chart-id": 4947,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Hospitalisierungen in baselstädtischen Spitälern",
		"subtitle": "nach Hauptbereich",
		"lesehilfe": "Im Jahr 2023 wurden 78 200 Fälle aus einer akutsomatischen Station entlassen.",
		"erlaeuterungen": "Gezählt werden stationäre Austritte aus einem baselstädtischen Spital innerhalb eines Jahres. Seit 2020 gelten nur noch Langzeitpflegefälle als Geriatrie-Fälle. Aufgrund einer geänderten Kodierungsvorgabe werden die Fälle der Akutgeriatrie der Inneren Medizin und somit der Akutsomatik zugeordnet.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik",
			"Bundesamt für Statistik (BFS), Medizinische Statistik der Krankenhäuser"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Hospitalisierungen in baselstädtischen Spitälern",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.4947",
		"kennzahlenset": "Gesundheit",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-22T09:29:54",
		"id": 4947
	},
	{
		"template": "line001",
		"data-id": 6991,
		"chart-id": 6991,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mittlere Aufenthaltsdauer in Spitälern nach Alter",
		"subtitle": "im Hauptbereich Akutsomatik in Tagen, Basel-Stadt",
		"lesehilfe": "Im Jahr 2023 hielten sich die 99-jährigen Personen mit durchschnittlich 9,1 Tagen am längsten in einem Basler Spital auf.",
		"erlaeuterungen": "Es werden alle stationär behandelten Patienten berücksichtigt, welche im Erhebungsjahr aus einem baselstädtischen Spital ausgetreten sind (mehrfach hospitalisierte Personen werden mehrfach gezählt). Gezählt werden die in Anspruch genommenen Pflegetage, abzüglich Zwischenaustritte (z. B. Ferien). Personen im Alter von 100 und mehr Jahren werden zusammengefasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittlere Aufenthaltsdauer in Spitälern nach Alter",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.06991",
		"kennzahlenset": "Gesundheit",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-22T09:30:05",
		"id": 6991
	},
	{
		"template": "line001",
		"data-id": 6992,
		"chart-id": 6992,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mittlere Aufenthaltsdauer in Spitälern nach Alter und Geschlecht",
		"subtitle": "im Hauptbereich Akutsomatik in Tagen, Basel-Stadt, 2023",
		"lesehilfe": "Im Jahr 2023 hielten sich Frauen im Alter von 13 Jahren mit 12,2 Tagen im Durchschnitt am längsten in einem baselstädtischen Spital auf.",
		"erlaeuterungen": "Es werden alle stationär behandelten Patienten berücksichtigt, welche im Erhebungsjahr aus einem baselstädtischen Spital ausgetreten sind (mehrfach hospitalisierte Personen werden mehrfach gezählt). Gezählt werden die in Anspruch genommenen Pflegetage, abzüglich Zwischenaustritte (z. B. Ferien). Personen im Alter von 100 und mehr Jahren werden zusammengefasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittlere Aufenthaltsdauer in Spitälern nach Alter und Geschlecht",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.06992",
		"kennzahlenset": "Gesundheit",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-22T09:30:06",
		"id": 6992
	},
	{
		"template": "line001",
		"data-id": 6993,
		"chart-id": 6993,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mittlere Aufenthaltsdauer in Spitälern",
		"subtitle": "nach Hauptbereich in Tagen, Basel-Stadt",
		"lesehilfe": "Über den gesamten Beobachtungszeitraum weisen psychiatrische Fälle im Schnitt die längste mittlere Aufenthaltsdauer auf (2023: 38,5 Tage), während ein akutsomatischer Patient das Spital deutlich schneller verlässt (2023: 6,7 Tage).",
		"erlaeuterungen": "Es werden alle stationär behandelten Patienten berücksichtigt, welche im Erhebungsjahr aus einem baselstädtischen Spital ausgetreten sind (mehrfach hospitalisierte Personen werden mehrfach gezählt). Gezählt werden die in Anspruch genommenen Pflegetage, abzüglich Zwischenaustritte (z. B. Ferien).<br>Seit 2020 werden aufgrund einer geänderten Kodierungsvorgabe die Fälle der Akutgeriatrie der Inneren Medizin und somit der Akutsomatik zugeordnet. Die Geriatrie wird daher nicht ausgewiesen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittlere Aufenthaltsdauer in Spitälern",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.06993",
		"kennzahlenset": "Gesundheit",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-22T09:30:07",
		"id": 6993
	},
	{
		"template": "line001",
		"data-id": 6997,
		"chart-id": 6997,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Stationär behandelte Patienten",
		"subtitle": "in baselstädtischen Spitälern, nach Geschlecht und Alter, 2023",
		"lesehilfe": "Es werden deutlich mehr Frauen im gebärfähigen Alter stationär behandelt als gleichaltrige Männer. Dafür werden in den Altersjahren zwischen 53 und 77 mehr männliche Patienten registriert. Anschliessend überwiegen wieder die Frauen.",
		"erlaeuterungen": "Es werden alle stationär behandelten Patienten (ohne Neugeborene) berücksichtigt, welche im Erhebungsjahr mindestens einmal aus einem baselstädtischen Spital ausgetreten sind (mehrfach hospitalisierte Personen werden nur einmal gezählt). Personen im Alter von 100 und mehr Jahren werden zusammengefasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Stationär behandelte Patienten",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.06997",
		"kennzahlenset": "Gesundheit",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-22T09:29:55",
		"id": 6997
	},
	{
		"template": "line001",
		"data-id": 6998,
		"chart-id": 6998,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Neugeborene nach Alter der Mutter",
		"subtitle": "in baselstädtischen Spitälern, 2023",
		"lesehilfe": "Im Jahr 2023 haben die 34-jährigen Mütter die meisten Babys zur Welt gebracht (392), gefolgt von den 33-jährigen Müttern (368).",
		"erlaeuterungen": "Es werden alle Neugeborenen berücksichtigt, welche im Erhebungsjahr in einer stationären Einrichtung im Kanton Basel-Stadt zur Welt gekommen sind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Neugeborene nach Alter der Mutter",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.06998",
		"kennzahlenset": "Gesundheit",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-22T09:29:56",
		"id": 6998
	},
	{
		"template": "line001",
		"data-id": 6999,
		"chart-id": 6999,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Patienten nach Liege- und Altersklasse",
		"subtitle": "in baselstädtischen Spitälern, 2023",
		"lesehilfe": "Im Jahr 2023 wurden insgesamt 12 264 Personen im Alter zwischen 70 und 79 Jahren in einem baselstädtischen Spital stationär behandelt. Am häufigsten lagen die Patienten über alle Altersgruppen hinweg auf einer allgemeinen Abteilung des Spitals.",
		"erlaeuterungen": "Es werden alle stationär behandelten Patienten berücksichtigt, welche im Erhebungsjahr mindestens einmal aus einem baselstädtischen Spital ausgetreten sind (mehrfach hospitalisierte Personen werden nur einmal gezählt).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik",
			"Bundesamt für Statistik (BFS), Medizinische Statistik der Krankenhäuser"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Patienten nach Liege- und Altersklasse",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.06999",
		"kennzahlenset": "Gesundheit",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-22T09:29:57",
		"id": 6999
	},
	{
		"template": "template001",
		"data-id": 7000,
		"chart-id": 7000,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Aufenthaltsorte nach dem Spitalaustritt",
		"subtitle": "aus baselstädtischen Spitälern, nach Alter der Patienten, 2023",
		"lesehilfe": "Über 51% der Personen im Alter von mindestens 80 Jahren konnten im Jahr 2023 nach einer stationären Behandlung in einem baselstädtischen Spital wieder nach Hause. Etwa 16% der Patienten in dieser Altersklasse begaben sich nach einem stationären Spitalaufenthalt in eine Rehabilitationsklinik.",
		"erlaeuterungen": "Gezählt werden alle Patienten, welche nach einem stationären Aufenthalt aus einem baselstädtischen Spital ausgetreten sind. Ein Patient wird dabei mehrfach gezählt, wenn er mehrfach in stationärer Behandlung war.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik",
			"Bundesamt für Statistik (BFS), Medizinische Statistik der Krankenhäuser"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Aufenthaltsorte nach dem Spitalaustritt",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.07000",
		"kennzahlenset": "Gesundheit",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-22T09:29:58",
		"id": 7000
	},
	{
		"template": "line001",
		"data-id": 7710,
		"chart-id": 7710,
		"filter": "",
		"parentId": null,
		"children": [
			7948
		],
		"title": "Verlorene potentielle Lebensjahre",
		"subtitle": "je 100 000 Einwohner, Basel-Stadt",
		"lesehilfe": "Seit 1993 sind die verlorenen potentiellen Lebensjahre (VPL) im Kanton Basel-Stadt gesunken, wobei die VPL der Männer seit 2017 tendenziell wieder bis 2022 gestiegen sind. 2023 waren es bei den Männern 4 193 VPL und bei den Frauen 2 607.",
		"erlaeuterungen": "Anzahl verlorene potentielle Lebensjahre (VPL) je 100 000 Einwohner (ständige Wohnbevölkerung) für Todesfälle zwischen der Geburt und 75 Jahren. Zur Berechnung der VPL werden die bis zu einer festgelegten Altersgrenze verbleibenden Lebensjahre pro Altersgruppe addiert und gemäss der Altersstruktur gewichtet. Als Altersgrenze wurde hier 75 Jahre gewählt, aus Gründen der Vergleichbarkeit beispielsweise mit dem Indikator des Schweizerischen Gesundheitsobservatoriums (Obsan). Ein Todesfall im Alter von 65 Jahren entspricht damit 10 potentiell verlorenen Lebensjahren. Todesfälle nach der Vollendung des 75. Lebensjahres fliessen nicht in die Berechnung ein. Damit die VPL zwischen Männern und Frauen sowie den verschiedenen Jahren vergleichbar sind, wurden sie nach der Altersstruktur der baselstädtischen Bevölkerung im Jahr 2010 standardisiert.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Verlorene potentielle Lebensjahre",
		"thema": "14 Gesundheit",
		"unterthema": "Sterblichkeit",
		"kuerzel": "I.14.3.07710",
		"kennzahlenset": "Gesundheit",
		"kuerzelKunde": "",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-22T09:30:00",
		"id": 7710
	}
];