var indikatorensetData = [
	{
		"template": "map001",
		"data-id": 11165,
		"chart-id": 11165,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Pflegeheime",
		"subtitle": "Anzahl Plätze, Basel-Stadt, 2025",
		"lesehilfe": "Anfang 2025 hatte das Adullam Pflegezentrum Basel 135 Plätze.",
		"erlaeuterungen": "Zusätzliche 30 Pflegeplätze des Pflegezentrums Adullam Basel (Nr. 1) sind auf der Pflegeheimliste Basel-Landschaft aufgeführt. Der Umzug des Dominikushauses (Nr. 17) in den Neubau an der Immenbachstrasse 17 in Riehen erfolgte im Sommer 2023. Am eigentlichen Standort des Pflegezentrums irides (Nr. 22) an der Kohlenbergstrasse 20 in Basel entsteht ein Neubau.<br><br>Stand Anfang 2025",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.bs.ch/gd/bereich-gesundheitsversorgung/alters-und-langzeitpflege/angebote-der-alters-und-langzeitpflege#pflegeheime-basel-stadt' target = '_blank'>Aktuelle Pflegeheimliste</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Pflegeheime",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.1",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.1 Karten",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_001",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-30T12:02:58",
		"id": 11165
	},
	{
		"template": "map001",
		"data-id": 11166,
		"chart-id": 11166,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Tages- und Nachtpflegeeinrichtungen",
		"subtitle": "Anzahl Plätze, Basel-Stadt, 2025",
		"lesehilfe": "Anfang 2025  bot das Tagesheim Wendelin in Riehen 21 Plätze der Kategorie Allgemeine Tagespflegeeinrichtungen an.",
		"erlaeuterungen": "Spezialisierte Tagespflegeinrichtungen dienen der Betreuung von an Demenz erkrankten oder psychisch beeinträchtigten Personen.<br>Seit 2020 gibt es aufgrund zu geringer Nachfrage kein Nachtpflegeangebot mehr.<br><br>Stand Anfang 2025",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.bs.ch/themen/persoenliches-und-wohnen/wohnen/wohnen-im-alter/zuhause-mit-unterstuetzung-wohnen#tagespflegeeinrichtungen' target = '_blank'>Aktuelle Liste der Anbieter von Tagespflegeeinrichtungen</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Tages- und Nachtpflegeeinrichtungen",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.9",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.1 Karten",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_009",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-15T09:06:13",
		"id": 11166
	},
	{
		"template": "map001",
		"data-id": 11167,
		"chart-id": 11167,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnungen mit Service-Angebot",
		"subtitle": "Anzahl Wohnungen, Basel-Stadt, 2025",
		"lesehilfe": "Anfang 2025 hatte das Tertianum 107 Wohnungen mit Service-Angebot.",
		"erlaeuterungen": "Wohnungen mit Service-Angebot sind ein Angebot von Pflegeheimen im Bereich der ambulanten Unterstützung betagter Menschen. Wohnungen mit Leistungsvereinbarung richten sich in erster Linie an einkommensschwache ältere Menschen. Der Leistungsauftrag mit dem Kanton Basel-Stadt umschreibt dabei das minimale Grundangebot an Dienstleistungen, welche vom Pflegeheim für die Mietenden der Wohnungen angeboten werden müssen (24-Stunden-Notrufbereitschaft, eine Grundberatung sowie einen täglichen Kurzkontakt) sowie die maximale Monatstaxe.<br><br>Das Angebot des Adullam Basel wurde per 1.1.2025 aufgelöst.<br><br>Stand Anfang 2025",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.bs.ch/themen/persoenliches-und-wohnen/wohnen/wohnen-im-alter/zuhause-mit-unterstuetzung-wohnen#wohnen-mit-serviceangeboten' target = '_blank'>Angebote von Wohnungen mit Service-Angebot</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungen mit Service-Angebot",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.23",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.1 Karten",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_023",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-15T09:06:12",
		"id": 11167
	},
	{
		"template": "line001",
		"data-id": 11168,
		"chart-id": 11168,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Spitex-Anbieter",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2024 gab es im Kanton Basel-Stadt 59 Organisationen sowie 58 Einzelpersonen, welche eine Spitex-Dienstleistung angeboten haben. Sie alle verfügen über eine Bewilligung zu Ausübung und Abrechnung von Spitex-Leistungen.",
		"erlaeuterungen": "Stand Ende 2024",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.bs.ch/gesundheitsdepartement/bereich-gesundheitsversorgung/alters-und-langzeitpflege/angebote-der-alters#spitexanbieter' target = '_blank'>Liste der zugelassenen Spitex-Organisationen und -Einzelpersonen</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Spitex-Anbieter",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.17",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_017",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-15T09:06:09",
		"id": 11168
	},
	{
		"template": "line001",
		"data-id": 11169,
		"chart-id": 11169,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil allgemeiner Pflegeheimplätze und spezieller Wohnformen in Pflegeheimen",
		"subtitle": "in baselstädtischen Pflegeheimen",
		"lesehilfe": "Anfang 2025 gab es 606 Plätze in speziellen Wohnformen (20,2% aller Plätze) in den Pflegeheimen und 2 235 (74,5%) allgemeine Pflegeheimplätze im Kanton Basel-Stadt.",
		"erlaeuterungen": "Spezielle Wohnformen sind beispielsweise Pflegewohngruppen, psychogeriatrische Spezialeinrichtungen, Demenzabteilungen oder besondere Pflegeeinrichtungen für suchtkranke Menschen. Nichttarifplätze sind Plätze, welche nicht an die Einheitstaxe gemäss Pflegeheim-Rahmenvertrag gebunden sind.<br><br>Die Aktualisierung der Daten erfolgt jeweils am Anfang und am Ende des aktuellen Jahres.<br><br>Stand Anfang 2025",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.bs.ch/gesundheitsdepartement/bereich-gesundheitsversorgung/alters-und-langzeitpflege/angebote-der-alters#pflegeheime-basel-stadt' target = '_blank'>Aktuelle Pflegeheimliste</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil allgemeiner Pflegeheimplätze und spezieller Wohnformen in Pflegeheimen",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.2",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-06T08:02:02",
		"id": 11169
	},
	{
		"template": "line001",
		"data-id": 11170,
		"chart-id": 11170,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Plätze in Tages- und Nachtpflegeeinrichtungen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Anfang 2025 standen insgesamt 170 Plätze in Tages- und Nachpflegeeinrichtungen – davon 62 spezialisierte – zur Verfügung.",
		"erlaeuterungen": "Spezialisierte Tagespflegeinrichtungen dienen der Betreuung von an Demenz erkrankten oder psychisch beeinträchtigten Personen.<br>Seit 2020 gibt es aufgrund zu geringer Nachfrage kein Nachtpflegeangebot mehr.<br><br>Die Daten werden jeweils am Anfang und am Ende des aktuellen Jahres aktualisiert.<br><br>Stand Anfang 2025",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.bs.ch/themen/persoenliches-und-wohnen/wohnen/wohnen-im-alter/zuhause-mit-unterstuetzung-wohnen#tagespflegeeinrichtungen' target = '_blank'>Aktuelle List der Anbieter von Tagespflegeeinrichtungen</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Plätze in Tages- und Nachtpflegeeinrichtungen",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.10",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-15T09:06:07",
		"id": 11170
	},
	{
		"template": "line001",
		"data-id": 11171,
		"chart-id": 11171,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Pensions- und Pflegetage in Pflegeheimen und deren Auslastung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2024 ist die Auslastung im Vergleich zum Vorjahr gestiegen und beträgt in den Pflegeheimen 95,6%. Die Pensions- und Pflegetage beliefen sich 2024 auf über 1 Million.",
		"erlaeuterungen": "Auslastung ohne Pflegetage in ausserkantonalen Pflegeheimen. Die Auslastung berechnet sich wie folgt: Die Anzahl der abgerechneten Pensions- und Pflegetage dividiert durch die maximal mögliche Anzahl Pensions- und Pflegetage.",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt",
			"Bundesamt für Statistik (BFS), Statistik der sozialmedizinischen Institutionen (SOMED)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Pensions- und Pflegetage in Pflegeheimen und deren Auslastung",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.3",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-26T08:47:46",
		"id": 11171
	},
	{
		"template": "line001",
		"data-id": 11172,
		"chart-id": 11172,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil Pflegetage nach Pflegestufe in Pflegeheimen und Pflegestufen-Durchschnitt",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Der grösste Anteil (19,8%) der Pflegeheimbewohnenden ist in der Pflegestufe 6 zu finden. Seit 2017 stieg die durchschnittliche Pflegestufe bis zum Jahr 2024 um 10,2%. Die durchschnittliche Pflegestufe lag 2024 bei 6,4.",
		"erlaeuterungen": "Die Pflegestufe gibt an, wie viel Pflege eine Person pro Tag benötigt. In der Schweiz gibt es zwölf Pflegebedarfsstufen. Pflegestufe 1 umfasst einen Pflegebedarf von bis zu 20 Minuten am Tag, in Pflegestufe 12 fallen täglich mehr als 220 Minuten Pflege an. Pflegestufen gemäss Art. 7a der Krankenpflege-Leistungsverordnung (KLV).",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt",
			"Bundesamt für Statistik (BFS), Statistik der sozialmedizinischen Institutionen (SOMED)"
		],
		"externalLinks": [
			"<a href = ' https://www.fedlex.admin.ch/eli/cc/1995/4964_4964_4964/de' target = '_blank'>Krankenpflege-Leistungsverordnung (KLV)</a>",
			"<a href = 'https://www.bs.ch/themen/persoenliches-und-wohnen/wohnen/wohnen-im-alter/finanzierung-wohnen-im-alter#kosten-betreuung-und-pflege-im-pflegeheim' target = '_blank'>Pflegeheim Tagestaxen</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil Pflegetage nach Pflegestufe in Pflegeheimen und Pflegestufen-Durchschnitt",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.5",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-13T12:35:14",
		"id": 11172
	},
	{
		"template": "line001",
		"data-id": 11173,
		"chart-id": 11173,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Aufenthaltstage in Tages- und Nachtpflegeeinrichtungen und deren Auslastung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2024 betrug die Auslastung in den Tages- und Nachtpflegeeinrichtungen (TNP) 77,2%. Gegenüber dem Vorjahr ist ein Anstieg der totalen Auslastung zu verzeichnen. Im Jahr 2024 betrug die Anzahl der Aufenthaltstage, inkl. ausserkantonale Tagesgäste, 31 228.",
		"erlaeuterungen": "Die Auslastung ist mit den ausserkantonalen Tagesgästen berechnet. Die Auslastung berechnet sich wie folgt: Die Anzahl der abgerechneten Aufenthaltstage dividiert durch die maximal mögliche Anzahl Aufenthaltstage.<br>Die sehr hohe Auslastung der Tages- und Nachtpflegeeinrichtungen im Jahr 2012 kann mit dem damaligen grossen Kapazitätsengpass der Pflegeheimplätze erklärt werden. Auf einen Pflegeplatz wartende betagte Menschen nutzten als Überbrückung die TNP stärker, z. B. an fünf statt nur an zwei Tagen pro Woche, bis sie schliesslich in ein Pflegeheim eintreten konnten.<br>Seit 2020 gibt es aufgrund zu geringer Nachfrage kein Nachtpflegeangebot mehr.",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Aufenthaltstage in Tages- und Nachtpflegeeinrichtungen und deren Auslastung",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.11",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-24T08:41:32",
		"id": 11173
	},
	{
		"template": "line001",
		"data-id": 11174,
		"chart-id": 11174,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Pflegestunden Spitex",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Seit 2011 sind die geleisteten Spitex-Pflegestunden im Kanton Basel-Stadt mit Ausnahme der Jahre 2018 und 2022 stetig gestiegen. Im Jahr 2024 betrug die Anzahl Spitex-Pflegestunden mit Leistungsauftrag 284 132. Alle geleisteten Pflegestunden (ohne und mit Leistungsauftrag) summierten sich 2024 auf total 633 382 Stunden.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Pflegestunden Spitex",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.18",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_018",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-24T08:41:40",
		"id": 11174
	},
	{
		"template": "line001",
		"data-id": 11175,
		"chart-id": 11175,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Leistungsvolumen der Beiträge an die Pflege zu Hause",
		"subtitle": "durch Angehörige oder andere nahestehende Personen, Stadt Basel",
		"lesehilfe": "Die Anzahl der durch Angehörige oder nahestehende Personen Gepflegten in der Stadt Basel, welche dafür Pflegebeiträge beziehen, ist 2024 verglichen mit dem Vorjahr leicht auf 279 gesunken. Zu deren Gunsten wurden an insgesamt 76 165 Tagen Pflegeleistungen erbracht.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.bs.ch/themen/persoenliches-und-wohnen/wohnen/wohnen-im-alter/finanzierung-wohnen-im-alter#entschaedigung-bei-pflege-und-betreuung-zu-hause' target = '_blank'>Pflegebeiträge</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leistungsvolumen der Beiträge an die Pflege zu Hause",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.24",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_024",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-24T08:41:46",
		"id": 11175
	},
	{
		"template": "line001",
		"data-id": 11176,
		"chart-id": 11176,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Finanzierung der Pflegeheime",
		"subtitle": "in Mio. Franken, Basel-Stadt",
		"lesehilfe": "Im Jahr 2024 betrug der Finanzierungsbeitrag aus Ergänzungsleistungen 65,9 Mio. Franken, derjenige der Krankenversicherer 63,5 Mio. Franken und die kantonale Restfinanzierung 57,3 Mio. Franken. Das Gesamtfinanzierungsvolumen der Pflegeheime belief sich auf 366,5 Mio. Franken.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt",
			"Bundesamt für Statistik (BFS), Statistik der sozialmedizinischen Institutionen (SOMED)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Finanzierung der Pflegeheime",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.8",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-26T08:47:49",
		"id": 11176
	},
	{
		"template": "line001",
		"data-id": 11177,
		"chart-id": 11177,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Finanzierung der Tages- und Nachtpflegeeinrichtungen",
		"subtitle": "in Mio. Franken, Basel-Stadt",
		"lesehilfe": "2024 stieg das Finanzierungsvolumen mit total 5,1 Mio. Franken gegenüber dem Vorjahr um 0,9 Mio Franken. Davon finanzierten der Kanton bzw. die Gemeinden 2,7 Mio. Franken, die Krankenversicherer 1,0 Mio. Franken und die Tagesgäste 1,4 Mio. Franken.",
		"erlaeuterungen": "Seit 2020 gibt es aufgrund zu geringer Nachfrage kein Nachtpflegeangebot mehr.",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Finanzierung der Tages- und Nachtpflegeeinrichtungen",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.16",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_016",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-13T12:35:12",
		"id": 11177
	},
	{
		"template": "line001",
		"data-id": 11178,
		"chart-id": 11178,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Finanzierung der Spitex-Leistungen",
		"subtitle": "in Mio. Franken, Basel-Stadt",
		"lesehilfe": "2024 sind die Spitex-Kosten im Vergleich zum Vorjahr auf 65,5 Mio. Franken gestiegen. Der grösste Beitrag lag mit 36,6 Mio. Franken bei den Krankenversicherern, gefolgt von den Kantonen und Gemeinden mit 25,6 Mio. Franken und schliesslich dem Eigenbetrag der Klientinnen und Klienten von 3,3 Mio. Franken.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Finanzierung der Spitex-Leistungen",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.22",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_022",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-24T08:41:45",
		"id": 11178
	},
	{
		"template": "line001",
		"data-id": 11179,
		"chart-id": 11179,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Finanzierung der Beiträge an die Pflege zu Hause",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2024 betrug der Durchschnittsbeitrag der Stadt Basel an die Pflege zu Hause pro Tag 22,8 Franken. Der Kanton zahlte im Jahr 2024 2,4 Mio. Franken an die Beiträge für die Pflege zu Hause, davon entfielen 1,7 Mio. Franken auf die Stadt Basel.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Finanzierung der Beiträge an die Pflege zu Hause",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.25",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_025",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-24T08:41:48",
		"id": 11179
	},
	{
		"template": "line001",
		"data-id": 11182,
		"chart-id": 11182,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Durchschnittliche Dauer eines stationären Aufenthalts baselstädtischer Patientinnen und Patienten",
		"subtitle": "in Basler Spitälern im zeitlichen Verlauf",
		"lesehilfe": "Im Jahr 2023 dauerte im Kanton Basel-Stadt ein stationärer Aufenthalt einer Patientin bzw. eines Patienten aus dem Stadtkanton in der Akutsomatik durchschnittlich 6,7 Tage, in der Psychiatrie 33,5 Tage und in der Rehabilitation 23,1 Tage.",
		"erlaeuterungen": "Die durchschnittliche Dauer eines stationären Aufenthalts ist in Tagen angegeben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [
			"Weitere Kennzahlen zu Spitälern auf der <a href = 'https://www.statistik.bs.ch/zahlen/tabellen/14-gesundheit/einrichtungen.html' target = '_blank'>Internetseite des Statistischen Amtes Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Durchschnittliche Dauer eines stationären Aufenthalts baselstädtischer Patientinnen und Patienten",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.11182",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "2.3",
		"stufe1": "2 Spitalversorgung",
		"stufe2": "2.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-20T03:23:27",
		"id": 11182
	},
	{
		"template": "line001",
		"data-id": 11183,
		"chart-id": 11183,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Stationäre Spitalaustritte der baselstädtischen Wohnbevölkerung",
		"subtitle": "im zeitlichen Verlauf in Abhängigkeit vom Spitalstandort",
		"lesehilfe": "Im Jahr 2023 erfolgten 38 869 (89,1%) der insgesamt 43 604 Austritte baselstädtischer Patientinnen und Patienten nach einer stationären Behandlung aus einem Basler Spital.",
		"erlaeuterungen": "Gezählt werden die Austritte aus einer stationären Behandlung, um Doppelzählungen zu vermeiden (ein Patient kann beispielsweise im Jahr 2021 in ein Spital eintreten und erst im Folgejahr 2022 austreten).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [
			"Weitere Kennzahlen zu Spitälern auf der <a href = 'https://www.statistik.bs.ch/zahlen/tabellen/14-gesundheit/einrichtungen.html' target = '_blank'>Internetseite des Statistischen Amtes Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Stationäre Spitalaustritte der baselstädtischen Wohnbevölkerung",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.11183",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "2.4",
		"stufe1": "2 Spitalversorgung",
		"stufe2": "2.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-20T03:23:27",
		"id": 11183
	},
	{
		"template": "line001",
		"data-id": 11184,
		"chart-id": 11184,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Prozentuale Verteilung der stationären Behandlungen und des Case-Mix nach Leistungsbereichen",
		"subtitle": "bei baselstädtischen Patientinnen und Patienten in Basler Akutspitälern im Jahr 2023",
		"lesehilfe": "Im Jahr 2023 sind 45,7% der stationären, akutsomatischen, nach Swiss-DRG abgerechneten Behandlungen baselstädtischer Patientinnen und Patienten dem Leistungsbereich «Basispaket Chirurgie und innere Medizin» zugeordnet. Bei der Abrechnung entsprechen diese Behandlungen 36,1% (Case-Mix) des gesamten SwissDRG-Abgeltungsvolumens.",
		"erlaeuterungen": "Der Case-Mix beschreibt den gesamten Schweregrad der abgerechneten Behandlungsfälle. Er ergibt sich aus der Summe der Kostengewichte der Fälle und kann als Vergleichswert für die Fallschwere, also den Gesamtschweregrad der Fälle eines Spitals oder - wie in der Grafik - eines Leistungsbereichs dienen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [
			"Weitere Kennzahlen zu Spitälern auf der <a href = 'https://www.statistik.bs.ch/zahlen/tabellen/14-gesundheit/einrichtungen.html' target = '_blank'>Internetseite des Statistischen Amtes Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Prozentuale Verteilung der stationären Behandlungen und des Case-Mix nach Leistungsbereichen",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.11184",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "2.5",
		"stufe1": "2 Spitalversorgung",
		"stufe2": "2.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-20T03:23:28",
		"id": 11184
	},
	{
		"template": "line001",
		"data-id": 11185,
		"chart-id": 11185,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Schweregrad und Komplexität",
		"subtitle": "CMI und PCCL der baselstädtischen Spitäler aller stationären Patienten, 2023",
		"lesehilfe": "Im Jahr 2023 betrug der durchschnittliche ökonomische Schweregrad gemäss Case-Mix-Index (CMI) über alle akutsomatischen Spitäler des Kantons Basel-Stadt 1,21. Der durchschnittliche patientenbezogene Schweregrad nach PCCL betrug 0,90.",
		"erlaeuterungen": "Der Case-Mix (CM) beschreibt in der Akutsomatik den gesamten Schweregrad der nach SwissDRG abgerechneten Behandlungsfälle eines Spitals. Er ergibt sich aus der Summe der Kostengewichte der Fälle eines Spitals.<br>Dividiert man den Case-Mix durch die Anzahl Fälle, erhält man den Case-Mix-Index (CMI), d. h. das durchschnittliche Kostengewicht der Fälle eines Spitals. Der CMI stellt einen Vergleichswert für die durchschnittliche Fallschwere und den damit verbundenen zeitlichen, personellen und materiellen Ressourcenverbrauch resp. Behandlungsaufwand dar (ökonomischer Schweregrad).<br>Der PCCL (Patient Complication and Comorbidity Level) oder auch patientenbezogener Schweregrad, errechnet sich in einem komplexen Verfahren aus Bewertungen von Nebendiagnosen und Komplikationen (CCL) und liegt zwischen 0 (keine) und 6 (schwerste Nebendiagnosen und/oder Komplikationen). Somit ist der PCCL ein Mass für die durchschnittliche Krankheitslast resp. Multimorbidität der stationär behandelten Patientinnen und Patienten eines Spitals.<br>Sowohl der berechnete ökonomische Schweregrad CMI wie auch der patientenbezogene Schweregrad PCCL bewegen sich im Rahmen der Werte, die für einen Stadtkanton zu erwarten sind. Beispielsweise werden im Universitätsspital Basel häufig überdurchschnittlich komplexe Fälle mit entsprechend hohem Ressourcenverbrauch behandelt. Dies resultiert in einem Case-Mix-Index (CMI) grösser als 1,0.  <br>Patientinnen und Patienten mit hoher Krankheitslast und damit einem hohen PCCL-Wert (grösser als 1) sind für Spitäler resp. Leistungsbereiche zu erwarten, die auf die Behandlung von Betagten (z. B. Universitäre Altersmedizin Felix Platter) oder Menschen mit unheilbaren, lebensbedrohlichen oder chronisch fortschreitenden Krankheiten (z. B. Palliativzentrum Hildegard) ausgerichtet sind .",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [
			"Weitere Kennzahlen zu Spitälern auf der <a href = 'https://www.statistik.bs.ch/zahlen/tabellen/14-gesundheit/einrichtungen.html' target = '_blank'>Internetseite des Statistischen Amtes Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Schweregrad und Komplexität",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.11185",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "2.6",
		"stufe1": "2 Spitalversorgung",
		"stufe2": "2.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-20T03:23:29",
		"id": 11185
	},
	{
		"template": "map001",
		"data-id": 11897,
		"chart-id": 11897,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Spitalstandorte",
		"subtitle": "Standorte und Anzahl stationärer Austritte im Jahr 2023, Basel-Stadt",
		"lesehilfe": "Die meisten Austritte aus einer stationären Behandlung verzeichnete im Jahr 2023 das Universitätsspital Basel mit 41 110 von insgesamt 87 072 Austritten im Kanton Basel-Stadt.",
		"erlaeuterungen": "Spitäler mit Standort im Kanton Basel-Stadt und deren jeweilige Anzahl an Austritten aus einer stationären Behandlung im angegebenen Jahr. <br>Zur Bestimmung der Anzahl stationärer Behandlungen eines Spitals in einem bestimmten Zeitraum wird die Anzahl der Austritte während dieses Zeitraums herangezogen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [
			"Weitere Kennzahlen zu Spitälern auf der <a href = 'https://www.statistik.bs.ch/zahlen/tabellen/14-gesundheit/einrichtungen.html' target = '_blank'>Internetseite des Statistischen Amtes Basel-Stadt</a>",
			"<a href = 'https://www.bs.ch/gesundheitsdepartement/bereich-gesundheitsversorgung/spitalversorgung/spitalplanung#spitalliste' target = '_blank'>Spitalliste</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Spitalstandorte",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.11897",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "2.1",
		"stufe1": "2 Spitalversorgung",
		"stufe2": "2.1 Karten",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_001",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-20T03:23:26",
		"id": 11897
	},
	{
		"template": "line001",
		"data-id": 12727,
		"chart-id": 12727,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Pflegetage nach Pflegestufe in Pflegeheimen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die meisten Pflegetage sind in Stufe 6 (2024: 203 551 Pflegetage) zu finden. Danach folgt Stufe 8 (2024: 187 422 Pflegetage). Diese Reihenfolge ist seit 2017 unverändert.",
		"erlaeuterungen": "Die Pflegestufe gibt an, wie viel Pflege eine Person pro Tag benötigt. In der Schweiz gibt es zwölf Pflegebedarfsstufen. Pflegestufe 1 umfasst einen Pflegebedarf von bis zu 20 Minuten am Tag, in Pflegestufe 12 fallen täglich mehr als 220 Minuten Pflege an. Pflegestufen gemäss Art. 7a der Krankenpflege-Leistungsverordnung (KLV).",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt",
			"Bundesamt für Statistik (BFS), Statistik der sozialmedizinischen Institutionen (SOMED)"
		],
		"externalLinks": [
			"<a href = 'https://www.fedlex.admin.ch/eli/cc/1995/4964_4964_4964/de' target = '_blank'>Krankenpflege-Leistungsverordnung (KLV)</a>",
			"<a href = 'https://www.bs.ch/themen/persoenliches-und-wohnen/wohnen/wohnen-im-alter/finanzierung-wohnen-im-alter#kosten-betreuung-und-pflege-im-pflegeheim' target = '_blank'>Pflegeheim Tagestaxen</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Pflegetage nach Pflegestufe in Pflegeheimen",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.4",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-26T08:47:48",
		"id": 12727
	},
	{
		"template": "line001",
		"data-id": 12730,
		"chart-id": 12730,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Aufenthaltstage nach Pflegestufe in Tages- und Nachtpflegeeinrichtungen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2024 finden sich die meisten Pflegetage mit 11 002 Tagen in Stufe 4. Danach folgt mit 4 969 Pflegetagen die Stufe 6.",
		"erlaeuterungen": "Die Pflegestufe gibt an, wie viel Pflege eine Person pro Tag benötigt. In der Schweiz gibt es zwölf Pflegebedarfsstufen. Pflegestufe 1 umfasst einen Pflegebedarf von bis zu 20 Minuten am Tag, in Pflegestufe 12 fallen täglich mehr als 220 Minuten Pflege an. Pflegestufen gemäss Art. 7a der Krankenpflege-Leistungsverordnung (KLV).<br>Seit 2020 gibt es aufgrund zu geringer Nachfrage kein Nachtpflegeangebot mehr.",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.fedlex.admin.ch/eli/cc/1995/4964_4964_4964/de' target = '_blank'>Krankenpflege-Leistungsverordnung (KLV)</a>",
			"<a href = 'https://www.bs.ch/themen/persoenliches-und-wohnen/wohnen/wohnen-im-alter/finanzierung-wohnen-im-alter' target = '_blank'>Tagestaxen der Tagespflegeeinrichtungen</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Aufenthaltstage nach Pflegestufe in Tages- und Nachtpflegeeinrichtungen",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.12",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-24T08:41:33",
		"id": 12730
	},
	{
		"template": "line001",
		"data-id": 12732,
		"chart-id": 12732,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil Aufenthaltstage nach Pflegestufe in Tages- und Nachtpflegeeinrichtungen und Pflegestufen-Durchschnitt",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Der grösste Anteil (39,2%) der Gäste in Tages- und Nachtpflegeeinrichtungen ist in der Pflegestufe 4 zu finden. Seit 2021 stieg die durchschnittliche Pflegestufe bis zum Jahr 2024 um 11,4%. Die durchschnittliche Pflegestufe lag 2024 bei 3,9.",
		"erlaeuterungen": "Die Pflegestufe gibt an, wie viel Pflege eine Person pro Tag benötigt. In der Schweiz gibt es zwölf Pflegebedarfsstufen. Pflegestufe 1 umfasst einen Pflegebedarf von bis zu 20 Minuten am Tag, in Pflegestufe 12 fallen täglich mehr als 220 Minuten Pflege an. Pflegestufen gemäss Art. 7a der Krankenpflege-Leistungsverordnung (KLV).<br>Seit 2020 gibt es aufgrund zu geringer Nachfrage kein Nachtpflegeangebot mehr.",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.fedlex.admin.ch/eli/cc/1995/4964_4964_4964/de' target = '_blank'>Krankenpflege-Leistungsverordnung (KLV)</a>",
			"<a href = 'https://www.bs.ch/themen/persoenliches-und-wohnen/wohnen/wohnen-im-alter/finanzierung-wohnen-im-alter' target = '_blank'>Tagestaxen der Tagespflegeeinrichtungen</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil Aufenthaltstage nach Pflegestufe in Tages- und Nachtpflegeeinrichtungen und Pflegestufen-Durchschnitt",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.13",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_013",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-24T08:41:35",
		"id": 12732
	},
	{
		"template": "line001",
		"data-id": 12733,
		"chart-id": 12733,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Aufenthaltstage in Tages- und Nachtpflegeeinrichtungen nach Gemeinde",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2024 betrug die Anzahl aller Aufenthaltstage, inkl. ausserkantonale Tagesgäste, 31 228. Der Grossteil der Aufenthaltstage entfiel mit 23 785 auf Einwohnerinnen und Einwohner der Stadt Basel.",
		"erlaeuterungen": "Aufgrund der geringen Fallzahlen werden die Gemeinden Riehen und Bettingen gemeinsam dargestellt.<br>Seit 2020 gibt es aufgrund zu geringer Nachfrage kein Nachtpflegeangebot mehr.",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.fedlex.admin.ch/eli/cc/1995/4964_4964_4964/de' target = '_blank'>Krankenpflege-Leistungsverordnung (KLV)</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Aufenthaltstage in Tages- und Nachtpflegeeinrichtungen nach Gemeinde",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.14",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_014",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-24T08:41:36",
		"id": 12733
	},
	{
		"template": "line001",
		"data-id": 12734,
		"chart-id": 12734,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Aufenthaltstage in Tages- und Nachtpflegeeinrichtungen nach Spezialisierung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Mehrheit aller Aufenthaltstage fällt seit 2019 auf Plätze in allgemeinen Tages- und Nachtpflegeeinrichtungen. 2023 waren dies 17 511 von 27 450 Tagen.",
		"erlaeuterungen": "Spezialisierte Tagespflegeinrichtungen dienen der Betreuung von an Demenz erkrankten oder psychisch beeinträchtigten Personen.<br>Seit 2020 gibt es aufgrund zu geringer Nachfrage kein Nachtpflegeangebot mehr.",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Aufenthaltstage in Tages- und Nachtpflegeeinrichtungen nach Spezialisierung",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.15",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_015",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-20T03:23:12",
		"id": 12734
	},
	{
		"template": "line001",
		"data-id": 12735,
		"chart-id": 12735,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Pflegestunden Spitex nach Pflegeleistung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Mit Ausnahme von 2018 und 2022 sind die geleisteten Spitex-Pflegestunden im Kanton Basel-Stadt seit 2011 stetig gestiegen. Im Jahr 2024 betrug die Anzahl Pflegestunden 633 382 Stunden. Die Leistungsstunden der Bedarfsabklärung haben sich seit 2011 etwa verdreifacht.",
		"erlaeuterungen": "- Die Bedarfsabklärung wird zu Beginn und in regelmässigen Abständen durchgeführt. Sie dient der Beurteilung der Gesamtsituation, der Abklärung des Pflege- und Hilfebedarfs, der Beratung sowie der Koordination mit anderen Leistungserbringern wie z. B. dem Hausarzt.<br>- Behandlungspflege umfasst medizinische Leistungen, wie z. B. Richten und Verabreichen von Medikamenten, verordnetes Hauteinreiben, Anlegen von Verbänden, Verabreichen von Augentropfen, Blutdruckmessung, Pulskontrolle, Blutentnahme oder Wundversorgung. <br>- Die Grundpflege beinhaltet Hilfe beim Duschen, Baden und Waschen, bei Kompressionsstrümpfen, beim An- und Auskleiden, beim Essen und Trinken, beim Toilettengang, beim Aufstehen, Hinlegen und Gehen oder bei der Zahnpflege.<br>Die Unterscheidung der drei Pflegearten ist in Art. 7 Verordnung des EDI über Leistungen in der obligatorischen Krankenpflegeversicherung (KLV) geregelt.",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.fedlex.admin.ch/eli/cc/1995/4964_4964_4964/de' target = '_blank'>Krankenpflege-Leistungsverordnung (KLV)</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Pflegestunden Spitex nach Pflegeleistung",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.19",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_019",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-24T08:41:41",
		"id": 12735
	},
	{
		"template": "line001",
		"data-id": 12736,
		"chart-id": 12736,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil Pflegestunden Spitex nach Pflegeleistung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Der Anteil an Pflegeleistungen der Bedarfsabklärung ist seit 2011 gestiegen (2024: 7,8%). Der Anteil der Leistungen der Behandlungspflge beträgt über die Jahre knapp 31% und bei der Grundpflege 61%.",
		"erlaeuterungen": "- Die Bedarfsabklärung wird zu Beginn und in regelmässigen Abständen durchgeführt. Sie dient der Beurteilung der Gesamtsituation, der Abklärung des Pflege- und Hilfebedarfs, der Beratung sowie der Koordination mit anderen Leistungserbringern wie z. B. dem Hausarzt.<br>- Behandlungspflege umfasst medizinische Leistungen, wie z. B. Richten und Verabreichen von Medikamenten, verordnetes Hauteinreiben, Anlegen von Verbänden, Verabreichen von Augentropfen, Blutdruckmessung, Pulskontrolle, Blutentnahme oder Wundversorgung. <br>- Die Grundpflege beinhaltet Hilfe beim Duschen, Baden und Waschen, bei Kompressionsstrümpfen, beim An- und Auskleiden, beim Essen und Trinken, beim Toilettengang, beim Aufstehen, Hinlegen und Gehen oder bei der Zahnpflege.",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.fedlex.admin.ch/eli/cc/1995/4964_4964_4964/de' target = '_blank'>Krankenpflege-Leistungsverordnung (KLV)</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil Pflegestunden Spitex nach Pflegeleistung",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.20",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_020",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-24T08:41:43",
		"id": 12736
	},
	{
		"template": "line001",
		"data-id": 12737,
		"chart-id": 12737,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Pflegestunden Spitex nach Gemeinde",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2024 betrug die Anzahl Pflegestunden 633 382 Stunden. Der Grossteil wird mit 562 355 Pflegestunden bei Einwohnerinnen und Einwohnern der Stadt Basel erbracht.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Gesundheitsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.fedlex.admin.ch/eli/cc/1995/4964_4964_4964/de' target = '_blank'>Krankenpflege-Leistungsverordnung (KLV)</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Gemeinde"
		],
		"description": "Anzahl Pflegestunden Spitex nach Gemeinde",
		"thema": "14 Gesundheit",
		"unterthema": "Heime und Spitex",
		"kuerzel": "",
		"kennzahlenset": "Gesundheitsversorgung",
		"kuerzelKunde": "1.21",
		"stufe1": "1 Langzeitpflege",
		"stufe2": "1.2 Kennzahlen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_021",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-24T08:41:44",
		"id": 12737
	}
];