var indikatorensetNames = [
	"Arbeitsmarkt",
	"Legislaturplan",
	"Nachhaltigkeit",
	"Wohnraumentwicklung",
	"Umwelt",
	"Gesellschaftlicher-Zusammenhalt",
	"Wohnviertel",
	"Richtplan",
	"Wanderungen",
	"Integration",
	"Richtplan (Print)",
	"Legislaturplan (Print)",
	"Gefragte Karten",
	"Tourismus",
	"Integration (Print)",
	"Wanderungen (Print)",
	"Steuern",
	"Arbeitsmarkt (Print)",
	"Monatsindikatoren",
	"Leerstand",
	"Stadtteilmonitoring Rosental",
	"Testset",
	"Bevoelkerungsszenarien",
	"Stadtteilmonitoring Rosental (Print)",
	"City-Statistics",
	"Tourismus (Print)",
	"Stadtteilmonitoring Klybeck-Kleinhüningen",
	"CMS Kennzahlen Soziales",
	"Wirtschaftsbericht BS_BL_JU",
	"Gesellschaftlicher-Zusammenhalt (Print)",
	"Wirtschaftsbericht BS_BL_JU (Print)",
	"CMS Kennzahlen Soziales (Print)",
	"Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
	"Nachhaltigkeit (Print)",
	"Energiestatistik",
	"Bevoelkerungsszenarien (Print)",
	"Staedtevergleich",
	"Test"
];