var indikatorensetNames = [
	"Wirtschaftsbericht BS_BL_JU",
	"CMS Kennzahlen Soziales",
	"CMS Kennzahlen",
	"Gesundheitsversorgung",
	"Legislaturplan",
	"Legislaturplan (Print)",
	"Richtplan",
	"Soziales",
	"Nachhaltigkeit",
	"Nachhaltigkeit (Print)",
	"Befragungen",
	"Stadtteilmonitoring St. Johann",
	"Energiestatistik (Print)",
	"Arbeitsmarkt",
	"Wohnraumschutz",
	"Richtplan (Print)",
	"Umwelt",
	"Wohnraumentwicklung",
	"Gesellschaftlicher-Zusammenhalt",
	"Wohnviertel",
	"Wanderungen",
	"Integration",
	"Legislaturplan-2017-2021 (Print)",
	"Gefragte Karten",
	"Tourismus",
	"Integration (Print)",
	"Wanderungen (Print)",
	"Steuern",
	"Arbeitsmarkt (Print)",
	"Monatsindikatoren",
	"Leerstand",
	"Wohnbaustatistik",
	"Stadtteilmonitoring Rosental",
	"Gesundheit",
	"Testset",
	"Bevoelkerungsszenarien",
	"Stadtteilmonitoring Rosental (Print)",
	"City-Statistics",
	"Tourismus (Print)",
	"Stadtteilmonitoring Klybeck-Kleinhüningen",
	"City-Statistics (Print)",
	"Gesellschaftlicher-Zusammenhalt (Print)",
	"Wirtschaftsbericht BS_BL_JU (Print)",
	"CMS Kennzahlen Soziales (Print)",
	"Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
	"Energiestatistik",
	"Bevoelkerungsszenarien (Print)",
	"Leerstand (Print)",
	"Steuern (Print)",
	"Innenstadt-QuiZ",
	"Schluesselindikatoren",
	"Test"
];