var indikatorensetData = [
	{
		"template": "template001",
		"data-id": 9575,
		"chart-id": 9575,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Arbeitsstätten nach Branche",
		"subtitle": "Innenstadt und Stadt Basel",
		"lesehilfe": "Von den 4 571 Arbeitsstätten in der Innenstadt (2022) gehören 20,4% zur Branchengruppe Unternehmensdienstleistungen und Freiberufe, 17,6% zum Gesundheits- und Sozialwesen und 12,2% zum Detailhandel. In der Stadt Basel insgesamt beträgt der Anteil der Arbeitsstätten im Detailhandel 7,5%.",
		"erlaeuterungen": "Eine Arbeitsstätte ist ein an einem bestimmten Ort gelegenes Unternehmen (Einzelunternehmen) oder Teil eines Unternehmens (z. B. Werkstatt, Werk, Verkaufsladen, Büro, Dienststelle, Lager). An diesem Ort arbeiten eine oder mehrere Personen für dasselbe Unternehmen. Berücksichtigt werden alle Arbeitsstätten, die der AHV-Beitragspflicht unterstehen (ab 2 300 Franken Jahreslohn). Bei Unternehmen mit mehreren Arbeitsstätten wird die Struktur gemäss Angaben der Unternehmen erfasst. Dabei ist nicht auszuschliessen, dass es sich bei der Verteilung auf die verschiedenen Arbeitsstätten teilweise um rein administrative Zuordnungen handeln kann, und nicht alle effektiv vorhandenen Arbeitsstätten abgebildet sind.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Stadt Basel",
			"Innenstadt"
		],
		"description": "Arbeitsstätten nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09575",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "1.1-1",
		"stufe1": "Ziel 1: Funktionsvielfalt der Innenstadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_111",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-04T04:06:57",
		"id": 9575
	},
	{
		"template": "template001",
		"data-id": 9576,
		"chart-id": 9576,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Arbeitsstättenentwicklung nach Branche",
		"subtitle": "Innenstadt und Stadt Basel, 2022 gegenüber 2018",
		"lesehilfe": "Die Anzahl Arbeitsstätten hat zwischen 2018 und 2022 in der Innenstadt um +2,3% und in der Stadt Basel um +6,3% zugenommen. Nach Branche betrachtet gab es in der Innenstadt die deutlichsten Rückgänge im Bereich Verkehr und Lagerei (-19,6 %) sowie im verarbeitenden Gewerbe (-14,7%). In der Innenstadt hat die Zahl der Arbeitsstätten im Bereich Information und Kommunikation (+13,1%) am stärksten zugenommen.",
		"erlaeuterungen": "Eine Arbeitsstätte ist ein an einem bestimmten Ort gelegenes Unternehmen (Einzelunternehmen) oder Teil eines Unternehmens (z. B. Werkstatt, Werk, Verkaufsladen, Büro, Dienststelle, Lager). An diesem Ort arbeiten eine oder mehrere Personen für dasselbe Unternehmen. Berücksichtigt werden alle Arbeitsstätten, die der AHV-Beitragspflicht unterstehen (ab 2 300 Franken Jahreslohn). Bei Unternehmen mit mehreren Arbeitsstätten wird die Struktur gemäss Angaben der Unternehmen erfasst. Dabei ist nicht auszuschliessen, dass es sich bei der Verteilung auf die verschiedenen Arbeitsstätten teilweise um rein administrative Zuordnungen handeln kann, und nicht alle effektiv vorhandenen Arbeitsstätten abgebildet sind.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Stadt Basel",
			"Innenstadt"
		],
		"description": "Arbeitsstättenentwicklung nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09576",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "1.1-2",
		"stufe1": "Ziel 1: Funktionsvielfalt der Innenstadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_112",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-04T04:06:58",
		"id": 9576
	},
	{
		"template": "line001",
		"data-id": 9577,
		"chart-id": 9577,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Veranstaltungen auf der Allmend",
		"subtitle": "in Anzahl Tagen, nach Veranstaltungsort, Innenstadt Basel",
		"lesehilfe": "Im Jahr 2021 fanden auf dem Münsterplatz an 20 Tagen bewilligte Veranstaltungen statt (gemäss Kontingent wären 60 möglich).",
		"erlaeuterungen": "Abgebildet ist die Anzahl Tage, an denen auf den jeweiligen Plätzen bewilligte Veranstaltungen stattfinden. Für jeden Platz existiert ein jährliches Kontingent der maximalen Veranstaltungstage. Der Regierungsrat kann darüber hinaus zusätzliche Veranstaltungstage bewilligen.<br>Als Veranstaltung im Sinne der Bespielungspläne gelten alle Anlässe auf Allmend, die nach 20:00 Uhr stattfinden oder Anlässe, die vor 20:00 Uhr Lautsprecher und/oder unverstärkte laute Musikinstrumente einsetzen. Nicht als Veranstaltung im Sinne des Bespielungsplanes gelten bspw. tagsüber stattfindene Märkte oder die Fasnacht. <br>Barfüsser- und Theaterplatz werden bezüglich der Kontingente für Veranstaltungen als eine Einheit bewirtschaftet. Auf der Kaserne werden gemäss Bespielungsplan die Belegungstage erfasst (inkl. Auf- und Abbau), auf allen anderen Plätzen nur die effektiven Veranstaltungstage (Bespielung). Details zu den Bespielungsplänen siehe Links.",
		"quellenangabe": [
			"Allmendverwaltung Basel-Stadt"
		],
		"externalLinks": [
			"Tiefbauamt Basel-Stadt, <a href = 'https://www.tiefbauamt.bs.ch/oeffentlicher-raum/nutzung-des-oeffentlichen-raumes/veranstaltungen.html' target = '_blank'>Veranstaltungen im öffentlichen Raum</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Veranstaltungen auf der Allmend",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Lärm",
		"kuerzel": "I.02.14.09577",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "1.2-1",
		"stufe1": "Ziel 1: Funktionsvielfalt der Innenstadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_121",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-12-07T12:41:07",
		"id": 9577
	},
	{
		"template": "line001",
		"data-id": 9578,
		"chart-id": 9578,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Lärmintensive Veranstaltungen auf der Allmend",
		"subtitle": "in Anzahl Tagen, nach Veranstaltungsort, Innenstadt Basel",
		"lesehilfe": "Auf dem Barfüsser- und dem Theaterplatz fanden 2021 an 16 Tagen lärmintensive bewilligte Veranstaltungen statt (gemäss Kontingent wären 40 möglich).",
		"erlaeuterungen": "Abgebildet ist die Anzahl Tage, an denen auf den jeweiligen Plätzen bewilligte lärmintensive Veranstaltungen stattfinden (bspw. ausgesprochene Musikanlässe, wie bass- und rhythmusbetonte Live-Konzerte, Discos und Kino, respektive Anlässe mit einem hohen Animationsanteil). Für jeden Platz existiert (neben dem jährlichen Kontingent an maximalen Veranstaltungstagen) ein Kontingent für Veranstaltungstage mit besonders lärmintensiven Auswirkungen. Der Regierungsrat kann darüber hinaus zusätzliche Veranstaltungstage bewilligen.<br>Barfüsser- und Theaterplatz werden bezüglich der Kontingente für Veranstaltungen als eine Einheit bewirtschaftet. Auf der Kaserne werden gemäss Bespielungsplan die Belegungstage erfasst (inkl. Auf- und Abbau), auf allen anderen Plätzen nur die effektiven Veranstaltungstage (Bespielung). Details zu den Bespielungsplänen siehe Links.",
		"quellenangabe": [
			"Allmendverwaltung Basel-Stadt"
		],
		"externalLinks": [
			"Tiefbauamt Basel-Stadt, <a href = 'https://www.tiefbauamt.bs.ch/oeffentlicher-raum/nutzung-des-oeffentlichen-raumes/veranstaltungen.html' target = '_blank'>Veranstaltungen im öffentlichen Raum</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Lärmintensive Veranstaltungen auf der Allmend",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Lärm",
		"kuerzel": "I.02.14.09578",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "1.2-2",
		"stufe1": "Ziel 1: Funktionsvielfalt der Innenstadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_122",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-12-07T12:41:07",
		"id": 9578
	},
	{
		"template": "line001",
		"data-id": 9579,
		"chart-id": 9579,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Meldungen bei der Polizei",
		"subtitle": "Basel-Stadt, Stadt Basel und Innenstadt",
		"lesehilfe": "Im Jahr 2024 wurden bei der Polizeieinsatzzentrale 1 146 Meldungen erfasst, welche die Innenstadt betreffen.",
		"erlaeuterungen": "Bei den bei der Polizeieinsatzzentrale eingegangenen Meldungen (sog. Requisitionen) handelt es sich überwiegend um Telefonanrufe seitens der Bevölkerung. Die Daten sind seit 2013 verfügbar.",
		"quellenangabe": [
			"Kantonspolizei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Stadt Basel",
			"Innenstadt"
		],
		"description": "Meldungen bei der Polizei",
		"thema": "19 Kriminalität und Strafrecht",
		"unterthema": "Polizei",
		"kuerzel": "I.19.1.09579",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "1.3-1",
		"stufe1": "Ziel 1: Funktionsvielfalt der Innenstadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_131",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-02-26T08:32:14",
		"id": 9579
	},
	{
		"template": "template001",
		"data-id": 9580,
		"chart-id": 9580,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Meldungen bei der Polizei bezüglich Innenstadt nach Kategorie",
		"subtitle": "Innenstadt Basel",
		"lesehilfe": "In der Innenstadt war im Jahr 2024 Lärm der häufigste Grund für Meldungen bei der Polizeieinsatzzentrale (280). Am zweit- und dritthäufigsten waren Meldungen wegen Körperverletzung (219) sowie wegen Alkohol und Drogen (176).",
		"erlaeuterungen": "Bei den bei der Polizeieinsatzzentrale eingegangenen Meldungen (sog. Requisitionen) handelt es sich überwiegend um Telefonanrufe seitens der Bevölkerung. Die Daten sind seit 2013 verfügbar.",
		"quellenangabe": [
			"Kantonspolizei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Meldungen bei der Polizei bezüglich Innenstadt nach Kategorie",
		"thema": "19 Kriminalität und Strafrecht",
		"unterthema": "Polizei",
		"kuerzel": "I.19.1.09580",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "1.3-2",
		"stufe1": "Ziel 1: Funktionsvielfalt der Innenstadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_132",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-03-05T08:35:51",
		"id": 9580
	},
	{
		"template": "line001",
		"data-id": 9581,
		"chart-id": 9581,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung",
		"subtitle": "Basel-Stadt und Innenstadt",
		"lesehilfe": "In der Innenstadt leben im Jahr 2024 14 586 Menschen. Dies sind 12,9% mehr als 2008. Im Kanton Basel-Stadt wuchs die Einwohnerzahl in diesem Zeitraum um 9,7% auf 207 515.",
		"erlaeuterungen": "Bevölkerungsbestand am Jahresende.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Innenstadt"
		],
		"description": "Wohnbevölkerung",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "2.1-1",
		"stufe1": "Ziel 2: Finanzkraft des Kantons Basel-Stadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_211",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-20T08:24:41",
		"id": 9581
	},
	{
		"template": "line001",
		"data-id": 9582,
		"chart-id": 9582,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sesshaftigkeit",
		"subtitle": "Basel-Stadt und Innenstadt",
		"lesehilfe": "In der Innenstadt liegt der Anteil der Personen, die seit zehn oder mehr Jahren an der gleichen Adresse wohnen, Ende 2024 bei 29,0%, im Kanton Basel-Stadt bei 33,0%.",
		"erlaeuterungen": "Anteil der seit mindestens zehn Jahren an der gleichen Adresse wohnenden Personen an der gesamten Wohnbevölkerung eines Gebietes in Prozent. Ohne Personen an administrativen Meldeadressen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Innenstadt"
		],
		"description": "Sesshaftigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "2.1-2",
		"stufe1": "Ziel 2: Finanzkraft des Kantons Basel-Stadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_212",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-21T02:31:41",
		"id": 9582
	},
	{
		"template": "template001",
		"data-id": 9583,
		"chart-id": 9583,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Nettomietpreise",
		"subtitle": "in Franken pro m<sup>2</sup> Wohnfläche, Basel-Stadt und Innenstadt, 2018-2022",
		"lesehilfe": "Die Nettomiete pro m<sup>2</sup> von 3- und 4-Zimmer-Wohnungen liegt in der Innenstadt im Durchschnitt der Jahre 2018 bis 2022 bei 19,1 Franken.",
		"erlaeuterungen": "Der m²-Preis bezieht sich auf die Nettomiete, dividiert durch die Wohnfläche von 3- oder 4-Zimmer-Wohnungen. Die Daten stammen aus der Strukturerhebung und beruhen auf der Hochrechnung einer Stichprobe; sie sind folglich mit einer gewissen Unsicherheit behaftet. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2018 bis 2022 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle, welche den wahren Wert mit einer Wahrscheinlichkeit von 95% umfassen. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit jenen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Innenstadt"
		],
		"description": "Nettomietpreise",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Mietpreise",
		"kuerzel": "I.09.3.09583",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "2.2-1",
		"stufe1": "Ziel 2: Finanzkraft des Kantons Basel-Stadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_221",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-06-24T04:32:45",
		"id": 9583
	},
	{
		"template": "line001",
		"data-id": 9584,
		"chart-id": 9584,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Reineinkommen pro Veranlagung",
		"subtitle": "in Franken, Basel-Stadt und Innenstadt",
		"lesehilfe": "2021 beträgt das durchschnittliche Reineinkommen pro Veranlagung von Personen, die in der Innenstadt wohnen, rund 109 200 Franken. Der Wert für den ganzen Kanton beträgt ca. 76 200 Franken.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Innenstadt"
		],
		"description": "Reineinkommen pro Veranlagung",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09584",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "2.3-1",
		"stufe1": "Ziel 2: Finanzkraft des Kantons Basel-Stadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_231",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-04T04:07:00",
		"id": 9584
	},
	{
		"template": "line001",
		"data-id": 9585,
		"chart-id": 9585,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Summe des Ertrags aus Einkommens- und Vermögenssteuer von Zu- und Weggezogenen",
		"subtitle": "in Franken, Basel-Stadt und Innenstadt",
		"lesehilfe": "Von Zuzügern in die Innenstadt stammten im Jahr 2021 rund 5,2 Millionen Franken Steuerertrag, von Wegzügern (Ertrag des Vorjahrs) rund 4,3 Millionen Franken.",
		"erlaeuterungen": "Die Methodik zur Untersuchung des Wanderungseffekts unterscheidet sich von den übrigen Auswertungen der Steuerstatistik Basel-Stadt. Die Analyse der Effekte auf den Ertrag aus Einkommens- und Vermögenssteuer durch Zu- und Abwanderung im Kanton Basel-Stadt wird durch verschiedene methodische Aspekte erschwert. Seit der eidgenössischen Steuerharmonisierung im Jahr 2002 ist für die Steuerpflicht innerhalb der Schweiz der Wohnsitz am 31. Dezember massgebend. Es liegen daher in Basel-Stadt in der Regel keine Daten zur Einkommens- und Vermögenssituation im Jahr des Wegzugs vor. Für die Steuerstatistik der Wegzügerinnen und Wegzüger wurden daher die Steuerdaten des jeweiligen Vorjahres verwendet. Für die Zugezogenen und die ganzjährig Niedergelassenen sind die Steuerdaten des Berichtsjahres vorhanden und wurden für die Analyse verwendet. Bei der Definition der Zuzüger wurde berücksichtigt, dass Ausländer ohne Niederlassungsbewilligung in der Regel an der Quelle veranlagt werden. Aus diesem Grund wurde ein Zuzug erst bei einer Niederlassung als solcher gezählt. Quellensteuerpflichtige sind in der Regel nicht erfasst, ausser sie werden nachträglich ordentlich veranlagt. Dies ist zum Beispiel der Fall, wenn die Einkünfte mehr als 120 000 Franken im Kalenderjahr betragen.<br>In der Auswertung ist sowohl die Kantons- als auch die Gemeindesteuer berücksichtigt.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Innenstadt"
		],
		"description": "Summe des Ertrags aus Einkommens- und Vermögenssteuer von Zu- und Weggezogenen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09585",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "2.4-1",
		"stufe1": "Ziel 2: Finanzkraft des Kantons Basel-Stadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_241",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-04T04:07:01",
		"id": 9585
	},
	{
		"template": "line001",
		"data-id": 9586,
		"chart-id": 9586,
		"filter": "",
		"parentId": "8355",
		"children": [],
		"title": "Entwicklung Wertschöpfung nach Branche, Basel-Stadt",
		"subtitle": "real, indexiert (2014 = 100)",
		"lesehilfe": "Die reale Wertschöpfung in der Pharmaindustrie in Basel-Stadt hat sich seit 2014 mehr als verdreifacht, diejenige in der Chemie hat sich fast verdoppelt. Das Gastgewerbe hat während der Pandemie die deutlichsten Wertschöpfungseinbussen erlitten. Im Jahr 2022 konnte sich das Gastgewerbe wieder etwas erholen.",
		"erlaeuterungen": "Das Wachstum der realen Wertschöpfung wird in Preisen des Vorjahres gerechnet. Hier sind die Daten indexiert (Wert im Jahr 2014 = 100). Die dargestellten Branchen und Branchenaggregate basieren auf der allgemeinen Systematik der Wirtschaftszweige NOGA 2008.",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Wertschöpfung nach Branche, Basel-Stadt",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.09586",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "2.5-1",
		"stufe1": "Ziel 2: Finanzkraft des Kantons Basel-Stadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_251",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-07-12T08:24:01",
		"id": 9586
	},
	{
		"template": "line001",
		"data-id": 9587,
		"chart-id": 9587,
		"filter": "",
		"parentId": null,
		"children": [
			5194,
			6169,
			8908
		],
		"title": "Besuche in Theater, Kinos und Museen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Kinobesuche haben im Lauf der Zeit deutlich abgenommen: Von fast 1,1 Mio. im Jahr 2003 auf gut 670 000 im Jahr 2023. Bei den meisten Institutionen sind die Zahlen bis 2019 vergleichsweise konstant geblieben. Im Zuge der COVID-19-Pandemie kam es zu stärkeren Rückgängen, ab 2022 normalisierten sich die Werte wieder.",
		"erlaeuterungen": "In den Kategorien «Theater» und «Kleintheater» entsprechen die Zahlen jeweils der Saison von Mitte des Vorjahres bis Mitte des Datenjahres, also bspw. 2019 der Saison 2018/19. Bei der Stadtbibliothek sind nicht die Besuche, sondern die Ausleihen von Medien dargestellt.",
		"quellenangabe": [
			"Jeweilige Institutionen",
			"Bundesamt für Statistik (BFS), Film- und Kinostatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Besuche in Theater, Kinos und Museen",
		"thema": "16 Kultur und Sport",
		"unterthema": "Kultureinrichtungen",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "3.1-1",
		"stufe1": "Ziel 3: Zentrumsfunktion Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_311",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-04T04:07:03",
		"id": 9587
	},
	{
		"template": "template001",
		"data-id": 9588,
		"chart-id": 9588,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Arbeitsstätten im Detailhandel, nach Branche",
		"subtitle": "Innenstadt Basel",
		"lesehilfe": "Im Jahr 2022 gab es in der Innenstadt 558 Arbeitsstätten im Detailhandel, wobei die meisten dem Bereich Bekleidung und Lederwaren angehörten (148 bzw. 26,5%).",
		"erlaeuterungen": "Eine Arbeitsstätte ist ein an einem bestimmten Ort gelegenes Unternehmen (Einzelunternehmen) oder Teil eines Unternehmens (z. B. Werkstatt, Werk, Verkaufsladen, Büro, Dienststelle, Lager). An diesem Ort arbeiten eine oder mehrere Personen für dasselbe Unternehmen. Berücksichtigt werden alle Arbeitsstätten, die der AHV-Beitragspflicht unterstehen (ab 2 300 Franken Jahreslohn). Bei Unternehmen mit mehreren Arbeitsstätten wird die Struktur gemäss Angaben der Unternehmen erfasst. Dabei ist nicht auszuschliessen, dass es sich bei der Verteilung auf die verschiedenen Arbeitsstätten teilweise um rein administrative Zuordnungen handeln kann und nicht alle effektiv vorhandenen Arbeitsstätten abgebildet sind.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Arbeitsstätten im Detailhandel, nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09588",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "3.2-1",
		"stufe1": "Ziel 3: Zentrumsfunktion Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_321",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-04T04:07:04",
		"id": 9588
	},
	{
		"template": "template001",
		"data-id": 9589,
		"chart-id": 9589,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Veränderung der Anzahl Arbeitsstätten im Detailhandel",
		"subtitle": "Innenstadt Basel, 2022 gegenüber 2018",
		"lesehilfe": "Die Anzahl Arbeitsstätten im Detailhandel hat in der Innenstadt zwischen 2018 und 2022 um 7,0% abgenommen. Den stärksten Rückgang gab es mit -17,9% im Bereich Verlagsproduktion, Sport- und Spielwaren. Der Bereich der Antiquitäten und Gebrauchtwaren verzeichnete mit +12,5% den einzigen Zuwachs.",
		"erlaeuterungen": "Eine Arbeitsstätte ist ein an einem bestimmten Ort gelegenes Unternehmen (Einzelunternehmen) oder Teil eines Unternehmens (z. B. Werkstatt, Werk, Verkaufsladen, Büro, Dienststelle, Lager). An diesem Ort arbeiten eine oder mehrere Personen für dasselbe Unternehmen. Berücksichtigt werden alle Arbeitsstätten, die der AHV-Beitragspflicht unterstehen (ab 2 300 Franken Jahreslohn). Bei Unternehmen mit mehreren Arbeitsstätten wird die Struktur gemäss Angaben der Unternehmen erfasst. Dabei ist nicht auszuschliessen, dass es sich bei der Verteilung auf die verschiedenen Arbeitsstätten teilweise um rein administrative Zuordnungen handeln kann und nicht alle effektiv vorhandenen Arbeitsstätten abgebildet sind.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Veränderung der Anzahl Arbeitsstätten im Detailhandel",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09589",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "3.2-2",
		"stufe1": "Ziel 3: Zentrumsfunktion Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_322",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-04T04:07:05",
		"id": 9589
	},
	{
		"template": "line001",
		"data-id": 9590,
		"chart-id": 7588,
		"filter": "",
		"parentId": "7588",
		"children": [],
		"title": "Geschäftsleerstandsfläche nach Nutzung",
		"subtitle": "in m², Basel-Stadt",
		"lesehilfe": "Das Angebot leerstehender Geschäftsflächen hat zwischen 2023 und 2024 von 190 600 m² auf 249 200 m² zugenommen. Dies ist hauptsächlich auf eine Zunahme im Bürobereich von 134 300 m² auf 175 100 m² zurückzuführen.",
		"erlaeuterungen": "Die Erhebung wird vom Schweizerischen Verband der Immobilienwirtschaft (SVIT) beider Basel durchgeführt. Stichtag ist der 1. Juni.",
		"quellenangabe": [
			"Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Geschäftsleerstandsfläche nach Nutzung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "3.3-1",
		"stufe1": "Ziel 3: Zentrumsfunktion Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_331",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-16T09:26:00",
		"id": 9590
	},
	{
		"template": "template001",
		"data-id": 9592,
		"chart-id": 9592,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Fussgängerinnen und Fussgänger",
		"subtitle": "Tagesdurchschnitt Mo-Fr und Sa, Innenstadt Basel",
		"lesehilfe": "Im Jahr 2022 passierten unter der Woche täglich durchschnittlich 8 584 Fussgänger die Zählstelle in der Gerbergasse. An Samstagen waren es mit 13 390 deutlich mehr.",
		"erlaeuterungen": "Wo keine Werte ausgewiesen sind, war die Zählstelle noch nicht in Betrieb, vorübergehend ausser Betrieb oder es wurden nicht genügend Messwerte aufgezeichnet. Ein Jahreswert wird bei mehr als neun gezählten Monaten ausgewiesen. Bei der Zählstelle Mittlere Rheinbrücke wird nur die Seite Schifflände ausgewiesen. Erneuerungsarbeiten an der Greifengasse und auf der Mittleren Rheinbrücke in den Jahren 2017 und 2018 hatten grössere Beeinträchtigungen im Innenstadtbereich zur Folge.",
		"quellenangabe": [
			"Amt für Mobilität Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Fussgängerinnen und Fussgänger",
		"thema": "11 Verkehr",
		"unterthema": "Mobilitätsverhalten",
		"kuerzel": "I.11.6.09592",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "4.1-1",
		"stufe1": "Ziel 4: Stadtgerechte Mobilität fördern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_411",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-13T10:14:38",
		"id": 9592
	},
	{
		"template": "template001",
		"data-id": 9593,
		"chart-id": 9593,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Velofahrende",
		"subtitle": "Tagesdurchschnitt Mo-Fr und Sa, Innenstadt Basel",
		"lesehilfe": "Im Jahr 2022 passierten unter der Woche täglich durchschnittlich 9 423 Velos die Zählstelle bei der Wettsteinbrücke. An Samstagen fuhren dort mit 5 425 weniger Velos vorbei.",
		"erlaeuterungen": "Wo keine Werte ausgewiesen sind, war die Zählstelle noch nicht in Betrieb, vorübergehend ausser Betrieb oder es wurden nicht genügend Messwerte aufgezeichnet. Ein Jahreswert wird bei mehr als neun gezählten Monaten ausgewiesen. Die Zählstelle «352 Johanniterbrücke» (hellblaue Säulen) war bis 2017 aktiv und hat den Verkehr nur in eine Fahrtrichtung erfasst. Im Jahr 2019 wurde sie durch die Zählstelle «952 Johanniterbrücke» (dunkelblaue Säulen) ersetzt, welche mit neuer Technik und an einem leicht anderen Ort installiert wurde. Die Werte dieser beiden Zählstellen sind deshalb nicht vergleichbar.",
		"quellenangabe": [
			"Amt für Mobilität Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Velofahrende",
		"thema": "11 Verkehr",
		"unterthema": "Mobilitätsverhalten",
		"kuerzel": "I.11.6.09593",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "4.2-1",
		"stufe1": "Ziel 4: Stadtgerechte Mobilität fördern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_421",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-10-13T10:14:39",
		"id": 9593
	},
	{
		"template": "template001",
		"data-id": 9594,
		"chart-id": 9594,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Einfahrten in Parkhäuser in der Innenstadt",
		"subtitle": "Durchschnittliche Einfahrten pro Tag, Innenstadt Basel",
		"lesehilfe": "An Werktagen wurden im Jahr 2023 in den vier Parkhäusern der Innenstadt zusammen durchschnittlich 5 668 Einfahrten pro Tag registriert, an Samstagen waren es 6 583. An Werktagen wurden am meisten Einfahrten im Parkhaus City (1 654) gezählt, an Samstagen war das Parkhaus Elisabethen (2 128) am besten besucht.",
		"erlaeuterungen": "Aufgrund von technischen Problemen sind für das Parkhaus City erst ab dem Jahr 2021 Daten verfügbar.",
		"quellenangabe": [
			"Parkhäuser Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Einfahrten in Parkhäuser in der Innenstadt",
		"thema": "11 Verkehr",
		"unterthema": "Motorfahrzeuge",
		"kuerzel": "I.11.1.09594",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "4.4-1",
		"stufe1": "Ziel 4: Stadtgerechte Mobilität fördern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_441",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-16T03:13:27",
		"id": 9594
	},
	{
		"template": "template001",
		"data-id": 9595,
		"chart-id": 9595,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Parkhausauslastung Montag bis Freitag in der Innenstadt",
		"subtitle": "nach Stunden, Innenstadt Basel",
		"lesehilfe": "2022 war die höchste durchschnittliche Auslastung der innenstädtischen Parkhäuser an Werktagen mit 73,4% zwischen 12 und 13 Uhr zu beobachten.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Parkhäuser Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Parkhausauslastung Montag bis Freitag in der Innenstadt",
		"thema": "11 Verkehr",
		"unterthema": "Motorfahrzeuge",
		"kuerzel": "I.11.1.09595",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "4.5-1",
		"stufe1": "Ziel 4: Stadtgerechte Mobilität fördern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_451",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-09-24T03:31:44",
		"id": 9595
	},
	{
		"template": "template001",
		"data-id": 9596,
		"chart-id": 9596,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Parkhausauslastung an Samstagen in der Innenstadt",
		"subtitle": "nach Stunden, Innenstadt Basel",
		"lesehilfe": "2022 war die höchste durchschnittliche Auslastung der innenstädtischen Parkhäuser an Samstagen zwischen 13 und 14 Uhr zu beobachten (67,0%).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Parkhäuser Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Parkhausauslastung an Samstagen in der Innenstadt",
		"thema": "11 Verkehr",
		"unterthema": "Motorfahrzeuge",
		"kuerzel": "I.11.1.09596",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "4.5-2",
		"stufe1": "Ziel 4: Stadtgerechte Mobilität fördern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_452",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-09-24T03:31:45",
		"id": 9596
	},
	{
		"template": "template001",
		"data-id": 9597,
		"chart-id": 9597,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Aussteigende ÖV-Passagiere an Haltestellen in der Innenstadt",
		"subtitle": "Tagesdurchschnitt Mo-Do/Fr, Innenstadt Basel",
		"lesehilfe": "Die Zahl der an Haltestellen in der Innenstadt aussteigenden ÖV-Passagiere hat während der beiden Pandemie-Jahre 2020 und 2021 abgenommen. Im Jahr 2021 wurden unter der Woche durchschnittlich rund 130 000 Passagiere täglich gezählt, das sind 46% weniger als im Mittel der Jahre 2011 bis 2020. 2022 nahm die Zahl der aussteigenden Passagiere im Vergleich zum Vorjahr wieder um rund ein Viertel zu.",
		"erlaeuterungen": "Modellrechungen für alle Haltestellen im Perimeter Innenstadt. Berücksichtigt sind die Passagierzahlen der Basler Verkehrsbetriebe (BVB), der Baselland Transport AG (BLT), der Autobus AG Liestal (AAGL), sowie seit 2019 des öffentlichen Busbetriebs in der Communauté d'agglomération des Trois Frontières im Elsass (Distribus) und seit 2020 der Südwestdeutschen Landesverkehrs-GmbH (SWEG). BVB, Distribus und SWEG: Mo-Do; BLT und AAGL: Mo-Fr.",
		"quellenangabe": [
			"Amt für Mobilität Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Aussteigende ÖV-Passagiere an Haltestellen in der Innenstadt",
		"thema": "11 Verkehr",
		"unterthema": "Öffentlicher Verkehr",
		"kuerzel": "I.11.2.09597",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "4.3-1",
		"stufe1": "Ziel 4: Stadtgerechte Mobilität fördern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_431",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-11-29T11:54:03",
		"id": 9597
	},
	{
		"template": "template001",
		"data-id": 9598,
		"chart-id": 6126,
		"filter": "",
		"parentId": "6126",
		"children": [],
		"title": "Kantonaler Wettbewerbsindikator (KWI)",
		"subtitle": "Basel-Stadt im kantonalen Vergleich, 2023",
		"lesehilfe": "Im Jahr 2023 liegt Basel-Stadt beim Kantonalen Wettbewerbsindikator (KWI) der UBS mit einem Wert von 99,2 auf Rang 2 aller Schweizer Kantone. Der Nachbarkanton Basel-Landschaft belegt Rang 6.",
		"erlaeuterungen": "Der Kantonale Wettbewerbsindikator (KWI) der UBS gibt Aufschluss über das relative längerfristige Wachstumspotenzial eines Kantons. Die Wettbewerbsfähigkeit eines Kantons beschreibt sein Potenzial für eine nachhaltige Steigerung seiner Wirtschaftsleistung. Kantone mit einer hohen relativen Wettbewerbsfähigkeit dürften längerfristig stärker wachsen als die Schweizer Gesamtwirtschaft. Hingegen ist in Kantonen mit einer tiefen relativen Wettbewerbsfähigkeit mit einem unterdurchschnittlichen Wachstum zu rechnen. Der KWI basiert auf der vergleichenden Analyse von acht thematischen Säulen mit insgesamt über 50 Variablen. Die Variablen werden gewichtet, aggregiert und normiert, sodass jeder Kanton für jede Säule eine Punktzahl zwischen 0 und 100 erhält. Zur Ermittlung des KWI wird für jeden Kanton der Durchschnitt aus den Punktzahlen der acht Säulen errechnet und so normiert, dass der höchste kantonale Durchschnittswert 100 beträgt.",
		"quellenangabe": [
			"UBS Switzerland AG"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Schweiz"
		],
		"description": "Kantonaler Wettbewerbsindikator (KWI)",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.09598",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "5.1-1",
		"stufe1": "Ziel 5: Internationale Ausstrahlung und Anziehungskraft Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_511",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-04T04:07:05",
		"id": 9598
	},
	{
		"template": "template001",
		"data-id": 9599,
		"chart-id": 6011,
		"filter": "",
		"parentId": "6011",
		"children": [],
		"title": "Wanderungssaldo",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2024 ergab sich durch Zu- und Wegzüge im Kanton Basel-Stadt ein Plus von 1 133 Personen. Im betrachteten Zeitraum gab es nur im Jahr 2021 einen negativen Saldo.",
		"erlaeuterungen": "Der Wanderungssaldo ist die Differenz der von ausserhalb in den Kanton Basel-Stadt Zugezogenen und der aus dem Kanton Basel-Stadt Weggezogenen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wanderungssaldo",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "5.2-1",
		"stufe1": "Ziel 5: Internationale Ausstrahlung und Anziehungskraft Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_521",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-13T02:46:13",
		"id": 9599
	},
	{
		"template": "line001",
		"data-id": 9600,
		"chart-id": 6546,
		"filter": "",
		"parentId": "6546",
		"children": [],
		"title": "Logiernächte nach Herkunft der Gäste",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2023 wurden sowohl der Vorjahreswert als auch die 1,42 Millionen Übernachtungen im Jahr 2019 überboten. 1,47 Millionen Logiernächte bedeuten einen neuen Höchststand für die Basler Hotellerie. Dies sind 13,4% bzw. 173 868 mehr als 2022. Gäste aus der Schweiz übernachteten im Berichtsjahr 541 147 Mal in einem baselstädtischen Hotel, 2022 waren es 536 630. Dies entspricht einem Plus von 4 517 Logiernächten oder 0,8%. Gäste aus dem Ausland logierten 2023 insgesamt 933 828 Mal in einem Hotel in Basel-Stadt, 2022 waren es 764 477. Hier beträgt der Zuwachs 169 351 Logiernächte bzw. 22,2%. Im Jahresdurchschnitt 2023 übernachteten rund 4 000 Gäste pro Tag in den baselstädtischen Hotelbetrieben. Der Höchstwert der täglichen Übernachtungen wurde am Samstag, 9. Dezember mit 8 007 registriert, der Tiefstwert am Sonntag, 8. Januar mit 1 455.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Logiernächte nach Herkunft der Gäste",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "5.3-1",
		"stufe1": "Ziel 5: Internationale Ausstrahlung und Anziehungskraft Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_531",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-04T04:07:06",
		"id": 9600
	},
	{
		"template": "template001",
		"data-id": 9601,
		"chart-id": 7971,
		"filter": "",
		"parentId": "7971",
		"children": [],
		"title": "Hotelübernachtungen",
		"subtitle": "pro Einwohner, 2021",
		"lesehilfe": "Am meisten Hotelübernachtungen pro Einwohner werden 2021 in der Kernstadt Genf (5,4) registriert. In der Agglomeration Basel zeigen die Kernstadt (4,5 Hotelübernachtungen pro Einwohner) und die deutschen Gemeinden (2,7) eine höhere touristische Attraktivität als die übrige Agglomeration.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Hotelübernachtungen",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "5.3-2",
		"stufe1": "Ziel 5: Internationale Ausstrahlung und Anziehungskraft Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_532",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-21T02:31:43",
		"id": 9601
	},
	{
		"template": "line001",
		"data-id": 9691,
		"chart-id": 9691,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Saldo des Ertrags aus Einkommens- und Vermögenssteuer von Zu- und Weggezogenen",
		"subtitle": "in Franken, Basel-Stadt und Innenstadt",
		"lesehilfe": "Von Personen, die in der Innenstadt wohnen, ergab sich im Jahr 2021 durch Zu- und Wegzüge ein positiver Saldo des Steuerertrags von rund 0,9 Mio. Franken. Für den gesamten Kanton ergab sich - einschliesslich Gemeindesteuer - ein Plus von rund 2,0 Mio. Franken.",
		"erlaeuterungen": "Die Methodik zur Untersuchung des Wanderungseffekts unterscheidet sich von den übrigen Auswertungen der Steuerstatistik Basel-Stadt. Die Analyse der Effekte auf den Ertrag aus Einkommens- und Vermögenssteuer durch Zu- und Abwanderung im Kanton Basel-Stadt wird durch verschiedene methodische Aspekte erschwert. Seit der eidgenössischen Steuerharmonisierung im Jahr 2002 ist für die Steuerpflicht innerhalb der Schweiz der Wohnsitz am 31. Dezember massgebend. Es liegen daher in Basel-Stadt in der Regel keine Daten zur Einkommens- und Vermögenssituation im Jahr des Wegzugs vor. Für die Steuerstatistik der Wegzügerinnen und Wegzüger wurden daher die Steuerdaten des jeweiligen Vorjahres verwendet. Für die Zugezogenen und die ganzjährig Niedergelassenen sind die Steuerdaten des Berichtsjahres vorhanden und wurden für die Analyse verwendet. Bei der Definition der Zuzüger wurde berücksichtigt, dass Ausländer ohne Niederlassungsbewilligung in der Regel an der Quelle veranlagt werden. Aus diesem Grund wurde ein Zuzug erst bei einer Niederlassung als solcher gezählt. Quellensteuerpflichtige sind in der Regel nicht erfasst, ausser sie werden nachträglich ordentlich veranlagt. Dies ist zum Beispiel der Fall, wenn die Einkünfte mehr als 120 000 Franken im Kalenderjahr betragen.<br>In der Auswertung ist sowohl die Kantons- als auch die Gemeindesteuer berücksichtigt.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Innenstadt"
		],
		"description": "Saldo des Ertrags aus Einkommens- und Vermögenssteuer von Zu- und Weggezogenen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09691",
		"kennzahlenset": "Innenstadt-QuiZ",
		"kuerzelKunde": "2.4-2",
		"stufe1": "Ziel 2: Finanzkraft des Kantons Basel-Stadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_242",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-04T04:07:02",
		"id": 9691
	}
];