var indikatorensetData = [
	{
		"template": "template001",
		"data-id": 9575,
		"chart-id": 9575,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Arbeitsstätten nach Branche",
		"subtitle": "Innenstadt und Stadt Basel",
		"lesehilfe": "In der Innenstadt befinden sich 4 479 Arbeitsstätten. Rund 21% gehören zur Branchengruppe Unternehmensdienstleistungen und Freiberufe, 16% zum Gesundheits- und Sozialwesen und 13% zum Detailhandel (gesamte Stadt Basel: 8%).",
		"erlaeuterungen": "Eine Arbeitsstätte ist ein an einem bestimmten Ort gelegenes Unternehmen (Einzelunternehmen) oder Teil eines Unternehmens (z. B. Werkstatt, Werk, Verkaufsladen, Büro, Dienststelle, Lager). An diesem Ort arbeiten eine oder mehrere Personen für dasselbe Unternehmen. Berücksichtigt werden alle Arbeitsstätten, die der AHV-Beitragspflicht unterstehen (ab 2 300 Franken Jahreslohn). Bei Unternehmen mit mehreren Arbeitsstätten wird die Struktur gemäss Angaben der Unternehmen erfasst. Dabei ist nicht auszuschliessen, dass es sich bei der Verteilung auf die verschiedenen Arbeitsstätten teilweise um rein administrative Zuordnungen handeln kann und nicht alle effektiv vorhandenen Arbeitsstätten abgebildet sind.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Stadt Basel",
			"Innenstadt"
		],
		"description": "Arbeitsstätten nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09575",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "1.1-1",
		"stufe1": "Ziel 1: Funktionsvielfalt der Innenstadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:19:54",
		"id": 9575
	},
	{
		"template": "template001",
		"data-id": 9576,
		"chart-id": 9576,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Arbeitsstättenentwicklung nach Branche",
		"subtitle": "Basel-Stadt, 2019 gegenüber 2015",
		"lesehilfe": "Die Anzahl Arbeitsstätten in der Innenstadt hat zwischen 2015 und 2019 insgesamt um 1,7% abgenommen. Deutliche Rückgänge waren im Bereich Bau und Verkehr (-27%) sowie im Grosshandel (-23%) zu beobachten. Am stärksten zugenommen hat die Zahl der Arbeitsstätten im Gesundheits- und Sozialwesen.",
		"erlaeuterungen": "Eine Arbeitsstätte ist ein an einem bestimmten Ort gelegenes Unternehmen (Einzelunternehmen) oder Teil eines Unternehmens (z. B. Werkstatt, Werk, Verkaufsladen, Büro, Dienststelle, Lager). An diesem Ort arbeiten eine oder mehrere Personen für dasselbe Unternehmen. Berücksichtigt werden alle Arbeitsstätten, die der AHV-Beitragspflicht unterstehen (ab 2 300 Franken Jahreslohn). Bei Unternehmen mit mehreren Arbeitsstätten wird die Struktur gemäss Angaben der Unternehmen erfasst. Dabei ist nicht auszuschliessen, dass es sich bei der Verteilung auf die verschiedenen Arbeitsstätten teilweise um rein administrative Zuordnungen handeln kann und nicht alle effektiv vorhandenen Arbeitsstätten abgebildet sind.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Stadt Basel",
			"Innenstadt"
		],
		"description": "Arbeitsstättenentwicklung nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09576",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "1.1-2",
		"stufe1": "Ziel 1: Funktionsvielfalt der Innenstadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:19:55",
		"id": 9576
	},
	{
		"template": "line001",
		"data-id": 9577,
		"chart-id": 9577,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Belegungsdauer der Allmend in der Innenstadt",
		"subtitle": "nach Veranstaltungsort, in Tagen, Basel-Stadt",
		"lesehilfe": "Im Jahr 2021 fanden auf dem Münsterplatz an 20 Tagen bewilligte Veranstaltungen statt. Die Belegungstage der Kaserne wurden von 2011 bis 2014 nach anderer, nicht vergleichbarer Methodik erfasst und sind deshalb nicht abgebildet.",
		"erlaeuterungen": "Abgebildet ist die Anzahl Tage, an denen auf den jeweiligen Plätzen bewilligte Veranstaltungen stattfinden. Für jeden Platz existiert ein jährliches Kontingent der maximalen Veranstaltungstage sowie ein Kontingent für Veranstaltungstage mit besonders lärmintensiven Auswirkungen. Der Regierungsrat kann darüber hinaus zusätzliche Veranstaltungstage bewilligen.<br>Als Veranstaltung im Sinne der Bespielungspläne gelten alle Anlässe auf Allmend, die nach 20:00 Uhr stattfinden oder Anlässe, die vor 20:00 Uhr Lautsprecher und/oder unverstärkte laute Musikinstrumente einsetzen. Nicht als Veranstaltung im Sinne des Bespielungsplanes gelten bspw. tagsüber stattfindene Märkte oder die Fasnacht. <br>Barfüsser- und Theaterplatz werden bezüglich der Kontingente für Veranstaltungen als eine Einheit bewirtschaftet. Auf der Kaserne werden gemäss Bespielungsplan die Belegungstage erfasst (inkl. Auf- und Abbau), auf allen anderen Plätzen nur die effektiven Veranstaltungstage (Bespielung). Details zu den Bespielungsplänen siehe Links.",
		"quellenangabe": [
			"Allmendverwaltung Basel-Stadt"
		],
		"externalLinks": [
			"Tiefbauamt Basel-Stadt, <a href = 'https://www.tiefbauamt.bs.ch/oeffentlicher-raum/nutzung-des-oeffentlichen-raumes/veranstaltungen.html' target = '_blank'>Veranstaltungen im öffentlichen Raum</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Belegungsdauer der Allmend in der Innenstadt",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "1.2-1",
		"stufe1": "Ziel 1: Funktionsvielfalt der Innenstadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:19:55",
		"id": 9577
	},
	{
		"template": "line001",
		"data-id": 9578,
		"chart-id": 9578,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Lärmintensive Veranstaltungen auf der Allmend in der Innenstadt",
		"subtitle": "nach Veranstaltungsort, in Tagen, Basel-Stadt",
		"lesehilfe": "Auf dem Barfüsser- und dem Theaterplatz fanden 2021 an 16 Tagen lärmintensive bewilligte Veranstaltungen statt.",
		"erlaeuterungen": "Abgebildet ist die Anzahl Tage, an denen auf den jeweiligen Plätzen bewilligte lärmintensive Veranstaltungen stattfinden (bspw. ausgesprochene Musikanlässe, wie bass- und rhythmusbetonte Live-Konzerte, Discos und Kino, respektive Anlässe mit einem hohen Animationsanteil). Für jeden Platz existiert ein jährliches Kontingent der maximalen Veranstaltungstage sowie ein Kontingent für Veranstaltungstage mit besonders lärmintensiven Auswirkungen. Der Regierungsrat kann darüber hinaus zusätzliche Veranstaltungstage bewilligen.<br>Als Veranstaltung im Sinne der Bespielungspläne gelten alle Anlässe auf Allmend, die nach 20:00 Uhr stattfinden oder Anlässe, die vor 20:00 Uhr Lautsprecher und/oder unverstärkte laute Musikinstrumente einsetzen. Nicht als Veranstaltung im Sinne des Bespielungsplanes gelten bspw. tagsüber stattfindene Märkte oder die Fasnacht. <br>Barfüsser- und Theaterplatz werden bezüglich der Kontingente für Veranstaltungen als eine Einheit bewirtschaftet. Auf der Kaserne werden gemäss Bespielungsplan die Belegungstage erfasst (inkl. Auf- und Abbau), auf allen anderen Plätzen nur die effektiven Veranstaltungstage (Bespielung). Details zu den Bespielungsplänen siehe Links.",
		"quellenangabe": [
			"Allmendverwaltung Basel-Stadt"
		],
		"externalLinks": [
			"Tiefbauamt Basel-Stadt, <a href = 'https://www.tiefbauamt.bs.ch/oeffentlicher-raum/nutzung-des-oeffentlichen-raumes/veranstaltungen.html' target = '_blank'>Veranstaltungen im öffentlichen Raum</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Lärmintensive Veranstaltungen auf der Allmend in der Innenstadt",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "1.2-2",
		"stufe1": "Ziel 1: Funktionsvielfalt der Innenstadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:19:55",
		"id": 9578
	},
	{
		"template": "line001",
		"data-id": 9581,
		"chart-id": 9581,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "In der Innenstadt leben im Jahr 2021 14 290 Menschen. Dies sind 10,6% mehr als 2008. Im Kanton Basel-Stadt wuchs die Einwohnerzahl in diesem Zeitraum um 6,6% auf 201 805.",
		"erlaeuterungen": "Bevölkerungsbestand am Jahresende.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Innenstadt"
		],
		"description": "Wohnbevölkerung",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.09581",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "2.1-1",
		"stufe1": "Ziel 2: Finanzkraft des Kantons Basel-Stadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:19:58",
		"id": 9581
	},
	{
		"template": "line001",
		"data-id": 9582,
		"chart-id": 9582,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sesshaftigkeit",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "In der Innenstadt liegt der Anteil der Personen, die seit zehn oder mehr Jahren an der gleichen Adresse wohnen, Ende 2021 bei 29,4%. Im Kanton Basel-Stadt liegt die Sesshaftigkeit Ende 2021 bei 34,4%.",
		"erlaeuterungen": "Anteil der seit mindestens zehn Jahren an der gleichen Adresse wohnenden Personen an der gesamten Wohnbevölkerung des Wohnviertels in Prozent. Ohne Personen an administrativen Meldeadressen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Innenstadt"
		],
		"description": "Sesshaftigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.09582",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "2.1-2",
		"stufe1": "Ziel 2: Finanzkraft des Kantons Basel-Stadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:19:58",
		"id": 9582
	},
	{
		"template": "template001",
		"data-id": 9583,
		"chart-id": 9583,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Nettomietpreise Innenstadt",
		"subtitle": "in Franken pro m<sup>2</sup>, Basel-Stadt, 2016-2020",
		"lesehilfe": "Die Nettomiete pro m<sup>2</sup> von 3- und 4-Zimmer-Wohnungen liegt in der Innenstadt im Durchschnitt der Jahre 2016 bis 2020 bei 18,5 Franken.",
		"erlaeuterungen": "Der m²-Preis bezieht sich auf die Nettomiete, dividiert durch die Wohnfläche von 3- oder 4-Zimmer-Wohnungen. Die Daten stammen aus der Strukturerhebung. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe und sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2016 bis 2020 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Innenstadt"
		],
		"description": "Nettomietpreise Innenstadt",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Mietpreise",
		"kuerzel": "I.09.3.09583",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "2.2-1",
		"stufe1": "Ziel 2: Finanzkraft des Kantons Basel-Stadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:19:59",
		"id": 9583
	},
	{
		"template": "line001",
		"data-id": 9584,
		"chart-id": 9584,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Reineinkommen pro Veranlagung",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "2019 beträgt das durchschnittliche Reineinkommen pro Veranlagung von Personen, die in der Innenstadt wohnen, rund 89 600 Franken. Der Wert für den ganzen Kanton beträgt ca. 72 400 Franken.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Innenstadt"
		],
		"description": "Reineinkommen pro Veranlagung",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "2.3-1",
		"stufe1": "Ziel 2: Finanzkraft des Kantons Basel-Stadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:19:59",
		"id": 9584
	},
	{
		"template": "line001",
		"data-id": 9585,
		"chart-id": 9585,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Summe des Ertrags aus Einkommens- und Vermögenssteuer von Zu- und Weggezogenen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Von Personen, die in der Innenstadt wohnen, ergab sich im Jahr 2019 durch Zu- und Wegzüge ein positiver Saldo des Steuerertrags von rund 1,5 Mio. Franken (Zuzüger: 5,0 Mio. Franken; Wegzüger 3,5 Mio. Franken). Für den gesamten Kanton ergab sich - einschliesslich Gemeindesteuer - ein Plus von 6,2 Mio. Franken.",
		"erlaeuterungen": "Die Methodik zur Untersuchung des Wanderungseffekts unterscheidet sich von den übrigen Auswertungen in der Steuerstatistik Basel-Stadt. Die Analyse der Effekte auf den Ertrag aus Einkommens- und Vermögenssteuer durch Zu- und Abwanderung im Kanton Basel-Stadt wird durch verschiedene methodische Aspekte erschwert. Seit der eidgenössischen Steuerharmonisierung im Jahr 2002 ist für die Steuerpflicht innerhalb der Schweiz der Wohnsitz am 31. Dezember massgebend. Es liegen daher in Basel-Stadt in der Regel keine Daten zur Einkommens- und Vermögenssituation im Jahr des Wegzugs vor. Für die Steuerstatistik der Wegzügerinnen und Wegzüger wurden daher die Steuerdaten des jeweiligen Vorjahres verwendet. Für die Zugezogenen und die ganzjährig Niedergelassenen sind die Steuerdaten des Berichtsjahres vorhanden und wurden für die Analyse verwendet. Bei der Definition der Zuzüger wurde berücksichtigt, dass Ausländer ohne Niederlassungsbewilligung in der Regel an der Quelle veranlagt werden. Aus diesem Grund wurde ein Zuzug erst bei einer Niederlassung als solcher gezählt. Quellensteuerpflichtige sind in der Regel nicht erfasst, ausser sie werden nachträglich ordentlich veranlagt. Dies ist zum Beispiel der Fall, wenn die Einkünfte mehr als 120 000 Franken im Kalenderjahr betragen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Innenstadt"
		],
		"description": "Summe des Ertrags aus Einkommens- und Vermögenssteuer von Zu- und Weggezogenen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "2.4-1",
		"stufe1": "Ziel 2: Finanzkraft des Kantons Basel-Stadt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:19:59",
		"id": 9585
	},
	{
		"template": "line001",
		"data-id": 9587,
		"chart-id": 9587,
		"filter": "",
		"parentId": "6169",
		"children": [],
		"title": "Anzahl Besuche in Theater, Kinos und Museen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Kinobesuche haben im Lauf der Zeit deutlich abgenommen: von fast 1,1 Mio. im Jahr 2003 auf rund 594 000 im Jahr 2019. Bei den übrigen Institutionen blieben die Zahlen vergleichsweise konstant.",
		"erlaeuterungen": "In den Kategorien «Theater» und «Kleintheater» entsprechen die Zahlen jeweils der Saison von Mitte des Vorjahres bis Mitte des Datenjahres, also bspw. 2019 der Saison 2018/19.",
		"quellenangabe": [
			"Jeweilige Institutionen",
			"Bundesamt für Statistik (BFS), Film- und Kinostatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Besuche in Theater, Kinos und Museen",
		"thema": "16 Kultur und Sport",
		"unterthema": "Kultureinrichtungen",
		"kuerzel": "I.16.1.09587",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "3.1-1",
		"stufe1": "Ziel 3: Zentrumsfunktion Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:20:00",
		"id": 9587
	},
	{
		"template": "template001",
		"data-id": 9588,
		"chart-id": 9588,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Arbeitsstätten im Detailhandel in der Innenstadt, nach Branche",
		"subtitle": "Innenstadt Basel",
		"lesehilfe": "Im Jahr 2019 gab es in der Innenstadt 592 Arbeitsstätten im Detailhandel, das sind 99 bzw. 14,3% weniger als noch im Jahr 2011. Am meisten Arbeitsstätten gehören dem Bereich Kleidung und Lederwaren an (166 bzw. 28%).",
		"erlaeuterungen": "Eine Arbeitsstätte ist ein an einem bestimmten Ort gelegenes Unternehmen (Einzelunternehmen) oder Teil eines Unternehmens (z. B. Werkstatt, Werk, Verkaufsladen, Büro, Dienststelle, Lager). An diesem Ort arbeiten eine oder mehrere Personen für dasselbe Unternehmen. Berücksichtigt werden alle Arbeitsstätten, die der AHV-Beitragspflicht unterstehen (ab 2 300 Franken Jahreslohn). Bei Unternehmen mit mehreren Arbeitsstätten wird die Struktur gemäss Angaben der Unternehmen erfasst. Dabei ist nicht auszuschliessen, dass es sich bei der Verteilung auf die verschiedenen Arbeitsstätten teilweise um rein administrative Zuordnungen handeln kann und nicht alle effektiv vorhandenen Arbeitsstätten abgebildet sind.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Arbeitsstätten im Detailhandel in der Innenstadt, nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09588",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "3.2-1",
		"stufe1": "Ziel 3: Zentrumsfunktion Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:20:01",
		"id": 9588
	},
	{
		"template": "template001",
		"data-id": 9589,
		"chart-id": 9589,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Veränderung der Anzahl Arbeitsstätten im Detailhandel",
		"subtitle": "Innenstadt, 2019 gegenüber 2015",
		"lesehilfe": "Die Anzahl Arbeitsstätten im Detailhandel hat in der Innenstadt zwischen 2015 und 2019 um 8,6% abgenommen. Am stärksten war der Zuwachs mit 20,7% im Bereich Waren verschiedener Art, wozu unter anderem Supermärkte und Kaufhäuser zählen. Der stärkste Rückgang ist mit 23,0% im Bereich Haushaltsgeräte, Textilien, Möbel zu beobachten.",
		"erlaeuterungen": "Eine Arbeitsstätte ist ein an einem bestimmten Ort gelegenes Unternehmen (Einzelunternehmen) oder Teil eines Unternehmens (z. B. Werkstatt, Werk, Verkaufsladen, Büro, Dienststelle, Lager). An diesem Ort arbeiten eine oder mehrere Personen für dasselbe Unternehmen. Berücksichtigt werden alle Arbeitsstätten, die der AHV-Beitragspflicht unterstehen (ab 2 300 Franken Jahreslohn). Bei Unternehmen mit mehreren Arbeitsstätten wird die Struktur gemäss Angaben der Unternehmen erfasst. Dabei ist nicht auszuschliessen, dass es sich bei der Verteilung auf die verschiedenen Arbeitsstätten teilweise um rein administrative Zuordnungen handeln kann und nicht alle effektiv vorhandenen Arbeitsstätten abgebildet sind.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Veränderung der Anzahl Arbeitsstätten im Detailhandel",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09589",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "3.2-2",
		"stufe1": "Ziel 3: Zentrumsfunktion Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:20:01",
		"id": 9589
	},
	{
		"template": "befragungen001",
		"data-id": 9591,
		"chart-id": 9591,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Zufriedenheit mit verschiedenen Aspekten am Wohnort",
		"subtitle": "Basel",
		"lesehilfe": "2019 gaben fast 90% der befragten Personen in Basel an, mit den Einkaufsmöglichzkeiten an ihrem Wohnort zufrieden zu sein. 85% bzw. 81% sind zufrieden mit den Grünanlagen bzw. der öffentlichen Sicherheit. Mit der Sauberkeit sind drei Viertel zufrieden (37,4% «sehr» und 38,7% «eher zufrieden») und mit der Lärmsituation sind es 67% (25,8% «sehr» und 41,5% «eher zufrieden»).",
		"erlaeuterungen": "Alle vier Jahre wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt. Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Zufriedenheit mit verschiedenen Aspekten am Wohnort",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.09591",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "3.4-1",
		"stufe1": "Ziel 3: Zentrumsfunktion Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:20:02",
		"id": 9591
	},
	{
		"template": "template001",
		"data-id": 9592,
		"chart-id": 9592,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl zu Fuss gehende in der Innenstadt",
		"subtitle": "Tagesdurchschnitt",
		"lesehilfe": "Im Jahr 2021 überquerten an Werktagen durchschnittlich 11 710 Fussgänger die mittlere Rheinbrücke. An Samstagen waren es mit 17 839 deutlich mehr.",
		"erlaeuterungen": "Wo keine Werte ausgewiesen sind, war die Zählstelle noch nicht in Betrieb, vorübergehend ausser Betrieb oder es wurden nicht genügend Messwerte aufgezeichnet. Ein Jahreswert wird bei mehr als 9 gezählten Monaten ausgewiesen.",
		"quellenangabe": [
			"Amt für Mobilität Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Anzahl zu Fuss gehende in der Innenstadt",
		"thema": "11 Verkehr",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "4.1-1",
		"stufe1": "Ziel 4: Stadtgerechte Mobilität fördern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:20:02",
		"id": 9592
	},
	{
		"template": "template001",
		"data-id": 9593,
		"chart-id": 9593,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Velofahrende in der Innenstadt",
		"subtitle": "Tagesdurchschnitt",
		"lesehilfe": "Im Jahr 2021 passierten an Werktagen durchschnittlich 3 709 Velos die Zählstelle bei der Johanniterbrücke. An Samstagen fuhren dort mit 2 580 weniger Velos vorbei.",
		"erlaeuterungen": "Wo keine Werte ausgewiesen sind, war die Zählstelle noch nicht in Betrieb, vorübergehend ausser Betrieb oder es wurden nicht genügend Messwerte aufgezeichnet. Ein Jahreswert wird bei mehr als 9 gezählten Monaten ausgewiesen. Die Zählstelle «352 Johanniterbrücke» zählte nur in eine Richtung. Im Jahr 2019 wurde sie durch die neu installierte Zählstelle «952 Johanniterbrücke» ersetzt. Die Werte der beiden Zählstellen sind nicht vergleichbar.",
		"quellenangabe": [
			"Amt für Mobilität Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Anzahl Velofahrende in der Innenstadt",
		"thema": "11 Verkehr",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "4.1-2",
		"stufe1": "Ziel 4: Stadtgerechte Mobilität fördern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:20:02",
		"id": 9593
	},
	{
		"template": "template001",
		"data-id": 9594,
		"chart-id": 9594,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Einfahrten in Parkhäuser in der Innenstadt",
		"subtitle": "Durchschnittliche Einfahrten pro Tag",
		"lesehilfe": "Durchschnittlich 4 896 Einfahrten pro Tag wurden im Jahr 2021 in den vier Parkhäusern der Innenstadt zusammen registriert. Am meisten Einfahrten wurden mit 1 618 pro Tag im Parkhaus City gezählt.",
		"erlaeuterungen": "Wegen eines Datenbankdefekts sind für das Parkhaus City erst ab dem Jahr 2021 Daten verfügbar.",
		"quellenangabe": [
			"Parkhäuser Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Einfahrten in Parkhäuser in der Innenstadt",
		"thema": "11 Verkehr",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "4.1-3",
		"stufe1": "Ziel 4: Stadtgerechte Mobilität fördern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:20:03",
		"id": 9594
	},
	{
		"template": "template001",
		"data-id": 9595,
		"chart-id": 9595,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Parkhausauslastung an Werktagen (Mo - Fr) in der Innenstadt",
		"subtitle": "nach Stunden",
		"lesehilfe": "2021 war die höchste durchschnittliche Auslastung der innerstädtischen Parkhäuser  an Werktagen mit 70,0% zwischen 12 und 13 Uhr zu beobachten.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Parkhäuser Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Parkhausauslastung an Werktagen (Mo - Fr) in der Innenstadt",
		"thema": "11 Verkehr",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "4.2-1",
		"stufe1": "Ziel 4: Stadtgerechte Mobilität fördern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:20:03",
		"id": 9595
	},
	{
		"template": "template001",
		"data-id": 9596,
		"chart-id": 9596,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Parkhausauslastung an Samstagen in der Innenstadt",
		"subtitle": "nach Stunden",
		"lesehilfe": "2021 war die höchste durchschnittliche Auslastung der innerstädtischen Parkhäuser an Samstagen zwischen 13 und 14 Uhr zu beobachten (56,2%).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Parkhäuser Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Innenstadt"
		],
		"description": "Parkhausauslastung an Samstagen in der Innenstadt",
		"thema": "11 Verkehr",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "4.2-2",
		"stufe1": "Ziel 4: Stadtgerechte Mobilität fördern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:20:04",
		"id": 9596
	},
	{
		"template": "template001",
		"data-id": 9598,
		"chart-id": 6126,
		"filter": "",
		"parentId": "6126",
		"children": [],
		"title": "Kantonaler Wettbewerbsindikator (KWI)",
		"subtitle": "Basel-Stadt im kantonalen Vergleich, 2021",
		"lesehilfe": "Im Jahr 2021 liegt Basel-Stadt beim Kantonalen Wettbewerbsindikator (KWI) der UBS mit einem Wert von 97,9 auf Rang 2 aller Schweizer Kantone. Der Nachbarkanton Basel-Landschaft belegt Rang 7.",
		"erlaeuterungen": "Der Kantonale Wettbewerbsindikator (KWI) gibt Aufschluss über das relative längerfristige Wachstumspotenzial eines Kantons. Die Wettbewerbsfähigkeit eines Kantons beschreibt sein Potenzial für eine nachhaltige Steigerung seiner Wirtschaftsleistung. Kantone mit einer hohen relativen Wettbewerbsfähigkeit dürften längerfristig stärker wachsen als die Schweizer Gesamtwirtschaft. Hingegen ist in Kantonen mit einer tiefen relativen Wettbewerbsfähigkeit mit einem unterdurchschnittlichen Wachstum zu rechnen. Der KWI basiert auf der vergleichenden Analyse von acht Säulen mit insgesamt über 50 Variablen. Die Variablen werden gewichtet, aggregiert und normiert, sodass jeder Kanton für jede Säule eine Punktzahl zwischen 0 und 100 erhält. Zur Ermittlung des KWI wird für jeden Kanton der Durchschnitt aus den Punktzahlen der acht Säulen errechnet und so normiert, dass der höchste kantonale Durchschnittswert 100 beträgt.",
		"quellenangabe": [
			"UBS Switzerland AG"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Schweiz"
		],
		"description": "Kantonaler Wettbewerbsindikator (KWI)",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.09598",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "5.1-1",
		"stufe1": "Ziel 5: Internationale Ausstrahlung und Anziehungskraft Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:20:04",
		"id": 9598
	},
	{
		"template": "line001",
		"data-id": 9600,
		"chart-id": 6546,
		"filter": "",
		"parentId": "6546",
		"children": [],
		"title": "Logiernächte nach Herkunft der Gäste",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Nach einem Höchststand von 1,42 Millionen Übernachtungen im Jahr 2019 brach die Anzahl Logiernächte 2020 auf 545 906 Übernachtungen ein. Das Jahr 2021 schloss bei 784 607 Logiernächten, das sind 238 701 bzw. 43,7% mehr als 2020. Gäste aus der Schweiz übernachteten im Berichtsjahr 401 814 Mal in einem baselstädtischen Hotel, 2020 waren es 279 513. Dies entspricht einem Plus von 122 301 Logiernächten oder 43,8%. Gäste aus dem Ausland logierten 2021 insgesamt 382 793 Mal in einem Hotel in Basel-Stadt, 2020 waren es 266 393. Hier beträgt der Zuwachs 116 400 Logiernächte bzw. 43,7%.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Logiernächte nach Herkunft der Gäste",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.09600",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "5.3-1",
		"stufe1": "Ziel 5: Internationale Ausstrahlung und Anziehungskraft Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:20:05",
		"id": 9600
	},
	{
		"template": "template001",
		"data-id": 9601,
		"chart-id": 7971,
		"filter": "",
		"parentId": "7971",
		"children": [],
		"title": "Hotelübernachtungen",
		"subtitle": "pro Einwohner, 2019",
		"lesehilfe": "Die Kernstädte weisen die höchste Übernachtungskonzentration in Hotelbetrieben auf. Am meisten Hotelübernachtungen pro Einwohner werden 2019 in der Stadt Genf (10,8) registriert, gefolgt von den Städten Zürich (8,7) und Basel (8,2). In der Agglomeration Basel zeigen auch die deutschen Gemeinden eine relativ hohe touristische Attraktivität (4,5 Hotelübernachtungen pro Einwohner).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), City Statistics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Agglomeration"
		],
		"description": "Hotelübernachtungen",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.09601",
		"kennzahlenset": "Innenstadt - QuiZ",
		"kuerzelKunde": "5.3-1",
		"stufe1": "Ziel 5: Internationale Ausstrahlung und Anziehungskraft Basels stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-11T11:20:05",
		"id": 9601
	}
];