var indikatorensetData = [
	{
		"template": "template001_print",
		"data-id": 7573,
		"chart-id": 9066,
		"filter": "",
		"parentId": "7573",
		"children": [],
		"title": "Leerwohnungsbestand und -quote",
		"subtitle": "Basel-Stadt und Basel-Landschaft",
		"lesehilfe": "Die Leerstandsquote beider Basel zusammen sinkt leicht von 1,1% im letzten Jahr auf 1,0% im 2021. Insgesamt standen 2021 in den beiden Halbkantonen 2 639 Wohnungen leer, 51 weniger als 2020.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungsbestand und -quote",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09066",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-2-1",
		"stufe1": "Wohnungsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:18",
		"id": 9066
	},
	{
		"template": "template001_print",
		"data-id": 7574,
		"chart-id": 9067,
		"filter": "",
		"parentId": "7574",
		"children": [],
		"title": "Leerwohnungen nach Zimmerzahl sowie Leerstandsquote",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Leerstandsquote im Stadtkanton steigt 2021 auf 1,1%. Insgesamt stehen 1 235 Wohnungen leer, davon sind zwei Drittel Zwei- oder Dreizimmerwohnungen.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungen nach Zimmerzahl sowie Leerstandsquote",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09067",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-2-2",
		"stufe1": "Wohnungsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:18",
		"id": 9067
	},
	{
		"template": "line001_print",
		"data-id": 9068,
		"chart-id": 9068,
		"filter": "",
		"parentId": "7575",
		"children": [],
		"title": "Leerwohnungsbestand nach Gemeinde",
		"subtitle": "Basel-Stadt und Basel-Landschaft, 2021",
		"lesehilfe": "Die Verfügbarkeit auf den Stichtag 1. Juni hin kann die Leerwohnungsquote v. a. in kleineren Gemeinden mit insgesamt geringem Wohnungsbestand stark beeinflussen. Die Gemeinde Rümlingen mit einem Wohnungsbestand von insgesamt 184 Wohnungen erreicht mit drei Leerwohnungen eine Leerwohnungsquote von 1,6%.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Leerwohnungsbestand nach Gemeinde",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09068",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-2-4",
		"stufe1": "Wohnungsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:19",
		"id": 9068
	},
	{
		"template": "template001_print",
		"data-id": 7576,
		"chart-id": 9069,
		"filter": "",
		"parentId": "7576",
		"children": [],
		"title": "Leerwohnungen und Leerwohnungsquoten nach Kantonsgebiet",
		"subtitle": "Basel-Stadt und Basel-Landschaft, 2021",
		"lesehilfe": "Im Kanton Basel-Landschaft weisen die Bezirke Liestal (1,4%) und Laufen (1,2%) die höchsten Quoten auf. In den Bezirken Sissach (0,7%), Waldenburg (0,8%) und Arlesheim (0,9%) liegen die Leerwohnungsquoten hingegen unter dem gesamtkantonalen Wert von 1,0%. Im Stadtkanton (1,1%) liegen die Quoten in Gross- (1,2%) und Kleinbasel (1,0%) über jener von Riehen und Bettingen (0,7%).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk",
			"Gemeinde",
			"Wahlkreis"
		],
		"description": "Leerwohnungen und Leerwohnungsquoten nach Kantonsgebiet",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09069",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-2-5",
		"stufe1": "Wohnungsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:20",
		"id": 9069
	},
	{
		"template": "pie001_print",
		"data-id": 7577,
		"chart-id": 9070,
		"filter": "",
		"parentId": "7577",
		"children": [],
		"title": "Leerwohnungen nach Zimmerzahl",
		"subtitle": "Basel-Stadt, 2021",
		"lesehilfe": "Die Leerstandsquote der Dreizimmerwohnungen entspricht mit 1,1% der kantonalen Leerstandsquote. Die höchste Quote weisen mit 2,3% die Einzimmerwohnungen auf. Bei den Wohnungen mit sechs und mehr Zimmern ist sie mit 0,2% am niedrigstgen.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungen nach Zimmerzahl",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09070",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-3-1",
		"stufe1": "Wohnungsleerstand im Kanton Basel-Stadt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:20",
		"id": 9070
	},
	{
		"template": "pie001_print",
		"data-id": 7578,
		"chart-id": 9071,
		"filter": "",
		"parentId": "7578",
		"children": [],
		"title": "Leerwohnungen nach Bautätigkeit",
		"subtitle": "Basel-Stadt, 2021",
		"lesehilfe": "Knapp 81% der leerstehenden Wohnungen blieben in der letzen zwei Jahren unverändert, gut 14% wurden renoviert und 5% sind neu erstellt worden.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungen nach Bautätigkeit",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09071",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-3-2",
		"stufe1": "Wohnungsleerstand im Kanton Basel-Stadt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:21",
		"id": 9071
	},
	{
		"template": "template001_print",
		"data-id": 7579,
		"chart-id": 9072,
		"filter": "",
		"parentId": "7579",
		"children": [],
		"title": "Nettoproduktion an Wohnungen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Nettoproduktion von Wohnungen beträgt 2020 672 Einheiten. Davon  stammen 607 aus Neu- und 219 aus Umbauten. Durch Abbrüche gehen 158 Wohnungen verloren. 2021 wird mit einer Nettoproduktion von rund 850 Wohnungen gerechnet.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettoproduktion an Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09072",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-3-3",
		"stufe1": "Wohnungsleerstand im Kanton Basel-Stadt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:21",
		"id": 9072
	},
	{
		"template": "template001_print",
		"data-id": 7580,
		"chart-id": 9073,
		"filter": "",
		"parentId": "7580",
		"children": [],
		"title": "Wohnungen und Wohnbevölkerung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Leerwohnungsbestände von meist mehr als 800 Einheiten ergaben sich mit rückläufiger Bevölkerungszahl Mitte der 1970er- und 1980er-Jahre sowie von 1997 bis 2008. Seit 2019 liegt die Leerwohnungszahl bei steigender Bevölkerung über dieser Marke.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungen und Wohnbevölkerung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09073",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-3-4",
		"stufe1": "Wohnungsleerstand im Kanton Basel-Stadt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:22",
		"id": 9073
	},
	{
		"template": "pie001_print",
		"data-id": 7581,
		"chart-id": 9074,
		"filter": "",
		"parentId": "7581",
		"children": [],
		"title": "Leerwohnungen nach Zimmerzahl",
		"subtitle": "Basel-Landschaft, 2021",
		"lesehilfe": "Dreizimmerwohnungen weisen mit einer Quote von 1,5% den höchsten Leerstand auf. Sie machen rund 44% des Gesamtbestandes der leeren Wohnungen aus.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungen nach Zimmerzahl",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09074",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-4-1",
		"stufe1": "Wohnungsleerstand im Kanton Basel-Landschaft",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:23",
		"id": 9074
	},
	{
		"template": "pie001_print",
		"data-id": 7582,
		"chart-id": 9075,
		"filter": "",
		"parentId": "7582",
		"children": [],
		"title": "Leerwohnungen nach Bautätigkeit",
		"subtitle": "Basel-Landschaft, 2021",
		"lesehilfe": "Fast 80% der Leerwohnungen blieben in den zwei letzten Jahren unverändert, etwas unter 10% wurden neu erstellt.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungen nach Bautätigkeit",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09075",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-4-2",
		"stufe1": "Wohnungsleerstand im Kanton Basel-Landschaft",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:23",
		"id": 9075
	},
	{
		"template": "template001_print",
		"data-id": 7583,
		"chart-id": 9076,
		"filter": "",
		"parentId": "7583",
		"children": [],
		"title": "Nettoproduktion an Wohnungen",
		"subtitle": "Basel-Landschaft",
		"lesehilfe": "Die Nettoproduktion von Wohnungen steigt nach dem Rückgang zwischen 2015 und 2018 auch im Jahr 2021 weiter an.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettoproduktion an Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09076",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-4-3",
		"stufe1": "Wohnungsleerstand im Kanton Basel-Landschaft",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:24",
		"id": 9076
	},
	{
		"template": "template001_print",
		"data-id": 7584,
		"chart-id": 9077,
		"filter": "",
		"parentId": "7584",
		"children": [],
		"title": "Wohnungen und Wohnbevölkerung",
		"subtitle": "Basel-Landschaft",
		"lesehilfe": "Zum ersten Mal seit 2014 geht der Leerwohungsbestand 2021 zurück. Dies bei weiterhin steigender Bevölkerung und einer Zunahme bei den belegten Wohnungen.",
		"erlaeuterungen": "Ab 1994 mit Bezirk Laufen. Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungen und Wohnbevölkerung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09077",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-4-4",
		"stufe1": "Wohnungsleerstand im Kanton Basel-Landschaft",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:24",
		"id": 9077
	},
	{
		"template": "template001_print",
		"data-id": 7585,
		"chart-id": 9078,
		"filter": "",
		"parentId": "7585",
		"children": [],
		"title": "Leerwohnungsquote nach Kanton",
		"subtitle": "",
		"lesehilfe": "Die schweizerische Leerwohnungsquote ist gegenüber dem Vorjahr gesunken. Die niedrigste Quote weist der Kanton Zug (0,34%), die höchste der Kanton Solothurn (3,15%) auf.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungsquote nach Kanton",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09078",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-5-1",
		"stufe1": "Wohnungsleerstand im nationalen Kontext",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:25",
		"id": 9078
	},
	{
		"template": "line001_print",
		"data-id": 7586,
		"chart-id": 9079,
		"filter": "",
		"parentId": "7586",
		"children": [],
		"title": "Leerwohnungsquote in Grossstädten und in der Schweiz",
		"subtitle": "",
		"lesehilfe": "Mit dem vor gut zehn Jahren einsetzenden Anstieg der Wohnbevölkerung ging auch die Basler Leerwohnungsquote bis 2017 auf die Werte im Bereich der anderen grösseren Schweizer Städte zurück. Seit 2018 hat die Stadt Basel die anderen Grossstädte bezüglich der Leerwohnungsziffer überholt.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde",
			"Schweiz"
		],
		"description": "Leerwohnungsquote in Grossstädten und in der Schweiz",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09079",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-5-2",
		"stufe1": "Wohnungsleerstand im nationalen Kontext",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:25",
		"id": 9079
	},
	{
		"template": "line001_print",
		"data-id": 7587,
		"chart-id": 9080,
		"filter": "",
		"parentId": "7587",
		"children": [],
		"title": "Geschäftsleerstandsfläche",
		"subtitle": "Basel-Stadt und Basel-Landschaft",
		"lesehilfe": "Das Angebot an Geschäftsflächen in den beiden Basel zusammen ist um 15% auf  375 000 m² gewachsen. Gut 49% des gesamten Angebots entfallen auf den Stadt- und knapp 51% auf den Landkanton.",
		"erlaeuterungen": "Die Erhebung wird vom Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel durchgeführt. Stichtag ist der 1. Juni.",
		"quellenangabe": [
			"Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Geschäftsleerstandsfläche",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09080",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-6-1",
		"stufe1": "Geschäftsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:26",
		"id": 9080
	},
	{
		"template": "line001_print",
		"data-id": 7588,
		"chart-id": 9081,
		"filter": "",
		"parentId": "7588",
		"children": [],
		"title": "Geschäftsleerstandsfläche nach Nutzung",
		"subtitle": "in m², Basel-Stadt",
		"lesehilfe": "Das Angebot leerstehender Geschäftsflächen hat zwischen 2020 und 2021 von 120 500  m² auf 184 700 m² zugenommen (+ 53%). Dies ist hauptsächlich auf eine Zunahme im Bürobereich von 76 500  m² auf 122 400  m² zurückzuführen.",
		"erlaeuterungen": "Die Erhebung wird vom Schweizerischen Verband der Immobilienwirtschaft (SVIT) beider Basel durchgeführt. Stichtag ist der 1. Juni.",
		"quellenangabe": [
			"Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Geschäftsleerstandsfläche nach Nutzung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09081",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-6-2",
		"stufe1": "Geschäftsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:27",
		"id": 9081
	},
	{
		"template": "line001_print",
		"data-id": 7589,
		"chart-id": 9082,
		"filter": "",
		"parentId": "7589",
		"children": [],
		"title": "Geschäftsleerstandsfläche nach Nutzung",
		"subtitle": "Basel-Landschaft",
		"lesehilfe": "Im Landkanton nahm die Bürofläche zwischen 2020 und 2021 um 20 400 m² auf 87 800 m² zu. Die Büroflächen sind mit einem Anteil von 46% der grösste Bereich. Danach folgt der Gewerbebereich mit 24%.",
		"erlaeuterungen": "Die Erhebung wird vom Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel durchgeführt. Stichtag ist der 1. Juni.",
		"quellenangabe": [
			"Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Geschäftsleerstandsfläche nach Nutzung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09082",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-6-3",
		"stufe1": "Geschäftsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:27",
		"id": 9082
	},
	{
		"template": "pie001_print",
		"data-id": 7590,
		"chart-id": 9083,
		"filter": "",
		"parentId": "7590",
		"children": [],
		"title": "Geschäftsleerstandsfläche nach Nutzung",
		"subtitle": "Basel-Stadt, Anteile 2021",
		"lesehilfe": "Rund zwei Drittel des Geschäftsleerstandes entfallen auf den Bürobereich. Kleinere Anteile zwischen 13% und 9% weisen die Gewerbe-, Lager- und Ladenflächen auf.",
		"erlaeuterungen": "Die Erhebung wird vom Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel durchgeführt. Stichtag ist der 1. Juni.",
		"quellenangabe": [
			"Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Geschäftsleerstandsfläche nach Nutzung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09083",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-6-4",
		"stufe1": "Geschäftsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:28",
		"id": 9083
	},
	{
		"template": "pie001_print",
		"data-id": 9064,
		"chart-id": 9084,
		"filter": "",
		"parentId": "9064",
		"children": [],
		"title": "Geschäftsleerstandsfläche nach Nutzung",
		"subtitle": "Basel-Landschaft, Anteile 2021",
		"lesehilfe": "Der Bürobereich (46%) und der Gewerbebereich (24%) weisen den grössten Anteil am Leerstand aus. Danach folgen die Lagerflächen mit 19%.",
		"erlaeuterungen": "Die Erhebung wird vom Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel durchgeführt. Stichtag ist der 1. Juni.",
		"quellenangabe": [
			"Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Geschäftsleerstandsfläche nach Nutzung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09084",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-6-5",
		"stufe1": "Geschäftsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:28",
		"id": 9084
	},
	{
		"title": "Leerwohnungen nach Zimmerzahl",
		"subtitle": "Basel-Landschaft",
		"kuerzel": "I.09.2.09144",
		"kuerzelKunde": "LEB-2-3",
		"description": "Leerwohnungen nach Zimmerzahl",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kennzahlenset": "Leerstand (Print)",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-12-24T09:50:49.4949",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Landkanton machen Drei- und Vierzimmerwohnungen gut drei Viertel des Leerwohnungsbestandes aus. Die Leerwohnungsquote bleibt 2020 bei 1,1%.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "_000",
		"parentId": 9137,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 9137,
		"chart-id": 9144,
		"filter": "",
		"id": 9144
	},
	{
		"template": "template001_print",
		"data-id": 9336,
		"chart-id": 9336,
		"filter": "",
		"parentId": "9137",
		"children": [],
		"title": "Leerwohnungen nach Zimmerzahl sowie Leerstandsquote",
		"subtitle": "Basel-Landschaft",
		"lesehilfe": "Im Landkanton sinkt die Leerstandsquote 2021 auf 1,0%, 1 404 Wohnungen stehen leer. Davon sind rund drei Viertel Drei- oder Vierzimmerwohnungen.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungen nach Zimmerzahl sowie Leerstandsquote",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09336",
		"kennzahlenset": "Leerstand (Print)",
		"kuerzelKunde": "LEB-2-3",
		"stufe1": "Wohnungsleerstand in den beiden Basel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:19",
		"id": 9336
	}
];