var indikatorensetData = [
	{
		"template": "stock001",
		"data-id": 11788,
		"chart-id": 6033,
		"filter": "",
		"parentId": "6033",
		"children": [],
		"title": "Hitzetage",
		"subtitle": "Anzahl Tage, Meteorologische Station Basel-Binningen",
		"lesehilfe": "Im Jahr 2024 wurden 24 Hitzetage verzeichnet. Das Maximum innerhalb des abgebildeten Zeitraumes wurde mit 43 Hitzetagen im Jahr 2003 registriert.",
		"erlaeuterungen": "Anzahl Tage im Jahr, an denen die Lufttemperatur mindestens 30 °C erreicht hat. Die Temperaturmessungen erfolgen an der meteorologischen Station Basel-Binningen in 2 m über Grund (317 m ü. M.; 47°33' N/7°35' E).",
		"quellenangabe": [
			"Meteorologischer Verein der Region Basel"
		],
		"externalLinks": [
			"Weitere Informationen zum Indikator: <a href = 'http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-08-0801' target = '_blank'>Umweltbericht beider Basel</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Hitzetage",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Klima",
		"kuerzel": "I.02.12.11788",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "5.2",
		"stufe1": "Legislaturziel 5: Mit natürlichen Ressourcen nachhaltig umgehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-03-25T08:33:34",
		"id": 11788
	},
	{
		"template": "befragungen001",
		"data-id": 12519,
		"chart-id": 12519,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Kantonale Online-Dienstleistungen",
		"subtitle": "«Welche Dienstleistungen des Kantons nutzen Sie online bzw. kennen Sie?», nur Personen mit Internetzugang, Basel-Stadt, 2023",
		"lesehilfe": "Von den digitalen kantonalen Dienstleistungen ist die Möglichkeit, die Steuererklärung online einzureichen, am bekanntesten: Rund 60% kennen das Steuerportal «eSteuern.BS». 42% haben dieses bereits mindestens einmal genutzt. An zweiter Stelle der genutzten Online-Dienstleistungen steht das eKonto, gefolgt vom Online-Schalter der Motorfahrzeugkontrolle (MFK), den Kartendiensten MapBS und Geoportal BS sowie der Dräggwägg-App.",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: Ab 2019 in schriftlicher Form (Papier- bzw. Onlinefragebogen), zuvor telefonisch; ab 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppen (2011, 2015 und 2019 wurden nachgewichtet, die Werte weichen daher von früher publizierten ab).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Kantonale Online-Dienstleistungen",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.12519",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "6.4",
		"stufe1": "Legislaturziel 6: Modernen, kundenfreundlichen Service public anbieten",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-10-15T09:04:26",
		"id": 12519
	},
	{
		"template": "template001",
		"data-id": 2956,
		"chart-id": 2956,
		"filter": "",
		"parentId": null,
		"children": [
			6276
		],
		"title": "Zufriedenheit mit der Gesundheitsversorgung, nach Altersgruppe",
		"subtitle": "«Wie zufrieden sind Sie mit der Gesundheitsversorgung?», Anteil sehr oder eher Zufriedene, Basel-Stadt",
		"lesehilfe": "92,0% der Bevölkerung sind 2023 sehr oder eher zufrieden mit der Gesundheitsversorgung. Bei Personen ab 70 Jahren liegt die Zufriedenheit mit 96,4% am höchsten.",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: seit 2019 in schriftlicher Form (Papier- bzw. Onlinefragebogen), zuvor telefonisch; seit 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppe (2011, 2015 und 2019 wurden nachgewichtet, die Werte weichen daher von früher publizierten ab). «Zufriedenheit» fasst die Antwortkategorien «Sehr zufrieden» und «Eher zufrieden» zusammen. Um die Daten über die Jahre vergleichen zu können, bleiben befragte Personen, welche die Frage mit «Weiss nicht» oder gar nicht beantwortet haben, unberücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit der Gesundheitsversorgung, nach Altersgruppe",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.2956",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.10",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-31T10:44:13",
		"id": 2956
	},
	{
		"template": "line001",
		"data-id": 3104,
		"chart-id": 3104,
		"filter": "",
		"parentId": null,
		"children": [
			6278
		],
		"title": "Globale und kontinentale Erreichbarkeit",
		"subtitle": "Stadt Basel im Vergleich mit ausgewählten Schweizer Städten",
		"lesehilfe": "Aufgrund der starken Reiseeinschränkungen als Massnahme zur Bekämpfung der COVID-19-Pandemie sank die Erreichbarkeit der Städte im Jahr 2020 markant. Am stärksten hat sich die kontinentale Erreichbarkeit verringert. Seither haben sich die Index-Werte wieder verbessert, sie liegen allerdings auch 2022 immer noch tiefer als vor 2020. Zürich weist trotz Verlusten weiterhin die beste Erreichbarkeit der Schweizer Regionen auf.",
		"erlaeuterungen": "Bei der Kennzahl handelt es sich um einen indexierten Wert: 100 = Mittel aller einbezogenen Ursprungsregionen im Jahr 2002. Globale Erreichbarkeit: Erreichbarkeit von Regionen ausserhalb Europas; kontinentale Erreichbarkeit: Erreichbarkeit aller Regionen Europas. Die Erreichbarkeitsmodelle von BAK Economics basieren auf dem Ansatz aktivitätsbasierter Gravitationsindikatoren, welchem Strassenerreichbarkeit, Bahnfahr- und Flugpläne zugrunde liegen. Sie folgen dem Konzept der Erreichbarkeit «aus der Region» (outbound accessibility), d. h. es werden Reisezeit und Frequenz herangezogen, die benötigt werden, um aus der Region andere Regionen zu erreichen. Die Reisedestinationen werden über die Reisezeit und das Bruttoinlandprodukt der Region gewichtet. Um die Entwicklung nach den starken Reiseeinschränkungen im Jahr 2020 zeitnah zu beobachten, wurde die Erreichbarkeit engegen dem zweijährlichen Rhythmus ausnahmsweise auch für das Jahr 2021 berechnet.",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [
			"Weiterführende Informationen: <a href = 'https://www.bak-economics.com/en/solutions/regional-analysis/region-international/location-factors/erreichbarkeit/' target = '_blank'>BAK Economics</a> und",
			"<a href = 'http://www.mobilitaet.bs.ch/gesamtverkehr/verkehrskennzahlen/erreichbarkeit.html' target = '_blank'>Amt für Mobilität</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Globale und kontinentale Erreichbarkeit",
		"thema": "11 Verkehr",
		"unterthema": "Mobilitätsverhalten",
		"kuerzel": "I.11.6.3104",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.12",
		"stufe1": "Legislaturziel 1: Standortattraktivität langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-29T08:32:36",
		"id": 3104
	},
	{
		"template": "befragungen001",
		"data-id": 5033,
		"chart-id": 5033,
		"filter": "",
		"parentId": null,
		"children": [
			6279
		],
		"title": "Transnationale Patentanmeldungen",
		"subtitle": "pro 1000 Beschäftigte und Jahr, nach Wirtschaftsbranchen und ausgewählten Kantonen",
		"lesehilfe": "In Basel-Stadt wurden von 2015 bis 2019 pro Jahr im Schnitt 0,99 transnationale Patente pro 1000 Beschäftigte angemeldet, rund die Hälfte davon im Bereich der Pharmazeutischen Industrie (0,56 pro 1000 Beschäftigte). Im Kanton Zürich und in der gesamten Schweiz werden vor allem in der Branche Elektronik, Optik und Maschinenbau Patente angemeldet.",
		"erlaeuterungen": "Die transnationalen Patentanmeldungen spiegeln die Anzahl der von den Unternehmen als betriebswirtschaftlich verwertbar eingeschätzten Erfindungen im Technologiebereich wider. Sie werden von Forschenden am European Patent Office (EPO) oder über das Patent Cooperation Treaty (PCT)-Verfahren (gleichzeitige Patentanmeldung bei einer Vielzahl von nationalen Patentämtern) angemeldet. Die über das PCT-Verfahren zum EPO gelangenden Patentanmeldungen werden nur einmal gezählt. Die Regionalisierung der Patentdaten erfolgt nach der Wohnadresse der beteiligten Forscher und wird von der OECD durchgeführt (REGPAT database). Falls ein Patent von mehreren Forschern mit Wohnort in unterschiedlichen Regionen angemeldet wird, wird das Patent gemäss den Forscheranteilen aufgeteilt. Die Patentanmeldungen sind pro 1000 Beschäftigte im gesamten Kanton im Mittel über mehrere Jahre abgebildet.",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Transnationale Patentanmeldungen",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Volkseinkommen",
		"kuerzel": "I.04.1.05033",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.5",
		"stufe1": "Legislaturziel 1: Standortattraktivität langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-06-07T08:10:16",
		"id": 5033
	},
	{
		"template": "template001",
		"data-id": 5041,
		"chart-id": 5041,
		"filter": "",
		"parentId": null,
		"children": [
			6369
		],
		"title": "Anzahl Neugründungen in Basel-Stadt",
		"subtitle": "in ausgewählten Branchen",
		"lesehilfe": "Im Jahr 2023 wurden in Basel-Stadt 1 389 neue Unternehmen gegründet, 18 weniger als im Jahr 2022. Rund ein Viertel (378 im Jahr 2023) der Neugründungen ist im Bereich der freiberuflichen, wissenschaftlichen und technischen Dienstleistungen angesiedelt. An zweiter und dritter Stelle kommen die Branchen Gesundheits- und Sozialwesen (200) sowie Kunst, Unterhaltung, Erholung (192).",
		"erlaeuterungen": "Unter Neugründungen werden Unternehmen mit marktwirtschaftlicher Tätigkeit verstanden, die tatsächlich neu entstanden sind, also nicht aus Fusionen, Übernahmen, Spaltungen oder Restrukturierungen hervorgegangen sind. Die Statistik der Unternehmensdemografie (UDEMO) basiert auf der Statistik der Unternehmensstruktur (STATENT).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensdemografie (UDEMO)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Neugründungen in Basel-Stadt",
		"thema": "06 Industrie, Dienstleistungen",
		"unterthema": "Neugründungen",
		"kuerzel": "I.06.2.5041",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.4",
		"stufe1": "Legislaturziel 1: Standortattraktivität langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-12-04T08:36:26",
		"id": 5041
	},
	{
		"template": "befragungen001",
		"data-id": 5192,
		"chart-id": 5192,
		"filter": "",
		"parentId": null,
		"children": [
			9418
		],
		"title": "Besuchte Weiterbildungen und Kurse im letzten Jahr",
		"subtitle": "«Haben Sie in den letzten 12 Monaten eine Weiterbildung oder einen Kurs besucht?», Basel-Stadt",
		"lesehilfe": "16,8% der Bevölkerung gaben 2023 an, innerhalb der letzten zwölf Monate einen Weiterbildungskurs besucht zu haben, 14,5% haben mehrere Kurse besucht. 56,6% gaben an, keinen Kurs besucht zu haben.",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: Seit 2019 in schriftlicher Form (Papier- bzw. Onlinefragebogen), zuvor telefonisch; seit 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppe (2011, 2015 und 2019 wurden nachgewichtet, die Werte weichen daher von früher publizierten ab).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Besuchte Weiterbildungen und Kurse im letzten Jahr",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.5192",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.7",
		"stufe1": "Legislaturziel 1: Standortattraktivität langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-09-30T12:46:01",
		"id": 5192
	},
	{
		"template": "template001",
		"data-id": 5193,
		"chart-id": 5193,
		"filter": "",
		"parentId": null,
		"children": [
			9461
		],
		"title": "Staatsausgaben für Kultur",
		"subtitle": "pro Kopf in Franken, Basel-Stadt",
		"lesehilfe": "Die Ausgaben des Kantons betragen 2022 im Bereich Kulturerbe 499 und im Bereich Übrige Kultur 550 Franken pro Kopf.",
		"erlaeuterungen": "Ausgaben nach Funktion berechnet von der Eidgenössischen Finanzverwaltung; pro Kopf der mittleren Wohnbevölkerung Basel-Stadt.",
		"quellenangabe": [
			"Eidgenössische Finanzverwaltung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Staatsausgaben für Kultur",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Staatsrechnung",
		"kuerzel": "I.18.1.5193",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.13",
		"stufe1": "Legislaturziel 1: Standortattraktivität langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_013",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-10-11T12:59:40",
		"id": 5193
	},
	{
		"template": "template001",
		"data-id": 6126,
		"chart-id": 6126,
		"filter": "",
		"parentId": null,
		"children": [
			6283,
			9598,
			9786,
			12557
		],
		"title": "Kantonaler Wettbewerbsindikator (KWI)",
		"subtitle": "Basel-Stadt im kantonalen Vergleich, 2025",
		"lesehilfe": "Im Jahr 2025 liegt Basel-Stadt beim Kantonalen Wettbewerbsindikator (KWI) der UBS mit einem Wert von 94,2 auf Rang 2 aller Schweizer Kantone. Der Nachbarkanton Basel-Landschaft belegt Rang 7.",
		"erlaeuterungen": "Der Kantonale Wettbewerbsindikator (KWI) der UBS gibt Aufschluss über das relative längerfristige Wachstumspotenzial eines Kantons. Aktuell erscheint er alle zwei Jahre, zuletzt 2025. Die Wettbewerbsfähigkeit eines Kantons beschreibt sein Potenzial für eine nachhaltige Steigerung seiner Wirtschaftsleistung. Kantone mit einer hohen relativen Wettbewerbsfähigkeit dürften längerfristig stärker wachsen als die Schweizer Gesamtwirtschaft. Hingegen ist in Kantonen mit einer tiefen relativen Wettbewerbsfähigkeit mit einem unterdurchschnittlichen Wachstum zu rechnen. Der KWI basiert auf der vergleichenden Analyse von acht thematischen Säulen mit insgesamt über 50 Variablen. Die Variablen werden gewichtet, aggregiert und normiert, sodass jeder Kanton für jede Säule eine Punktzahl zwischen 0 und 100 erhält. Zur Ermittlung des KWI wird für jeden Kanton der Durchschnitt aus den Punktzahlen der acht Säulen errechnet und so normiert, dass der höchste kantonale Durchschnittswert 100 beträgt.",
		"quellenangabe": [
			"UBS Switzerland AG"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Schweiz"
		],
		"description": "Kantonaler Wettbewerbsindikator (KWI)",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.06126",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.1",
		"stufe1": "Legislaturziel 1: Standortattraktivität langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-12T11:18:13",
		"id": 6126
	},
	{
		"template": "template001",
		"data-id": 6127,
		"chart-id": 6127,
		"filter": "",
		"parentId": null,
		"children": [
			6050,
			6284,
			8939
		],
		"title": "Kantonales Wettbewerbsprofil",
		"subtitle": "Basel-Stadt im Vergleich zum Mediankanton, 2023",
		"lesehilfe": "Basel-Stadt liegt im Jahr 2023 in den Bereichen Wirtschaftsstruktur, Humankapital, Erreichbarkeit und Einzugsgebiet an der Spitze aller Kantone. Die Werte des hier dargestellten Mediankantons entsprechen dem Medianwert aller Kantone der jeweiligen Säule.",
		"erlaeuterungen": "Der Kantonale Wettbewerbsindikator (KWI) gibt Aufschluss über das relative längerfristige Wachstumspotenzial eines Kantons. Die Wettbewerbsfähigkeit eines Kantons beschreibt sein Potenzial für eine nachhaltige Steigerung seiner Wirtschaftsleistung. Kantone mit einer hohen relativen Wettbewerbsfähigkeit dürften längerfristig stärker wachsen als die Schweizer Gesamtwirtschaft. Hingegen ist in Kantonen mit einer tiefen relativen Wettbewerbsfähigkeit mit einem unterdurchschnittlichen Wachstum zu rechnen. Der KWI basiert auf der vergleichenden Analyse von acht Säulen mit insgesamt über 50 Variablen. Die Variablen werden gewichtet, aggregiert und normiert, sodass jeder Kanton für jede Säule eine Punktzahl zwischen 0 und 100 erhält. Zur Ermittlung des KWI wird für jeden Kanton der Durchschnitt aus den Punktzahlen der acht Säulen errechnet und so normiert, dass der höchste kantonale Durchschnittswert 100 beträgt. Der Mediankanton ist ein Referenzkanton, der aus den Medianwerten der jeweiligen Wettbewerbssäulen zusammengesetzt ist. Der Medianwert der jeweiligen Säule unterteilt die Rangliste der Kantone in eine obere und eine untere Hälfte mit je 13 Kantonen. Für die Interpretation der kantonalen Wettbewerbsprofile gilt: Je höher der Wert für einen Kanton in einer Säule ist, desto besser ist seine relative Bewertung.",
		"quellenangabe": [
			"UBS Switzerland AG"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Kantonales Wettbewerbsprofil",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.06127",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.2",
		"stufe1": "Legislaturziel 1: Standortattraktivität langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-10-11T12:59:41",
		"id": 6127
	},
	{
		"template": "line001",
		"data-id": 6147,
		"chart-id": 6037,
		"filter": "",
		"parentId": "6037",
		"children": [],
		"title": "Lohnunterschied zwischen Frauen und Männern",
		"subtitle": "im privaten Sektor in der Nordwestschweiz",
		"lesehilfe": "Im Jahr 2022 erreicht der Medianlohn der Frauen in der Privatwirtschaft in der Nordwestschweiz 6 251 Franken, während der Medianlohn der Männer bei 7 100 Franken liegt. Der Lohnunterschied hat sich gegenüber 2020 kaum verändert und liegt 2022 bei 12,0%. Im Jahr 2002 lag er bei 20,7%.",
		"erlaeuterungen": "Grundlage ist der Median des monatlichen Bruttolohns, standardisiert (Vollzeitäquivalent basierend auf 4,33 Wochen à 40 Arbeitsstunden), im privaten Sektor (ohne Landwirtschaft), im Monat Oktober, einschliesslich u. a. 1/12 des 13. Monatslohns und 1/12 der jährlichen Boni.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Lohnstrukturerhebung (LSE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Lohnunterschied zwischen Frauen und Männern",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Löhne",
		"kuerzel": "",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.11",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-21T06:57:38",
		"id": 6147
	},
	{
		"template": "line001",
		"data-id": 6150,
		"chart-id": 6150,
		"filter": "",
		"parentId": null,
		"children": [
			6054,
			6303,
			8943
		],
		"title": "Mittelwert und Median des Reineinkommens",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Der Mittelwert des Reineinkommens des obersten Quintils ist seit 1991 am deutlichsten gestiegen. Die übrigen Werte verlaufen relativ konstant.",
		"erlaeuterungen": "Mittelwert und Median werden pro Veranlagung berechnet (Ehepaare werden bspw. gemeinsam veranlagt). Der Mittelwert des obersten respektive untersten Quintils ist der Durchschnitt des Reineinkommens derjenigen 20% der Veranlagungen mit den jeweils höchsten respektive niedrigsten Reineinkommen. Über den Betrachtungszeitraum gab es zahlreiche Veränderungen in der Steuergesetzgebung, die einen Einfluss auf die Berechnung des Reineinkommens haben können, etwa durch erhöhte Abzugsmöglichkeiten (z. B. für Berufskosten).",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittelwert und Median des Reineinkommens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.6150",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.1",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-07-22T10:43:41",
		"id": 6150
	},
	{
		"template": "line001",
		"data-id": 6154,
		"chart-id": 6154,
		"filter": "",
		"parentId": null,
		"children": [
			6007,
			6258,
			6306,
			8454,
			8957
		],
		"title": "Verkehrsleistungsindex",
		"subtitle": "indexiert (Basis 2010 = 100), Basel-Stadt",
		"lesehilfe": "Das Verkehrsaufkommen in Basel-Stadt hat 2023 im Vergleich zum Vorjahr bei allen Verkehrsmitteln zugenommen. Mit Ausnahme des Velovekehrs liegt das Verkehrsaufkommen aber immer noch unter dem Niveau von vor der Pandemie.",
		"erlaeuterungen": "Der Verkehrsleistungsindex erfasst die Veränderung der Fahrleistung der verschiedenen Verkehrsmittel im ganzen Kantonsgebiet. Es wird die Veränderung gegenüber dem Referenzjahr 2010 dargestellt (indexiert, 2010 = 100). Bei den Fussgängerdaten ist das Referenzjahr 2013, da diese erst seit dann erhoben werden. Weiterführende Informationen: <a href='https://www.mobilitaet.bs.ch/gesamtverkehr/verkehrskennzahlen/verkehrsindex.html' target=\"_blank\">Amt für Mobilität Basel-Stadt</a>.",
		"quellenangabe": [
			"Amt für Mobilität Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Verkehrsleistungsindex",
		"thema": "11 Verkehr",
		"unterthema": "Mobilitätsverhalten",
		"kuerzel": "I.11.6.06154",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "5.5",
		"stufe1": "Legislaturziel 5: Mit natürlichen Ressourcen nachhaltig umgehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-07-24T08:47:17",
		"id": 6154
	},
	{
		"template": "template001",
		"data-id": 6160,
		"chart-id": 9008,
		"filter": "",
		"parentId": "9008",
		"children": [
			4953
		],
		"title": "Endenergieverbrauch nach Verbrauchergruppe",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Der Endenergieverbrauch hat zwischen 2010 und 2022 um 30,6% abgenommen. Auf die Kategorie Wohnen (Anteil 2022: 38,7%) entfällt 2022 ein kleinerer Energieeinsatz als 2010; dies obwohl es eine Zunahme der Energiebezugsfläche in diesem Zeitraum gab. Der Verbrauch in der Kategorie Nichtwohnen ist zurückgegangen (Anteil 2022: 44,5%), von 2 284 GWh auf 1 633 GWh. Dies ist eine Reduktion um 28,5%, unter anderem wegen einer starken Abnahme der Energiebezugsfläche. In der Kategorie Verkehr (Anteil 2022: 16,8%) ist 2022 gegenüber 2018 ein starker Rückgang ersichtlich. Dieser ist vor allem aufgrund des methodischen Bruchs infolge des aktualisierten Gesamtverkehrsmodells im Jahr 2020 zustandegekommen.",
		"erlaeuterungen": "Endenergie ist der nach Energiewandlungs- und Übertragungsverlusten übriggebliebene Teil der Bruttoenergie, welcher von den Energienutzern verbraucht wird. Bei den Verbrauchergruppen wird zwischen «Verkehr», «Wohnen» und «Nichtwohnen» unterschieden. Zum Wohnen gehören private Haushalte und zum Nichtwohnen Gewerbe, Handel, Dienstleistungen und Industrie. Verteilverluste, statistische Differenzen sowie Exporte bleiben in dieser Betrachtung unberücksichtigt. Daher ist die Summe des Verbrauchs der drei abgebildeten Verbrauchergruppen kleiner als der totale Endverbrauch.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [
			"<a href = 'https://www.statistik.bs.ch/analysen-berichte/raum-umwelt/energiestatistik.html' target = '_blank'>Energiestatistik Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Endenergieverbrauch nach Verbrauchergruppe",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "5.7",
		"stufe1": "Legislaturziel 5: Mit natürlichen Ressourcen nachhaltig umgehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-09-30T12:46:06",
		"id": 6160
	},
	{
		"template": "line001",
		"data-id": 6161,
		"chart-id": 6161,
		"filter": "",
		"parentId": null,
		"children": [
			5795,
			6313,
			8916
		],
		"title": "Anteil erneuerbarer Energie am Bruttoenergieverbrauch",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Der Anteil erneuerbarer Energie am Bruttoenergieverbrauch ist von 34,6% im Jahr 2010 auf 43,9% im Jahr 2022 gestiegen.",
		"erlaeuterungen": "Folgende Energieträger werden als erneuerbar berücksichtigt: Wasserkraft, Holz, Umweltwärme, thermische und fotovoltaische Sonnenenergie, Klärschlamm, Biogas, erneuerbare Elektrizität (in Basel-Stadt stammen 100% des importierten Strommixes aus erneuerbaren Quellen) und Kehricht (zu 50% als erneuerbar taxiert).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil erneuerbarer Energie am Bruttoenergieverbrauch",
		"thema": "08 Energie",
		"unterthema": "Erneuerbare",
		"kuerzel": "I.08.3.06161",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "5.8",
		"stufe1": "Legislaturziel 5: Mit natürlichen Ressourcen nachhaltig umgehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-06-12T07:33:28",
		"id": 6161
	},
	{
		"template": "template001",
		"data-id": 6163,
		"chart-id": 6163,
		"filter": "",
		"parentId": null,
		"children": [
			5796,
			6314,
			8917,
			10052
		],
		"title": "Siedlungsabfälle, Wertstoffsammlungen, Recyclingquote",
		"subtitle": "in kg pro Kopf resp. Prozent, Basel-Stadt",
		"lesehilfe": "Die Siedlungsabfälle reduzierten sich zwischen 2000 und 2023 von 194 auf 149 kg pro Kopf. Die Recyclingquote liegt aktuell bei 39,5%.",
		"erlaeuterungen": "Grundlage ist die kantonale Abfallstatistik. Bei der Wertstoffsammlung sind berücksichtigt: Altpapier und Karton, Altglas, Altmetall/Alu/Weissblech, Grüngut, Textilien sowie Sonderabfälle. Die Recyclingquote entspricht dem Anteil der Wertstoffsammlungen an der Gesamtmenge der Siedlungsabfälle.",
		"quellenangabe": [
			"Amt für Umwelt und Energie Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Siedlungsabfälle, Wertstoffsammlungen, Recyclingquote",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Entsorgung",
		"kuerzel": "I.02.6.6163",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "5.4",
		"stufe1": "Legislaturziel 5: Mit natürlichen Ressourcen nachhaltig umgehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-10-11T12:59:44",
		"id": 6163
	},
	{
		"template": "template001",
		"data-id": 6165,
		"chart-id": 6165,
		"filter": "",
		"parentId": null,
		"children": [
			6031,
			6316,
			8923,
			11901
		],
		"title": "Treibhausgas-Emissionen",
		"subtitle": "in Tonnen CO<sub>2</sub>-Äquivalente pro Kopf, Basel-Stadt",
		"lesehilfe": "Die direkten Treibhausgas-Emissionen auf dem Kantonsgebiet lagen 2022 bei 3,1 Tonnen CO<sub>2</sub>eq (CO<sub>2</sub>-Äquivalente) pro Kopf. Das Reduktionsziel (Netto-Null bis 2037) und der Zielpfad sind in der <a href='https://www.pd.bs.ch/ueber-das-departement/Fachstelle-Klima/Klimapolitik/Klimaschutzstrategie-Kanton-Basel-Stadt--Netto-Null-bis-2037.html' target='_blank'>Klimaschutzstrategie Basel-Stadt</a> festgelegt.",
		"erlaeuterungen": "Direkte Emissionen (sog. Scope 1) sind CO<sub>2</sub>-Emissionen auf dem Kantonsgebiet (Territorialprinzip), die durch das Verbrennen von fossilen Energieträgern wie Heizöl, Erdgas, Benzin und Diesel sowie bei der thermischen Verwertung von Abfällen (Kehricht und Industrieabfälle) entstehen. Weitere direkte Treibhausgasemissionen (in t CO<sub>2</sub>eq) umfassen insbesondere F-Gas-Emissionen in der Industrie, Methanemissionen aus dem Erdgasverteilnetz und Lachgasemissionen aus der Abwasserreinigung.<br>Insgesamt sinken die Treibhausgasemissionen im Netto-Null-Absenkpfad um 87% im Vergleich zu 2020 und umfassen im Jahr 2037 noch 88 000 Tonnen CO<sub>2</sub>eq. Diese restlichen, schwer vermeidbaren Emissionen umfassen Emissionen aus der Mobilität, der Entsorgung und nicht-energiebedingte Emissionen. Für den Netto-Null Absenkpfad wird davon ausgegangen, dass 2037 eine Carbon Capture and Storage (CCS) Anlage zur Abscheidung von CO<sub>2</sub> an der Kehrichtverbrennungsanlage in Betrieb gehen wird, sofern dies technisch und wirtschaftlich machbar ist.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik",
			"Klimaschutzstrategie Kanton Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.pd.bs.ch/ueber-das-departement/Fachstelle-Klima/Klimapolitik/Klimaschutzstrategie-Kanton-Basel-Stadt--Netto-Null-bis-2037.htm' target = '_blank'>Klimaschutzstrategie Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Treibhausgas-Emissionen",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Klima",
		"kuerzel": "I.02.12.06165",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "5.1",
		"stufe1": "Legislaturziel 5: Mit natürlichen Ressourcen nachhaltig umgehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-03-25T08:33:33",
		"id": 6165
	},
	{
		"template": "befragungen001",
		"data-id": 6186,
		"chart-id": 6186,
		"filter": "",
		"parentId": "4859",
		"children": [],
		"title": "Beurteilung der kantonalen Verwaltung",
		"subtitle": "«Wie ist der letzte Kontakt mit der kantonalen Verwaltung verlaufen?», Basel-Stadt",
		"lesehilfe": "19,9% der Bevölkerung empfand den letzten Kontakt mit der kantonalen Verwaltung als sehr positiv und 38,1% als eher positiv. 10,5% der Befragten empfanden den Kontakt als eher oder sehr negativ.",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: Seit 2019 in schriftlicher Form (Papier- bzw. Onlinefragebogen), zuvor telefonisch; seit 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppe (2011, 2015 und 2019 wurden nachgewichtet, die Werte weichen daher von früher publizierten ab).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beurteilung der kantonalen Verwaltung",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "6.3",
		"stufe1": "Legislaturziel 6: Modernen, kundenfreundlichen Service public anbieten",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-09-24T03:31:46",
		"id": 6186
	},
	{
		"template": "line001",
		"data-id": 6206,
		"chart-id": 6206,
		"filter": "",
		"parentId": null,
		"children": [
			6336
		],
		"title": "Schulabgängerinnen und -abgänger ohne Anschlusslösung",
		"subtitle": "nach Schultyp, Basel-Stadt",
		"lesehilfe": "Der Anteil der Schulabgängerinnen und -abgänger ohne Anschlusslösung lag 2024 bei total 0,7%. Das ist der niedrigste Wert im Beobachtungszeitraum. Bei der Sekundarschule (und davor bei der Weiterbildungsschule) ist der Anteil konstant tief. Bei den übrigen Schultypen führen die geringe Zahl an Beobachtungen und die damit verbundenen grossen jährlichen Schwankungen zu unruhigen Kurvenverläufen.",
		"erlaeuterungen": "Datengrundlage bildet die jährliche Befragung der Schulabgängerinnen und -abgänger durch die Bildungsstatistikstelle des Bereichs Mittelschulen und Berufsbildung im Erziehungsdepartement des Kantons Basel-Stadt. Allgemeine Gewerbeschule: nur Link zum Beruf und Vorkurse; Berufsfachschule: nur Vorkurse und Vorlehren; ohne Gymnasien. Seit 2018 ersetzen die Werte der Sekundarschule diejenigen der Weiterbildungsschule.",
		"quellenangabe": [
			"Erziehungsdepartement Basel-Stadt, Berufs- und Schulwahlerhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Schulabgängerinnen und -abgänger ohne Anschlusslösung",
		"thema": "15 Bildung",
		"unterthema": "Bildungsabschlüsse",
		"kuerzel": "I.15.7.6206",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.6",
		"stufe1": "Legislaturziel 1: Standortattraktivität langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-09-30T12:46:00",
		"id": 6206
	},
	{
		"template": "template001",
		"data-id": 6996,
		"chart-id": 6996,
		"filter": "",
		"parentId": null,
		"children": [
			9419
		],
		"title": "Stationär behandelte Patienten",
		"subtitle": "in baselstädtischen Spitälern, nach Wohnkanton",
		"lesehilfe": "Im Jahr 2023 wurden insgesamt 68 957 Patienten in baselstädtischen Spitälern stationär behandelt. Davon wohnten u. a. 29 848 Personen im Kanton Basel-Stadt und 22 464 in Basel-Landschaft.",
		"erlaeuterungen": "Es werden alle stationär behandelten Patienten berücksichtigt, welche im Erhebungsjahr mindestens einmal aus einem baselstädtischen Spital ausgetreten sind (mehrfach hospitalisierte Personen werden nur einmal gezählt).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gesundheitsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Stationär behandelte Patienten",
		"thema": "14 Gesundheit",
		"unterthema": "Spitäler",
		"kuerzel": "I.14.1.06996",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "3.2",
		"stufe1": "Legislaturziel 3: Partnerschaftlich zusammenarbeiten",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-22T10:03:38",
		"id": 6996
	},
	{
		"template": "line001",
		"data-id": 9361,
		"chart-id": 8355,
		"filter": "",
		"parentId": null,
		"children": [
			8355,
			8472,
			9420,
			9586
		],
		"title": "Entwicklung Wertschöpfung nach Branche, Basel-Stadt",
		"subtitle": "real, indexiert (2014 = 100)",
		"lesehilfe": "Die reale Wertschöpfung in der Pharmaindustrie in Basel-Stadt hat sich seit 2014 fast verdreifacht, diejenige in der Chemie hat sich verdoppelt. Das Gastgewerbe hat während der COVID-19-Pandemie erhebliche Wertschöpfungseinbussen erlitten. Inzwischen liegt die Wertschöpfung im Gastgewerbe fast wieder auf dem Niveau von 2019.",
		"erlaeuterungen": "Das Wachstum der realen Wertschöpfung wird in Preisen des Vorjahres gerechnet. Hier sind die Daten indexiert (Wert im Jahr 2014 = 100). Die dargestellten Branchen und Branchenaggregate basieren auf der allgemeinen Systematik der Wirtschaftszweige NOGA 2008.",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Wertschöpfung nach Branche, Basel-Stadt",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.09361",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.3",
		"stufe1": "Legislaturziel 1: Standortattraktivität langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-02T10:25:21",
		"id": 9361
	},
	{
		"template": "template001",
		"data-id": 9363,
		"chart-id": 6460,
		"filter": "",
		"parentId": "6460",
		"children": [],
		"title": "Arbeitslosenquote nach Branche",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die mittlere Arbeitslosenquote über alle Branchen ist von 3,0% im Jahr 2023 auf 3,7% im Jahr 2024 gestiegen. Am höchsten ist die Quote auch im Jahr 2024 in den Branchen Baugewerbe (11,5%), Gastgewerbe (9,7%) und in der Dienstleistungsgruppe Gebäudebetreuung, Sicherheit und sonstige wirtschaftliche Dienstleistungen (8,3%). Deutlich höher als im Vorjahr ist die Quote in den Branchen Information, Kommunikation (5,5%) sowie Personalvermittlung und -überlassung (4,5%).",
		"erlaeuterungen": "Als Arbeitslose gelten Personen, welche bei einem Regionalen Arbeitsvermittlungszentrum (RAV) gemeldet sind, keine Stelle haben und sofort vermittelbar sind. Die Arbeitslosenquote berechnet sich aus der Anzahl Arbeitslosen (SECO), geteilt durch die Erwerbstätigen, da die Anzahl Erwerbspersonen nach Branche nicht vorhanden ist (Quelle: BFS, Strukturerhebung, Pooling 2021-2023). Für das Total werden die Erwerbspersonen ebenfalls gemäss Strukturerhebung verwendet, weshalb die Arbeitslosenquote leicht von derjenigen des SECO abweichen kann.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)",
			"Staatssekretariat für Wirtschaft SECO, Arbeitslosenstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitslosenquote nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.9",
		"stufe1": "Legislaturziel 1: Standortattraktivität langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-12T11:18:18",
		"id": 9363
	},
	{
		"template": "line001",
		"data-id": 9365,
		"chart-id": 7588,
		"filter": "",
		"parentId": "7588",
		"children": [],
		"title": "Geschäftsleerstandsfläche nach Nutzung",
		"subtitle": "in m², Basel-Stadt",
		"lesehilfe": "Das Angebot leerstehender Geschäftsflächen hat zwischen 2024 und 2025 von 249 200  m² auf 200 400 m² abgenommen. Dies ist hauptsächlich auf eine Abnahme im Bürobereich von 175 100 m² auf 132 700 m² zurückzuführen.",
		"erlaeuterungen": "Die Erhebung wird vom Schweizerischen Verband der Immobilienwirtschaft (SVIT) beider Basel durchgeführt. Stichtag ist der 1. Juni.",
		"quellenangabe": [
			"Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Geschäftsleerstandsfläche nach Nutzung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.10",
		"stufe1": "Legislaturziel 1: Standortattraktivität langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-08-22T08:38:40",
		"id": 9365
	},
	{
		"template": "line001",
		"data-id": 9366,
		"chart-id": 9366,
		"filter": "",
		"parentId": null,
		"children": [
			9424
		],
		"title": "Angebotsquote bei Büroflächen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Angebotsquote bei Büroflächen hat seit 2018 stark zugenommen. 2024 waren 6,4% aller Büroflächen auf dem Markt verfügbar.",
		"erlaeuterungen": "Die Angebotsquote drückt das Angebot leerstehender und angebotener Büroflächen gemessen an der Gesamtfläche der Büroflächen aus.",
		"quellenangabe": [
			"JLL Büromarkt Schweiz"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Angebotsquote bei Büroflächen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.09366",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.11",
		"stufe1": "Legislaturziel 1: Standortattraktivität langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-11-13T08:45:49",
		"id": 9366
	},
	{
		"template": "template001",
		"data-id": 9368,
		"chart-id": 9368,
		"filter": "",
		"parentId": null,
		"children": [
			9425
		],
		"title": "Beschäftigte in der Branche Kultur",
		"subtitle": "nach Wirtschaftszweig, Basel-Stadt",
		"lesehilfe": "Im Kanton Basel-Stadt sind im Jahr 2023 4 276 Beschäftigte in der Branche Kultur tätig, 200 mehr als im Vorjahr. Ein Grossteil der Beschäftigten (40,4%) arbeitet im Bereich der darstellenden Kunst. Aufgrund von Arbeitsstätten, welche den Wirtschaftszweig gegenüber dem Vorjahr wechselten, haben sich die Anteile der Beschäftigten im Jahr 2023 verändert.",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und dafür einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Erfasst werden Personen, für welche im Referenzmonat Dezember AHV-Beiträge geleistet werden. Die Branche Kultur umfasst die Wirtschaftszweige «Kreative, künstlerische und unterhaltende Tätigkeiten» (NOGA 90) und «Bibliotheken, Archive, Museen, botanische und zoologische Gärten» (NOGA 91). Im Zuge der Veröffentlichung der STATENT 2019 wurden die Ergebnisse der Zeitreihe 2011-2018 auf der Grundlage neuer Informationen revidiert.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beschäftigte in der Branche Kultur",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09368",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.14",
		"stufe1": "Legislaturziel 1: Standortattraktivität langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_014",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-24T08:41:37",
		"id": 9368
	},
	{
		"template": "befragungen001",
		"data-id": 9369,
		"chart-id": 9369,
		"filter": "",
		"parentId": null,
		"children": [
			9426
		],
		"title": "Zufriedenheit mit dem Kulturangebot",
		"subtitle": "«Wie zufrieden sind Sie mit dem Kulturangebot?», Basel-Stadt",
		"lesehilfe": "2023 zeigen sich 37,4% der Befragten sehr und 41,5% eher zufrieden mit dem Kulturangebot. 9,1% sind damit unzufrieden.",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: Seit 2019 in schriftlicher Form (Papier- bzw. Onlinefragebogen), zuvor telefonisch; seit 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppe (2011, 2015 und 2019 wurden nachgewichtet, die Werte weichen daher von früher publizierten ab).<br>Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit dem Kulturangebot",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.09369",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.15",
		"stufe1": "Legislaturziel 1: Standortattraktivität langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_015",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-09-24T03:31:43",
		"id": 9369
	},
	{
		"template": "line001",
		"data-id": 9370,
		"chart-id": 8459,
		"filter": "",
		"parentId": "8459",
		"children": [],
		"title": "Mittelwert und Median des Reinvermögens",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Der Median des Reinvermögens ist im Zeitverlauf überwiegend gestiegen, seit 2007 von rund 11 400 auf 23 400 Franken im Jahr 2021. Die Werte des Medians liegen im Vergleich zum Mittelwert des Reinvermögens auf einem deutlich niedrigeren Niveau. Der Mittelwert des Reinvermögens pro Veranlagung hat in den letzten Jahren deutlich zugenommen.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige, ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittelwert und Median des Reinvermögens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.2",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-07-22T10:43:42",
		"id": 9370
	},
	{
		"template": "line001",
		"data-id": 9371,
		"chart-id": 6036,
		"filter": "",
		"parentId": "6036",
		"children": [
			9678
		],
		"title": "Gini-Koeffizienten von Reineinkommen und Reinvermögen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Der Gini-Koeffizient des Reineinkommens nimmt im Zeitverlauf insgesamt leicht zu, jener des Reinvermögens zeigt sich auf höherem Niveau etwas konstanter. Für das Reinvermögen liegt für das Jahr 2000 aufgrund von Gesetzesänderungen kein Wert vor.",
		"erlaeuterungen": "Der Gini-Koeffizient ist ein Mass für die Gleichmässigkeit einer Verteilung (hier des Reineinkommens und des Reinvermögens). Er kann Werte zwischen 0 (alle besitzen gleich viel) und 1 (einer besitzt alles) annehmen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Gini-Koeffizienten von Reineinkommen und Reinvermögen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.3",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-07-22T10:43:44",
		"id": 9371
	},
	{
		"template": "line001",
		"data-id": 9372,
		"chart-id": 9372,
		"filter": "",
		"parentId": null,
		"children": [
			9429,
			9681
		],
		"title": "Anzahl Fälle in der Sozialhilfe und Sozialhilfequote",
		"subtitle": "Kanton Basel-Stadt",
		"lesehilfe": "Im Verlaufe des Jahres 2024 wurden insgesamt 9 819 Personen finanziell durch die Sozialhilfe unterstützt. Die kantonale Sozialhilfequote liegt bei 4,7%. Sie sinkt seit dem Jahr 2017 kontinuierlich.",
		"erlaeuterungen": "Die Sozialhilfequote zeigt den prozentualen Anteil der Sozialhilfebeziehenden an der jeweiligen Bevölkerungsgruppe gemäss Stand am Ende des Jahres. Als Sozialhilfebeziehende werden alle Personen gezählt, die im Verlaufe eines Jahres mindestens eine Leistung der Sozialhilfe erhalten haben. Es werden alle Beziehenden mit Dossiertyp Sozialhilfefall sowie Anerkannte Flüchtlinge (FL), Vorläufig Aufgenommene (VA) und Vorläufig aufgenommene Flüchtlinge (VA FL) mit einer Aufenthaltsdauer von mehr als fünf bzw. sieben Jahren (FL 5+, VA 7+, VA FL 7+) berücksichtigt. <br>Die Berechnungsmethode wurde 2022 für die Jahre ab 2017 rückwirkend angepasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Fälle in der Sozialhilfe und Sozialhilfequote",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe",
		"kuerzel": "I.13.3.09372",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.5",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-03-17T11:05:06",
		"id": 9372
	},
	{
		"template": "template001",
		"data-id": 9373,
		"chart-id": 9373,
		"filter": "",
		"parentId": null,
		"children": [
			9430,
			10033
		],
		"title": "Anteil Personen, die in einem Haushalt mit Betreibungen, Zahlungsrückständen oder Kontoüberziehungen leben",
		"subtitle": "Nordwestschweiz",
		"lesehilfe": "2022 lebten von der Bevölkerung in der Nordwestschweiz: 9,7% in einem Haushalt mit mindestens einer Art von Zahlungsrückstand. 2020 lebten: 5,5% in einem Haushalt, in dem mindestens eine Person eine Betreibung oder einen Verlustschein hatte; 5,9% in einem Haushalt mit mindestens einer Kontoüberziehung oder einer unbezahlten Kreditkartenrechnung.",
		"erlaeuterungen": "Folgende Arten von Zahlungsrückständen, d. h. in den letzten zwölf Monaten aus finanziellen Gründen nicht fristgerecht beglichene Rechnungen, werden berücksichtigt: Miete oder Hypothekarzinsen;  laufende Rechnungen für Wasser, Strom, Gas, Heizung; Kreditrückzahlungen oder Kreditkartenrechnungen; Krankenkassenprämien; Steuern. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe und sind folglich mit einer gewissen Unsicherheit behaftet. Das Konfidenzintervall (schwarzer Fehlerbalken) gibt den Bereich an, welcher den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Die Ergebnisse zu Betreibungen und Verlustscheinen sowie Kontoüberziehungen und unbezahlten Kreditkartenrechnungen beziehen sich auf das Modul «Verschuldung», das Bestandteil der Erhebungen 2013, 2017 und 2020 war.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Erhebung über die Einkommen und Lebensbedingungen (SILC)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil Personen, die in einem Haushalt mit Betreibungen, Zahlungsrückständen oder Kontoüberziehungen leben",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09373",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.6",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-10-11T12:59:42",
		"id": 9373
	},
	{
		"template": "befragungen001",
		"data-id": 9374,
		"chart-id": 4862,
		"filter": "",
		"parentId": "4862",
		"children": [],
		"title": "Beurteilung der Bildungschancen",
		"subtitle": "«Wie stehen Sie zu folgender Aussage: Alle Kinder erhalten die gleichen Bildungschancen.», Basel-Stadt",
		"lesehilfe": "6,9% der Bevölkerung sind 2023 sehr und 19,1% eher mit der Aussage einverstanden, dass alle Kinder die gleichen Bildungschancen erhalten. 29,0% sind mit der Aussage eher bzw. überhaupt nicht einverstanden. Der Anteil Befragter, welcher diese Aussage nicht beurteilt hat, ist im Vergleich zu den Vorjahren gestiegen.",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: seit 2019 in schriftlicher Form (Papier- bzw. Onlinefragebogen), zuvor telefonisch; seit 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppe (2011, 2015 und 2019 wurden nachgewichtet, die Werte weichen daher von früher publizierten ab).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beurteilung der Bildungschancen",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.7",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-31T10:44:27",
		"id": 9374
	},
	{
		"template": "line001",
		"data-id": 9375,
		"chart-id": 9375,
		"filter": "",
		"parentId": null,
		"children": [
			9432,
			9732,
			12545
		],
		"title": "Entwicklung von Krankenkassenprämien und Reineinkommen",
		"subtitle": "indexiert (2010 = 100), Basel-Stadt",
		"lesehilfe": "Im Jahr 2021 lag der Index (Basis 2010) der mittleren Prämien bei 126,6 und jener für den Median des Reinkommens bei 105,9.<br>Für das Jahr 2025 wird bei den Prämien mit einen Anstieg auf 138,1 gerechnet.",
		"erlaeuterungen": "Mittlere Prämie: Gewichteter Durchschnitt der Krankenkassenprämien aller Versicherten pro Jahr. Die Gesamtprämiensumme einer Versichertengruppe wird durch die Gesamtzahl der Versicherten der jeweiligen Gruppe geteilt.<br>Die geschätzten Prämien beruhen auf Schätzungen der Versicherer zu den Veränderungen ihres Versichertenbestandes. Der effektive Prämienanstieg wird aber gemäss BAG tiefer erwartet, da bei stärkeren Prämienanstiegen beispielsweise mehr Versicherte höhere Franchisen wählen oder in ein alternatives Versicherungsmodell wechseln. <br>Median Reineinkommen: Medianwert des Reineinkommens der Steuerveranlagungen gemäss Steuerstatistik Basel-Stadt.",
		"quellenangabe": [
			"Bundesamt für Gesundheit (BAG)",
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung von Krankenkassenprämien und Reineinkommen",
		"thema": "14 Gesundheit",
		"unterthema": "Prävention, Praxen, Rettung",
		"kuerzel": "I.14.4.09375",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.4",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-12T02:42:56",
		"id": 9375
	},
	{
		"template": "befragungen001",
		"data-id": 9376,
		"chart-id": 8461,
		"filter": "",
		"parentId": null,
		"children": [
			9433
		],
		"title": "Zufriedenheit mit dem Angebot der Kinderbetreuung",
		"subtitle": "«Wie zufrieden sind Sie mit dem Kinderbetreuungsangebot?», Basel-Stadt",
		"lesehilfe": "Insgesamt 40,5% zeigen sich 2023 sehr oder eher zufrieden mit dem Kinderbetreuungsangebot. 11,9% sind damit unzufrieden. 47,6% haben diese Frage mit «Weiss nicht» oder gar nicht beantwortet.",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: Seit 2019 in schriftlicher Form (Papier- bzw. Onlinefragebogen), zuvor telefonisch; seit 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppe (2011, 2015 und 2019 wurden nachgewichtet, die Werte weichen daher von früher publizierten ab). Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit dem Angebot der Kinderbetreuung",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.09376",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.8",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-09-30T12:46:05",
		"id": 9376
	},
	{
		"template": "befragungen001",
		"data-id": 9377,
		"chart-id": 9377,
		"filter": "",
		"parentId": null,
		"children": [
			9434
		],
		"title": "Zufriedenheit mit der Seniorenfreundlichkeit im Kanton Basel-Stadt",
		"subtitle": "«Wie seniorenfreundlich empfinden Sie den Kanton Basel-Stadt?», Basel-Stadt",
		"lesehilfe": "13% der Personen ab 55 Jahren empfinden den Kanton Basel-Stadt als sehr seniorenfreundlich, 48% als eher seniorenfreundlich. Der Anteil derjenigen, welche den Kanton als eher weniger oder gar nicht seniorenfreundlich empfinden, liegt bei 16%.",
		"erlaeuterungen": "Seit 2011 wird alle vier Jahre die Bevölkerungsbefragung 55plus durchgeführt. Die Befragung richtet sich an Personen im Alter von mindestens 55 Jahren mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Da die Antwortoptionen bei der jüngsten Durchführung erweitert wurden (neu: «Weiss nicht»), lassen sich die Resultate über die Jahre nicht ohne Weiteres vergleichen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Befragung 55plus"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit der Seniorenfreundlichkeit im Kanton Basel-Stadt",
		"thema": "50 Befragungen",
		"unterthema": "Befragung 55 plus",
		"kuerzel": "I.50.4.09377",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "2.9",
		"stufe1": "Legislaturziel 2: Gesellschaftlichen Zusammenhalt stärken",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-21T06:57:39",
		"id": 9377
	},
	{
		"template": "template001",
		"data-id": 9379,
		"chart-id": 9379,
		"filter": "",
		"parentId": null,
		"children": [
			9436
		],
		"title": "Studierende Universität Basel und Fachhochschule Nordwestschweiz",
		"subtitle": "nach Wohnkanton bzw. Ausland",
		"lesehilfe": "Die Zahl der Studierenden liegt 2024 bei total 27 309. Damit wurde der Rekord vom Vorjahr noch einmal übertroffen. Den grössten Anteil macht mit 6 577 Personen (24,1%) die Kategorie «Übrige Schweiz» aus.",
		"erlaeuterungen": "Studierende der Universität Basel (Wohnort vor Studienbeginn) und der Fachhochschule Nordwestschweiz FHNW (stipendienrechtlicher Wohnsitz). Stichtag jeweils im Herbstsemester. Universität Basel aus methodischen Gründen ohne Advanced Studies.",
		"quellenangabe": [
			"Universität Basel",
			"Fachhochschule Nordwestschweiz (FHNW)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Studierende Universität Basel und Fachhochschule Nordwestschweiz",
		"thema": "15 Bildung",
		"unterthema": "Hochschulen",
		"kuerzel": "I.15.4.09379",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "3.1",
		"stufe1": "Legislaturziel 3: Partnerschaftlich zusammenarbeiten",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-05T08:43:16",
		"id": 9379
	},
	{
		"template": "template001",
		"data-id": 9380,
		"chart-id": 9380,
		"filter": "",
		"parentId": null,
		"children": [
			9437
		],
		"title": "Zupendelnde Fachkräfte in Bildung, Kultur, Gesundheits- und Sozialwesen",
		"subtitle": "aus dem schweizerischen Teil der Agglomeration nach Basel-Stadt",
		"lesehilfe": "Im Jahr 2022 pendelten rund 9 300 Personen aus dem schweizerischen Teil der Agglomeration Basel nach Basel-Stadt, um einer Erwerbstätigkeit im Bereich Gesundheits- und Sozialwesen nachzugehen. Rund 2 000 zupendelnde Erwerbstätige arbeiteten im Bereich Bildung und Kultur.",
		"erlaeuterungen": "Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe von jährlich rund 5 000 in Basel-Stadt wohnhaften Personen ab 15 Jahren und sind folglich mit einer gewissen Unsicherheit behaftet. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Agglomeration Basel: gemäss Typologie «Räume mit städtischem Charakter 2012» des BFS. Branchen: Bildung (NOGA 85), Gesundheits- und Sozialwesen (NOGA 86 bis 88), Kultur (NOGA 90 und 91).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [
			"<a href = 'https://www.bfs.admin.ch/bfs/de/home/statistiken/querschnittsthemen/raeumliche-analysen/raeumliche-gliederungen/analyseregionen.assetdetail.188849.html' target = '_blank'>Definition Agglomerationen gemäss BFS</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zupendelnde Fachkräfte in Bildung, Kultur, Gesundheits- und Sozialwesen",
		"thema": "11 Verkehr",
		"unterthema": "Pendler",
		"kuerzel": "I.11.5.09380",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "3.3",
		"stufe1": "Legislaturziel 3: Partnerschaftlich zusammenarbeiten",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-10-11T12:59:42",
		"id": 9380
	},
	{
		"template": "template001",
		"data-id": 9381,
		"chart-id": 9381,
		"filter": "",
		"parentId": null,
		"children": [
			9438
		],
		"title": "Grenzgänger und Pendler aus und nach Basel-Stadt",
		"subtitle": "",
		"lesehilfe": "Im Jahr 2022 pendelten etwas mehr als 91 100 Personen nach Basel-Stadt, um einer Erwerbstätigkeit nachzugehen – rund die Hälfte davon aus der Nordwestschweiz. Dem gegenüber stehen rund 24 300 Wegpendler. Daraus ergibt sich ein Zupendlerüberschuss (Saldo) von rund 66 800 Personen.",
		"erlaeuterungen": "Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe von jährlich rund 5 000 in Basel-Stadt wohnhaften Personen ab 15 Jahren und sind folglich mit einer gewissen Unsicherheit behaftet. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Die Zahl der Zupendler aus dem Ausland basiert auf der Grenzgängerstatistik des Bundesamtes für Statistik (4. Quartal).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)",
			"Bundesamt für Statistik (BFS), Grenzgängerstatistik (GGS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Grenzgänger und Pendler aus und nach Basel-Stadt",
		"thema": "11 Verkehr",
		"unterthema": "Pendler",
		"kuerzel": "I.11.5.09381",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "3.4",
		"stufe1": "Legislaturziel 3: Partnerschaftlich zusammenarbeiten",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-10-11T12:59:43",
		"id": 9381
	},
	{
		"template": "template001",
		"data-id": 9382,
		"chart-id": 9382,
		"filter": "",
		"parentId": null,
		"children": [
			9439
		],
		"title": "Wohnungen nach Belegungsart",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Ende 2024 existieren in Basel-Stadt 102 970 Wohnungen. Den grössten Anteil machen mit 75 195 (73,0%) die Mietwohnungen aus. Seit 2014 ist der Bestand von Genossenschaftswohnungen von 10 368 auf 11 598 gestiegen.",
		"erlaeuterungen": "Es werden nur Wohnungen berücksichtigt, welche per 31.12. von mindestens einer Person belegt waren. Sonstige Wohnungen umfassen Notwohnungen der Sozialhilfe, subventionierte Wohnungen gemeinnütziger Institutionen, Dienst- und Abwartswohnungen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungen nach Belegungsart",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.09382",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "4.1",
		"stufe1": "Legislaturziel 4: Städtischen Raum gemeinsam nutzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-11-13T08:45:51",
		"id": 9382
	},
	{
		"template": "template001",
		"data-id": 9383,
		"chart-id": 4133,
		"filter": "",
		"parentId": "4133",
		"children": [],
		"title": "Wohnungen nach Zimmerzahl",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Seit 2010 ist der gesamte Wohnungsbestand leicht und stetig auf 116 651 im Jahr 2024 gestiegen. Am stärksten war das Wachstum in diesem Zeitraum bei den Fünf- bzw. Zweizimmerwohnungen (+13,3% auf 7 198 bzw. +13,1% auf 27 965), am geringsten bei den Wohnungen mit sechs und mehr Zimmern (+8,5% auf 5 952).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungen nach Zimmerzahl",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.09383",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "4.2",
		"stufe1": "Legislaturziel 4: Städtischen Raum gemeinsam nutzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-03-31T11:06:02",
		"id": 9383
	},
	{
		"template": "template001",
		"data-id": 9384,
		"chart-id": 4135,
		"filter": "",
		"parentId": "4135",
		"children": [],
		"title": "Nettowohnungsproduktion",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Nettowohnungsproduktion lag 2024 bei 511 Einheiten; dies vor allem dank sehr hoher Umbautätigkeit.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettowohnungsproduktion",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.09384",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "4.3",
		"stufe1": "Legislaturziel 4: Städtischen Raum gemeinsam nutzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-03-25T08:33:31",
		"id": 9384
	},
	{
		"template": "befragungen001",
		"data-id": 9385,
		"chart-id": 4127,
		"filter": "",
		"parentId": "4127",
		"children": [],
		"title": "Zufriedenheit mit dem Wohnungsangebot",
		"subtitle": "«Wie zufrieden sind Sie mit dem Wohnungsangebot?», Basel-Stadt",
		"lesehilfe": "15,0% der Bevölkerung ist 2023 mit dem Wohnungsangebot sehr zufrieden und 32,5% eher zufrieden. Gegenüber 2019 ist die Unzufriedenheit mit dem Wohnungsangebot gestiegen.",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: seit 2019 in schriftlicher Form (Papier- bzw. Onlinefragebogen), zuvor telefonisch; seit 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppe (2011, 2015 und 2019 wurden nachgewichtet, die Werte weichen daher von früher publizierten ab). Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit dem Wohnungsangebot",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "4.4",
		"stufe1": "Legislaturziel 4: Städtischen Raum gemeinsam nutzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-31T10:44:42",
		"id": 9385
	},
	{
		"template": "template001",
		"data-id": 9386,
		"chart-id": 4149,
		"filter": "",
		"parentId": "4149",
		"children": [],
		"title": "Freiraumfläche und Anteil an der Gesamtfläche",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2024 betrugen die Freiraumflächen insgesamt 95,28 ha (2,58% der Kantonsfläche). Die Zunahme seit 2021 erfolgte u. a. aufgrund der Öffnung des Novartis Campus und der dortigen Parkanlagen für die Öffentlichkeit. Im Jahr 2013 reduzierten sich die Freiraumflächen vorübergehend aufgrund von Schulhauserweiterungen auf Kosten von Sportanlagen sowie der Umgestaltung der Voltamatte bis auf rund 83,9 Hektaren. Die Öffnung des Schwarzparks für die Bevölkerung sorgte 2014 für einen Sprung auf 88,5 Hektaren.",
		"erlaeuterungen": "Zu den Freiraumflächen zählen Parkanlagen, Spielplätze und Rasenflächen von Sportanlagen. Die Angaben basieren auf der Datenebene «Bodenbedeckung» der Amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100 m<sup>2</sup> geführt werden. Diese werden bei Bedarf oder spätestens in einem Turnus von 6 bis 12 Jahren mit einer periodischen Nachführung aktualisiert. Befestigte Objekte wie Gebäude, Strassenräume oder öffentliche Pärke werden detaillierter erfasst und bei baulichen Änderungen nachgeführt.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Freiraumfläche und Anteil an der Gesamtfläche",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.09386",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "4.5",
		"stufe1": "Legislaturziel 4: Städtischen Raum gemeinsam nutzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-01-13T12:16:25",
		"id": 9386
	},
	{
		"template": "template001",
		"data-id": 9387,
		"chart-id": 9387,
		"filter": "",
		"parentId": null,
		"children": [
			9444
		],
		"title": "Fussgänger- und Begegnungszonen",
		"subtitle": "Länge in Kilometern, Stadt Basel",
		"lesehilfe": "Im Jahr 2024 betrug die Länge der Begegnungszonen in der Stadt Basel 23,5 km, jene der Fussgängerzonen 4,8 km.",
		"erlaeuterungen": "Begegnungszonen: Es gilt eine Höchstgeschwindigkeit von 20 km/h; Fussgängerinnen und Fussgänger haben gegenüber Autos und Velos überall Vortritt. Fussgängerzonen (erst seit 2015 systematisch erfasst): Grundsätzliches Fahrverbot; befinden sich v. a. in der Innenstadt. Nicht als verkehrsberuhigte Strassen zählen separate Fuss- und Velowege sowie Altstadtgassen und Fussgängerpassagen, durch welche Autos nicht hindurchfahren können. Sind Fussgängerzonen oder Fahrverbote nur zeitlich eingeschränkt signalisiert, so müssen sie zwischen 09:00 und 19:00 Uhr während mindestens 8 Stunden entsprechend signalisiert sein (ohne Anlieferung), damit sie als verkehrsberuhigte Strassen zählen.",
		"quellenangabe": [
			"Amt für Mobilität Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://map.geo.bs.ch/?lang=de&baselayer_ref=Grundkarte%20grau&tree_groups=Verkehrsberuhigte%20Zonen&tree_group_layers_Verkehrsberuhigte%20Zonen=VR_Begegnungszone%2CVR_Fussgaengerzone&map_x=2612007&map_y=1267428&map_zoom=3' target = '_blank'>Fussgänger- und Begegnungszonen im kantonalen Geoportal.</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Fussgänger- und Begegnungszonen",
		"thema": "11 Verkehr",
		"unterthema": "Mobilitätsverhalten",
		"kuerzel": "I.11.6.09387",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "4.6",
		"stufe1": "Legislaturziel 4: Städtischen Raum gemeinsam nutzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-15T09:06:15",
		"id": 9387
	},
	{
		"template": "befragungen001",
		"data-id": 9388,
		"chart-id": 4150,
		"filter": "",
		"parentId": "4150",
		"children": [],
		"title": "Zufriedenheit mit Grünanlagen und Parks am Wohnort",
		"subtitle": "«Wie zufrieden sind Sie mit den Grünanlagen und Parks an Ihrem Wohnort?», Basel-Stadt, 2023",
		"lesehilfe": "85,8% der Bevölkerung sind 2023 mit den Grünanlagen und Parks an ihrem Wohnort eher bis sehr zufrieden.",
		"erlaeuterungen": "Alle vier Jahre wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt. Die Daten werden 2023 nach Geschlecht, Staatsangehörigkeit und Altersgruppe gewichtet. Die Daten der Befragungen 2011, 2015 und 2019 wurden nach den identischen Faktoren nachgewichtet. Die Werte dieser drei Jahre weichen daher von früher publizierten ab. Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit Grünanlagen und Parks am Wohnort",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.09388",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "4.7",
		"stufe1": "Legislaturziel 4: Städtischen Raum gemeinsam nutzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-03T08:35:42",
		"id": 9388
	},
	{
		"template": "line001",
		"data-id": 9390,
		"chart-id": 9390,
		"filter": "",
		"parentId": null,
		"children": [
			8455,
			8958,
			9447,
			10049,
			11906
		],
		"title": "Tropennächte",
		"subtitle": "Anzahl Nächte, Basel-Stadt",
		"lesehilfe": "Im Jahr 2024 wurden an der Messstation St. Johann im Stadtzentrum von Basel 23 Tropennächte registriert, während an der vorstädtischen Station Basel-Binningen nur 2 Tropennächte verzeichnet wurden.",
		"erlaeuterungen": "Tropennächte sind Nächte, in denen die Temperatur nicht unter 20 °C sinkt. Die Temperaturmessungen erfolgen an verschiedenen Messstationen in der Region Basel. Gewisse Abweichungen zu den validierten MeteoSchweiz-Daten aufgrund unterschiedlicher Methodik sind möglich. Infolge der unterschiedlichen Lagen der Messstationen ist auch die Anzahl Tropennächte verschieden stark ausgeprägt. Im innenstädtischen Umfeld mit schlechter Durchlüftung und dichter Bebauung ist die thermische Belastung nachts besonders hoch, wohingegen in vorstädtischer Lage (offene Bebauung) oder bei viel Vegetation (Kühlung durch Verdunstung) die nächtliche Abkühlung besser erfolgen kann.",
		"quellenangabe": [
			"Universität Basel",
			"Lufthygieneamt beider Basel",
			"Meteorologischer Verein der Region Basel",
			"MeteoSchweiz"
		],
		"externalLinks": [
			"Weitere Informationen zum Indikator und den einzelnen Messstationen: <a href = 'https://www.bs.ch/schwerpunkte/umweltbericht-beider-basel/indikatoren-uebersicht/indikator-0815' target = '_blank'>Umweltbericht beider Basel</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Tropennächte",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Klima",
		"kuerzel": "I.02.12.09390",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "5.3",
		"stufe1": "Legislaturziel 5: Mit natürlichen Ressourcen nachhaltig umgehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-21T02:31:42",
		"id": 9390
	},
	{
		"template": "template001",
		"data-id": 9391,
		"chart-id": 9391,
		"filter": "",
		"parentId": null,
		"children": [
			9448
		],
		"title": "Elektroautos",
		"subtitle": "Neue Inverkehrsetzungen von Personenwagen mit elektrischem Antrieb (inkl. Hybride)",
		"lesehilfe": "Der Anteil Elektroautos (inkl. Hybride) an den gesamten neuen Inverkehrsetzungen von Personenwagen hat seit 2011 von 0,2% auf 23,8% (2024) zugenommen.",
		"erlaeuterungen": "In der Kategorie der Elektrofahrzeuge werden hier neben den rein elektrisch betriebenen Fahrzeugen auch Plug-in-Hybride berücksichtigt, deren Akku sowohl über den Verbrennungsmotor als auch mit einem Stecker am Stromnetz geladen werden kann. Wasserstoffautos werden von einem Elektromotor angetrieben, deshalb zählen auch sie zu den Elektrofahrzeugen. «Personenwagen» sind leichte Motorwagen zum Personentransport mit höchstens neun Sitzplätzen einschliesslich Fahrer oder Fahrerin. Der Strassenfahrzeugbestand berücksichtigt alle am 30. September immatrikulierten zivilen Fahrzeuge von Halterinnen und Haltern, die an diesem Stichtag Wohnsitz im Kanton hatten.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Elektroautos",
		"thema": "11 Verkehr",
		"unterthema": "Motorfahrzeuge",
		"kuerzel": "I.11.1.09391",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "5.6",
		"stufe1": "Legislaturziel 5: Mit natürlichen Ressourcen nachhaltig umgehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-03-25T08:33:35",
		"id": 9391
	},
	{
		"template": "line001",
		"data-id": 9392,
		"chart-id": 9392,
		"filter": "",
		"parentId": null,
		"children": [
			9449
		],
		"title": "Solarenergie",
		"subtitle": "Produktion in GWh, Basel-Stadt",
		"lesehilfe": "Die Erzeugung von Elektrizität durch Fotovoltaikanlagen stieg von 0,3 GWh im Jahr 2000 auf 39,5 GWh im Jahr 2022. Die Produktion von solarthermischer Energie nahm in den letzten Jahren ebenfalls zu und lag 2022 bei 20,8 GWh.",
		"erlaeuterungen": "Daten zur solarthermischen Energie werden seit 2010 im Rahmen der kantonalen Energiestatistik jedes zweite Jahr erhoben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Solarenergie",
		"thema": "08 Energie",
		"unterthema": "Produktion",
		"kuerzel": "I.08.2.09392",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "5.9",
		"stufe1": "Legislaturziel 5: Mit natürlichen Ressourcen nachhaltig umgehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-03-12T10:18:49",
		"id": 9392
	},
	{
		"template": "template001",
		"data-id": 9393,
		"chart-id": 9393,
		"filter": "",
		"parentId": null,
		"children": [
			9450
		],
		"title": "Anteil Fernwärme und erneuerbare Energieträger an den Heizungen",
		"subtitle": "Anteil am Bruttoenergieverbrauch aller Heizungen, Basel-Stadt",
		"lesehilfe": "Fernwärme, welche aus erneuerbaren Energieträgern produziert wird, weist 2022 einen Anteil von 38,7% am Bruttoenergieverbrauch der Heizungen im Kanton Basel-Stadt auf. Die anderen erneuerbaren Energieträger liegen bei 3,2%, so dass die erneuerbaren zusammen auf 41,2% kommen. Der Verbrauch von Fernwärme aus nicht erneuerbaren Energieträgern ist von 14,1% im Jahr 2014 auf 23,7% im Jahr 2022 gestiegen, während die anderen nicht erneuerbaren von 51,3% auf 34,4% gesunken sind.",
		"erlaeuterungen": "Elektrische Heizungen sind nicht berücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil Fernwärme und erneuerbare Energieträger an den Heizungen",
		"thema": "08 Energie",
		"unterthema": "Erneuerbare",
		"kuerzel": "I.08.3.09393",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "5.10",
		"stufe1": "Legislaturziel 5: Mit natürlichen Ressourcen nachhaltig umgehen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-10-15T09:04:25",
		"id": 9393
	},
	{
		"template": "template001",
		"data-id": 9394,
		"chart-id": 9394,
		"filter": "",
		"parentId": null,
		"children": [
			9451
		],
		"title": "Offene Behördendaten",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Ende 2024 sind im kantonalen Datenportal 331 Datensätze von 42 Organisationen, sogenannte offene Behördendaten (Open Government Data, OGD), publiziert. Im kantonalen Geoportal sind 192 Geodatensätze öffentlich verfügbar.",
		"erlaeuterungen": "Jeweils Stand per 31. Dezember. Ein Datensatz im Datenportal entspricht jeweils einer Tabelle, ein Datensatz im Geoportal kann mehrere Ebenen (Karten resp. Tabellen) umfassen; die Zahlen sind daher nicht direkt miteinander vergleichbar. Datensätze des Geoportals sind teilweise auch im kantonalen Datenportal publiziert. Das kantonale Datenportal ist seit November 2019 online.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt",
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [
			"Kantonales Datenportal: <a href = 'https://data.bs.ch' target = '_blank'>data.bs.ch</a>",
			"Kantonales Geoportal: <a href = 'https://map.geo.bs.ch/' target = '_blank'>map.geo.bs.ch</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Offene Behördendaten",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.09394",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "6.1",
		"stufe1": "Legislaturziel 6: Modernen, kundenfreundlichen Service public anbieten",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-01-14T08:52:56",
		"id": 9394
	},
	{
		"template": "template001",
		"data-id": 9396,
		"chart-id": 9396,
		"filter": "",
		"parentId": null,
		"children": [
			9453
		],
		"title": "Teilzeiterwerbstätige in der kantonalen Verwaltung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Bei den Männern ist der Anteil der Teilzeiterwerbstätigen im Beobachtungszeitraum von 32% auf 40% gestiegen und bei den Frauen von 75% auf 78%.",
		"erlaeuterungen": "Anteil der Teilzeiterwerbstätigen in der baselstädtischen Kantonsverwaltung. Gezeigt wird das gesamte Staatspersonal (unabhängig vom Wohnsitz) auf Basis des ordentlichen Bestandes (sog. Headcount); nur Verwaltung im engeren Sinn (ohne Betriebe wie BVB und IWB sowie Spitäler).",
		"quellenangabe": [
			"Human Ressources Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Teilzeiterwerbstätige in der kantonalen Verwaltung",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.09396",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "6.5",
		"stufe1": "Legislaturziel 6: Modernen, kundenfreundlichen Service public anbieten",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-09-30T12:46:08",
		"id": 9396
	},
	{
		"template": "template001",
		"data-id": 9397,
		"chart-id": 9397,
		"filter": "",
		"parentId": null,
		"children": [
			9454
		],
		"title": "Anteil Frauen in Kaderpositionen in der kantonalen Verwaltung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2023 beträgt der Anteil der Frauen in Kaderpositionen in der kantonalen Verwaltung Basel-Stadt 37,1%.",
		"erlaeuterungen": "Staatspersonal: Auf Basis des ordentlichen Bestandes (sog. Headcount), nur Verwaltung im engeren Sinn (ohne Betriebe wie BVB und IWB sowie Spitäler).",
		"quellenangabe": [
			"Human Ressources Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil Frauen in Kaderpositionen in der kantonalen Verwaltung",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Staatspersonal",
		"kuerzel": "I.18.3.09397",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "6.6",
		"stufe1": "Legislaturziel 6: Modernen, kundenfreundlichen Service public anbieten",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-09-30T12:46:10",
		"id": 9397
	},
	{
		"template": "template001",
		"data-id": 9398,
		"chart-id": 9398,
		"filter": "",
		"parentId": null,
		"children": [
			9455
		],
		"title": "Aktive E-Government-Konten",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Per 31.12.2024 haben sich 25 593 von 58 313 registrierten Benutzenden mit ihrem E-Government-Konto (eKonto) des Kantons Basel-Stadt bereits mit der neuen, verbindlichen Anmelde-Lösung AGOV (Authentifizierungsdienst der Schweizer Behörden) angemeldet. Aufgrund der Umstellung ist diese Zahl mit den Vorjahren nicht vergleichbar.",
		"erlaeuterungen": "Registrierte Benutzer können Privatpersonen und Firmen sein; aktive Benutzer sind Benutzer, welche sich in den letzten 365 Tagen mindestens einmal angemeldet haben. Konten von Benutzern, welche sich länger als zwei Jahre nicht angemeldet haben, werden nach Vorankündigung gelöscht.",
		"quellenangabe": [
			"Finanzdepartement Basel-Stadt"
		],
		"externalLinks": [
			"Informationen zum <a href = 'https://www.itbs.bs.ch/dienstleistungen/egovernment/das-ekonto.html' target = '_blank'>eKonto des Kantons Basel-Stadt</a>."
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Aktive E-Government-Konten",
		"thema": "17 Politik",
		"unterthema": "",
		"kuerzel": "I.17.PTAN.09398",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "6.2",
		"stufe1": "Legislaturziel 6: Modernen, kundenfreundlichen Service public anbieten",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-01-06T09:57:39",
		"id": 9398
	},
	{
		"template": "template001",
		"data-id": 9457,
		"chart-id": 6459,
		"filter": "",
		"parentId": "6459",
		"children": [],
		"title": "Beschäftigung nach Branche",
		"subtitle": "in Vollzeitäquivalenten, Basel-Stadt",
		"lesehilfe": "In Basel-Stadt sind 2023 rund 155 700 Beschäftigte (in VZÄ) tätig, was einem Rückgang um rund 600 VZÄ bzw. -0,4% im Vergleich zum Vorjahr entspricht. Die grösste Branche ist das Gesundheits- und Sozialwesen mit rund 25 300 VZÄ (+2,5%), welche auch das stärkste absolute Wachstum gegenüber dem Vorjahr aufweist (+613 VZÄ). Die Branche «Personalvermittlung und -überlassung» hingegen weist im Jahr 2023 die grösste relative Abnahme auf (-391 VZÄ bzw. -5,9%).",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und die einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Referenzperiode ist jeweils der Dezember des Jahres. Die Beschäftigung in Vollzeitäquivalenten (VZÄ) resultiert aus der Umrechnung des Arbeitsvolumens sämtlicher Voll- und Teilzeitbeschäftigten in Vollzeitbeschäftigte mittels Schätzmodell (basierend auf Lohnangaben der AHV und Informationen weiterer Erhebungen).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beschäftigung nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "",
		"kennzahlenset": "Legislaturplan",
		"kuerzelKunde": "1.8",
		"stufe1": "Legislaturziel 1: Standortattraktivität langfristig sichern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-12T11:18:16",
		"id": 9457
	}
];