var indikatorensetData = [
	{
		"template": "line001",
		"data-id": 7510,
		"chart-id": 7510,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Arbeitslosenquote nach Alter",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Arbeitslosenquote ist seit Jahresbeginn von 4,4% auf aktuell 3,7% gesunken. Zum Rückgang haben sowohl saisonale Effekte als auch die Lockerungen der Massnahmen gegen die COVID-19-Pandemie beigetragen. Die Jugendarbeitslosenquote ist im Juli auf 3,8% gestiegen, während die Arbeitslosenquote der Personen ab 50 Jahren weiterhin unter dem Durchschnitt der Gesamtbevölkerung liegt.",
		"erlaeuterungen": "Als Arbeitslose gelten Personen, welche bei einem Regionalen Arbeitsvermittlungszentrum (RAV) gemeldet sind, keine Stelle haben und sofort vermittelbar sind. Die Arbeitslosenquote berechnet sich aus der Zahl der Arbeitslosen, geteilt durch die Erwerbspersonen.",
		"quellenangabe": [
			"Staatssekretariat für Wirtschaft SECO, Arbeitslosenstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitslosenquote nach Alter",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Arbeitslose",
		"kuerzel": "",
		"kennzahlenset": "Monatsindikatoren",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-09T08:36:19",
		"id": 7510
	},
	{
		"template": "line001",
		"data-id": 7511,
		"chart-id": 7511,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Gemeldete offene Stellen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Seit Jahresbeginn 2021 steigt die Zahl der offenen Stellen wieder an und übertrifft seit April 2021 gar die Werte von vor dem Ausbruch der COVID-19-Pandemie. Aktuell sind rund 2 400 Stellen in Basel-Stadt offen. Die grosse Mehrheit davon sind meldepflichtig.",
		"erlaeuterungen": "Die offenen Stellen werden den regionalen Arbeitsvermittlungszentren freiwillig gemeldet. Im Juli 2018 wurde eine Meldepflicht für Branchen mit einer Arbeitslosenquote über 8% eingeführt. Dieser Schwellenwert wurde im Januar 2020 auf 5% gesenkt. Wegen COVID-19 und seinen Folgen hat der Bundesrat die Stellenmeldepflicht für die Zeit vom 26. März 2020 bis 8. Juni 2020 aufgehoben.",
		"quellenangabe": [
			"Staatssekretariat für Wirtschaft SECO, Arbeitslosenstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Gemeldete offene Stellen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Arbeitslose",
		"kuerzel": "I.03.4.07511",
		"kennzahlenset": "Monatsindikatoren",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-09T08:36:20",
		"id": 7511
	},
	{
		"template": "line001",
		"data-id": 7512,
		"chart-id": 7512,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Jahresteuerung Basler Index und Landesindex",
		"subtitle": "",
		"lesehilfe": "Die Jahresteuerung des Basler Index lag seit dem Basiswechsel von Dezember 2015 jeweils leicht über derjenigen des gesamtschweizerischen Landesindex der Konsumentenpreise. Diese Entwicklung setzte sich zwischen April 2020 und März 2021 fort, allerdings im negativen Bereich; der Basler Index entwickelte sich damit etwas weniger stark rückläufig als der Landesindex. Jüngst hat die Teuerung wieder spürbar angezogen.",
		"erlaeuterungen": "Die Jahresteuerung beschreibt die Teuerung zwischen dem aktuellen Monat und dem Vorjahresmonat wie beispielsweise zwischen Februar 2021 und Februar 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt",
			"Bundesamt für Statistik (BFS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Jahresteuerung Basler Index und Landesindex",
		"thema": "05 Preise",
		"unterthema": "Basler Index der Konsumentenpreise",
		"kuerzel": "I.05.1.07512",
		"kennzahlenset": "Monatsindikatoren",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_0-1",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-02T08:32:46",
		"id": 7512
	},
	{
		"template": "line001",
		"data-id": 7513,
		"chart-id": 7513,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Basler Index",
		"subtitle": "Basis Dezember 2020 = 100",
		"lesehilfe": "Die mittlere Jahresteuerung des Basler Index beläuft sich für das ganze Jahr 2020 auf -0,6%. Das durchschnittliche Preisniveau in der Region Basel ist damit leicht gesunken. Im bisherigen Jahresverlauf 2021 hat sich die Teuerung akzentuiert.",
		"erlaeuterungen": "Als regionale Variante des Landesindex der Konsumentenpreise veröffentlicht das Statistische Amt des Kantons Basel-Stadt monatlich den Basler Index. Dieser misst die durchschnittliche Preisveränderung der durch die privaten Haushalte des Kantons Basel-Stadt konsumierten Waren und Dienstleistungen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt",
			"Bundesamt für Statistik (BFS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Basler Index",
		"thema": "05 Preise",
		"unterthema": "Basler Index der Konsumentenpreise",
		"kuerzel": "I.05.1.07513",
		"kennzahlenset": "Monatsindikatoren",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_0-2",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-02T08:32:46",
		"id": 7513
	},
	{
		"template": "template001",
		"data-id": 7515,
		"chart-id": 7515,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bilanz der Wohnbevölkerung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Monatliche Veränderungen am Bevölkerungsbestand sind in erster Linie auf räumliche Bevölkerungsbewegungen (Zuzüge und Wegzüge) zurückzuführen. Der Saldo der natürlichen Bevölkerungsbewegungen (Geburten und Todesfälle) ist in der Regel deutlich kleiner und trägt damit nur geringfügig zur Veränderung des Bestandes bei.",
		"erlaeuterungen": "Aufgrund nachträglich gemeldeter Ereignisse (z. B. verspäteter An- oder Abmeldungen) entspricht die Summe aus Wanderungssaldo und Geburtssaldo nicht der effektiven Veränderung des Bevölkerungsbestandes per Ende Monat. Diese Differenz wird mit dem Bereinigungssaldo ausgewiesen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bilanz der Wohnbevölkerung",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.07515",
		"kennzahlenset": "Monatsindikatoren",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-07-22T08:43:05",
		"id": 7515
	},
	{
		"template": "line001",
		"data-id": 7516,
		"chart-id": 7516,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Logiernächte nach Monat und Herkunft",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "53 919 Logiernächte wurden im Juni 2021 in den Basler Hotelbetrieben gebucht, 6 380 bzw. 10,6% weniger als im Mai. Im Vergleich zum Vorjahresmonat entspricht dies einer Zunahme um 78,6% bzw. 23 729 Übernachtungen. Die inländischen Gäste buchten 30 615 Logiernächte (+62,3%), die Gäste aus dem Ausland 23 304 Übernachtungen (+105,7%).",
		"erlaeuterungen": "Bei der Herkunft der Gäste ist der Wohnsitz massgebend und nicht die Staatsangehörigkeit.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Logiernächte nach Monat und Herkunft",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07516",
		"kennzahlenset": "Monatsindikatoren",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-07-29T08:25:33",
		"id": 7516
	},
	{
		"template": "template001",
		"data-id": 7517,
		"chart-id": 7517,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Auslastung der Hotels nach Kategorie",
		"subtitle": "Basel-Stadt, Juni",
		"lesehilfe": "Rund drei Viertel der verfügbaren Zimmer werden in 3- bis 5-Sterne-Hotels angeboten. Die Auslastung liegt aktuell in allen Kategorien unter 35%.",
		"erlaeuterungen": "Die Nettozimmerauslastung gibt an, wie oft ein Zimmer an den Tagen, an denen der Betrieb geöffnet war und das Zimmer zur Verfügung stand, belegt war.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Auslastung der Hotels nach Kategorie",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "",
		"kennzahlenset": "Monatsindikatoren",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-07-29T08:25:34",
		"id": 7517
	},
	{
		"template": "mappie001",
		"data-id": 7763,
		"chart-id": 7763,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bevölkerung nach Wohnviertel",
		"subtitle": "Basel-Stadt, Juni",
		"lesehilfe": "Im Juni 2021 stieg die Einwohnerzahl gegenüber dem Vormonat in drei Wohnvierteln sowie in Riehen. In sechzehn Wohnvierteln und in Bettingen ging sie zurück.",
		"erlaeuterungen": "Die Karte zeigt auf der Ebene der Gemeinden und Wohnviertel die Einwohnerzahl (Punkte) am Ende des Monats und deren Veränderung gegenüber dem Ende des Vormonats (Flächen).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel",
			"Gemeinde"
		],
		"description": "Bevölkerung nach Wohnviertel",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.07763",
		"kennzahlenset": "Monatsindikatoren",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-07-22T08:43:05",
		"id": 7763
	},
	{
		"template": "line001",
		"data-id": 8980,
		"chart-id": 8980,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Arbeitslose, Langzeitarbeitslose und Anteil der Langzeitarbeitslosen am Total",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Nach einem knappen Jahr der Covid-19-Pandemie erreichte im Januar 2021 die Zahl der Personen, die bei den RAV in Basel-Stadt als arbeitslos registriert sind, einen Höchstand von rund 4 500. Seit Februar 2021 ist die Zahl rückläufig. Ende Juli 2021 sind rund 3 800 Personen arbeitslos. Die Zahl der Langzeitarbeitslosen geht allerdings kaum zurück und ist im Juli 2021 mit rund 1 100 Personen mehr als doppelt so hoch wie im Frühling 2020. Der Anteil der Langzeitarbeitslosen liegt aktuell bei 29%.",
		"erlaeuterungen": "Als Arbeitslose gelten Personen, welche bei einem Regionalen Arbeitsvermittlungszentrum (RAV) gemeldet sind, keine Stelle haben und sofort vermittelbar sind. Langzeitarbeitslose sind Personen, die länger als ein Jahr als arbeitslos registriert sind. In der Grafik sind Monatswerte abgebildet.",
		"quellenangabe": [
			"Staatssekretariat für Wirtschaft SECO, Arbeitslosenstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitslose, Langzeitarbeitslose und Anteil der Langzeitarbeitslosen am Total",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Arbeitslose",
		"kuerzel": "I.03.4.08980",
		"kennzahlenset": "Monatsindikatoren",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-09T08:36:20",
		"id": 8980
	},
	{
		"template": "template001",
		"data-id": 8981,
		"chart-id": 8981,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Veränderung der Arbeitslosenzahl im Vergleich zum Vorjahresmonat",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Von März 2020 bis April 2021 waren die Arbeitslosenzahlen in Basel-Stadt aufgrund der Covid-19-Pandemie stets deutlich höher als im Vorjahresmonat. Der Trend hat sich im Mai 2021 geändert. Ende Juli 2021 sind 434 Personen weniger arbeitslos als ein Jahr zuvor.",
		"erlaeuterungen": "Dargestellt ist die Differenz der Arbeitslosenzahlen in Basel-Stadt jeweils im Vergleich zum Vorjahresmonat. Als Arbeitslose gelten Personen, welche bei einem Regionalen Arbeitsvermittlungszentrum (RAV) gemeldet sind, keine Stelle haben und sofort vermittelbar sind.",
		"quellenangabe": [
			"Staatssekretariat für Wirtschaft SECO, Arbeitslosenstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Veränderung der Arbeitslosenzahl im Vergleich zum Vorjahresmonat",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Arbeitslose",
		"kuerzel": "I.03.4.08981",
		"kennzahlenset": "Monatsindikatoren",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-09T08:36:21",
		"id": 8981
	},
	{
		"template": "stock001",
		"data-id": 8992,
		"chart-id": 8992,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Von Kurzarbeit betroffene Arbeitnehmer",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Mit dem Lockdown zur Bekämpfung der COVID-19-Pandemie im Frühling 2020 sind die Anmeldungen von Kurzarbeit rasant gestiegen. Für März 2020 wurde beim Amt für Wirtschaft und Arbeit (AWA) des Kantons Basel-Stadt Kurzarbeit für 85 000 Arbeitnehmerinnen und Arbeitnehmer beantragt, während es im Vormonat noch 21 Anmeldungen gewesen waren. Die beantragte Kurzarbeit für April, Mai und Juni war am höchsten und betraf mehr als 90 000 Personen. Im Juli und August lag der Wert nur ein bisschen tiefer (rund 75 000). Von September bis Dezember betrug die Anzahl der Angestellten, für die Kurzarbeit beantragt wurde, zwischen 20 000 und 30 000. Zu Beginn des Jahres 2021 lag der Wert wieder im Bereich von 50 000 Personen. Im Mai 2021 war ein deutlicher Rückgang zu beobachten und im Juli 2021 liegt der Wert mit rund 30 000 nochmal leicht tiefer (provisorische Zahlen). 99% der beantragten Kurzarbeit wurde bisher vom AWA genehmigt.<br><br>Wie viel Kurzarbeit wird tatsächlich in Anspruch genommen (abgerechnet)? Von März bis Mai 2020 wurde für 40 000 bis 60 000 Arbeitnehmerinnen und Arbeitnehmer tatsächlich Kurzarbeit abgerechnet (die Spitze war im April). Damit liegt der Anteil der genehmigten Kurzarbeit, die abgerechnet und entschädigt wurde, in Frühling 2020 zwischen 50% und 65%. In den Monaten Juni bis September 2020 ging die Zahl der abgerechneten Kurzarbeit deutlich zurück. Im Januar und Februar 2021 wurde wieder Kurzarbeit für mehr als 20 000 Personen abgerechnet, seit März geht die Zahl zurück.  <br><br>Die aktuelle Lage ist (auch bei längerer Betrachtungsperspektive) beispiellos. Üblicherweise wird Kurzarbeit für weniger als 100 Personen pro Monat beantragt. In Folge der globalen Finanz- und Wirtschaftskrise 2008/2009 wurde zwischen März 2009 und Juni 2010 Kurzarbeit für rund 1 000 bis fast 1 700 Personen pro Monat beantragt. Abgerechnet wurde damals durchschnittlich die Hälfte der beantragten Kurzarbeit.",
		"erlaeuterungen": "Die Kurzarbeit ist ein Instrument des Bundes, um Entlassungen zu verhindern. Kurzarbeitsentschädigungen werden von den Unternehmen für ihre Angestellten beantragt, wenn sie mit einem vorübergehenden Rückgang der Nachfrage konfrontiert sind. Wegen der COVID-19-Pandemie wurde der Zugang zur Kurzarbeit erleichtert. Bei Erfüllung der Bedingungen für Kurzarbeit genehmigen die kantonalen Arbeitsämter die Anträge. Nach Ablauf der Abrechnungsperiode wird die Kurzarbeit abgerechnet, d. h. es wird berechnet, wie viel effektiv weniger gearbeitet wurde. Daraufhin bekommen die Firmen eine Entschädigung, damit sie trotzdem die Löhne bezahlen können (80% des ausgefallenen Lohns). In der Grafik ist die Anzahl der von Kurzarbeit betroffenen Arbeitnehmerinnen und Arbeitnehmer, die in einem Betrieb oder in einer Betriebsabteilung arbeiten, die Kurzarbeit beim AWA des Kantons Basel-Stadt beantragt haben, abgebildet. Die betroffenen Personen können auch ausserhalb des Kantons Basel-Stadt arbeiten oder wohnen. Die Zahlen der beantragten und der genehmigten Kurzarbeit der letzten drei Monate sind provisorisch. Die Zahl der abgerechneten Kurzarbeit in Basel-Stadt steht mit drei Monaten Verzögerung zur Verfügung.",
		"quellenangabe": [
			"Staatssekretariat für Wirtschaft SECO, Arbeitslosenstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Von Kurzarbeit betroffene Arbeitnehmer",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Arbeitslose",
		"kuerzel": "I.03.4.08992",
		"kennzahlenset": "Monatsindikatoren",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-08-09T08:36:21",
		"id": 8992
	}
];