var indikatorensetData = [
	{
		"template": "line001_print",
		"data-id": 6242,
		"chart-id": 6242,
		"filter": "",
		"parentId": "5201",
		"children": [],
		"title": "Bevölkerungsdichte",
		"subtitle": "Einwohner pro Hektar, Basel-Stadt",
		"lesehilfe": "Bis 2002 verzeichnete Basel-Stadt sinkende Bevölkerungszahlen. Seit 2007 nimmt die baselstädtische Wohnbevölkerung und mit ihr die Bevölkerungsdichte wieder zu.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bevölkerungsdichte",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.06242",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 4-2",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 4: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:35",
		"id": 6242
	},
	{
		"template": "mappie001_print",
		"data-id": 6243,
		"chart-id": 6243,
		"filter": "",
		"parentId": "5202",
		"children": [],
		"title": "Bevölkerungsdichte",
		"subtitle": "Einwohner pro Hektar, nach Wohnviertel, Basel-Stadt, 2019",
		"lesehilfe": "Mit 257,3 Einwohnern pro Hektar weist das Wohnviertel Matthäus am Jahresende 2019 die höchste Bevölkerungsdichte auf. Ebenfalls hohe Bevölkerungsdichten zeigen sich in den Wohnvierteln Gundeldingen, Iselin und Clara. Im Vergleich zu 2000 am stärksten zugenommen hat die Bevölkerungsdichte im Wohnviertel Rosental; dies aufgrund der Bebauung des Erlenmattareals. Ebenfalls deutlich höher als noch 2000 sind die Bevölkerungsdichten in den Wohnvierteln Clara, Altstadt Grossbasel, Iselin und Am Ring.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Bevölkerungsdichte",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.06243",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 4-3",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 4: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_003",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:35",
		"id": 6243
	},
	{
		"template": "template001_print",
		"data-id": 6244,
		"chart-id": 6244,
		"filter": "",
		"parentId": "5203",
		"children": [],
		"title": "Zu- und Wegpendler nach Herkunft und Ziel",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2020 pendeln rund 89 000 Personen nach Basel-Stadt, um einer Erwerbstätigkeit nachzugehen, rund 61% von ihnen aus der Schweiz. Rund 22 000 Wegpendler stehen dem gegenüber. Dies ergibt einen Zupendlerüberschuss von rund 67 000 Personen.",
		"erlaeuterungen": "Bis 2000 stammen die Daten aus der Eidgenössischen Volkszählung (Vollerhebung), seit 2010 aus der Strukturerhebung (Hochrechnungen aufgrund einer Stichprobenerhebung). Die Zahl der Zupendler aus dem Ausland basiert bis 2000 auf den gültigen Grenzgängerbewilligungen Ende November (2000: Ende Dezember) gemäss Bundesamt für Migration und seit 2010 auf der Grenzgängerstatistik des Bundesamtes für Statistik (4. Quartal). Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)",
			"Bundesamt für Statistik (BFS), Volkszählung (VZ)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zu- und Wegpendler nach Herkunft und Ziel",
		"thema": "11 Verkehr",
		"unterthema": "Pendler",
		"kuerzel": "I.11.5.06244",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 4-12",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 4: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:34",
		"id": 6244
	},
	{
		"template": "line001_print",
		"data-id": 6245,
		"chart-id": 6245,
		"filter": "",
		"parentId": "5813",
		"children": [],
		"title": "Leerwohnungsquote",
		"subtitle": "in Prozent, Basel-Stadt",
		"lesehilfe": "Die Leerwohnungsquote sank seit 2006 kontinuierlich und erreichte 2014 mit 0,2% den tiefsten Wert. Danach stieg sie und erreichte 2021 eine Quote von 1,1%.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungsquote",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.06245",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 4-5",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 4: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:36",
		"id": 6245
	},
	{
		"template": "mappie001_print",
		"data-id": 6246,
		"chart-id": 6246,
		"filter": "",
		"parentId": "5814",
		"children": [],
		"title": "Leerwohnungsquote nach Gemeinde und Wohnviertel",
		"subtitle": "Basel-Stadt, 2021",
		"lesehilfe": "Die höchste Leerwohnungsquote aller Wohnviertel wurde 2021 in der Grossbasler Altstadt verzeichnet (2,2%). Die Zunahme gegenüber der Quote von vor zehn Jahren war ebenfalls im Wohnviertel Altstadt am grössten (von 0,4% auf 2,2%).",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Leerwohnungsquote nach Gemeinde und Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.06246",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 4-6",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 4: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_006",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:37",
		"id": 6246
	},
	{
		"template": "line001_print",
		"data-id": 6247,
		"chart-id": 6247,
		"filter": "",
		"parentId": "4140",
		"children": [],
		"title": "Mittlere Wohnfläche pro Person",
		"subtitle": "in m², Basel-Stadt",
		"lesehilfe": "2021 beträgt die mittlere Wohnfläche pro Person in Basel-Stadt 41,6 m². Zuvor nahm sie bis 2010 auf 42,1 m² zu, sank zwischenzeitlich auf 41,0 m² im Jahr 2018 und steigt seither wieder.",
		"erlaeuterungen": "Stand jeweils per Jahresende. Ab 2012 kantonale Registerauswertungen, frühere Werte wurden auf Basis der Volkszählungen 1980, 1990 und 2000 berechnet.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittlere Wohnfläche pro Person",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.06247",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 4-7",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 4: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:37",
		"id": 6247
	},
	{
		"template": "template001_print",
		"data-id": 6248,
		"chart-id": 6248,
		"filter": "",
		"parentId": "4135",
		"children": [],
		"title": "Nettowohnungsproduktion",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Nettowohnungsproduktion lag 2021 bei 977 Einheiten. Dies vor allem dank einer wiederum hohen Neubauproduktion sowie eines stark positiven Umbausaldos.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettowohnungsproduktion",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.06248",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 4-8",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 4: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:38",
		"id": 6248
	},
	{
		"template": "template001_print",
		"data-id": 6249,
		"chart-id": 6249,
		"filter": "",
		"parentId": "5817",
		"children": [],
		"title": "Nettowohnungsproduktion",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2012-2021",
		"lesehilfe": "Die Nettowohnungsproduktion war in den letzten zehn Jahren im Wohnviertel Rosental besonders hoch. Auf dieses Wohnviertel entfielen rund 22% der gesamtkantonalen Nettoproduktion. Die Nettowohnungsproduktion ist insgesamt vor allem auf grosse Arealentwicklungen zurückzuführen und in kleinerem Masse auf Erneuerungen bzw. Verdichtungen im Bestand.",
		"erlaeuterungen": "Die Nettowohnungsproduktion setzt sich wie folgt zusammen: Neugebaute Wohnungen minus abgebrochene Wohnungen plus Saldo aus Umbauten (kann positiv oder negativ sein).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Nettowohnungsproduktion",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.06249",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 4-9",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 4: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:38",
		"id": 6249
	},
	{
		"template": "mappie001_print",
		"data-id": 6250,
		"chart-id": 6250,
		"filter": "",
		"parentId": "5818",
		"children": [],
		"title": "Bruttogeschossfläche Wohnen nach Wohnviertel",
		"subtitle": "in m<sup>2</sup>, Basel-Stadt, 2020",
		"lesehilfe": "Die grösste Bruttogeschossfläche (BGF) Wohnen weist im Jahr 2020 die Gemeinde Riehen vor dem Wohnviertel Gundeldingen auf. Werden die Anteile der BGF Wohnen an der gesamten BGF betrachtet, verfügen die Wohnviertel Bruderholz und Bachletten über die höchsten Werte.",
		"erlaeuterungen": "Die Daten zur Bruttogeschossfläche (BGF) wurden bis 2020 fünfjährlich aktualisiert. Die Erhebungsmethodik wurde im Rahmen der Berechnung der Daten für das Jahr 2020 überarbeitet. Ab 2020 werden die Daten jährlich aktualisiert. Die Bruttogeschossfläche ist die Summe der Grundflächen der ober- und unterirdischen Geschosse von Gebäuden, welche zum Wohnen oder Arbeiten genutzt werden können. Für das Jahr 2000 stehen keine Daten zur Verfügung.",
		"quellenangabe": [
			"Planungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bruttogeschossfläche Wohnen nach Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.06250",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 4-10",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 4: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_010",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:33",
		"id": 6250
	},
	{
		"template": "befragungen001_print",
		"data-id": 6251,
		"chart-id": 6251,
		"filter": "",
		"parentId": "4150",
		"children": [],
		"title": "Zufriedenheit mit Grünanlagen und Parks am Wohnort",
		"subtitle": "«Wie zufrieden sind Sie mit den Grünanlagen und Parks an Ihrem Wohnort?», Basel-Stadt, 2019",
		"lesehilfe": "85,9% der 2019 Befragten sind mit den Grünanlagen und Parks an ihrem Wohnort eher bis sehr zufrieden.",
		"erlaeuterungen": "Alle vier Jahre wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt. Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit Grünanlagen und Parks am Wohnort",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.06251",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 5-1",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Die Wohn- und Wohnumfeldqualitäten steigern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:39",
		"id": 6251
	},
	{
		"template": "befragungen001_print",
		"data-id": 6252,
		"chart-id": 6252,
		"filter": "",
		"parentId": "5821",
		"children": [],
		"title": "Bewertung der Lebensqualität",
		"subtitle": "«Wie würden Sie die Lebensqualität im Kanton Basel-Stadt insgesamt bewerten?», Basel-Stadt",
		"lesehilfe": "Auf einer 10er-Skala konnten die befragten Personen die Lebensqualität im Kanton Basel-Stadt bewerten. 2019 geben die Befragten der Lebensqualität im Stadtkanton im Durchschnitt eine 8,0. Dies entspricht dem höchsten Wert seit der ersten Befragung im Jahr 2003.",
		"erlaeuterungen": "Alle vier Jahre wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt.<br>Um die Daten über die Jahre zu vergleichen, bleiben die befragten Personen, welche die Frage mit «Weiss nicht» oder gar nicht beantwortet haben, unberücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bewertung der Lebensqualität",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.06252",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 5-2",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Die Wohn- und Wohnumfeldqualitäten steigern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:39",
		"id": 6252
	},
	{
		"template": "befragungen001_print",
		"data-id": 6253,
		"chart-id": 6253,
		"filter": "",
		"parentId": "5822",
		"children": [],
		"title": "Anteil Einwohner pro ÖV-Güteklasse",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Fast zwei Drittel der Einwohner in Basel-Stadt wohnen in einem Gebiet der ÖV-Güteklasse A und damit in einer Zone mit sehr guter Anbindung an den öffentlichen Verkehr, rund 32% in einem Gebiet der Güteklasse B. Die Anteile haben sich zwischen 2019 und 2020 kaum verändert.",
		"erlaeuterungen": "Die ÖV-Güteklassen sind ein Mass für die räumliche Erschliessungsqualität durch den öffentlichen Verkehr. Die Güteklassen werden zweistufig bestimmt: Die Art der Verkehrsmittel und das Kursintervall weisen jeder Haltestelle eine bestimmte Kategorie zu. Die Haltestellenkategorie in Verbindung mit der Distanz des Wohnorts einer Person zur Haltestelle ergibt dann die ÖV-Güteklasse für eine bestimmte Person.",
		"quellenangabe": [
			"Amt für Mobilität Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://map.geo.bs.ch/main/wsgi/file_proxy/GO_GueteklassenOeV/Definition_Gueteklassen_oeffentlicher_Verkehr.pdf' target = '_blank'>Definition der Güteklassen des öffentlichen Verkehrs</a>",
			"<a href = 'https://map.geo.bs.ch/ngeodesktop?lang=de&baselayer_ref=Grundkarte%20grau&map_x=2612508&map_y=1267331&map_zoom=2&tree_group_layers_G%C3%BCteklassen%20%C3%B6ffentlicher%20Verkehr=GO_GueteklassenOeV&tree_groups=Liniennetz%20%C3%B6ffentlicher%20Verkehr&tree_group_layers_Liniennetz%20%C3%B6ffentlicher%20Verkehr=GO_GueteklassenOeV' target = '_blank'>Karte der Güteklassen des öffentlichen Verkehrs</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil Einwohner pro ÖV-Güteklasse",
		"thema": "11 Verkehr",
		"unterthema": "Öffentlicher Verkehr",
		"kuerzel": "I.11.2.06253",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 6-1",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 6: Die Siedlungsentwicklung und stadtgerechte Mobilität aufeinander abstimmen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_06_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:42",
		"id": 6253
	},
	{
		"template": "line001_print",
		"data-id": 6254,
		"chart-id": 6254,
		"filter": "",
		"parentId": "5823",
		"children": [],
		"title": "Beschäftigtendichte",
		"subtitle": "Anzahl Beschäftigte in Vollzeitäquivalenten pro Hektar, Basel-Stadt",
		"lesehilfe": "Im Kanton Basel-Stadt arbeiteten 2019 in Vollzeitäquivalente (VZÄ) umgerechnet rund 152 462 Beschäftigte. Das entspricht einer Beschäftigtendichte von 42,5 Beschäftigten (VZÄ) pro Hektar.",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und dafür einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Beschäftigung in Vollzeitäquivalenten (VZÄ) resultiert aus der Umrechnung des Arbeitsvolumens sämtlicher Voll- und Teilzeitbeschäftigten in Vollzeitbeschäftigte mittels Schätzmodell (basierend auf Lohnangaben der AHV und Informationen weiterer Erhebungen).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beschäftigtendichte",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.06254",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 7-2",
		"stufe1": "Sachgebiet Siedlung - Wirtschaft",
		"stufe2": "Strategie 7: Das Nutzungspotenzial der Wirtschaftsflächen vergrössern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_07_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:43",
		"id": 6254
	},
	{
		"template": "mappie001_print",
		"data-id": 6255,
		"chart-id": 6255,
		"filter": "",
		"parentId": "5825",
		"children": [],
		"title": "Bruttogeschossfläche Arbeiten nach Wohnviertel",
		"subtitle": "in m<sup>2</sup>, Basel-Stadt, 2020",
		"lesehilfe": "Die meiste für Arbeiten genutzte Bruttogeschossfläche (BGF) findet man im Jahr 2020 in den Wohnvierteln St. Alban und St. Johann.  Der Rückgang im Wohnviertel St. Johann geht mit einer gleichzeitigen Zunahme der BGF Wohnen einher. Grund dafür waren Neubau-Projekte wie Volta West, Volta Mitte und Volta Zentrum sowie Umnutzungen generell. Bezogen auf die Anteile BGF Arbeiten an der gesamten BGF betrachtet sind es die Wohnviertel Altstadt Grossbasel und Kleinhüningen mit den höchsten Werte.",
		"erlaeuterungen": "Die Daten zur Bruttogeschossfläche (BGF) wurden bis 2020 fünfjährlich aktualisiert. Die Erhebungsmethodik wurde im Rahmen der Berechnung der Daten für das Jahr 2020 überarbeitet. Ab 2020 werden die Daten jährlich aktualisiert. Die Bruttogeschossfläche ist die Summe der Grundflächen der ober- und unterirdischen Geschosse von Gebäuden, welche zum Wohnen oder Arbeiten genutzt werden können. Für das Jahr 2000 stehen keine Daten zur Verfügung.",
		"quellenangabe": [
			"Planungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bruttogeschossfläche Arbeiten nach Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.06255",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 7-3",
		"stufe1": "Sachgebiet Siedlung - Wirtschaft",
		"stufe2": "Strategie 7: Das Nutzungspotenzial der Wirtschaftsflächen vergrössern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_07_00_00_00_003",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:44",
		"id": 6255
	},
	{
		"template": "line001_print",
		"data-id": 6256,
		"chart-id": 6256,
		"filter": "",
		"parentId": "5891",
		"children": [],
		"title": "Kontinentale Erreichbarkeit",
		"subtitle": "Stadt Basel im nationalen Vergleich",
		"lesehilfe": "Durch die Reiseeinschränkungen, die 2020 als Massnahmen zur Bekämpfung der COVID-19-Pandemie ergriffen wurden, hat sich die kontinentale Erreichbarkeit der Schweizer Städte, sowie der europäischen Regionen allgemein, markant verschlechtert. Der Erreichbarkeitsindex ist 2020 gegenüber 2018 stark zurückgegangen (in Basel z. B. von 133 auf 107) und ist tiefer als vor 20 Jahren. Am stärksten war die Auswirkung der Einschränkungen im Flugverkehr.",
		"erlaeuterungen": "Kontinentale Erreichbarkeit = Erreichbarkeit aller Regionen Europas. Bei der Kennzahl handelt es sich um einen indexierten Wert: 100 = Mittel aller einbezogenen Ursprungsregionen im Jahr 2002. Erreichbarkeit ist kein klares, lineares Konzept. Vielmehr beruht es auf einer Vielzahl von Faktoren, die unter dem Themenbereich Erreichbarkeit subsumiert werden können. Die Erreichbarkeitsmodelle von BAK Economics basieren auf dem Ansatz aktivitätsbasierter Gravitationsindikatoren. Zudem folgen sie dem Konzept der Erreichbarkeit «aus der Region» (outbound accessibility), das heisst es werden Reisezeit und Frequenz herangezogen, die benötigt werden, um aus der Region andere Regionen zu erreichen. Der resultierende Indikator reflektiert das gesamte Potenzial aller Regionen ohne jegliche Limitierung der Reisezeit; die Reisedestinationen werden jedoch über die Reisezeit und das Bruttoinlandprodukt der Region gewichtet.",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [
			"Weiterführende Informationen <a href = 'https://www.bak-economics.com/en/solutions/regional-analysis/region-international/location-factors/erreichbarkeit/' target = '_blank'>BAK Economics</a>, und",
			"<a href = 'http://www.mobilitaet.bs.ch/gesamtverkehr/verkehrskennzahlen/erreichbarkeit.html' target = '_blank'>Amt für Mobilität</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Kontinentale Erreichbarkeit",
		"thema": "11 Verkehr",
		"unterthema": "Mobilitätsverhalten",
		"kuerzel": "I.11.6.06256",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 8-1",
		"stufe1": "Sachgebiet Siedlung - Wirtschaft",
		"stufe2": "Strategie 8: Bedingugen für Wirtschaft und Bildung verbessern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_08_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:45",
		"id": 6256
	},
	{
		"template": "line001_print",
		"data-id": 6257,
		"chart-id": 6257,
		"filter": "",
		"parentId": "5901",
		"children": [],
		"title": "Bevölkerungs- und Beschäftigtenentwicklung",
		"subtitle": "indexiert (Basis 2011 = 100), Basel-Stadt",
		"lesehilfe": "Die Wohnbevölkerung ist im Kanton Basel-Stadt zwischen 2011 und 2019 von 192 076 auf 200 407 gestiegen, was einem Anstieg von etwa 4,3% entspricht. Die Zahl der Beschäftigten stieg im gleichen Zeitraum um 5,1% von 183 183 auf 192 450.",
		"erlaeuterungen": "Es ist jeweils der Bevölkerungsbestand Ende Jahr abgebildet. Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und dafür einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Referenzperiode ist jeweils der Dezember des Jahres.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bevölkerungs- und Beschäftigtenentwicklung",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.06257",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 4-11",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 4: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:34",
		"id": 6257
	},
	{
		"template": "line001_print",
		"data-id": 6258,
		"chart-id": 6258,
		"filter": "",
		"parentId": "6154",
		"children": [],
		"title": "Verkehrsleistungsindex",
		"subtitle": "indexiert (Basis 2010 = 100), Basel-Stadt",
		"lesehilfe": "Im Jahr 2020, dem ersten Jahr der COVID-19-Pandemie, kam es bei sämtlichen Verkehrsmitteln zu einem Rückgang. Am stärksten ist dieser beim öffentlichen Verkehr mit 35,4 Indexpunkten. Einzig der Veloverkehr blieb mehr oder weniger stabil (-3,1 Indexpunkte). 2019 lag die Fahrleistung des motorisierten Individualverkehrs (MIV Total) auf dem Stadtstrassennetz um 7,7% tiefer, diejenige des Veloverkehrs um 45% höher als 2010.",
		"erlaeuterungen": "Der Verkehrsleistungsindex erfasst die Veränderung der Fahrleistung der verschiedenen Verkehrsmittel im ganzen Kantonsgebiet. Es wird die Veränderung gegenüber dem Referenzjahr 2010 dargestellt (indexiert, 2010 = 100). Bei den Fussgängerdaten ist das Referenzjahr 2013, da diese erst seit dann erhoben werden. Weiterführende Informationen: <a href='https://www.mobilitaet.bs.ch/gesamtverkehr/verkehrskennzahlen/verkehrsindex.html' target=\"_blank\">Amt für Mobilität Basel-Stadt</a>",
		"quellenangabe": [
			"Amt für Mobilität Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Verkehrsleistungsindex",
		"thema": "11 Verkehr",
		"unterthema": "Mobilitätsverhalten",
		"kuerzel": "I.11.6.06258",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 11-1",
		"stufe1": "Sachgebiet Mobilität",
		"stufe2": "Strategie 11: Vereinbarkeit von Mobilität, urbaner Wohnqualität und Wirtschaftsstandort",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_11_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:30",
		"id": 6258
	},
	{
		"template": "template001_print",
		"data-id": 6259,
		"chart-id": 6259,
		"filter": "",
		"parentId": "6214",
		"children": [],
		"title": "Bevölkerung am Jahresende und Anzahl Wohnungen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Wohnbevölkerung in Basel-Stadt liegt 2021 mit rund 202 000 Personen tiefer als noch 1960 (222 500 Personen). Demgegenüber steht ein Anstieg der Anzahl Wohnungen auf rund 113 500 Wohnungen (+35 000) über denselben Zeitraum. Die Bevölkerungszahl erreichte 1970 einen Höchststand von 236 219 Personen und sank bis 2001 auf 187 489. Seither wird bis 2020 eine kontinuierliche Zunahme registriert.",
		"erlaeuterungen": "Bis 2012 wurde die Bevölkerungszahl ermittelt, indem der Vormonatsbestand durch die Berücksichtigung natürlicher und räumlicher Ereignisse fortgeschrieben wurde. Seit 2013 basiert die Bevölkerungsstatistik direkt auf Auswertungen aus dem kantonalen Einwohnerregister.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bevölkerung am Jahresende und Anzahl Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.06259",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 4-1",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 4: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:33",
		"id": 6259
	},
	{
		"template": "template001_print",
		"data-id": 6260,
		"chart-id": 6260,
		"filter": "",
		"parentId": "6215",
		"children": [],
		"title": "Wohnbevölkerung gemäss Bevölkerungsszenarien",
		"subtitle": "Bevölkerungsszenarien Basel-Stadt, 2022",
		"lesehilfe": "Bis zum Jahr 2045 erhöht sich die kantonale Wohnbevölkerung im Mittleren Szenario von 202 000 am Ende des Jahres 2021 um 10% auf rund 222 000 Einwohner.",
		"erlaeuterungen": "Resultat der Bevölkerungsszenarien 2022. Bevölkerungsbestand am Jahresende. Die Bevölkerungszahl setzt sich zusammen aus der ständigen und nichtständigen Wohnbevölkerung und Personen am Nebenwohnsitz.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsszenarien"
		],
		"externalLinks": [
			"Detaillierte Informationen zu den Bevölkerungsszenarien und der angewandten Methodik finden Sie auf der <a href = 'https://www.statistik.bs.ch/analysen-berichte/gesellschaft-soziales/bevoelkerungsszenarien.html' target = '_blank'>Internetseite zu den Bevölkerungsszenarien</a>."
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnbevölkerung gemäss Bevölkerungsszenarien",
		"thema": "01 Bevölkerung",
		"unterthema": "Szenarien",
		"kuerzel": "I.01.9.06260",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 4-4",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 4: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:36",
		"id": 6260
	},
	{
		"template": "befragungen001_print",
		"data-id": 6261,
		"chart-id": 6261,
		"filter": "",
		"parentId": "5178",
		"children": [],
		"title": "Zufriedenheit mit verschiedenen Aspekten am Wohnort, Teil 1",
		"subtitle": "«Wie zufrieden sind Sie mit den folgenden Aspekten an Ihrem Wohnort?», Basel-Stadt, 2019",
		"lesehilfe": "Die befragten Personen konnten 22 Punkte, die für den Wohnort wichtig sind, bewerten (siehe auch Teil 2 des Indikators). Am zufriedensten (70,5% «sehr» und 21,7% «eher zufrieden») sind sie 2019 mit dem öffentlichen Verkehr, gefolgt von der generellen Vielfalt der Einkaufsmöglichkeiten in Basel und der Abfallbeseitigung.",
		"erlaeuterungen": "Alle vier Jahre wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt. Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit verschiedenen Aspekten am Wohnort, Teil 1",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.06261",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 5-3a",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Die Wohn- und Wohnumfeldqualitäten steigern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:40",
		"id": 6261
	},
	{
		"template": "line001_print",
		"data-id": 6262,
		"chart-id": 6262,
		"filter": "",
		"parentId": "6217",
		"children": [],
		"title": "Leerstehende Geschäftsflächen",
		"subtitle": "in Quadratmetern, Basel-Stadt",
		"lesehilfe": "Im Jahr 2021 beträgt die leerstehende Fläche insgesamt rund 185 000 m², was einem neuen Höchtsstand entspricht. Die Büroflächen machen mit rund 121 000 m² fast zwei Drittel der leerstehenden Geschäftsflächen aus.",
		"erlaeuterungen": "Die Erhebung wird vom Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel durchgeführt. Stichtag ist der 1. Juni.",
		"quellenangabe": [
			"Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerstehende Geschäftsflächen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.06262",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 7-4",
		"stufe1": "Sachgebiet Siedlung - Wirtschaft",
		"stufe2": "Strategie 7: Das Nutzungspotenzial der Wirtschaftsflächen vergrössern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_07_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:44",
		"id": 6262
	},
	{
		"template": "template001_print",
		"data-id": 6263,
		"chart-id": 6263,
		"filter": "",
		"parentId": "6218",
		"children": [],
		"title": "Bevölkerung ab 15 Jahren nach Ausbildungsniveau",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Seit 1990 hat sich der Anteil der Personen mit einer Ausbildung auf Tertiärstufe kontinuierlich erhöht. 2020 beträgt dieser Anteil 47%. Rund 33% der baselstädtischen Wohnbevölkerung besitzen eine höchste abgeschlossene Ausbildung auf Niveau Sekundarstufe II und 20% auf Niveau Sekundarstufe I.",
		"erlaeuterungen": "Die Sekundarstufe I umfasst Ausbildungen bis maximal der obligatorischen Schule. Unter Sekundarstufe II ist die berufliche Grundbildung, z. B. eine Berufslehre, sowie die allgemeinbildende Schule, z. B. die gymnasiale Maturität, zusammengefasst. Die Tertiärstufe umfasst die höhere Berufsbildung, z. B. eine höhere Fachschule für Technik oder Wirtschaft sowie Ausbildungen an Hochschulen, wie z. B. ein Bachelor- oder Masterstudium. Bis 2000 stammen die Daten aus der Eidgenössischen Volkszählung (Vollerhebung), seit 2010 aus der Strukturerhebung (Hochrechnungen aufgrund einer Stichprobenerhebung). Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Da die Frage zur höchsten abgeschlossenen Ausbildung im Fragebogen der Strukturerhebung 2020 verändert wurde, ist die Veränderung zwischen 2020 und den Vorjahren mit Vorsicht zu interpretieren.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)",
			"Bundesamt für Statistik (BFS), Volkszählung (VZ)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bevölkerung ab 15 Jahren nach Ausbildungsniveau",
		"thema": "15 Bildung",
		"unterthema": "Bildungsniveau",
		"kuerzel": "I.15.6.06263",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 8-2",
		"stufe1": "Sachgebiet Siedlung - Wirtschaft",
		"stufe2": "Strategie 8: Bedingugen für Wirtschaft und Bildung verbessern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_08_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:45",
		"id": 6263
	},
	{
		"template": "line001_print",
		"data-id": 6264,
		"chart-id": 6264,
		"filter": "",
		"parentId": "6220",
		"children": [],
		"title": "Haushalte in Begegnungszonen",
		"subtitle": "indexiert (2011 = 100), Basel",
		"lesehilfe": "Die Anzahl Privathaushalte in Begegnungszonen ist von 2011 bis 2019 prozentual stärker angestiegen als das Total der Privathaushalte in der Stadt Basel. Dies ist in erster Linie auf die Ausweitung der Begegnungszonen zurückzuführen. Ende 2019 gibt es 8 080 Privathaushalte in Begegnungszonen.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Planungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Haushalte in Begegnungszonen",
		"thema": "01 Bevölkerung",
		"unterthema": "Haushalte",
		"kuerzel": "I.01.2.06264",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 5-4",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Die Wohn- und Wohnumfeldqualitäten steigern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:41",
		"id": 6264
	},
	{
		"template": "template001_print",
		"data-id": 6265,
		"chart-id": 6265,
		"filter": "",
		"parentId": "6236",
		"children": [],
		"title": "Anzahl Beschäftigte nach Branche",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2019 sind in Basel-Stadt 192 450 Personen beschäftigt. Das sind 1 988 Personen mehr als im Vorjahr. Die grösste Beschäftigungszunahme verzeichnet die Branchengruppe Unternehmensdienstleistungen und Freiberufe, während bei der Pharmaindustrie mit 382 Beschäftigten weniger die grösste Abnahme zu beobachten ist",
		"erlaeuterungen": "«Unternehmens-DL, Freiberufe» umfasst: Erbringung von freiberuflichen, wissenschaftlichen und technischen Dienstleistungen, Erbringung von sonstigen wirtschaftlichen Dienstleistungen; «Übrige Branchen» umfasst: Land- und Forstwirtschaft, Fischerei, Bergbau und Gewinnung von Steinen und Erden, Beherbergung und Gastronomie, Information und Kommunikation, Grundstücks- und Wohnungswesen, Kunst, Unterhaltung und Erholung, sonstige Dienstleistungen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Beschäftigte nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.06265",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 7-1",
		"stufe1": "Sachgebiet Siedlung - Wirtschaft",
		"stufe2": "Strategie 7: Das Nutzungspotenzial der Wirtschaftsflächen vergrössern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_07_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:43",
		"id": 6265
	},
	{
		"template": "stock001_print",
		"data-id": 8417,
		"chart-id": 8417,
		"filter": "",
		"parentId": "4132",
		"children": [],
		"title": "Bevölkerungsbestand am Jahresende",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Zwischen dem 31.12.2011 und dem 31.12.2021 nahm die Bevölkerung im Kanton Basel-Stadt von 192 304 auf 201 805 Personen zu.",
		"erlaeuterungen": "Angaben zur Erhebung der Bevölkerungszahlen: 1774-1847: Kantonale Volkszählungen; 1850-1900: Eidgenössische Volkszählungen; 1901-2011: Fortschreibung der kantonalen Bevölkerungsstatistik; ab 2012: Auswertungen aus dem kantonalen Einwohnerregister.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [
			"Weitere Informationen zur Bevölkerungsstatistik finden Sie auf der Seite <a href = 'https://www.statistik.bs.ch/haeufig-gefragt/einwohner/zentrale-begriffe-einwohner.html' target = '_blank'>Einwohner&nbsp;-&nbsp;Zentrale Begriffe</a>."
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bevölkerungsbestand am Jahresende",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08417",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 1-1",
		"stufe1": "Querschnittsthemen",
		"stufe2": "Strategie 1: Regionale Sichtweise",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:29",
		"id": 8417
	},
	{
		"template": "line001_print",
		"data-id": 8418,
		"chart-id": 8418,
		"filter": "",
		"parentId": "7774",
		"children": [],
		"title": "Bruttogeschossflächen Wohnen und Arbeiten",
		"subtitle": "in m<sup>2</sup>, Basel-Stadt",
		"lesehilfe": "Sowohl die für Wohn- als auch die für Arbeitszwecke genutzte Bruttogeschossfläche hat seit 1995 zugenommen. Dies ist auf die Bautätigkeit im Kanton zurückzuführen.",
		"erlaeuterungen": "Die Daten zur Bruttogeschossfläche (BGF) wurden bis 2020 fünfjährlich aktualisiert. Die Erhebungsmethodik wurde im Rahmen der Berechnung der Daten für das Jahr 2020 überarbeitet und sind damit nicht direkt vergleichbar mit den Vorjahren. Ab 2020 werden die Daten jährlich aktualisiert. Die Bruttogeschossfläche ist die Summe der Grundflächen der ober- und unterirdischen Geschosse von Gebäuden, welche zum Wohnen oder Arbeiten genutzt werden können. Für das Jahr 2000 stehen keine Daten zur Verfügung.",
		"quellenangabe": [
			"Bau- und Verkehrsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bruttogeschossflächen Wohnen und Arbeiten",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.08418",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 1-2",
		"stufe1": "Querschnittsthemen",
		"stufe2": "Strategie 1: Regionale Sichtweise",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:32",
		"id": 8418
	},
	{
		"template": "template001_print",
		"data-id": 8419,
		"chart-id": 8419,
		"filter": "",
		"parentId": "7775",
		"children": [],
		"title": "Bauzonen",
		"subtitle": "indexiert (2005 = 100), Basel-Stadt",
		"lesehilfe": "Die Bauzonenfläche im Kanton Basel-Stadt ist 2021 im Vergleich zu 2005 um 0,08 Indexpunkte kleiner. Die Fläche der Bauzonen mit potenzieller Wohnnutzung liegt bei 100,91 Indexpunkten.",
		"erlaeuterungen": "Zonen gemäss Zonenplan Basel-Stadt und Zonenplan Gemeinde Riehen (revidiert auf 1.1.2017). Bauzonen: Zonen 2 bis 7 einschliesslich 2a, 5a und Stadt- und Dorfbild-Schutz- und Schonzone sowie die Riehener Arbeitszonen und Zone 2R. Bauzonen mit potenzieller Wohnnutzung: ohne Zonen mit reiner Arbeitsnutzung (Basel: «Zone 7 Industrie- und Gewerbezone»; Riehen: Arbeitszonen).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Bau- und Verkehrsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"Informationen zum <a href = 'http://www.zonenplan.bs.ch/' target = '_blank'>Zonenplan Basel-Stadt</a>",
			"Zonenpläne Basel-Stadt, Riehen und Bettingen als Karten auf <a href = 'https://map.geo.bs.ch/s/h97S' target = '_blank'>MapBS</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bauzonen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.08419",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 1-3",
		"stufe1": "Querschnittsthemen",
		"stufe2": "Strategie 1: Regionale Sichtweise",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:32",
		"id": 8419
	},
	{
		"template": "line001_print",
		"data-id": 8420,
		"chart-id": 8420,
		"filter": "",
		"parentId": "7777",
		"children": [],
		"title": "Jährlich durch Stau generierte Verzögerungszeit",
		"subtitle": "Stadt Basel im Vergleich mit ausgewählten Schweizer Städten",
		"lesehilfe": "Die Verzögerungszeit für den motorisierten Individualverkehr betrug in der Stadt Basel im Jahr 2020 rund 22%. Das bedeutet, dass eine durchschnittliche Reise 22% länger dauerte, als dies unter staufreien Bedingungen der Fall gewesen wäre. In allen betrachteten Städten ist ein Rückgang gegenüber 2019 zu beobachten. Dies dürfte zumindest teilweise mit der verringerten Mobilität aufgrund der Pandemie zusammenhängen.",
		"erlaeuterungen": "Die Zahlen basieren auf gesammelten Verkehrsdaten des Navigationsgeräte-Herstellers TomTom. Damit die urbanen Flächen, für die der Index berechnet wird, international vergleichbar sind, wurden sie von TomTom individuell definiert.",
		"quellenangabe": [
			"TomTom International"
		],
		"externalLinks": [
			"Detaillierte Informationen zu den TomTom Staudaten und der angewandten Methodik sind hier zu finden: <a href = 'https://www.tomtom.com/en_gb/traffic-index/about' target = '_blank'>TomTom Traffic Index</a>.",
			"Die Werte für <a href = 'https://www.tomtom.com/en_gb/trafficindex/city/basel' target = '_blank'>Basel</a>;",
			"die Werte für <a href = 'https://www.tomtom.com/en_gb/trafficindex/city/GNV' target = '_blank'>Genf</a>;",
			"die Werte für <a href = 'https://www.tomtom.com/en_gb/trafficindex/city/ZUR' target = '_blank'>Zürich</a>;",
			"die Werte für <a href = 'https://www.tomtom.com/en_gb/trafficindex/city/bern' target = '_blank'>Bern</a>."
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Jährlich durch Stau generierte Verzögerungszeit",
		"thema": "11 Verkehr",
		"unterthema": "Mobilitätsverhalten",
		"kuerzel": "I.11.6.08420",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 11-2",
		"stufe1": "Sachgebiet Mobilität",
		"stufe2": "Strategie 11: Vereinbarkeit von Mobilität, urbaner Wohnqualität und Wirtschaftsstandort",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_11_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:30",
		"id": 8420
	},
	{
		"template": "line001_print",
		"data-id": 8421,
		"chart-id": 8421,
		"filter": "",
		"parentId": "7778",
		"children": [],
		"title": "Warentransit durch die Schweiz",
		"subtitle": "mit Eingang oder Ausgang Region Basel, in Tonnen, nach Verkehrsträger",
		"lesehilfe": "Der Transit durch die Region Basel nimmt auf der Strasse seit 2010 kontinuierlich ab.",
		"erlaeuterungen": "Berücksichtigt sind Waren, welche auf ihrem Weg vom Ursprungs- zum Zielland die Schweiz durchqueren und dabei in der Region Basel die Landesgrenze (resp. ein Zollamt) passieren. «Eingang» bezeichnet dabei Waren, welche die Grenze in Richtung Schweiz überqueren, «Ausgang» solche, die in Richtung Ausland transportiert werden. Die Region Basel besteht aus den Zollzonen Basel rechts, Basel links, Flughafen und Rheinhafen BS/BL. Über Pipelines verlassen in der Region Basel keine Waren die Schweiz.",
		"quellenangabe": [
			"Eidgenössische Zollverwaltung (EZV)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Warentransit durch die Schweiz",
		"thema": "06 Industrie, Dienstleistungen",
		"unterthema": "Aussenhandel",
		"kuerzel": "I.06.4.08421",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 11-3",
		"stufe1": "Sachgebiet Mobilität",
		"stufe2": "Strategie 11: Vereinbarkeit von Mobilität, urbaner Wohnqualität und Wirtschaftsstandort",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_11_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:31",
		"id": 8421
	},
	{
		"template": "line001_print",
		"data-id": 8422,
		"chart-id": 8422,
		"filter": "",
		"parentId": "7779",
		"children": [],
		"title": "Motorisierungsgrad",
		"subtitle": "Personenwagen pro 1000 Einwohner, Basel-Stadt",
		"lesehilfe": "Seit dem Höchststand von 332 Personenwagen pro 1000 Einwohnerinnen und Einwohner im Jahr 2004 ist eine leicht abnehmende Tendenz zu beobachten. Aktuell beträgt der Motorisierungsgrad 307 Personenwagen pro 1000 Einwohner.",
		"erlaeuterungen": "Der Motorisierungsgrad zeigt das Verhältnis zwischen Fahrzeugbestand und mittlerer kantonaler Wohnbevölkerung.",
		"quellenangabe": [
			"Kantonspolizei Basel-Stadt, Motorfahrzeugkontrolle; Statistisches Amt Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'http://www.polizei.bs.ch/verkehr/motorfahrzeugkontrolle.html' target = '_blank'>Motorfahrzeugkontrolle Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Motorisierungsgrad",
		"thema": "11 Verkehr",
		"unterthema": "Motorfahrzeuge",
		"kuerzel": "I.11.1.08422",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 11-4",
		"stufe1": "Sachgebiet Mobilität",
		"stufe2": "Strategie 11: Vereinbarkeit von Mobilität, urbaner Wohnqualität und Wirtschaftsstandort",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_11_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:31",
		"id": 8422
	},
	{
		"template": "line001_print",
		"data-id": 8423,
		"chart-id": 8423,
		"filter": "",
		"parentId": "5196",
		"children": [],
		"title": "Mietpreisindex Basel-Stadt",
		"subtitle": "Indexwert (Basis 2000 = 100)",
		"lesehilfe": "Der Mietpreisindex zeigt insgesamt eine steigende Entwicklung von 80,4 Punkten im Jahr 1995 auf den aktuellen Wert von 100,8 im November 2021.",
		"erlaeuterungen": "Mietpreisindex: Geschichtete Zufallsstichprobe, die 5% der Miet- und Genossenschaftswohnungen mit 1 bis 6 Zimmern umfasst, welche dauerhaft zu Wohnzwecken vermietet werden. Es wird der Wert im November des jeweiligen Jahres ausgewiesen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Mietpreiserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mietpreisindex Basel-Stadt",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Mietpreise",
		"kuerzel": "I.09.3.08423",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 5-5",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Die Wohn- und Wohnumfeldqualitäten steigern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:42",
		"id": 8423
	},
	{
		"template": "befragungen001_print",
		"data-id": 8971,
		"chart-id": 8971,
		"filter": "",
		"parentId": "8852",
		"children": [],
		"title": "Zufriedenheit mit verschiedenen Aspekten am Wohnort, Teil 2",
		"subtitle": "«Wie zufrieden sind Sie mit den folgenden Aspekten an Ihrem Wohnort?» Stand: 2019",
		"lesehilfe": "Die befragten Personen konnten 22 Punkte, die für den Wohnort wichtig sind, bewerten (siehe auch Teil 1 des Indikators). Die tiefsten Zufriedenheitswerte haben die Kinderbetreuung (17,7% «sehr» und 21,8% «eher zufrieden») und die Einrichtungen für Jugendliche (12,1% «sehr» und 29,5% «eher zufrieden») erhalten. Bei diesen Faktoren liegt der Anteil «Weiss nicht» allerdings bei über 40%. Beim Wohnungsangebot ist der Anteil der Zufriedenen («sehr» und «eher zufrieden») 2019 etwas höher als 2015.",
		"erlaeuterungen": "Alle vier Jahre wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt. Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit verschiedenen Aspekten am Wohnort, Teil 2",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.08971",
		"kennzahlenset": "Richtplan (Print)",
		"kuerzelKunde": "ST 5-3b",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Die Wohn- und Wohnumfeldqualitäten steigern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:02:40",
		"id": 8971
	}
];