var indikatorensetData = [
	{
		"template": "template001",
		"data-id": 11899,
		"chart-id": 11899,
		"filter": "",
		"parentId": null,
		"children": [
			22305
		],
		"title": "Bevölkerungsszenarien 2025-2055, Bundesamt für Statistik",
		"subtitle": "Ständige Wohnbevölkerung, Basel-Stadt",
		"lesehilfe": "Gemäss Referenzszenario des BFS steigt die ständige Wohnbevölkerung von 200 031 Personen im Jahr 2023 auf 212 809 Personen im Jahr 2055.",
		"erlaeuterungen": "Das Referenzszenario (AR-00-2025) schreibt die im Lauf der letzten Jahrzehnte beobachteten Entwicklungen fort. Das «hohe» Szenario (BR-00-2025) kombiniert die Hypothesen, die das Bevölkerungswachstum begünstigen. Das «tiefe» Szenario (CR-00-2025) geht von Hypothesen aus, die dem Bevölkerungswachstum weniger förderlich sind.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS)"
		],
		"externalLinks": [
			"<a href = 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/zukuenftige-entwicklung/kantonale-szenarien.html' target = '_blank'>Kantonale Szenarien, Bundesamt für Statistik</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bevölkerungsszenarien 2025-2055, Bundesamt für Statistik",
		"thema": "01 Bevölkerung",
		"unterthema": "Szenarien",
		"kuerzel": "I.01.9.11899",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 1-2",
		"stufe1": "Querschnittsthemen",
		"stufe2": "Strategie 1: Regionale Sichtweise einnehmen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-27T10:03:14",
		"id": 11899
	},
	{
		"template": "template001",
		"data-id": 11900,
		"chart-id": 11900,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Kantonale Bauzonenauslastung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die kantonale Auslastungsziffer beträgt im Jahr 2024 114,3%.",
		"erlaeuterungen": "Gemäss Art. 15 des Raumplanungsgesetzes sind Bauzonen so festzulegen, dass sie dem voraussichtlichen Bedarf für 15 Jahre entsprechen. Überdimensionierte Bauzonen sind zu reduzieren. Ein wichtiger Wert bei der Beurteilung der Grösse der Bauzonen eines Kantons ist die Auslastung. Im Kanton Basel-Stadt liegt dieser Wert bei über 100%. Somit hat der Kanton nicht zu viele Bauzonen im Verhältnis zur erwarteten Bevölkerungs- und Arbeitsplatzentwicklung.",
		"quellenangabe": [
			"Städtebau & Architektur Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Kantonale Bauzonenauslastung",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 1-5",
		"stufe1": "Querschnittsthemen",
		"stufe2": "Strategie 1: Regionale Sichtweise einnehmen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-26T02:51:15",
		"id": 11900
	},
	{
		"template": "template001",
		"data-id": 11901,
		"chart-id": 6165,
		"filter": "",
		"parentId": "6165",
		"children": [],
		"title": "Treibhausgas-Emissionen",
		"subtitle": "in Tonnen CO<sub>2</sub>-Äquivalente pro Kopf, Basel-Stadt",
		"lesehilfe": "Die direkten Treibhausgas-Emissionen auf dem Kantonsgebiet lagen 2022 bei 3,1 Tonnen CO<sub>2</sub>eq (CO<sub>2</sub>-Äquivalente) pro Kopf. Das Reduktionsziel (Netto-Null bis 2037) und der Zielpfad sind in der <a href='https://www.pd.bs.ch/ueber-das-departement/Fachstelle-Klima/Klimapolitik/Klimaschutzstrategie-Kanton-Basel-Stadt--Netto-Null-bis-2037.html' target='_blank'>Klimaschutzstrategie Basel-Stadt</a> festgelegt.",
		"erlaeuterungen": "Direkte Emissionen (sog. Scope 1) sind CO<sub>2</sub>-Emissionen auf dem Kantonsgebiet (Territorialprinzip), die durch das Verbrennen von fossilen Energieträgern wie Heizöl, Erdgas, Benzin und Diesel sowie bei der thermischen Verwertung von Abfällen (Kehricht und Industrieabfälle) entstehen. Weitere direkte Treibhausgasemissionen (in t CO<sub>2</sub>eq) umfassen insbesondere F-Gas-Emissionen in der Industrie, Methanemissionen aus dem Erdgasverteilnetz und Lachgasemissionen aus der Abwasserreinigung.<br>Insgesamt sinken die Treibhausgasemissionen im Netto-Null-Absenkpfad um 87% im Vergleich zu 2020 und umfassen im Jahr 2037 noch 88 000 Tonnen CO<sub>2</sub>eq. Diese restlichen, schwer vermeidbaren Emissionen umfassen Emissionen aus der Mobilität, der Entsorgung und nicht-energiebedingte Emissionen. Für den Netto-Null Absenkpfad wird davon ausgegangen, dass 2037 eine Carbon Capture and Storage (CCS) Anlage zur Abscheidung von CO<sub>2</sub> an der Kehrichtverbrennungsanlage in Betrieb gehen wird, sofern dies technisch und wirtschaftlich machbar ist.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik",
			"Klimaschutzstrategie Kanton Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://www.pd.bs.ch/ueber-das-departement/Fachstelle-Klima/Klimapolitik/Klimaschutzstrategie-Kanton-Basel-Stadt--Netto-Null-bis-2037.htm' target = '_blank'>Klimaschutzstrategie Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Treibhausgas-Emissionen",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Klima",
		"kuerzel": "I.02.12.11901",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 2-1",
		"stufe1": "Querschnittsthemen",
		"stufe2": "Strategie 2: Das Klima schützen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-03-25T08:34:16",
		"id": 11901
	},
	{
		"template": "template001",
		"data-id": 11902,
		"chart-id": 9614,
		"filter": "",
		"parentId": "9614",
		"children": [],
		"title": "Bruttoenergieverbrauch erneuerbare Energieträger",
		"subtitle": "in GWh, Basel-Stadt",
		"lesehilfe": "Der Verbrauch der im Kanton Basel-Stadt erzeugten erneuerbaren Energie hat zwischen 2010 und 2022 von 741 GWh auf 1 074 GWh zugenommen, was einem Plus von 45% entspricht. Eine starke Zunahme ist beim Holz mit 130% zu verzeichnen. Dies ist auf die Inbetriebnahme des zweiten Holzheizkraftwerks zurückzuführen. Starke Zunahmen sind auch bei der Photovoltaik (+1 057%), der Umweltwärme (+152%) und der thermischen Solarenergie (+191%) zu beobachten, die 2022 zusammen einen Anteil von 9,1% an den erneuerbaren Energien ausmachen. Die Produktion von Wasserkraft ist von witterungsbedingten Wasserpegelständen abhängig und schwankt daher.",
		"erlaeuterungen": "Dieser Indikator zeigt den Bruttoenergieverbrauch der erneuerbaren Energien, die im Kanton gewonnen wurden. Der Import von erneuerbaren Energien in den Kanton, insbesondere der ausserkantonale Bezug von Elektrizität, bleibt folglich unberücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bruttoenergieverbrauch erneuerbare Energieträger",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 2-2",
		"stufe1": "Querschnittsthemen",
		"stufe2": "Strategie 2: Das Klima schützen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-21T06:59:11",
		"id": 11902
	},
	{
		"template": "stock001",
		"data-id": 11903,
		"chart-id": 6033,
		"filter": "",
		"parentId": "6033",
		"children": [],
		"title": "Hitzetage",
		"subtitle": "Anzahl Tage, Meteorologische Station Basel-Binningen",
		"lesehilfe": "Im Jahr 2024 wurden 24 Hitzetage verzeichnet. Das Maximum innerhalb des abgebildeten Zeitraumes wurde mit 43 Hitzetagen im Jahr 2003 registriert.",
		"erlaeuterungen": "Anzahl Tage im Jahr, an denen die Lufttemperatur mindestens 30 °C erreicht hat. Die Temperaturmessungen erfolgen an der meteorologischen Station Basel-Binningen in 2 m über Grund (317 m ü. M.; 47°33' N/7°35' E).",
		"quellenangabe": [
			"Meteorologischer Verein der Region Basel"
		],
		"externalLinks": [
			"Weitere Informationen zum Indikator: <a href = 'http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-08-0801' target = '_blank'>Umweltbericht beider Basel</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Hitzetage",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Klima",
		"kuerzel": "I.02.12.11903",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 3-1",
		"stufe1": "Querschnittsthemen",
		"stufe2": "Strategie 3: Dem Klimawandel begegnen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-03-25T08:34:17",
		"id": 11903
	},
	{
		"template": "template001",
		"data-id": 11905,
		"chart-id": 6574,
		"filter": "",
		"parentId": "6574",
		"children": [],
		"title": "Baumkronenbedeckung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2024 betrug die Kronenbedeckung (durch Bäume beschattete Fläche) 24,4% der gesamten Kantonsfläche und 17,2% der Stadt Basel. Schliesst man die reinen Waldflächen von der Betrachtung aus, so reduzieren sich die Anteile auf 16,5% respektive 15,1%.",
		"erlaeuterungen": "Durch flugzeuggestützte Laserabtastung der Oberfläche (LiDAR - Light Detecting And Ranging) werden Daten zur Kronenbedeckung abgeleitet. Seit 2021 finden alle drei Jahre Befliegungen statt, um die Entwicklung der Kronenbedeckung verfolgen zu können. <br>Berücksichtigt werden bei der Auswertung nur Kronen mit einer Höhe über 3 m. Die LiDAR-Methodologie wurde in den letzten Jahren verbessert. Änderungen unter 1% (zwischen 2012 und 2021) sollten nicht als reale Veränderungen betrachtet und mit Vorsicht interpretiert werden. Es gibt eine gewisse Variabilität bei Flugmethode, Flugzeitpunkt und Klassifizierungsmethode; diese befindet sich im Prozentbereich.",
		"quellenangabe": [
			"Stadtgärtnerei Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://data.bs.ch/explore/dataset/100357' target = '_blank'>OGD-Datensatz</a>",
			"<a href = 'https://tiefbauamt-bs.ch/geoviewer/kronenbedeckung' target = '_blank'>Baumkronenbedeckung als Karte</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Baumkronenbedeckung",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Landschaft",
		"kuerzel": "I.02.13.11905",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 3-2",
		"stufe1": "Querschnittsthemen",
		"stufe2": "Strategie 3: Dem Klimawandel begegnen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-20T08:24:58",
		"id": 11905
	},
	{
		"template": "template001",
		"data-id": 11906,
		"chart-id": 9390,
		"filter": "",
		"parentId": "9390",
		"children": [],
		"title": "Tropennächte",
		"subtitle": "Anzahl Nächte, Basel-Stadt",
		"lesehilfe": "Im Jahr 2024 wurden an der Messstation St. Johann im Stadtzentrum von Basel 23 Tropennächte registriert, während an der vorstädtischen Station Basel-Binningen nur 2 Tropennächte verzeichnet wurden.",
		"erlaeuterungen": "Tropennächte sind Nächte, in denen die Temperatur nicht unter 20 °C sinkt. Die Temperaturmessungen erfolgen an verschiedenen Messstationen in der Region Basel. Gewisse Abweichungen zu den validierten MeteoSchweiz-Daten aufgrund unterschiedlicher Methodik sind möglich. Infolge der unterschiedlichen Lagen der Messstationen ist auch die Anzahl Tropennächte verschieden stark ausgeprägt. Im innenstädtischen Umfeld mit schlechter Durchlüftung und dichter Bebauung ist die thermische Belastung nachts besonders hoch, wohingegen in vorstädtischer Lage (offene Bebauung) oder bei viel Vegetation (Kühlung durch Verdunstung) die nächtliche Abkühlung besser erfolgen kann.",
		"quellenangabe": [
			"Universität Basel",
			"Lufthygieneamt beider Basel",
			"Meteorologischer Verein der Region Basel",
			"MeteoSchweiz"
		],
		"externalLinks": [
			"Weitere Informationen zum Indikator und den einzelnen Messstationen: <a href = 'https://www.bs.ch/schwerpunkte/umweltbericht-beider-basel/indikatoren-uebersicht/indikator-0815' target = '_blank'>Umweltbericht beider Basel</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Tropennächte",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Klima",
		"kuerzel": "I.02.12.11906",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 3-3",
		"stufe1": "Querschnittsthemen",
		"stufe2": "Strategie 3: Dem Klimawandel begegnen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-21T02:31:52",
		"id": 11906
	},
	{
		"template": "template001",
		"data-id": 11907,
		"chart-id": 11907,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Lärmbelastete Personen",
		"subtitle": "Anteil an der Gesamtbevölkerung in Prozent, Basel-Stadt",
		"lesehilfe": "11,7% der im Kanton Basel-Stadt wohnhaften Personen gelten 2021 als tagsüber lärmbelastet, da der Grenzwert für Strassenlärm an ihrem Gebäude überschritten wird. Von Überschreitungen des Nacht-Grenzwertes sind 20,5% betroffen.",
		"erlaeuterungen": "Anteil Personen, die in Gebäuden wohnen, bei welchen die Immissionsgrenzwerte für Strassenverkehrslärm der schweizerischen Lärmschutz-Verordnung (LSV) überschritten werden. Die angegebenen Werte beruhen auf Modellierungen. Die Lärmimmission an den Gebäuden werden in einem 3D-Oberflächenmodell (Gelände, Gebäude, Hindernisse) auf Basis des Emissionskatasters für Strassenverkehrslärm berechnet. Sobald ein Teil eines Gebäudes, z. B. eine Fassade oder die oberen Geschosse, welche nicht durch eine Lärmschutzwand geschützt werden, von Grenzwertüberschreitungen (gemäss LSV) betroffen sind, werden sämtliche Bewohner des Gebäudes als lärmbelastete Personen gezählt. Die Ausrichtung der einzelnen Wohnungen fliesst nicht in die Beurteilung ein. Weiter werden lärmempfindliche Räume in Betrieben nicht berücksichtigt.",
		"quellenangabe": [
			"Amt für Umwelt und Energie Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Lärmbelastete Personen",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 6-6",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 6: Die Wohn- und Wohnumfeldqualitäten steigern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_06_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-26T02:51:32",
		"id": 11907
	},
	{
		"template": "template001",
		"data-id": 11908,
		"chart-id": 11908,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Langzeitbelastungsindex",
		"subtitle": "Basel-Stadt und Umgebung",
		"lesehilfe": "Der Langzeitbelastungsindex für die Stadt Basel lag 2024 bei 2,3. Er liegt damit höher als in der Agglomeration, wo er 1,9 beträgt.",
		"erlaeuterungen": "Der Langzeitbelastungsindex (LBI) ist ein Mischindex zur Luftbelastung, der den Auswirkungen auf die menschliche Gesundheit durch die chronische Einwirkung von verschmutzter Luft Rechnung trägt. Er kann Werte von 1 (gering) bis 6 (sehr hoch) annehmen. Der LBI wird auf Basis der jährlichen Werte der Konzentrationen der drei Schadstoffe Feinstaub (PM10), Stickstoffdioxid (NO<sub>2</sub>) und Ozon (O<sub>3</sub>) berechnet. Die Konzentrationen dieser drei Schadstoffe werden in Bezug zu den Immissionsgrenzwerten der Luftreinhalte-Verordnung (LRV) gesetzt. Die sich daraus ergebenden Werte werden zusätzlich aufgrund der unterschiedlichen chronischen gesundheitlichen Auswirkungen dieser Schadstoffe gewichtet (4,5 für PM10, 4,5 für NO<sub>2</sub>, 1 für O<sub>3</sub>). Die Berechnung des LBI ist in der Empfehlung Nr. 27 der Schweizerischen Gesellschaft der Lufthygiene-Fachleute (Cercl'Air) im Detail beschrieben.",
		"quellenangabe": [
			"Lufthygieneamt beider Basel"
		],
		"externalLinks": [
			"<a href = 'https://cerclair.ch/assets/pdf/27b_2015_06_10_D_Langzeit_Luftbelastungs_Index.pdf' target = '_blank'> Empfehlung Nr. 27 der Schweizerischen Gesellschaft der Lufthygiene-Fachleute (Cercl'Air)</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Langzeitbelastungsindex",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Lärm",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 6-7",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 6: Die Wohn- und Wohnumfeldqualitäten steigern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_06_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-21T02:31:55",
		"id": 11908
	},
	{
		"template": "template001",
		"data-id": 11909,
		"chart-id": 11909,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Strukturen der Fliessgewässer",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Von 47 km Fliessstrecke werden 2025 nur knapp 2 km (4,2%)  als natürlich oder naturnah bezeichnet.",
		"erlaeuterungen": "Die Beurteilung der Struktur der Fliessgewässer erfolgt über die ökomorphologische Bewertung nach dem Modul-Stufen-Konzept, Stufe F des Bundesamtes für Umwelt. Im Kanton Basel-Stadt wird eine Fliesstrecke von insgesamt 47 km bewertet.",
		"quellenangabe": [
			"Amt für Umwelt und Energie Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'http://www.modul-stufen-konzept.ch' target = '_blank'>Modul-Stufen-Konzept des Bundesamtes für Umwelt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Strukturen der Fliessgewässer",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Verbrauch",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 10-1",
		"stufe1": "Sachgebiet Natur und Landschaft",
		"stufe2": "Strategie 10: Landschaftsräume sichern und vernetzen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_10_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-21T02:31:47",
		"id": 11909
	},
	{
		"template": "template001",
		"data-id": 11910,
		"chart-id": 11910,
		"filter": "",
		"parentId": null,
		"children": [
			22316
		],
		"title": "Revitalisierungsrate Oberflächengewässer",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Seit 2015 wurden 1,6 km der bis 2035 geplanten 9,6 km revitalisiert.",
		"erlaeuterungen": "Länge der jährlich revitalisierten Gewässerabschnitte im Vergleich zur Gesamtlänge der gemäss Revitalisierungsplanung prioritär zu revitalisierenden Gewässerstrecken. Laut Gewässerschutzgesetz sind die Kantone verpflichtet, Revitalisierungen an Gewässern durchzuführen. Im Kanton Basel-Stadt ist der Nutzen von Revitalisierungsmassnahmen an Wiese und Riehenteich (Abschnitte Neuer Teich und Mühleteich) unter Berücksichtigung des zu erwartenden Aufwands am grössten. Bis 2035 sollen 9,6 km revitalisiert werden. In den Jahren 2015 bis 2095 sollen gesamthaft rund 4 000 km der Fliessgewässer in der Schweiz revitalisiert werden.",
		"quellenangabe": [
			"Amt für Umwelt und Energie Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Revitalisierungsrate Oberflächengewässer",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Verbrauch",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 10-2",
		"stufe1": "Sachgebiet Natur und Landschaft",
		"stufe2": "Strategie 10: Landschaftsräume sichern und vernetzen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_10_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-06-05T08:30:40",
		"id": 11910
	},
	{
		"template": "template001",
		"data-id": 11911,
		"chart-id": 11911,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Waldfläche",
		"subtitle": "Anteil an der Kantonsfläche in Prozent, Basel-Stadt",
		"lesehilfe": "11,8% der Kantonsfläche waren 2014 von Wald bedeckt.",
		"erlaeuterungen": "Der Wald gemäss Arealstatistik umfasst geschlossene und aufgelöste Waldflächen, jedoch nicht Gebüschwald und Gehölze. Die Arealstatistik erhebt im Turnus von zwölf bzw. neun Jahren Informationen zur Bodennutzung und -bedeckung der Schweiz auf der Grundlage von Luftbildern des Bundesamtes für Landestopografie (Punktstichprobenerhebung im Abstand von 100 x 100 Meter; im Kanton Basel-Stadt 3 698 Punkte).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Arealstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Waldfläche",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Verbrauch",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 10-3",
		"stufe1": "Sachgebiet Natur und Landschaft",
		"stufe2": "Strategie 10: Landschaftsräume sichern und vernetzen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_10_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-21T02:31:50",
		"id": 11911
	},
	{
		"template": "template001",
		"data-id": 11912,
		"chart-id": 11912,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Kantonale Unterschutzstellungen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "0,2% der Kantonsfläche galten 2021 als geschützte Flächen.",
		"erlaeuterungen": "Zu den kantonalen Unterschutzstellungen werden Naturschutzgebiete (inkl. Waldreservate) mit effektivem Flächenschutz (grundeigentümerverbindlicher Schutz oder Schutz durch Vertrag mit dem Eigentümer) gezählt. Qualitative Veränderungen der geschützten Gebiete werden durch den Indikator nicht abgebildet.",
		"quellenangabe": [
			"Stadtgärtnerei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Kantonale Unterschutzstellungen",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 11-1",
		"stufe1": "Sachgebiet Natur und Landschaft",
		"stufe2": "Strategie 11: Wertvolle Naturräume schützen und Biodiversität stärken",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_11_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-26T02:51:06",
		"id": 11912
	},
	{
		"template": "template001",
		"data-id": 11914,
		"chart-id": 11914,
		"filter": "",
		"parentId": null,
		"children": [
			22319
		],
		"title": "Biodiversitätsförderflächen in der Landwirtschaft",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2024 sind von der gesamten Landwirtschaftlichen Nutzfläche im Kanton Basel-Stadt 21,05% Biodiversitätsförderflächen.",
		"erlaeuterungen": "Anteil der Biodiversitätsförderflächen (BFF) an der gesamten Landwirtschaftlichen Nutzfäche (LN). Qualitative Veränderungen der geschützten Gebiete werden durch den Indikator nicht abgebildet. Die Biodiversitätsförderflächen dienen dem Erhalt und der Förderung der Arten und der ökologisch wertvollen Lebensräume.",
		"quellenangabe": [
			"Stadtgärtnerei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Biodiversitätsförderflächen in der Landwirtschaft",
		"thema": "07 Landwirtschaft",
		"unterthema": "Biodiversität",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 11-2",
		"stufe1": "Sachgebiet Natur und Landschaft",
		"stufe2": "Strategie 11: Wertvolle Naturräume schützen und Biodiversität stärken",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_11_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-08-11T03:06:11",
		"id": 11914
	},
	{
		"template": "template001",
		"data-id": 11915,
		"chart-id": 11915,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Fruchtfolgeflächen",
		"subtitle": "in Hektaren, Basel-Stadt",
		"lesehilfe": "2024 sind im gesamten Kanton 249 ha Fruchtfolgeflächen ausgeschieden.",
		"erlaeuterungen": "Fruchtfolgeflächen (FFF) sind die wertvollsten Landwirtschaftsflächen. Der vom Bund im <a href='http://www.are.admin.ch/are/de/home/raumentwicklung-und-raumplanung/strategie-und-planung/konzepte-und-sachplaene/sachplaene-des-bundes/sachplan-fruchtfolgeflaechen-sp-fff.html' target='_blank'>Sachplan Fruchtfolgeflächen</a> geforderte Mindestumfang an FFF von 240 ha im Kanton Basel-Stadt ist gesichert.",
		"quellenangabe": [
			"Städtebau & Architektur Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Fruchtfolgeflächen",
		"thema": "07 Landwirtschaft",
		"unterthema": "Landwirtschaft",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 12-1",
		"stufe1": "Sachgebiet Natur und Landschaft",
		"stufe2": "Strategie 12: Kulturland nachhaltig gestalten",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_12_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-01-07T09:34:21",
		"id": 11915
	},
	{
		"template": "line001",
		"data-id": 11916,
		"chart-id": 11916,
		"filter": "",
		"parentId": null,
		"children": [
			22321
		],
		"title": "Trinkwasserverbrauch Haushalte und Kleingewerbe",
		"subtitle": "in Mio. m<sup>3</sup>, Basel-Stadt",
		"lesehilfe": "2024 belief sich der Trinkwasserverbrauch durch Haushalte und Kleingewerbe auf 11 Mio. m<sup>3</sup>.",
		"erlaeuterungen": "Jährliche Wassermenge ab dem öffentlichen Netz, welche durch Haushalte und Kleingewerbe verbraucht wird. Private Quellen und Grundwasserfassungen werden dabei nicht berücksichtigt. Die Zuteilung des Wasserverbrauches auf die Verbrauchergruppen wurde 2015 revidiert. Die Daten vor 2015 sind nicht direkt mit jenen nach 2015 vergleichbar.",
		"quellenangabe": [
			"Industrielle Werke Basel (IWB)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Trinkwasserverbrauch Haushalte und Kleingewerbe",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Verbrauch",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 14-1",
		"stufe1": "Sachgebiet Ver- und Entsorgung",
		"stufe2": "Strategie 14: Die Trinkwasserversorgung sicherstellen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "06_14_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-06-12T07:33:30",
		"id": 11916
	},
	{
		"template": "template001",
		"data-id": 11917,
		"chart-id": 11917,
		"filter": "",
		"parentId": null,
		"children": [
			22322
		],
		"title": "Wasserverbrauch Gewerbe und Industrie",
		"subtitle": "in Mio. m<sup>3</sup>, Basel-Stadt",
		"lesehilfe": "Der Wasserverbrauch durch Gewerbe und Industrie belief sich 2024 auf gesamthaft 21,1 Mio. m<sup>3</sup>. Davon entfielen 14,3 Mio. m<sup>3</sup> auf private Grundwasserförderungen.",
		"erlaeuterungen": "Jährliche Brauchwassermenge der Industrie und des Gewerbes für Kühlung und Produktion; sowohl Verbrauch aus dem öffentlichen Netz als auch private Grundwasserförderungen. Die Daten werden durch die IWB (Summe von Verbrauch durch Gewerbe, Temporär, Bau, Industrie) und das Amt für Umwelt und Energie (Grundwasserförderung privat) erhoben. Die Zuteilung des Wasserverbrauches auf die Verbrauchergruppen wurde 2015 revidiert. Die Daten vor 2015 sind nicht direkt mit jenen nach 2015 vergleichbar.",
		"quellenangabe": [
			"Amt für Umwelt und Energie Basel-Stadt; Industrielle Werke Basel-Stadt (IWB)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wasserverbrauch Gewerbe und Industrie",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Verbrauch",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 14-2",
		"stufe1": "Sachgebiet Ver- und Entsorgung",
		"stufe2": "Strategie 14: Die Trinkwasserversorgung sicherstellen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "06_14_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-06-05T08:30:41",
		"id": 11917
	},
	{
		"template": "line001",
		"data-id": 11918,
		"chart-id": 11918,
		"filter": "",
		"parentId": null,
		"children": [
			22323
		],
		"title": "Wassertemperatur Grundwasser",
		"subtitle": "in C°, Basel-Stadt",
		"lesehilfe": "2024 beträgt die mittlere Temperatur des Grundwassers 15,3 °C. Für 90% aller Messstellen liegt der Wert dabei im Jahresmittel zwischen 13,0 und 17,5 °C.",
		"erlaeuterungen": "Die Grundwassertemperatur wird an mehreren Messstellen (aktuell rund 80) kontinuierlich gemessen, und daraus der Mittelwert der Jahrestemperatur des Grundwassers ermittelt. Zusätzlich werden die 5%- und 95%-Quantile bestimmt, um die Schwankungsbreite der Grundwassertemperaturen (ohne Ausreisser) darzustellen. Aus den Daten lässt sich ableiten, dass die Grundwassertemperaturen gegenüber natürlichen Verhältnissen anthropogen stark erhöht sind. Dies ist bedingt durch den Wärmeübertrag von Einbauten (Gebäuden) ins Grundwasser, den Wärmeinseleffekt von dicht bebauten Gebieten, Kühlwassernutzungen von Gebäuden wie auch durch klimatische Veränderungen.",
		"quellenangabe": [
			"Amt für Umwelt und Energie Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wassertemperatur Grundwasser",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Verbrauch",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 14-3",
		"stufe1": "Sachgebiet Ver- und Entsorgung",
		"stufe2": "Strategie 14: Die Trinkwasserversorgung sicherstellen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "06_14_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-06-12T07:33:31",
		"id": 11918
	},
	{
		"template": "template001",
		"data-id": 12564,
		"chart-id": 12564,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Beschäftigte",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Zahl der Beschäftigten stieg zwischen 2013 und 2022 von 188 491 auf 199 737.<br>Zielwert gemäss kantonalem Richtplan: 220 000 Beschäftige bis 2035. Zielpfad: ab 2019 lineares Wachstum um ca. 1 700 Beschäftigte pro Jahr.",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und dafür einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beschäftigte",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.12564",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 8-2",
		"stufe1": "Sachgebiet Siedlung - Wirtschaft",
		"stufe2": "Strategie 8: Das Nutzungspotenzial der Wirtschaftsflächen vergrössern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_08_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-04T04:07:10",
		"id": 12564
	},
	{
		"template": "line001",
		"data-id": 5201,
		"chart-id": 5201,
		"filter": "",
		"parentId": null,
		"children": [
			6242
		],
		"title": "Bevölkerungsdichte",
		"subtitle": "Einwohner pro Hektar, Basel-Stadt",
		"lesehilfe": "Bis 2002 verzeichnete Basel-Stadt sinkende Bevölkerungszahlen. Seit 2007 nimmt die baselstädtische Wohnbevölkerung und mit ihr die Bevölkerungsdichte wieder zu.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bevölkerungsdichte",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 5-2",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-06-19T07:43:15",
		"id": 5201
	},
	{
		"template": "mappie001",
		"data-id": 5202,
		"chart-id": 5202,
		"filter": "",
		"parentId": null,
		"children": [
			6243,
			8977,
			8978
		],
		"title": "Bevölkerungsdichte",
		"subtitle": "Einwohner pro Hektar, nach Wohnviertel, Basel-Stadt, 2024",
		"lesehilfe": "Mit 254,8 Einwohnern pro Hektar weist das Wohnviertel Matthäus am Jahresende 2024 die höchste Bevölkerungsdichte auf. Im Vergleich zu 2005 am stärksten zugenommen hat die Bevölkerungsdichte im Wohnviertel Rosental mit +49,8 Einwohnern pro Hektar; dies aufgrund der Bebauung des Erlenmattareals.",
		"erlaeuterungen": "Es wurden ausschliesslich Personen an Wohnadressen ausgewertet (ohne Meldeadressen).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Bevölkerungsdichte",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 5-3",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_003",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-27T10:03:14",
		"id": 5202
	},
	{
		"template": "template001",
		"data-id": 5203,
		"chart-id": 5203,
		"filter": "",
		"parentId": null,
		"children": [
			6244
		],
		"title": "Zu- und Wegpendler nach Herkunft und Ziel",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2023 pendeln rund 92 000 Personen nach Basel-Stadt, um einer Erwerbstätigkeit nachzugehen, rund 63% von ihnen aus der Schweiz. Rund 25 000 Wegpendler stehen dem gegenüber. Dies ergibt einen Zupendlerüberschuss von rund 67 000 Personen.",
		"erlaeuterungen": "Bis 2000 stammen die Daten aus der Eidgenössischen Volkszählung (Vollerhebung), seit 2010 aus der Strukturerhebung (Hochrechnungen aufgrund einer Stichprobenerhebung). Die Zahl der Zupendler aus dem Ausland basiert bis 2000 auf den gültigen Grenzgängerbewilligungen Ende November (2000: Ende Dezember) gemäss Bundesamt für Migration und seit 2010 auf der Grenzgängerstatistik des Bundesamtes für Statistik (4. Quartal). Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)",
			"Bundesamt für Statistik (BFS), Volkszählung (VZ)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zu- und Wegpendler nach Herkunft und Ziel",
		"thema": "11 Verkehr",
		"unterthema": "Pendler",
		"kuerzel": "I.11.5.05203",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 5-12",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-06-05T08:30:43",
		"id": 5203
	},
	{
		"template": "line001",
		"data-id": 5813,
		"chart-id": 5813,
		"filter": "",
		"parentId": null,
		"children": [
			6245,
			9685
		],
		"title": "Leerwohnungsquote",
		"subtitle": "in Prozent, Basel-Stadt",
		"lesehilfe": "Die Leerwohnungsquote liegt 2024 bei 0,77%. Zwischen 2005 und 2014 sank sie von 1,52% auf 0,23%, danach stieg sie bis 1,17% (2022). Seit 2023 sinkt sie wieder.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungsquote",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.5813",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 5-5",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-16T09:26:21",
		"id": 5813
	},
	{
		"template": "mappie001",
		"data-id": 5814,
		"chart-id": 5814,
		"filter": "",
		"parentId": null,
		"children": [
			6246
		],
		"title": "Leerwohnungsquote nach Gemeinde und Wohnviertel",
		"subtitle": "Basel-Stadt, 2024",
		"lesehilfe": "Die höchste Leerwohnungsquote wurde 2024 im Wohnviertel Altstadt Grossbasel verzeichnet (1,3%). Auch die Zunahme gegenüber der Quote von vor zehn Jahren war im Wohnviertel Altstadt Grossbasel am grössten (von 0,1% auf 1,3%).",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Leerwohnungsquote nach Gemeinde und Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.05814",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 5-6",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_006",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-16T09:26:22",
		"id": 5814
	},
	{
		"template": "line001",
		"data-id": 5815,
		"chart-id": 5815,
		"filter": "",
		"parentId": "4140",
		"children": [],
		"title": "Mittlere Wohnfläche pro Person",
		"subtitle": "in m², Basel-Stadt",
		"lesehilfe": "2024 beträgt die mittlere Wohnfläche pro Person in Basel-Stadt 41,5 m². Zuvor nahm sie bis 2010 auf 42,1 m² zu und sank zwischenzeitlich auf 41,0 m².",
		"erlaeuterungen": "Stand jeweils per Jahresende. Ab 2012 kantonale Registerauswertungen, frühere Werte wurden auf Basis der Volkszählungen 1980, 1990 und 2000 berechnet.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittlere Wohnfläche pro Person",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 5-7",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-03-31T11:07:11",
		"id": 5815
	},
	{
		"template": "template001",
		"data-id": 5816,
		"chart-id": 4135,
		"filter": "",
		"parentId": "4135",
		"children": [],
		"title": "Nettowohnungsproduktion",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Nettowohnungsproduktion lag 2024 bei 511 Einheiten; dies vor allem dank sehr hoher Umbautätigkeit.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettowohnungsproduktion",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.05816",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 5-8",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-03-25T08:34:18",
		"id": 5816
	},
	{
		"template": "template001",
		"data-id": 5817,
		"chart-id": 5817,
		"filter": "",
		"parentId": null,
		"children": [
			6249,
			7597
		],
		"title": "Nettowohnungsproduktion",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2015-2024",
		"lesehilfe": "Die Nettowohnungsproduktion war in den letzten zehn Jahren im Wohnviertel Rosental besonders hoch. Auf dieses Wohnviertel entfielen 17% der gesamtkantonalen Nettoproduktion. Insgesamt ist die Nettowohnungsproduktion  vor allem auf grosse Arealentwicklungen zurückzuführen und in geringerem Masse auf Erneuerungen bzw. Verdichtungen im Wohnungsbestand.",
		"erlaeuterungen": "Die Nettowohnungsproduktion setzt sich wie folgt zusammen: Neugebaute Wohnungen minus abgebrochene Wohnungen plus Saldo aus Umbauten (kann positiv oder negativ sein).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Nettowohnungsproduktion",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.5817",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 5-9",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-03-25T08:34:19",
		"id": 5817
	},
	{
		"template": "mappie001",
		"data-id": 5818,
		"chart-id": 5818,
		"filter": "",
		"parentId": null,
		"children": [
			6250
		],
		"title": "Bruttogeschossfläche Wohnen nach Wohnviertel",
		"subtitle": "in m<sup>2</sup>, Basel-Stadt, 2023",
		"lesehilfe": "Die grösste Bruttogeschossfläche (BGF) Wohnen weist im Jahr 2023 die Gemeinde Riehen vor dem Wohnviertel Gundeldingen auf. Werden die Anteile der BGF Wohnen an der gesamten BGF betrachtet, erreichen die Wohnviertel Bruderholz und Bachletten die höchsten Werte.",
		"erlaeuterungen": "Die Bruttogeschossfläche (BGF) ist die Summe der Grundflächen der ober- und unterirdischen Geschosse von Gebäuden, die zum Wohnen oder Arbeiten genutzt werden können. Aufgrund eines Methodenwechsels sind die Daten der Jahre seit 2020 nicht direkt mit denjenigen der Vorjahre vergleichbar.",
		"quellenangabe": [
			"Planungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bruttogeschossfläche Wohnen nach Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.5818",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 5-10",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_010",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-21T02:31:53",
		"id": 5818
	},
	{
		"template": "befragungen001",
		"data-id": 5819,
		"chart-id": 5819,
		"filter": "",
		"parentId": "4150",
		"children": [],
		"title": "Zufriedenheit mit Grünanlagen und Parks am Wohnort",
		"subtitle": "«Wie zufrieden sind Sie mit den Grünanlagen und Parks an Ihrem Wohnort?», Basel-Stadt, 2023",
		"lesehilfe": "85,8% der Bevölkerung sind 2023 mit den Grünanlagen und Parks an ihrem Wohnort eher bis sehr zufrieden.",
		"erlaeuterungen": "Alle vier Jahre wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt. Die Daten werden 2023 nach Geschlecht, Staatsangehörigkeit und Altersgruppe gewichtet. Die Daten der Befragungen 2011, 2015 und 2019 wurden nach den identischen Faktoren nachgewichtet. Die Werte dieser drei Jahre weichen daher von früher publizierten ab. Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit Grünanlagen und Parks am Wohnort",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.05819",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 6-1",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 6: Die Wohn- und Wohnumfeldqualitäten steigern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_06_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-04-03T08:36:17",
		"id": 5819
	},
	{
		"template": "befragungen001",
		"data-id": 5821,
		"chart-id": 5821,
		"filter": "",
		"parentId": null,
		"children": [
			5165,
			6252,
			8893
		],
		"title": "Bewertung der Lebensqualität",
		"subtitle": "«Wie würden Sie die Lebensqualität im Kanton Basel-Stadt insgesamt bewerten?», Basel-Stadt",
		"lesehilfe": "Auf einer 10er-Skala konnten die befragten Personen die Lebensqualität im Kanton Basel-Stadt bewerten. 2023 gibt die Bevölkerung der Lebensqualität im Stadtkanton im Durchschnitt eine Note von 7,8. Die Lebensqualität wird damit vergleichbar hoch bewertet wie in den Jahren davor.",
		"erlaeuterungen": "Für die Berechnung der Durchschnittsnote bleiben befragte Personen, welche die Frage mit «Weiss nicht» oder gar nicht beantwortet haben, unberücksichtigt. <br>Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: Ab 2019 in schriftlicher Form (Papier- bzw. Onlinefragebogen), zuvor telefonisch; Ab 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppen (2011, 2015 und 2019 wurden nachgewichtet, die Werte weichen daher von früher publizierten ab).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bewertung der Lebensqualität",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.5821",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 6-2",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 6: Die Wohn- und Wohnumfeldqualitäten steigern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_06_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-10T07:47:35",
		"id": 5821
	},
	{
		"template": "befragungen001",
		"data-id": 5822,
		"chart-id": 5822,
		"filter": "",
		"parentId": null,
		"children": [
			6253
		],
		"title": "Anteil Einwohnerinnen und Einwohner pro ÖV-Güteklasse",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Fast zwei Drittel der Wohnbevölkerung des Kantons Basel-Stadt wohnen in einem Gebiet der ÖV-Güteklasse A und damit in einer Zone mit sehr guter Anbindung an den öffentlichen Verkehr, rund 30% in einem Gebiet der Güteklasse B. Die Anteile haben sich in den letzten Jahren kaum verändert.",
		"erlaeuterungen": "Die ÖV-Güteklassen sind ein Mass für die räumliche Erschliessungsqualität durch den öffentlichen Verkehr. Die Güteklassen werden zweistufig bestimmt: Die Art der Verkehrsmittel und das Kursintervall weisen jeder Haltestelle eine bestimmte Kategorie zu. Die Haltestellenkategorie in Verbindung mit der Distanz des Wohnortes einer Person zur Haltestelle ergibt dann die ÖV-Güteklasse für eine bestimmte Person.",
		"quellenangabe": [
			"Amt für Mobilität Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://map.geo.bs.ch/main/wsgi/file_proxy/GO_GueteklassenOeV/Definition_Gueteklassen_oeffentlicher_Verkehr.pdf' target = '_blank'>Definition der Güteklassen des öffentlichen Verkehrs</a>",
			"<a href = 'https://map.geo.bs.ch/?lang=de&baselayer_ref=Grundkarte%20grau&map_x=2612508&map_y=1267331&map_zoom=2&tree_group_layers_G%C3%BCteklassen%20%C3%B6ffentlicher%20Verkehr=GO_GueteklassenOeV&tree_group_layers_Liniennetz%20%C3%B6ffentlicher%20Verkehr=GO_GueteklassenOeV&tree_groups=Liniennetz_OEV&tree_group_layers_Liniennetz_OEV=GO_GueteklassenOeV' target = '_blank'>Karte der Güteklassen des öffentlichen Verkehrs</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil Einwohnerinnen und Einwohner pro ÖV-Güteklasse",
		"thema": "11 Verkehr",
		"unterthema": "Öffentlicher Verkehr",
		"kuerzel": "I.11.2.05822",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 7-1",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 7: Die Siedlungsentwicklung und stadtgerechte Mobilität aufeinander abstimmen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_07_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-06-05T08:30:45",
		"id": 5822
	},
	{
		"template": "line001",
		"data-id": 5823,
		"chart-id": 5823,
		"filter": "",
		"parentId": null,
		"children": [
			6254
		],
		"title": "Beschäftigtendichte",
		"subtitle": "Anzahl Beschäftigte in Vollzeitäquivalenten pro Hektar, Basel-Stadt",
		"lesehilfe": "Im Jahr 2022 arbeiteten im Kanton Basel-Stadt in Vollzeitäquivalente (VZÄ) umgerechnet und pro Hektar rund 44 Beschäftigte (2013: rund 40 Beschäftigte).",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und dafür einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Beschäftigung in Vollzeitäquivalenten (VZÄ) resultiert aus der Umrechnung des Arbeitsvolumens sämtlicher Voll- und Teilzeitbeschäftigten in Vollzeitbeschäftigte mittels Schätzmodell (basierend auf Lohnangaben der AHV und Informationen weiterer Erhebungen).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beschäftigtendichte",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.5823",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 8-3",
		"stufe1": "Sachgebiet Siedlung - Wirtschaft",
		"stufe2": "Strategie 8: Das Nutzungspotenzial der Wirtschaftsflächen vergrössern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_08_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-04T04:07:11",
		"id": 5823
	},
	{
		"template": "mappie001",
		"data-id": 5825,
		"chart-id": 5825,
		"filter": "",
		"parentId": null,
		"children": [
			6255
		],
		"title": "Bruttogeschossfläche Arbeiten nach Wohnviertel",
		"subtitle": "in m<sup>2</sup>, Basel-Stadt, 2023",
		"lesehilfe": "Die meiste für Arbeiten genutzte Bruttogeschossfläche (BGF) findet man im Jahr 2023 in den Wohnvierteln St. Alban und St. Johann. Bezogen auf die Anteile BGF Arbeiten an der gesamten BGF weisen die Wohnviertel Kleinhüningen und Altstadt Grossbasel die höchsten Werte auf.",
		"erlaeuterungen": "Die Bruttogeschossfläche (BGF) ist die Summe der Grundflächen der ober- und unterirdischen Geschosse von Gebäuden, die zum Wohnen oder Arbeiten genutzt werden können.",
		"quellenangabe": [
			"Planungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bruttogeschossfläche Arbeiten nach Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.5825",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 8-4",
		"stufe1": "Sachgebiet Siedlung - Wirtschaft",
		"stufe2": "Strategie 8: Das Nutzungspotenzial der Wirtschaftsflächen vergrössern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_08_00_00_00_004",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-06-03T08:37:44",
		"id": 5825
	},
	{
		"template": "line001",
		"data-id": 5891,
		"chart-id": 5891,
		"filter": "",
		"parentId": null,
		"children": [
			6256
		],
		"title": "Kontinentale Erreichbarkeit",
		"subtitle": "Stadt Basel im nationalen Vergleich",
		"lesehilfe": "Durch die starken Reiseeinschränkungen als Massnahmen zur Bekämpfung der COVID-19-Pandemie sank die Erreichbarkeit der europäischen Regionen im Jahr 2020 markant. Der Erreichbarkeitsindex 2022 (z. B. Basel: 118,4) ist höher als 2020 (106,8), aber immer noch tiefer als 2018 (133,3) und als im Jahr 2000 (126,6).",
		"erlaeuterungen": "Kontinentale Erreichbarkeit = Erreichbarkeit aller Regionen Europas. Bei der Kennzahl handelt es sich um einen indexierten Wert: 100 = Mittel aller einbezogenen Ursprungsregionen im Jahr 2002. Erreichbarkeit ist kein klares, lineares Konzept. Vielmehr beruht es auf einer Vielzahl von Faktoren, die unter dem Themenbereich Erreichbarkeit subsumiert werden können. Die Erreichbarkeitsmodelle von BAK Economics basieren auf dem Ansatz aktivitätsbasierter Gravitationsindikatoren. Zudem folgen sie dem Konzept der Erreichbarkeit «aus der Region» (outbound accessibility), das heisst es werden Reisezeit und Frequenz herangezogen, die benötigt werden, um aus der Region andere Regionen zu erreichen. Der resultierende Indikator reflektiert das gesamte Potenzial aller Regionen ohne jegliche Limitierung der Reisezeit; die Reisedestinationen werden jedoch über die Reisezeit und das Bruttoinlandprodukt der Region gewichtet. Um die Entwicklung nach den starken Reiseeinschränkungen im Jahr 2020 kurzfristig zu beobachten, wurde die Erreichbarkeit engegen dem zweijährlichen Rhythmus ausnahmsweise auch für das Jahr 2021 berechnet.",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [
			"Weiterführende Informationen <a href = 'https://www.bak-economics.com/en/solutions/regional-analysis/region-international/location-factors/erreichbarkeit/' target = '_blank'>BAK Economics</a>, und",
			"<a href = 'http://www.mobilitaet.bs.ch/gesamtverkehr/verkehrskennzahlen/erreichbarkeit.html' target = '_blank'>Amt für Mobilität</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Kontinentale Erreichbarkeit",
		"thema": "11 Verkehr",
		"unterthema": "Mobilitätsverhalten",
		"kuerzel": "I.11.6.5891",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 9-1",
		"stufe1": "Sachgebiet Siedlung - Wirtschaft",
		"stufe2": "Strategie 9: Bedingugen für Wirtschaft und Bildung verbessern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_09_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-26T02:51:38",
		"id": 5891
	},
	{
		"template": "line001",
		"data-id": 5901,
		"chart-id": 5901,
		"filter": "",
		"parentId": null,
		"children": [
			6257
		],
		"title": "Bevölkerungs- und Beschäftigtenentwicklung",
		"subtitle": "indexiert (Basis 2013 = 100), Basel-Stadt",
		"lesehilfe": "Die Wohnbevölkerung ist im Kanton Basel-Stadt zwischen 2013 und 2022 um 4,7% gestiegen. Die Zahl der Beschäftigten stieg im gleichen Zeitraum um 6,0%.",
		"erlaeuterungen": "Es ist jeweils der Bevölkerungsbestand Ende Jahr abgebildet. Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und dafür einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Referenzperiode ist jeweils der Dezember des Jahres.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bevölkerungs- und Beschäftigtenentwicklung",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.5901",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 5-11",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-04T04:07:09",
		"id": 5901
	},
	{
		"template": "line001",
		"data-id": 6007,
		"chart-id": 6154,
		"filter": "",
		"parentId": "6154",
		"children": [],
		"title": "Verkehrsleistungsindex",
		"subtitle": "indexiert (Basis 2010 = 100), Basel-Stadt",
		"lesehilfe": "Das Verkehrsaufkommen in Basel-Stadt hat 2023 im Vergleich zum Vorjahr bei allen Verkehrsmitteln zugenommen. Mit Ausnahme des Velovekehrs liegt das Verkehrsaufkommen aber immer noch unter dem Niveau von vor der Pandemie.",
		"erlaeuterungen": "Der Verkehrsleistungsindex erfasst die Veränderung der Fahrleistung der verschiedenen Verkehrsmittel im ganzen Kantonsgebiet. Es wird die Veränderung gegenüber dem Referenzjahr 2010 dargestellt (indexiert, 2010 = 100). Bei den Fussgängerdaten ist das Referenzjahr 2013, da diese erst seit dann erhoben werden. Weiterführende Informationen: <a href='https://www.mobilitaet.bs.ch/gesamtverkehr/verkehrskennzahlen/verkehrsindex.html' target=\"_blank\">Amt für Mobilität Basel-Stadt</a>.",
		"quellenangabe": [
			"Amt für Mobilität Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Verkehrsleistungsindex",
		"thema": "11 Verkehr",
		"unterthema": "Mobilitätsverhalten",
		"kuerzel": "I.11.16.06007",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 13-1",
		"stufe1": "Sachgebiet Mobilität",
		"stufe2": "Strategie 13: Stadtgerechte Mobilität fördern und Erreichbarkeit gewährleisten",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_13_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-07-30T09:44:17",
		"id": 6007
	},
	{
		"template": "template001",
		"data-id": 6214,
		"chart-id": 6214,
		"filter": "",
		"parentId": null,
		"children": [
			6259
		],
		"title": "Bevölkerung am Jahresende und Anzahl Wohnungen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Von 1960 bis 1970 wuchsen sowohl Wohnungsbestand als auch Bevölkerung. Es gab kaum Leerwohnungen. In den 1970er-Jahren nahm die Bevölkerung ab, der Wohnungsbestand weiterhin zu. Dies führte Mitte der 1970er-Jahre zu einer hohen Anzahl Leerwohnungen. Die seit 2007 anhaltende Bevölkerungszunahme führte zunächst zu einem Rückgang der Anzahl Leerwohnungen. Infolge vermehrter Bautätigkeit stieg die Zahl der Leerwohnungen in den Jahren 2015 bis 2022 jedoch wieder.",
		"erlaeuterungen": "Bis 2011 wurde die Bevölkerungszahl ermittelt, indem der Vorjahresbestand durch natürliche Ereignisse (Geburt, Tod) und räumliche Ereignisse (Zuzug, Wegzug) fortgeschrieben wurde. Seit 2012 wird die Bevölkerungszahl direkt aus dem kantonalen Einwohnerregister gewonnen. Die Leerwohnungen werden per Stichtag 1. Juni im Rahmen der Leerwohnungszählung ermittelt. Der in der Grafik dargestellte Wohnungsbestand umfasst die im Wohnungsregister erfassten Wohnungen ohne die Leerwohnungen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bevölkerung am Jahresende und Anzahl Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.06214",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 5-1",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-03-12T10:19:03",
		"id": 6214
	},
	{
		"template": "template001",
		"data-id": 6215,
		"chart-id": 6215,
		"filter": "",
		"parentId": null,
		"children": [
			6260,
			7747,
			8448,
			8954,
			9061,
			10041
		],
		"title": "Wohnbevölkerung gemäss Bevölkerungsszenarien",
		"subtitle": "Bevölkerungsszenarien Basel-Stadt, 2025",
		"lesehilfe": "Bis zum Jahr 2045 erhöht sich die kantonale Wohnbevölkerung im Mittleren Szenario von 207 515 am Ende des Jahres 2024 um 9,5% auf rund 227 000 Einwohner.",
		"erlaeuterungen": "Resultat der Bevölkerungsszenarien 2025. Bevölkerungsbestand am Jahresende. Die Bevölkerungszahl setzt sich zusammen aus der ständigen und nichtständigen Wohnbevölkerung und Personen am Nebenwohnsitz.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsszenarien"
		],
		"externalLinks": [
			"Detaillierte Informationen zu den Bevölkerungsszenarien und der angewandten Methodik finden Sie auf der <a href = 'https://www.statistik.bs.ch/analysen-berichte/gesellschaft-soziales/bevoelkerungsszenarien.html' target = '_blank'>Internetseite zu den Bevölkerungsszenarien</a>."
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnbevölkerung gemäss Bevölkerungsszenarien",
		"thema": "01 Bevölkerung",
		"unterthema": "Szenarien",
		"kuerzel": "",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 5-4",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 5: Mehr Wohnraum für eine wachsende Bevölkerung schaffen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_05_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-07-15T09:02:18",
		"id": 6215
	},
	{
		"template": "befragungen001",
		"data-id": 6216,
		"chart-id": 5178,
		"filter": "",
		"parentId": "5178",
		"children": [],
		"title": "Zufriedenheit mit verschiedenen Aspekten am Wohnort, Teil 1",
		"subtitle": "«Wie zufrieden sind Sie mit den folgenden Aspekten an Ihrem Wohnort?», Basel-Stadt, 2023",
		"lesehilfe": "Die befragten Personen konnten 24 Punkte, die für den Wohnort wichtig sind, bewerten (siehe auch Teil 2 des Indikators). Am zufriedensten (69,2% «sehr» und 23,4% «eher zufrieden») sind sie 2023 mit dem öffentlichen Verkehr, gefolgt von den Einkaufsmöglichkeiten am Wohnort und der generellen Vielfalt der Einkaufsmöglichkeiten in Basel.",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: Ab 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppen (2019 wurde nachgewichtet, die Werte weichen daher von früher publizierten ab).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit verschiedenen Aspekten am Wohnort, Teil 1",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.06216",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 6-3a",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 6: Die Wohn- und Wohnumfeldqualitäten steigern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_06_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-10T07:47:36",
		"id": 6216
	},
	{
		"template": "line001",
		"data-id": 6217,
		"chart-id": 6217,
		"filter": "",
		"parentId": null,
		"children": [
			6262
		],
		"title": "Leerstehende Geschäftsflächen",
		"subtitle": "in m², Basel-Stadt",
		"lesehilfe": "Im Jahr 2024 beträgt die leerstehende Fläche insgesamt 249 200 m², 58 600 m²  mehr als im Vorjahr. Die Büroflächen machen mit 175 100 m² rund 70% der leerstehenden Geschäftsflächen aus.",
		"erlaeuterungen": "Die Erhebung wird vom Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel durchgeführt. Stichtag ist der 1. Juni.",
		"quellenangabe": [
			"Schweizerischer Verband der Immobilienwirtschaft (SVIT) beider Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerstehende Geschäftsflächen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.06217",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 8-5",
		"stufe1": "Sachgebiet Siedlung - Wirtschaft",
		"stufe2": "Strategie 8: Das Nutzungspotenzial der Wirtschaftsflächen vergrössern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_08_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-08-16T09:26:24",
		"id": 6217
	},
	{
		"template": "template001",
		"data-id": 6218,
		"chart-id": 6218,
		"filter": "",
		"parentId": null,
		"children": [
			6263
		],
		"title": "Bevölkerung ab 15 Jahren nach Ausbildungsniveau",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Seit 1990 hat sich der Anteil der Personen mit einer Ausbildung auf Tertiärstufe kontinuierlich erhöht. 2023 beträgt dieser Anteil knapp 50%. Rund 31% der baselstädtischen Wohnbevölkerung besitzen eine höchste abgeschlossene Ausbildung auf Niveau Sekundarstufe II und knapp 20% eine auf Niveau Sekundarstufe I.",
		"erlaeuterungen": "Die Sekundarstufe I umfasst Ausbildungen bis maximal obligatorische Schule. Unter Sekundarstufe II ist die berufliche Grundbildung, z. B. eine Berufslehre, sowie die allgemeinbildende Schule, z. B. die gymnasiale Maturität, zusammengefasst. Die Tertiärstufe umfasst die höhere Berufsbildung, z. B. eine höhere Fachschule für Technik oder Wirtschaft sowie Ausbildungen an Hochschulen, wie z. B. ein Bachelor- oder Masterstudium. Bis 2000 stammen die Daten aus der Eidgenössischen Volkszählung (Vollerhebung), seit 2010 aus der Strukturerhebung (Hochrechnungen aufgrund einer Stichprobenerhebung). Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Da die Frage zur höchsten abgeschlossenen Ausbildung im Fragebogen der Strukturerhebung 2020 verändert wurde, ist die Veränderung zwischen 2020 und den Vorjahren mit Vorsicht zu interpretieren.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)",
			"Bundesamt für Statistik (BFS), Volkszählung (VZ)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bevölkerung ab 15 Jahren nach Ausbildungsniveau",
		"thema": "15 Bildung",
		"unterthema": "Bildungsniveau",
		"kuerzel": "I.15.6.6218",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 9-2",
		"stufe1": "Sachgebiet Siedlung - Wirtschaft",
		"stufe2": "Strategie 9: Bedingungen für Wirtschaft und Bildung verbessern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_09_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-06-19T07:43:17",
		"id": 6218
	},
	{
		"template": "line001",
		"data-id": 6220,
		"chart-id": 6220,
		"filter": "",
		"parentId": null,
		"children": [
			6264
		],
		"title": "Haushalte in Begegnungszonen",
		"subtitle": "indexiert (2011 = 100), Stadt Basel",
		"lesehilfe": "Die Anzahl Privathaushalte in Begegnungszonen ist von 2011 bis 2023 prozentual stärker gestiegen als das Total der Privathaushalte in der Stadt Basel. Dies ist in erster Linie auf die Ausweitung der Begegnungszonen zurückzuführen. Ende 2023 gibt es in der Stadt Basel gut 90 000 Privathaushalte; gut 9 200 liegen in Begegnungszonen.",
		"erlaeuterungen": "In den Begegnungszonen gilt eine Höchstgeschwindigkeit von 20 km/h. Fussgängerinnen und Fussgänger haben gegenüber Autos und Velos überall Vortritt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Planungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Haushalte in Begegnungszonen",
		"thema": "01 Bevölkerung",
		"unterthema": "Haushalte",
		"kuerzel": "I.01.TRKE.06220",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 6-4",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 6: Die Wohn- und Wohnumfeldqualitäten steigern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_06_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-20T03:23:33",
		"id": 6220
	},
	{
		"template": "template001",
		"data-id": 6236,
		"chart-id": 6236,
		"filter": "",
		"parentId": null,
		"children": [
			6046,
			6265,
			6347,
			6371,
			8935
		],
		"title": "Anzahl Beschäftigte nach Branche",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2022 sind in Basel-Stadt 199 737 Personen beschäftigt. Das sind 6 735 Personen mehr als im Vorjahr. Die grösste Beschäftigungszunahme verzeichnet das Gastgewerbe mit 19,8% im Vergleich zum Vorjahr, während die Branche «Übriges verarbeitendes Gewerbe» mit -2,4% als einzige Branche eine Beschäftigungsabnahme aufweist.",
		"erlaeuterungen": "Übrige Branchen: Land- und Forstwirtschaft, Fischerei, Bergbau und Gewinnung von Steinen und Erden, Information und Kommunikation, Grundstücks- und Wohnungswesen, Kunst, Unterhaltung und Erholung sowie sonstige Dienstleistungen; Unternehmens-DL, Freiberufe: Erbringung von freiberuflichen, wissenschaftlichen und technischen Dienstleistungen sowie Erbringung von sonstigen wirtschaftlichen Dienstleistungen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Beschäftigte nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.6236",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 8-1",
		"stufe1": "Sachgebiet Siedlung - Wirtschaft",
		"stufe2": "Strategie 8: Das Nutzungspotenzial der Wirtschaftsflächen vergrössern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_08_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-09-30T12:46:28",
		"id": 6236
	},
	{
		"template": "line001",
		"data-id": 7773,
		"chart-id": 7773,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bevölkerung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Ende 2024 beträgt der Bevölkerungsbestand im Kanton Basel-Stadt 207 515 Personen.<br>Zielwert gemäss kantonalem Richtplan: 220 000 Einwohnerinnen und Einwohner bis 2035. Zielpfad: ab 2019 lineares Wachstum um ca. 1 200 Personen pro Jahr.",
		"erlaeuterungen": "siehe <a href='https://www.statistik.bs.ch/haeufig-gefragt/einwohner/zentrale-begriffe-einwohner.html#page_section3_section1' target='_blank'>Zentrale Begriffe zu den Einwohnerdaten</a>.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bevölkerung",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.07773",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 1-1",
		"stufe1": "Querschnittsthemen",
		"stufe2": "Strategie 1: Regionale Sichtweise einnehmen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-02-17T11:24:57",
		"id": 7773
	},
	{
		"template": "line001",
		"data-id": 7774,
		"chart-id": 7774,
		"filter": "",
		"parentId": null,
		"children": [
			8418
		],
		"title": "Bruttogeschossflächen Wohnen und Arbeiten",
		"subtitle": "in m<sup>2</sup>, Basel-Stadt",
		"lesehilfe": "Sowohl die für Wohn- als auch die für Arbeitszwecke genutzte Bruttogeschossfläche hat seit 1995 zugenommen. Dies ist auf die Bautätigkeit im Kanton zurückzuführen.",
		"erlaeuterungen": "Die Bruttogeschossfläche (BGF) ist die Summe der Grundflächen der ober- und unterirdischen Geschosse von Gebäuden, die zum Wohnen oder Arbeiten genutzt werden können. Aufgrund eines Methodenwechsels sind die Daten der Jahre seit 2020 nicht direkt mit denjenigen der Vorjahre vergleichbar. Für das Jahr 2000 stehen keine Daten zur Verfügung.",
		"quellenangabe": [
			"Bau- und Verkehrsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bruttogeschossflächen Wohnen und Arbeiten",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.07774",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 1-3",
		"stufe1": "Querschnittsthemen",
		"stufe2": "Strategie 1: Regionale Sichtweise einnehmen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-21T02:31:51",
		"id": 7774
	},
	{
		"template": "template001",
		"data-id": 7775,
		"chart-id": 7775,
		"filter": "",
		"parentId": null,
		"children": [
			8419
		],
		"title": "Bauzonen",
		"subtitle": "indexiert (2005 = 100), Basel-Stadt",
		"lesehilfe": "Die Bauzonenfläche im Kanton Basel-Stadt ist 2024 im Vergleich zu 2005 um 0,2 Indexpunkte grösser. Die Fläche der Bauzonen mit potenzieller Wohnnutzung liegt bei 101,28 Indexpunkten.",
		"erlaeuterungen": "Zonen gemäss Zonenplan Basel-Stadt und Zonenplan Gemeinde Riehen (revidiert per 1.1.2017). Bauzonen: Zonen 2 bis 7 einschliesslich 2a, 5a und Stadt- und Dorfbild-Schutz- und Schonzone sowie die Riehener Arbeitszonen und Zone 2R. Bauzonen mit potenzieller Wohnnutzung: ohne Zonen mit reiner Arbeitsnutzung (Basel: «Zone 7 Industrie- und Gewerbezone»; Riehen: Arbeitszonen).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Bau- und Verkehrsdepartement Basel-Stadt"
		],
		"externalLinks": [
			"Informationen zum <a href = 'http://www.zonenplan.bs.ch/' target = '_blank'>Zonenplan Basel-Stadt</a>",
			"Zonenpläne Basel-Stadt, Riehen und Bettingen als Karten auf <a href = 'https://map.geo.bs.ch/s/h97S' target = '_blank'>MapBS</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bauzonen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.07775",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 1-4",
		"stufe1": "Querschnittsthemen",
		"stufe2": "Strategie 1: Regionale Sichtweise einnehmen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-03-17T11:07:22",
		"id": 7775
	},
	{
		"template": "line001",
		"data-id": 7777,
		"chart-id": 7777,
		"filter": "",
		"parentId": null,
		"children": [
			8420
		],
		"title": "Jährlich durch Stau generierte Verzögerungszeit",
		"subtitle": "Stadt Basel im Vergleich mit ausgewählten Schweizer Städten",
		"lesehilfe": "Die Verzögerungszeit für den motorisierten Individualverkehr betrug in der Stadt Basel im Jahr 2021 rund 24%. Das bedeutet, dass eine durchschnittliche Reise 24% länger dauerte, als dies unter staufreien Bedingungen der Fall gewesen wäre. Nach dem deutlichen Rückgang zwischen 2019 und 2020, ist im Jahr 2021 in allen betrachteten Städten wieder ein Anstieg zu beobachten.",
		"erlaeuterungen": "Die Zahlen basieren auf gesammelten Verkehrsdaten des Navigationsgeräte-Herstellers TomTom. Damit die urbanen Flächen, für die der Index berechnet wird, international vergleichbar sind, wurden sie von TomTom individuell definiert.",
		"quellenangabe": [
			"TomTom International"
		],
		"externalLinks": [
			"Detaillierte Informationen zu den TomTom Staudaten und der angewandten Methodik sind hier zu finden: <a href = 'https://www.tomtom.com/en_gb/traffic-index/about' target = '_blank'>TomTom Traffic Index</a>.",
			"Die Werte für <a href = 'https://www.tomtom.com/en_gb/trafficindex/city/basel' target = '_blank'>Basel</a>;",
			"die Werte für <a href = 'https://www.tomtom.com/en_gb/trafficindex/city/GNV' target = '_blank'>Genf</a>;",
			"die Werte für <a href = 'https://www.tomtom.com/en_gb/trafficindex/city/ZUR' target = '_blank'>Zürich</a>;",
			"die Werte für <a href = 'https://www.tomtom.com/en_gb/trafficindex/city/bern' target = '_blank'>Bern</a>."
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Jährlich durch Stau generierte Verzögerungszeit",
		"thema": "11 Verkehr",
		"unterthema": "Mobilitätsverhalten",
		"kuerzel": "I.11.6.07777",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 13-2",
		"stufe1": "Sachgebiet Mobilität",
		"stufe2": "Strategie 13: Stadtgerechte Mobilität fördern und Erreichbarkeit gewährleisten",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_13_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-26T02:51:10",
		"id": 7777
	},
	{
		"template": "line001",
		"data-id": 7778,
		"chart-id": 7778,
		"filter": "",
		"parentId": null,
		"children": [
			8421
		],
		"title": "Warentransit durch die Schweiz",
		"subtitle": "mit Eingang oder Ausgang Region Basel, in Tonnen, nach Verkehrsträger",
		"lesehilfe": "Der Transit durch die Region Basel nimmt auf der Strasse seit 2010 kontinuierlich ab. Nach einem leichten Anstieg beim Eingang auf der Strasse im Jahr 2022 gab es 2023 wieder einen Rückgang.",
		"erlaeuterungen": "Berücksichtigt sind Waren, welche auf ihrem Weg vom Ursprungs- zum Zielland die Schweiz durchqueren und dabei in der Region Basel die Landesgrenze (resp. ein Zollamt) passieren. «Eingang» bezeichnet dabei Waren, welche die Grenze in Richtung Schweiz überqueren, «Ausgang» solche, die in Richtung Ausland transportiert werden. Die Region Basel besteht aus den Zollzonen Basel rechts, Basel links, Flughafen und Rheinhafen BS/BL. Über Pipelines verlassen in der Region Basel keine Waren die Schweiz.",
		"quellenangabe": [
			"Eidgenössische Zollverwaltung (EZV)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Warentransit durch die Schweiz",
		"thema": "06 Industrie, Dienstleistungen",
		"unterthema": "Aussenhandel",
		"kuerzel": "I.06.4.07778",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 13-3",
		"stufe1": "Sachgebiet Mobilität",
		"stufe2": "Strategie 13: Stadtgerechte Mobilität fördern und Erreichbarkeit gewährleisten",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_13_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-11-12T02:43:27",
		"id": 7778
	},
	{
		"template": "line001",
		"data-id": 7779,
		"chart-id": 7779,
		"filter": "",
		"parentId": null,
		"children": [
			8422
		],
		"title": "Motorisierungsgrad",
		"subtitle": "Personenwagen pro 1000 Einwohner, Basel-Stadt",
		"lesehilfe": "Seit dem Höchststand von 332 Personenwagen pro 1000 Einwohnerinnen und Einwohner im Jahr 2004 ist eine leicht abnehmende Tendenz zu beobachten. Aktuell beträgt der Motorisierungsgrad 300 Personenwagen pro 1000 Einwohnerinnen und Einwohner.",
		"erlaeuterungen": "Der Motorisierungsgrad zeigt das Verhältnis zwischen Fahrzeugbestand und mittlerer kantonaler Wohnbevölkerung. Die Auswertung basiert ab 2021 auf den Fahrzeugdaten des Informationssystems Verkehrszulassung (IVZ) des Bundesamts für Strassen (ASTRA). Leichte Differenzen zu den Zahlen der Motorfahrzeugkontrolle Basel-Stadt sind möglich.",
		"quellenangabe": [
			"Kantonspolizei Basel-Stadt, Motorfahrzeugkontrolle; Statistisches Amt Basel-Stadt",
			"Bundesamt für Strassen (ASTRA)"
		],
		"externalLinks": [
			"<a href = 'https://www.astra.admin.ch/astra/de/home/fachleute/weitere-bereiche/fachanwendungen/ivz.html' target = '_blank'>IVZ - Informationssystem Verkehrszulassung</a>",
			"<a href = 'https://www.astra.admin.ch/astra/de/home/dokumentation/daten-informationsprodukte/fahrzeugdaten.html' target = '_blank'>Infos zu den Fahrzeugdaten des ASTRA</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Motorisierungsgrad",
		"thema": "11 Verkehr",
		"unterthema": "Motorfahrzeuge",
		"kuerzel": "I.11.1.07779",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 13-4",
		"stufe1": "Sachgebiet Mobilität",
		"stufe2": "Strategie 13: Stadtgerechte Mobilität fördern und Erreichbarkeit gewährleisten",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_13_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-06-19T07:43:14",
		"id": 7779
	},
	{
		"template": "line001",
		"data-id": 7782,
		"chart-id": 7782,
		"filter": "",
		"parentId": null,
		"children": [
			8423
		],
		"title": "Mietpreisindex Basel-Stadt",
		"subtitle": "Indexwert (Basis Mai 2000 = 100)",
		"lesehilfe": "Mit Ausnahme von 1997 ist der Basler Mietpreisindex zwischen 1995 und 2024 von Jahr zu Jahr gestiegen. Aktuell steht er im November 2024 bei 138,2 Punkten (Basis Mai 2000 = 100).",
		"erlaeuterungen": "Mietpreisindex: Geschichtete Zufallsstichprobe, die 5% der Miet- und Genossenschaftswohnungen mit 1 bis 6 Zimmern umfasst, welche dauerhaft zu Wohnzwecken vermietet werden. Es wird der Wert im November des jeweiligen Jahres ausgewiesen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Mietpreiserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mietpreisindex Basel-Stadt",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Mietpreise",
		"kuerzel": "I.09.3.07782",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 6-5",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 6: Die Wohn- und Wohnumfeldqualitäten steigern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_06_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-07-24T08:40:39",
		"id": 7782
	},
	{
		"template": "befragungen001",
		"data-id": 8877,
		"chart-id": 8852,
		"filter": "",
		"parentId": "8852",
		"children": [],
		"title": "Zufriedenheit mit verschiedenen Aspekten am Wohnort, Teil 2",
		"subtitle": "«Wie zufrieden sind Sie mit den folgenden Aspekten an Ihrem Wohnort?» Stand: 2023",
		"lesehilfe": "Die befragten Personen konnten 24 Punkte, die für den Wohnort wichtig sind, bewerten (siehe auch Teil 1 des Indikators). Die tiefsten Zufriedenheitswerte haben die Behinderteneinrichtungen (11,2% «sehr» und 26,3% «eher zufrieden»), das Angebot zur Kinderbetreuung und die Einrichtungen für Jugendliche erhalten. Bei diesen Faktoren liegt der Anteil «Weiss nicht» allerdings bei über 40%. Beim Wohnungsangebot ist der Anteil der Zufriedenen («sehr» und «eher zufrieden») 2023 etwas tiefer als 2019.",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Methodenwechsel mit Einfluss auf die Vergleichbarkeit der Ergebnisse: Ab 2023 Gewichtung nach Geschlecht, Staatsangehörigkeit und Altersgruppen (2019 wurde nachgewichtet, die Werte weichen daher von früher publizierten ab).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit verschiedenen Aspekten am Wohnort, Teil 2",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.08877",
		"kennzahlenset": "Richtplan",
		"kuerzelKunde": "ST 6-3b",
		"stufe1": "Sachgebiet Siedlung - Wohnen",
		"stufe2": "Strategie 6: Die Wohn- und Wohnumfeldqualitäten steigern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_06_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-04-10T07:47:37",
		"id": 8877
	}
];