var indikatorensetData = [
	{
		"template": "line001",
		"data-id": 9663,
		"chart-id": 9663,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Nettoschuldenquote",
		"subtitle": "in Promille des BIP der Schweiz, Basel-Stadt",
		"lesehilfe": "2021 beträgt die Nettoschuldenquote des Kantons Basel-Stadt -0,1 Promille des Schweizer Bruttoinlandprodukts.<br><br><b>Zielwert:</b> 6,5 Promille<br><i>(Grundlage: FHG §4 Abs. 1)</i><br><br><b>Ampelwerte:</b><br>\tGrün: \tQuote ≤ 6,5 Promille im letzten Rechnungsjahr, dem aktuellen Budget und allen \tPlanjahren<br>Gelb: \tQuote ≤ 6,5 Promille im letzten Rechnungsjahr, aber im aktuellen Budget oder einem \tder Planjahre über 6,5 Promille<br>Rot: \tQuote > 6,5 Promille im letzten Rechnungsjahr",
		"erlaeuterungen": "Die Nettoschuldenquote des Kantons Basel-Stadt wird in Bezug auf das Schweizer Bruttoinlandprodukt berechnet. Die Schuldenbremse wurde im Jahr 2005 beschlossen: Die Verschuldung des Kantons darf im Verhältnis zu seiner wirtschaftlichen Leistungsfähigkeit mittelfristig einen definierten Wert nicht überschreiten. Die Nettoschuld relativ zum Bruttoinlandprodukt der Schweiz durfte nicht mehr als 7,5 Promille betragen, seit dem Jahr 2010 nicht mehr als 6,5 Promille.",
		"quellenangabe": [
			"Jahresbericht des Kantons Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettoschuldenquote",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Volkseinkommen",
		"kuerzel": "I.04.1.09663",
		"kennzahlenset": "Schluesselindikatoren",
		"kuerzelKunde": "2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-04-13T08:21:44",
		"id": 9663
	},
	{
		"template": "line001",
		"data-id": 9672,
		"chart-id": 9672,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil erneuerbarer Energie am Bruttoenergieverbrauch",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "<b>Zielwert:</b> 85 % bis 2037<br><i>(Grundlage: Gegenvorschlag des Grossen Rates GRB vom 14.9.2022 zur Klimagerechtigkeitsinitiative, angenommen an Volksabstimmung vom 27. November 2022)</i><br><b>Zielpfad:</b> exponentielles Wachstum (15,3 Prozent im Vergleich zum letzten Wert).<br><br><b>Ampelwerte:</b><br>\tGrün: \tWert auf/über Zielpfad und Wachstum gleich/stärker als Zielpfad<br>Gelb: \tWert auf/über Zielpfad und Wachstum geringer als Zielpfad<br>\tbzw. Wert unter Zielpfad und Wachstum gleich/stärker als Zielpfad<br>Rot: \tWert unter Zielpfad und Wachstum geringer als Zielpfad",
		"erlaeuterungen": "Folgende Energieträger werden als erneuerbar berücksichtigt: Wasserkraft, Holz, Umweltwärme, thermische und fotovoltaische Sonnenenergie, Klärschlamm, Biogas, erneuerbare Elektrizität (in Basel-Stadt stammen 100% des importierten Strommixes aus erneuerbaren Quellen) und Kehricht (zu 50% als erneuerbar taxiert).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil erneuerbarer Energie am Bruttoenergieverbrauch",
		"thema": "08 Energie",
		"unterthema": "Erneuerbare",
		"kuerzel": "I.08.3.09672",
		"kennzahlenset": "Schluesselindikatoren",
		"kuerzelKunde": "4",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-04-13T08:21:45",
		"id": 9672
	},
	{
		"template": "line001",
		"data-id": 9673,
		"chart-id": 9673,
		"filter": "",
		"parentId": null,
		"children": [
			9784
		],
		"title": "Bevölkerungsbestand",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Ende 2022 beträgt der Bevölkerungsbestand im Kanton Basel-Stadt 204 550 Personen.<br><br><b>Zielwert:</b> 220 000 Einwohnende bis 2035<br><i>(Grundlage: Richtplan Basel-Stadt)</i><br><br><b>Ampelwerte:</b><br>\tGrün: \tWert auf/über Zielpfad und Wachstum gleich/stärker als Zielpfad<br>Gelb: \tWert auf/über Zielpfad und Wachstum geringer als Zielpfad<br>\tbzw. Wert unter Zielpfad und Wachstum gleich/stärker als Zielpfad<br>Rot: \tWert unter Zielpfad und Wachstum geringer als Zielpfad",
		"erlaeuterungen": "Angaben zur Erhebung der Bevölkerungszahlen: 1774-1847: Kantonale Volkszählungen; 1850-1900: Eidgenössische Volkszählungen; 1901-2011: Fortschreibung der kantonalen Bevölkerungsstatistik; ab 2012: Auswertungen aus dem kantonalen Einwohnerregister.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bevölkerungsbestand",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.09673",
		"kennzahlenset": "Schluesselindikatoren",
		"kuerzelKunde": "1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-04-13T08:21:42",
		"id": 9673
	},
	{
		"template": "line001",
		"data-id": 9674,
		"chart-id": 9674,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "CO<sub>2</sub>-Emissionen",
		"subtitle": "in Tonnen pro Kopf, Basel-Stadt",
		"lesehilfe": "Die energiebedingten CO<sub>2</sub>-Emissionen nahmen zwischen 2012 und 2020 von 4,32 Tonnen auf 3,11 Tonnen CO<sub>2</sub> pro Kopf ab.<br><br><b>Zielwert:</b> Netto-Null bis 2037<br><b>\tZielpfad:</b> lineare Reduktion (jährlich ca. 0,2 Tonnen/ Person)<br><i>(Grundlage: Gegenvorschlag des Grossen Rates vom 14.9.2022 zur Klimagerechtigkeitsinitiative, angenommen an Volksabstimmung vom 27. November 2022)</i><br><br><b>Ampelwerte:</b><br>\tGrün: \tWert auf/unter Zielpfad und Reduktion gleich/stärker als Zielpfad<br>Gelb: \tWert auf/unter Zielpfad und Reduktion geringer als Zielpfad oder Wert über Zielpfad und Reduktion gleich/stärker als Zielpfad<br>Rot: \tWert über Zielpfad und Reduktion geringer als Zielpfad",
		"erlaeuterungen": "Die CO<sub>2</sub>-Emissionen berechnen sich aus dem Bruttoenergieverbrauch der verschiedenen Energieträger multipliziert mit dem jeweiligen Emissionskoeffizienten von CO<sub>2</sub>. Erneuerbare Brennstoffe wie Holz oder Biogas gelten als CO<sub>2</sub>-neutral und sind nicht in den Emissionen eingeschlossen. Der in der Kehrichtverwertungsanlage (KVA) verbrannte Hauskehricht wird zu 50% als erneuerbar gezählt und ist somit nur zur Hälfte in die CO<sub>2</sub>-Emissionen eingerechnet. Der Pro-Kopf-Verbrauch basiert auf der mittleren Wohnbevölkerung eines Jahres.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "CO<sub>2</sub>-Emissionen",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Luftschadstoffe",
		"kuerzel": "I.02.5.09674",
		"kennzahlenset": "Schluesselindikatoren",
		"kuerzelKunde": "3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-04-13T08:21:45",
		"id": 9674
	},
	{
		"template": "template001",
		"data-id": 9675,
		"chart-id": 9675,
		"filter": "",
		"parentId": null,
		"children": [
			9786
		],
		"title": "Kantonaler Wettbewerbsindikator (KWI)",
		"subtitle": "Basel-Stadt im kantonalen Vergleich, 2021",
		"lesehilfe": "Im Jahr 2021 liegt Basel-Stadt beim Kantonalen Wettbewerbsindikator (KWI) der UBS mit einem Wert von 97,9 auf Rang 2 aller Schweizer Kantone. Der Nachbarkanton Basel-Landschaft belegt Rang 7.<br><br><b>Zielwert:</b> Mindestens zweiter Platz im Kantonsvergleich<br><i>(Grundlage: Vorschlag Legislaturplankonferenz)</i><br><br><b>Ampelwerte:</b><br>\tGrün: \t1. und 2. Platz<br>Gelb: \t3. Platz<br>Rot: \t4. Platz oder schlechter",
		"erlaeuterungen": "Der Kantonale Wettbewerbsindikator (KWI) gibt Aufschluss über das relative längerfristige Wachstumspotenzial eines Kantons. Die Wettbewerbsfähigkeit eines Kantons beschreibt sein Potenzial für eine nachhaltige Steigerung seiner Wirtschaftsleistung. Kantone mit einer hohen relativen Wettbewerbsfähigkeit dürften längerfristig stärker wachsen als die Schweizer Gesamtwirtschaft. Hingegen ist in Kantonen mit einer tiefen relativen Wettbewerbsfähigkeit mit einem unterdurchschnittlichen Wachstum zu rechnen. Der KWI basiert auf der vergleichenden Analyse von acht Säulen mit insgesamt über 50 Variablen. Die Variablen werden gewichtet, aggregiert und normiert, sodass jeder Kanton für jede Säule eine Punktzahl zwischen 0 und 100 erhält. Zur Ermittlung des KWI wird für jeden Kanton der Durchschnitt aus den Punktzahlen der acht Säulen errechnet und so normiert, dass der höchste kantonale Durchschnittswert 100 beträgt.",
		"quellenangabe": [
			"UBS Switzerland AG"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Schweiz"
		],
		"description": "Kantonaler Wettbewerbsindikator (KWI)",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.09675",
		"kennzahlenset": "Schluesselindikatoren",
		"kuerzelKunde": "5",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-04-13T08:21:46",
		"id": 9675
	},
	{
		"template": "template001",
		"data-id": 9676,
		"chart-id": 9676,
		"filter": "",
		"parentId": null,
		"children": [
			9787
		],
		"title": "Beschäftigte",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Zahl der Beschäftigten stieg zwischen 2011 und 2020 um 3,1% von 183 183 auf 188 778.<br><br><b>Zielwert:</b> 220 000 Beschäftige bis 2035<br><i>(Grundlage: Richtplan Basel-Stadt)</i><br><b>Zielpfad:</b> lineares Wachstum (ca. 1 700 Beschäftigte / Jahr)<br><br><b>Ampelwerte:</b><br>\tGrün: \tZahl auf/über Zielpfad und Wachstum gleich/stärker als Zielpfad<br>Gelb: \tZahl auf/über Zielpfad und Wachstum geringer als Zielpfad<br>\tbzw. Zahl unter Zielpfad und Wachstum gleich/stärker als Zielpfad<br>Rot: \tZahl unter Zielpfad und Wachstum geringer als Zielpfad",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und dafür einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beschäftigte",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.09676",
		"kennzahlenset": "Schluesselindikatoren",
		"kuerzelKunde": "6",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-04-13T08:21:46",
		"id": 9676
	},
	{
		"template": "line001",
		"data-id": 9677,
		"chart-id": 9677,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Arbeitslosenquote",
		"subtitle": "Basel-Stadt und Schweiz",
		"lesehilfe": "<b>Zielwert:</b> Arbeitslosenquote BS entwickelt sich gleich oder besser als Ar-beitslosenquote CH<br><i>(Grundlage: Vorschlag Legislaturplankonferenz)</i><br><br><b>Ampelwerte:</b><br>\tGrün: \tQuote BS entwickelt sich gleich oder besser als Quote CH<br>Gelb: \tQuote BS entwickelt sich um max. 0,3 Prozentpunkte schlechter als Quote CH<br>Rot: \tQuote BS entwickelt sich um mehr als 0,3 Prozentpunkte schlechter als Quote CH",
		"erlaeuterungen": "Als Arbeitslose gelten Personen, welche bei einem Regionalen Arbeitsvermittlungszentrum (RAV) gemeldet sind, keine Stelle haben und sofort vermittelbar sind. Die Arbeitslosenquote berechnet sich aus der Anzahl Arbeitsloser geteilt durch die Anzahl Erwerbspersonen mal 100.",
		"quellenangabe": [
			"Staatssekretariat für Wirtschaft SECO, Arbeitslosenstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitslosenquote",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Arbeitslose",
		"kuerzel": "I.03.4.09677",
		"kennzahlenset": "Schluesselindikatoren",
		"kuerzelKunde": "7",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-04-13T08:21:47",
		"id": 9677
	},
	{
		"template": "line001",
		"data-id": 9679,
		"chart-id": 9679,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Lebenserwartung bei Geburt",
		"subtitle": "in Jahren, Basel-Stadt",
		"lesehilfe": "<b>Zielwert:</b> Stabiles Verhältnis der Lebenserwartung Basel-Stadt zur Lebenserwartung Schweiz<br><i>(Vorschlag Legislaturplankonferenz)</i><br><br><b>Ampelwerte:</b><br>\tGrün: \tWert BS steigt/bleibt gleich und Wert BS entwickelt sich nicht schlechter als in der CH <br>Gelb: \tWert BS steigt/bleibt gleich, aber Wert BS entwickelt sich schlechter als in der CH<br>Rot: \tWert BS fällt",
		"erlaeuterungen": "Die Lebenserwartung bei Geburt entspricht der durchschnittlichen Zahl der zu erwartenden Lebensjahre eines Neugeborenen unter der Voraussetzung, dass die altersspezifischen Sterblichkeitsverhältnisse eines bestimmten Kalenderjahres während des ganzen Lebens konstant bleiben.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Lebenserwartung bei Geburt",
		"thema": "14 Gesundheit",
		"unterthema": "Sterblichkeit",
		"kuerzel": "I.14.3.09679",
		"kennzahlenset": "Schluesselindikatoren",
		"kuerzelKunde": "8",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-04-13T08:21:47",
		"id": 9679
	},
	{
		"template": "line001",
		"data-id": 9680,
		"chart-id": 9680,
		"filter": "",
		"parentId": null,
		"children": [
			9785
		],
		"title": "Sicherheitsgefühl im Alltag",
		"subtitle": "«Wie sicher fühlen Sie sich ganz allgemein im Alltag?», Basel-Stadt",
		"lesehilfe": "94,9% der 2019 Befragten fühlen sich im Alltag sehr oder eher sicher.<br><br><b>Zielwert:</b> Mehr als 90% der Bevölkerung fühlen sich im Alltag «sicher» und/oder «eher sicher»<br><i>(Grundlage: Vorschlag Legislaturplankonferenz)</i><br><br><b>Ampelwerte:</b><br>\tGrün: \tWert > 90%<br>Gelb: \tWert = 80 bis 90%<br>Rot: \tWert < 80%",
		"erlaeuterungen": "Alle vier Jahre (bis 2007 alle zwei) wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Sicherheitsgefühl im Alltag",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.09680",
		"kennzahlenset": "Schluesselindikatoren",
		"kuerzelKunde": "10",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-04-13T08:21:42",
		"id": 9680
	},
	{
		"template": "line001",
		"data-id": 9682,
		"chart-id": 9682,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Abschlussquote der Sekundarstufe II",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Der Anteil der Jugendlichen, die bis zum 25. Altersjahr einen Erstabschluss der Sekundarstufe II erworben haben, lag 2019 in Basel-Stadt bei 85,0%.<br><br><b>Zielwert:</b> 95 % der Jugendlichen haben bis zum Alter von 25 Jahren <br>einen Abschluss auf Stufe Sek II<br><i>(Grundlage: politisches Ziel von Bund, Kantonen und Arbeitnehmerorganisationen)</i><br><br><b>Ampelwerte:</b><br>\tGrün: \tWert ≥ 95%<br>Gelb: \tWert = 90 bis 94,9%<br>Rot: \tWert < 90",
		"erlaeuterungen": "Bei der Berechnung werden die folgenden Abschlüsse berücksichtigt: - Berufliche Grundbildung: eidgenössische Fähigkeitszeugnisse und Berufsatteste gemäss der Statistik der beruflichen Grundbildung (SBG); - Allgemeinbildung: gymnasiale Maturitätszeugnisse, Fachmittelschulausweise und Abschlüsse der internationalen Schulen in der Schweiz gemäss der Statistik der Bildungsabschlüsse (SBA). Die Referenzbevölkerung besteht aus allen Personen, die im Alter des Beendens der obligatorischen Schule in der Schweiz wohnten. Ausgenommen sind Grenzgängerinnen und Grenzgänger sowie Personen, die im Zuge der jüngsten Zuwanderung nach beendeter obligatorischer Schulzeit in die Schweiz gekommen sind. Jugendliche, die das Land vor dem Erwerb eines Abschlusses auf der Sekundarstufe II verlassen haben, werden ebenfalls nicht berücksichtigt. Ausserdem werden bei der Abschlussquote nur Personen bis zu einem Alter von 25 Jahren betrachtet. Für eine bessere Stabilität der Ergebnisse wird ein Dreijahresdurchschnitt berechnet. Die Quote für das Jahr t entspricht folglich dem Durchschnitt der für die Jahre t-1, t und t+1 erhaltenen Werte.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Längsschnittanalysen im Bildungsbereich (LABB)"
		],
		"externalLinks": [
			"Weiterführende Informationen zum Thema finden Sie auf der <a href = 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bildung-wissenschaft/bildungsindikatoren/themen/bildungserfolg/abschlussquote-sekii.html' target = '_blank'>Homepage des Bundesamtes für Statistik</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Abschlussquote der Sekundarstufe II",
		"thema": "15 Bildung",
		"unterthema": "Bildungsabschlüsse",
		"kuerzel": "I.15.7.09682",
		"kennzahlenset": "Schluesselindikatoren",
		"kuerzelKunde": "11",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-04-13T08:21:43",
		"id": 9682
	},
	{
		"template": "template001",
		"data-id": 9684,
		"chart-id": 9684,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Nettowohnungsproduktion seit 2019",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "<b>Zielwert:</b> 10 000 Wohnungen bis 2035<br><i>(Grundlage: gekoppelt an Richtplanziel 220 000 Einwohnende bis 2035; berechnet auf Basis des aktuellen Wohnungsbestands und der durchschnittlichen Personenbelegung pro Wohnung)</i><br><br><b>Ampelwerte:</b><br>\tGrün: \tZahl auf/über Zielpfad und Wachstum gleich/stärker als Zielpfad<br>Gelb: \tZahl auf/über Zielpfad und Wachstum geringer als Zielpfad \tbzw. Zahl unter Zielpfad und Wachstum gleich/stärker als Zielpfad<br>Rot: \tZahl unter Zielpfad und Wachstum geringer als Zielpfad",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettowohnungsproduktion seit 2019",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.09684",
		"kennzahlenset": "Schluesselindikatoren",
		"kuerzelKunde": "12",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-04-13T08:21:43",
		"id": 9684
	},
	{
		"template": "line001",
		"data-id": 9686,
		"chart-id": 9686,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mietpreis- und Einkommensindex",
		"subtitle": "Basel-Stadt, Indexwert (Basis 2015 = 100)",
		"lesehilfe": "<b>Zielwert:</b> Mietpreise steigen weniger stark als Medianeinkommen<br><i>(Grundlage: Vorschlag Legislaturplankonferenz)</i><br><br><b>Ampelwerte:</b><br>\tGrün: \tMietpreise steigen weniger stark als Medianeinkommen<br>Gelb: \tMietpreise und Medianeinkommen steigen gleich stark<br>Rot: \tMietpreise steigen stärker als Medianeinkommen",
		"erlaeuterungen": "Mietpreisindex: Geschichtete Zufallsstichprobe, die 5% der Miet- und Genossenschaftswohnungen mit 1 bis 6 Zimmern umfasst, welche dauerhaft zu Wohnzwecken vermietet werden. Es wird der Wert im November des jeweiligen Jahres ausgewiesen. <br>Reineinkommen: Median wird pro Veranlagung berechnet (Ehepaare werden bspw. gemeinsam veranlagt). Über den Betrachtungszeitraum gab es zahlreiche Veränderungen in der Steuergesetzgebung, die einen Einfluss auf die Berechnung des Reineinkommens haben können, etwa durch erhöhte Abzugsmöglichkeiten (z. B. für Berufskosten).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik",
			"Statistisches Amt Basel-Stadt, Mietpreiserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mietpreis- und Einkommensindex",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Mietpreise",
		"kuerzel": "I.09.3.09686",
		"kennzahlenset": "Schluesselindikatoren",
		"kuerzelKunde": "13",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_013",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-04-13T08:21:43",
		"id": 9686
	},
	{
		"template": "template001",
		"data-id": 9687,
		"chart-id": 9687,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Verkehrsleistungsindex MIV im Stadtstrassennetz",
		"subtitle": "Indexwert (Basis 2010 = 100)",
		"lesehilfe": "<b>Zielwert:</b> nicht grösser als Indexwert 2019<br><b>Zielpfad:</b> lineares Wachstum (ca. 1 200 Einwohnende / Jahr)<br><br><i>(Grundlage: USG §13 bzw. VuV §5)</i><br><br><b>Ampelwerte:</b><br>\tGrün: \tWert steigt nicht und liegt tiefer/gleich Indexwert 2019<br>Gelb: \tWert steigt und liegt tiefer/gleich Indexwert 2019 oder Wert steigt nicht und liegt über Indexwert 2019<br>Rot: \tWert steigt und liegt über Indexwert 2019",
		"erlaeuterungen": "Der Verkehrsleistungsindex erfasst die Veränderung der Fahrleistung der verschiedenen Verkehrsmittel im ganzen Kantonsgebiet. Die Veränderung gegenüber dem Referenzjahr 2010 wird in Prozent dargestellt (indexiert, 2010 = 100). <br><br>Der Verkehrsleistungsindex basiert auf den an automatischen Zählstellen erfassten Verkehrsaufkommen, aus welchen mit Modellen die Verkehrsleistung für den gesamten Kanton abgeleitet werden. Jede Zählstelle wird auf Basis des Gesamtverkehrsmodells der Region Basel gewichtet. Der Index für den motorisierten Individualverkehr (MIV) berechnet sich anhand von rund 40 Dauerzählstellen des Kantons Basel-Stadt, des Kantons Basel-Landschaft und des Bundesamts für Strassen. Er umfasst die Verkehrsleistung aller Motorfahrzeuge auf baselstädtischem Kantonsgebiet (inkl. Lastwagen, Lieferwagen, Motorrädern), aber ohne Linienbusse, Motorfahrräder und E-Bikes. Der MIV Stadtstrassennetz entspricht der Verkehrsleistung auf allen Strassen des Kantonsgebiets ohne die Autobahnen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'Verkehrspolitisches Leitbild Kanton Basel-Stadt' target = '_blank'><a href=https://www.mobilitaet.bs.ch/gesamtverkehr/mobilitaetsstrategie/verkehrspolitische-grunds-tze.html target=_blank rel=nofollow>https://www.mobilitaet.bs.ch/gesamtverkehr/mobilitaetsstrategie/verkehrspolitische-grunds-tze.html</a></a>",
			"Weitere Informationen zum Indikator: <a href = 'http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-05-0501' target = '_blank'>Umweltbericht beider Basel</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Verkehrsleistungsindex MIV im Stadtstrassennetz",
		"thema": "11 Verkehr",
		"unterthema": "Mobilitätsverhalten",
		"kuerzel": "I.11.6.09687",
		"kennzahlenset": "Schluesselindikatoren",
		"kuerzelKunde": "14",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_014",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-04-13T08:21:44",
		"id": 9687
	},
	{
		"template": "line001",
		"data-id": 9693,
		"chart-id": 9693,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sozialhilfequote",
		"subtitle": "Stadt Basel im Vergleich mit anderen Städten",
		"lesehilfe": "<b>Zielwert:</b> Sozialhilfequote Basel entwickelt sich gleich oder besser im Ver-gleich zu Zürich, Bern, Winterthur und Biel <br><i>(Grundlage: ??)</i><br><br><b>Ampelwerte:</b><br>\tGrün: \tQuote Basel entwickelt sich gleich oder besser im Vergleich zu Vergleichsstädten<br>Gelb: \tQuote Basel entwickelt sich leicht schlechter (≤ 0.3 %) im Vergleich zu Vergleichsstädten<br>Rot: \tQuote Basel entwickelt sich klar schlechter (> 0.3 %) im Vergleich zu Vergleichsstädten",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Sozialhilfequote",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09693",
		"kennzahlenset": "Schluesselindikatoren",
		"kuerzelKunde": "9",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-04-13T08:21:48",
		"id": 9693
	}
];