var indikatorensetData = [
	{
		"template": "template001",
		"data-id": 4152,
		"chart-id": 4152,
		"filter": "",
		"parentId": null,
		"children": [
			9292,
			9921
		],
		"title": "Anzahl und Quote der Haushalte mit Familienmietzinsbeiträgen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Ende des Jahres 2023 beziehen 2 144 Haushalte Familienmietzinsbeiträge. Dies entspricht 2,1% aller Haushalte im Kanton Basel-Stadt. Ende 2022 waren es ebenfalls 2,1%. Die Anzahl der mit Familienmietzinsbeiträgen unterstützten Haushalte geht seit 2021 zurück.",
		"erlaeuterungen": "Die Quote der Haushalte mit Familienmietzinsbeiträgen (FAMI) entspricht dem Verhältnis der Anzahl Haushalte mit Mietzinsbeiträgen zur Gesamtzahl der Haushalte (exklusive Haushalte in Wohnungen ohne Kocheinrichtung) per Ende des Jahres. Stichtag ist jeweils der 4. Januar des Folgejahres.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Basler Informationssystem Sozialleistungen (BISS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl und Quote der Haushalte mit Familienmietzinsbeiträgen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.4152",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "5.2",
		"stufe1": "Familienmietzinsbeiträge",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-28T09:22:26",
		"id": 4152
	},
	{
		"template": "template001",
		"data-id": 4154,
		"chart-id": 4154,
		"filter": "",
		"parentId": null,
		"children": [
			9924
		],
		"title": "Bestand und Auslastungsquote der Notwohnungen und Wohneinheiten nach WRFG",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Zum Jahresende 2023 stehen 116 Notwohnungen zur Verfügung. Nach WRFG stehen 82 Wohneinheiten bereit. Damit stehen insgesamt 198 Wohnmöglichkeiten zur Verfügung. Über alle Wohnmöglichkeiten gesehen, resultiert zum Ende des Jahres 2023 eine Auslastungsquote von 90%.",
		"erlaeuterungen": "Bestand am Ende des Jahres. Die Sozialhilfe des Kantons Basel-Stadt kann Wohnungen einerseits an Familien und Personen in Not, andererseits im Rahmen des Sozialen Wohnens nach dem Gesetz über die Wohnraumförderung (WRFG) vermieten. Das Angebot des Sozialen Wohnens nach WRFG umfasst auch Einzelzimmer. Die Auslastungsquote unterscheidet nicht zwischen Notwohnen und Sozialem Wohnen. Sie entspricht dem Verhältnis der belegten Wohnungen und Einzelzimmer zum Gesamtbestand an Wohnmöglichkeiten im Sinne des Notwohnens und des Sozialen Wohnens nach WRFG. Die Datenquelle wurde 2024 für den gesamten Beobachtungszeitraum rückwirkend angepasst und die Datenbasis vereinheitlicht.",
		"quellenangabe": [
			"Sozialhilfe des Kantons Basel-Stadt, Wohnen"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bestand und Auslastungsquote der Notwohnungen und Wohneinheiten nach WRFG",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Notwohnen",
		"kuerzel": "I.13.3.04154",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "7.1",
		"stufe1": "Notwohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-28T09:22:26",
		"id": 4154
	},
	{
		"template": "line001",
		"data-id": 9289,
		"chart-id": 9289,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sozialhilfequote nach Gemeinde",
		"subtitle": "",
		"lesehilfe": "Die kantonale Sozialhilfequote liegt 2022 bei 5,0%. Sie sinkt seit dem Jahr 2017 kontinuierlich. Die Stadt Basel weist 2022 eine Quote von 5,3% aus, Riehen 2,7% und Bettingen 1,7%.",
		"erlaeuterungen": "Die Sozialhilfequote zeigt den prozentualen Anteil der Sozialhilfebeziehenden an der jeweiligen Bevölkerungsgruppe gemäss Bevölkerungsstand am Ende des Jahres. Als Sozialhilfebeziehende werden alle Personen gezählt, die im Verlaufe eines Jahres mindestens eine Sozialhilfeleistung erhalten haben. Es werden alle Beziehenden mit Dossiertyp Sozialhilfefall sowie Anerkannte Flüchtlinge (FL), Vorläufig Aufgenommene (VA) und Vorläufig aufgenommene Flüchtlinge (VA FL) mit einer Aufenthaltsdauer von mehr als fünf bzw. sieben Jahren (FL 5+, VA 7+, VA FL 7+) berücksichtigt. <br>Die Berechnungsmethode wurde 2022 für die Jahre ab 2017 rückwirkend angepasst. Bis 2017 galt für die Anzahl Beziehender folgende Definition: Alle Personen mit Dossiertyp «Sozialhilfefall», «Asyl» oder «Flüchtling» die im Verlauf eines Jahres mindestens eine Sozialhilfeleistung erhalten haben. Auf die Werte von Riehen und Bettingen hat diese Umstellung keinen Einfluss.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Sozialhilfequote nach Gemeinde",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe und Notwohnen",
		"kuerzel": "",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "1-03",
		"stufe1": "Kernindikatoren",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-05-25T09:11:17",
		"id": 9289
	},
	{
		"template": "line001",
		"data-id": 9291,
		"chart-id": 9291,
		"filter": "",
		"parentId": "6055",
		"children": [],
		"title": "Angebotene Plätze für Tagesbetreuung und Tagesstrukturen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Anzahl angebotener Plätze für die Tagesbetreuung hat in den vergangenen Jahren ein stetiges Wachstum erfahren. Im Oktober 2022 liegt die Platzzahl bei 4 398. Auch die Tagesstrukturen wurden stetig ausgebaut. 2022 bieten die Frühhorte Platz für 656 Kinder, die Mittagsmodule  3 800 und die Nachmittagsmodule 3 450 Plätze.",
		"erlaeuterungen": "Tagesstrukturen: Stichwoche im September. Frühhorte werden an einigen Primarschulstandorten angeboten. Die Mittags- und Nachmittagsmodule werden einerseits von schuleigenen und andererseits schulexternen Tagesstrukturen bereitgestellt. In den Sekundarschulen bestehen ebenfalls Verpflegungsangebote und die Möglichkeit, sich nachmittags beaufsichtigt in den Schulräumlichkeiten aufzuhalten. Da bei den Sekundarschulen keine Anmeldepflicht besteht, existiert keine eindeutige Platzzahl. Die Anzahl Tagesstrukturplätze berücksichtigt dieses Angebot daher nicht.<br>Tagesbetreuung: Plätze in Kindertagesstätten und Tagesfamilien. Stichwoche im Oktober.",
		"quellenangabe": [
			"Erziehungsdepartement Basel-Stadt, Fachstelle Tagesbetreuung",
			"Erziehungsdepartement Basel-Stadt, Fachstelle Tagesstrukturen"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Angebotene Plätze für Tagesbetreuung und Tagesstrukturen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09291",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "1-08",
		"stufe1": "Kernindikatoren",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-05-22T02:05:12",
		"id": 9291
	},
	{
		"template": "line001",
		"data-id": 9294,
		"chart-id": 9294,
		"filter": "",
		"parentId": null,
		"children": [
			9934
		],
		"title": "Beziehende von Prämienverbilligung",
		"subtitle": "inkl. Beziehende von Sozialhilfe und Ergänzungsleistungen, Basel-Stadt",
		"lesehilfe": "Mit 51 711 Beziehenden erhält Ende 2022 ein Viertel aller in Basel-Stadt wohnhaften Personen Prämienverbilligung.",
		"erlaeuterungen": "Bestand per Ende des Jahres. PV: Prämienverbilligung, SH: Sozialhilfe, EL: Ergänzungsleistungen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Amt für Sozialbeiträge Basel-Stadt, Abteilung Prämienverbilligung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Beziehende von Prämienverbilligung",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09294",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "1-06",
		"stufe1": "Kernindikatoren",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-04T11:56:28",
		"id": 9294
	},
	{
		"template": "line001",
		"data-id": 9295,
		"chart-id": 9295,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sozialhilfequote nach Altersgruppe",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Minderjährige weisen 2022 mit 8,5% die höchste Sozialhilfequote im Kanton auf. Mit 4,8% ist die Sozialhilfequote der 26- bis 35-Jährigen die tiefste aller Altersgruppen im erwerbsfähigen Alter.",
		"erlaeuterungen": "Die Sozialhilfequote zeigt den prozentualen Anteil der Sozialhilfebeziehenden an der jeweiligen Bevölkerungsgruppe gemäss Stand am Ende des Jahres. Als Sozialhilfebeziehende werden alle Personen gezählt, die im Verlaufe eines Jahres mindestens eine Leistung der Sozialhilfe erhalten haben. Es werden alle Beziehenden mit Dossiertyp Sozialhilfefall sowie Anerkannte Flüchtlinge (FL), Vorläufig Aufgenommene (VA) und Vorläufig aufgenommene Flüchtlinge (VA FL) mit einer Aufenthaltsdauer von mehr als 5 bzw. 7 Jahren (FL 5+, VA 7+, VA FL 7+) berücksichtigt<br>Die Berechnungsmethode wurde 2022 für die Jahre ab 2017 rückwirkend angepasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Sozialhilfequote nach Altersgruppe",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09295",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "1-04",
		"stufe1": "Kernindikatoren",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-05-25T07:08:40",
		"id": 9295
	},
	{
		"template": "line001",
		"data-id": 9919,
		"chart-id": 9919,
		"filter": "",
		"parentId": null,
		"children": [
			10031
		],
		"title": "Anteil Beziehende von EL und Beihilfen an allen Beziehenden einer AHV- oder IV-Rente per Ende Jahr",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "69% der Personen mit IV erhielten zum Jahresende 2022 Ergänzungsleistungen (EL), 41% werden mittels Beihilfen zur IV unterstützt. Bei den Personen mit AHV<br>liegen diese Anteile bei 21% bzw. 13%.",
		"erlaeuterungen": "Anteil AHV-/IV-Beziehende mit Ergänzungsleistungen (EL) an allen AHV-/IV-Rentnern per Ende Jahr.",
		"quellenangabe": [
			"Amt für Sozialbeiträge Basel-Stadt, Abteilung Ergänzungsleistungen",
			"Bundesamt für Sozialversicherungen (BSV)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil Beziehende von EL und Beihilfen an allen Beziehenden einer AHV- oder IV-Rente per Ende Jahr",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09919",
		"kennzahlenset": "Soziales",
		"kuerzelKunde": "",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-11-13T09:13:27",
		"id": 9919
	}
];