var indikatorensetData = [
	{
		"template": "spider001",
		"data-id": 12609,
		"chart-id": 6640,
		"filter": "",
		"parentId": "6640",
		"children": [],
		"title": "St. Johann - Quartierradar",
		"subtitle": "",
		"lesehilfe": "Das Wohnviertel St. Johann verzeichnet einen relativ hohen Anteil Ausländer und Sozialhilfeempfänger. Der Altersquotient ist niedrig. Die Wohnfläche pro Kopf ist vergleichsweise gering. Die Anzahl Arbeitsplätze pro Kopf liegt im oberen Drittel, die Erwerbstätigenquote im mittleren Drittel.",
		"erlaeuterungen": "Die Grafik fasst 16 Indikatoren zusammen. Die Indikatoren sind den drei Bereichen <font color=\"923F8D\">Gesellschaft und Soziales</font>, <font color=\"68AB2B\">Raum und Umwelt</font> sowie <font color=\"689199\">Wirtschaft und Arbeit</font> zugeordnet. Die Werte der Indikatoren sind als Ränge im Vergleich zu allen anderen Basler Wohnvierteln und Gemeinden ausgewiesen. Das Wohnviertel oder die Gemeinde mit dem niedrigsten Wert des Indikators erhält Rang 1, mit dem höchsten Wert Rang 21 zugewiesen. Je grösser die graue Fläche, desto öfter erreicht das Wohnviertel oder die Gemeinde hohe Ränge bei den Indikatoren. <a href =\" https://statistik.bs.ch/files/berichte-analysen/Methodik-Quartierradar.pdf \" target = '_blank'>Zur Definition der einzelnen Indikatoren </a>",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "St. Johann - Quartierradar",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.12609",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "1.02",
		"stufe1": "1 Übersicht",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:10:52",
		"id": 12609
	},
	{
		"template": "line001",
		"data-id": 12610,
		"chart-id": 12610,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "In den Bezirken Pestalozzi (+2,4%), Kannenfeld (+0,2%) und Landskron (-1,5%) ist die Bevölkerung 2023 im Vergleich zu 2004 nahezu gleichgeblieben, die Bezirke Lysbüchel (+70,9%) und Friedmatt (+12,6%) verzeichneten hingegen grössere Zunahmen. Im Gesamtkanton hat 2023 die Bevölkerungszahl im Vergleich zu 2004 um 9,5% zugenommen.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnbevölkerung",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.01",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:10:53",
		"id": 12610
	},
	{
		"template": "populationPyramid001",
		"data-id": 12611,
		"chart-id": 12611,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung nach Alter und Geschlecht",
		"subtitle": "Bezirk Friedmatt, 2023",
		"lesehilfe": "Im Bezirk Friedmatt des Wohnviertels St. Johann sind die grössten Fünfjahresklassen diejenigen der 25- bis 49-Jährigen, was auch der Bevölkerungsverteilung im Gesamtkanton entspricht.",
		"erlaeuterungen": "Die Bevölkerungspyramide zeigt die Wohnbevölkerung am Jahresende nach Alter (Fünfjahresklassen) und Geschlecht.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnbevölkerung nach Alter und Geschlecht",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.02a",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:10:54",
		"id": 12611
	},
	{
		"template": "line001",
		"data-id": 12612,
		"chart-id": 12612,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Jugendquotient",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Zwischen 2004 und 2023 ist der Jugendquotient im Bezirk Landskron von 28,2 auf 21,8 gesunken, im Bezirk Lysbüchel von 29,3 auf 31,6 gestiegen. Im Jahr 2023 beträgt der Jugendquotient in der Stadt Basel 25,9.",
		"erlaeuterungen": "Der Jugendquotient beschreibt das Verhältnis der Personen im Alter von 19 oder weniger Jahren zu jenen im erwerbsfähigen Alter zwischen 20 und 64 Jahren. Das Verhältnis wird pro 100 Personen zwischen 20 und 64 Jahren ausgewiesen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel",
			"Agglomeration"
		],
		"description": "Jugendquotient",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.03",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:10:58",
		"id": 12612
	},
	{
		"template": "line001",
		"data-id": 12613,
		"chart-id": 12613,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Altersquotient",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Der Altersquotient ist 2023 im Bezirk Friedmatt am höchsten (42,3) und im Bezirk Lysbüchel am tiefsten (8,9). Im Friedmattbezirk ist er verglichen mit 2004 am stärksten gesunken (2004: 48,2).",
		"erlaeuterungen": "Der Altersquotient beschreibt das Verhältnis der Personen im Alter von 65 oder mehr Jahren zu jenen im erwerbsfähigen Alter zwischen 20 und 64 Jahren. Das Verhältnis wird pro 100 Personen zwischen 20 und 64 Jahren ausgewiesen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel",
			"Agglomeration"
		],
		"description": "Altersquotient",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.04",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:10:58",
		"id": 12613
	},
	{
		"template": "line001",
		"data-id": 12614,
		"chart-id": 12614,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Ausländeranteil",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "In den Bezirken Kannenfeld, Friedmatt und Pestalozzi ist der Ausländeranteil in den letzten Jahren in einem ähnlichen Umfang gestiegen wie in der Stadt Basel. Eine Abnahme zeigt sich in den Bezirken Lysbüchel und Landskron.",
		"erlaeuterungen": "Bevölkerungsbestand zum Jahresende.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Ausländeranteil",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.05",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:10:59",
		"id": 12614
	},
	{
		"template": "template001",
		"data-id": 12615,
		"chart-id": 12615,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Ausländer nach Staatsangehörigkeit",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "In den Bezirken Pestalozzi und Kannenfeld bildeten in den letzten Jahren jeweils die Deutschen die grösste ausländische Bevölkerungsgruppe. In den Bezirken Lysbüchel und Landskron waren es Personen aus den EU-17 + EFTA-Staaten und im Bezirk Friedmatt Türkinnen und Türken.",
		"erlaeuterungen": "Bevölkerungsbestand zum Jahresende.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Ausländer nach Staatsangehörigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.07",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:01",
		"id": 12615
	},
	{
		"template": "line001",
		"data-id": 12616,
		"chart-id": 12616,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sesshaftigkeit",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Die höchste Sesshaftigkeit im Wohnviertel St. Johann liegt Ende 2023 mit 36,6% im Bezirk Friedmatt. Gegenüber 2020 ist sie dort um fast drei Prozentpunkte gesunken. Die niedrigste Sesshaftigkeit weist mit 19,2% der Bezirk Lysbüchel auf.",
		"erlaeuterungen": "Anteil Einwohner, die seit mindestens zehn Jahren an der gleichen Adresse wohnen. Ohne Personen an administrativen Meldeadressen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Sesshaftigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.12616",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.08",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:02",
		"id": 12616
	},
	{
		"template": "template001",
		"data-id": 12617,
		"chart-id": 12617,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Haushalte nach Art des Haushalts",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Der Anteil Familienhaushalte ist 2023 im Bezirk Friedmatt mit 56% am grössten. In den Bezirken Pestalozzi und Landskron liegt der Anteil Einpersonenhaushalte jeweils knapp über 50%.",
		"erlaeuterungen": "Personen, die in der gleichen Wohnung leben, bilden einen Haushalt. Haushalte werden unterteilt in Privathaushalte und Kollektivhaushalte. Hier werden nur Privathaushalte betrachtet. Die Gruppe «Andere Haushalte» umfasst Mehrpersonenhaushalte wie Wohngemeinschaften und unverheiratete Paare ohne ein gemeinsames Kind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Haushalte nach Art des Haushalts",
		"thema": "01 Bevölkerung",
		"unterthema": "Haushalte",
		"kuerzel": "I.01.TRKE.12617",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.01",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:15",
		"id": 12617
	},
	{
		"template": "template001",
		"data-id": 12618,
		"chart-id": 12618,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wanderungssaldo nach Zuzugs- und Wegzugsort",
		"subtitle": "Wohnviertel St. Johann",
		"lesehilfe": "Im Jahr 2023 weist das Wohnviertel St. Johann einen positiven Wanderungssaldo auf. Dieser ist auf Zuzüge aus dem Ausland zurückzuführen.",
		"erlaeuterungen": "Schweizerische ausserkantonale Agglomerationsgemeinden: Aesch, Allschwil, Arboldswil, Arisdorf, Arlesheim, Augst, Bärschwil, Bättwil, Bennwil, Biel-Benken, Binningen, Birsfelden, Blauen, Böckten, Bottmingen, Breitenbach, Bretzwil, Brislach, Bubendorf, Buckten, Büren, Burg im Leimental, Büsserach, Buus, Diepflingen, Dittingen, Dornach, Duggingen, Ettingen, Fehren, Frenkendorf, Füllinsdorf, Gelterkinden, Gempen, Giebenach, Grellingen, Hellikon, Hemmiken, Hersberg, Himmelried, Hochwald, Hofstetten-Flüh, Hölstein, Itingen, Kaiseraugst, Känerkinden, Kleinlützel, Lampenberg, Laufen, Lausen, Lauwil, Liestal, Lupsingen, Magden, Maisprach, Meltingen, Metzerlen-Mariastein, Möhlin, Mumpf, Münchenstein, Muttenz, Nenzlingen, Niederdorf, Nuglar-St. Pantaleon, Nunningen, Nusshof, Oberdorf, Obermumpf, Oberwil, Olsberg, Ormalingen, Pfeffingen, Pratteln, Ramlinsburg, Reigoldswil, Reinach, Rheinfelden, Rickenbach, Rodersdorf, Röschenz, Rümlingen, Rünenberg, Schönenbuch, Seltisberg, Seewen, Sissach, Tecknau, Tenniken, Therwil, Titterten, Thürnen, Wahlen, Wegenstetten, Wenslingen, Wintersingen, Witterswil, Wittinsburg, Zeiningen, Ziefen, Zullwil, Zunzgen, Zuzgen und Zwingen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wanderungssaldo nach Zuzugs- und Wegzugsort",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.09",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_013",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:03",
		"id": 12618
	},
	{
		"template": "line001",
		"data-id": 12619,
		"chart-id": 12619,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Segregationsindex nach Staatsangehörigkeit",
		"subtitle": "Wohnviertel St. Johann",
		"lesehilfe": "Im Jahr 2023 weisen im Wohnviertel St. Johann Personen aus arabischen Ländern (41,9) gefolgt von der Türkei (41,3) und afrikanischen Ländern (38,5) die höchsten Segregationsindices auf. Die hohen Werte bedeuten, dass die Wohnorte dieser Bevölkerungsgruppen am stärksten auf einzelne statistische Blöcke im Wohnviertel St. Johann konzentriert sind. Im Vergleich zum Jahr 2004 haben die Segregationsindices fast aller Ländergruppen abgenommen.",
		"erlaeuterungen": "Der Segregationsindex ist ein Mass zur Beschreibung räumlicher Ungleichverteilungen von Bevölkerungsgruppen. Er misst hier, wie stark die Verteilung einer Bevölkerungsgruppe über das Gebiet des Wohnviertels St. Johann von einer Gleichverteilung abweicht, wobei 0 absolute Gleichverteilung und 100 maximale Segregation bedeutet. Der Wert des Segregationsindexes lässt sich auch als Prozentanteil der betrachteten Gruppe interpretieren, der in einen anderen statistischen Block umziehen müsste, um gleich über das Gebiet des Wohnviertels St. Johann verteilt zu sein wie die übrige Bevölkerung. Ein Segregationsindex von 0 bedeutet, dass der Anteil Personen einer Gruppe am Total der Bevölkerung in jedem Teilgebiet gleich gross ist. Bei kleinräumigen Betrachtungen können die Werte infolge kleiner Gruppengrössen über die Jahre stark schwanken.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Segregationsindex nach Staatsangehörigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.11",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_015",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:04",
		"id": 12619
	},
	{
		"template": "template001",
		"data-id": 12620,
		"chart-id": 12620,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Religionszugehörigkeit",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "In allen Bezirken des Wohnviertels St. Johann bildeten in den Jahren 2021 bis 2023 die Einwohner, die keiner oder einer nicht öffentlich-rechtlichen Religionsgemeinschaft angehören oder deren Zugehörigkeit unbekannt ist, die grösste Gruppe.",
		"erlaeuterungen": "Im Kanton Basel-Stadt sind folgende Religionsgemeinschaften öffentlich-rechtlich anerkannt: evangelisch-reformiert, römisch-katholisch, christkatholisch, israelitisch.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Religionszugehörigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Religionen",
		"kuerzel": "I.01.TRUN.12620",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.06",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:00",
		"id": 12620
	},
	{
		"template": "line001",
		"data-id": 12621,
		"chart-id": 12621,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mittelwert und Median des Reineinkommens",
		"subtitle": "in Franken, Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Im Steuerjahr 2021 beträgt der Mittelwert des Reineinkommens im Bezirk Kannenfeld 65 377 Franken (Median: 49 167), der Mittelwert für Landskron liegt bei 48 535 Franken (Median: 39 469). Über die Jahre hat der Mittelwert im Bezirk Lysbüchel relativ stark zugenommen. Der Mittelwert für die Stadt Basel beträgt 73 241 Franken (Median: 49 666).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen (ordentliche Veranlagung); ohne Auswärtige und ohne Wochenaufenthalter. Einkünfte von Quellenbesteuerten unter 120 000 Franken im Kalenderjahr sind in der Regel in den Auswertungen nicht enthalten.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Mittelwert und Median des Reineinkommens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.12621",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.06",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:12",
		"id": 12621
	},
	{
		"template": "line001",
		"data-id": 12622,
		"chart-id": 12622,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mittelwert und Median des Reinvermögens",
		"subtitle": "in Franken, Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Die Werte für Mittelwert und Median des Reinvermögens sind bei fast allen Wohnbezirken des Wohnviertels St. Johann über die Jahre gestiegen. 2021 verzeichnet der Bezirk Kannenfeld mit 356 919 Franken den höchsten Mittelwert (Median: 27 595 Franken). Den tiefsten weist der Bezirk Landskron mit 94 373 Franken auf (Median: 6 352 Franken). Der Mittelwert für die Stadt Basel beträgt 565 189 Franken (Median: 20 870).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen (ordentliche Veranlagung); ohne Auswärtige und ohne Wochenaufenthalter. Einkünfte von Quellenbesteuerten unter 120 000 Franken im Kalenderjahr sind in der Regel in den Auswertungen nicht enthalten.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Mittelwert und Median des Reinvermögens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.12622",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.07",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:13",
		"id": 12622
	},
	{
		"template": "line001",
		"data-id": 12623,
		"chart-id": 12623,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Steuerertrag durch Zu- und Wegzüger",
		"subtitle": "in Franken, Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Der Saldo aus dem Steuerertrag der Zuzüger und dem Steuerertrag (des Vorjahres) der Wegzüger ist in den Bezirken des Wohnviertels St. Johann überwiegend positiv. Es kommen allerdings auch vereinzelte grössere negative Saldi vor. Im Jahr 2021 ergab sich für den Bezirk Landskron rechnerisch ein Gewinn von rund 517 000 Franken (bei 164 Weg- und 193 Zuzügern), im Bezirk Lysbüchel hingegen ein Verlust von ca. 332 000 Franken (bei 61 Weg- und 61 Zuzügern).",
		"erlaeuterungen": "Beim Steuerverfahren der ordentlichen Veranlagung ist für die kantonale Steuerpflicht der Wohnsitz am 31. Dezember massgebend. Es liegen daher im Wegzugskanton in der Regel keine Steuerdaten für das Jahr des Wegzugs vor. Deshalb ist für Wegziehende jeweils der Steuerertrag des Vorjahres abgebildet. Für die Zugezogenen und die ganzjährig Niedergelassenen werden die Steuerdaten des Berichtsjahres verwendet. <br>Aufgrund verschiedener methodischer Besonderheiten sind quellenbesteuerte Personen in dieser Auswertung zunächst nicht berücksichtig. Erst wenn sie nachträglich ordentlich veranlagt werden (zum Beispiel bei Einkünften von mehr als 120 000 Franken pro Jahr) oder die Niederlassungsbewilligung erhalten und deshalb ins ordentliche Verfahren wechseln, werden sie als Zuzug gezählt und in die Auswertung miteinbezogen – auch wenn sie schon länger im Kanton wohnhaft sind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Steuerertrag durch Zu- und Wegzüger",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.12623",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.08",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:14",
		"id": 12623
	},
	{
		"template": "template001",
		"data-id": 12624,
		"chart-id": 12624,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnungen nach Zimmerzahl",
		"subtitle": "Wohnviertel St. Johann",
		"lesehilfe": "Im Jahr 2023 gab es im Wohnviertel St. Johann 11 442 Wohnungen. 4 049 (35,4%) davon waren Vierzimmerwohnungen.",
		"erlaeuterungen": "Als Zimmer gelten Räume, welche als bauliche Einheit die Wohnung bilden. Küchen, Badezimmer, Toilettenräume, Reduits, Gänge, Veranden usw. gelten nicht als Zimmer. Ebensowenig werden halbe Zimmer gezählt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnungen nach Zimmerzahl",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12624",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.03",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:17",
		"id": 12624
	},
	{
		"template": "template001",
		"data-id": 12625,
		"chart-id": 12625,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnungen nach Belegungsart",
		"subtitle": "Wohnviertel St. Johann",
		"lesehilfe": "Im Wohnviertel St. Johann überwiegt 2023 der Mietwohnungsanteil mit 78,7%. Der Anteil an Genossenschaftswohnungen betrug 10,1%, was unter dem Wert für die Stadt Basel (11,0%) lag. Selbstbewohnte Eigentümerwohnungen weisen einen Anteil von 9,7% auf.",
		"erlaeuterungen": "Die Daten beziehen sich auf die belegten Wohnungen, Mansarden oder Einzelzimmer (Haushalte). Sonstige Wohnungen umfassen Notwohnungen der Sozialhilfe, subventionierte Wohnungen gemeinnütziger Institutionen, Dienst- und Abwartswohnungen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnungen nach Belegungsart",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12625",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.04",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:18",
		"id": 12625
	},
	{
		"template": "line001",
		"data-id": 12626,
		"chart-id": 12626,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnfläche pro Person",
		"subtitle": "in m<sup>2</sup>, Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Die mittlere Wohnfläche des Wohnviertels St. Johann liegt 2023 mit 36,8 m² tiefer als in der Stadt Basel (40,7 m²). Nach Bezirk betrachtet, zeigen sich Unterschiede: Im Bezirk Kannenfeld liegt die mittlere Wohnfläche mit 42,7 m² über dem städtischen Durchschnitt, im Bezirk Landskron mit 34,2 m² darunter.",
		"erlaeuterungen": "Die durchschnittliche Wohnfläche pro Bewohner berechnet sich aus der Gesamtfläche der bewohnten Wohnungen, dividiert durch die Summe der zugeordneten Bewohner. Als Wohnfläche gilt die bewohnbare Fläche der Wohnung in Quadratmetern. Sie setzt sich zusammen aus der Summe der Flächen aller Zimmer, Küchen, Badezimmer, Toilettenräume, Reduits und Gänge einer Wohnung. Zusätzliche separate Wohnräume (z. B. Mansarden), offene Balkone und Terrassen sowie nicht bewohnbare Keller- und Dachgeschossräume fallen bei der Berechnung ausser Betracht.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnfläche pro Person",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12626",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.02",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:16",
		"id": 12626
	},
	{
		"template": "line001",
		"data-id": 12627,
		"chart-id": 12627,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Leerwohnungsquote",
		"subtitle": "Wohnviertel St. Johann",
		"lesehilfe": "Die Leerwohnungsquote im Wohnviertel St. Johann liegt für 2024 mit 0,79% auf ähnlichem Niveau wie jene der Stadt Basel mit 0,77%.",
		"erlaeuterungen": "Stichtag ist der 1. Juni. Nur Wohnungen, die für den eigentlichen Wohnungsmarkt in Betracht kommen; also ohne leere Wohnungen, die für den Abbruch oder Umbau bestimmt sind. Die Prozentangaben beziehen sich auf den Leerwohnungsbestand am Gesamtwohnungsbestand.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Leerwohnungsquote",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12627",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.05",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:19",
		"id": 12627
	},
	{
		"template": "line001",
		"data-id": 12628,
		"chart-id": 12628,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Nettomietpreise nach Wohnviertel",
		"subtitle": "in Franken pro m<sup>2</sup>, Basel-Stadt, 2018-2022",
		"lesehilfe": "Die Nettomiete pro m<sup>2</sup> von 3- und 4-Zimmer-Wohnungen liegt im Wohnviertel St. Johann bei ungefähr 17,9 Franken.",
		"erlaeuterungen": "Der Quadratmeter-Preis bezieht sich auf die Nettomiete, dividiert durch die Wohnfläche von 3- oder 4- Zimmer-Wohnungen. Die Daten stammen aus der Strukturerhebung. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe und sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2018 bis 2022 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Nettomietpreise nach Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Mietpreise",
		"kuerzel": "I.09.3.12628",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.06",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:20",
		"id": 12628
	},
	{
		"template": "line001",
		"data-id": 12629,
		"chart-id": 12629,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil Einfamilienhäuser",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Der Einfamilienhausanteil im Wohnviertel St. Johann liegt unter dem städtischen Durchschnitt, die Bezirke weisen aber grosse Unterschiede auf. Im Bezirk Friedmatt ist der Anteil mit rund 60% relativ hoch. In den Bezirken Pestalozzi, Kannenfeld und Lysbüchel ist er sehr niedrig.",
		"erlaeuterungen": "Anteil der Einfamilienhäuser an allen bewohnbaren Gebäuden des Wohnviertels oder Bezirkes in Prozent. Die Daten stamme aus dem kantonalen Gebäude- und Wohnungsregister GWR.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anteil Einfamilienhäuser",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12629",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.07",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:20",
		"id": 12629
	},
	{
		"template": "template001",
		"data-id": 12630,
		"chart-id": 12630,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Umgebaute Wohnungen",
		"subtitle": "nach Art des Umbaus, Wohnviertel St. Johann",
		"lesehilfe": "Im Wohnviertel St. Johann kamen 2023 73 Wohnungen neu hinzu (Umbausaldo). Insbesondere Umnutzungen gewerblich genutzter Objekte in Wohnungen sowie Ausbauten trugen dazu bei.",
		"erlaeuterungen": "Die prozentualen Anteile im Tooltip beziehen sich auf das Total der Zugänge resp. das Total der Abgänge.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Baustatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Umgebaute Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12630",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.08",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:21",
		"id": 12630
	},
	{
		"template": "template001",
		"data-id": 12631,
		"chart-id": 12631,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Nettowohnungsproduktion",
		"subtitle": "Wohnviertel St. Johann",
		"lesehilfe": "Die Nettowohnungsproduktion wurde 2010, 2018, 2021 und 2022 massgeblich von grossen Neubauprojekten beeinflusst. 2023 enstand aus einem Lagergebäude ein Wohngebäude mit 64 Wohnungen.",
		"erlaeuterungen": "Die Nettowohnungsproduktion setzt sich wie folgt zusammen: Neu gebaute Wohnungen minus abgebrochene Wohnungen plus Saldo aus Umbauten (kann positiv oder negativ sein).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Baustatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Nettowohnungsproduktion",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12631",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.09",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:22",
		"id": 12631
	},
	{
		"template": "template001",
		"data-id": 12632,
		"chart-id": 12632,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Genossenschaftswohnungen",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Im Wohnviertel St. Johann sind 2023 10,1% der Wohnungen Genossenschaftswohnungen. Das ist nahe am städtischen Durchschnitt von 11,0%. Der Schwerpunkt des genossenschaftlichen Wohnungsbaus liegt im Wohnbezirk Friedmatt mit einem Anteil von 29,9%. Der Wohnbezirk Kannenfeld dagegen weist keine Genossenschaftswohnungen auf.",
		"erlaeuterungen": "Es werden nur Wohnungen berücksichtigt, welche am Stichtag (31.12.) durch mindestens eine Person belegt waren.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Genossenschaftswohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12632",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "4.10",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:23",
		"id": 12632
	},
	{
		"template": "line001",
		"data-id": 12633,
		"chart-id": 12633,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil an der Gesamtbeschäftigung der Stadt Basel",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Im Jahr 2022 findet man 5,9% der Beschäftigen der Stadt Basel im Bezirk Lysbüchel und 0,3% im Bezirk Kannenfeld. Insgesamt entfallen 10,0% der Beschäftigung der Stadt Basel auf das Wohnviertel St. Johann.",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und dafür einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Referenzperiode ist jeweils der Dezember des Jahres. Bei Unternehmen mit mehreren Arbeitsstätten werden die Beschäftigten gemäss Angaben der Unternehmen auf die verschiedenen Arbeitsstätten verteilt. Dabei ist nicht auszuschliessen, dass es sich teilweise um rein administrative Zuordnungen handeln kann und nicht alle Beschäftigten effektiv an dieser Arbeitsstätte bzw. Adresse tätig sind.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anteil an der Gesamtbeschäftigung der Stadt Basel",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.12633",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.01",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:05",
		"id": 12633
	},
	{
		"template": "line001",
		"data-id": 12634,
		"chart-id": 12634,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Beschäftigung nach ausgewählten Branchen",
		"subtitle": "Wohnviertel St. Johann",
		"lesehilfe": "Die wichtigste Branche im Wohnviertel St. Johann ist die pharmazeutische Industrie  mit 7 883 Beschäftigten im Jahr 2022, gefolgt von den sonstigen wirtschaftlichen Dienstleistungen (2 742) und der Schiff- und Luftfahrt (2 313). Die Gastronomie (2 306), das Gesundheitswesen (2 146) sowie die Lagerei (1 692) sind weitere Branchen mit substanziellen Beschäftigtenzahlen.",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und die einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Referenzperiode ist jeweils der Dezember des Jahres. Bei Unternehmen mit mehreren Arbeitsstätten werden die Beschäftigten gemäss Angaben der Unternehmen auf die verschiedenen Arbeitsstätten verteilt. Dabei ist nicht auszuschliessen, dass es sich teilweise um rein administrative Zuordnungen handelt kann und nicht alle Beschäftigten effektiv an dieser Arbeitsstätte (oder Adresse) tätig sind.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Beschäftigung nach ausgewählten Branchen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.12634",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.03",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:09",
		"id": 12634
	},
	{
		"template": "template001",
		"data-id": 12635,
		"chart-id": 12635,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Rotlichtsalons",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Im St.Johann gab es im Jahr 2023 insgesamt 7 Rotlichtsalons (2007 waren es deren 22). In den Bezirken Landskron und Pestalozzi waren es drei bzw. zwei, in den Bezirken Kannenfeld und Friedmatt je einer. Im Bezirk Lysbüchel wurden keine Salons verzeichnet. Insgesamt waren im Jahr 2023 im Kanton Basel-Stadt 130 Rotlichtsalons registriert.",
		"erlaeuterungen": "Für die Jahre 2008 und 2012 liegen keine Daten vor.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anzahl Rotlichtsalons",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.12635",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.09",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:14",
		"id": 12635
	},
	{
		"template": "line001",
		"data-id": 12636,
		"chart-id": 12636,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Nettoerwerbstätigenquote",
		"subtitle": "Wohnviertel St. Johann",
		"lesehilfe": "Die Nettoerwerbstätigenquote im Wohnviertel St. Johann betrug im Durchschnitt der Jahre 2018 bis 2022 71,5%.",
		"erlaeuterungen": "Die Nettoerwerbstätigenquote ist definiert als die Anzahl der Erwerbstätigen, geteilt durch die Wohnbevölkerung im Alter von 15 bis 64 Jahren. Bis 2000 stammen die Daten zu den Erwerbspersonen aus der Eidgenössischen Volkszählung (Vollerhebung), seit 2010 aus der Strukturerhebung. Die Strukturerhebung ist eine Stichprobenerhebung, weshalb die Schätzungen mit einer gewissen Ungenauigkeit verbunden sind. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2018 bis 2022 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)",
			"Bundesamt für Statistik (BFS), Volkszählung (VZ)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Nettoerwerbstätigenquote",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.12636",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.04",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:09",
		"id": 12636
	},
	{
		"template": "line001",
		"data-id": 12637,
		"chart-id": 12637,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bruttogeschossfläche Wohnen und Arbeiten",
		"subtitle": "in m<sup>2</sup>, Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Im Bezirk Lysbüchel hat die Bruttogeschossfläche für Wohnen zwischen 1995 und 2022 von 94 705 m<sup>2</sup> auf 117 226 m<sup>2</sup> zugenommen. Diejenige für Arbeiten ist von 888 332 m<sup>2</sup> auf 693 764 m<sup>2</sup> gesunken. In der Stadt Basel hat die Bruttogeschossfläche sowohl für Wohnen als auch für Arbeiten zwischen 1995 und 2022 zugenommen.",
		"erlaeuterungen": "Die Bruttogeschossfläche (BGF) ist die Summe der Grundflächen der ober- und unterirdischen Geschosse von Gebäuden, die zum Wohnen oder Arbeiten genutzt werden können. Aufgrund eines Methodenwechsels sind die Daten der Jahre seit 2020 nicht direkt mit denjenigen der Vorjahre vergleichbar. Für das Jahr 2000 stehen keine Daten zur Verfügung.",
		"quellenangabe": [
			"Bau- und Verkehrsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Bruttogeschossfläche Wohnen und Arbeiten",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.12637",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.02",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:06",
		"id": 12637
	},
	{
		"template": "line001",
		"data-id": 12638,
		"chart-id": 12638,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Nettoerwerbsquote der Frauen",
		"subtitle": "Wohnviertel St. Johann",
		"lesehilfe": "Im Wohnviertel St. Johann lag die Nettoerwerbsquote der Frauen im Mittel der Jahre 2018 bis 2022 bei 72,3%. Zum Vergleich: Die Quote für die Stadt Basel beträgt 74,0%.",
		"erlaeuterungen": "Die Nettoerwerbsquote ist definiert als die Summe der Erwerbspersonen (Erwerbstätige plus Erwerbslose), geteilt durch die Wohnbevölkerung im Alter von 15 bis 64 Jahren. Bis 2000 stammen die Daten zu den Erwerbspersonen aus der Eidgenössischen Volkszählung (Vollerhebung), seit 2010 aus der Strukturerhebung. Die Strukturerhebung ist eine Stichprobenerhebung, weshalb die Schätzungen mit einer gewissen Ungenauigkeit verbunden sind. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2018 bis 2022 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese 5 Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)",
			"Bundesamt für Statistik (BFS), Volkszählung (VZ)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Nettoerwerbsquote der Frauen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.12638",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "3.05",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:10",
		"id": 12638
	},
	{
		"template": "line001",
		"data-id": 12639,
		"chart-id": 12639,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sozialhilfequote",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Der Bezirk Landskron weist 2023 mit 8,2% die höchste Sozialhilfequote im St. Johann auf. Im Bezirk Kannenfeld liegt sie mit 2,5% am tiefsten. Gegenüber 2017 ist die Sozialhilfequote in allen Bezirken des St.Johann gesunken, am stärksten im Bezirk Landskron.",
		"erlaeuterungen": "Die Sozialhilfequote zeigt den prozentualen Anteil der Sozialhilfebeziehenden an der jeweiligen Bevölkerungsgruppe gemäss Stand am Ende des Jahres. Als Sozialhilfebeziehende werden alle Personen gezählt, die im Verlaufe eines Jahres mindestens eine Leistung der Sozialhilfe erhalten haben. Es werden alle Beziehenden mit Dossiertyp Sozialhilfefall sowie Anerkannte Flüchtlinge (FL), Vorläufig Aufgenommene (VA) und Vorläufig aufgenommene Flüchtlinge (VA FL) mit einer Aufenthaltsdauer von mehr als fünf bzw. sieben Jahren (FL 5+, VA 7+, VA FL 7+) berücksichtigt<br>Die Berechnungsmethode wurde 2022 für die Jahre ab 2017 rückwirkend angepasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Sozialhilfequote",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe",
		"kuerzel": "I.13.3.12639",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "5.04",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:27",
		"id": 12639
	},
	{
		"template": "line001",
		"data-id": 12640,
		"chart-id": 12640,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sek P-Quote nach Staatsangehörigkeit",
		"subtitle": "Wohnviertel St. Johann",
		"lesehilfe": "Die Sek P-Quote der Schülerinnen und Schüler ohne Schweizer Pass liegt 2024 im Wohnviertel St. Johann mit 13,1% tiefer als jene der Schweizerinnen und Schweizer (37,5%). Für die Stadt Basel beträgt das Total 2024 36,7%.",
		"erlaeuterungen": "Seit 2017/18 Anteil der Sek-Schülerinnen und Schüler im Leistungszug P mit hohen Anforderungen an allen Sek-Schülerinnen und Schülern der 10. und 11. Schulstufe (einschliesslich zweier obligatorischer Kindergartenstufen gezählt) an öffentlichen Schulen und mit Wohnort Basel-Stadt. Bis Schuljahr 2015/16 Anteil der Gymnasiastinnen und Gymnasiasten an allen Schülerinnen und Schülern der 10. und 11. Schulstufe. Im Übergangsjahr 2016/17 wurde als Hilfskonstrukt für Stufe 10 der Sek P-Anteil und für Stufe 11 der Gym-Anteil herangezogen. Stichtag der Bildungsstatistik ist jeweils im September; das Jahr 2022 in der Grafik entspricht Schuljahr 2022/23.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bildungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Sek P-Quote nach Staatsangehörigkeit",
		"thema": "15 Bildung",
		"unterthema": "Schulen und Schulpersonal",
		"kuerzel": "I.15.1.12640",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "5.02",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:25",
		"id": 12640
	},
	{
		"template": "line001",
		"data-id": 12641,
		"chart-id": 12641,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil deutschsprachiger Kinder in Kindergarten und Primarschule",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "In den Bezirken Pestalozzi und Kannenfeld ist der Anteil deutschsprachiger Kinder höher als im städtischen Durchschnitt, in den Bezirken Lysbüchel, Landskron und Friedmatt dagegen tiefer.",
		"erlaeuterungen": "Der Indikator zeigt den Anteil der Schülerinnen und Schüler mit Erstsprache Deutsch an allen Schülerinnen und Schülern der öffentlichen Kindergärten und Primarschulen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bildungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anteil deutschsprachiger Kinder in Kindergarten und Primarschule",
		"thema": "15 Bildung",
		"unterthema": "Schulen und Schulpersonal",
		"kuerzel": "I.15.1.12641",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "5.01",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:24",
		"id": 12641
	},
	{
		"template": "line001",
		"data-id": 12642,
		"chart-id": 12642,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil der Bevölkerung mit tertiärem Bildungsabschluss",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2018-2022",
		"lesehilfe": "Im Wohnviertel St. Johann betrug der Anteil Personen mit tertiärem Bildungsabschluss im Zeitraum von 2018 bis 2022 im Mittel 43,9 Prozent.",
		"erlaeuterungen": "Anteil der Personen mit höchstem Bildungsabschluss «Tertiärstufe» an der über 14-jährigen Wohnbevölkerung. Die Tertiärstufe umfasst die höhere Berufsbildung, z. B. eine höhere Fachschule für Technik oder Wirtschaft, sowie Ausbildungen an Hochschulen wie z. B. ein Bachelor- oder Masterstudium. Die Daten stammen aus der Strukturerhebung. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe und sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2018 bis 2022 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Die Frage zur höchsten abgeschlossenen Ausbildung wurde im Fragebogen der Strukturerhebung 2020 verändert. Somit liegt ein methodischer Bruch innerhalb des Poolingzeitraums vor.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anteil der Bevölkerung mit tertiärem Bildungsabschluss",
		"thema": "15 Bildung",
		"unterthema": "Bildungsniveau",
		"kuerzel": "I.15.6.12642",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "5.03",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:25",
		"id": 12642
	},
	{
		"template": "line001",
		"data-id": 12643,
		"chart-id": 12643,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Quote der Haushalte mit Familienmietzinsbeiträgen und reiner Prämienverbilligung",
		"subtitle": "Wohnviertel St. Johann",
		"lesehilfe": "3,3% der Haushalte im Wohnviertel St. Johann beziehen Ende des Jahres 2023 Familienmietzinsbeiträge (FAMI). In 20,9% der Haushalte bezieht mindestens eine Person Prämienverbilligung (PV). Zum Vergleich: Die FAMI-Quote der Stadt-Basel liegt bei 2,2%, die PV-Quote bei 16,2%.",
		"erlaeuterungen": "Die Quote der Haushalte mit Familienmietzinsbeiträgen (FAMI) entspricht dem Verhältnis der Anzahl Haushalte mit Mietzinsbeiträgen zur Gesamtzahl der Haushalte (exklusive Haushalte in Wohnungen ohne Kocheinrichtung) per Ende des Jahres. Die Quote der Haushalte mit Prämienverbilligung (PV) entspricht dem Verhältnis der Anzahl Haushalte mit PV zur Gesamtzahl der Haushalte (exklusive Haushalte in Wohnungen ohne Kocheinrichtung) per Ende des Jahres. Es werden alle Haushalte mit mindestens einer Person mit reiner PV gezählt. Beziehende von Sozialhilfe und Ergänzungsleistungen, die die PV im Rahmen jener Leistungen ausbezahlt erhalten, sind nicht einberechnet. Stichtag ist jeweils der 4. Januar des Folgejahres.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Basler Informationssystem Sozialleistungen (BISS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Quote der Haushalte mit Familienmietzinsbeiträgen und reiner Prämienverbilligung",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.12643",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "5.05",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:28",
		"id": 12643
	},
	{
		"template": "template001",
		"data-id": 12644,
		"chart-id": 8080,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bodenbedeckung nach Nutzungsart",
		"subtitle": "Anteil an der Gesamtfläche, Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Im Jahr 2024 sind im Bezirk Lysbüchel 17,6% der Fläche Grünflächen. 2005 waren es 6,7%.",
		"erlaeuterungen": "Grünfläche: alle privaten und öffentlichen bestockten (Wald, Übrige) oder humusierten Flächen (Acker, Wiese, Friedhof, Gartenanlage, Gewässervorland, Park, Reben, Schrebergarten, Sportanlage, Tierpark, Übrige). Gewässer: stehende und fliessende Gewässer. Verkehrsfläche: Befestigte Flächen wie Strassen, Wege, Trottoirs (inkl. Rabatten) und Verkehrsinseln sowie Bahn- und Tramareale. Übrige befestigte Flächen: Hafen- und Fabrikareale; Tankanlagen; Wasserbecken und befestigtes Gewässervorland; befestigte Sportanlagen; alle weiteren befestigten Flächen. Als befestigt gelten künstlich hergerichtete Flächen, insbesondere asphaltierte, betonierte, bekieste, gemergelte oder mit Steinen oder Platten belegte Flächen. <br>Die Angaben basieren auf der Datenebene «Bodenbedeckung» der amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100 m<sup>2</sup> geführt werden. Diese werden bei Bedarf oder spätestens in einem Turnus von 6-12 Jahren mit einer periodischen Nachführung aktualisiert. Befestigte Objekte wie Gebäude, Strassenräume oder öffentliche Pärke werden detaillierter erfasst und bei baulichen Änderungen nachgeführt.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Bodenbedeckung nach Nutzungsart",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.12644",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.01",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-01-07T09:34:20",
		"id": 12644
	},
	{
		"template": "template001",
		"data-id": 12645,
		"chart-id": 12645,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Grünflächen nach Kategorie",
		"subtitle": "in m<sup>2</sup>, Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Im Bezirk Friedmatt (mit dem Kannenfeldpark) macht die Bodenbedeckungsart «Gartenanlagen» den Grossteil der Grünflächen aus (2023: 252 000 m<sup>2</sup>). Im Bezirk Lysbüchel wuchs die Grünfläche seit 2005 von rund 48 600 auf 130 400 m<sup>2</sup>.",
		"erlaeuterungen": "Als Grünfläche gelten alle privaten und öffentlichen bestockten (Wald, Übrige) oder humusierten (Acker, Wiese, Friedhof, Gartenanlage, Gewässervorland, Park, Reben, Schrebergarten, Sportanlage, Tierpark, Übrige) Flächen. Die Angaben basieren auf der Datenebene «Bodenbedeckung» der amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100 m<sup>2</sup> geführt werden. Diese werden bei Bedarf oder spätestens in einem Turnus von 6-12 Jahren mit einer periodischen Nachführung aktualisiert. Befestigte Objekte wie Gebäude, Strassenräume oder öffentliche Pärke werden detaillierter erfasst und bei baulichen Änderungen nachgeführt.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Grünflächen nach Kategorie",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.12645",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.02",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:32",
		"id": 12645
	},
	{
		"template": "map002",
		"data-id": 12646,
		"chart-id": 12646,
		"filter": "",
		"parentId": null,
		"children": [
			7701
		],
		"title": "Städtischer Wärmeinseleffekt",
		"subtitle": "im Siedlungsraum, nach Wohnviertel, Basel-Stadt, 2017",
		"lesehilfe": "Die dichtbebauten innenstädtischen Wohnviertel sind am stärksten vom städtischen Wärmeinseleffekt betroffen: In der Altstadt Grossbasel liegt die berechnete nächtliche (4 Uhr) Lufttemperatur im Mittel 4,5 °C über der mittleren Temperatur im unbebauten Umland (14,2 °C). Aber auch im Siedlungsraum der Gemeinde Riehen ist die Temperatur noch um 1,1 °C erhöht.",
		"erlaeuterungen": "Die Daten stammen aus der 2019 publizierten Stadtklimaanalyse Basel-Stadt und wurden räumlich für den Siedlungsraum gemäss Zonenplan gemittelt. Es handelt sich um mit einem numerischen Modell berechnete Temperaturwerte in 2 m über Grund für eine stabile sommerliche Hochdruckwetterlage mit wolkenlosem Himmel und geringen Windgeschwindigkeiten.",
		"quellenangabe": [
			"Lufthygieneamt beider Basel"
		],
		"externalLinks": [
			"<a href = 'https://www.stadtklima.bs.ch/' target = '_blank'>https://www.stadtklima.bs.ch</a>",
			"<a href = 'https://map.geo.bs.ch/file_proxy/KL_Stadtklima_Windstroemungsfeld/Endbericht_Basel_Klimaanalyse_Rev09_ohne_Anhang.pdf' target = '_blank'>Bericht Stadtklimaanalyse Kanton Basel-Stadt 2019</a>",
			"<a href = 'https://map.geo.bs.ch/?lang=de&baselayer_ref=Grundkarte%20grau&tree_group_layers_Stadtklima%20Basel-Stadt=KL_Stadtklima_Waermeinseleffekt&tree_groups=Stadtklima%20Basel-Stadt' target = '_blank'>Detailierte Klimaanalysekarte im Geoportal Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Städtischer Wärmeinseleffekt",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Klima",
		"kuerzel": "I.02.12.12646",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.04",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_004",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:33",
		"id": 12646
	},
	{
		"template": "template001",
		"data-id": 12648,
		"chart-id": 12648,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Gebäude nach Energieträger der Hauptheizung",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Mit dem Ausbau des baselstädtischen Fernwärmenetzes nimmt in den Bezirken Friedmatt, Kannenfeld, Landskron, Lysbüchel und Pestalozzi der Anteil fernwärmebeheizter Gebäude zu. Gleichzeitig ist der Einsatz von Heizöl rückläufig.",
		"erlaeuterungen": "Die Anzahl Gebäude nach Energieträger der Hauptheizung stammt aus der kantonalen Gebäude- und Wohnungsstatistik, welche jährlich per 31. Dezember aus dem kantonalen Gebäude- und Wohnungsregister (GWR) erzeugt wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Gebäude nach Energieträger der Hauptheizung",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.12648",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.07",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:36",
		"id": 12648
	},
	{
		"template": "line001",
		"data-id": 12649,
		"chart-id": 12649,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Stromverbrauch",
		"subtitle": "in Gigawattstunden (GWh), Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "2022 betrug der gesamte Stromverbrauch im Bezirk Lysbüchel 35,4 GWh, im flächenmässig kleinsten Bezirk Kannenfeld nur 3,2 GWh.",
		"erlaeuterungen": "Die kantonale Energiestatistik erscheint seit dem Jahr 2012 im Zweijahresrhythmus. Ausgewiesen werden hier ausschliesslich Endverbräuche in Gigawattstunden (GWh).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Stromverbrauch",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.12649",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.06",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:35",
		"id": 12649
	},
	{
		"template": "line001",
		"data-id": 12650,
		"chart-id": 12650,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Personenwagen pro Haushalt, Motorisierungsgrad",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "2023 waren im Bezirk Pestalozzi im Schnitt 0,33 Personenwagen pro Haushalt registriert, der Motorisierungsgrad lag bei 177,9 privaten Personenwagen pro 1 000 Einwohnern.",
		"erlaeuterungen": "Anzahl der auf Privatpersonen zugelassenen Personenwagen geteilt durch die Anzahl Haushalte sowie pro 1 000 Einwohner (Motorisierungsgrad). Zur Berechnung wird jeweils der Stand Ende September der Personenwagen, Haushalte und Einwohner (exkl. Personen an administrativen Meldeadressen) verwendet.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Bundesamt für Strassen (ASTRA)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Personenwagen pro Haushalt, Motorisierungsgrad",
		"thema": "11 Verkehr",
		"unterthema": "Motorfahrzeuge",
		"kuerzel": "I.11.1.12650",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.08",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:37",
		"id": 12650
	},
	{
		"template": "mappie001",
		"data-id": 7707,
		"chart-id": 7707,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Feinstaubbelastung",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2020",
		"lesehilfe": "2020 waren im Wohnviertel St. Johann 84 Personen (0,45% der dortigen Wohnbevölkerung) an ihrem Wohnort Feinstaub-Belastungen ausgesetzt, welche über dem zulässigen Jahresgrenzwert lagen. Die den Berechnungen zugrunde liegenden <a href='https://geoview.bl.ch/?map_x=2613974.25&map_y=1267407.75&map_zoom=4&tree_group_layers_Luft=luftqualitaet_pm10_gesamt_2020&tree_groups=Luft' target='_blank'>Immissionskarten</a> zeigen, dass hohe Belastungen primär nahe viel befahrenen Strassen erfolgen, v. a. neben den Autobahnabschnitten.",
		"erlaeuterungen": "Anzahl und Anteil Personen, an deren Wohnort im Jahresmittel Feinstaub-Belastungen (PM10) von über 20 µg/m<sup>3</sup> (Jahresgrenzwert gemäss Luftreinhalteverordnung) auftreten. Berechnet basierend auf Daten des Lufthygieneamtes beider Basel (Immissionen modelliert auf Basis eines 10 x 10 m-Rasters für 2020). Unter PM10 versteht man Partikel, die kleiner sind als 10 Mikrometer. Dieser Staub ist ein physikalisch-chemisch komplexes Gemisch. Er entsteht bei industriellen und gewerblichen Produktionsprozessen, Verbrennungsprozessen, mechanischen Prozessen (Abrieb, Aufwirbelung) sowie durch sekundäre Bildung (aus SO<sub>2</sub>, NO<sub>x</sub>, NH<sub>3</sub>, VOC). PM10 ist in seiner Zusammensetzung sehr vielfältig und kann Russ, Schwermetalle, Sulfat, Nitrat, Ammonium, organischen Kohlenstoff, polyzyklische aromatische Kohlenwasserstoffe oder Dioxine/Furane enthalten. Feinstaub führt zu Erkrankungen der Atemwege, des Herz-Kreislaufsystems, zu einer Zunahme des Krebsrisikos und der Sterberate.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Lufthygieneamt beider Basel"
		],
		"externalLinks": [
			"Weitere Informationen zu <a href = 'http://www.bs.ch/indikator-1109' target = '_blank'>Feinstaub-Immissionen</a> in der Region Basel",
			"Nationale <a href = 'https://www.admin.ch/opc/de/classified-compilation/19850321/index.html#app7ahref0' target = '_blank'>Luftreinhalte-Verordnung (LRV), Anhang 7</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Feinstaubbelastung",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Luft",
		"kuerzel": "I.02.15.12651",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.09",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_009",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:38",
		"id": 12651
	},
	{
		"template": "mappie001",
		"data-id": 7708,
		"chart-id": 7708,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Stickoxidbelastung",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2020",
		"lesehilfe": "2020 waren im Wohnviertel Rosental 2 170 Personen (11,7% der dortigen Wohnbevölkerung) an ihrem Wohnort Stickstoffdioxid-Belastungen ausgesetzt, welche über dem zulässigen Jahresgrenzwert lagen. Die den Berechnungen zugrunde liegenden <a href='https://geoview.bl.ch/?map_x=2612751.75&map_y=1267417.75&map_zoom=5&tree_group_layers_Luft=luftqualitaet_no2_gesamt_2020&tree_groups=Luft' target='_blank'>Immissionskarten</a> zeigen, dass hohen Belastungen primär nahe viel befahrenen Strassen erfolgen, v. a. neben den Autobahnabschnitten.",
		"erlaeuterungen": "Anzahl und Anteil Personen, an deren Wohnort im Jahresmittel Stickstoffdioxid-Immissionen (NO<sub>2</sub>) von über 30 µg/m<sup>3</sup> (Jahresgrenzwert gemäss Luftreinhalteverordnung) auftreten. Berechnet basierend auf Daten des Lufthygieneamtes beider Basel (Immissionen modelliert auf Basis eines 10 x 10 m-Rasters für 2020). Stickoxide (NO<sub>x</sub>) entstehen beim Verbrennen von Brenn- und Treibstoffen, insbesondere bei hohen Verbrennungstemperaturen. Hauptquelle ist der Strassenverkehr. Stickoxide sind wichtige Vorläufersubstanzen für die Bildung von sauren Niederschlägen, sekundärem Feinstaub und – zusammen mit flüchtigen organischen Verbindungen – von Ozon/Sommersmog. Stickstoffdioxid (NO<sub>2</sub>) und andere Reizgase begünstigen Erkrankungen der Atemwege.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Lufthygieneamt beider Basel"
		],
		"externalLinks": [
			"Weitere Informationen zu <a href = 'http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-11-1111' target = '_blank'>Stickstoffdioxid-Immissionen</a>in der Region Basel",
			"Nationale <a href = 'https://www.admin.ch/opc/de/classified-compilation/19850321/index.html#app7ahref0' target = '_blank'>Luftreinhalte-Verordnung (LRV), Anhang 7</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Stickoxidbelastung",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Luft",
		"kuerzel": "I.02.15.12652",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.10",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_010",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:42",
		"id": 12652
	},
	{
		"template": "line001",
		"data-id": 12653,
		"chart-id": 12653,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Freiraumfläche",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Im Bezirk Friedmatt waren 2023 7,4% der Bezirksfläche Freiraumflächen, in den Bezirken Kannenfeld und Landskron gab es keine Freiraumflächen (Stadt Basel: 3,1%).",
		"erlaeuterungen": "Zu den Freiraumflächen zählen Parkanlagen, Spielplätze und Rasenflächen von Sportanlagen. Die Angaben basieren auf der Datenebene «Bodenbedeckung» der Amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100 m<sup>2</sup> geführt werden. Diese werden bei Bedarf oder spätestens in einem Turnus von 6-12 Jahren mit einer periodischen Nachführung aktualisiert. Befestigte Objekte wie Gebäude, Strassenräume oder öffentliche Pärke werden detaillierter erfasst und bei baulichen Änderungen nachgeführt.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Freiraumfläche",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "7.03",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:33",
		"id": 12653
	},
	{
		"template": "line001",
		"data-id": 12655,
		"chart-id": 12655,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Delikte",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Im Jahr 2022 wurden im Bezirk Pestalozzi 30 Delikte gemeldet. Im dargestellten Zeitraum wurden in diesem Bezirk 2019 am wenigsten (14) und 2012 am meisten Delikte (45) registriert. In der Stadt Basel gab es im Jahr 2022 1 559 Delikte. Der Minimalwert wurde dort 2020 (1 158), der Maximalwert 2012 (2 069) registriert.",
		"erlaeuterungen": "Bei der Kantonspolizei gemeldete Delikte der folgenden Kategorien: Entreissdiebstahl, Raub, Einbruch- und Einschleichdiebstähle, Nötigung sowie Sexualdelikte (Vergewaltigung, sexuelle Nötigung).",
		"quellenangabe": [
			"Kantonspolizei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Delikte",
		"thema": "19 Kriminalität und Strafrecht",
		"unterthema": "Polizei",
		"kuerzel": "I.19.1.12655",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "6.01",
		"stufe1": "6 Sicherheit",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "06_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:29",
		"id": 12655
	},
	{
		"template": "line001",
		"data-id": 12656,
		"chart-id": 12656,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Einbruch- und Einschleichdiebstähle",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Im Jahr 2022 gab es im Bezirk Pestalozzi 27 Einbruch- oder Einschleichdiebstähle. Im dargestellten Zeitraum wurden in diesem Bezirk 2019 am wenigsten (13) und 2012 am meisten Einbruch- oder Einschleichdiebstähle (39) registriert. In der Stadt Basel gab es im Jahr 2022 1 358 Einbruch- oder Einschleichdiebstähle. Der Minimalwert wurde dort 2020 (995), der Maximalwert 2012 (1 819) registriert.",
		"erlaeuterungen": "Bei der Kantonspolizei gemeldete Einbruch- und Einschleichdiebstähle.",
		"quellenangabe": [
			"Kantonspolizei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Einbruch- und Einschleichdiebstähle",
		"thema": "19 Kriminalität und Strafrecht",
		"unterthema": "Polizei",
		"kuerzel": "I.19.1.12656",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "6.02",
		"stufe1": "6 Sicherheit",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "06_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:30",
		"id": 12656
	},
	{
		"template": "template001",
		"data-id": 12657,
		"chart-id": 12657,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Umzugssaldo",
		"subtitle": "Wohnviertel St. Johann, nach Bezirk",
		"lesehilfe": "Im Jahr 2023 weisen die Bezirke Kannenfeld, Landskron und Pestalozzi einen negativen Umzugssaldo auf, d. h. es verlegen mehr Personen aus diesen Bezirken ihren Wohnsitz in den übrigen Kanton Basel-Stadt als von dort in diese Bezirke. Hingegen weisen 2023 die Bezirke Friedmatt und Lysbüchel positive Umzugssaldi auf. Die hohen Umzugsgewinne im Bezirk Lysbüchel 2022 und 2023 sind auf die Fertigstellung von Wohngebäuden zurückzuführen.",
		"erlaeuterungen": "Umzüge sind räumliche Bevölkerungsbewegungen innerhalb des Kantons Basel-Stadt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Umzugssaldo",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.10",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_014",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:11:03",
		"id": 12657
	},
	{
		"template": "populationPyramid001",
		"data-id": 12611,
		"chart-id": 12659,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung nach Alter und Geschlecht",
		"subtitle": "Bezirk Kannenfeld, 2023",
		"lesehilfe": "Im Bezirk Kannenfeld des Wohnviertels St. Johann sind die grössten Fünfjahresklassen diejenigen der 25- bis 44-Jährigen, was auch der Bevölkerungsverteilung im Gesamtkanton entspricht.",
		"erlaeuterungen": "Die Bevölkerungspyramide zeigt die Wohnbevölkerung am Jahresende nach Alter (Fünfjahresklassen) und Geschlecht.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Wohnbevölkerung nach Alter und Geschlecht",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.12659",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.02b",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:10:54",
		"id": 12659
	},
	{
		"template": "populationPyramid001",
		"data-id": 12611,
		"chart-id": 12719,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung nach Alter und Geschlecht",
		"subtitle": "Bezirk Landskron, 2023",
		"lesehilfe": "Im Bezirk Landskron des Wohnviertels St. Johann sind die grössten Fünfjahresklassen diejenigen der 25- bis 44-Jährigen, was auch der Bevölkerungsverteilung im Gesamtkanton entspricht.",
		"erlaeuterungen": "Die Bevölkerungspyramide zeigt die Wohnbevölkerung am Jahresende nach Alter (Fünfjahresklassen) und Geschlecht.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnbevölkerung nach Alter und Geschlecht",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.02c",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:10:55",
		"id": 12719
	},
	{
		"template": "populationPyramid001",
		"data-id": 12611,
		"chart-id": 12720,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung nach Alter und Geschlecht",
		"subtitle": "Bezirk Lysbüchel, 2023",
		"lesehilfe": "Im Bezirk Lysbüchel des Wohnviertels St. Johann sind die grössten Fünfjahresklassen diejenigen der 25- bis 44-Jährigen, was auch der Bevölkerungsverteilung im Gesamtkanton entspricht.",
		"erlaeuterungen": "Die Bevölkerungspyramide zeigt die Wohnbevölkerung am Jahresende nach Alter (Fünfjahresklassen) und Geschlecht.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Wohnbevölkerung nach Alter und Geschlecht",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.02d",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:10:56",
		"id": 12720
	},
	{
		"template": "populationPyramid001",
		"data-id": 12611,
		"chart-id": 12721,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnbevölkerung nach Alter und Geschlecht",
		"subtitle": "Bezirk Pestalozzi, 2023",
		"lesehilfe": "Im Bezirk Pestalozzi des Wohnviertels St. Johann sind die grössten Fünfjahresklassen diejenigen der 25- bis 44-Jährigen, was auch der Bevölkerungsverteilung im Gesamtkanton entspricht.",
		"erlaeuterungen": "Die Bevölkerungspyramide zeigt die Wohnbevölkerung am Jahresende nach Alter (Fünfjahresklassen) und Geschlecht.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Wohnbevölkerung nach Alter und Geschlecht",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring St. Johann",
		"kuerzelKunde": "2.02e",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-12-18T11:10:57",
		"id": 12721
	}
];