var indikatorensetData = [
	{
		"template": "spider001_print",
		"data-id": 7902,
		"chart-id": 7902,
		"filter": "",
		"parentId": "6754",
		"children": [],
		"title": "Rosental - Quartierradar",
		"subtitle": "Ausgabe 2022",
		"lesehilfe": "Im Wohnviertel Rosental sind die Einwohner am wenigsten sesshaft. Der Altersquotient ist der tiefste im ganzen Kanton, der Anteil Ausländer dagegen der höchste. Das Wohnviertel weist einen niedrigen Anteil Einfamilienhäuser auf und verfügt mit der Erlenmatt-Siedlung über relativ viele Neubauten. Die Steuererträge sind vergleichsweise gering.",
		"erlaeuterungen": "Die Grafik fasst 16 Indikatoren zusammen. Die Indikatoren sind den drei Bereichen <font color=\"923F8D\">Gesellschaft und Soziales</font>, <font color=\"68AB2B\">Raum und Umwelt</font> sowie <font color=\"689199\">Wirtschaft und Arbeit</font> zugeordnet. Die Werte der Indikatoren sind als Ränge im Vergleich zu allen anderen Basler Wohnvierteln und Gemeinden ausgewiesen. Das Wohnviertel oder die Gemeinde mit dem niedrigsten Wert des Indikators erhält Rang 1, mit dem höchsten Wert Rang 21 zugewiesen. Je grösser die graue Fläche, desto öfter erreicht das Wohnviertel oder die Gemeinde hohe Ränge bei den Indikatoren. <a href =\" https://www.statistik.bs.ch/dam/jcr:2cb04e13-b746-4455-8735-029f0439dc73/Quartierradar.pdf \" target = '_blank'>Zur Definition der einzelnen Indikatoren </a>",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Rosental - Quartierradar",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.07902",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"kuerzelKunde": "1.02",
		"stufe1": "1 Übersicht",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:18:49",
		"id": 7902
	},
	{
		"template": "line001_print",
		"data-id": 7903,
		"chart-id": 7903,
		"filter": "",
		"parentId": "7665",
		"children": [],
		"title": "Wohnbevölkerung",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"lesehilfe": "Im Bezirk Messe hat die Bevölkerung seit 2002 leicht zugenommen (+6,3%). Im Gesamtkanton hat die Bevölkerungszahl etwas stärker zugenommen (+7,3%). Ein drastischer Anstieg zeigt sich im Bezirk Erlenmatt: Mit dem Bau von Wohnungen auf dem ehemaligen Areal der Deutschen Bahn stieg die Einwohnerzahl von unter 200 bis zum Jahr 2008 auf 2 955 (2021).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnbevölkerung",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.07903",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"kuerzelKunde": "2.01",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:20",
		"id": 7903
	},
	{
		"title": "Wohnbevölkerung nach Alter und Geschlecht",
		"subtitle": "Wohnviertel Rosental, nach Bezirk, 2018",
		"kuerzel": "I.01.1.07904",
		"kuerzelKunde": "2.02",
		"description": "Wohnbevölkerung nach Alter und Geschlecht",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:31.3131",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "In den Bezirken Messe und Erlenmatt sind die Fünfjahresgruppen der 25- bis 29-Jährigen, der 30- bis 34-Jährigen und der 35- bis 39-Jährigen am stärksten besetzt. Dies ist auch im Gesamtkanton so, allerdings ist das Phänomen in den beiden Bezirken des Rosentalviertels ausgeprägter: Ende 2018 waren im Bezirk Messe 35% der Männer und 33% der Frauen zwischen 25 und 39 Jahre alt und im Bezirk Erlenmatt 41% der Männer und 42% der Frauen. Im Kanton Basel-Stadt gehörten 25% der Männer und 25% der Frauen dieser Altersgruppe an.",
		"erlaeuterungen": "",
		"template": "",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_00_00_00_00_002",
		"parentId": 7666,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7904,
		"chart-id": 7904,
		"filter": "",
		"id": 7904
	},
	{
		"title": "Jugendquotient",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"kuerzel": "I.01.1.07905",
		"kuerzelKunde": "2.03",
		"description": "Jugendquotient",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel",
			"Agglomeration"
		],
		"aktualisierungsdatum": "2020-01-28T16:09:22.2222",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Bezirk Messe ist der Jugendquotient zwischen 2000 und 2018 von 28,7 auf 24,3 gesunken. Im Bezirk Erlenmatt hat der Jugendquotient hingegen zugenommen, von 26,0 im Jahr 2000 auf 33,8 im Jahr 2018. Im Kanton Basel-Stadt lag der Jugendquotient im Jahr 2000 bei 27,8, im Jahr 2018 bei 26,5.",
		"erlaeuterungen": "Der Jugendquotient ergibt sich aus der Anzahl unter 20-Jähriger pro 100 20- bis 64-Jähriger (Personen im erwerbsfähigen Alter).",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_00_00_00_00_003",
		"parentId": 7667,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7905,
		"chart-id": 7905,
		"filter": "",
		"id": 7905
	},
	{
		"title": "Altersquotient",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"kuerzel": "I.01.1.07906",
		"kuerzelKunde": "2.04",
		"description": "Altersquotient",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel",
			"Bezirk"
		],
		"aktualisierungsdatum": "2020-01-28T16:07:09.099",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Bezirk Messe lag der Altersquotient Ende 2018 bei 12,8, im Bezirk Erlenmatt bei 11,3. Während der Altersquotient im Messe-Bezirk im Vergleich zum Jahr 2000 gesunken ist, hat er im Erlenmatt-Bezirk zugenommen. Im Gesamtkanton ist der Altersquotient seit dem Jahr 2000 (33,9) gesunken, 2018 lag er bei 30,4.",
		"erlaeuterungen": "Der Altersquotient ergibt sich aus der Anzahl über 64-Jähriger pro 100 20- bis 64-Jähriger (Personen im erwerbsfähigen Alter).",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_00_00_00_00_004",
		"parentId": 7668,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7906,
		"chart-id": 7906,
		"filter": "",
		"id": 7906
	},
	{
		"title": "Ausländeranteil",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"kuerzel": "I.01.1.07907",
		"kuerzelKunde": "2.05",
		"description": "Ausländeranteil",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:31.3131",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Bezirk Messe ist der Ausländeranteil seit 2000 von 49,5% auf 55,6% gestiegen. Ein anderes Bild zeigt der Bezirk Erlenmatt. Bis ca. 2008 schwankte der Anteil Ausländer von Jahr zu Jahr relativ stark, was auf die geringe Einwohnerzahl zurückzuführen ist. Danach stieg der Ausländeranteil bis 2012 auf den Höchstwert von 68,5% und sank seither wieder jährlich auf 55,9% per Ende 2018.",
		"erlaeuterungen": "Während die Bevölkerungszahl im Bezirk Messe seit 2000 kontinuierlich von 4&nbsp;185 auf 4&nbsp;730 anstieg, veränderte sich die Anzahl Einwohner im Bezirk Erlenmatt sehr sprunghaft. Dies ist auf die starke Bautätigkeit, insbesondere in den Jahren 2009 (+233 Wohnungen) und 2015 (+574 Wohnungen), aber auch in den Jahren 2014 (+63 Wohnungen), 2017 (+80 Wohnungen) und 2018 (+43 Wohnungen) zurückzuführen. Bei der Interpretation der bevölkerungsbezogenen Indikatoren ist dies zu berücksichtigen.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_00_00_00_00_005",
		"parentId": 7669,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7907,
		"chart-id": 7907,
		"filter": "",
		"id": 7907
	},
	{
		"title": "Ausländer nach Staatsangehörigkeit",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"kuerzel": "I.01.1.07908",
		"kuerzelKunde": "2.07",
		"description": "Ausländer nach Staatsangehörigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:31.3131",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Bezirk Erlenmatt bildeten in den letzten fünf Jahren jeweils Personen aus der Kategorie \"Übrige Länder\" die grösste ausländische Bevölkerungsgruppe, gefolgt von den Deutschen. Die grösste ausländische Bevölkerungsgruppe im Bezirk Messe waren von 2014 bis 2015 Personen aus dem Balkan und seit 2016 Personen aus den EU-17 + EFTA-Staaten.",
		"erlaeuterungen": "Die Bevölkerungszahl entwickelte sich im Wohnviertel Rosental in den letzten Jahren sehr sprunghaft. Dies ist durch die starke Bautätigkeit im Bezirk Erlenmatt, insbesondere in den Jahren 2009 (+233 Wohnungen) und 2015 (+574 Wohnungen), aber auch den Jahren 2014 (+63 Wohnungen), 2017 (+80 Wohnungen) und 2018 (+43 Wohnungen) begründet. Bei der Interpretation der bevölkerungsbezogenen Indikatoren ist dieser Hintergrund zu berücksichtigen.",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_00_00_00_00_007",
		"parentId": 7670,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7908,
		"chart-id": 7908,
		"filter": "",
		"id": 7908
	},
	{
		"template": "line001_print",
		"data-id": 7909,
		"chart-id": 7909,
		"filter": "",
		"parentId": "7671",
		"children": [],
		"title": "Sesshaftigkeit",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"lesehilfe": "Im Wohnviertel Rosental liegt der Anteil an Personen, die seit zehn oder mehr Jahren an der gleichen Adresse wohnen, Ende 2022 bei 19,2 Prozent. Das ist der niedrigste Anteil aller Wohnviertel. Dies liegt unter anderem daran, dass im Wohnviertel Rosental in den letzten Jahren viele neue Wohnungen erstellt wurden. Dies gilt insbesondere für den Bezirk Erlenmatt, der in den letzten Jahren daher stets Quoten unter 10% aufweist.",
		"erlaeuterungen": "Anteil Einwohner, die seit mindestens zehn Jahren an der gleichen Adresse wohnen. Ohne Personen an administrativen Meldeadressen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Sesshaftigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.07909",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"kuerzelKunde": "2.08",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-15T08:14:04",
		"id": 7909
	},
	{
		"template": "template001_print",
		"data-id": 7910,
		"chart-id": 7910,
		"filter": "",
		"parentId": "7672",
		"children": [],
		"title": "Haushalte nach Art des Haushalts",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"lesehilfe": "Die Haushaltsstruktur im Bezirk Erlenmatt weist in den letzten Jahren keine grossen Veränderungen auf. 2022 machen Einpersonenhaushalte 48% aus, 44% sind Familienhaushalte. 14% werden anderen Haushalten zugeordnet. Im Bezirk Messe gab es in den letzten drei Jahren ebenfalls keine grossen Veränderungen.",
		"erlaeuterungen": "Personen, die in der gleichen Wohnung leben, bilden einen Haushalt. Haushalte werden unterteilt in Privat- und Kollektivhaushalte. Hier werden nur Privathaushalte betrachtet. Die Gruppe \"Andere Haushalte\" umfasst Mehrpersonenhaushalte wie Wohngemeinschaften und unverheiratete Paare ohne ein gemeinsames Kind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel",
			"Bezirk"
		],
		"description": "Haushalte nach Art des Haushalts",
		"thema": "01 Bevölkerung",
		"unterthema": "Haushalte",
		"kuerzel": "I.01.2.07910",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"kuerzelKunde": "4.01",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-09T08:20:02",
		"id": 7910
	},
	{
		"template": "template001_print",
		"data-id": 7911,
		"chart-id": 7911,
		"filter": "",
		"parentId": "7673",
		"children": [],
		"title": "Wanderungssaldo nach Zuzugs- und Wegzugsort",
		"subtitle": "Wohnviertel Rosental",
		"lesehilfe": "Im Jahr 2023 weist das Rosentalviertel einen positiven Wanderungssaldo auf. Dieser ist auf Zuzüge aus dem Ausland zurückzuführen.",
		"erlaeuterungen": "Schweizerische ausserkantonale Agglomerationsgemeinden: Aesch, Allschwil, Arboldswil, Arlesheim, Augst, Bättwil, Biel-Benken, Binningen, Ettingen, Frenkendorf, Füllinsdorf, Gelterkinden, Gempen, Giebenach, Grellingen, Himmelried, Hochwald, Hofstetten-Flüh, Hölstein, Itingen, Kaiseraugst, Lampenberg, Laufen, Lausen, Liestal, Lupsingen, Magden, Möhlin, Mumpf, Münchenstein, Muttenz, Nenzlingen, Niederdorf, Nuglar-St. Pantaleon, Oberdorf, Oberwil, Ormalingen, Pfeffingen, Pratteln, Ramlinsburg, Reinach, Rheinfelden, Rodersdorf, Röschenz, Rünenberg, Schönenbuch, Seltsiberg, Sissach, Stein, Tecknau, Tenniken, Therwil, Thürnen, Wahlen, Wallbach, Witterswil, Zeinigen, Ziefen, Zunzgen, Zwingen; dazu kamen 2016: Arisdorf, Bärschwil, Bennwil, Bretzwil, Buckten, Burg im Leimental, Büsserach, Buus, Dittingen, Fehren, Hellikon, Hemmiken, Hersberg, Känerkinden, Kleinlützel, Lauwil, Maisprach, Meltingen, Metzerlen-Mariastein, Nunningen, Nusshof, Obermumpf, Olsberg, Reigoldswil, Rickenbach, Rümlingen, Seewen, Titterten, Wegenstetten, Wenslingen, Wintersingen, Wittinsburg, Zullwil und Zunzgen; nicht mehr dazu gehören seit 2016: Stein und Wallbach.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wanderungssaldo nach Zuzugs- und Wegzugsort",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"kuerzelKunde": "2.09",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-20T08:24:38",
		"id": 7911
	},
	{
		"title": "Segregationsindex nach Staatsangehörigkeit",
		"subtitle": "Wohnviertel Rosental",
		"kuerzel": "I.01.1.07912",
		"kuerzelKunde": "2.11",
		"description": "Segregationsindex nach Staatsangehörigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:31.3131",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "2018 wiesen Personen aus der Türkei weitaus den höchsten Segregationsindex auf (33,4). Der hohe Wert bedeutet, dass die Wohnorte dieser Bevölkerungsgruppe am stärksten auf einzelne Blöcke im Wohnviertel Rosental konzentriert waren. Mit deutlichem Abstand folgten Personen aus dem Balkan (17,9) und der Länderguppe EU-Ost (18,4). Die niedrigsten Indices ergaben sich 2018 für die Personen aus der Gruppe EU-17 + EFTA (14,6) sowie für die Schweizer (13,4). Im Vergleich zu 1999 haben die Segregationsindices aller Ländergruppen mit Ausnahme desjenigen der Türken abgenommen.",
		"erlaeuterungen": "Der Segregationsindex ist ein Mass zur Beschreibung räumlicher Ungleichverteilungen von Bevölkerungsgruppen. Er misst hier, wie stark die Verteilung einer Bevölkerungsgruppe über das Wohnviertel Rosental von einer Gleichverteilung abweicht, wobei 0 absolute Gleichverteilung und 100 maximale Segregation bedeutet. Der Wert des Segregationsindexes lässt sich auch als Prozentanteil der betrachteten Gruppe interpretieren, der in einen anderen Block umziehen müsste, um gleich über das Wohnviertel Rosental verteilt zu sein wie die übrige Bevölkerung. Ein Segregationsindex von 0 bedeutet, dass der Anteil Personen einer Gruppe am Total der Bevölkerung in jedem Teilgebiet gleich gross ist.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_00_00_00_00_011",
		"parentId": 7674,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7912,
		"chart-id": 7912,
		"filter": "",
		"id": 7912
	},
	{
		"title": "Religionszugehörigkeit",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"kuerzel": "I.01.7.07913",
		"kuerzelKunde": "2.06",
		"description": "Religionszugehörigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Religionen",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:31.3131",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "In beiden Bezirken des Wohnviertels Rosental bildeten in den Jahren 2014 bis 2018 die Einwohner, die keiner Religionsgemeinschaft angehören oder deren Zugehörigkeit unbekannt ist, die grösste Gruppe. Die zweitgrösste Gruppe bildeten Personen, die einer nicht öffentlich-rechtlich anerkannten Religionsgemeinschaft angehörten.",
		"erlaeuterungen": "Im Kanton Basel-Stadt sind folgende Religionsgemeinschaften öffentlich-rechtlich anerkannt: Evangelisch-reformiert, Römisch-katholisch, Christkatholisch, Israelitisch.",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_00_00_00_00_006",
		"parentId": 7675,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7913,
		"chart-id": 7913,
		"filter": "",
		"id": 7913
	},
	{
		"title": "Mittelwert und Median des Reineinkommens",
		"subtitle": "in Fr., Wohnviertel Rosental, nach Bezirk",
		"kuerzel": "I.18.2.07914",
		"kuerzelKunde": "3.06",
		"description": "Mittelwert und Median des Reineinkommens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:32.3232",
		"stufe1": "3 Erwerbsleben und öffentliche Finanzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Bezirk Erlenmatt liegt der Mittelwert des Reineinkommens im Jahr 2016 bei rund 79 500 Franken, der Median bei 60 900 Franken. Es liegen dort aktuell 886 Veranlagungen vor. Im Jahr 2005 waren es nur 74 Veranlagungen. Im Bezirk Messe beträgt der Mittelwert 45 500 Franken, der Median 39 500 Franken. Hier ist die Zahl der Veranlagungen deutlich höher und beträgt 2016 insgesamt 2 477 (2005: 2 443).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "03_00_00_00_00_006",
		"parentId": 7676,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7914,
		"chart-id": 7914,
		"filter": "",
		"id": 7914
	},
	{
		"title": "Mittelwert und Median des Reinvermögens",
		"subtitle": "in Fr., Wohnviertel Rosental, nach Bezirk",
		"kuerzel": "I.18.2.07915",
		"kuerzelKunde": "3.07",
		"description": "Mittelwert und Median des Reinvermögens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:32.3232",
		"stufe1": "3 Erwerbsleben und öffentliche Finanzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Bezirk Erlenmatt liegt der Mittelwert des Reinvermögens im Jahr 2016 bei rund 159 400 Franken, der Median bei 16 800 Franken. Es liegen dort akutell 886 Veranlagungen vor. Im Jahr 2005 waren es nur 74 Veranlagungen. Im Bezirk Messe beträgt der Mittelwert 69 100 Franken, der Median 2 000 Franken. Hier ist die Zahl der Veranlagungen deutlich höher und beträgt 2016 insgesamt 2 477 (2005: 2 443).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "03_00_00_00_00_007",
		"parentId": 7677,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7915,
		"chart-id": 7915,
		"filter": "",
		"id": 7915
	},
	{
		"title": "Steuerertrag durch Zu- und Wegzüger",
		"subtitle": "in Fr., Wohnviertel Rosental, nach Bezirk",
		"kuerzel": "I.18.2.07916",
		"kuerzelKunde": "3.08",
		"description": "Steuerertrag durch Zu- und Wegzüger",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:32.3232",
		"stufe1": "3 Erwerbsleben und öffentliche Finanzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Sowohl im Bezirk Messe als auch im Bezirk Erlenmatt sind in fast allen Jahren durch die Zuzüger mehr Steuereinnahmen erzielt worden, als durch die Wegzüger verlorenging. Beim Bezirk Erlenmatt kamen durch die neuen Wohnbauten entsprechend mehr Einwohner hinzu. Dies zeigt zum Beispiel der hohe Ertrag von Zuzügern im Jahr 2015 (148 Zuzüger gegenüber 17 Wegzügern).",
		"erlaeuterungen": "Seit der eidgenössischen Steuerharmonisierung im Jahr 2002 ist für die Steuerpflicht innerhalb der Schweiz der Wohnsitz am 31. Dezember massgebend. Es liegen daher in Basel-Stadt in der Regel keine Daten zur Einkommens- und Vermögenssituation im Jahr des Wegzugs vor. Für die Steuerstatistik der Wegzügerinnen und Wegzüger wurden daher die Steuerdaten des jeweiligen Vorjahres verwendet. Bei der Definition der Zuzüger wurde berücksichtigt, dass Ausländer ohne Niederlassungsbewilligung in der Regel an der Quelle veranlagt werden. Aus diesem Grund wurde ein Zuzug erst bei einer Niederlassung als solcher gezählt. Quellensteuerpflichtige sind in der Regel nicht erfasst, ausser sie werden nachträglich ordentlich veranlagt. Dies ist zum Beispiel der Fall, wenn die Einkünfte mehr als 120 000 Franken im Kalenderjahr betragen.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "03_00_00_00_00_008",
		"parentId": 7678,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7916,
		"chart-id": 7916,
		"filter": "",
		"id": 7916
	},
	{
		"title": "Wohnungen nach Zimmerzahl",
		"subtitle": "Wohnviertel Rosental",
		"kuerzel": "I.09.1.07917",
		"kuerzelKunde": "4.03",
		"description": "Wohnungen nach Zimmerzahl",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:32.3232",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Durch die Überbauungen auf dem Entwicklungsareal Erlenmatt konnte das Wohnviertel Rosental 2015 und 2018 einen grossen Zuwachs an Wohnungen verzeichnen.",
		"erlaeuterungen": "Als Zimmer gelten Räume, welche als bauliche Einheit die Wohnung bilden. Küchen, Badezimmer, Toilettenräume, Reduits, Gänge, Veranden usw. gelten nicht als Zimmer. Ebensowenig werden halbe Zimmer gezählt.",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "04_00_00_00_00_003",
		"parentId": 7679,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7917,
		"chart-id": 7917,
		"filter": "",
		"id": 7917
	},
	{
		"title": "Wohnungen nach Belegungsart",
		"subtitle": "Wohnviertel Rosental",
		"kuerzel": "I.09.1.07918",
		"kuerzelKunde": "4.04",
		"description": "Wohnungen nach Belegungsart",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:32.3232",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Wohnviertel Rosental sind 2018 2 905 Mietwohnungen, 165 Eigentümerwonungen und 110 Genossensschaftswohnungen registriert. Der Anteil der Mietwohnungen gemessen am Gesamtbestand beträgt im betrachteten Zeitraum stets über 90%.",
		"erlaeuterungen": "Die Daten beziehen sich auf die belegten Wohnungen (Haushalte). Sonstige Wohnungen umfassen Notwohnungen der Sozialhilfe, subventionierte Wohnungen gemeinnütziger Institutionen, Dienst- und Abwartswohnungen.",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "04_00_00_00_00_004",
		"parentId": 7680,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7918,
		"chart-id": 7918,
		"filter": "",
		"id": 7918
	},
	{
		"title": "Wohnfläche pro Person",
		"subtitle": "in m<sup>2</sup>, Wohnviertel Rosental, nach Bezirk",
		"kuerzel": "I.09.1.07919",
		"kuerzelKunde": "4.02",
		"description": "Wohnfläche pro Person",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:32.3232",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die durchschnittliche Wohnfläche pro Person ist im betrachteten Zeitraum im Bezirk Erlenmatt stets höher als im Bezirk Messe. 2018 beträgt sie 35,3 m<sup>2</sup> (Erlenmatt) respektive 32,9 m<sup>2</sup>.",
		"erlaeuterungen": "Die durchschnittliche Wohnfläche pro Bewohner berechnet sich aus der Gesamtfläche der bewohnten Wohnungen, dividiert durch die Summe der zugeordneten Bewohner. Als Wohnungsfläche gelten sämtliche bewohnbaren Flächen einer Wohnung, also die Summe der Flächen sämtlicher Zimmer, Küchen, Kochnischen, Badezimmer, Toilettenräume, Abstellräume, Gänge, Veranden etc. einer Wohnung (ohne Terrassen oder offene Balkone). Für die Berechnung werden sämtliche einer Wohnung zugeordneten Bewohner berücksichtigt, unabhängig von ihrem Meldeverhältnis (Niedergelassene und Aufenthalter). Personen mit mehreren Wohnsitzen werden entsprechend mehrmals gezählt.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "04_00_00_00_00_002",
		"parentId": 7681,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7919,
		"chart-id": 7919,
		"filter": "",
		"id": 7919
	},
	{
		"title": "Leerwohnungsquote",
		"subtitle": "Wohnviertel Rosental",
		"kuerzel": "I.09.1.07920",
		"kuerzelKunde": "4.05",
		"description": "Leerwohnungsquote",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:32.3232",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Das Wohnviertel Rosental wies in den 00er-Jahren hohe Leerwohnungsquoten aus. Bis 2014 sank die Quote und anschliessend stieg sie wieder. Die hohe Quote 2019 ist durch die Fertigstellung einer Grossüberbauung kurz vor dem Stichtag verursacht.",
		"erlaeuterungen": "Stichtag ist der 1. Juni. Nur Wohnungen, die für den eigentlichen Wohnungsmarkt in Betracht kommen; also ohne leere Wohnungen, die für den Abbruch oder Umbau bestimmt sind. Die Prozentangaben beziehen sich auf den Leerwohnungsbestand am Gesamtwohnungsbestand.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "04_00_00_00_00_005",
		"parentId": 7682,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7920,
		"chart-id": 7920,
		"filter": "",
		"id": 7920
	},
	{
		"title": "Nettomietpreise nach Wohnviertel",
		"subtitle": "in Fr. pro m<sup>2</sup>, Basel-Stadt, 2015-2017",
		"kuerzel": "I.09.3.07921",
		"kuerzelKunde": "4.06",
		"description": "Nettomietpreise nach Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Mietpreise",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:32.3232",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die Nettomiete pro m² von 3- und 4-Zimmer-Wohnungen liegt im Wohnviertel Rosental bei ungefähr 18,5 Franken.",
		"erlaeuterungen": "Der m²-Preis bezieht sich auf die Nettomiete, dividiert durch die Wohnfläche von 3- oder 4- Zimmer-Wohnungen. Die Daten stammen aus der Strukturerhebung. Die Strukturerhebung ist eine Stichprobenerhebung, weshalb die Schätzungen mit einer gewissen Ungenauigkeit verbunden sind. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2015 bis 2017 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese drei Jahre interpretiert werden.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "04_00_00_00_00_006",
		"parentId": 7683,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7921,
		"chart-id": 7921,
		"filter": "",
		"id": 7921
	},
	{
		"title": "Anteil Einfamilienhäuser",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"kuerzel": "I.09.1.07922",
		"kuerzelKunde": "4.07",
		"description": "Anteil Einfamilienhäuser",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:32.3232",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Weil es im Bezirk Erlenmatt nur wenige grosse Mehrfamilienhäuser gibt, bewirkte der Bau von sechs neuen Einfamilienhäusern 2015 einen Sprung auf fast 20%.",
		"erlaeuterungen": "Anteil der Einfamilienhäuser an allen bewohnbaren Gebäuden des Wohnviertels oder Bezirkes in Prozent.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "04_00_00_00_00_007",
		"parentId": 7684,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7922,
		"chart-id": 7922,
		"filter": "",
		"id": 7922
	},
	{
		"title": "Umgebaute Wohnungen",
		"subtitle": "nach Art des Umbaus, Wohnviertel Rosental",
		"kuerzel": "I.09.1.07923",
		"kuerzelKunde": "4.08",
		"description": "Umgebaute Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-17T09:06:06.066",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Wohnviertel Rosental war der Umbausaldo im betrachteten Zeitraum meist positiv. Am meisten Zugänge entstanden durch Dachstock- oder andere Ausbauten.",
		"erlaeuterungen": "",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "04_00_00_00_00_008",
		"parentId": 7685,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Baustatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7923,
		"chart-id": 7923,
		"filter": "",
		"id": 7923
	},
	{
		"title": "Nettowohnungsproduktion",
		"subtitle": "Wohnviertel Rosental",
		"kuerzel": "I.09.1.07924",
		"kuerzelKunde": "4.09",
		"description": "Nettowohnungsproduktion",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:32.3232",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Seit 2004 wird im Wohnviertel Rosental, insbesondere im Bezirk Erlenmatt, sehr viel neu gebaut. Die Zahl der Abbrüche ist gering und der Umbausaldo meist leicht positiv, womit die Nettoproduktion, besonders im Bezirk Erlenmatt, sehr hoch ist.",
		"erlaeuterungen": "Die Nettowohnungsproduktion setzt sich wie folgt zusammen: Neu gebaute Wohnungen minus abgebrochene Wohnungen plus Saldo aus Umbauten (kann positiv oder negativ sein).",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "04_00_00_00_00_009",
		"parentId": 7686,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Baustatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7924,
		"chart-id": 7924,
		"filter": "",
		"id": 7924
	},
	{
		"title": "Anteil Genossenschaften an Neubauten",
		"subtitle": "Wohnviertel Rosental",
		"kuerzel": "I.09.1.07925",
		"kuerzelKunde": "4.10",
		"description": "Anteil Genossenschaften an Neubauten",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:32.3232",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Während im Kanton der Anteil der Genossenschaftswohnungen gut 10,0% beträgt, sind es im Wohnviertel Rosental zwischen 2,0 und 3,4%.",
		"erlaeuterungen": "Es werden nur Wohnungen berücksichtigt, welche am Stichtag (31.12.) durch mindestens eine Person belegt waren.",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "04_00_00_00_00_010",
		"parentId": 7687,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7925,
		"chart-id": 7925,
		"filter": "",
		"id": 7925
	},
	{
		"title": "Anteil an der Gesamtbeschäftigung Basel-Stadt",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"kuerzel": "I.03.2.07926",
		"kuerzelKunde": "3.01",
		"description": "Anteil an der Gesamtbeschäftigung Basel-Stadt",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:31.3131",
		"stufe1": "3 Erwerbsleben und öffentliche Finanzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Jahr 2017 sind im Kanton Basel-Stadt 190 966 Beschäftigte tätig. Davon arbeiten 3 930 im Bezirk Messe und 1 309 im Bezirk Erlenmatt. Anteilsmässig sind dies 2,1% bzw. 0,7%. Insgesamt entfallen somit 2,8% der Beschäftigung des Kantons Basel-Stadt auf das Wohnviertel Rosental.",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und die einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Referenzperiode ist jeweils der Dezember des Jahres.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "03_00_00_00_00_001",
		"parentId": 7688,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7926,
		"chart-id": 7926,
		"filter": "",
		"id": 7926
	},
	{
		"title": "Beschäftigung nach ausgewählten Branchen",
		"subtitle": "Wohnviertel Rosental",
		"kuerzel": "I.03.2.07927",
		"kuerzelKunde": "3.03",
		"description": "Beschäftigung nach ausgewählten Branchen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:32.3232",
		"stufe1": "3 Erwerbsleben und öffentliche Finanzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die wichtigste Branche im Wohnviertel Rosental ist die Forschung und Entwicklung mit 1 608 Beschäftigten im Jahr 2017, gefolgt von den Sonstigen wirtschaftlichen Dienstleistungen (599) und der Branche Erziehung und Unterricht (492). Personalvermittlung und -überlassung (437), Baugewerbe (376) sowie Beherbergung und Gastronomie (284) sind weitere Branchen mit substantiellen Beschäftigtenzahlen.",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben, und die einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Referenzperiode ist jeweils der Dezember des Jahres.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "03_00_00_00_00_003",
		"parentId": 7689,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7927,
		"chart-id": 7927,
		"filter": "",
		"id": 7927
	},
	{
		"template": "template001_print",
		"data-id": 7928,
		"chart-id": 7928,
		"filter": "",
		"parentId": "7690",
		"children": [],
		"title": "Anzahl Rotlichtsalons",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"lesehilfe": "Im Bezirk Messe gab es im Jahr 2022 insgesamt 15 Rotlichtsalons (2006 waren es deren 20), im Bezirk Erlenmatt einen einzigen. Insgesamt waren im Jahr 2022 im Kanton Basel-Stadt 119 Rotlichtsalons registriert.",
		"erlaeuterungen": "Für die Jahre 2008 und 2012 liegen keine Daten vor.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Anzahl Rotlichtsalons",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.07928",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"kuerzelKunde": "3.09",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:55",
		"id": 7928
	},
	{
		"title": "Nettoerwerbstätigenquote",
		"subtitle": "Wohnviertel Rosental",
		"kuerzel": "I.03.1.07929",
		"kuerzelKunde": "3.04",
		"description": "Nettoerwerbstätigenquote",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:32.3232",
		"stufe1": "3 Erwerbsleben und öffentliche Finanzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Wohnviertel Rosental lag die Nettoerwerbstätigenquote im Mittel der Jahre 2013 bis 2017 bei 72,8%.",
		"erlaeuterungen": "Die Nettoerwerbstätigenquote ist definiert als die Anzahl der Erwerbstätigen, geteilt durch die Wohnbevölkerung im Alter von 15 bis 64 Jahren. Bis 2000 stammen die Daten zu den Erwerbspersonen aus der Eidgenössischen Volkszählung (Vollerhebung), seit 2010 aus der Strukturerhebung. Die Strukturerhebung ist eine Stichprobenerhebung, weshalb die Schätzungen mit einer gewissen Ungenauigkeit verbunden sind. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2013 bis 2017 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "03_00_00_00_00_004",
		"parentId": 7691,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)",
			"Bundesamt für Statistik (BFS), Volkszählung (VZ)"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7929,
		"chart-id": 7929,
		"filter": "",
		"id": 7929
	},
	{
		"template": "line001_print",
		"data-id": 7930,
		"chart-id": 7930,
		"filter": "",
		"parentId": "7692",
		"children": [],
		"title": "Bruttogeschossfläche Wohnen und Arbeiten",
		"subtitle": "in m<sup>2</sup>, Wohnviertel Rosental, nach Bezirk",
		"lesehilfe": "Die Bruttogeschossflächen Wohnen und Arbeiten haben im Bezirk Erlenmatt aufgrund der Bautätigkeit seit 2005 deutlich zugenommen.",
		"erlaeuterungen": "Die Daten zur Bruttogeschossfläche (BGF) wurden bis 2020 fünfjährlich aktualisiert. Die Erhebungsmethodik wurde im Rahmen der Berechnung der Daten für das Jahr 2020 überarbeitet, sie sind damit nicht direkt vergleichbar mit den Vorjahren. Ab 2020 werden die Daten jährlich aktualisiert. Die Bruttogeschossfläche ist die Summe der Grundflächen der ober- und unterirdischen Geschosse von Gebäuden, welche zum Wohnen oder Arbeiten genutzt werden können. Für das Jahr 2000 stehen keine Daten zur Verfügung.",
		"quellenangabe": [
			"Bau- und Verkehrsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Bruttogeschossfläche Wohnen und Arbeiten",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.07930",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"kuerzelKunde": "3.02",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:49",
		"id": 7930
	},
	{
		"title": "Nettoerwerbsquote der Frauen",
		"subtitle": "Wohnviertel Rosental",
		"kuerzel": "I.03.1.07931",
		"kuerzelKunde": "3.05",
		"description": "Nettoerwerbsquote der Frauen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:32.3232",
		"stufe1": "3 Erwerbsleben und öffentliche Finanzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Wohnviertel Rosental lag die Nettoerwerbsquote der Frauen im Mittel der Jahre 2013 bis 2017 bei 75,1%.",
		"erlaeuterungen": "Die Nettoerwerbsquote ist definiert als die Summe der Erwerbspersonen (Erwerbstätige plus Erwerbslose), geteilt durch die Wohnbevölkerung im Alter von 15 bis 64 Jahren. Bis 2000 stammen die Daten zu den Erwerbspersonen aus der Eidgenössischen Volkszählung (Vollerhebung), seit 2010 aus der Strukturerhebung. Die Strukturerhebung ist eine Stichprobenerhebung, weshalb die Schätzungen mit einer gewissen Ungenauigkeit verbunden sind. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2013 bis 2017 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "03_00_00_00_00_005",
		"parentId": 7693,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)",
			"Bundesamt für Statistik (BFS), Volkszählung (VZ)"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7931,
		"chart-id": 7931,
		"filter": "",
		"id": 7931
	},
	{
		"template": "line001_print",
		"data-id": 7932,
		"chart-id": 7932,
		"filter": "",
		"parentId": "7694",
		"children": [],
		"title": "Sozialhilfebezüger und -quote",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"lesehilfe": "2021 beträgt die Sozialhilfequote im Bezirk Messe 11,4%. 529 Personen wurden im Verlaufe des Jahres mindestens einmal von der Sozialhilfe finanziell unterstützt. Der Bezirk Erlenmatt weist eine Quote von 0,3% auf; die Anzahl Bezügerinnen und Bezüger beläuft sich auf 10.",
		"erlaeuterungen": "Soziahilfequote: Anteil der im Jahresverlauf unterstützten Sozialhilfeempfänger am Endjahresbestand der Bevölkerung der entsprechenden Raumeinheit. Es sind alle sozialhilfebeziehenden Personen berücksichtigt, die im Verlaufe eines Jahres mindestens eine bedarfsabhängige Sozialhilfeleistung erhalten haben. Die Dossiertypen Asyl und Flüchtling sind ebenfalls berücksichtigt. Asylsuchende mit Nichteintretens- oder Negativentscheid (NEE-NE-Dossiers) werden aus den Auswertungen ausgeschlossen, weil diese Personen nicht Sozialhilfe, sondern Nothilfe erhalten.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Sozialhilfebezüger und -quote",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe und Notwohnen",
		"kuerzel": "I.13.3.07932",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"kuerzelKunde": "5.04",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:11",
		"id": 7932
	},
	{
		"template": "line001_print",
		"data-id": 7933,
		"chart-id": 7933,
		"filter": "",
		"parentId": "7695",
		"children": [],
		"title": "Sek P-Quote nach Staatsangehörigkeit",
		"subtitle": "Wohnviertel Rosental",
		"lesehilfe": "Die Sek P-Quote der Schülerinnen und Schüler ohne Schweizer Pass liegt 2022 im Wohnviertel Rosental mit 34,2% bereits zum dritten Mal in Folge höher als jene der Schweizerinnen und Schweizer (21,2%). Für die Stadt Basel beträgt der Wert 2022 35,8%. Unruhiger Kurvenverlauf aufgrund der geringen Zahl an Beobachtungen.",
		"erlaeuterungen": "Seit 2017/18 Anteil der Sek-Schülerinnen und Schüler im Leistungszug P mit hohen Anforderungen an allen Sek-Schülerinnen und Schülern der 10. und 11. Schulstufe (einschliesslich zweier obligatorischer Kindergartenstufen gezählt) an öffentlichen Schulen und mit Wohnort Basel-Stadt. Bis Schuljahr 2015/16 Anteil der Gymnasiastinnen und Gymnasiasten an allen Schülerinnen und Schülern der 10. und 11. Schulstufe. Im Übergangsjahr 2016/17 wurde als Hilfskonstrukt für Stufe 10 der Sek P-Anteil und für Stufe 11 der Gym-Anteil herangezogen. Stichtag der Bildungsstatistik ist jeweils im September; das Jahr 2022 in der Grafik entspricht Schuljahr 2022/23.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bildungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Sek P-Quote nach Staatsangehörigkeit",
		"thema": "15 Bildung",
		"unterthema": "Schulen und Schulpersonal",
		"kuerzel": "I.15.1.07933",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"kuerzelKunde": "5.02",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-15T08:14:09",
		"id": 7933
	},
	{
		"template": "line001_print",
		"data-id": 7934,
		"chart-id": 7934,
		"filter": "",
		"parentId": "7696",
		"children": [],
		"title": "Anteil deutschsprachiger Kinder in Kindergarten und Primarschule",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"lesehilfe": "Während beim Bezirk Messe der Anteil deutschsprachiger Schulkinder nur langsam steigt, verzeichnet der sich im baulichen Umbruch befindliche Bezirk Erlenmatt im Beobachtungszeitraum eine dynamische Entwicklung hin zu einer ausgeglicheneren Verteilung deutsch- und fremdsprachiger Kinder. 2022 liegen die Quoten für beide Bezirke tiefer als im Vorjahr.",
		"erlaeuterungen": "Der Indikator zeigt den Anteil der Schülerinnen und Schüler mit Erstsprache Deutsch an allen Schülerinnen und Schülern der öffentlichen Kindergärten und Primarschulen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bildungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anteil deutschsprachiger Kinder in Kindergarten und Primarschule",
		"thema": "15 Bildung",
		"unterthema": "Schulen und Schulpersonal",
		"kuerzel": "I.15.1.07934",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"kuerzelKunde": "5.01",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-15T08:14:08",
		"id": 7934
	},
	{
		"title": "Anteil der Bevölkerung mit tertiärem Bildungsabschluss",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2013-2017",
		"kuerzel": "I.15.6.07935",
		"kuerzelKunde": "5.03",
		"description": "Anteil der Bevölkerung mit tertiärem Bildungsabschluss",
		"thema": "15 Bildung",
		"unterthema": "Bildungsniveau",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:33.3333",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Wohnviertel Rosental betrug der Anteil Personen mit tertiärem Bildungsabschluss im Zeitraum von 2013 bis 2017 im Mittel 33,7 Prozent.",
		"erlaeuterungen": "Anteil der Personen mit höchstem Bildungsabschluss Tertiärstufe an der über 14-jährigen Wohnbevölkerung. Die Tertiärstufe umfasst die höhere Berufsbildung, z. B. eine höhere Fachschule für Technik oder Wirtschaft, sowie Ausbildungen an Hochschulen wie z. B. ein Bachelor- oder Masterstudium. Die Daten stammen aus der Strukturerhebung. Die Strukturerhebung ist eine Stichprobenerhebung, weshalb die Schätzungen mit einer gewissen Ungenauigkeit verbunden sind. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2013 bis 2017 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "05_00_00_00_00_003",
		"parentId": 7697,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7935,
		"chart-id": 7935,
		"filter": "",
		"id": 7935
	},
	{
		"template": "line001_print",
		"data-id": 7936,
		"chart-id": 7936,
		"filter": "",
		"parentId": "7698",
		"children": [],
		"title": "Anteil Haushalte mit Familienmietzinsbeiträgen resp. reinen Prämienverbilligungen",
		"subtitle": "Wohnviertel Rosental",
		"lesehilfe": "3,3% der Haushalte im Wohnviertel Rosental erhalten Ende 2021 Familienmietzinsbeiträge (Kanton: 2,3%). In 20,2% der Haushalte bezieht mindestens eine Person reine Prämienverbilligungen (Kanton: 17,0%).",
		"erlaeuterungen": "Anteil Haushalte mit Prämienverbilligungen: Es werden alle Haushalte mit mindestens einer Person mit reiner Prämienverbilligung gezählt (ohne Bezügerinnen und Bezüger von Ergänzungsleistungen und Sozialhilfe).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Basler Informationssystem Sozialleistungen (BISS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anteil Haushalte mit Familienmietzinsbeiträgen resp. reinen Prämienverbilligungen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.07936",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"kuerzelKunde": "5.05",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:11",
		"id": 7936
	},
	{
		"template": "template001_print",
		"data-id": 7937,
		"chart-id": 7937,
		"filter": "",
		"parentId": "7699",
		"children": [],
		"title": "Bodenbedeckung nach Nutzungsart",
		"subtitle": "Anteil an der Bezirksfläche, Wohnviertel Rosental, nach Bezirk",
		"lesehilfe": "Im Bezirk Messe ist über den gesamten betrachteten Zeitraum der Grossteil des Bodens mit Gebäuden bedeckt (2021: 46,4%). Im Bezirk Erlenmatt zeigt sich die Transformation hin zu einem Wohngebiet: Die «Übrigen befestigten Flächen» haben sich verringert (2009: 56,7%; 2021: 24,8%) und die Grünflächen haben zugenommen (2009: 2,8%; 2021: 25,6%).",
		"erlaeuterungen": "Grünfläche: alle privaten und öffentlichen bestockten (Wald, Übrige) oder humusierten Flächen (Acker, Wiese, Friedhof, Gartenanlage, Gewässervorland, Park, Reben, Schrebergarten, Sportanlage, Tierpark, Übrige). Gewässer: stehende und fliessende Gewässer. Verkehrsfläche: Befestigte Flächen wie Strassen, Wege, Trottoirs (inkl. Rabatten) und Verkehrsinseln sowie Bahn- und Tramareale. Übrige befestigte Flächen: Hafen- und Fabrikareale; Tankanlagen; Wasserbecken und befestigtes Gewässervorland; befestigte Sportanlagen; alle weiteren befestigten Flächen. Als befestigt gelten künstlich hergerichtete Flächen, insbesondere asphaltierte, betonierte, bekieste, gemergelte oder mit Steinen oder Platten belegte Flächen. <br>Die Angaben basieren auf der Datenebene «Bodenbedeckung» der amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100 m<sup>2</sup> geführt werden. Diese werden bei Bedarf oder spätestens in einem Turnus von 6 bis 12 Jahren mit einer periodischen Nachführung aktualisiert. Befestigte Objekte wie Gebäude, Strassenräume oder öffentliche Pärke werden detaillierter erfasst und bei baulichen Änderungen nachgeführt.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [
			"Die Daten der Bodenbedeckung im <a href = 'https://map.geo.bs.ch/s/0JGP' target = '_blank'>kantonalen Geoportal</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Bodenbedeckung nach Nutzungsart",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.07937",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"kuerzelKunde": "7.01",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:16",
		"id": 7937
	},
	{
		"template": "template001_print",
		"data-id": 7938,
		"chart-id": 7938,
		"filter": "",
		"parentId": "7700",
		"children": [],
		"title": "Grünflächen nach Kategorie",
		"subtitle": "in m<sup>2</sup>, Wohnviertel Rosental, nach Bezirk",
		"lesehilfe": "Im Bezirk Messe macht die Bodenbedeckungsart «Gartenanlagen» den Grossteil der Grünflächen aus (2021: 26 355 m<sup>2</sup>). Im Bezirk Erlenmatt erfolgte 2016 fast eine Verdopplung der Grünflächen von rund 33 200 auf 57 500 m<sup>2</sup>.",
		"erlaeuterungen": "Als Grünfläche gelten alle privaten und öffentlichen bestockten (Wald, Übrige) oder humusierten (Acker, Wiese, Friedhof, Gartenanlage, Gewässervorland, Park, Reben, Schrebergarten, Sportanlage, Tierpark, Übrige) Flächen. Die Angaben basieren auf der Datenebene «Bodenbedeckung» der amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100 m<sup>2</sup> geführt werden. Diese werden bei Bedarf oder spätestens in einem Turnus von 6 bis 12 Jahren mit einer periodischen Nachführung aktualisiert. Befestigte Objekte wie Gebäude, Strassenräume oder öffentliche Pärke werden detaillierter erfasst und bei baulichen Änderungen nachgeführt.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [
			"Die Daten der Bodenbedeckung im <a href = 'https://map.geo.bs.ch/s/5jZH' target = '_blank'>kantonalen Geoportal</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Grünflächen nach Kategorie",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.07938",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"kuerzelKunde": "7.02",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:18",
		"id": 7938
	},
	{
		"title": "Anzahl Tropennächte",
		"subtitle": "nach Wohnviertel, 2018",
		"kuerzel": "I.02.12.07939",
		"kuerzelKunde": "7.04",
		"description": "Anzahl Tropennächte",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Klima",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:33.3333",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "In den Wohnvierteln Rosental und Altstadt Kleinbasel traten 2018 mit 14 Nächten über 20 °C kantonsweit am meisten Tropennächte auf (gemittelt über das gesamte Wohnviertel). Den tiefsten Wert wies die Gemeinde Bettingen mit nur 2 Tropennächten auf.",
		"erlaeuterungen": "Tropennächte sind Nächte, in denen die Temperatur nicht unter 20 °C sinkt. Heissere Flächen sind in der Regel stark bebaute, versiegelte und vegetationsarme Gebiete (z. B. Innenstädte, Industrie- und Bahnareale). Kühlere Flächen finden sich dort, wo genügend Vegetation (z. B. Parks) oder grössere Gewässer (Rhein) vorhanden sind oder wo Kaltluftzufuhr, z. B. aus umliegenden kühleren Gebieten, erfolgen kann. Die Daten basieren auf Modellrechnungen (200 x 200 m-Raster, räumlich gemittelt über das jeweilige Wohnviertel) der Universität Basel für das Jahr 2018 und berücksichtigen neben Temperaturmessungen (an zehn Standorten) auch Topografie, Gebäude, Bäume und die Oberflächenbeschaffenheit des Bodens.",
		"template": "map002_print",
		"darstellungsart": "Karte",
		"printformat": "",
		"orderKey": "07_00_00_00_00_004",
		"parentId": 7701,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"MCR-Lab, Universität Basel"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7939,
		"chart-id": 7939,
		"filter": "",
		"id": 7939
	},
	{
		"title": "Heizsysteme nach Energieträger",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"kuerzel": "I.08.1.07942",
		"kuerzelKunde": "7.07",
		"description": "Heizsysteme nach Energieträger",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:33.3333",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Mit dem Ausbau des Basler Fernwärmenetzes nimmt auch in den Bezirken Messe und Erlenmatt der Anteil fernwärmebeheizter Gebäude stetig zu. Gleichzeit ist der Einsatz von Heizöl rückläufig.",
		"erlaeuterungen": "Die Anzahl Heizsysteme nach Energieträger stammt aus der kantonalen Gebäude- und Wohnungsstatistik, welche jährlich per 31. Dezember aus dem kantonalen Gebäude- und Wohnungsregister (GWR) erzeugt wird.",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "07_00_00_00_00_007",
		"parentId": 7704,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7942,
		"chart-id": 7942,
		"filter": "",
		"id": 7942
	},
	{
		"title": "Stromverbrauch",
		"subtitle": "in Gigawattstunden (GWh), Wohnviertel Rosental, nach Bezirk",
		"kuerzel": "I.08.1.07943",
		"kuerzelKunde": "7.06",
		"description": "Stromverbrauch",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:33.3333",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Zwischen 2010 und 2016 hat der Stromverbrauch im Bezirk Erlenmatt als Folge der Bautätigkeit stetig zugenommen. Auch im Bezirk Messe hat die Bautätigkeit zu einem Anstieg geführt.",
		"erlaeuterungen": "Die kantonale Energiestatistik basiert seit 2010 auf einer neuen methodischen Grundlage und erscheint im Zweijahresrhythmus. Abgebildet ist der jeweilige Endverbrauch.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "07_00_00_00_00_006",
		"parentId": 7705,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7943,
		"chart-id": 7943,
		"filter": "",
		"id": 7943
	},
	{
		"title": "Personenwagen pro Haushalt, Motorisierungsgrad",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"kuerzel": "I.11.1.07944",
		"kuerzelKunde": "7.08",
		"description": "Personenwagen pro Haushalt, Motorisierungsgrad",
		"thema": "11 Verkehr",
		"unterthema": "Motorfahrzeuge",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:33.3333",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "2017 waren im Bezirk Erlenmatt im Schnitt 0,48 Personenwagen pro Haushalt registriert, der Motorisierungsgrad lag bei 223,2 privaten Personenwagen pro 1 000 Einwohnern.",
		"erlaeuterungen": "Anzahl der auf Privatpersonen zugelassenen Personenwagen geteilt durch die Anzahl Haushalte sowie pro 1 000 Einwohner (Motorisierungsgrad). Zur Berechnung wird jeweils der Jahresendbestand der Personenwagen und Einwohner (exkl. Personen an administrativen Meldeadressen) verwendet. Die höheren Werte im Bezirk Erlenmatt für das Jahr 2014 sind auf methodische Unterschiede in der Erfassung von neu- und umgemeldeten Fahrzeugen und Einwohner um den Jahreswechsel zurückzuführen.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "07_00_00_00_00_008",
		"parentId": 7706,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Kantonspolizei Basel-Stadt, Motorfahrzeugkontrolle"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7944,
		"chart-id": 7944,
		"filter": "",
		"id": 7944
	},
	{
		"title": "Feinstaubbelastung",
		"subtitle": "nach Wohnviertel, 2015",
		"kuerzel": "I.02.15.07945",
		"kuerzelKunde": "7.09",
		"description": "Feinstaubbelastung",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Luft",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:42:30.3030",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Wohnviertel Rosental waren 2015 im Jahresmittel mit 1 407 Personen rund 23% der dortigen Wohnbevölkerung an ihrem Wohnort Feinstaub-Immissionen von über 20 µg/m<sup>3</sup> ausgesetzt.",
		"erlaeuterungen": "Anzahl und Anteil Personen, an deren Wohnort im Jahresmittel Feinstaub-Belastungen (PM10) von über 20 µg/m<sup>3</sup> (Jahresgrenzwert gemäss Luftreinhalteverordnung) auftreten. Berechnet basierend auf Daten des Lufthygieneamtes beider Basel (Immissionskarten 10 x 10 m für 2015). Unter PM10 versteht man Partikel, die kleiner sind als 10 Mikrometer. Dieser Staub ist ein physikalisch-chemisch komplexes Gemisch. Er entsteht bei industriellen und gewerblichen Produktionsprozessen, Verbrennungsprozessen, mechanischen Prozessen (Abrieb, Aufwirbelung) sowie durch sekundäre Bildung (aus SO<sub>2</sub>, NO<sub>x</sub>, NH<sub>3</sub>, VOC). PM10 ist in seiner Zusammensetzung sehr vielfältig und kann Russ, Schwermetalle, Sulfat, Nitrat, Ammonium, organischen Kohlenstoff, polyzyklische aromatische Kohlenwasserstoffe oder Dioxine/Furane enthalten. Feinstaub führt zu Erkrankungen der Atemwege, des Herz-Kreislaufsystems, zu einer Zunahme des Krebsrisikos und der Sterberate.",
		"template": "mappie001_print",
		"darstellungsart": "Karte",
		"printformat": "",
		"orderKey": "07_00_00_00_00_009",
		"parentId": 7707,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Lufthygieneamt beider Basel"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			"Weitere Informationen zu <a href = 'http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-11-1109' target = '_blank'>Feinstaub-Immissionen</a> in der Region Basel",
			"Nationale <a href = 'https://www.admin.ch/opc/de/classified-compilation/19850321/index.html#app7ahref0' target = '_blank'>Luftreinhalte-Verordnung (LRV), Anhang 7</a>"
		],
		"data-id": 7945,
		"chart-id": 7945,
		"filter": "",
		"id": 7945
	},
	{
		"title": "Stickoxidbelastung",
		"subtitle": "nach Wohnviertel, 2015",
		"kuerzel": "I.02.15.07946",
		"kuerzelKunde": "7.10",
		"description": "Stickoxidbelastung",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Luft",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:42:23.2323",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Wohnviertel Rosental waren 2015 im Jahresmittel mit 1 980 Personen rund 32% der dortigen Wohnbevölkerung an ihrem Wohnort Stickoxid-Immissionen von über 30 µg/m<sup>3</sup> ausgesetzt.",
		"erlaeuterungen": "Anzahl und Anteil Personen, an deren Wohnort im Jahresmittel Stickstoffdioxid-Belastungen (NO<sub>2</sub>) von über 30 µg/m<sup>3</sup> (Jahresgrenzwert gemäss Luftreinhalteverordnung) auftreten. Berechnet basierend auf Daten des Lufthygieneamtes beider Basel (Immissionen modelliert auf Basis eines 10 x 10 m-Rasters). Stickoxide (NO<sub>x</sub>) entstehen beim Verbrennen von Brenn- und Treibstoffen, insbesondere bei hohen Verbrennungstemperaturen. Hauptquelle ist der Strassenverkehr. Stickoxide sind wichtige Vorläufersubstanzen für die Bildung von sauren Niederschlägen, sekundärem Feinstaub und – zusammen mit flüchtigen organischen Verbindungen – von Ozon/Sommersmog. Stickstoffdioxid (NO<sub>2</sub>) und andere Reizgase begünstigen Erkrankungen der Atemwege.",
		"template": "mappie001_print",
		"darstellungsart": "Karte",
		"printformat": "",
		"orderKey": "07_00_00_00_00_010",
		"parentId": 7708,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Lufthygieneamt beider Basel"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			"Weitere Informationen zu <a href = 'http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-11-1111' target = '_blank'>Stickstoffdioxid-Immissionen</a>in der Region Basel",
			"Nationale <a href = 'https://www.admin.ch/opc/de/classified-compilation/19850321/index.html#app7ahref0' target = '_blank'>Luftreinhalte-Verordnung (LRV), Anhang 7</a>"
		],
		"data-id": 7946,
		"chart-id": 7946,
		"filter": "",
		"id": 7946
	},
	{
		"template": "line001_print",
		"data-id": 7947,
		"chart-id": 7947,
		"filter": "",
		"parentId": "7709",
		"children": [],
		"title": "Freiraumfläche",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"lesehilfe": "Im Bezirk Erlenmatt waren 2021 11,3% der Bezirksfläche Freiraumflächen, im Bezirk Messe nur 0,6% (Stadt Basel: 2,9%).",
		"erlaeuterungen": "Im Bezirk Erlenmatt wurden im abgebildeten Zeitraum durch die Umnutzung des ehemaligen Bahnareals zu Wohngebieten auch neue Freiraumflächen geschaffen. Zu den Freiraumflächen zählen Parkanlagen, Spielplätze und Rasenflächen von Sportanlagen. Die Angaben basieren auf der Datenebene «Bodenbedeckung» der Amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100 m<sup>2</sup> geführt werden. Diese werden bei Bedarf oder spätestens in einem Turnus von 6-12 Jahren mit einer periodischen Nachführung aktualisiert. Befestigte Objekte wie Gebäude, Strassenräume oder öffentliche Pärke werden detaillierter erfasst und bei baulichen Änderungen nachgeführt.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Freiraumfläche",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.07947",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"kuerzelKunde": "7.03",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:18",
		"id": 7947
	},
	{
		"title": "Delikte",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"kuerzel": "I.19.1.07949",
		"kuerzelKunde": "6.01",
		"description": "Delikte",
		"thema": "19 Kriminalität und Strafrecht",
		"unterthema": "Polizei",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:33.3333",
		"stufe1": "6 Sicherheit",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Bezirk Messe ist die Zahl der Delikte zwischen 2009 und 2017 von 19 auf 51 gestiegen. Im Bezirk Erlenmatt war die Zahl der Delikte in den Jahren 2009 bis 2014 sehr niedrig (0 bis 6 Delikte pro Jahr). Seit 2015 werden dort zwischen 4 und 13 Delikte registriert.",
		"erlaeuterungen": "Bei der Kantonspolizei gemeldete Delikte der folgenden Kategorien: Entreissdiebstahl, Raub, Einbruch- und Einschleichdiebstähle in Wohngebieten (Raumeinheiten mit Wohnungen) sowie Sexualdelikte (Vergewaltigung, sexuelle Nötigung).",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "06_00_00_00_00_001",
		"parentId": 7711,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Kantonspolizei Basel-Stadt"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7949,
		"chart-id": 7949,
		"filter": "",
		"id": 7949
	},
	{
		"title": "Einbruch- und Einschleichdiebstähle",
		"subtitle": "Wohnviertel Rosental, nach Bezirk",
		"kuerzel": "I.19.1.07950",
		"kuerzelKunde": "6.02",
		"description": "Einbruch- und Einschleichdiebstähle",
		"thema": "19 Kriminalität und Strafrecht",
		"unterthema": "Polizei",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"aktualisierungsdatum": "2019-12-10T15:05:33.3333",
		"stufe1": "6 Sicherheit",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Bezirk Messe gab es im Jahr 2017 insgesamt 46 Einbruch- oder Einschleichdiebstähle, im Bezirk Erlenmatt 13.",
		"erlaeuterungen": "Bei der Kantonspolizei gemeldete Einbruch- und Einschleichdiebstähle in Wohngebieten (Raumeinheiten mit Wohnungen).",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "06_00_00_00_00_002",
		"parentId": 7712,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Kantonspolizei Basel-Stadt"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7950,
		"chart-id": 7950,
		"filter": "",
		"id": 7950
	},
	{
		"template": "template001_print",
		"data-id": 7951,
		"chart-id": 7951,
		"filter": "",
		"parentId": "7764",
		"children": [],
		"title": "Umzugssaldo",
		"subtitle": "Wohnviertel Rosental",
		"lesehilfe": "Der Bezirk Messe weist für das Jahr 2023 einen negativen Umzugssaldo auf, d. h. es verlegen mehr Personen aus diesem Bezirk ihren Wohnsitz in den übrigen Kanton Basel-Stadt als von dort in den Bezirk Messe. Die hohen Umzugsgewinne im Bezirk Erlenmatt 2015 und 2019 sind auf die Fertigstellung von Wohngebäuden zurückzuführen.",
		"erlaeuterungen": "Umzüge sind räumliche Bevölkerungsbewegungen innerhalb des Kantons Basel-Stadt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Umzugssaldo",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"kuerzelKunde": "2.10",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-20T08:24:39",
		"id": 7951
	},
	{
		"parentId": null,
		"children": [],
		"template": "mappie001_print",
		"title": "Übersichtskarte Wohnviertel",
		"subtitle": "",
		"kennzahlenset": "Stadtteilmonitoring Rosental (Print)",
		"kuerzel": "",
		"kuerzelKunde": "1.01",
		"description": "Übersichtskarte Wohnviertel",
		"thema": "",
		"unterthema": "",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2021-07-13T08:34:13.1313",
		"stufe1": "1 Übersicht",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "<bitte Kommentar erfassen>",
		"erlaeuterungen": "",
		"darstellungsart": "Karte",
		"printformat": "",
		"orderKey": "01_00_00_00_00_000",
		"renderLink": [],
		"quellenangabe": [],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8844,
		"chart-id": 8844,
		"filter": "",
		"id": 8844
	}
];