var indikatorensetData = [
	{
		"template": "spider001_print",
		"data-id": 8615,
		"chart-id": 8615,
		"filter": "",
		"parentId": "6756",
		"children": [],
		"title": "Klybeck - Quartierradar",
		"subtitle": "Ausgabe 2022",
		"lesehilfe": "Das Wohnviertel Klybeck verzeichnet den höchsten Anteil Sozialhilfeempfänger und zweithöchsten Ausländeranteil. Der Altersquotient und die Gymnasialquote sind dagegen niedrig. Die Wohnungen und die Wohnfläche pro Kopf sind die kleinsten im Kanton. Das Wohnviertel weist die niedrigsten Steuererträge und eine sehr geringe Erwerbstätigenquote auf.",
		"erlaeuterungen": "Die Grafik fasst 16 Indikatoren zusammen. Die Indikatoren sind den drei Bereichen <font color=\"923F8D\">Gesellschaft und Soziales</font>, <font color=\"68AB2B\">Raum und Umwelt</font> sowie <font color=\"689199\">Wirtschaft und Arbeit</font> zugeordnet. Die Werte der Indikatoren sind als Ränge im Vergleich zu allen anderen Basler Wohnvierteln und Gemeinden ausgewiesen. Das Wohnviertel oder die Gemeinde mit dem niedrigsten Wert des Indikators erhält Rang 1, mit dem höchsten Wert Rang 21 zugewiesen. Je grösser die graue Fläche, desto öfter erreicht das Wohnviertel oder die Gemeinde hohe Ränge bei den Indikatoren. <a href =\" https://www.statistik.bs.ch/dam/jcr:2cb04e13-b746-4455-8735-029f0439dc73/Quartierradar.pdf \" target = '_blank'>Zur Definition der einzelnen Indikatoren </a>",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Klybeck - Quartierradar",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.08615",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "1.02",
		"stufe1": "1 Übersicht",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:18:51",
		"id": 8615
	},
	{
		"title": "Wohnbevölkerung",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"kuerzel": "I.01.1.08616",
		"kuerzelKunde": "2.01",
		"description": "Wohnbevölkerung",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:27.2727",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Wohnviertel Klybeck lebten Ende 2019 7 237 Einwohner, 2,3% mehr als im Jahr 2000. Im Wohnviertel Kleinhüningen betrug die Einwohnerzahl Ende 2019 2 798, der Zuwachs gegenüber dem Jahr 2000 fiel mit 18,5% deutlich stärker aus. Dies ist wohl teilweise auf den Neubau von Wohnungen an der Hochbergerstrasse (2002) und im Densapark (2011) zurückzuführen. In der Stadt Basel hat die Bevölkerungszahl zwischen 2000 und 2019 um 6,8% zugenommen.",
		"erlaeuterungen": "",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_00_00_00_00_001",
		"parentId": 8046,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8616,
		"chart-id": 8616,
		"filter": "",
		"id": 8616
	},
	{
		"title": "Wohnbevölkerung nach Alter und Geschlecht",
		"subtitle": "Wohnviertel Klybeck, 2019",
		"kuerzel": "I.01.1.08617",
		"kuerzelKunde": "2.02a",
		"description": "Wohnbevölkerung nach Alter und Geschlecht",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:27.2727",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Wohnviertel Klybeck sind die Fünfjahresgruppen der 25- bis 29-Jährigen, der 30- bis 34-Jährigen und der 35- bis 39-Jährigen am stärksten besetzt. Dies ist auch in der Stadt Basel so.",
		"erlaeuterungen": "Die Bevölkerungspyramide zeigt die Wohnbevölkerung am Jahresende nach Alter (Fünfjahresklassen), Geschlecht und Staatsangehörigkeit.",
		"template": "populationPyramid001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_00_00_00_00_002",
		"parentId": 8047,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8617,
		"chart-id": 8617,
		"filter": "",
		"id": 8617
	},
	{
		"template": "line001_print",
		"data-id": 8618,
		"chart-id": 8618,
		"filter": "",
		"parentId": "8048",
		"children": [],
		"title": "Jugendquotient",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Im Wohnviertel Klybeck ist der Jugendquotient zwischen 2001 und 2021 auf 27,1 gesunken. Im Wohnviertel Kleinhüningen hat er leicht zugenommen auf 32,0. In der Stadt Basel lag der Jugendquotient im Jahr 2001 bei 26,9, im Jahr 2021 bei 25,5.",
		"erlaeuterungen": "Der Jugendquotient beschreibt das Verhältnis der Personen im Alter von 19 oder weniger Jahren zu jenen im erwerbsfähigen Alter zwischen 20 und 64 Jahren. Das Verhältnis wird pro 100 Personen zwischen 20 und 64 Jahren ausgewiesen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel",
			"Agglomeration"
		],
		"description": "Jugendquotient",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08618",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "2.03",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:21",
		"id": 8618
	},
	{
		"template": "line001_print",
		"data-id": 8619,
		"chart-id": 8619,
		"filter": "",
		"parentId": "8049",
		"children": [],
		"title": "Altersquotient",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Im Wohnviertel Klybeck liegt der Altersquotient 2021 bei 22,4, im Wohnviertel Kleinhüningen bei 31,9. Im Vergleich zum Jahr 2001 ist der Wert im Wohnviertel Klybeck leicht gesunken, im Wohnviertel Kleinhüningen etwas gestiegen. In der Stadt Basel ist der Altersquotient seit 2001 recht kontinuierlich gesunken.",
		"erlaeuterungen": "Der Altersquotient beschreibt das Verhältnis der Personen im Alter von 65 oder mehr Jahren zu jenen im erwerbsfähigen Alter zwischen 20 und 64 Jahren. Das Verhältnis wird pro 100 Personen zwischen 20 und 64 Jahren ausgewiesen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel",
			"Agglomeration"
		],
		"description": "Altersquotient",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08619",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "2.04",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:22",
		"id": 8619
	},
	{
		"title": "Ausländeranteil",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"kuerzel": "I.01.1.07669",
		"kuerzelKunde": "2.05",
		"description": "Ausländeranteil",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:26.2626",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Der Ausländeranteil schwankte im Wohnviertel Klybeck in den Jahren 2000 bis 2011 zwischen 48,1% und 50,7%. In den folgenden Jahren lag er zwischen 50,0% und 52,4%. Im Wohnviertel Kleinhüningen stieg der Ausländeranteil zwischen 2000 und 2006 von 39,9% auf 46,1%. Danach bewegte er sich bis 2011 zwischen 42,6% und 45,3%. Seither stieg der Anteil Ausländer bis auf 48,0%. In der Stadt Basel stieg der Ausländeranteil über den gesamten Beobachtungszeitraum von 29,4% auf 37,8%.",
		"erlaeuterungen": "Bevölkerungsbestand zum Jahresende.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_00_00_00_00_006",
		"parentId": 8050,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8620,
		"chart-id": 8620,
		"filter": "",
		"id": 8620
	},
	{
		"title": "Ausländer nach Staatsangehörigkeit",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"kuerzel": "I.01.1.08621",
		"kuerzelKunde": "2.07",
		"description": "Ausländer nach Staatsangehörigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:27.2727",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "In den letzten fünf Jahren bildeten im Wohnviertel Klybeck Personen aus den EU-17- und EFTA-Staaten die grösste ausländische Bevölkerungsgruppe. Während die Anzahl Personen aus der Türkei und dem Balkan gesunken ist, stieg die Zahl der Personen aus arabischen und afrikanischen Ländern von 73 auf 110 bzw. von 106 auf 170. Im Wohnviertel Kleinhüningen bildeten Personen aus dem Balkan in den letzten fünf Jahren die grösste ausländische Bevölkerungsgruppe.",
		"erlaeuterungen": "Bevölkerungsbestand zum Jahresende.",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_00_00_00_00_008",
		"parentId": 8051,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8621,
		"chart-id": 8621,
		"filter": "",
		"id": 8621
	},
	{
		"title": "Sesshaftigkeit",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen und Stadt Basel",
		"kuerzel": "I.01.1.08622",
		"kuerzelKunde": "2.08",
		"description": "Sesshaftigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:27.2727",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "In den beiden Wohnvierteln Klybeck und Kleinhüningen liegt der Anteil an Personen, die seit zehn oder mehr Jahren an der gleichen Adresse wohnen, Ende 2019 bei 34,4% und 37,9%. Verglichen mit anderen Wohnvierteln bewegen sich diese Anteile im Mittelfeld. Die Sesshaftigkeit in der Stadt Basel liegt Ende 2019 bei 33,6%.",
		"erlaeuterungen": "Anteil Einwohner, die seit mindestens zehn Jahren an der gleichen Adresse wohnen. Ohne Personen an administrativen Meldeadressen.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_00_00_00_00_009",
		"parentId": 8052,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8622,
		"chart-id": 8622,
		"filter": "",
		"id": 8622
	},
	{
		"template": "template001_print",
		"data-id": 8623,
		"chart-id": 8623,
		"filter": "",
		"parentId": "8053",
		"children": [],
		"title": "Haushalte nach Art des Haushalts",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Die Haushaltsstruktur weist in beiden Wohnvierteln in den letzten Jahren keine grossen Veränderungen auf. Der Anteil Einpersonenhaushalte ist im Wohnviertel Klybeck höher als im Wohnviertel Kleinhüningen (2022: 49% gegenüber 43%).",
		"erlaeuterungen": "Personen, die in der gleichen Wohnung leben, bilden einen Haushalt. Haushalte werden unterteilt in Privathaushalte und Kollektivhaushalte. Hier werden nur Privathaushalte betrachtet. Die Gruppe «Andere Haushalte» umfasst Mehrpersonenhaushalte wie Wohngemeinschaften und unverheiratete Paare ohne ein gemeinsames Kind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Haushalte nach Art des Haushalts",
		"thema": "01 Bevölkerung",
		"unterthema": "Haushalte",
		"kuerzel": "I.01.2.08623",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "4.01",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-09T08:20:04",
		"id": 8623
	},
	{
		"title": "Wanderungssaldo nach Zuzugs- und Wegzugsort",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"kuerzel": "I.01.5.08624",
		"kuerzelKunde": "2.09",
		"description": "Wanderungssaldo nach Zuzugs- und Wegzugsort",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:27.2727",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "In den Jahren 2014 bis 2018 kamen im Wohnviertel Klybeck häufiger positive als negative Wanderungssaldi zustande, im Wohnviertel Kleinhüningen verhielt es sich umgekehrt. Bei beiden sind allfällige Wanderungsgewinne jeweils hauptsächlich auf Zuzüge aus dem Ausland zurückzuführen und ihre Bilanzen gegenüber der Agglomeration Basel waren stets negativ. In der Stadt Basel kamen die positiven Wanderungsbilanzen für die Jahre 2014 bis 2018 ebenfalls hauptsächlich aufgrund der Zuzüge aus dem Ausland zustande.",
		"erlaeuterungen": "Schweizerische ausserkantonale Agglomerationsgemeinden: Aesch, Allschwil, Arboldswil, Arlesheim, Augst, Bättwil, Biel-Benken, Binningen, Ettingen, Frenkendorf, Füllinsdorf, Gelterkinden, Gempen, Giebenach, Grellingen, Himmelried, Hochwald, Hofstetten-Flüh, Hölstein, Itingen, Kaiseraugst, Lampenberg, Laufen, Lausen, Liestal, Lupsingen, Magden, Möhlin, Mumpf, Münchenstein, Muttenz, Nenzlingen, Niederdorf, Nuglar-St. Pantaleon, Oberdorf, Oberwil, Ormalingen, Pfeffingen, Pratteln, Ramlinsburg, Reinach, Rheinfelden, Rodersdorf, Röschenz, Rünenberg, Schönenbuch, Seltsiberg, Sissach, Stein, Tecknau, Tenniken, Therwil, Thürnen, Wahlen, Wallbach, Witterswil, Zeinigen, Ziefen, Zunzgen, Zwingen; dazu kamen 2016: Arisdorf, Bärschwil, Bennwil, Bretzwil, Buckten, Burg im Leimental, Büsserach, Buus, Dittingen, Fehren, Hellikon, Hemmiken, Hersberg, Känerkinden, Kleinlützel, Lauwil, Maisprach, Meltingen, Metzerlen-Mariastein, Nunningen, Nusshof, Obermumpf, Olsberg, Reigoldswil, Rickenbach, Rümlingen, Seewen, Titterten, Wegenstetten, Wenslingen, Wintersingen, Wittinsburg, Zullwil und Zunzgen; nicht mehr dazu gehören seit 2016: Stein und Wallbach.",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_00_00_00_00_010",
		"parentId": 8054,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8624,
		"chart-id": 8624,
		"filter": "",
		"id": 8624
	},
	{
		"title": "Segregationsindex nach Staatsangehörigkeit",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"kuerzel": "I.01.1.08625",
		"kuerzelKunde": "2.11",
		"description": "Segregationsindex nach Staatsangehörigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:28.2828",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "2019 wiesen Personen aus der Gruppe der arabischen Länder den höchsten Segregationsindex auf (39,7). Der hohe Wert bedeutet, dass die Wohnorte dieser Bevölkerungsgruppe am stärksten auf einzelne Blöcke im Gebiet der Wohnviertel Klybeck und Kleinhüningen konzentriert waren. Danach folgten Personen aus der Gruppe der afrikanischen Länder (38,2) und derjenigen der EU-Ost Staaten (29,0). Die niedrigsten Indices ergaben sich 2019 für Italiener (18,1), Schweizer (15,9) und Deutsche (15,7). Im Vergleich zu 2000 haben die Segregationsindices aller Ländergruppen abgenommen.",
		"erlaeuterungen": "Der Segregationsindex ist ein Mass zur Beschreibung räumlicher Ungleichverteilungen von Bevölkerungsgruppen. Er misst hier, wie stark die Verteilung einer Bevölkerungsgruppe über das Gebiet der Wohnviertel Klybeck und Kleinhüningen von einer Gleichverteilung abweicht, wobei 0 absolute Gleichverteilung und 100 maximale Segregation bedeutet. Der Wert des Segregationsindexes lässt sich auch als Prozentanteil der betrachteten Gruppe interpretieren, der in einen anderen Block umziehen müsste, um gleich über das Gebiet der Wohnviertel Klybeck und Kleinhüningen verteilt zu sein wie die übrige Bevölkerung. Ein Segregationsindex von 0 bedeutet, dass der Anteil Personen einer Gruppe am Total der Bevölkerung in jedem Teilgebiet gleich gross ist. Bei kleinräumigen Betrachtungen können die Werte infolge kleiner Gruppengrössen über die Jahre stark schwanken.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_00_00_00_00_012",
		"parentId": 8055,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8625,
		"chart-id": 8625,
		"filter": "",
		"id": 8625
	},
	{
		"title": "Religionszugehörigkeit",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"kuerzel": "I.01.7.08626",
		"kuerzelKunde": "2.06",
		"description": "Religionszugehörigkeit",
		"thema": "01 Bevölkerung",
		"unterthema": "Religionen",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:52.5252",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "In den Wohnvierteln Klybeck und Kleinhüningen bildeten in den Jahren 2010 bis 2019 die Einwohner, die keiner oder einer nicht öffentlich-rechtlichen Religionsgemeinschaft angehören oder deren Zugehörigkeit unbekannt ist, die grösste Gruppe. Ihr Anteil an der Bevölkerung hat in diesem Zeitraum zugenommen, im Wohnviertel Klybeck von 76% auf 83% und im Wohnviertel Kleinhüningen von 76% auf 82%. Die zweitgrösste Gruppe bildeten Angehörige der römisch-katholischen Kirche. Ihr Anteil an der Bevölkerung hat zwischen 2010 und 2019 abgenommen, im Wohnviertel Klybeck von 13% auf 10% und im Wohnviertel Kleinhüningen von 13% auf 11%. In der Stadt Basel ist dieser Anteil im selben Zeitraum von 16% auf 12% gesunken.",
		"erlaeuterungen": "Im Kanton Basel-Stadt sind folgende Religionsgemeinschaften öffentlich-rechtlich anerkannt: evangelisch-reformiert, römisch-katholisch, christkatholisch, israelitisch.",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_00_00_00_00_007",
		"parentId": 8056,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8626,
		"chart-id": 8626,
		"filter": "",
		"id": 8626
	},
	{
		"template": "line001_print",
		"data-id": 8627,
		"chart-id": 8627,
		"filter": "",
		"parentId": "8057",
		"children": [],
		"title": "Mittelwert und Median des Reineinkommens",
		"subtitle": "in Franken, Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Im Steuerjahr 2019 beträgt der Mittelwert des Reineinkommens im Wohnviertel Kleinhüningen rund 45 000 Franken (Median: 39 800), der Mittelwert für Klybeck liegt bei 42 100 Franken (Median: 36 500). Während die Werte in Kleinhüningen über die Jahre relativ konstant blieben, gingen sie im Wohnviertel Klybeck tendenziell etwas zurück. In der Stadt Basel beträgt der Mittelwert 2019 rund 69 200 Franken (Median: 48 700).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen (ordentliche Veranlagung); ohne Auswärtige und ohne Wochenaufenthalter. Einkünfte von Quellenbesteuerten unter 120 000 Franken im Kalenderjahr sind in der Regel in den Auswertungen nicht enthalten.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Mittelwert und Median des Reineinkommens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.08627",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "3.06",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:51",
		"id": 8627
	},
	{
		"template": "line001_print",
		"data-id": 8628,
		"chart-id": 8628,
		"filter": "",
		"parentId": "8058",
		"children": [],
		"title": "Mittelwert und Median des Reinvermögens",
		"subtitle": "in Franken, Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Die Werte für Mittelwert und Median des Reinvermögens sind in den Wohnvierteln Kleinhüningen und Klybeck über die Jahre überwiegend gestiegen. 2019 beträgt der Mittelwert für Kleinhüningen rund 75 200 Franken, der Median ca. 3 300 Franken. Die Werte für Klybeck liegen etwas tiefer - der Mittelwert bei 65 800 Franken, der Median bei ca. 2 400 Franken. Für die Stadt Basel liegt der Mittelwert bei 485 500 und der Median bei 17 300 Franken.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen (ordentliche Veranlagung); ohne Auswärtige und ohne Wochenaufenthalter. Einkünfte von Quellenbesteuerten unter 120 000 Franken im Kalenderjahr sind in der Regel in den Auswertungen nicht enthalten.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Mittelwert und Median des Reinvermögens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.08628",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "3.07",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:53",
		"id": 8628
	},
	{
		"template": "line001_print",
		"data-id": 8629,
		"chart-id": 8629,
		"filter": "",
		"parentId": "8059",
		"children": [],
		"title": "Steuerertrag durch Zu- und Wegzüger",
		"subtitle": "in Franken, Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "In den meisten Jahren ist der Saldo aus dem Steuerertrag der Zuzüger und dem Steuerertrag der Wegzüger (des Vorjahres) in den Wohnvierteln Klybeck und Kleinhüningen negativ. Im Jahr 2019 ergab sich für Klybeck rechnerisch ein Verlust von rund 139 000 Franken (bei 152 Weg- und 149 Zuzügern), in Kleinhüningen ein Verlust von ca. 121 000 Franken (bei 59 Weg- und 36 Zuzügern).",
		"erlaeuterungen": "Beim Steuerverfahren der ordentlichen Veranlagung ist für die kantonale Steuerpflicht der Wohnsitz am 31. Dezember massgebend. Es liegen daher im Wegzugskanton in der Regel keine Steuerdaten für das Jahr des Wegzugs vor. Deshalb ist für Wegziehende jeweils der Steuerertrag des Vorjahres abgebildet. Für die Zugezogenen und die ganzjährig Niedergelassenen werden die Steuerdaten des Berichtsjahres verwendet. <br>Aufgrund verschiedener methodischer Besonderheiten sind quellenbesteuerte Personen in dieser Auswertung zunächst nicht berücksichtig. Erst wenn sie nachträglich ordentlich veranlagt werden (zum Beispiel bei Einkünften von mehr als 120 000 Franken pro Jahr) oder die Niederlassungsbewilligung erhalten und deshalb ins ordentliche Verfahren wechseln, werden sie als Zuzug gezählt und in die Auswertung miteinbezogen – auch wenn sie schon länger im Kanton wohnhaft sind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Steuerertrag durch Zu- und Wegzüger",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.08629",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "3.08",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:54",
		"id": 8629
	},
	{
		"template": "template001_print",
		"data-id": 8630,
		"chart-id": 8630,
		"filter": "",
		"parentId": "8060",
		"children": [],
		"title": "Wohnungen nach Zimmerzahl",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "In den beiden Wohnvierteln Klybeck und Kleinhüningen kommen Dreizimmerwohnungen am häufigsten vor. In Kleinhüningen sind die Anteile der Wohnungen mit 3 oder mehr Zimmern grösser als im benachbarten Klybeck. In Klybeck sind dagegen die Anteile von Ein- und Zweizimmerwohnungen grösser.",
		"erlaeuterungen": "Als Zimmer gelten Räume, welche als bauliche Einheit die Wohnung bilden. Küchen, Badezimmer, Toilettenräume, Reduits, Gänge, Veranden usw. gelten nicht als Zimmer. Ebensowenig werden halbe Zimmer gezählt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnungen nach Zimmerzahl",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.08630",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "4.03",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-22T08:09:04",
		"id": 8630
	},
	{
		"template": "template001_print",
		"data-id": 8631,
		"chart-id": 8631,
		"filter": "",
		"parentId": "8061",
		"children": [],
		"title": "Wohnungen nach Belegungsart",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Der Mietwohnungsanteil überwiegt in beiden Wohnvierteln (2022: Klybeck 83,4%, Kleinhüningen 71,7%). Der Anteil an Genossenschaftswohnungen betrug 2022 13,6% (Klybeck) und 22,4% (Kleinhüningen), was über dem Wert für die Stadt Basel (10,6%) lag. In beiden Wohnvierteln gibt es nur wenige selbstbewohnte Eigentümerwohnungen.",
		"erlaeuterungen": "Die Daten beziehen sich auf die belegten Wohnungen, Mansarden oder Einzelzimmer (Haushalte). Sonstige Wohnungen umfassen Notwohnungen der Sozialhilfe, subventionierte Wohnungen gemeinnütziger Institutionen, Dienst- und Abwartswohnungen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnungen nach Belegungsart",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.08631",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "4.04",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-22T08:09:05",
		"id": 8631
	},
	{
		"template": "line001_print",
		"data-id": 8632,
		"chart-id": 8632,
		"filter": "",
		"parentId": "8062",
		"children": [],
		"title": "Wohnfläche pro Person",
		"subtitle": "in m<sup>2</sup>, Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "In den Wohnvierteln Klybeck und Kleinhüningen ist die beanspruchte Wohnfläche pro Person deutlich geringer als im städtischen Durchschnitt.",
		"erlaeuterungen": "Die durchschnittliche Wohnfläche pro Bewohner berechnet sich aus der Gesamtfläche der bewohnten Wohnungen, dividiert durch die Summe der zugeordneten Bewohner. Als Wohnungsfläche gelten sämtliche bewohnbaren Flächen einer Wohnung, also die Summe der Flächen sämtlicher Zimmer, Küchen, Kochnischen, Badezimmer, Toilettenräume, Abstellräume, Gänge, Veranden etc. einer Wohnung (ohne Terrassen oder offene Balkone). Für die Berechnung werden sämtliche einer Wohnung zugeordneten Bewohner berücksichtigt, unabhängig von ihrem Meldeverhältnis (Niedergelassene und Aufenthalter). Personen mit mehreren Wohnsitzen werden entsprechend mehrmals gezählt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnfläche pro Person",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.08632",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "4.02",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-22T08:09:04",
		"id": 8632
	},
	{
		"template": "line001_print",
		"data-id": 8633,
		"chart-id": 8633,
		"filter": "",
		"parentId": "8063",
		"children": [],
		"title": "Leerwohnungsquote",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "In der Dekade von 2000 bis 2009 bewegte sich die Leerwohnungsquote der beiden Wohnviertel stets über der 1%-Marke. Seit 2010 liegt sie dagegen fast immer darunter.",
		"erlaeuterungen": "Stichtag ist der 1. Juni. Nur Wohnungen, die für den eigentlichen Wohnungsmarkt in Betracht kommen; also ohne leere Wohnungen, die für den Abbruch oder Umbau bestimmt sind. Die Prozentangaben beziehen sich auf den Leerwohnungsbestand am Gesamtwohnungsbestand.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Leerwohnungsquote",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.08633",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "4.05",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:05",
		"id": 8633
	},
	{
		"title": "Nettomietpreise nach Wohnviertel",
		"subtitle": "in Fr. pro m<sup>2</sup>, Basel-Stadt, 2015-2017",
		"kuerzel": "I.09.3.08634",
		"kuerzelKunde": "4.06",
		"description": "Nettomietpreise nach Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Mietpreise",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:26.2626",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die Nettomiete pro m<sup>2</sup> von 3- und 4-Zimmer-Wohnungen liegt in den Wohnvierteln Klybeck und Kleinhüningen unter 16 Franken. Im Durchschnitt liegt die Nettomiete pro m<sup>2</sup> in der Stadt Basel bei ungefähr 17 Franken.",
		"erlaeuterungen": "Der m<sup>2</sup>-Preis bezieht sich auf die Nettomiete, dividiert durch die Wohnfläche von 3- oder 4-Zimmer-Wohnungen. Die Daten stammen aus der Strukturerhebung. Die Strukturerhebung ist eine Stichprobenerhebung, weshalb die Schätzungen mit einer gewissen Ungenauigkeit verbunden sind. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2015 bis 2017 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese drei Jahre interpretiert werden.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "04_00_00_00_00_006",
		"parentId": 8064,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8634,
		"chart-id": 8634,
		"filter": "",
		"id": 8634
	},
	{
		"template": "line001_print",
		"data-id": 8635,
		"chart-id": 8635,
		"filter": "",
		"parentId": "8065",
		"children": [],
		"title": "Anteil Einfamilienhäuser",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Der Einfamilienhausanteil liegt unter dem städtischen Durchschnitt. Im Wohnviertel Klybeck ist er besonders gering.",
		"erlaeuterungen": "Anteil der Einfamilienhäuser an allen bewohnbaren Gebäuden des Wohnviertels oder Bezirkes in Prozent. Die Werte von 2011 und 2012 beruhen auf der jährlichen Fortschreibung der Volkszählung 2000. Ab 2013 stammen die Daten aus dem kantonalen Gebäude- und Wohnungsregister GWR.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anteil Einfamilienhäuser",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.08635",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "4.07",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-22T08:09:06",
		"id": 8635
	},
	{
		"template": "template001_print",
		"data-id": 8636,
		"chart-id": 8636,
		"filter": "",
		"parentId": "8066",
		"children": [],
		"title": "Umgebaute Wohnungen",
		"subtitle": "nach Art des Umbaus, Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "2022 enstanden 157 zusätzliche Wohnungen durch die Umnutzung eines Hotels und von Schulungsräumen. 2019 enstanden 80 zusätzliche Wohnungen durch die Umnutzung eines Bürogebäudes. In den anderen Jahren hat sich der Wohnungsbestand durch Umbauten relativ wenig verändert.",
		"erlaeuterungen": "Die prozentualen Anteile im Tooltip beziehen sich auf das Total der Zugänge resp. das Total der Abgänge.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Baustatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Umgebaute Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.08636",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "4.08",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-22T08:09:07",
		"id": 8636
	},
	{
		"template": "template001_print",
		"data-id": 8637,
		"chart-id": 8637,
		"filter": "",
		"parentId": "8067",
		"children": [],
		"title": "Nettowohnungsproduktion",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Die Nettowohnungsproduktion wurde 2005, 2011 und 2020 massgeblich von grossen Neubauprojekten beeinflusst. 2019 enstand aus einem Büro- und 2022 aus einem Hotelgebäude ein Wohngebäude mit 80 und 157 Wohnungen.",
		"erlaeuterungen": "Die Nettowohnungsproduktion setzt sich wie folgt zusammen: Neu gebaute Wohnungen minus abgebrochene Wohnungen plus Saldo aus Umbauten (kann positiv oder negativ sein).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Baustatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Nettowohnungsproduktion",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.08637",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "0",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-22T08:09:03",
		"id": 8637
	},
	{
		"template": "template001_print",
		"data-id": 8638,
		"chart-id": 8638,
		"filter": "",
		"parentId": "8068",
		"children": [],
		"title": "Genossenschaftswohnungen",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Der Anteil der Genossenschaftswohnungen ist im Wohnviertel Kleinhüningen signifikant höher als im Wohnviertel Klybeck.",
		"erlaeuterungen": "Es werden nur Wohnungen berücksichtigt, welche am Stichtag (31.12.) durch mindestens eine Person belegt waren.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Genossenschaftswohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.08638",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "4.10",
		"stufe1": "4 Bauen und Wohnen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-22T08:09:07",
		"id": 8638
	},
	{
		"title": "Anteil an der Gesamtbeschäftigung der Stadt Basel",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"kuerzel": "I.03.2.07688",
		"kuerzelKunde": "3.01",
		"description": "Anteil an der Gesamtbeschäftigung der Stadt Basel",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:26.2626",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Jahr 2017 sind in der Stadt Basel 185 605 Beschäftigte tätig. Davon arbeiten 3 913 im Wohnviertel Klybeck und 7 458 im Wohnviertel Kleinhüningen. Anteilsmässig sind dies 2,1% bzw. 4,0%. Insgesamt entfallen somit 6,1% der Beschäftigung der Stadt Basel auf den Stadtteil Klybeck-Kleinhüningen.",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben, und die einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Referenzperiode ist jeweils der Dezember des Jahres.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "03_00_00_00_00_001",
		"parentId": 8069,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8639,
		"chart-id": 8639,
		"filter": "",
		"id": 8639
	},
	{
		"template": "line001_print",
		"data-id": 8640,
		"chart-id": 8640,
		"filter": "",
		"parentId": "8070",
		"children": [],
		"title": "Beschäftigung nach ausgewählten Branchen",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Am beschäftigungsstärksten ist im Stadtteil Klybeck-Kleinhüningen die Branche Sonstige wirtschaftliche Dienstleistungen mit 2 052 Beschäftigten im Jahr 2020. Davon entfallen 1 857 Beschäftigte auf den Wirtschaftszweig «Gebäudebetreuung; Garten- und Landschaftsbau». Es folgen die Branchen Schifffahrt und Luftfahrt (1 012), Landverkehr (595) sowie Architektur- und Ingenieurbüros (544).",
		"erlaeuterungen": "Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben, und die einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten. Die Referenzperiode ist jeweils der Dezember des Jahres. Bei Unternehmen mit mehreren Arbeitsstätten werden die Beschäftigten gemäss Angaben der Unternehmen auf die verschiedenen Arbeitsstätten verteilt. Dabei ist nicht auszuschliessen, dass es sich teilweise um rein administrative Zuordnungen handeln kann, und nicht alle Beschäftigten effektiv an dieser Arbeitsstätte (oder Adresse) tätig sind.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Beschäftigung nach ausgewählten Branchen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08640",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "3.03",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-15T08:14:05",
		"id": 8640
	},
	{
		"template": "template001_print",
		"data-id": 8641,
		"chart-id": 8641,
		"filter": "",
		"parentId": "8071",
		"children": [],
		"title": "Anzahl Rotlichtsalons",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Im Wohnviertel Klybeck gab es 2022 einen Rotlichtsalon, im Wohnviertel Kleinhüningen wurden keine Salons verzeichnet. Insgesamt waren im Jahr 2022 in der Stadt Basel 119 Rotlichtsalons registriert.",
		"erlaeuterungen": "Für die Jahre 2008 und 2012 liegen keine Daten vor.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anzahl Rotlichtsalons",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.08641",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "3.09",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-15T08:14:06",
		"id": 8641
	},
	{
		"title": "Nettoerwerbstätigenquote",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"kuerzel": "I.03.1.08642",
		"kuerzelKunde": "3.04",
		"description": "Nettoerwerbstätigenquote",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:27.2727",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Wohnviertel Klybeck lag die Nettoerwerbstätigenquote im Mittel der Jahre 2013 bis 2017 bei 61,7%, im Wohnviertel Kleinhüningen bei 65,3%. Zum Vergleich: Die Quote für die Stadt Basel betrug 73,4%.",
		"erlaeuterungen": "Die Nettoerwerbstätigenquote ist definiert als die Anzahl der Erwerbstätigen, geteilt durch die Wohnbevölkerung im Alter von 15 bis 64 Jahren. Bis 2000 stammen die Daten zu den Erwerbspersonen aus der Eidgenössischen Volkszählung (Vollerhebung), seit 2010 aus der Strukturerhebung. Die Strukturerhebung ist eine Stichprobenerhebung, weshalb die Schätzungen mit einer gewissen Ungenauigkeit verbunden sind. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2013 bis 2017 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "03_00_00_00_00_004",
		"parentId": 8072,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)",
			"Bundesamt für Statistik (BFS), Volkszählung (VZ)"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8642,
		"chart-id": 8642,
		"filter": "",
		"id": 8642
	},
	{
		"template": "line001_print",
		"data-id": 8643,
		"chart-id": 8643,
		"filter": "",
		"parentId": "8073",
		"children": [],
		"title": "Bruttogeschossfläche Wohnen und Arbeiten",
		"subtitle": "in m<sup>2</sup>, Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Während die Bruttogeschossfläche für Wohnen in Klybeck seit 1995 stabil blieb, hat sie für Arbeiten insbesondere seit 2015 deutlich abgenommen. In Kleinhüningen hat sie für Wohnen zwischen 1995 und 2015 zugenommen und ging bis 2020 wieder etwas zurück, für Arbeiten war sie zwischen 1995 und 2015 leicht rückläufig, ehe sie bis 2020 deutlich zu zunahm.",
		"erlaeuterungen": "Die Daten zur Bruttogeschossfläche (BGF) wurden bis 2020 fünfjährlich aktualisiert. Die Erhebungsmethodik wurde im Rahmen der Berechnung der Daten für das Jahr 2020 überarbeitet. Die Daten sind damit nicht direkt vergleichbar mit den Vorjahren. Ab 2020 werden die Daten jährlich aktualisiert. Die Bruttogeschossfläche ist die Summe der Grundflächen der ober- und unterirdischen Geschosse von Gebäuden, welche zum Wohnen oder Arbeiten genutzt werden können. Für das Jahr 2000 stehen keine Daten zur Verfügung.",
		"quellenangabe": [
			"Bau- und Verkehrsdepartement Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Bruttogeschossfläche Wohnen und Arbeiten",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.08643",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "3.02",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:50",
		"id": 8643
	},
	{
		"template": "line001_print",
		"data-id": 8644,
		"chart-id": 8644,
		"filter": "",
		"parentId": "8074",
		"children": [],
		"title": "Nettoerwerbsquote der Frauen",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Im Wohnviertel Klybeck lag die Nettoerwerbsquote der Frauen im Mittel der Jahre 2015 bis 2019 bei 70,4%, im Wohnviertel Kleinhüningen bei 62,1%. Zum Vergleich: Die Quote für die Stadt Basel betrug 75,4%.",
		"erlaeuterungen": "Die Nettoerwerbsquote ist definiert als die Summe der Erwerbspersonen (Erwerbstätige plus Erwerbslose), geteilt durch die Wohnbevölkerung im Alter von 15 bis 64 Jahren. Bis 2000 stammen die Daten zu den Erwerbspersonen aus der Eidgenössischen Volkszählung (Vollerhebung), seit 2010 aus der Strukturerhebung. Die Strukturerhebung ist eine Stichprobenerhebung, weshalb die Schätzungen mit einer gewissen Ungenauigkeit verbunden sind. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2015 bis 2019 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese 5 Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Folglich gibt es innerhalb des Poolingzeitraums 2015-2019 einen methodischen Bruch.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)",
			"Bundesamt für Statistik (BFS), Volkszählung (VZ)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Nettoerwerbsquote der Frauen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.08644",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "3.05",
		"stufe1": "3 Erwerbsleben und Steuern",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:51",
		"id": 8644
	},
	{
		"template": "line001_print",
		"data-id": 8645,
		"chart-id": 8645,
		"filter": "",
		"parentId": "8075",
		"children": [],
		"title": "Sozialhilfebezüger und -quote",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "2021 beträgt die Sozialhilfequote im Klybeck 12,8% und in Kleinhüningen 11,7%. Beide Wohnviertel liegen damit über der Sozialhilfequote der Stadt Basel (6,3%).",
		"erlaeuterungen": "Sozialhilfequote: Anteil der im Jahresverlauf unterstützten Sozialhilfeempfänger am Endjahresbestand der Bevölkerung der entsprechenden Raumeinheit. Es sind alle sozialhilfebeziehenden Personen berücksichtigt, die im Verlaufe eines Jahres mindestens eine bedarfsabhängige Sozialhilfeleistung erhalten haben. Die Dossiertypen Asyl und Flüchtling sind ebenfalls berücksichtigt. Asylsuchende mit Nichteintretens- oder Negativentscheid (NEE-NE-Dossiers) werden aus den Auswertungen ausgeschlossen, weil diese Personen nicht Sozialhilfe, sondern Nothilfe erhalten.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Sozialhilfebezüger und -quote",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe und Notwohnen",
		"kuerzel": "I.13.3.08645",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "5.04",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:10",
		"id": 8645
	},
	{
		"title": "Gymnasialquote",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"kuerzel": "I.15.1.08646",
		"kuerzelKunde": "5.02",
		"description": "Gymnasialquote",
		"thema": "15 Bildung",
		"unterthema": "Schulen und Schulpersonal",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:27.2727",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die Gymnasialquoten der Wohnviertel Klybeck und Kleinhüningen sind nach vorübergehendem Anstieg seit zwei Jahren leicht (Klybeck) respektive stark (Kleinhüningen; aufgrund tiefer Gesamtschülerzahl reagiert die Quote heftiger) rückläufig. Dieser Rückgang lässt sich im ganzen Kanton beobachten und ist auf ein Massnahmenpaket seitens Erziehungsdepartement zur Stabilisierung der Übertrittsquoten von der Sekundarschule ins Gymnasium zurückzuführen. Für die Stadt Basel beträgt der Wert 2019 38,5%.",
		"erlaeuterungen": "Gymnasialquote: Anteil der Gymnasiastinnen und Gymnasiasten an allen Schülerinnen und Schülern (SuS) der 10. und 11. Schulstufe (einschliesslich zweier obligatorischer Kindergartenstufen) an öffentlichen Schulen und mit Elternwohnort Basel-Stadt. Bis zum Schuljahr 2015/16 wurden Weiterbildungsschule WBS und Gymnasium gegenübergestellt. Aufgrund von HarmoS (Ablösung WBS durch Sekundarschule Sek, Verkürzung Gymnasium) war dies 2016/17 nur auf Stufe 11 möglich (auf Stufe 10 Vergleich mit Sek P), 2017/18 dann gar nicht mehr. Als Hilfsquote wird daher für die gleichen beiden Stufen der Anteil Sek P-SuS an allen Sek-SuS herangezogen.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "05_00_00_00_00_002",
		"parentId": 8076,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bildungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8646,
		"chart-id": 8646,
		"filter": "",
		"id": 8646
	},
	{
		"template": "line001_print",
		"data-id": 8647,
		"chart-id": 8647,
		"filter": "",
		"parentId": "8077",
		"children": [],
		"title": "Anteil deutschsprachiger Kinder in Kindergarten und Primarschule",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Die Quote der Schülerinnen und Schüler mit Erstsprache Deutsch ist 2022 in den Wohnvierteln Klybeck (19,4%) und Kleinhüningen (19,1%) weiterhin tief. Im Beobachtungszeitraum ist in beiden Wohnvierteln kein eindeutiger Trend feststellbar. Für die gesamte Stadt Basel beträgt der Vergleichswert 46,6%.",
		"erlaeuterungen": "Der Indikator zeigt den Anteil der Schülerinnen und Schüler mit Erstsprache Deutsch an allen Schülerinnen und Schülern der öffentlichen Kindergärten und Primarschulen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bildungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anteil deutschsprachiger Kinder in Kindergarten und Primarschule",
		"thema": "15 Bildung",
		"unterthema": "Schulen und Schulpersonal",
		"kuerzel": "I.15.1.08647",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "5.01",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-15T08:14:07",
		"id": 8647
	},
	{
		"template": "line001_print",
		"data-id": 8648,
		"chart-id": 8648,
		"filter": "",
		"parentId": "8078",
		"children": [],
		"title": "Anteil der Bevölkerung mit tertiärem Bildungsabschluss",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2016-2020",
		"lesehilfe": "Die Wohnviertel Klybeck und Kleinhüningen haben verglichen mit den anderen städtischen Wohnvierteln den tiefsten Anteil von Personen mit tertiärem Bildungsabschluss. Im Mittel des Zeitraums von 2016 bis 2020 lag der Anteil im Wohnviertel Klybeck bei knapp 23%, im Wohnviertel Kleinhüningen bei rund 15%. In der Stadt Basel liegt der Anteil bei 42%.",
		"erlaeuterungen": "Anteil der Personen mit höchstem Bildungsabschluss «Tertiärstufe» an der über 14-jährigen Wohnbevölkerung. Die Tertiärstufe umfasst die höhere Berufsbildung, z. B. eine höhere Fachschule für Technik oder Wirtschaft, sowie Ausbildungen an Hochschulen wie z. B. ein Bachelor- oder Masterstudium. Die Daten stammen aus der Strukturerhebung. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe und sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2016 bis 2020 zusammen ausgewertet (Pooling). Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Weiter wurde die Frage zur höchsten abgeschlossenen Ausbildung im Fragebogen der Strukturerhebung 2020 verändert. Somit liegen zwei methodische Brüche innerhalb des Poolingzeitraums vor.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anteil der Bevölkerung mit tertiärem Bildungsabschluss",
		"thema": "15 Bildung",
		"unterthema": "Bildungsniveau",
		"kuerzel": "I.15.6.08648",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "5.03",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:09",
		"id": 8648
	},
	{
		"template": "line001_print",
		"data-id": 8649,
		"chart-id": 8649,
		"filter": "",
		"parentId": "8079",
		"children": [],
		"title": "Anteil Haushalte mit Familienmietzinsbeiträgen resp. reinen Prämienverbilligungen",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "28,7% der Haushalte des Klybeck und 27,0% der Haushalte im Wohnviertel Kleinhüningen beziehen Ende 2021 reine Prämienverbilligungen (PV) und 4,2% resp. 4,5% Familienmietzinsbeiträge. Die PV-Quote des Kantons Basel-Stadt liegt bei 17,0%, die FAMI-Quote bei 2,3%.",
		"erlaeuterungen": "Anteil Haushalte mit Prämienverbilligungen: Es werden alle Haushalte mit mindestens einer Person mit reinen Prämienverbilligungen gezählt (ohne Bezügerinnen und Bezüger von Ergänzungsleistungen und Sozialhilfe).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Basler Informationssystem Sozialleistungen (BISS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anteil Haushalte mit Familienmietzinsbeiträgen resp. reinen Prämienverbilligungen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.08649",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "5.05",
		"stufe1": "5 Bildung und Soziales",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:12",
		"id": 8649
	},
	{
		"template": "template001_print",
		"data-id": 8650,
		"chart-id": 8650,
		"filter": "",
		"parentId": "8080",
		"children": [],
		"title": "Bodenbedeckung nach Nutzungsart",
		"subtitle": "Anteil an der Gesamtfläche, Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Im Wohnviertel Kleinhüningen waren 2021 16,6% (22,44 ha) des Bodens mit Gebäuden bedeckt, im Wohnviertel Klybeck 27,1% (24,98 ha). Seit 2013 weist Kleinhüningen einen grösseren Anteil an Grünflächen auf als Klybeck (2021: 22,5% zu 12,4%).",
		"erlaeuterungen": "Grünfläche: alle privaten und öffentlichen bestockten (Wald, Übrige) oder humusierten Flächen (Acker, Wiese, Friedhof, Gartenanlage, Gewässervorland, Park, Reben, Schrebergarten, Sportanlage, Tierpark, Übrige). Gewässer: stehende und fliessende Gewässer. Verkehrsfläche: Befestigte Flächen wie Strassen, Wege, Trottoirs (inkl. Rabatten) und Verkehrsinseln sowie Bahn- und Tramareale. Übrige befestigte Flächen: Hafen- und Fabrikareale; Tankanlagen; Wasserbecken und befestigtes Gewässervorland; befestigte Sportanlagen; alle weiteren befestigten Flächen. Als befestigt gelten künstlich hergerichtete Flächen, insbesondere asphaltierte, betonierte, bekieste, gemergelte oder mit Steinen oder Platten belegte Flächen. <br>Die Angaben basieren auf der Datenebene «Bodenbedeckung» der amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100 m<sup>2</sup> geführt werden. Diese werden bei Bedarf oder spätestens in einem Turnus von 6-12 Jahren mit einer periodischen Nachführung aktualisiert. Befestigte Objekte wie Gebäude, Strassenräume oder öffentliche Pärke werden detaillierter erfasst und bei baulichen Änderungen nachgeführt.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [
			"Die Daten der Bodenbedeckung im <a href = 'https://map.geo.bs.ch/s/0JGP' target = '_blank'>kantonalen Geoportal</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Bodenbedeckung nach Nutzungsart",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.08650",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "7.01",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:17",
		"id": 8650
	},
	{
		"title": "Grünflächen nach Kategorie",
		"subtitle": "in m<sup>2</sup>, Wohnviertel Klybeck und Kleinhüningen",
		"kuerzel": "I.02.1.08651",
		"kuerzelKunde": "7.02",
		"description": "Grünflächen nach Kategorie",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:25.2525",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Wohnviertel Kleinhüningen entfiel im Jahr 2019 ein Grossteil (rund 230 500 m<sup>2</sup>) der Grünflächen auf die Bodenbedeckungsart «Übrige humusierte» und nur 4 885 m<sup>2</sup> auf die Kategorie «Gartenanlage». Das Klybeck weist in der Summe weniger Grünflächen auf, dafür mehr in den Kategorien «Gartenanlage» (74 000 m<sup>2</sup>) und «Parkanlage/Spielplatz» (23 400 m<sup>2</sup>).",
		"erlaeuterungen": "Als Grünfläche gelten alle privaten und öffentlichen bestockten (Wald, Übrige) oder humusierten (Acker, Wiese, Friedhof, Gartenanlage, Gewässervorland, Park, Reben, Schrebergarten, Sportanlage, Tierpark, Übrige) Flächen. Die Angaben basieren auf der Datenebene «Bodenbedeckung» der amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100 m<sup>2</sup> geführt werden (öffentliche Parkanlagen und Rabatten im Strassenbereich werden detaillierter erfasst). Diese werden bei Bedarf oder spätestens in einem Turnus von 6 bis 12 Jahren mit einer periodischen Nachführung aktualisiert.",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "07_00_00_00_00_002",
		"parentId": 8081,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			"Die Daten der Bodenbedeckung im <a href = 'https://map.geo.bs.ch/s/5jZH' target = '_blank'>kantonalen Geoportal</a>"
		],
		"data-id": 8651,
		"chart-id": 8651,
		"filter": "",
		"id": 8651
	},
	{
		"title": "Anzahl Tropennächte",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2018",
		"kuerzel": "I.02.12.08652",
		"kuerzelKunde": "7.04",
		"description": "Anzahl Tropennächte",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Klima",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:25.2525",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "In den Wohnvierteln Klybeck und Kleinhüningen traten 2018 12 resp. 11 Tropennächte auf (gemittelt über das gesamte Wohnviertel).",
		"erlaeuterungen": "Tropennächte sind Nächte, in denen die Temperatur nicht unter 20 °C sinkt. Heissere Flächen sind in der Regel stark bebaute, versiegelte und vegetationsarme Gebiete (z. B.Innenstädte, Industrie- und Bahnareale). Kühlere Flächen finden sich dort, wo genügend Vegetation (z. B. Parks) oder grössere Gewässer (Rhein) vorhanden sind oder wo Kaltluftzufuhr, z. B. aus umliegenden kühleren Gebieten, erfolgen kann. Die Daten basieren auf Modellrechnungen (200 x 200 m-Raster, räumlich gemittelt über das jeweilige Wohnviertel) der Universität Basel für das Jahr 2018 und berücksichtigen neben Temperaturmessungen (an zehn Standorten) auch Topografie, Gebäude, Bäume und die Oberflächenbeschaffenheit des Bodens.",
		"template": "map002_print",
		"darstellungsart": "Karte",
		"printformat": "",
		"orderKey": "07_00_00_00_00_004",
		"parentId": 8082,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"MCR-Lab, Universität Basel"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8652,
		"chart-id": 8652,
		"filter": "",
		"id": 8652
	},
	{
		"title": "Heizsysteme nach Energieträger",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"kuerzel": "I.08.1.08654",
		"kuerzelKunde": "7.07",
		"description": "Heizsysteme nach Energieträger",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:27.2727",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Während der Anteil fernwärmebeheizter Gebäude in Klybeck seit 2010 leicht zugenommen hat, ist der Anteil mit Heizöl versorgter Bauten zurückgegangen. In Kleinhüningen ist ein leichter Anstieg beim Erdgas zu verzeichnen, während der Anteil Heizöl auch hier seit 2010 rückläufig ist.",
		"erlaeuterungen": "Die Anzahl Heizsysteme nach Energieträger stammt aus der kantonalen Gebäude- und Wohnungsstatistik, welche jährlich per 31. Dezember aus dem kantonalen Gebäude- und Wohnungsregister (GWR) erzeugt wird.",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "07_00_00_00_00_007",
		"parentId": 8085,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8654,
		"chart-id": 8654,
		"filter": "",
		"id": 8654
	},
	{
		"template": "line001_print",
		"data-id": 8655,
		"chart-id": 8655,
		"filter": "",
		"parentId": "8086",
		"children": [],
		"title": "Stromverbrauch",
		"subtitle": "in Gigawattstunden (GWh), Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Das Total des Stromverbrauches pro Wohnviertel ist sowohl für Klybeck als auch für Kleinhüningen seit 2012 rückläufig.",
		"erlaeuterungen": "Die Daten stammen aus der kantonalen Energiestatistik, welche seit dem Jahr 2012 im Zweijahresrhythmus erscheint. Ausgewiesen werden hier ausschliesslich Endverbräuche in Gigawattstunden (GWh).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Energiestatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Stromverbrauch",
		"thema": "08 Energie",
		"unterthema": "Verbrauch",
		"kuerzel": "I.08.1.08655",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "7.06",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "07_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:19",
		"id": 8655
	},
	{
		"title": "Personenwagen pro Haushalt, Motorisierungsgrad",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"kuerzel": "I.11.1.08656",
		"kuerzelKunde": "7.08",
		"description": "Personenwagen pro Haushalt, Motorisierungsgrad",
		"thema": "11 Verkehr",
		"unterthema": "Motorfahrzeuge",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:27.2727",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "2017 waren im Wohnviertel Klybeck im Schnitt 0,46 Personenwagen pro Haushalt registriert, der Motorisierungsgrad lag bei 219,8 privaten Personenwagen pro 1 000 Einwohnern. Im Wohnviertel Kleinhüningen waren die entsprechenden Werte 0,57 und 256,3, in der Stadt Basel 0,46 und 232,2.",
		"erlaeuterungen": "Anzahl der auf Privatpersonen zugelassenen Personenwagen geteilt durch die Anzahl Haushalte sowie pro 1 000 Einwohner (Motorisierungsgrad). Zur Berechnung wird jeweils der Jahresendbestand der Personenwagen und Einwohner (exkl. Personen an administrativen Meldeadressen) verwendet.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "07_00_00_00_00_008",
		"parentId": 8087,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Kantonspolizei Basel-Stadt, Motorfahrzeugkontrolle"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8656,
		"chart-id": 8656,
		"filter": "",
		"id": 8656
	},
	{
		"title": "Feinstaubbelastung",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2015",
		"kuerzel": "I.02.15.08657",
		"kuerzelKunde": "7.09",
		"description": "Feinstaubbelastung",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Luft",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:25.2525",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Wohnviertel Kleinhüningen waren 2015 im Jahresmittel mit 456 Personen 15,7% der dortigen Wohnbevölkerung an ihrem Wohnort Feinstaub-Immissionen von über 20&nbsp;µg/m<sup>3</sup> ausgesetzt. Im Wohnviertel Klybeck lag die Belastung für alle Einwohner unter dem Grenzwert.",
		"erlaeuterungen": "Anzahl und Anteil Personen, an deren Wohnort im Jahresmittel Feinstaub-Belastungen (PM10) von über 20&nbsp;µg/m<sup>3</sup> (Jahresgrenzwert gemäss Luftreinhalteverordnung) auftreten. Berechnet basierend auf Daten des Lufthygieneamtes beider Basel (Immissionskarten 10x10 m für 2015). Unter PM10 versteht man Partikel, die kleiner sind als 10 Mikrometer. Dieser Staub ist ein physikalisch-chemisch komplexes Gemisch. Er entsteht bei industriellen und gewerblichen Produktionsprozessen, Verbrennungsprozessen, mechanischen Prozessen (Abrieb, Aufwirbelung) sowie durch sekundäre Bildung (aus SO<sub>2</sub>, NO<sub>x</sub>, NH<sub>3</sub>, VOC). PM10 ist in seiner Zusammensetzung sehr vielfältig und kann Russ, Schwermetalle, Sulfat, Nitrat, Ammonium, organischen Kohlenstoff, polyzyklische aromatische Kohlenwasserstoffe oder Dioxine/Furane enthalten. Feinstaub führt zu Erkrankungen der Atemwege, des Herz-Kreislaufsystems, zu einer Zunahme des Krebsrisikos und der Sterberate.",
		"template": "mappie001_print",
		"darstellungsart": "Karte",
		"printformat": "",
		"orderKey": "07_00_00_00_00_009",
		"parentId": 8088,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Lufthygieneamt beider Basel"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			"Karte der <a href = 'https://map.geo.bs.ch/s/nojy' target = '_blank'>Feinstaub-Imissionen (PM10) 2015</a> im kantonalen Geoportal",
			"Weitere Informationen zu <a href = 'http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-11-1109' target = '_blank'>Feinstaub-Immissionen</a> in der Region Basel",
			"Nationale <a href = 'https://www.admin.ch/opc/de/classified-compilation/19850321/index.html#app7ahref0' target = '_blank'>Luftreinhalte-Verordnung (LRV), Anhang 7</a>"
		],
		"data-id": 7707,
		"chart-id": 8657,
		"filter": "",
		"id": 8657
	},
	{
		"title": "Stickoxidbelastung",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2015",
		"kuerzel": "I.02.15.08658",
		"kuerzelKunde": "7.10",
		"description": "Stickoxidbelastung",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Luft",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:50.5050",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Wohnviertel Kleinhüningen waren 2015 im Jahresmittel mit 1 490 Personen 51,4% der dortigen Wohnbevölkerung an ihrem Wohnort Stickoxid-Immissionen von über 30 µg/m<sup>3</sup> ausgesetzt. Im Wohnviertel Klybeck waren es 590 Personen (8,1%).",
		"erlaeuterungen": "Anzahl und Anteil Personen, an deren Wohnort im Jahresmittel Stickstoffdioxid-Belastungen (NO<sub>2</sub>) von über 30 µg/m<sup>3</sup> (Jahresgrenzwert gemäss Luftreinhalteverordnung) auftreten. Berechnet basierend auf Daten des Lufthygieneamtes beider Basel (Immissionen modelliert auf Basis eines 10 x 10 m-Rasters). Stickoxide (NO<sub>x</sub>) entstehen beim Verbrennen von Brenn- und Treibstoffen, insbesondere bei hohen Verbrennungstemperaturen. Hauptquelle ist der Strassenverkehr. Stickoxide sind wichtige Vorläufersubstanzen für die Bildung von sauren Niederschlägen, sekundärem Feinstaub und – zusammen mit flüchtigen organischen Verbindungen – von Ozon/Sommersmog. Stickstoffdioxid (NO<sub>2</sub>) und andere Reizgase begünstigen Erkrankungen der Atemwege.",
		"template": "mappie001_print",
		"darstellungsart": "Karte",
		"printformat": "",
		"orderKey": "07_00_00_00_00_010",
		"parentId": 8089,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Lufthygieneamt beider Basel"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			"Karte der <a href = 'https://map.geo.bs.ch/s/5WPK' target = '_blank'>Stickstoffdioxid-Immissionsbelastung 2015</a> im kantonalen Geoportal.",
			"Weitere Informationen zu <a href = 'http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-11-1111' target = '_blank'>Stickstoffdioxid-Immissionen</a>in der Region Basel",
			"Nationale <a href = 'https://www.admin.ch/opc/de/classified-compilation/19850321/index.html#app7ahref0' target = '_blank'>Luftreinhalte-Verordnung (LRV), Anhang 7</a>"
		],
		"data-id": 8658,
		"chart-id": 8658,
		"filter": "",
		"id": 8658
	},
	{
		"title": "Freiraumfläche",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"kuerzel": "I.02.1.07709",
		"kuerzelKunde": "7.03",
		"description": "Freiraumfläche",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"aktualisierungsdatum": "2020-02-19T19:40:25.2525",
		"stufe1": "7 Raum und Umwelt",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im Wohnviertel Kleinhüningen waren 2019 0,4% der Gesamtfläche Freiraumflächen, im Wohnviertel Klybeck deren 2,5% (Stadt Basel: 2,8%).",
		"erlaeuterungen": "Zu den Freiraumflächen zählen Parkanlagen, Spielplätze und Rasenflächen von Sportanlagen. Die Angaben basieren auf der Datenebene «Bodenbedeckung» der Amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100&nbsp;m<sup>2</sup> geführt werden (Öffentliche Pärke und Rabatten im Strassenbereich werden detaillierter erfasst). Diese werden bei Bedarf oder spätestens in einem Turnus von 6 bis 12 Jahren mit einer periodischen Nachführung aktualisiert.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "07_00_00_00_00_003",
		"parentId": 8090,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8659,
		"chart-id": 8659,
		"filter": "",
		"id": 8659
	},
	{
		"template": "line001_print",
		"data-id": 8661,
		"chart-id": 8661,
		"filter": "",
		"parentId": "8092",
		"children": [],
		"title": "Delikte",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Im Wohnviertel Klybeck schwankte die Zahl der Delikte in den Jahren 2009 bis 2020 zwischen 40 (2018) und 64 (2010). In Kleinhüningen bewegte sich die Zahl der Delikte im untersuchten Zeitraum zwischen 14 (2019) und 43 (2018). In der Stadt Basel war die Zahl der Delikte im Jahr 2020 (1 157) am niedrigsten und im Jahr 2012 (2 069) am höchsten.",
		"erlaeuterungen": "Berücksichtigt sind folgende Deliktkategorien: Entreissdiebstahl, Raub, Einbruch- und Einschleichdiebstähle, Nötigung sowie Sexualdelikte (Vergewaltigung, sexuelle Nötigung).",
		"quellenangabe": [
			"Kantonspolizei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Delikte",
		"thema": "19 Kriminalität und Strafrecht",
		"unterthema": "Polizei",
		"kuerzel": "I.19.1.08661",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "6.01",
		"stufe1": "6 Sicherheit",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "06_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:14",
		"id": 8661
	},
	{
		"template": "line001_print",
		"data-id": 8662,
		"chart-id": 8662,
		"filter": "",
		"parentId": "8093",
		"children": [],
		"title": "Einbruch- und Einschleichdiebstähle",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Im Wohnviertel Klybeck gab es im Jahr 2021 insgesamt 58 Einbruch- oder Einschleichdiebstähle, in Kleinhüningen 35. In der Stadt Basel wurden insgesamt 1 743 Einbruch- oder Einschleichdiebstähle gemeldet.",
		"erlaeuterungen": "Anzahl Einbruch- und Einschleichdiebstähle.",
		"quellenangabe": [
			"Kantonspolizei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Bezirk"
		],
		"description": "Einbruch- und Einschleichdiebstähle",
		"thema": "19 Kriminalität und Strafrecht",
		"unterthema": "Polizei",
		"kuerzel": "I.19.1.08662",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "6.02",
		"stufe1": "6 Sicherheit",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "06_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:15",
		"id": 8662
	},
	{
		"template": "template001_print",
		"data-id": 8663,
		"chart-id": 8663,
		"filter": "",
		"parentId": "8094",
		"children": [],
		"title": "Umzugssaldo",
		"subtitle": "Wohnviertel Klybeck und Kleinhüningen",
		"lesehilfe": "Im Jahr 2021 weist das Wohnviertel Klybeck einen negativen Umzugssaldo auf (-117).  D. h, es verlegen mehr Personen aus diesem Wohnviertel ihren Wohnsitz in den übrigen Kanton Basel-Stadt als von dort ins Wohnviertel Klybeck. Der Umzugssaldo Kleinhüningens ist 2021 ebenfalls negativ (-13).",
		"erlaeuterungen": "Umzüge sind räumliche Bevölkerungsbewegungen innerhalb des Kantons Basel-Stadt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Umzugssaldo",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "I.01.5.08663",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "2.10",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:24",
		"id": 8663
	},
	{
		"template": "spider001_print",
		"data-id": 8664,
		"chart-id": 8664,
		"filter": "",
		"parentId": "6757",
		"children": [],
		"title": "Kleinhüningen - Quartierradar",
		"subtitle": "Ausgabe 2022",
		"lesehilfe": "Beim Wohnviertel Kleinhüningen sticht der zweithöchste Anteil Sozialhilfeempfänger hervor. Die Gymnasialquote ist die zweitniedrigste im Kanton. Die Bauten im Wohnviertel sind neueren Datums, die Wohnfläche pro Person ist die zweitkleinste im Kanton. Die Steuererträge und die Erwerbstätigenquote zählen zu den niedrigsten im Kanton. Die Anzahl Arbeitsplätze pro Kopf ist gross.",
		"erlaeuterungen": "Die Grafik fasst 16 Indikatoren zusammen. Die Indikatoren sind den drei Bereichen <font color=\"923F8D\">Gesellschaft und Soziales</font>, <font color=\"68AB2B\">Raum und Umwelt</font> sowie <font color=\"689199\">Wirtschaft und Arbeit</font> zugeordnet. Die Werte der Indikatoren sind als Ränge im Vergleich zu allen anderen Basler Wohnvierteln und Gemeinden ausgewiesen. Das Wohnviertel oder die Gemeinde mit dem niedrigsten Wert des Indikators erhält Rang 1, mit dem höchsten Wert Rang 21 zugewiesen. Je grösser die graue Fläche, desto öfter erreicht das Wohnviertel oder die Gemeinde hohe Ränge bei den Indikatoren. <a href =\" https://www.statistik.bs.ch/dam/jcr:2cb04e13-b746-4455-8735-029f0439dc73/Quartierradar.pdf \" target = '_blank'>Zur Definition der einzelnen Indikatoren </a>",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Kleinhüningen - Quartierradar",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.08664",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "1.03",
		"stufe1": "1 Übersicht",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:18:52",
		"id": 8664
	},
	{
		"template": "populationPyramid001_print",
		"data-id": 8665,
		"chart-id": 8665,
		"filter": "",
		"parentId": "8614",
		"children": [],
		"title": "Wohnbevölkerung nach Alter und Geschlecht",
		"subtitle": "Wohnviertel Kleinhüningen, 2022",
		"lesehilfe": "Im Wohnviertel Kleinhüningen zählen die 30- bis 34-Jährigen, die 35- bis 39-Jährigen und die 60- bis 64-Jährigen zu den grössten Gruppen. In der Stadt Basel bilden die 25- bis 29-Jährigen, die 30- bis 34-Jährigen und die 35- bis 39-Jährigen die grössten Altersgruppen.",
		"erlaeuterungen": "Die Bevölkerungspyramide zeigt die Wohnbevölkerung am Jahresende nach Alter (Fünfjahresklassen), Geschlecht und Staatsangehörigkeit.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Wohnbevölkerung nach Alter und Geschlecht",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08665",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzelKunde": "2.02b",
		"stufe1": "2 Bevölkerung",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-15T08:14:03",
		"id": 8665
	},
	{
		"parentId": 8842,
		"children": [],
		"template": "mappie001_print",
		"title": "Übersichtskarte Wohnviertel",
		"subtitle": "",
		"kennzahlenset": "Stadtteilmonitoring Klybeck-Kleinhüningen (Print)",
		"kuerzel": "",
		"kuerzelKunde": "1.01",
		"description": "Übersichtskarte Wohnviertel",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2021-02-11T08:15:31.3131",
		"stufe1": "1 Übersicht",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die 21 Wohnviertel und Gemeinden (Riehen und Bettingen) des Kantons Basel-Stadt.",
		"erlaeuterungen": "",
		"darstellungsart": "Karte",
		"printformat": "",
		"orderKey": "01_00_00_00_00_000",
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8844,
		"chart-id": 8844,
		"filter": "",
		"id": 8848
	}
];