var indikatorensetData = [
	{
		"template": "befragungen001",
		"data-id": 22408,
		"chart-id": 22408,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Zufriedenheit mit Grünanlagen und Parks am Wohnort",
		"subtitle": "«Wie zufrieden sind Sie mit den Grünanlagen und Parks an Ihrem Wohnort?», Stadt Basel",
		"lesehilfe": "84,4% der Bevölkerung in der Stadt Basel sind 2023 mit den Grünanlagen und Parks an ihrem Wohnort eher bis sehr zufrieden.",
		"erlaeuterungen": "Alle vier Jahre wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt. Die Daten werden 2023 nach Geschlecht, Staatsangehörigkeit und Altersgruppe gewichtet. Die Daten der Befragungen 2011, 2015 und 2019 wurden nach den identischen Faktoren nachgewichtet. Die Werte dieser drei Jahre weichen daher von früher publizierten ab. Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit Grünanlagen und Parks am Wohnort",
		"thema": "50 Befragungen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.1.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-12-19T11:16:22",
		"id": 22408
	},
	{
		"template": "befragungen001",
		"data-id": 22409,
		"chart-id": 22409,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Zufriedenheit mit Wohnumfeld",
		"subtitle": "«Wie zufrieden sind Sie insgesamt mit Ihrem Wohnumfeld?», Stadt Basel",
		"lesehilfe": "Mit 46,9% ist beinahe die Hälfte der befragten Familien in der Stadt Basel sehr zufrieden mit dem Wohnumfeld. 2,4% zeigen sich sehr unzufrieden.",
		"erlaeuterungen": "Befragt werden Familien, die seit mindestens einem Jahr im Kanton Basel-Stadt wohnen. Als Familie wird ein Haushalt definiert, in welchem mindestens ein Elternteil mit mindestens einem Kind unter 18 Jahren gemeinsam lebt. Seit 2022 Gewichtung nach höchstem Bildungsabschluss der Eltern (ohne bzw. mit Tertiärabschluss) sowie der Familienform (Eineltern- bzw. Zweielternhaushalte). Die Daten der Befragungen 2013 und 2017 wurden nach den identischen Faktoren nachgewichtet. Die Werte dieser beiden Jahre weichen deshalb von früher publizierten ab.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Familienbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Zufriedenheit mit Wohnumfeld",
		"thema": "50 Befragungen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.1.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-12-19T11:16:24",
		"id": 22409
	},
	{
		"template": "befragungen001",
		"data-id": 22410,
		"chart-id": 22410,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Empfinden Hitzetage Sommer",
		"subtitle": "«Wie empfinden Sie die Hitzetage (Temperatur 30 °C und mehr) in den Sommermonaten an Ihrem Wohnort?», Stadt Basel, 2023",
		"lesehilfe": "22,2% der Bevölkerung in der Stadt Basel empfinden Hitzetage als unangenehm und 27,1% als eher unangenehm. Demgegenüber finden 10,0% Hitzetage angenehm und 23,4% eher angenehm.",
		"erlaeuterungen": "Befragt werden volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. Die Ergebnisse sind gewichtet nach Geschlecht, Staatsangehörigkeit und Altersgruppen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Empfinden Hitzetage Sommer",
		"thema": "50 Befragungen",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.1.3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-12-19T11:16:25",
		"id": 22410
	},
	{
		"template": "template001",
		"data-id": 22411,
		"chart-id": 22411,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Erreichbare Freiraumfläche",
		"subtitle": "Anzahl Einwohnerinnen und Einwohner pro Kategorie, Stadt Basel",
		"lesehilfe": "Im Jahr 2024 wohnen in der Stadt Basel gemäss Freiraumversorgungsmodell rund 25 700 Einwohnerinnen und Einwohner in Gebieten, von denen aus im Schnitt nur 0 bis 1,5 m<sup>2</sup> Freiraumfläche pro Person erreichbar sind.",
		"erlaeuterungen": "Defintion gemäss «Freiraumversorgungsmodell Stadt Basel» 2022. Dieses stellt die Versorgung der in der Stadt Basel wohnenden und beschäftigten Menschen mit erholungsrelevantem öffentlichem Freiraum dar. Pro Einwohnerin und Einwohner sollen 9 m<sup>2</sup> öffentlich zugänglicher, nutzungsoffener Freiraum mit Aufenthaltsqualität zur Verfügung stehen und für jede in Basel beschäftigte Person entsprechend 2 m<sup>2</sup>. Einberechnet werden alle öffentlich zugänglichen Freiräume, wenn sie vollständig oder zumindest teilweise nutzungsoffen sind und eine Aufenthaltsqualität bieten. Die Freiräume müssen zudem über eine angemessene Ausstattung verfügen und vom Wohn- resp. Arbeitsort aus innert 300 m (Luftlinie) erreichbar sein. Dies entspricht einer Gehdistanz von rund 10 Minuten für wenig mobile Menschen. Nicht querbare Zugangshindernisse werden im Freiraumversorgungsmodell berücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Städtebau & Architektur Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Erreichbare Freiraumfläche",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.2.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2026-01-05T10:20:50",
		"id": 22411
	},
	{
		"template": "template001",
		"data-id": 22412,
		"chart-id": 22412,
		"filter": "",
		"parentId": "6574",
		"children": [],
		"title": "Baumkronenbedeckung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2024 betrug die Kronenbedeckung (durch Bäume beschattete Fläche) 24,4% der gesamten Kantonsfläche und 17,2% der Stadt Basel. Schliesst man die reinen Waldflächen von der Betrachtung aus, so reduzieren sich die Anteile auf 16,5% respektive 15,1%.",
		"erlaeuterungen": "Durch flugzeuggestützte Laserabtastung der Oberfläche (LiDAR - Light Detecting And Ranging) werden Daten zur Kronenbedeckung abgeleitet. Seit 2021 finden alle drei Jahre Befliegungen statt, um die Entwicklung der Kronenbedeckung verfolgen zu können. <br>Berücksichtigt werden bei der Auswertung nur Kronen mit einer Höhe über 3 m. Die LiDAR-Methodologie wurde in den letzten Jahren verbessert. Änderungen unter 1% (zwischen 2012 und 2021) sollten nicht als reale Veränderungen betrachtet und mit Vorsicht interpretiert werden. Es gibt eine gewisse Variabilität bei Flugmethode, Flugzeitpunkt und Klassifizierungsmethode; diese befindet sich im Prozentbereich.",
		"quellenangabe": [
			"Stadtgärtnerei Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'https://data.bs.ch/explore/dataset/100357' target = '_blank'>OGD-Datensatz</a>",
			"<a href = 'https://tiefbauamt-bs.ch/geoviewer/kronenbedeckung' target = '_blank'>Baumkronenbedeckung als Karte</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Baumkronenbedeckung",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.2.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-12-19T11:16:29",
		"id": 22412
	},
	{
		"template": "template001",
		"data-id": 22413,
		"chart-id": 22413,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bevölkerung in Stadtklimakonzept-Fokusgebieten",
		"subtitle": "Stadt Basel, 2024",
		"lesehilfe": "Ende 2024 lebten im Kanton Basel-Stadt 109 916 Personen in Fokusgebieten, welche laut Stadtklimakonzept einen hohen Handlungsbedarf aufweisen.",
		"erlaeuterungen": "Im <a href='https://www.bs.ch/schwerpunkte/klima/stadtklima#strategie-stadtklimakonzept' target='_blank'>Stadtklimakonzept Basel-Stadt</a> sind, basierend auf der Klimaanalyse für das Jahr 2030, für die Priorisierung von Massnahmen zur Reduktion der bioklimatischen Belastung sogenannte Fokusgebiete eingegrenzt worden, in denen die Betroffenheit besonders gross ist.",
		"quellenangabe": [
			"Bau- und Verkehrsdepartement Basel-Stadt, Städtebau & Architektur"
		],
		"externalLinks": [
			"<a href = 'https://www.stadtklima.bs.ch' target = '_blank'>Stadtklima Basel-Stadt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Bevölkerung in Stadtklimakonzept-Fokusgebieten",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.3.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-12-19T11:16:31",
		"id": 22413
	},
	{
		"template": "template001",
		"data-id": 22414,
		"chart-id": 11910,
		"filter": "",
		"parentId": "11910",
		"children": [],
		"title": "Revitalisierungsrate Oberflächengewässer",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Seit 2015 wurden 1,6 km der bis 2035 geplanten 9,6 km revitalisiert.",
		"erlaeuterungen": "Länge der jährlich revitalisierten Gewässerabschnitte im Vergleich zur Gesamtlänge der gemäss Revitalisierungsplanung prioritär zu revitalisierenden Gewässerstrecken. Laut Gewässerschutzgesetz sind die Kantone verpflichtet, Revitalisierungen an Gewässern durchzuführen. Im Kanton Basel-Stadt ist der Nutzen von Revitalisierungsmassnahmen an Wiese und Riehenteich (Abschnitte Neuer Teich und Mühleteich) unter Berücksichtigung des zu erwartenden Aufwands am grössten. Bis 2035 sollen 9,6 km revitalisiert werden. In den Jahren 2015 bis 2095 sollen gesamthaft rund 4 000 km der Fliessgewässer in der Schweiz revitalisiert werden.",
		"quellenangabe": [
			"Amt für Umwelt und Energie Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Revitalisierungsrate Oberflächengewässer",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.4.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-12-19T11:16:33",
		"id": 22414
	},
	{
		"template": "template001",
		"data-id": 22415,
		"chart-id": 11909,
		"filter": "",
		"parentId": "11909",
		"children": [],
		"title": "Strukturen der Fliessgewässer",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Von 47 km Fliessstrecke werden 2025 nur knapp 2 km (4,2%)  als natürlich oder naturnah bezeichnet.",
		"erlaeuterungen": "Die Beurteilung der Struktur der Fliessgewässer erfolgt über die ökomorphologische Bewertung nach dem Modul-Stufen-Konzept, Stufe F des Bundesamtes für Umwelt. Im Kanton Basel-Stadt wird eine Fliesstrecke von insgesamt 47 km bewertet.",
		"quellenangabe": [
			"Amt für Umwelt und Energie Basel-Stadt"
		],
		"externalLinks": [
			"<a href = 'http://www.modul-stufen-konzept.ch' target = '_blank'>Modul-Stufen-Konzept des Bundesamtes für Umwelt</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Strukturen der Fliessgewässer",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.4.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-12-19T11:16:35",
		"id": 22415
	},
	{
		"template": "template001",
		"data-id": 22417,
		"chart-id": 22417,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bodenversiegelung",
		"subtitle": "Stadt Basel",
		"lesehilfe": "Bei der letzten Datenerhebung 2014 waren in der Stadt Basel gemäss Arealstatistik 1 428 ha versiegelt.",
		"erlaeuterungen": "Fläche an versiegelten Böden (absolut und pro Einwohner). Von Bodenversiegelung spricht man, wenn die Bodenoberfläche mit praktisch undurchlässigen Materialien abgedeckt oder überdeckt wird. Der Austausch von Wasser, Luft und Energie zwischen Atmosphäre und Boden wird nahezu verhindert. Von Bedeutung sind dabei vor allem Gebäude, Verkehrsflächen, Energieversorgungsanlagen und Deponien.<br><br>Zu den versiegelten Böden werden in der Arealstatistik (Nomenklatur der Bodenbedeckung NOLC04) folgende Kategorien gezählt:<br>- Befestigte Flächen (z. B. Verkehrsflächen)<br>- Gebäude<br>- Treibhäuser<br><br>Die Arealstatistik erhebt im Turnus von zwölf bzw. neun Jahren Informationen zur Bodennutzung und -bedeckung der Schweiz auf der Grundlage von Luftbildern des Bundesamtes für Landestopographie (Stichpunktprobenerhebung im Abstand von 100 x 100 m).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Arealstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Bodenversiegelung",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.5.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-12-19T11:16:36",
		"id": 22417
	},
	{
		"template": "template001",
		"data-id": 22418,
		"chart-id": 22418,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil der Gebäudeflächen an der Siedlungsfläche",
		"subtitle": "Stadt Basel",
		"lesehilfe": "Ein Viertel (2024: 25,3%) der <a href='https://map.geo.bs.ch/?lang=de&baselayer_ref=blank&tree_groups=Richtplankarte&tree_group_layers_Richtplankarte=RP_Ausgangslage_Siedlung_Siedlungsgebiet&map_x=2614535&map_y=1267844&map_zoom=2&tree_group_opacity_Richtplankarte=1' target='_blank'>Siedlungsfläche</a> der Stadt Basel sind Gebäudeflächen.",
		"erlaeuterungen": "Die Angaben basieren auf der Datenebene «Bodenbedeckung» der amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100 m<sup>2</sup> geführt werden. Diese werden bei Bedarf oder spätestens in einem Turnus von 6-12 Jahren mit einer periodischen Nachführung aktualisiert. Befestigte Objekte wie Gebäude, Strassenräume oder öffentliche Pärke werden detaillierter erfasst und bei baulichen Änderungen nachgeführt.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Anteil der Gebäudeflächen an der Siedlungsfläche",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.5.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-12-19T11:16:38",
		"id": 22418
	},
	{
		"template": "template001",
		"data-id": 22418,
		"chart-id": 22419,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil der Verkehrsflächen an der Siedlungsfläche",
		"subtitle": "Stadt Basel",
		"lesehilfe": "Ein Viertel (2024: 24,4%) der <a href='https://map.geo.bs.ch/?lang=de&baselayer_ref=blank&tree_groups=Richtplankarte&tree_group_layers_Richtplankarte=RP_Ausgangslage_Siedlung_Siedlungsgebiet&map_x=2614535&map_y=1267844&map_zoom=2&tree_group_opacity_Richtplankarte=1' target='_blank'>Siedlungsfläche</a> der Stadt Basel sind Verkehrsflächen.",
		"erlaeuterungen": "Die Angaben basieren auf der Datenebene «Bodenbedeckung» der amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100 m<sup>2</sup> geführt werden. Diese werden bei Bedarf oder spätestens in einem Turnus von 6-12 Jahren mit einer periodischen Nachführung aktualisiert. Befestigte Objekte wie Gebäude, Strassenräume oder öffentliche Pärke werden detaillierter erfasst und bei baulichen Änderungen nachgeführt.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Anteil der Verkehrsflächen an der Siedlungsfläche",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.5.3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-12-19T11:16:40",
		"id": 22419
	},
	{
		"template": "template001",
		"data-id": 22420,
		"chart-id": 22420,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteil der Freiflächen an den Arealentwicklungsflächen",
		"subtitle": "in m<sup>2</sup>, Stadt Basel",
		"lesehilfe": "In den Jahren 2025-2030 sind in grösseren Arealentwicklungsgebieten in der Stadt Basel neue Freiraumflächen von insgesamt 17 900 m<sup>2</sup> geplant. Für 2045-2050 sind bisher noch keine zusätzlichen Freiraumflächen vorgesehen.",
		"erlaeuterungen": "Stand November 2025, gemäss Städtebau & Architektur Basel-Stadt.",
		"quellenangabe": [
			"Städtebau & Architektur Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde"
		],
		"description": "Anteil der Freiflächen an den Arealentwicklungsflächen",
		"thema": "02 Raum, Umwelt",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Stadtklimakonzept",
		"kuerzelKunde": "3.6.1.",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-12-19T11:16:41",
		"id": 22420
	}
];