var indikatorensetData = [
	{
		"template": "line001_print",
		"data-id": 9315,
		"chart-id": 9315,
		"filter": "",
		"parentId": "6896",
		"children": [],
		"title": "Zusammensetzung der Gesamteinnahmen",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Die Gesamteinnahmen des Kantons betragen über den betrachteten Zeitraum zwischen knapp 4 Mrd. und 5 Mrd. Franken. Die Werte sind dem Jahresbericht des Kantons entommen und nach dem Mittelfluss pro Kalenderjahr dargestellt (zum Beispiel unabhängig davon, für welches Steuerjahr genau bezahlt wurde; die Daten der im Bericht folgenden Grafiken zur Steuerstatistik beziehen sich hingegen auf das jeweilige Steuerjahr).  Dies erschwert einen Vergleich mit den Vorjahren. Im Kalenderjahr 2019 beträgt der Ertrag aus Einkommens- und Vermögenssteuern rund 1,8 Mrd. Franken (+0,3% gegenüber dem Vorjahr), der Anteil am Gesamtertrag beträgt 36,3%. Die Gewinn- und Kapitalsteuern belaufen sich 2019 auf rund 1,1 Mrd. Franken (+44,3% gegenüber 2018), der Anteil liegt bei 22,2%. Zusammen beträgt der Anteil der aufgeführten Steuerarten im Jahr 2019 58,5% des gesamten Ertrags des Kantons. Der Ertrag aus Quellensteuer ist zum Teil in der Kategorie Übriges und zum Teil in der Kategorie Einkommens- und Vermögenssteuern enthalten.",
		"erlaeuterungen": "Der Jahresbericht des Kantons Basel-Stadt weist Erträge aus, die während eines Kalenderjahres verbucht wurden. Dies unterscheidet sich somit von der Steuerstatistik Basel-Stadt, der Veranlagungsdaten zugrundeliegen, die auf ein bestimmtes Steuerjahr bezogen sind – unabhängig davon, in welchem Jahr die Steuer verbucht oder bezahlt worden ist. NP = Natürliche Personen; JP = Juristische Personen.",
		"quellenangabe": [
			"Jahresbericht des Kantons Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zusammensetzung der Gesamteinnahmen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09315",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.1.1",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.1 Ertrag des Kantons",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_101",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:50",
		"id": 9315
	},
	{
		"template": "line001_print",
		"data-id": 9316,
		"chart-id": 9316,
		"filter": "",
		"parentId": "6897",
		"children": [],
		"title": "Entwicklung des Ertrags aus Steuern",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Die einzelnen Steuerertragsarten haben sich seit 2010 unterschiedlich entwickelt. Grössere Schwankungen liegen vor allem bei der Gewinnsteuer vor, zwischen 2010 und 2018 ist dieser Wert nominal um 9,9% gestiegen. 2018 beträgt der Zuwachs gegenüber dem Vorjahr 53,7%. Bei den natürlichen Personen ist der Ertrag aus Einkommenssteuern von 2010 bis 2019 um 12,4% gestiegen (2019 gegenüber Vorjahr: +6,2%), aus Vermögenssteuern um 47,7% (gegenüber Vorjahr: +34,4%). Der Ertrag aus Quellenbesteuerung (2020) stieg um 77,9% (gegenüber Vorjahr: +7,5%).",
		"erlaeuterungen": "Der Jahresbericht des Kantons Basel-Stadt weist Erträge aus, die während eines Kalenderjahres verbucht wurden. Dies unterscheidet sich somit von der Steuerstatistik Basel-Stadt, der Veranlagungsdaten zugrunde liegen, die auf ein bestimmtes Steuerjahr bezogen sind – unabhängig davon, in welchem Jahr die Steuer verbucht oder bezahlt worden ist. Zum Zeitpunkt des Exports der Steuerdaten für statistische Zwecke sind gewöhnlich rund 98% der Veranlagungen von natürlichen Personen bearbeitet. Veränderungen gegenüber dem Vorjahr können zu einem Teil auch aufgrund des unterschiedlichen Bearbeitungsstandes entstehen.",
		"quellenangabe": [
			"Jahresbericht des Kantons Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung des Ertrags aus Steuern",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09316",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.1.2",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.1 Ertrag des Kantons",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_102",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:51",
		"id": 9316
	},
	{
		"template": "line001_print",
		"data-id": 9317,
		"chart-id": 9317,
		"filter": "",
		"parentId": "6898",
		"children": [],
		"title": "Veranlagungen natürlicher Personen und Bevölkerung",
		"subtitle": "nach Tarif und Alter, Basel-Stadt, 2019",
		"lesehilfe": "Im Jahr 2019 gibt es insgesamt 117 200 Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen und wohnhaften Personen. Die meisten Veranlagungen mit jeweils über 2 000 liegen in den Altersjahren 28 bis 39 sowie 53 bis 56 vor. Nicht berücksichtigt sind Veranlagungen von Auswärtigen (insgesamt rund 8 200 Veranlagungen) und von Unterjährigen (ca. 4 900 Veranlagungen). Rund 79 000 Veranlagungen von Alleinstehenden (Anteil 67,8%), 31 300 von Verheirateten (26,7%) und ca. 6 500 von Alleinstehenden mit Kind oder einer anderen unterstützten Person (5,5%).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Veranlagungen natürlicher Personen und Bevölkerung",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09317",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.2.1",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_201",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:52",
		"id": 9317
	},
	{
		"template": "line001_print",
		"data-id": 9318,
		"chart-id": 9318,
		"filter": "",
		"parentId": "6899",
		"children": [],
		"title": "Veranlagungen, Bevölkerung und Summe von Reineinkommen, -vermögen und Steuerertrag",
		"subtitle": "indexiert (2010 = 100), Basel-Stadt",
		"lesehilfe": "Die indexierten Linien für die Wohnbevölkerung in Basel-Stadt und die Anzahl der Veranlagungen verlaufen relativ gleichmässig. Die grössten Schwankungen seit 2010 zeigt das Reinvermögen, das seitdem nominal 46,9% gewachsen ist. Das Reineinkommen stieg um 14,4%. Der Ertrag aus Einkommens- und Vermögenssteuer lag 2019 um 18,6% über dem Wert von 2010. Der grössere Anstieg des Reinvermögens zwischen 2011 und 2014 sowie in den Jahren 2016 und 2019 lag unter anderem am steigenden Wert von Kapitalanlagen bzw. Wertschriften. Ein weiterer Grund für die Schwankungen kann auch der Bearbeitungsstand der Veranlagungen sein. In den Auswertungen sind in der Regel zum Zeitpunkt des Datenexports 98% der gesamten Veranlagungen berücksichtigt.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Veranlagungen, Bevölkerung und Summe von Reineinkommen, -vermögen und Steuerertrag",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09318",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.2.2",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_202",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:54",
		"id": 9318
	},
	{
		"template": "line001_print",
		"data-id": 9319,
		"chart-id": 9319,
		"filter": "",
		"parentId": "6900",
		"children": [],
		"title": "Mittelwert und Median des Reineinkommens, Summe des Ertrags aus Einkommenssteuer",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Mittelwert und Median des Reineinkommens pro Veranlagung bewegen sich relativ konstant. Im Jahr 2019 beträgt der Mittelwert rund 72 400 Franken (+10,1% seit 2010, +3,8% gegenüber 2018), der Median ca. 49 900 Franken (+3,8% seit 2010, +0,4% gegenüber 2018). Der Ertrag aus Einkommenssteuer 2019 beträgt 1,223 Mrd. Franken (+12,4% gegenüber 2010 und +6,2% gegenüber 2018).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittelwert und Median des Reineinkommens, Summe des Ertrags aus Einkommenssteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09319",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.2.3",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_203",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:55",
		"id": 9319
	},
	{
		"template": "line001_print",
		"data-id": 9320,
		"chart-id": 9320,
		"filter": "",
		"parentId": "6901",
		"children": [],
		"title": "Mittelwert des Reineinkommens",
		"subtitle": "in Franken, Basel-Stadt, 2010 und 2019",
		"lesehilfe": "In den meisten Wohnvierteln ist ein Anstieg des Mittelwertes pro Veranlagung im Vergleich zum Steuerjahr 2010 zu verzeichnen. Am relativ stärksten fällt er in den Wohnvierteln Rosental und Vorstädte aus, mit 26,2% und 39,5%. In der Gemeinde Bettingen beträgt die Steigerung 49,0%. Der Mittelwert aller Veranlagungen im Kanton stieg um 10,1%.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittelwert des Reineinkommens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09320",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.2.4",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_204",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:55",
		"id": 9320
	},
	{
		"template": "line001_print",
		"data-id": 9321,
		"chart-id": 9321,
		"filter": "",
		"parentId": "6902",
		"children": [],
		"title": "Median des Reineinkommens",
		"subtitle": "in Franken, Basel-Stadt, 2010 und 2019",
		"lesehilfe": "Der Median des Reineinkommens pro Veranlagung ist zwischen 2010 und 2019 in den meisten Wohnvierteln gewachsen. Den stärksten relativen Zuwachs gibt es in den Wohnvierteln Vorstädte (+17,2%) und Rosental (+15,2%). Den grössten Rückgang verzeichnet das Wohnviertel Klybeck (-5,3%). Der Median aller Veranlagungen im gesamten Kanton stieg um 3,8%.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Median des Reineinkommens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09321",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.2.5",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_205",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:56",
		"id": 9321
	},
	{
		"template": "line001_print",
		"data-id": 9322,
		"chart-id": 9322,
		"filter": "",
		"parentId": "6903",
		"children": [],
		"title": "Mittelwert und Median des Reinvermögens, Summe des Ertrags aus Vermögenssteuer",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Der Median des Reinvermögens ist seit 2010 relativ stetig gestiegen, insgesamt um 50,0%, von rund 13 100 auf 19 600 Franken. Der Mittelwert und der Ertrag aus Vermögenssteuer zeigen im Zeitverlauf etwas grössere Schwankungen. Im Vergleich zum Vorjahr sind die Werte ebenfalls gestiegen, der Mittelwert um 22,2%, der Ertrag um 34,4% und der Median um 2,3%. Der Anstieg des Medians über die Jahre ist ein Indikator dafür, dass sich die tieferen Vermögen allgemein insgesamt positiv entwickelt haben. Allerdings sind die Werte des Medians im Vergleich zum Mittelwert des Reinvermögens auf einem deutlich niedrigeren Niveau. Ein Teil der stärkeren Veränderungen kannn auch im Bearbeitungsstand der Veranlagungen begründet sein - in den Auswertungen sind in der Regel zum Zeitpunkt des Datenexports für jedes Steuerjahr 98% der gesamten Veranlagungen im Kanton berücksichtigt.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige, ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittelwert und Median des Reinvermögens, Summe des Ertrags aus Vermögenssteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09322",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.2.6",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_206",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:57",
		"id": 9322
	},
	{
		"template": "line001_print",
		"data-id": 9323,
		"chart-id": 9323,
		"filter": "",
		"parentId": "6904",
		"children": [],
		"title": "Mittelwert des Reinvermögens",
		"subtitle": "in Franken, Basel-Stadt, 2010 und 2019",
		"lesehilfe": "Den höchsten Mittelwert des Reinvermögens pro Veranlagung weist im Jahr 2019 mit ca. 2,8 Mio. Franken die Gemeinde Bettingen auf, gefolgt vom Wohnviertel Vorstädte mit rund 2,6 Mio. Franken. 2010 lag der höchste Wert im Wohnviertel Bruderholz.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittelwert des Reinvermögens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09323",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.2.7",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_207",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:57",
		"id": 9323
	},
	{
		"template": "line001_print",
		"data-id": 9324,
		"chart-id": 9324,
		"filter": "",
		"parentId": "6905",
		"children": [],
		"title": "Median des Reinvermögens",
		"subtitle": "in Franken, Basel-Stadt, 2010 und 2019",
		"lesehilfe": "Der höchste Median des Reinvermögens 2019 wird mit rund 92 200 Franken in der Einwohnergemeinde Bettingen verzeichnet. Auch 2010 wurde der höchste Wert dort registriert.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Median des Reinvermögens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09324",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.2.8",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_208",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:58",
		"id": 9324
	},
	{
		"template": "line001_print",
		"data-id": 9325,
		"chart-id": 9325,
		"filter": "",
		"parentId": "6906",
		"children": [],
		"title": "Ertrag aus  Einkommens- und Vermögensssteuer",
		"subtitle": "in Franken, Basel-Stadt, 2010 und 2019",
		"lesehilfe": "Die einzelnen Wohnviertel und Gemeinden tragen unterschiedlich zum Steuerertrag des Kantons bei. Dies liegt einerseits an der grösseren Anzahl an Steuerpflichtigen (zum Beispiel Gundeldingen, St. Johann, Riehen), andererseits am höheren durchschnittlichen Ertrag pro Veranlagung (zum Beispiel Bruderholz oder St. Alban). In den meisten Wohnvierteln bzw. Gemeinden fällt der Steuerertrag beider Steuerarten 2019 höher aus als 2010. Der höchste Betrag an Einkommenssteuer liegt 2019 in Riehen vor (einschliesslich Gemeindesteuer), er beträgt rund 162 Mio. Franken. Der höchste Wert für die Vermögenssteuer liegt mit ca. 86 Mio. Franken im Wohnviertel Bruderholz vor.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Ertrag aus  Einkommens- und Vermögensssteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09325",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.2.9",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_209",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:58",
		"id": 9325
	},
	{
		"template": "befragungen001_print",
		"data-id": 9326,
		"chart-id": 9326,
		"filter": "",
		"parentId": "6907",
		"children": [],
		"title": "Veranlagungen und Summe Einkommenssteuer nach Stufen des steuerbaren Einkommens",
		"subtitle": "in Franken, Basel-Stadt, 2019",
		"lesehilfe": "Bei 25,1% aller Veranlagungen (ca. 29 400) beträgt das steuerbare Einkommen 0 Franken, somit muss keine Einkommenssteuer bezahlt werden. Fast gleich viele Veranlagungen (24,3%) liegen in der Gruppe mit einem steuerbaren Einkommen von 1 bis 24 999 Franken vor. Der Einkommenssteuerertrag beträgt zusammen rund 78 Mio. Franken. Dies sind 6,3% des gesamten Einkommenssteuerertrags. Von Veranlagungen mit einem steuerbaren Einkommen von 200 000 Franken und mehr (ca. 3 900 oder 3,3% aller Veranlagungen) stammt ein Einkommenssteuerertrag von rund 382 Mio. Franken (31,2% des Einkommenssteuertrags). Insgesamt stammen aus 11,2% der Veranlagungen 52,4% der Einkommenssteuer.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Veranlagungen und Summe Einkommenssteuer nach Stufen des steuerbaren Einkommens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09326",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.2.10",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_210",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:52",
		"id": 9326
	},
	{
		"template": "befragungen001_print",
		"data-id": 9327,
		"chart-id": 9327,
		"filter": "",
		"parentId": "6908",
		"children": [],
		"title": "Veranlagungen und Summe Vermögenssteuer nach Stufen des steuerbaren Vermögens",
		"subtitle": "in Franken, Basel-Stadt, 2019",
		"lesehilfe": "Bei der Vermögenssteuer sind die Anteile der Vermögensklassen weniger gleichmässig verteilt als bei der Einkommenssteuer. Bei 69,7% aller Veranlagungen (ca. 81 700) betrug das steuerbare Vermögen 0 Franken, somit musste keine Vermögenssteuer bezahlt werden. Bei rund 3 400 Veranlagungen (2,9%) mit einem steuerbaren Vermögen von 2 Mio. Franken und mehr betrug die Vermögenssteuer insgesamt rund 281 Mio. Franken (82,1% des gesamten Vermögenssteuerertrags). Von 89,5% aller Veranlagungen (Vermögensklassen von 0 bis 499 999 Franken) stammen insgesamt 4,5% des Vermögenssteuerertrags des Steuerjahres 2019. Aus 10,5% der Veranlagungen stammen insgesamt rund 95,5% der Vermögenssteuer.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Veranlagungen und Summe Vermögenssteuer nach Stufen des steuerbaren Vermögens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09327",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.2.11",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_211",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:53",
		"id": 9327
	},
	{
		"template": "line001_print",
		"data-id": 9328,
		"chart-id": 9328,
		"filter": "",
		"parentId": "6909",
		"children": [],
		"title": "Gesamtertrag aus Einkommens- und Vermögenssteuer",
		"subtitle": "in Franken, Basel-Stadt, 2010 und 2019",
		"lesehilfe": "Den höchsten Ertrag aus Einkommens- und Vermögenssteuer 2019 verzeichnet die Gemeinde Riehen mit rund 206 Mio. Franken (+16,7% gegenüber 2010), gefolgt vom Wohnviertel Bruderholz mit ca. 189 Mio. Franken (-7,3%). Den kleinsten Ertrag steuert Kleinhüningen mit 7,9 Mio. Franken bei (+10,4%). Im Jahr 2019 beträgt der Wert für den gesamten Kanton rund 1,6 Mrd. Franken, 18,6% mehr als 2010.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Gesamtertrag aus Einkommens- und Vermögenssteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09328",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.2.12",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_212",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:53",
		"id": 9328
	},
	{
		"template": "line001_print",
		"data-id": 9329,
		"chart-id": 9329,
		"filter": "",
		"parentId": "6910",
		"children": [],
		"title": "Summe des Ertrags aus Einkommens- und Vermögenssteuer von Zugezogenen und Weggezogenen",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Für jedes betrachtete Jahr liegt ein positiver Saldo des Steuerertrags von Zuzügern und Wegzügern vor. 2019 betrug er 6,1 Mio. Franken. Sowohl bei der Einkommenssteuer (rund 5,6 Mio. Franken) als auch bei der Vermögenssteuer (500 000 Franken) wurde ein Plus verzeichnet. Von Zuzügern lagen für das Steuerjahr 2019 rund 5 000 Veranlagungen vor, von Wegzügern des Vorjahres 4 500 Veranlagungen. Die Methodik zur Untersuchung des Wanderungseffekts unterscheidet sich von den übrigen Auswertungen.",
		"erlaeuterungen": "Die Methodik zur Untersuchung des Wanderungseffekts unterscheidet sich von den übrigen Auswertungen. Die Analyse der Effekte auf den Ertrag aus Einkommens- und Vermögenssteuer durch Zu- und Abwanderung im Kanton Basel-Stadt wird durch verschiedene methodische Aspekte erschwert. Seit der eidgenössischen Steuerharmonisierung im Jahr 2002 ist für die Steuerpflicht innerhalb der Schweiz der Wohnsitz am 31. Dezember massgebend. Es liegen daher in Basel-Stadt in der Regel keine Daten zur Einkommens- und Vermögenssituation im Jahr des Wegzugs vor. Für die Steuerstatistik der Wegzügerinnen und Wegzüger wurden daher die Steuerdaten des jeweiligen Vorjahres verwendet. Für die Zugezogenen und die ganzjährig Niedergelassenen sind die Steuerdaten des Berichtsjahres vorhanden und wurden für die Analyse verwendet. Bei der Definition der Zuzüger wurde berücksichtigt, dass Ausländer ohne Niederlassungsbewilligung in der Regel an der Quelle veranlagt werden. Aus diesem Grund wurde ein Zuzug erst bei einer Niederlassung als solcher gezählt. Quellensteuerpflichtige sind in der Regel nicht erfasst, ausser sie werden nachträglich ordentlich veranlagt. Dies ist zum Beispiel der Fall, wenn die Einkünfte mehr als 120 000 Franken im Kalenderjahr betragen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Summe des Ertrags aus Einkommens- und Vermögenssteuer von Zugezogenen und Weggezogenen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09329",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.3.1",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.3 Wanderung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_301",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:59",
		"id": 9329
	},
	{
		"template": "template001_print",
		"data-id": 9330,
		"chart-id": 9330,
		"filter": "",
		"parentId": "6911",
		"children": [],
		"title": "Quellensteuerertrag",
		"subtitle": "in Franken, Basel-Stadt, 2011 und 2020",
		"lesehilfe": "Bei der Quellensteuer liegen die Daten bereits für das Jahr 2020 vor. Im Vergleich mit dem Jahr 2011 hat sowohl die Anzahl Veranlagungen als auch der Ertrag aus Quellensteuer von in Basel-Stadt wohnhaften Personen stark zugenommen. 2020 beträgt der Quellensteuerertrag rund 533 Mio. Franken (einschliesslich Auswärtige sowie der Anteil, der an den Bund fliesst). Die meisten Veranlagungen in Basel-Stadt liegen 2020 von Personen vor, die im Wohnviertel Matthäus wohnen (ca. 2 800); bei mehreren Quellensteuerveranlagungen pro Person wurden diese zu einer zusammgefasst). Der höchste Ertrag wird im Wohnviertel St. Alban mit 37,9 Mio. Franken verzeichnet. Von Personen, die nicht im Kanton Basel-Stadt wohnen, stammen rund 207 Mio. Franken Quellensteuern.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Daten aus der Quellenbesteuerung in Basel-Stadt. <br>Ausländische Arbeitnehmer und Arbeitnehmerinnen, welche keine Niederlassungsbewilligung besitzen, aber im Kanton Basel-Stadt Wohnsitz haben, unterliegen unter anderem für die Einkünfte aus unselbstständiger Erwerbstätigkeit einem Steuerabzug an der Quelle. Die Quellensteuerauswertungen beinhalten auch den Anteil, der an den Bund fliesst, im Steuerjahr 2020 rund 109 Mio. Franken. <br>Unter anderem werden Quellensteuerpflichtige mit Einkünften von über 120 000 Franken automatisch nachträglich ordentlich veranlagt. Diese sind dann ebenfalls in den Auswertungen der Einkommens- und Vermögenssteuer enthalten (Doppelzählungen); im Steuerjahr 2019 betrifft dies 5 316 Veranlagungen (4,5% der rund 117 000 ordentlichen Veranlagungen), die somit auch in den Auswertungen zur Quellenbesteuerung 2019 enthalten waren.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Quellensteuerertrag",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09330",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.4.1",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.4 Quellensteuer",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_04_00_00_00_401",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:59",
		"id": 9330
	},
	{
		"template": "template001_print",
		"data-id": 9331,
		"chart-id": 9331,
		"filter": "",
		"parentId": "6912",
		"children": [],
		"title": "Quellensteuerertrag nach Status",
		"subtitle": "in Franken, Basel-Stadt, 2011 und 2020",
		"lesehilfe": "Die bedeutendsten Erträge aus Quellenbesteuerung stammen aus Erwerbseinkommen (ohne Grenzgänger), 2020 sind dies rund 384 Mio. Franken (+81,2% gegenüber 2011). Der Ertrag der Grenzgänger aus Deutschland u. a. (einschliesslich einige wenige aus anderen Staaten) beträgt 2020 insgesamt 88,7 Mio. Franken (+18,6% gegenüber 2011). Die meisten Grenzgänger aus Frankreich zahlen keine direkte Quellensteuer in Basel-Stadt. Der Fiskalausgleich, den es aus Frankreich für sie gibt, ist der Vollständigkeit halber aufgeführt. Für das Jahr 2020 liegt er bei 75,6 Mio. Franken, +11,1% gegenüber 2011). Eine gewisse Bedeutung haben auch die Quellensteuererträge, die aufgrund von Kapitalleistungen anfallen. 2020 betragen sie insgesamt 32,1 Mio. Franken. In den meisten Kategorien hat auch die Anzahl der Veranlagungen seit 2011 stark zugenommen, beispielsweise beim Erwerb von rund 23 100 auf 34 300 (+48,5%). Insgesamt beträgt der Quellensteuerertrag 2020 rund 533 Mio. Franken, 69,9% mehr als 2011 und 7,5% mehr als im Jahr 2019.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Daten aus der Quellenbesteuerung in Basel-Stadt. <br>Ausländische Arbeitnehmer und Arbeitnehmerinnen, welche keine Niederlassungsbewilligung besitzen, aber im Kanton Basel-Stadt Wohnsitz haben, unterliegen unter anderem für die Einkünfte aus unselbstständiger Erwerbstätigkeit einem Steuerabzug an der Quelle. Ebenso sind beispielsweise Grenzgänger aus Deutschland quellensteuerpflichtig. Die Quellensteuerauswertungen beinhalten auch den Anteil, der an den Bund fliesst, im Steuerjahr 2020 rund 109 Mio. Franken. <br>Unter anderem werden Quellensteuerpflichtige mit Einkünften von über 120 000 Franken automatisch nachträglich ordentlich veranlagt. Diese sind dann ebenfalls in den Auswertungen der Einkommens- und Vermögenssteuer enthalten (Doppelzählungen); im Steuerjahr 2019 betrifft dies 5 316 Veranlagungen (4,5% der rund 117 000 ordentlichen Veranlagungen), die somit auch in den Auswertungen zur Quellenbesteuerung 2019 enthalten waren.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Quellensteuerertrag nach Status",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09331",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.4.2",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.4 Quellensteuer",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_04_00_00_00_402",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:00:01",
		"id": 9331
	},
	{
		"template": "mappie002_print",
		"data-id": 9332,
		"chart-id": 9332,
		"filter": "",
		"parentId": "6980",
		"children": [],
		"title": "Mittelwert des Gesamtsteuerertrags sowie Anteil von Einkommens- und Vermögenssteuerertrag",
		"subtitle": "in Franken, Basel-Stadt, 2019",
		"lesehilfe": "Der Mittelwert des Gesamtsteuerertrags pro Veranlagung im Jahr 2019 fällt in den hell gefärbten Wohnvierteln eher niedrig aus, in den dunkleren eher hoch. St. Alban, Bruderholz und Riehen tragen die höchsten Summen zum Gesamtertrag des Kantons bei. Die Grösse der Kreise symbolisiert jeweils die Höhe des Steuerertrags. Eher klein fällt der Gesamtertrag in den Wohnvierteln Kleinhüningen, Clara oder Altstadt Kleinbasel aus. Der Anteil an Vermögenssteuer ist zum Beispiel im Wohnviertel Bruderholz besonders ausgeprägt.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen, ohne Auswärtige, ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Mittelwert des Gesamtsteuerertrags sowie Anteil von Einkommens- und Vermögenssteuerertrag",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09332",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.2.13",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_213",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T10:59:54",
		"id": 9332
	},
	{
		"template": "template001_print",
		"data-id": 9333,
		"chart-id": 9333,
		"filter": "",
		"parentId": "6981",
		"children": [],
		"title": "Gewinn-, Kapital- und Grundstücksteuer",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Für die juristischen Personen liegen die neuesten Daten für das Steuerjahr 2018 vor. Zuletzt beträgt dieser Steuerertrag von ihnen bei insgesamt rund 11 900 Veranlagungen zusammen 760 Mio. Franken. Die bedeutendste Steuerart, die Gewinnsteuer, trug 583 Mio. dazu bei. Kapitalsteuer wurden rund 123 Mio. Franken entrichtet, Grundstücksteuer 17,1 Mio. Franken. Der Gesamtertrag schwankt teilweise erheblich von Jahr zu Jahr – insgesamt ging er um 1,3% zurück (im Jahr 2009 war die Gewinnsteuer vergleichsweise hoch). Im Vergleich zum Vorjahr stieg der Ertrag im Steuerjahr 2018 um 46,2%. Im Jahr zuvor war der Rückgang relativ gross ausgefallen (-26,9% gegenüber 2016).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von juristischen Personen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Gewinn-, Kapital- und Grundstücksteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09333",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.5.1",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.5 Juristische Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_05_00_00_00_501",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:00:01",
		"id": 9333
	},
	{
		"template": "befragungen001_print",
		"data-id": 9334,
		"chart-id": 9334,
		"filter": "",
		"parentId": "6982",
		"children": [],
		"title": "Steuerertrag juristischer Personen nach Stufen der Gesamtsteuer",
		"subtitle": "in Franken, Basel-Stadt, 2018",
		"lesehilfe": "Im Jahr 2018 gibt es insgesamt rund 11 500 Veranlagungen von juristischen Personen im Kanton Basel-Stadt. 1 353 (11,3%) von ihnen müssen keine Gewinn-, Kapital- oder Grundstücksteuer bezahlen. Bei der grossen Mehrheit ( rund 7 500 Veranlagungen bzw. 62,7%) liegt der Steuerbetrag zwischen 1 und 4 999 Franken. Der Ertrag von ihnen beläuft sich insgesamt auf 7,3 Mio. Franken. In der obersten Kategorie – mit einem Steuerbetrag von über 1 Mio. Franken pro Veranlagung – gibt es 68 Veranlagungen (0,6% von allen), deren Steuerbetrag ca. 586 Mio. Franken (77,2% des gesamten Steuerertrags der juristischen Personen) beträgt.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von juristischen Personen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Steuerertrag juristischer Personen nach Stufen der Gesamtsteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09334",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.5.2",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.5 Juristische Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_05_00_00_00_502",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:00:02",
		"id": 9334
	},
	{
		"template": "befragungen001_print",
		"data-id": 9335,
		"chart-id": 9335,
		"filter": "",
		"parentId": "6983",
		"children": [],
		"title": "Steuerertrag juristischer Personen nach Stufen des steuersatzbestimmenden Gewinns",
		"subtitle": "in Franken, Basel-Stadt, 2018",
		"lesehilfe": "Mehr als die Hälfte (58,2%) der juristischen Personen weisen 2018 einen steuersatzbestimmenden Gewinn von 0 Franken auf. Juristische Personen, die keine Gewinnsteuer entrichten müssen, zahlen in der Regel als Alternativsteuer die Grundstücksteuer. Von diesen stammen insgesamt 38,8 Mio. Franken, dies sind 5,1% des Gesamtertrags. Am anderen Ende tragen insgesamt 588 Veranlagungen von juristischen Personen (4,9%) mit einem satzbestimmenden Gewinn von über 1 Mio. Franken einen Steuerbetrag von zusammen 657 Mio. Franken bei (86,5% der gesamten Steuer der juristischen Personen).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von juristischen Personen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Steuerertrag juristischer Personen nach Stufen des steuersatzbestimmenden Gewinns",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.09335",
		"kennzahlenset": "Steuern (Print)",
		"kuerzelKunde": "2.5.3",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.5 Juristische Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_05_00_00_00_503",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:00:03",
		"id": 9335
	}
];