var indikatorensetData = [
	{
		"template": "template001",
		"data-id": 22357,
		"chart-id": 22357,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Veranlagungen natürlicher Personen",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Im Zuge der ordentlichen Veranlagung natürlicher Personen gab es im Steuerjahr 2022 insgesamt fast 119 000 Veranlagungen von ganzjährig in Basel-Stadt wohnhaften Personen. 2013 waren es rund 115 000.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anzahl Veranlagungen natürlicher Personen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.2.7",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_207",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-10T09:02:31",
		"id": 22357
	},
	{
		"template": "template001",
		"data-id": 22358,
		"chart-id": 22358,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Ertrag aus Einkommenssteuer",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Die einzelnen Wohnviertel und Gemeinden tragen unterschiedlich zum Steuerertrag des Kantons bei. Dies liegt einerseits an der grösseren Anzahl an Steuerpflichtigen (zum Beispiel Gundeldingen, St. Johann, Riehen), andererseits am höheren durchschnittlichen Ertrag pro Veranlagung (zum Beispiel Bruderholz oder St. Alban). Den höchsten Ertrag aus Einkommenssteuer (einschliesslich Gemeindesteuer) für das Steuerjahr 2022 weist Riehen mit rund 179 Mio. Franken aus. Für den ganzen Kanton beträgt der Wert 1,3 Mrd. Franken, 24% mehr als im Jahr 2013.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Ertrag aus Einkommenssteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.2.8",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_208",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-10T09:02:33",
		"id": 22358
	},
	{
		"template": "template001",
		"data-id": 22359,
		"chart-id": 22359,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Ertrag aus Vermögenssteuer",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Die einzelnen Wohnviertel und Gemeinden tragen unterschiedlich zum Steuerertrag des Kantons bei. Dies liegt einerseits an der grösseren Anzahl an Steuerpflichtigen (zum Beispiel Gundeldingen, St. Johann, Riehen), andererseits am höheren durchschnittlichen Ertrag pro Veranlagung (zum Beispiel Bruderholz oder St. Alban). Der höchste Wert für die Vermögenssteuer 2022 liegt mit ca. 64 Mio. Franken im Wohnviertel Vorstädte vor. Insgesamt beträgt der Ertrag einschliesslich Gemeindesteuer rund 333 Mio. Franken, ca. 19% mehr als im Jahr 2013.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Ertrag aus Vermögenssteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.2.9",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_209",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-10T09:02:34",
		"id": 22359
	},
	{
		"template": "template001",
		"data-id": 22421,
		"chart-id": 22421,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Veranlagungen Quellensteuerpflichtige",
		"subtitle": "",
		"lesehilfe": "Im Jahr 2023 gab es insgesamt rund 27 600 Veranlagungen von quellensteuerpflichtigen Personen, die in Basel-Stadt wohnten; die meisten in den Wohnvierteln Matthäus und St. Johann mit jeweils über 2 700 Veranlagungen.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Quellensteuerdaten Basel-Stadt. Ausländische Personen ohne Niederlassungsbewilligung mit Wohnsitz im Kanton unterliegen einem Steuerabzug auf Einkommen aus unselbstständiger Erwerbstätigkeit. Daneben gibt es weitere Fälle, wo Quellensteuer entrichtet werden muss (zum Beispiel bei Kapitalabfindungen). Bei Einkommen über 120 000 Franken erfolgt eine nachträgliche ordentliche Veranlagung, wodurch Doppelzählungen entstehen. 2022 betraf dies rund 7 100 Fälle (ca. 6% der 119 000 ordentlichen Veranlagungen), die sowohl in den Auswertungen der ordentlichen Veranlagungen als auch in jenen zur Quellensteuer enthalten sind.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Anzahl Veranlagungen Quellensteuerpflichtige",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.4.1",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.4 Quellensteuer",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_04_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-10T09:02:37",
		"id": 22421
	},
	{
		"template": "template001",
		"data-id": 22422,
		"chart-id": 22422,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Quellensteuerertrag",
		"subtitle": "",
		"lesehilfe": "Im Jahr 2023 betrug der Ertrag aus Quellensteuer in Basel-Stadt 546 Mio. Franken, 34% mehr als 2014. Der höchste Ertrag 2023 liegt mit rund 37 Mio. Franken im Wohnviertel St. Alban vor.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Quellensteuerdaten Basel-Stadt. Ausländische Personen ohne Niederlassungsbewilligung mit Wohnsitz im Kanton unterliegen einem Steuerabzug auf Einkommen aus unselbstständiger Erwerbstätigkeit. Daneben gibt es weitere Fälle, wo Quellensteuer entrichtet werden muss (zum Beispiel bei Kapitalabfindungen). Bei Einkommen über 120 000 Franken erfolgt eine nachträgliche ordentliche Veranlagung, wodurch Doppelzählungen entstehen. 2022 betraf dies rund 7 100 Fälle (ca. 6% der 119 000 ordentlichen Veranlagungen), die sowohl in den Auswertungen der ordentlichen Veranlagungen als auch in jenen zur Quellensteuer enthalten sind. Die Quellensteuerauswertungen beinhalten auch den Anteil, der an den Bund fliesst, im Steuerjahr 2023 rund 110 Mio. Franken.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Quellensteuerertrag",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.4.2",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.4 Quellensteuer",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_04_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-10T09:02:38",
		"id": 22422
	},
	{
		"template": "template001",
		"data-id": 22423,
		"chart-id": 22423,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Veranlagungen juristischer Personen",
		"subtitle": "",
		"lesehilfe": "Die Anzahl der Veranlagungen von juristischen Personen hat im Zehnjahresvergleich um 18% zugenommen. 2021 gab es rund 12 700.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von juristischen Personen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Veranlagungen juristischer Personen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.5.1",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.5 Juristische Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_05_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-10T09:02:40",
		"id": 22423
	},
	{
		"template": "template001",
		"data-id": 22424,
		"chart-id": 22424,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Steuerbetreibungen",
		"subtitle": "",
		"lesehilfe": "Für das Steuerjahr 2020 wurden rund 5 400 Betreibungen eingeleitet. Der durchschnittliche Betreibungsbetrag lag bei 4 600 Franken. In den letzten zehn Jahren ging die Zahl der Steuerbetreibungen um 23% zurück.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Steuerbetreibungen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.6.1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-10T09:02:46",
		"id": 22424
	},
	{
		"template": "template001",
		"data-id": 22425,
		"chart-id": 22425,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Steuererlasse",
		"subtitle": "",
		"lesehilfe": "Die Zahl der Steuererlasse ging kontinuierlich zurück. Im Steuerjahr 2020 gab es 534 Steuererlasse, der durchschnittliche Erlassbetrag lag bei 2 700 Franken.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Steuererlasse",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.6.2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-10T09:02:47",
		"id": 22425
	},
	{
		"template": "line001",
		"data-id": 6896,
		"chart-id": 6896,
		"filter": "",
		"parentId": null,
		"children": [
			9315
		],
		"title": "Zusammensetzung der Gesamteinnahmen",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Die Gesamteinnahmen des Kantons betragen 2022 rund 4,8  Mrd. Franken. Die Werte sind dem Jahresbericht des Kantons entnommen und nach dem Mittelfluss pro Kalenderjahr dargestellt. 2022 beträgt der Ertrag aus Einkommens- und Vermögenssteuern rund 2,0 Mrd. Franken (6,6% mehr als im Vorjahr), der Anteil dieses Steuerertrags am Gesamtertrag des Kantons beträgt rund 41%.",
		"erlaeuterungen": "Der Jahresbericht des Kantons Basel-Stadt weist Erträge aus, die während eines Kalenderjahres verbucht wurden. Dies unterscheidet sich somit von der Steuerstatistik Basel-Stadt, der Veranlagungsdaten zugrundeliegen, die auf ein bestimmtes Steuerjahr bezogen sind – unabhängig davon, in welchem Jahr die Steuer verbucht oder bezahlt worden ist. NP = Natürliche Personen; JP = Juristische Personen.",
		"quellenangabe": [
			"Jahresbericht des Kantons Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zusammensetzung der Gesamteinnahmen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06896",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.1.1",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.1 Ertrag des Kantons",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_101",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-10T09:02:16",
		"id": 6896
	},
	{
		"template": "line001",
		"data-id": 6897,
		"chart-id": 6897,
		"filter": "",
		"parentId": null,
		"children": [
			9316
		],
		"title": "Entwicklung des Ertrags aus Steuern",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Grössere Schwankungen liegen vor allem bei der Gewinnsteuer der juristischen Personen vor, zwischen 2013 und 2021 ist dieser Wert nominal um rund 12% gesunken. Bei den natürlichen Personen ist der Ertrag aus Einkommenssteuer von 2013 bis 2022 um 24% gestiegen, der Ertrag aus Vermögenssteuer um 19%. Der Ertrag aus Quellenbesteuerung (2024) stieg seit 2015 im Zehnjahresvergleich um 34%.",
		"erlaeuterungen": "Bei der Steuerstatistik Basel-Stadt liegen Veranlagungsdaten zugrunde, die auf ein bestimmtes Steuerjahr bezogen sind – unabhängig davon, in welchem Jahr die Steuer verbucht oder bezahlt worden ist. Zum Zeitpunkt des Exports der Steuerdaten für statistische Zwecke sind in der Regel mindestens rund 98% der Veranlagungen von natürlichen Personen des Steuerjahres bearbeitet. Veränderungen gegenüber dem Vorjahr können zu einem Teil auch aufgrund des unterschiedlichen Bearbeitungsstandes entstehen. Das jeweils neuste zur Verfügung stehende Jahr unterscheidet sich je nach Steuerart.",
		"quellenangabe": [
			"Jahresbericht des Kantons Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung des Ertrags aus Steuern",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06897",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.1.2",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.1 Ertrag des Kantons",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_01_00_00_00_102",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-11-28T11:26:56",
		"id": 6897
	},
	{
		"template": "pie001",
		"data-id": 6898,
		"chart-id": 6898,
		"filter": "",
		"parentId": null,
		"children": [
			9317
		],
		"title": "Veranlagungen natürlicher Personen",
		"subtitle": "Basel-Stadt, 2022",
		"lesehilfe": "Im Jahr 2022 gibt es insgesamt 118 596 Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen und wohnhaften Personen. Nicht berücksichtigt sind Veranlagungen von Auswärtigen (insgesamt rund 8 500 Veranlagungen) und von Unterjährigen (ca. 4 800 Veranlagungen). Nach Tarif betrachtet stammen rund 81 000 Veranlagungen von Alleinstehenden, 31 000 von Verheirateten und ca. 7 000 von Alleinstehenden mit Kind oder einer anderen unterstützten Person.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter. Zum Zeitpunkt des Exports der Steuerdaten für statistische Zwecke sind in der Regel mindestens rund 98% der Veranlagungen von natürlichen Personen des Steuerjahres bearbeitet. Veränderungen gegenüber dem Vorjahr können zu einem Teil auch aufgrund des unterschiedlichen Bearbeitungsstandes entstehen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Veranlagungen natürlicher Personen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06898",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.2.1",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_201",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-11-27T12:26:53",
		"id": 6898
	},
	{
		"template": "line001",
		"data-id": 6899,
		"chart-id": 6899,
		"filter": "",
		"parentId": null,
		"children": [
			9318
		],
		"title": "Summe von Reineinkommen, -vermögen und Steuerertrag",
		"subtitle": "indexiert (2013 = 100), Basel-Stadt",
		"lesehilfe": "Die grössten Schwankungen seit 2013 zeigt das Reinvermögen, das seitdem nominal um rund 25% gewachsen ist. Das Reineinkommen stieg um rund 18%. Der Ertrag aus Einkommens- und Vermögenssteuer lag 2022 um ca. 23% über dem Wert von 2013. Der in manchen Jahren grössere Anstieg des Reinvermögens liegt unter anderem am steigenden Wert von Kapitalanlagen bzw. Wertschriften. Ein weiterer Grund für die Schwankungen kann auch der Bearbeitungsstand der Veranlagungen sein (siehe Erläuterungen und methodische Hinweise).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter. Zum Zeitpunkt des Exports der Steuerdaten für statistische Zwecke sind in der Regel mindestens rund 98% der Veranlagungen von natürlichen Personen des Steuerjahres bearbeitet. Veränderungen gegenüber dem Vorjahr können zu einem Teil auch aufgrund des unterschiedlichen Bearbeitungsstandes entstehen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Summe von Reineinkommen, -vermögen und Steuerertrag",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06899",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.2.2",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_202",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-11-28T11:26:58",
		"id": 6899
	},
	{
		"template": "line001",
		"data-id": 6901,
		"chart-id": 6901,
		"filter": "",
		"parentId": null,
		"children": [
			9320
		],
		"title": "Mittelwert des Reineinkommens",
		"subtitle": "in Franken, Basel-Stadt, 2013 und 2022",
		"lesehilfe": "In den meisten Wohnvierteln ist ein Anstieg des Mittelwertes pro Veranlagung im Vergleich zum Steuerjahr 2013 zu verzeichnen. Am relativ stärksten fällt er im Wohnviertel Vorstädte und in der Gemeinde Bettingen aus, mit jeweils über 50%. Der Mittelwert des Reineinkommens aller Veranlagungen im Kanton stieg um rund 14%.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter. Zum Zeitpunkt des Exports der Steuerdaten für statistische Zwecke sind in der Regel mindestens rund 98% der Veranlagungen von natürlichen Personen des Steuerjahres bearbeitet. Veränderungen gegenüber einem anderen Jahr können zu einem Teil auch aufgrund des unterschiedlichen Bearbeitungsstandes entstehen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittelwert des Reineinkommens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06901",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.2.3",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_203",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-11-27T12:27:01",
		"id": 6901
	},
	{
		"template": "line001",
		"data-id": 6902,
		"chart-id": 6902,
		"filter": "",
		"parentId": null,
		"children": [
			9321
		],
		"title": "Median des Reineinkommens",
		"subtitle": "in Franken, Basel-Stadt, 2013 und 2022",
		"lesehilfe": "Der Median des Reineinkommens pro Veranlagung ist zwischen 2013 und 2022 in fast allen Wohnvierteln gestiegen. Den stärksten relativen Zuwachs gibt es im Wohnviertel Rosental (+20,3%). Den grössten Rückgang verzeichnet das Wohnviertel Kleinhüningen (-2,5%). Der Median des Reineinkommens aller Veranlagungen im gesamten Kanton stieg um 6,0%.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter. Zum Zeitpunkt des Exports der Steuerdaten für statistische Zwecke sind in der Regel mindestens rund 98% der Veranlagungen von natürlichen Personen des Steuerjahres bearbeitet. Veränderungen gegenüber einem anderen Jahr können zu einem Teil auch aufgrund des unterschiedlichen Bearbeitungsstandes entstehen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Median des Reineinkommens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06902",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.2.4",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_204",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-11-27T12:27:02",
		"id": 6902
	},
	{
		"template": "line001",
		"data-id": 6904,
		"chart-id": 6904,
		"filter": "",
		"parentId": null,
		"children": [
			9323
		],
		"title": "Mittelwert des Reinvermögens",
		"subtitle": "in Franken, Basel-Stadt, 2013 und 2022",
		"lesehilfe": "Den höchsten Mittelwert des Reinvermögens pro Veranlagung weist im Jahr 2022 mit ca. 3,4 Mio. Franken das Wohnviertel Vorstädte auf, gefolgt von der Gemeinde Bettingen mit rund 2,8 Mio. Franken. 2013 lag der höchste Wert im Wohnviertel Bruderholz vor.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittelwert des Reinvermögens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06904",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.2.5",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_205",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-10T09:02:29",
		"id": 6904
	},
	{
		"template": "line001",
		"data-id": 6905,
		"chart-id": 6905,
		"filter": "",
		"parentId": null,
		"children": [
			8318,
			8589,
			9324
		],
		"title": "Median des Reinvermögens",
		"subtitle": "in Franken, Basel-Stadt, 2013 und 2022",
		"lesehilfe": "Der höchste Median des Reinvermögens 2022 wird mit rund 83 100 Franken in der Einwohnergemeinde Bettingen verzeichnet. Auch 2013 wurde der höchste Wert dort registriert.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Median des Reinvermögens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06905",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.2.6",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_206",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-10T09:02:30",
		"id": 6905
	},
	{
		"template": "befragungen001",
		"data-id": 6907,
		"chart-id": 6907,
		"filter": "",
		"parentId": null,
		"children": [
			9326
		],
		"title": "Veranlagungen und Summe Einkommenssteuer nach Stufen des steuerbaren Einkommens",
		"subtitle": "in Franken, Basel-Stadt, 2022",
		"lesehilfe": "Bei rund 28 300 aller Veranlagungen (ca. 24%) im Steuerjahr 2022 beträgt das steuerbare Einkommen 0 Franken, somit muss keine Einkommenssteuer bezahlt werden. Von Veranlagungen mit einem steuerbaren Einkommen von 200 000 Franken und mehr (ca. 4 400 oder rund 4% aller Veranlagungen) stammt ein Einkommenssteuerertrag von rund 465 Mio. Franken (ca. 35% des Einkommenssteuertrags).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter. Zum Zeitpunkt des Exports der Steuerdaten für statistische Zwecke sind in der Regel mindestens rund 98% der Veranlagungen von natürlichen Personen des Steuerjahres bearbeitet. Veränderungen gegenüber dem Vorjahr können zu einem Teil auch aufgrund des unterschiedlichen Bearbeitungsstandes entstehen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Veranlagungen und Summe Einkommenssteuer nach Stufen des steuerbaren Einkommens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06907",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.2.11",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_211",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-11-27T12:26:55",
		"id": 6907
	},
	{
		"template": "befragungen001",
		"data-id": 6908,
		"chart-id": 6908,
		"filter": "",
		"parentId": null,
		"children": [
			9327
		],
		"title": "Veranlagungen und Summe Vermögenssteuer nach Stufen des steuerbaren Vermögens",
		"subtitle": "in Franken, Basel-Stadt, 2022",
		"lesehilfe": "Bei der Vermögenssteuer sind die Anteile der Vermögensklassen weniger gleichmässig verteilt als bei der Einkommenssteuer. Bei rund 82 700 aller Veranlagungen (rund 70%) im Steuerjahr 2022 beträgt das steuerbare Vermögen 0 Franken, somit muss keine Vermögenssteuer bezahlt werden. Bei rund 3 300 Veranlagungen (ca. 3%) mit einem steuerbaren Vermögen von 2 Mio. Franken und mehr beträgt die Vermögenssteuer insgesamt rund 275 Mio. Franken (82% des gesamten Vermögenssteuerertrags).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter. Zum Zeitpunkt des Exports der Steuerdaten für statistische Zwecke sind in der Regel mindestens rund 98% der Veranlagungen von natürlichen Personen des Steuerjahres bearbeitet. Veränderungen gegenüber dem Vorjahr können zu einem Teil auch aufgrund des unterschiedlichen Bearbeitungsstandes entstehen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Veranlagungen und Summe Vermögenssteuer nach Stufen des steuerbaren Vermögens",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06908",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.2.12",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_212",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-11-27T12:26:56",
		"id": 6908
	},
	{
		"template": "line001",
		"data-id": 6909,
		"chart-id": 6909,
		"filter": "",
		"parentId": null,
		"children": [
			9328
		],
		"title": "Gesamtertrag aus Einkommens- und Vermögenssteuer",
		"subtitle": "in Franken, Basel-Stadt, 2013 und 2022",
		"lesehilfe": "Den höchsten Ertrag aus Einkommens- und Vermögenssteuer 2022 verzeichnet die Gemeinde Riehen mit rund 238 Mio. Franken (ca. +27% gegenüber 2013), gefolgt vom Wohnviertel Bruderholz mit ca. 170 Mio. Franken (ca. -13%). Den kleinsten Ertrag steuert Kleinhüningen mit rund 8 Mio. Franken bei (ca. -8%). Im Jahr 2022 beträgt der Wert für den gesamten Kanton rund 1,7 Mrd. Franken, ca. 23% mehr als 2013.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von ganzjährig in Basel-Stadt steuerpflichtigen Personen; ohne Auswärtige und ohne Wochenaufenthalter. Zum Zeitpunkt des Exports der Steuerdaten für statistische Zwecke sind in der Regel mindestens rund 98% der Veranlagungen von natürlichen Personen des Steuerjahres bearbeitet. Veränderungen gegenüber einem anderen Jahr können zu einem Teil auch aufgrund des unterschiedlichen Bearbeitungsstandes entstehen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Gesamtertrag aus Einkommens- und Vermögenssteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06909",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.2.13",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.2 Ordentliche Veranlagung natürlicher Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_213",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-11-27T12:26:58",
		"id": 6909
	},
	{
		"template": "line001",
		"data-id": 6910,
		"chart-id": 6910,
		"filter": "",
		"parentId": null,
		"children": [
			9329
		],
		"title": "Summe des Ertrags aus Einkommens- und Vermögenssteuer von Zugezogenen und Weggezogenen",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Für jedes betrachtete Jahr liegt ein positiver Saldo des Steuerertrags von Zuzügern und Wegzügern vor. 2022 beträgt er 1,4 Mio. Franken. Bei der Einkommenssteuer ergibt sich ein Plus von rund 1,4 Mio. Franken, bei der Vermögenssteuer ein Plus von 90 000 Franken. Von Zuzügern liegen für das Steuerjahr 2022 rund 4 800 Veranlagungen vor, von Wegzügern des Vorjahres 4 600 Veranlagungen.",
		"erlaeuterungen": "Die Untersuchung des Wanderungseffekts folgt einer eigenen Methodik. Sie wird dadurch erschwert, dass seit der Steuerharmonisierung 2002 der Wohnsitz am 31. Dezember für die Steuerpflicht entscheidend ist. Für Wegzüger liegen daher keine Daten zum Wegzugsjahr vor, sondern nur jene des Vorjahres. Bei Zugezogenen und ganzjährig Niedergelassenen wurden hingegen die Daten des jeweiligen Steuerjahres verwendet. Für einen Zuzug gilt der Zeitpunkt, wenn eine Niederlassungbewilligung erteilt wird, da ausländische Personen ohne Niederlassungsbewilligung meist quellenbesteuert werden. Quellensteuerpflichtige werden nur berücksichtigt, wenn sie nachträglich ordentlich veranlagt werden, etwa bei Einkommen über 120 000 Franken.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Summe des Ertrags aus Einkommens- und Vermögenssteuer von Zugezogenen und Weggezogenen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06910",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.3.1",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.3 Wanderung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_301",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-10T09:02:35",
		"id": 6910
	},
	{
		"template": "template001",
		"data-id": 6912,
		"chart-id": 6912,
		"filter": "",
		"parentId": null,
		"children": [
			9331
		],
		"title": "Quellensteuerertrag nach Status",
		"subtitle": "in Franken, Basel-Stadt, 2014 und 2023",
		"lesehilfe": "Die bedeutendsten Erträge aus Quellenbesteuerung stammen aus Erwerbseinkommen (ohne Grenzgänger); 2023 sind dies rund 397 Mio. Franken. Dies entspricht einem Anstieg von ca. 53% gegenüber 2014. Der Ertrag der Grenzgänger aus Deutschland u. a. (einschliesslich einige wenige aus anderen Staaten) beträgt 2023 insgesamt 87 Mio. Franken. Die meisten Grenzgänger aus Frankreich zahlen keine direkte Quellensteuer in Basel-Stadt. Für sie gibt es einen sog. Fiskalausgleich, den es aus Frankreich für sie gibt. Insgesamt beträgt der Quellensteuerertrag 2023 rund 546 Mio. Franken und liegt damit ähnlich hoch wie im Jahr zuvor. Gegenüber 2014 ist er um 43% gestiegen.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Quellensteuerdaten Basel-Stadt. Ausländische Personen ohne Niederlassungsbewilligung mit Wohnsitz im Kanton unterliegen einem Steuerabzug auf Einkommen aus unselbstständiger Erwerbstätigkeit. Daneben gibt es weitere Fälle, wo Quellensteuer entrichtet werden muss (zum Beispiel bei Kapitalabfindungen). Bei Einkommen über 120 000 Franken erfolgt eine nachträgliche ordentliche Veranlagung, wodurch Doppelzählungen entstehen. 2022 betraf dies rund 7 100 Fälle (ca. 6% der 119 000 ordentlichen Veranlagungen), die sowohl in den Auswertungen der ordentlichen Veranlagungen als auch in jenen zur Quellensteuer enthalten sind. Die Quellensteuerauswertungen beinhalten auch den Anteil, der an den Bund fliesst, im Steuerjahr 2023 rund 110 Mio. Franken.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Quellensteuerertrag nach Status",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06912",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.4.3",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.4 Quellensteuer",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_04_00_00_00_402",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-10T09:02:39",
		"id": 6912
	},
	{
		"template": "template001",
		"data-id": 6981,
		"chart-id": 6981,
		"filter": "",
		"parentId": null,
		"children": [
			9333
		],
		"title": "Gewinn-, Kapital- und Grundstücksteuer",
		"subtitle": "in Franken, Basel-Stadt",
		"lesehilfe": "Der Steuerertrag aus Gewinn-, Kapital- und Grundstücksteuer beträgt 2021 bei den rund 12 700 Veranlagungen zusammen 623 Mio. Franken. Die bedeutendste Steuerart, die Gewinnsteuer, trägt 503  Mio. dazu bei. Die Kapitalsteuer beträgt  rund 91 Mio. Franken, die Grundstücksteuer 29 Mio. Franken.",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von juristischen Personen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Gewinn-, Kapital- und Grundstücksteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06981",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.5.2",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.5 Juristische Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_05_00_00_00_501",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-10T09:02:42",
		"id": 6981
	},
	{
		"template": "befragungen001",
		"data-id": 6982,
		"chart-id": 6982,
		"filter": "",
		"parentId": null,
		"children": [
			9334
		],
		"title": "Steuerertrag juristischer Personen nach Stufen der Gesamtsteuer",
		"subtitle": "in Franken, Basel-Stadt, 2021",
		"lesehilfe": "Im Jahr 2021 gibt es insgesamt rund 12 700 Veranlagungen von juristischen Personen im Kanton Basel-Stadt. Rund 1 100 (9%) von ihnen müssen keine Gewinn-, Kapital- oder Grundstücksteuer bezahlen. Bei der grossen Mehrheit (rund 9 100 Veranlagungen bzw. 71%) liegt der Steuerbetrag zwischen 1 und 4 999 Franken. Ihr Ertrag beläuft sich insgesamt auf 6,5 Mio. Franken. In der obersten Kategorie – mit einem Steuerbetrag von über 1 Mio. Franken pro Veranlagung – gibt es 50 Veranlagungen. Ihr Ertrag beträgt rund 623 Mio. Franken (81% des gesamten Steuerertrags der juristischen Personen).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von juristischen Personen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Steuerertrag juristischer Personen nach Stufen der Gesamtsteuer",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06982",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.5.3",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.5 Juristische Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_05_00_00_00_502",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-10T09:02:43",
		"id": 6982
	},
	{
		"template": "befragungen001",
		"data-id": 6983,
		"chart-id": 6983,
		"filter": "",
		"parentId": null,
		"children": [
			9335
		],
		"title": "Steuerertrag juristischer Personen nach Stufen des steuersatzbestimmenden Gewinns",
		"subtitle": "in Franken, Basel-Stadt, 2021",
		"lesehilfe": "Mehr als die Hälfte (rund 55%) der juristischen Personen weist 2021 einen steuersatzbestimmenden Gewinn von 0 Franken auf. Juristische Personen, die keine Gewinnsteuer entrichten müssen, zahlen in der Regel als Alternativsteuer die Grundstücksteuer. Von dieser Gruppe stammen insgesamt 27 Mio. Franken, dies sind 4% des Gesamtertrags. Am anderen Ende tragen insgesamt 682 Veranlagungen von juristischen Personen (5%) mit einem satzbestimmenden Gewinn von über 1 Mio. Franken einen Steuerbetrag von zusammen 564 Mio. Franken bei (90% der gesamten Steuer der juristischen Personen).",
		"erlaeuterungen": "Grundlage der Auswertungen sind die Veranlagungen von juristischen Personen.",
		"quellenangabe": [
			"Steuerstatistik Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Steuerertrag juristischer Personen nach Stufen des steuersatzbestimmenden Gewinns",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.06983",
		"kennzahlenset": "Steuern",
		"kuerzelKunde": "2.5.4",
		"stufe1": "2 Kernindikatoren",
		"stufe2": "2.5 Juristische Personen",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_05_00_00_00_503",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-10-10T09:02:44",
		"id": 6983
	}
];