var indikatorensetData = [
	{
		"template": "template001_print",
		"data-id": 7972,
		"chart-id": 7972,
		"filter": "",
		"parentId": "6537",
		"children": [],
		"title": "Geöffnete Betriebe nach Hotelkategorie",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2021 waren im Kanton Basel-Stadt 66 Hotelbetriebe an mindestens einem Tag des Jahres geöffnet. Von diesen gehörten 20 Betriebe zur Kategorie der 4- oder 5-Sterne-Hotels, 25 Betriebe zur Kategorie der 3-Sterne-Hotels und 9 Betriebe zu den 1- und 2-Sterne-Hotels. 12 der geöffneten Hotels waren nicht klassiert.",
		"erlaeuterungen": "Anzahl der im Erhebungsjahr während mindestens einem Tag geöffneten Hotels, Appartementhäuser, Hostels, Jugendherbergen, Backpackers und B&Bs, deren Merkmale den Kriterien der NOGA (Allgemeine Systematik der Wirtschaftszweige) für Hotels und ähnliche Unterkünfte weitgehend entsprechen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Geöffnete Betriebe nach Hotelkategorie",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07972",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "Abb. 2.1",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:01:27",
		"id": 7972
	},
	{
		"template": "template001_print",
		"data-id": 7973,
		"chart-id": 7973,
		"filter": "",
		"parentId": "6538",
		"children": [],
		"title": "Durchschnittliche Betriebsgrösse",
		"subtitle": "in Zimmern, Basel-Stadt",
		"lesehilfe": "Betriebe mit 4 oder 5 Sternen boten 2021 im Durchschnitt 77 Zimmer an, 3-Sterne-Häuser im Schnitt 63 Zimmer. Die durchschnittliche Betriebsgrösse lag bei den Betrieben der 4 und 5-Sterne-Kategorie unter dem Durchschnitt der Jahre 2012 bis 2021. Bei allen anderen Kategorien lag die Zahl der Zimmer je Betrieb hingegen über dem Zehnjahresschnitt.",
		"erlaeuterungen": "Als durchschnittliche Betriebsgrösse wird die Anzahl Zimmer je Betrieb bezeichnet. 2019 wurde die Berechnung der Anzahl verfügbarer Zimmer an die Methodik des BFS angeglichen. Für den Jahresvergleich wurde die Berechnung für 2012 rückwirkend angepasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Durchschnittliche Betriebsgrösse",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07973",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "Abb. 2.2",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:01:32",
		"id": 7973
	},
	{
		"template": "template001_print",
		"data-id": 7974,
		"chart-id": 7974,
		"filter": "",
		"parentId": "6539",
		"children": [],
		"title": "Anzahl Zimmer und Auslastung nach Hotelkategorie",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2021 standen den Gästen der Basler Hotellerie insgesamt 4 146 Zimmer zur Verfügung. Davon entfielen 1 549 Zimmer auf Betriebe mit 4 oder 5 Sternen und 1 580 auf die Kategorie der 3-Sterne-Hotels. Die Anzahl verfügbarer Zimmer liegt 2021 unter dem Stand von vor zehn Jahren. Die Nettozimmerauslastung nahm gegenüber 2012 in allen Kategorien ab, insgesamt resultierte ein Minus von 25,2 Prozentpunkten.",
		"erlaeuterungen": "Die Nettozimmerauslastung gibt an, wie oft ein Zimmer an den Tagen belegt war, an denen der Betrieb geöffnet war, und das Zimmer zur Verfügung stand. 2019 wurde die Berechnung der Anzahl verfügbarer Zimmer an die Methodik des BFS angeglichen. Für den Jahresvergleich wurde die Berechnung für 2012 rückwirkend angepasst. Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Zimmer und Auslastung nach Hotelkategorie",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07974",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "Abb. 2.3",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:01:32",
		"id": 7974
	},
	{
		"template": "line001_print",
		"data-id": 7975,
		"chart-id": 7975,
		"filter": "",
		"parentId": "6540",
		"children": [],
		"title": "Nettozimmerauslastung nach Wochentag",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Nach weitgehender Kontinuität in den Jahren 2012 bis 2019 sank die durchschnittliche Nettozimmerauslastung 2020 deutlich. 2021 erholte sie sich über die gesamte Woche hinweg betrachtet um 6,6% und liegt im Berichtsjahr bei 35,0%. Lag die durchschnittliche Nettozimmerauslastung von Montag bis Donnerstag 2020 bei 31,1%, schliesst sie 2021 bei 34,5%. Von Freitag bis Sonntag lag die Nettozimmerauslastung im Jahr 2020 bei durchschnittlich 24,8%, 2021 bei 35,7%.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettozimmerauslastung nach Wochentag",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07975",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "Abb. 2.4",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:01:33",
		"id": 7975
	},
	{
		"template": "line001_print",
		"data-id": 7976,
		"chart-id": 7976,
		"filter": "",
		"parentId": "6541",
		"children": [],
		"title": "Hotelbetriebe und Anzahl Betten",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2021 boten die 66 baselstädtischen Hotels insgesamt 8 476 Betten an. Im Jahr 2020 waren es 8 011 Betten in ebenfalls 66 Hotelbetrieben. Dies entspricht einer Zunahme um 464 Betten. In der Erhebung von 1936 gab es in 42 Betrieben insgesamt 2 225 Betten.",
		"erlaeuterungen": "Seit 2016 werden bei allen Hotels die Doppelbetten, welche eine Schlafgelegenheit für zwei Personen anbieten, als zwei Betten in der Statistik aufgeführt. Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Hotelbetriebe und Anzahl Betten",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07976",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "Abb. 2.5",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:01:33",
		"id": 7976
	},
	{
		"template": "template001_print",
		"data-id": 7977,
		"chart-id": 7977,
		"filter": "",
		"parentId": "6542",
		"children": [],
		"title": "Verfügbare Betten nach Hotelkategorie",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2021 standen den Gästen in den baselstädtischen Hotels insgesamt 8 476 Betten zur Verfügung. Gegenüber 2020 bedeutet dies eine Zunahme um 5,8% bzw. 464 Betten. Von den im Jahr 2021 verfügbaren Betten entfielen 2 961 auf Betriebe mit 4 oder 5 Sternen, 3 122 auf die 3-Sterne-Hotels. Die Bettenzahl nahm in den beiden höchsten Kategorien gegenüber 2020 um 125 bzw. 4,1% ab. Bei den 3-Sterne-Betrieben resultierte eine Zunahme um 320 Betten bzw. 11,4%.",
		"erlaeuterungen": "Seit 2016 werden bei allen Hotels die Doppelbetten, welche eine Schlafgelegenheit für zwei Personen anbieten, als zwei Betten in der Statistik aufgeführt. 2019 wurde die Berechnung der Anzahl verfügbarer Betten an die Methodik des BFS angeglichen. Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Verfügbare Betten nach Hotelkategorie",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07977",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "Abb. 2.6",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:01:34",
		"id": 7977
	},
	{
		"template": "line001_print",
		"data-id": 7978,
		"chart-id": 7978,
		"filter": "",
		"parentId": "6543",
		"children": [],
		"title": "Mittlere Aufenthaltsdauer pro Jahr",
		"subtitle": "in Tagen, Basel-Stadt",
		"lesehilfe": "2021 verweilten die Gäste durchschnittlich 1,78 Tage in einem der Hotelbetriebe des Kantons Basel-Stadt. Schweizer Gäste blieben mit 1,66 Tagen durchschnittlicher Aufenthaltsdauer weniger lange als Gäste aus dem Ausland mit durchschnittlich 1,93 Tagen. Bis in die frühen 1990er-Jahre war dieses Verhältnis umgekehrt, mit Ausnahme der Kriegsjahre 1940, 1941, 1942 und 1944.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittlere Aufenthaltsdauer pro Jahr",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07978",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "Abb. 2.7",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:01:34",
		"id": 7978
	},
	{
		"template": "line001_print",
		"data-id": 7979,
		"chart-id": 7979,
		"filter": "",
		"parentId": "6544",
		"children": [],
		"title": "Mittlere Aufenthaltsdauer pro Monat",
		"subtitle": "in Tagen, Basel-Stadt, 2021",
		"lesehilfe": "Am längsten verweilten Inlandgäste im Monat Januar mit durchschnittlich 2,23 Tagen in baselstädtischen Hotels. Die längste Aufenthaltsdauer bei den ausländischen Gästen wurde mit 2,52 Tagen im April registriert. Die kürzeste Aufenthaltsdauer der Schweizer Gäste wurde mit durchschnittlich 1,44 Tagen im Dezember verzeichnet. Bei den Gästen aus dem Ausland resultierte die mit 1,65 Tagen kürzeste durchschnittliche Aufenthaltsdauer im August.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittlere Aufenthaltsdauer pro Monat",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07979",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "Abb. 2.8",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:01:35",
		"id": 7979
	},
	{
		"template": "template001_print",
		"data-id": 7980,
		"chart-id": 7980,
		"filter": "",
		"parentId": "6545",
		"children": [],
		"title": "Logiernächte pro Monat nach Herkunft der Gäste",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "In den Monaten August und September lag die Anzahl Logiernächte insgesamt über den Mittelwerten der letzten zehn Jahre, in allen anderen Monaten des Jahres 2021 darunter. Während bei den inländischen Gästen die Zahl der Logiernächte von April bis Dezember den jeweiligen Monatsdurchschnitt der letzten zehn Jahre übertraf, resultierte bei den ausländischen Gästen jeden Monat ein tieferer Wert. Im September war die Anzahl Logiernächte des Jahres 2021 mit 105 617 insgesamt am höchsten.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Logiernächte pro Monat nach Herkunft der Gäste",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07980",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "Abb. 2.10",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:01:28",
		"id": 7980
	},
	{
		"template": "line001_print",
		"data-id": 7981,
		"chart-id": 7981,
		"filter": "",
		"parentId": "6546",
		"children": [],
		"title": "Logiernächte nach Herkunft der Gäste",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Nach einem Höchststand von 1,42 Millionen Übernachtungen im Jahr 2019 brach die Anzahl Logiernächte 2020 auf 545 906 Übernachtungen ein. Das Jahr 2021 schloss bei 784 607 Logiernächten, das sind 238 701 bzw. 43,7% mehr als 2020. Gäste aus der Schweiz übernachteten im Berichtsjahr 401 814 Mal in einem baselstädtischen Hotel, 2020 waren es 279 513. Dies entspricht einem Plus von 122 301 Logiernächten oder 43,8%. Gäste aus dem Ausland logierten 2021 insgesamt 382 793 Mal in einem Hotel in Basel-Stadt, 2020 waren es 266 393. Hier beträgt der Zuwachs 116 400 Logiernächte bzw. 43,7%.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Logiernächte nach Herkunft der Gäste",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07981",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "Abb. 2.11",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:01:28",
		"id": 7981
	},
	{
		"template": "line001_print",
		"data-id": 7982,
		"chart-id": 7982,
		"filter": "",
		"parentId": "6547",
		"children": [],
		"title": "Logiernächte nach Herkunft der Gäste",
		"subtitle": "indexiert (2012 = 100), Basel-Stadt",
		"lesehilfe": "Nachdem der Index der Anzahl Logiernächte der inländischen Gäste zwischen 2012 und 2019 um 52,1 Indexpunkte gestiegen war, sank er im Jahr 2020 deutlich auf einen Wert von 89,2. 2021 erholte sich der Index und schloss bei 128,2 Punkten. Der Index der Logiernächte der ausländischen Gäste stieg zwischen 2011 und 2019 um 23,2 Indexpunkte. Dieser Index fiel 2020 noch deutlicher und erreichte einen Wert von 34,7. Zum Jahresende 2021 schloss er bei 49,8 Punkten.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Logiernächte nach Herkunft der Gäste",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07982",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "Abb. 2.12",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:01:29",
		"id": 7982
	},
	{
		"parentId": 6549,
		"children": [],
		"template": "map_gemeinden_print",
		"title": "Anteile am Übernachtungsvolumen der aufkommensstärksten Herkunftsmärkte",
		"subtitle": "Basel-Stadt, 2020",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzel": "I.10.1.07983",
		"kuerzelKunde": "2-15",
		"description": "Anteile am Übernachtungsvolumen der aufkommensstärksten Herkunftsmärkte",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2021-02-08T08:45:20.2020",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Insgesamt haben die Hotels bei der Nachfrage nach Übernachtungen aus den zehn aufkommensstärksten Märkten im Jahr 2020 gegenüber dem Mittelwert der Jahre 2009-2013 einen Rückgang von 49,2% zu verzeichnen. Die Nachfrage aus dem heimischen Markt ist gegenüber dem Mittelwert der Jahre 2009-2013 um 10,4% zurückgegangen. Für den deutschen Markt beläuft sich das Minus bei den Logiernächten auf 53,1%, für die Vereinigten Staaten auf 81,1% und das Vereinigte Königreich auf 75,1%. Der deutsche Markt generierte mit 19,4% den grössten Wachstumsbeitrag im Beobachtungszeitraum. Die US-amerikanischen Gäste sorgten mit 16,2% für den zweithöchsten Beitrag. Auf dem dritten Rang folgt das Vereinigte Königreich mit einem Wachstumsbeitrag von 11,6%. Der einheimische Markt trug 6,2% bei.",
		"erlaeuterungen": "Als Wachstumsbeitrag bezeichnet man denjenigen Beitrag, welchen einzelne Quellmärkte zum Wachstum der gesamten Nachfrage beisteuern. Die Kreisgrösse symbolisiert den Wachstumsbeitrag der verschiedenen Herkunftsländer. Die Abbildung zeigt neben dem Wachstumsbeitrag auch die Entwicklung und den aktuellen Marktanteil der einzelnen Herkunftsmärkte. Um den Effekt von Ausreissern (z. B. aufgrund von Grossveranstaltungen, welche nicht jedes Jahr stattfinden) auszugleichen, wird anstelle des Jahreswertes 2011 der Mittelwert über die Jahre 2009-2013 als Bezugsgrösse für die Berechnung des Wachstums verwendet. Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik ab März 2020.",
		"darstellungsart": "Karte",
		"printformat": "",
		"orderKey": "01_00_00_00_00_015",
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7983,
		"chart-id": 7983,
		"filter": "",
		"id": 7983
	},
	{
		"template": "template001_print",
		"data-id": 7984,
		"chart-id": 7984,
		"filter": "",
		"parentId": "6576",
		"children": [],
		"title": "Ankünfte pro Monat nach Herkunft der Gäste",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Insgesamt 440 785 Gäste haben von Januar bis Dezember 2021 in den baselstädtischen Hotels übernachtet. Gegenüber dem Mittelwert von 2012-2021 bedeutet dies einen Rückgang um 20,4% oder 113 016 Gäste. Der ankunftsstärkste Monat war mit 61 909 Gästen der August. Davon entfielen 35 350 Ankünfte auf Gäste aus dem Ausland. Bei den Gästen aus der Schweiz war der Oktober mit 29 597 Ankünften der stärkste Monat.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Ankünfte pro Monat nach Herkunft der Gäste",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07984",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "Abb. 2.9",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:01:35",
		"id": 7984
	},
	{
		"template": "pie001_print",
		"data-id": 7985,
		"chart-id": 7985,
		"filter": "",
		"parentId": "7519",
		"children": [],
		"title": "Marktanteile am Übernachtungsvolumen",
		"subtitle": "Basel-Stadt, 2021",
		"lesehilfe": "Die Schweiz ist im Jahr 2021 mit einem Anteil von 51,2% der grösste Markt für die Basler Hotellerie. Der wichtigste ausländische Markt ist Deutschland mit einem Marktanteil von 14,7%.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Marktanteile am Übernachtungsvolumen",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07985",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "Abb. 2.13",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_013",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:01:30",
		"id": 7985
	},
	{
		"template": "template001_print",
		"data-id": 7986,
		"chart-id": 7986,
		"filter": "",
		"parentId": "7520",
		"children": [],
		"title": "Logiernächte und Marktanteile am Übernachtungsvolumen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Mit Ausnahme der Schweiz und der Niederlande war die Zahl der Logiernächte 2021 gegenüber 2012 in allen ausgewiesenen Märkten tiefer. Die Logiernächte von Gästen aus der Schweiz nahmen von 313 411 im Jahr 2012 auf 401 814 im Jahr 2021 zu. Der Marktanteil der Schweizer Gäste nahm von 29,0% auf 51,2% zu. Bei den Gästen aus Deutschland, dem mit 14,7% Marktanteil nach wie vor grössten ausländischen Markt, ging die Zahl der Übernachtungen von 178 209 im Jahr 2012 auf 115 520 im Jahr 2021 zurück.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Logiernächte und Marktanteile am Übernachtungsvolumen",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07986",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "Abb. 2.14",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_014",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:01:30",
		"id": 7986
	},
	{
		"template": "pie001_print",
		"data-id": 7987,
		"chart-id": 7987,
		"filter": "",
		"parentId": "7522",
		"children": [],
		"title": "Logiernächte nach Herkunft und Hotelkategorie",
		"subtitle": "Basel-Stadt, 2021",
		"lesehilfe": "Bei der Wahl der Hotelkategorie gab es im Jahr 2021 zwischen den aus- und inländischen Gästen kaum Unterschiede: 41% der ausländischen Touristinnen und Touristen buchten ein 4- oder 5-Sterne-Hotel, 39% bevorzugten ein 3-Sterne-Hotel. Bei den inländischen Besucherinnen und Besuchern liegen beide Werte bei 39%.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Logiernächte nach Herkunft und Hotelkategorie",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07987",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "Abb. 2.15",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_015",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:01:31",
		"id": 7987
	},
	{
		"template": "template001_print",
		"data-id": 7988,
		"chart-id": 7988,
		"filter": "",
		"parentId": "7523",
		"children": [],
		"title": "Logiernächte der Hauptmärkte nach Hotelkategorie",
		"subtitle": "Basel-Stadt, 2021",
		"lesehilfe": "Gäste aus Deutschland, dem im Jahr 2021 mit 115 520 Logiernächten grössten ausländischen Markt der Basler Hotellerie, buchten zu 39,4% eine Übernachtung in einem 3-Sterne-Hotel. 38,9% der Logiernächte von Gästen aus Deutschland entfielen auf 4- und 5-Sterne-Häuser.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Logiernächte der Hauptmärkte nach Hotelkategorie",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07988",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "Abb. 2.16",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_016",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-28T11:01:31",
		"id": 7988
	}
];