var indikatorensetData = [
	{
		"template": "template001_print",
		"data-id": 7972,
		"chart-id": 7972,
		"filter": "",
		"parentId": "6537",
		"children": [],
		"title": "Geöffnete Betriebe nach Hotelkategorie",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2022 waren 65 Hotelbetriebe an mindestens einem Tag des Jahres geöffnet. 21 Betriebe gehörten zur Kategorie der 4- und 5-Sterne-Hotels, 23 Betriebe zur Kategorie der 3-Sterne-Hotels und 8 Betriebe zu den 1- und 2-Sterne-Hotels. 13 der geöffneten Hotels waren nicht klassiert.",
		"erlaeuterungen": "Anzahl der im Erhebungsjahr während mindestens einem Tag geöffneten Hotels, Appartementhäuser, Hostels, Jugendherbergen, Backpackers und B&Bs, deren Merkmale den Kriterien der NOGA (Allgemeine Systematik der Wirtschaftszweige) für Hotels und ähnliche Unterkünfte weitgehend entsprechen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Geöffnete Betriebe nach Hotelkategorie",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07972",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "2.1",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-09T10:52:48",
		"id": 7972
	},
	{
		"template": "template001_print",
		"data-id": 7973,
		"chart-id": 7973,
		"filter": "",
		"parentId": "6538",
		"children": [],
		"title": "Durchschnittliche Betriebsgrösse",
		"subtitle": "in Zimmern, Basel-Stadt",
		"lesehilfe": "Betriebe mit 4 und 5 Sternen boten 2022 im Durchschnitt 96 Zimmer an, 3-Sterne-Häuser im Schnitt 67 Zimmer, 1- bis 2-Sterne Betriebe 69 Zimmer. Mit Ausnahme der 4- und 5-Sterne-Häuser lag 2022 die Zahl der Zimmer je Betrieb über dem Zehnjahresschnitt.",
		"erlaeuterungen": "Als durchschnittliche Betriebsgrösse wird die Anzahl Zimmer je Betrieb bezeichnet. 2019 wurde die Berechnung der Anzahl verfügbarer Zimmer an die Methodik des Bundesamtes für Statistik (BFS) angeglichen. Für den Jahresvergleich wurde die Berechnung für 2013 rückwirkend angepasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Durchschnittliche Betriebsgrösse",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07973",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "2.2",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-09T10:52:48",
		"id": 7973
	},
	{
		"template": "template001_print",
		"data-id": 7974,
		"chart-id": 7974,
		"filter": "",
		"parentId": "6539",
		"children": [],
		"title": "Anzahl Zimmer und Auslastung nach Hotelkategorie",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2022 standen den Gästen der baselstädtischen Hotellerie insgesamt 4 608 Zimmer zur Verfügung. Davon entfielen 2 010 Zimmer auf Betriebe mit 4 und 5 Sternen und 1 547 auf die Kategorie der 3-Sterne-Hotels. Die Anzahl verfügbarer Zimmer liegt 2022 über dem Stand von vor zehn Jahren. Die Nettozimmerauslastung nahm gegenüber 2013 ab, insgesamt resultierte ein Minus von 9,6 Prozentpunkten.",
		"erlaeuterungen": "Die Nettozimmerauslastung gibt an, wie oft ein Zimmer an den Tagen belegt war, an denen der Betrieb geöffnet war, und das Zimmer zur Verfügung stand. 2019 wurde die Berechnung der Anzahl verfügbarer Zimmer an die Methodik des Bundesamtes für Statistik (BFS) angeglichen. Für den Jahresvergleich wurde die Berechnung für 2013 rückwirkend angepasst.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Zimmer und Auslastung nach Hotelkategorie",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07974",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "2.3",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-09T10:52:49",
		"id": 7974
	},
	{
		"template": "line001_print",
		"data-id": 7975,
		"chart-id": 7975,
		"filter": "",
		"parentId": "6540",
		"children": [],
		"title": "Nettozimmerauslastung nach Wochentag",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Nach weitgehender Kontinuität in den Jahren 2013 bis 2019 sank die durchschnittliche Nettozimmerauslastung 2020 und 2021 deutlich. 2022 erholte sie sich über die gesamte Woche hinweg betrachtet um 17,5% und liegt bei 52,5%. Lag die durchschnittliche Nettozimmerauslastung von Sonntag bis Donnerstag 2021 bei 32,7%, schliesst sie 2022 bei 51,5%. Von Freitag bis Samstag lag die Nettozimmerauslastung im Jahr 2021 bei durchschnittlich 40,6%, 2022 bei 54,9%.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettozimmerauslastung nach Wochentag",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07975",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "2.4",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-09T10:52:49",
		"id": 7975
	},
	{
		"template": "line001_print",
		"data-id": 7976,
		"chart-id": 7976,
		"filter": "",
		"parentId": "6541",
		"children": [],
		"title": "Hotelbetriebe und Anzahl Betten",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2022 boten die 65 baselstädtischen Hotels insgesamt 9 280 Betten an. Im Jahr 2021 waren es 8 476 Betten in 66 Hotelbetrieben. Dies entspricht einer Zunahme um 805 Betten. In der Erhebung von 1937 gab es in 42 Betrieben insgesamt 2 164 Betten.",
		"erlaeuterungen": "Seit 2016 werden in den Hotels die Doppelbetten, welche eine Schlafgelegenheit für zwei Personen anbieten, als zwei Betten in der Statistik aufgeführt. Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Hotelbetriebe und Anzahl Betten",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07976",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "2.5",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-09T10:52:50",
		"id": 7976
	},
	{
		"template": "template001_print",
		"data-id": 7977,
		"chart-id": 7977,
		"filter": "",
		"parentId": "6542",
		"children": [],
		"title": "Verfügbare Betten nach Hotelkategorie",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2022 standen den Gästen in den baselstädtischen Hotels insgesamt 9 280 Betten zur Verfügung. Gegenüber 2021 bedeutet dies eine Zunahme um 9,5% bzw. 805 Betten. Von den im Jahr 2022 verfügbaren Betten entfielen 3 778 auf Betriebe mit 4 und 5 Sternen, 3 051 auf die 3-Sterne-Hotels. Die Bettenzahl nahm in der höchsten Kategorie gegenüber 2021 um 818 bzw. 27,6% zu. Bei den 3-Sterne-Betrieben resultierte eine Abnahme um 71 Betten bzw. 2,3%.",
		"erlaeuterungen": "Seit 2016 werden in den Hotels die Doppelbetten, welche eine Schlafgelegenheit für zwei Personen anbieten, als zwei Betten in der Statistik aufgeführt. 2019 wurde die Berechnung der Anzahl verfügbarer Betten an die Methodik des Bundesamtes für Statistik (BFS) angeglichen. Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Verfügbare Betten nach Hotelkategorie",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07977",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "2.6",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-09T10:52:50",
		"id": 7977
	},
	{
		"template": "line001_print",
		"data-id": 7978,
		"chart-id": 7978,
		"filter": "",
		"parentId": "6543",
		"children": [],
		"title": "Mittlere Aufenthaltsdauer pro Jahr",
		"subtitle": "in Tagen, Basel-Stadt",
		"lesehilfe": "2022 verweilten die Gäste durchschnittlich 1,85 Tage in einem der Hotelbetriebe des Kantons Basel-Stadt. Schweizer Gäste blieben mit 1,68 Tagen durchschnittlicher Aufenthaltsdauer weniger lange als Gäste aus dem Ausland mit durchschnittlich 1,99 Tagen. Bis in die frühen 1990er-Jahre war dieses Verhältnis umgekehrt, mit Ausnahme der Kriegsjahre 1940, 1941, 1942 und 1944.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittlere Aufenthaltsdauer pro Jahr",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07978",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "2.7",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-09T10:52:51",
		"id": 7978
	},
	{
		"template": "line001_print",
		"data-id": 7979,
		"chart-id": 7979,
		"filter": "",
		"parentId": "6544",
		"children": [],
		"title": "Mittlere Aufenthaltsdauer pro Monat",
		"subtitle": "in Tagen, Basel-Stadt, 2022",
		"lesehilfe": "Am längsten verweilten Inlandgäste im Monat August mit durchschnittlich 1,81 Tagen in baselstädtischen Hotels. Die längste Aufenthaltsdauer bei den ausländischen Gästen wurde mit 2,20 Tagen im Juni registriert. Die kürzeste Aufenthaltsdauer der Schweizer Gäste wurde mit durchschnittlich 1,54 Tagen im November verzeichnet. Bei den Gästen aus dem Ausland resultierte die mit 1,74 Tagen kürzeste durchschnittliche Aufenthaltsdauer im Februar.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittlere Aufenthaltsdauer pro Monat",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07979",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "2.8",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-09T10:52:51",
		"id": 7979
	},
	{
		"template": "template001_print",
		"data-id": 7980,
		"chart-id": 7980,
		"filter": "",
		"parentId": "6545",
		"children": [],
		"title": "Logiernächte pro Monat nach Herkunft der Gäste",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Von Januar bis Dezember 2022 wurden insgesamt 1 301 107 Logiernächte in den baselstädtischen Hotels gezählt. Im Vergleich zum Mittelwert der letzten zehn Jahre entspricht dies einer Zunahme um 13,6% bzw. 155 315 Logiernächte. Der meistfrequentierte Monat war der September mit 140 393 Übernachtungen. Die höchste Übernachtungszahl der ausländischen Gäste wurde ebenfalls im September 2022 mit 89 647 verzeichnet, bei den Inlandgästen waren es die 57 726 Übernachtungen im August. Der besucherschwächste Monat war der Januar mit 39 575 Übernachtungen.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Logiernächte pro Monat nach Herkunft der Gäste",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07980",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "2.10",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-09T10:52:52",
		"id": 7980
	},
	{
		"template": "line001_print",
		"data-id": 7981,
		"chart-id": 7981,
		"filter": "",
		"parentId": "6546",
		"children": [],
		"title": "Logiernächte nach Herkunft der Gäste",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Nach einem Höchststand von 1,42 Millionen Übernachtungen im Jahr 2019 brach die Anzahl Logiernächte 2020 und 2021 ein. Das Jahr 2022 schloss bei 1,3 Millionen Logiernächten, das sind 516 500 bzw. 65,8% mehr als 2021. Gäste aus der Schweiz übernachteten im Berichtsjahr 536 630 Mal in einem baselstädtischen Hotel, 2021 waren es 401 814. Dies entspricht einem Plus von 134 816 Logiernächten oder 33,6%. Gäste aus dem Ausland logierten 2022 insgesamt 764 477 Mal in einem Hotel in Basel-Stadt, 2021 waren es 382 793. Hier beträgt der Zuwachs 381 684 Logiernächte bzw. 99,7%. Im Jahresdurchschnitt 2022 übernachteten 3 565 Gäste pro Tag in den baselstädtischen Hotelbetrieben. Der Höchstwert der täglichen Übernachtungen wurde am 16. Juli mit 7 301 registriert, der Tiefstwert am 9. Januar mit 664.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Logiernächte nach Herkunft der Gäste",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07981",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "2.11",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-09T10:52:52",
		"id": 7981
	},
	{
		"template": "line001_print",
		"data-id": 7982,
		"chart-id": 7982,
		"filter": "",
		"parentId": "6547",
		"children": [],
		"title": "Logiernächte nach Herkunft der Gäste",
		"subtitle": "indexiert (2013 = 100), Basel-Stadt",
		"lesehilfe": "In den letzten zehn Jahren ist die Anzahl der Logiernächte der inländischen Gäste um 66,3% bzw. 213 858 gewachsen. Der Index der Übernachtungen der ausländischen Gäste stieg zwischen 2013 und 2019 um 21 Indexpunkte. Dieser Index fiel 2020 und 2021 deutlich und erreichte 2021 einen Wert von 48,9. Zum Jahresende 2022 schloss er bei 97,6 Punkten.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Logiernächte nach Herkunft der Gäste",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07982",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "2.12",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-09T10:52:53",
		"id": 7982
	},
	{
		"parentId": 6549,
		"children": [],
		"template": "map_gemeinden_print",
		"title": "Anteile am Übernachtungsvolumen der aufkommensstärksten Herkunftsmärkte",
		"subtitle": "Basel-Stadt, 2020",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzel": "I.10.1.07983",
		"kuerzelKunde": "2-15",
		"description": "Anteile am Übernachtungsvolumen der aufkommensstärksten Herkunftsmärkte",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2021-02-08T08:45:20.2020",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Insgesamt haben die Hotels bei der Nachfrage nach Übernachtungen aus den zehn aufkommensstärksten Märkten im Jahr 2020 gegenüber dem Mittelwert der Jahre 2009-2013 einen Rückgang von 49,2% zu verzeichnen. Die Nachfrage aus dem heimischen Markt ist gegenüber dem Mittelwert der Jahre 2009-2013 um 10,4% zurückgegangen. Für den deutschen Markt beläuft sich das Minus bei den Logiernächten auf 53,1%, für die Vereinigten Staaten auf 81,1% und das Vereinigte Königreich auf 75,1%. Der deutsche Markt generierte mit 19,4% den grössten Wachstumsbeitrag im Beobachtungszeitraum. Die US-amerikanischen Gäste sorgten mit 16,2% für den zweithöchsten Beitrag. Auf dem dritten Rang folgt das Vereinigte Königreich mit einem Wachstumsbeitrag von 11,6%. Der einheimische Markt trug 6,2% bei.",
		"erlaeuterungen": "Als Wachstumsbeitrag bezeichnet man denjenigen Beitrag, welchen einzelne Quellmärkte zum Wachstum der gesamten Nachfrage beisteuern. Die Kreisgrösse symbolisiert den Wachstumsbeitrag der verschiedenen Herkunftsländer. Die Abbildung zeigt neben dem Wachstumsbeitrag auch die Entwicklung und den aktuellen Marktanteil der einzelnen Herkunftsmärkte. Um den Effekt von Ausreissern (z. B. aufgrund von Grossveranstaltungen, welche nicht jedes Jahr stattfinden) auszugleichen, wird anstelle des Jahreswertes 2011 der Mittelwert über die Jahre 2009-2013 als Bezugsgrösse für die Berechnung des Wachstums verwendet. Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik ab März 2020.",
		"darstellungsart": "Karte",
		"printformat": "",
		"orderKey": "01_00_00_00_00_015",
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 7983,
		"chart-id": 7983,
		"filter": "",
		"id": 7983
	},
	{
		"template": "template001_print",
		"data-id": 7984,
		"chart-id": 7984,
		"filter": "",
		"parentId": "6576",
		"children": [],
		"title": "Ankünfte pro Monat nach Herkunft der Gäste",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Insgesamt 703 941 Gäste haben von Januar bis Dezember 2022 in den baselstädtischen Hotels übernachtet. Gegenüber dem Mittelwert von 2013-2022 bedeutet dies eine Zunahme um 14,5% oder 89 118 Gäste. Der ankunftsstärkste Monat war mit 79 746 Gästen der Juli. Davon entfielen 33 270 Ankünfte auf Gäste aus dem Inland und 46 476 Ankünfte auf Gäste aus dem Ausland.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Ankünfte pro Monat nach Herkunft der Gäste",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07984",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "2.9",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-09T10:52:53",
		"id": 7984
	},
	{
		"template": "pie001_print",
		"data-id": 7985,
		"chart-id": 7985,
		"filter": "",
		"parentId": "7519",
		"children": [],
		"title": "Marktanteile am Übernachtungsvolumen",
		"subtitle": "Basel-Stadt, 2022",
		"lesehilfe": "Die Schweiz ist im Jahr 2022 mit einem Anteil von 41,2% der grösste Markt für die baselstädtische Hotellerie. Der wichtigste ausländische Markt ist Deutschland mit einem Marktanteil von 13,8%.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Marktanteile am Übernachtungsvolumen",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07985",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "2.13",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_013",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-09T10:52:54",
		"id": 7985
	},
	{
		"template": "template001_print",
		"data-id": 7986,
		"chart-id": 7986,
		"filter": "",
		"parentId": "7520",
		"children": [],
		"title": "Logiernächte und Marktanteile am Übernachtungsvolumen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Logiernächte von Gästen aus der Schweiz nahmen von 322 772 im Jahr 2013 auf 536 630 im Jahr 2022 zu. Der Marktanteil der Schweizer Gäste nahm von 29,2% auf 41,2% zu. Bei den Gästen aus Deutschland, dem mit 13,8% Marktanteil nach wie vor grössten ausländischen Markt, ging die Zahl der Übernachtungen von 185 430 im Jahr 2013 auf 179 918 im Jahr 2022 zurück.",
		"erlaeuterungen": "Die COVID-19-Pandemie und die damit verbundenen Massnahmen zum Schutz der Bevölkerung haben Auswirkungen auf Reiseverhalten und Tourismus und damit auf die Tourismusstatistik seit März 2020.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Logiernächte und Marktanteile am Übernachtungsvolumen",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07986",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "2.14",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_014",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-09T10:52:54",
		"id": 7986
	},
	{
		"template": "pie001_print",
		"data-id": 7987,
		"chart-id": 7987,
		"filter": "",
		"parentId": "7522",
		"children": [],
		"title": "Logiernächte nach Herkunft und Hotelkategorie",
		"subtitle": "Basel-Stadt, 2022",
		"lesehilfe": "Bei der Wahl der Hotelkategorie gab es im Jahr 2022 zwischen den aus- und inländischen Gästen kaum Unterschiede: 46% der ausländischen Touristinnen und Touristen buchten ein 4- oder 5-Sterne-Hotel, 33% bevorzugten ein 3-Sterne-Hotel. Bei den inländischen Besucherinnen und Besuchern liegen die Werte bei 42% bzw. 33%.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Logiernächte nach Herkunft und Hotelkategorie",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07987",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "2.15",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_015",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-09T10:52:55",
		"id": 7987
	},
	{
		"template": "template001_print",
		"data-id": 7988,
		"chart-id": 7988,
		"filter": "",
		"parentId": "7523",
		"children": [],
		"title": "Logiernächte der Hauptmärkte nach Hotelkategorie",
		"subtitle": "Basel-Stadt, 2022",
		"lesehilfe": "Gäste aus Deutschland, dem im Jahr 2022 mit 179 918 Logiernächten grössten ausländischen Markt der baselstädtischen Hotellerie, buchten zu 37,4% eine Übernachtung in einem 4- und 5-Sterne-Hotel. 73,5% der Logiernächte von Gästen aus den Vereinigten Staaten entfielen auf 4- und 5-Sterne-Häuser. Besucherinnen und Besucher aus Spanien und Italien buchten mehrheitlich in 3-Sterne-Hotels.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Tourismusstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Logiernächte der Hauptmärkte nach Hotelkategorie",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.07988",
		"kennzahlenset": "Tourismus (Print)",
		"kuerzelKunde": "2.16",
		"stufe1": "Kernindikatoren zum Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_016",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-02-09T10:52:55",
		"id": 7988
	}
];