var indikatorensetData = [
	{
		"template": "template001_print",
		"data-id": 6760,
		"chart-id": 6760,
		"filter": "",
		"parentId": "6011",
		"children": [],
		"title": "Zu- und Weggezogene nach Zuzugsort und Wegzugsort",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2021 ergab sich durch Zu- und Wegzüger im Kanton Basel-Stadt ein Minus von 1 000 Personen. Damit ist der Wanderungssaldo der betrachteten zehn Jahre das erste Mal negativ. Die meisten Wegzüger des Jahres 2021 (rund 5 200 Personen) gingen in die Nordwestschweiz. Die meisten Zuzüger kamen aus dem Ausland nach Basel-Stadt, zuletzt fast 6 800 Personen.",
		"erlaeuterungen": "Nordwestschweiz: Kanton Basel-Landschaft, Bezirke Dorneck und Thierstein des Kantons Solothurn sowie Bezirke Laufenburg und Rheinfelden einschliesslich der Gemeinden Bözen, Effingen und Elfingen des Kantons Aargau.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zu- und Weggezogene nach Zuzugsort und Wegzugsort",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "I.01.5.06760",
		"kennzahlenset": "Wanderungen (Print)",
		"kuerzelKunde": "Abb. 2.1",
		"stufe1": "Kernindikatoren zu den Wanderungsbewegungen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-24T04:29:08",
		"id": 6760
	},
	{
		"template": "template001_print",
		"data-id": 6761,
		"chart-id": 6761,
		"filter": "",
		"parentId": "6012",
		"children": [],
		"title": "Wanderungssaldo nach Staatsangehörigkeit, Zuzugs- und Wegzugsland",
		"subtitle": "Basel-Stadt, 2024",
		"lesehilfe": "2024 ergibt sich für den Kanton ein Wanderungsgewinn von total 1 133 Personen. Dieser kommt vor allem dadurch zustande, dass dem Wanderungsverlust von -711 bei den Schweizern ein Wanderungsgewinn von +1 844 bei den Ausländern gegenübersteht. Im Jahr 2023 wurde ein Wanderungsgewinn von 1 353 Personen verzeichnet.",
		"erlaeuterungen": "Der Wanderungssaldo ist die Differenz der von ausserhalb in den Kanton Basel-Stadt Zugezogenen und der aus dem Kanton Basel-Stadt Weggezogenen. Die Rubrik «Unbekannt» ist vor allem auf Wegzüger zurückzuführen, die ihre neue Adresse nicht angeben oder ohne Abmeldung wegziehen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wanderungssaldo nach Staatsangehörigkeit, Zuzugs- und Wegzugsland",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "",
		"kennzahlenset": "Wanderungen (Print)",
		"kuerzelKunde": "2.2",
		"stufe1": "2 Kernindikatoren zu den Wanderungsbewegungen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-20T08:24:42",
		"id": 6761
	},
	{
		"template": "pie001_print",
		"data-id": 6762,
		"chart-id": 6762,
		"filter": "",
		"parentId": "6013",
		"children": [],
		"title": "Aus dem Ausland Zugezogene nach Zuzugsland",
		"subtitle": "fünf wichtigste ausländische Zuzugsländer, Basel-Stadt, 2024",
		"lesehilfe": "Die grösste Gruppe der aus dem Ausland Zugewanderten kommt im Jahr 2024 aus Deutschland (2 347 Personen). An zweiter Stelle folgt Italien mit einem deutlich tieferen Wert (463). Aus der Kategorie Übriges Ausland stammen 3 542 Menschen.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Aus dem Ausland Zugezogene nach Zuzugsland",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "",
		"kennzahlenset": "Wanderungen (Print)",
		"kuerzelKunde": "2.3",
		"stufe1": "2 Kernindikatoren zu den Wanderungsbewegungen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-20T08:24:44",
		"id": 6762
	},
	{
		"template": "template001_print",
		"data-id": 6765,
		"chart-id": 6765,
		"filter": "",
		"parentId": "6016",
		"children": [],
		"title": "Zugezogene nach Zuzugsland, bei denen die Staatsangehörigkeit dem Zuzugsland entspricht",
		"subtitle": "Schweiz und fünf wichtigste ausländische Zuzugsländer, Basel-Stadt",
		"lesehilfe": "60% der Personen, die 2021 aus der Schweiz nach Basel-Stadt ziehen, sind Schweizer Staatsangehörige (2012: 58,5%). 75% der aus Deutschland zuwandernden Personen sind deutsche und 83% der aus Spanien zuziehenden Personen sind spanische Staatsangehörige.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zugezogene nach Zuzugsland, bei denen die Staatsangehörigkeit dem Zuzugsland entspricht",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "I.01.5.06765",
		"kennzahlenset": "Wanderungen (Print)",
		"kuerzelKunde": "Abb. 2.6",
		"stufe1": "Kernindikatoren zu den Wanderungsbewegungen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-24T04:29:09",
		"id": 6765
	},
	{
		"template": "template001_print",
		"data-id": 6766,
		"chart-id": 6766,
		"filter": "",
		"parentId": "6017",
		"children": [],
		"title": "Zugezogene nach Zuzugsland und Geschlecht",
		"subtitle": "Schweiz und fünf wichtigste ausländische Zuzugsländer, Basel-Stadt, 2021",
		"lesehilfe": "Knapp die Hälfte (49,7%) aller nach Basel-Stadt zugezogenen Personen sind Frauen. Die Zugezogenen aus den USA und der Schweiz weisen einen leicht höheren Frauenanteil auf (51,9% und 51,6%). Mehr Männer ziehen beispielsweise aus Frankreich zu (56,9%).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zugezogene nach Zuzugsland und Geschlecht",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "I.01.5.06766",
		"kennzahlenset": "Wanderungen (Print)",
		"kuerzelKunde": "Abb. 2.7",
		"stufe1": "Kernindikatoren zu den Wanderungsbewegungen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-24T04:29:09",
		"id": 6766
	},
	{
		"template": "populationPyramid001_print",
		"data-id": 6767,
		"chart-id": 6767,
		"filter": "",
		"parentId": "6018",
		"children": [],
		"title": "Wanderungssaldo gegenüber der Schweiz nach Alter",
		"subtitle": "Basel-Stadt, 2015 bis 2024 zusammengefasst",
		"lesehilfe": "Zwischen 2015 und 2024 war die Wanderungsbilanz zwischen den aus der Schweiz Zugezogenen und den in die Schweiz Weggezogenen bei zwei jüngeren Altersgruppen (15- bis 19- und 20- bis 24-Jährige) sowie den Personen ab 75 Jahren positiv. Bei allen anderen Altersgruppen war der Saldo negativ.",
		"erlaeuterungen": "Der Wanderungssaldo ist die Differenz der von ausserhalb in den Kanton Basel-Stadt Zugezogenen und der aus dem Kanton Basel-Stadt Weggezogenen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wanderungssaldo gegenüber der Schweiz nach Alter",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "",
		"kennzahlenset": "Wanderungen (Print)",
		"kuerzelKunde": "2.8",
		"stufe1": "2 Kernindikatoren zu den Wanderungsbewegungen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-20T08:24:46",
		"id": 6767
	},
	{
		"template": "populationPyramid001_print",
		"data-id": 6768,
		"chart-id": 6768,
		"filter": "",
		"parentId": "6019",
		"children": [],
		"title": "Wanderungssaldo gegenüber dem Ausland nach Alter",
		"subtitle": "Basel-Stadt, 2015 bis 2024 zusammengefasst",
		"lesehilfe": "In den Jahren 2015 bis 2024 sind in allen Altersklassen bis 59 Jahre in der Summe mehr Personen aus dem Ausland nach Basel-Stadt zugezogen, als aus Basel-Stadt ins Ausland weggezogen. Nur für die Altersklassen ab 60 Jahren ist der Wanderungssaldo negativ.",
		"erlaeuterungen": "Der Wanderungssaldo ist die Differenz der von ausserhalb in den Kanton Basel-Stadt Zugezogenen und der aus dem Kanton Basel-Stadt Weggezogenen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wanderungssaldo gegenüber dem Ausland nach Alter",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "",
		"kennzahlenset": "Wanderungen (Print)",
		"kuerzelKunde": "2.9",
		"stufe1": "2 Kernindikatoren zu den Wanderungsbewegungen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-20T08:24:47",
		"id": 6768
	},
	{
		"template": "template001_print",
		"data-id": 6770,
		"chart-id": 6770,
		"filter": "",
		"parentId": "6021",
		"children": [],
		"title": "Aus dem Ausland Zugezogene nach Zuzugsland sowie nach Gemeinde und Wohnviertel",
		"subtitle": "fünf wichtigste ausländische Zuzugsländer, Basel-Stadt, 2021",
		"lesehilfe": "2021 kamen 28% aller baselstädtischen Neuzuzügerinnen und Neuzuzüger aus Deutschland. Ihr Anteil ist in Bettingen (75%), Riehen (55%) und Hirzbrunnen (37%) besonders hoch. Personen aus den Vereinigten Staaten von Amerika ziehen überproportional häufig in die Altstadt Kleinbasel (15%).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel",
			"Kanton"
		],
		"description": "Aus dem Ausland Zugezogene nach Zuzugsland sowie nach Gemeinde und Wohnviertel",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "I.01.5.06770",
		"kennzahlenset": "Wanderungen (Print)",
		"kuerzelKunde": "Abb. 2.11",
		"stufe1": "Kernindikatoren zu den Wanderungsbewegungen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-24T04:29:10",
		"id": 6770
	},
	{
		"template": "mapcolumn002_print",
		"data-id": 6771,
		"chart-id": 6771,
		"filter": "",
		"parentId": "6022",
		"children": [],
		"title": "Bevölkerungssaldo räumlicher Bevölkerungsbewegungen pro 100 Einwohner",
		"subtitle": "Basel-Stadt, 2021",
		"lesehilfe": "Der Wanderungssaldo pro 100 Einwohner illustriert, in welche baselstädtischen Wohnviertel mehr Personen aus anderen Kantonen oder aus dem Ausland zuziehen, als von dort abwandern. Im Jahr 2021 verbuchten die Wohnviertel Clara und Vorstädte die grössten Wanderungsgewinne. Deutliche Wanderungsverluste ergaben sich hingegen für die Wohnviertel Kleinhüningen und Breite. Betrachtet man die innerkantonalen Umzüge, wiesen Bettingen und das Wohnviertel Clara deutlich die grössten Umzugsgewinne pro 100 Einwohner auf. Hohe Umzugsverluste pro 100 Einwohner verzeichneten unter anderem die Wohnviertel Vorstädte und Wettstein. Die höchsten Bevölkerungssaldi infolge sämtlicher räumlicher Bevölkerungsbewegungen (Wanderungen über die Kantonsgrenzen hinweg und Umzüge innerhalb des Kantons) wiesen Clara und Bettingen auf. Die höchsten Bevölkerungsverluste verzeichneten die Wohnviertel Vorstädte und Klybeck.",
		"erlaeuterungen": "Der Wanderungssaldo ist die Differenz zwischen den von ausserhalb in den Kanton Zugezogenen und den aus Basel-Stadt Weggezogenen. Der Umzugssaldo stellt die Differenz zwischen den innerkantonalen Wohnungswechseln bezogen auf ein baselstädtisches Wohnviertel oder eine baselstädtische Gemeinde dar. Der Bevölkerungssaldo berücksichtigt die Differenz zwischen den Zu- und Wegzugsereignissen der inner- und ausserkantonalen Wanderungen.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel",
			"Kanton"
		],
		"description": "Bevölkerungssaldo räumlicher Bevölkerungsbewegungen pro 100 Einwohner",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "I.01.5.06771",
		"kennzahlenset": "Wanderungen (Print)",
		"kuerzelKunde": "Abb. 2.12",
		"stufe1": "Kernindikatoren zu den Wanderungsbewegungen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_012",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-24T04:29:11",
		"id": 6771
	},
	{
		"template": "template001_print",
		"data-id": 6772,
		"chart-id": 6772,
		"filter": "",
		"parentId": "6023",
		"children": [],
		"title": "Zugezogene, Weggezogene und Wanderungssaldo",
		"subtitle": "nach Zuzugs- und Wegzugsland (fünf wichtigste ausländische Zuzugsländer), Basel-Stadt, 2021",
		"lesehilfe": "Betrachtet man die fünf wichtigsten ausländischen Zuzugsländer, verbuchte Basel-Stadt 2021 den grössten Zuzugsüberschuss gegenüber Deutschland (+666), danach folgt Spanien (+257).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zugezogene, Weggezogene und Wanderungssaldo",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "I.01.5.06772",
		"kennzahlenset": "Wanderungen (Print)",
		"kuerzelKunde": "Abb. 2.4",
		"stufe1": "Kernindikatoren zu den Wanderungsbewegungen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-06-24T04:29:11",
		"id": 6772
	},
	{
		"template": "line001_print",
		"data-id": 6773,
		"chart-id": 6773,
		"filter": "",
		"parentId": "6024",
		"children": [],
		"title": "Entwicklung der aus dem Ausland Zugezogenen",
		"subtitle": "nach Zuzugsland (fünf wichtigste ausländische Zuzugsländer), Basel-Stadt, indexiert (2015 = 100)",
		"lesehilfe": "Im Jahr 2024 zogen 23% mehr Personen aus Deutschland nach Basel-Stadt als 2015. Einen deutlichen Rückgang gegenüber 2015 gab es bei den Zugezogenen aus den Vereinigten Staaten von Amerika (-39%). Der vergleichsweise hohe Wert in der Gruppe «Übriges Ausland» im Jahr 2022 ist auf die Schutzsuchenden aus der Ukraine zurückzuführen.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung der aus dem Ausland Zugezogenen",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "I.01.5.06773",
		"kennzahlenset": "Wanderungen (Print)",
		"kuerzelKunde": "2.5",
		"stufe1": "2 Kernindikatoren zu den Wanderungsbewegungen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-05-20T08:24:45",
		"id": 6773
	},
	{
		"template": "mappie002_print",
		"data-id": 6774,
		"chart-id": 6774,
		"filter": "",
		"parentId": "6025",
		"children": [],
		"title": "Anteil Zugezogene nach Zuzugsland und Anzahl Zugezogene pro 100 Einwohner",
		"subtitle": "Basel-Stadt, 2021",
		"lesehilfe": "47% der Neuzuzügerinnen und Neuzuzüger in Basel-Stadt kommen aus der Schweiz, 53% ziehen aus dem Ausland zu. In der Gemeinde Bettingen ist der Anteil der Neuzuziehenden aus der Schweiz (62%) am höchsten. In den Wohnvierteln Breite, Gundeldingen, Bachletten und Iselin liegt der Anteil der zugezogenen Personen, die bereits zuvor in der Schweiz gelebt haben, ebenfalls deutlich über dem kantonalen Durchschnitt. Überdurchschnittlich viele Zuzügerinnen und Zuzüger aus dem Ausland gibt es beispielsweise in den Wohnvierteln Rosental, Clara und Wettstein. Am meisten Zuziehende pro 100 Einwohner weisen die Wohnviertel Vorstädte und Rosental mit jeweils 11 Personen auf, am wenigsten das Wohnviertel Hirzbrunnen und die Gemeinde Riehen mit jeweils 3 Personen.",
		"erlaeuterungen": "Zugezogene mit unbekanntem Zuzugsort werden in diesem Indikator nicht berücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel",
			"Kanton"
		],
		"description": "Anteil Zugezogene nach Zuzugsland und Anzahl Zugezogene pro 100 Einwohner",
		"thema": "01 Bevölkerung",
		"unterthema": "Wanderungen",
		"kuerzel": "I.01.5.06774",
		"kennzahlenset": "Wanderungen (Print)",
		"kuerzelKunde": "2.10",
		"stufe1": "2 Kernindikatoren zu den Wanderungsbewegungen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_010",
		"darstellungsart": "Karte",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-07-13T10:06:16",
		"id": 6774
	}
];