var indikatorensetData = [
	{
		"title": "Bruttoinlandprodukt",
		"subtitle": "total in Mrd. Franken, 2018",
		"kuerzel": "",
		"kuerzelKunde": "1.1-1",
		"description": "Bruttoinlandprodukt",
		"thema": "04 Volkswirtschaft",
		"unterthema": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-07-09T16:25:49.4949",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.1 Bruttoinlandprodukt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Das grösste nominale Bruttoinlandprodukt (BIP) der betrachteten Kantone erwirtschaftet Basel-Stadt mit 37,1 Mrd. Franken, gefolgt von Basel-Landschaft mit 21,1 und Jura mit 4,7 Mrd. Franken.",
		"erlaeuterungen": "Das Bruttoinlandprodukt (BIP) ist ein Mass für die wirtschaftliche Leistung der kantonalen Wirtschaft. Es misst den Wert der im Kanton hergestellten Waren und Dienstleistungen, soweit diese nicht als Vorleistungen für die Produktion anderer Waren und Dienstleistungen verwendet werden. Es wird das nominale BIP ausgewiesen (zu laufenden Preisen). <br>Die Berechnungsmethode verwendet den Produktionsansatz. Dabei wird die Wertschöpfung ermittelt, welche ein Kanton während einer bestimmten Periode erwirtschaftet. Die Wertschöpfung ergibt sich aus der Differenz zwischen dem Produktionswert (Wert der produzierten Waren und Dienstleistungen) und den Vorleistungen (Verbrauch von Gütern und Dienstleistungen im Produktionsprozess).",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "01_01_00_00_00_001",
		"parentId": 8350,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"BAK Economics"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8467,
		"chart-id": 8467,
		"filter": "",
		"id": 8467
	},
	{
		"title": "Bruttoinlandprodukt pro Kopf",
		"subtitle": "in Franken, 2018",
		"kuerzel": "",
		"kuerzelKunde": "1.1-2",
		"description": "Bruttoinlandprodukt pro Kopf",
		"thema": "04 Volkswirtschaft",
		"unterthema": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-07-09T16:25:49.4949",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.1 Bruttoinlandprodukt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Mit fast 191 000 Franken pro Kopf im Jahr 2018 weist der Kanton Basel-Stadt das höchste nominale Bruttoinlandprodukt pro Kopf der Schweiz auf. Basel-Landschaft kommt auf über 73 000 Franken, Jura auf rund 64 000 Franken. Der Durchschnittswert für die gesamte Schweiz liegt bei ca. 81 000 Franken.",
		"erlaeuterungen": "Das Bruttoinlandprodukt (BIP) ist ein Mass für die wirtschaftliche Leistung der kantonalen Wirtschaft. Es misst den Wert der im Kanton hergestellten Waren und Dienstleistungen, soweit diese nicht als Vorleistungen für die Produktion anderer Waren und Dienstleistungen verwendet werden. Es wird das nominale BIP ausgewiesen (zu laufenden Preisen).<br>Die Berechnungsmethode verwendet den Produktionsansatz. Dabei wird die Wertschöpfung ermittelt, welche ein Kanton während einer bestimmten Periode erwirtschaftet. Die Wertschöpfung ergibt sich aus der Differenz zwischen dem Produktionswert (Wert der produzierten Waren und Dienstleistungen) und den Vorleistungen (Verbrauch von Gütern und Dienstleistungen im Produktionsprozess).",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "01_01_00_00_00_002",
		"parentId": 8351,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"BAK Economics"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8468,
		"chart-id": 8468,
		"filter": "",
		"id": 8468
	},
	{
		"title": "Entwicklung Bruttoinlandprodukt",
		"subtitle": "real; indexiert (2014 = 100)",
		"kuerzel": "",
		"kuerzelKunde": "1.1-3",
		"description": "Entwicklung Bruttoinlandprodukt",
		"thema": "04 Volkswirtschaft",
		"unterthema": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-07-09T16:25:50.5050",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.1 Bruttoinlandprodukt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die grösste Steigerung des realen Bruttoinlandprodukts zwischen 2014 und 2018 weist Basel-Stadt mit 19,9% auf, gefolgt von Basel-Landschaft mit 9,9% und Jura mit 3,3%. In der gesamten Schweiz stieg der Wert um 7,8%.",
		"erlaeuterungen": "Das Bruttoinlandprodukt (BIP) ist ein Mass für die wirtschaftliche Leistung der kantonalen Wirtschaft. Es misst den Wert der im Kanton hergestellten Waren und Dienstleistungen, soweit diese nicht als Vorleistungen für die Produktion anderer Waren und Dienstleistungen verwendet werden. Grundlage für die Indexierung sind die Werte des realen BIP (zu Preisen des Vorjahres).<br>Die Berechnungsmethode verwendet den Produktionsansatz. Dabei wird die Wertschöpfung ermittelt, welche ein Kanton während einer bestimmten Periode erwirtschaftet. Die Wertschöpfung ergibt sich aus der Differenz zwischen dem Produktionswert (Wert der produzierten Waren und Dienstleistungen) und den Vorleistungen (Verbrauch von Gütern und Dienstleistungen im Produktionsprozess).",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "01_01_00_00_00_003",
		"parentId": 8352,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"BAK Economics"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8469,
		"chart-id": 8469,
		"filter": "",
		"id": 8469
	},
	{
		"title": "Entwicklung Bruttoinlandprodukt pro Kopf",
		"subtitle": "real; indexiert (2014 = 100)",
		"kuerzel": "",
		"kuerzelKunde": "1.1-4",
		"description": "Entwicklung Bruttoinlandprodukt pro Kopf",
		"thema": "04 Volkswirtschaft",
		"unterthema": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-07-09T16:25:50.5050",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.1 Bruttoinlandprodukt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die grösste Steigerung des realen Bruttoinlandprodukts pro Kopf zwischen 2014 und 2018 weist Basel-Stadt mit 16,8% auf. Im Kanton Basel-Landschaft beträgt der Zuwachs 6,4% und im Jura 0,6%. In der gesamten Schweiz stieg der Wert um 3,1%.",
		"erlaeuterungen": "Das Bruttoinlandprodukt (BIP) ist ein Mass für die wirtschaftliche Leistung der kantonalen Wirtschaft. Es misst den Wert der im Kanton hergestellten Waren und Dienstleistungen, soweit diese nicht als Vorleistungen für die Produktion anderer Waren und Dienstleistungen verwendet werden. Grundlage für die Indexierung sind die Werte des realen BIP (zu Preisen des Vorjahres).<br>Die Berechnungsmethode verwendet den Produktionsansatz. Dabei wird die Wertschöpfung ermittelt, welche ein Kanton während einer bestimmten Periode erwirtschaftet. Die Wertschöpfung ergibt sich aus der Differenz zwischen dem Produktionswert (Wert der produzierten Waren und Dienstleistungen) und den Vorleistungen (Verbrauch von Gütern und Dienstleistungen im Produktionsprozess).",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "01_01_00_00_00_004",
		"parentId": 8353,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"BAK Economics"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8470,
		"chart-id": 8470,
		"filter": "",
		"id": 8470
	},
	{
		"title": "Anteile Wertschöpfung nach Branche",
		"subtitle": "Anteile an der Gesamtwertschöpfung, 2018",
		"kuerzel": "",
		"kuerzelKunde": "1.2-1",
		"description": "Anteile Wertschöpfung nach Branche",
		"thema": "04 Volkswirtschaft",
		"unterthema": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-07-09T16:25:51.5151",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.2 Wertschöpfung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "In Basel-Stadt erwirtschaften 2018 die Branchen Chemie und Pharma 43,7% der kantonalen Wertschöpfung. In Basel-Landschaft hat der Bereich Handel und Reparatur mit 18,2% den grössten Anteil. Im Kanton Jura sind wiederum die Hersteller von Investitionsgütern am stärksten vertreten (32,6% der Wertschöpfung). Diese Branche ist in Basel-Stadt fast bedeutungslos, in Basel-Landschaft erwirtschaftet sie 8,8%. In der gesamten Region (BS, BL, JU) trägt die chemisch-pharmazeutische Industrie am meisten zur Gesamtwertschöpfung bei (31,3%). An zweiter Stelle folgt der Handel (10,1%).",
		"erlaeuterungen": "Die Anteile errechnen sich aus der jeweiligen nominalen Bruttowertschöpfung der Branche geteilt durch die Gesamtwertschöpfung in der jeweiligen Region.",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "01_02_00_00_00_001",
		"parentId": 8354,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"BAK Economics"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8471,
		"chart-id": 8471,
		"filter": "",
		"id": 8471
	},
	{
		"title": "Entwicklung Wertschöpfung nach Branche, Basel-Stadt",
		"subtitle": "real, indexiert (2014 = 100)",
		"kuerzel": "I.04.2.08472",
		"kuerzelKunde": "1.2-2",
		"description": "Entwicklung Wertschöpfung nach Branche, Basel-Stadt",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-07-09T16:25:51.5151",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.2 Wertschöpfung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die reale Wertschöpfung in der Pharmaindustrie in Basel-Stadt ist zwischen 2014 und 2018 um 71% gestiegen. Auch die Wertschöpfung in der Metallindustrie ist gewachsen (+18%), wobei diese Branche, ebenso wie der Bereich Elektro/Optik/Maschinen-Industrie (-26%), sehr klein ist. Die Wertschöpfung im Baugewerbe hat um 17% zugenommen, während sie im Bereich Verkehr und Lagerei um 12% zurückgegangen ist.",
		"erlaeuterungen": "Das Wachstum der realen Wertschöpfung wird in Preisen des Vorjahrs gerechnet. Hier sind die Daten indexiert (Wert im Jahr 2014 = 100).",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "01_02_00_00_00_002",
		"parentId": 8355,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"BAK Economics"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8472,
		"chart-id": 8472,
		"filter": "",
		"id": 8472
	},
	{
		"template": "line001_print",
		"data-id": 8473,
		"chart-id": 8473,
		"filter": "",
		"parentId": "8356",
		"children": [],
		"title": "Entwicklung Wertschöpfung nach Branche, Basel-Landschaft",
		"subtitle": "real, indexiert (2014 = 100)",
		"lesehilfe": "Seit 2014 hat sich auch in Basel-Landschaft die Wertschöpfung der Pharmaindustrie mehr als verdoppelt und die Wertschöpfung in der Chemischen Industrie hat um fast 60% zugenommen. Im ersten Pandemiejahr 2020 ist die Wertschöpfung vor allem im Gastgewerbe und im Bereich Verkehr und Lagerei eingebrochen.",
		"erlaeuterungen": "Das Wachstum der realen Wertschöpfung wird in Preisen des Vorjahrs gerechnet. Hier sind die Daten indexiert (Wert im Jahr 2014 = 100).",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Wertschöpfung nach Branche, Basel-Landschaft",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.08473",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.2-3",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.2 Wertschöpfung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:18:56",
		"id": 8473
	},
	{
		"template": "line001_print",
		"data-id": 8474,
		"chart-id": 8474,
		"filter": "",
		"parentId": "8357",
		"children": [],
		"title": "Entwicklung Wertschöpfung nach Branche, Jura",
		"subtitle": "real, indexiert (2014 = 100)",
		"lesehilfe": "Im Pandemiejahr 2020 ist die Wertschöpfung in vielen Branchen im Kanton Jura gesunken, aber am stärksten ist auch hier das Gastgewerbe betroffen. Deutlich zugenommen hat die realen Wertschöpfung im Baugewerbe sowie in den Finanz- und Versicherungsdienstleistungen.",
		"erlaeuterungen": "Das Wachstum de realen Wertschöpfung wird in Preisen des Vorjahrs gerechnet. Hier sind die Daten indexiert (Wert im Jahr 2014 = 100). Aufgrund der sehr niedrigen Beschäftigtenzahlen sind für den Kanton Jura keine Wertschöpfungszahlen für die chemischen Industrie und für Pharma vorhanden.",
		"quellenangabe": [
			"BAK Economics"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Wertschöpfung nach Branche, Jura",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kuerzel": "I.04.2.08474",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.2-4",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.2 Wertschöpfung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_02_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:18:57",
		"id": 8474
	},
	{
		"title": "Entwicklung Wertschöpfung nach Branche, BS/BL/JU",
		"subtitle": "real, indexiert (2014 = 100)",
		"kuerzel": "I.04.2.08475",
		"kuerzelKunde": "1.2-5",
		"description": "Entwicklung Wertschöpfung nach Branche, BS/BL/JU",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-07-09T16:25:52.5252",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.2 Wertschöpfung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "In der Gesamtregion BS/BL/JU hat zwischen 2014 und 2018 die Wertschöpfung in der Pharmaindustrie am stärksten zugenommen (+70%), während diejenige im Fahrzeugbau den deutlichsten Rückgang hinnehmen musste (-31%).",
		"erlaeuterungen": "Das Wachstum der realen Wertschöpfung wird in Preisen des Vorjahrs gerechnet. Hier sind die Daten indexiert (Wert im Jahr 2014 = 100).",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "01_02_00_00_00_005",
		"parentId": 8358,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"BAK Economics"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8475,
		"chart-id": 8475,
		"filter": "",
		"id": 8475
	},
	{
		"title": "Entwicklung Wertschöpfung nach Branche, Schweiz",
		"subtitle": "real, indexiert (2014 = 100)",
		"kuerzel": "I.04.2.08476",
		"kuerzelKunde": "1.2-6",
		"description": "Entwicklung Wertschöpfung nach Branche, Schweiz",
		"thema": "04 Volkswirtschaft",
		"unterthema": "Konjunktur",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"raeumlicheGliederung": [
			"Schweiz"
		],
		"aktualisierungsdatum": "2020-07-09T16:25:53.5353",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.2 Wertschöpfung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Auch in der Gesamtschweiz war das Wachstum in der Pharmabranche am stärksten: die reale Wertschöpfung ist zwischen 2014 und 2018 um 74% gestiegen. Rückläufig war die Wertschöpfung im Bereich Elektro/Optik/Maschinen, im Fahrzeugbau sowie im 1. Sektor.",
		"erlaeuterungen": "Das Wachstum der realen Wertschöpfung wird in Preisen des Vorjahrs gerechnet. Hier sind die Daten indexiert (Wert im Jahr 2014 = 100).",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "01_02_00_00_00_006",
		"parentId": 8359,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"BAK Economics"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8476,
		"chart-id": 8476,
		"filter": "",
		"id": 8476
	},
	{
		"template": "template001_print",
		"data-id": 8477,
		"chart-id": 8477,
		"filter": "",
		"parentId": "8360",
		"children": [],
		"title": "Entwicklung Erwerbstätige",
		"subtitle": "",
		"lesehilfe": "Im Kanton Basel-Landschaft waren im Jahr 2020 rund 138 000 Einwohner erwerbstätig. Der Kanton Basel-Stadt verzeichnete im gleichen Jahr rund 94 000 Erwerbstätige. Zusammen mit den rund 33 000 Erwerbstätigen im Kanton Jura waren in den drei Kantonen insgesamt etwa 265 000 Personen erwerbstätig.",
		"erlaeuterungen": "Seit 2010 stammen die Daten zu den Erwerbstätigen aus der Strukturerhebung. Es handelt sich um eine Stichprobenerhebung, weshalb die Schätzungen mit einer gewissen Ungenauigkeit verbunden sind. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Erwerbstätige",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.08477",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1-3",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:29",
		"id": 8477
	},
	{
		"template": "line001_print",
		"data-id": 8478,
		"chart-id": 8478,
		"filter": "",
		"parentId": "8361",
		"children": [],
		"title": "Entwicklung Grenzgänger",
		"subtitle": "indexiert (1. Quartal 2014 = 100)",
		"lesehilfe": "Alle betrachteten Kantone verzeichnen seit 2014 einen Anstieg an ausländischen Grenzgängern. Im Kanton Jura beträgt der Anstieg rund 46%, der Bestand im dritten Quartal 2022 liegt bei 10 100 Grenzgängern. Weniger stark gestiegen sind die Grenzgängerzahlen in Basel-Landschaft (+24% auf rund 24 100) und Basel-Stadt (+3% auf 34 800). In der gesamten Schweiz arbeiten im 3. Quartal 2022 rund 374 300 Grenzgänger, 31% mehr als im 1. Quartal 2014.",
		"erlaeuterungen": "Grenzgänger: Einwohnerinnen und Einwohner von EU- und EFTA-Staaten mit dauerhafter Aufenthaltsbewilligung haben die Möglichkeit, als Grenzgänger in der Schweiz zu arbeiten. Das BFS schätzt die Zahl der aktiven Grenzgänger aufgrund Daten verschiedener Quellen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Grenzgängerstatistik (GGS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Grenzgänger",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1-7",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:31",
		"id": 8478
	},
	{
		"template": "template001_print",
		"data-id": 8479,
		"chart-id": 8479,
		"filter": "",
		"parentId": "8362",
		"children": [],
		"title": "Grenzgänger",
		"subtitle": "2022, 3. Quartal",
		"lesehilfe": "Die meisten Grenzgänger arbeiten in Basel-Stadt, der Bestand im 3. Quartal 2022 beträgt rund 34 800. In Basel-Landschaft sind es 24 100, im Jura 10 100 Grenzgänger. In der gesamten Schweiz beträgt der Wert ca. 374 300.",
		"erlaeuterungen": "Grenzgänger: Einwohnerinnen und Einwohner von EU- und EFTA-Staaten mit dauerhafter Aufenthaltsbewilligung haben die Möglichkeit, als Grenzgänger in der Schweiz zu arbeiten. Das BFS schätzt die Zahl der aktiven Grenzgänger aufgrund Daten verschiedener Quellen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Grenzgängerstatistik (GGS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Grenzgänger",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "",
		"kuerzel": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1-5",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:29",
		"id": 8479
	},
	{
		"template": "template001_print",
		"data-id": 8480,
		"chart-id": 8480,
		"filter": "",
		"parentId": "8363",
		"children": [],
		"title": "Arbeitspendler Basel-Stadt",
		"subtitle": "Pooling 2016-2020",
		"lesehilfe": "Im Mittel der Jahre 2016 bis 2020 pendelten rund 95 300 Personen nach Basel-Stadt, um einer Erwerbstätigkeit nachzugehen. Die meisten von ihnen kommen aus Basel-Landschaft (ca. 41 200) oder aus dem Ausland (fast 35 000), vornehmlich aus Frankreich und Deutschland. Andere Schweizer Kantone spielen eine kleinere Rolle. Rund 24 400 Personen aus Basel-Stadt arbeiten in anderen Kantonen oder im Ausland, fast 15 100 von ihnen in Basel-Landschaft.",
		"erlaeuterungen": "Zupendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von einer Wohnadresse in einem anderen Kanton zu ihrem Arbeitsplatz pendeln. Die Zupendler aus dem Ausland stammen aus der Grenzgängerstatistik des Bundesamtes für Statistik (Durchschnitt der Jahre 2016 bis 2020, jeweils 4. Quartal). Erwerbstätige ohne Angabe des Ortes, wo ihr Arbeitsweg beginnt, sind nicht enthalten.<br>Wegpendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von ihrer Wohnadresse zu einem Arbeitsplatz in einem anderen Kanton oder Land pendeln. Wegpendler mit unbekanntem Arbeitsort sind nicht enthalten.<br>Pooling: Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2016 bis 2020 zusammen ausgewertet. Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Folglich gibt es innerhalb des Poolingzeitraums 2016-2020 einen methodischen Bruch.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitspendler Basel-Stadt",
		"thema": "11 Verkehr",
		"unterthema": "Pendler",
		"kuerzel": "I.11.5.08480",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1-9",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:33",
		"id": 8480
	},
	{
		"template": "template001_print",
		"data-id": 8481,
		"chart-id": 8481,
		"filter": "",
		"parentId": "8364",
		"children": [],
		"title": "Arbeitspendler Basel-Landschaft",
		"subtitle": "Pooling 2016-2020",
		"lesehilfe": "Im Kanton Basel-Landschaft gibt es im Mittel der Jahre 2016 bis 2020 etwas mehr Weg- als Zupendler (56 400 gegenüber rund 54 500). Die meisten Wegpendler arbeiten in Basel-Stadt, rund 41 200. Die meisten Zupendler kommen mit fast 21 900 Personen aus dem Ausland nach Basel-Landschaft, gefolgt von Basel-Stadt mit etwa 15 100 Arbeitskräften.",
		"erlaeuterungen": "Zupendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von einer Wohnadresse in einem anderen Kanton zu ihrem Arbeitsplatz pendeln. Die Zupendler aus dem Ausland stammen aus der Grenzgängerstatistik des Bundesamt für Statistik (Durchschnitt der Jahre 2016 bis 2020, jeweils 4. Quartal). Erwerbstätige ohne Angabe des Ortes, wo ihr Arbeitsweg beginnt, sind nicht enthalten.<br>Wegpendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von ihrer Wohnadresse zu einem Arbeitsplatz in einem anderen Kanton oder Land pendeln. Wegpendler mit unbekanntem Arbeitsort sind nicht enthalten.<br>Pooling: Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2016 bis 2020 zusammen ausgewertet. Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Folglich gibt es innerhalb des Poolingzeitraums 2016-2020 einen methodischen Bruch.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitspendler Basel-Landschaft",
		"thema": "11 Verkehr",
		"unterthema": "Pendler",
		"kuerzel": "I.11.5.08481",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1-10",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:26",
		"id": 8481
	},
	{
		"template": "template001_print",
		"data-id": 8482,
		"chart-id": 8482,
		"filter": "",
		"parentId": "8365",
		"children": [],
		"title": "Arbeitspendler Jura",
		"subtitle": "Pooling 2016-2020",
		"lesehilfe": "Im Kanton Jura gibt es im Mittel der Jahre 2016 bis 2020 deutlich weniger Weg- und Zupendler als in den beiden Basler Kantonen. Rund 5 100 Personen aus dem Jura pendelten zum Arbeiten in einen anderen Kanton oder ins Ausland, die meisten von ihnen mit rund 2 800 in den Kanton Bern, gefolgt von Neuenburg mit etwa 900 Personen. Fast drei Viertel der restlichen Wegpendler arbeiten in den Kantonen Basel-Stadt, Basel-Landschaft und Solothurn. Die meisten der insgesamt rund 10 600 Zupendler, die zum Arbeiten in den Jura kommen, stammen mit etwa 8 600 Personen aus dem Ausland.",
		"erlaeuterungen": "Zupendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von einer Wohnadresse in einem anderen Kanton zu ihrem Arbeitsplatz pendeln. Die Zupendler aus dem Ausland stammen aus der Grenzgängerstatistik des Bundesamtes für Statistik (Durchschnitt der Jahre 2016 bis 2020, jeweils 4. Quartal). Erwerbstätige ohne Angabe des Ortes, wo ihr Arbeitsweg beginnt, sind nicht enthalten.<br>Wegpendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von ihrer Wohnadresse zu einem Arbeitsplatz in einem anderen Kanton oder Land pendeln. Wegpendler mit unbekanntem Arbeitsort sind nicht enthalten.<br>Pooling: Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2016 bis 2020 zusammen ausgewertet. Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Folglich gibt es innerhalb des Poolingzeitraums 2016-2020 einen methodischen Bruch.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitspendler Jura",
		"thema": "11 Verkehr",
		"unterthema": "Pendler",
		"kuerzel": "I.11.5.08482",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1-11",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:26",
		"id": 8482
	},
	{
		"template": "template001_print",
		"data-id": 8483,
		"chart-id": 8483,
		"filter": "",
		"parentId": "8366",
		"children": [],
		"title": "Arbeitspendler BS/BL/JU",
		"subtitle": "Pooling 2016-2020",
		"lesehilfe": "Fasst man die drei Kantone Basel-Stadt, Basel-Landschaft und Jura zusammen, so pendeln im Mittel der Jahre 2016 bis 2020 insgesamt rund 28 800 Personen zur Arbeit aus diesem Gebiet weg, fast 103 300 kommen von auswärts an ihren Arbeitsplatz. Mit fast 9 200 Personen pendelt die grösste Gruppe in den Aargau. Bei den Zupendlern kommt die grosse Mehrheit mit rund 65 100 Arbeitskräften aus dem Ausland.",
		"erlaeuterungen": "Zupendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von einer Wohnadresse in einem anderen Kanton zu ihrem Arbeitsplatz pendeln. Die Zupendler aus dem Ausland stammen aus der Grenzgängerstatistik des Bundesamtes für Statistik (Durchschnitt der Jahre 2016 bis 2020, jeweils 4. Quartal). Erwerbstätige ohne Angabe des Ortes, wo ihr Arbeitsweg beginnt, sind nicht enthalten.<br>Wegpendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von ihrer Wohnadresse zu einem Arbeitsplatz in einem anderen Kanton oder Land pendeln. Wegpendler mit unbekanntem Arbeitsort sind nicht enthalten.<br>Pooling: Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2016 bis 2020 zusammen ausgewertet. Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Folglich gibt es innerhalb des Poolingzeitraums 2016-2020 einen methodischen Bruch.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitspendler BS/BL/JU",
		"thema": "11 Verkehr",
		"unterthema": "Pendler",
		"kuerzel": "I.11.5.08483",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1-12",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:27",
		"id": 8483
	},
	{
		"template": "template001_print",
		"data-id": 8484,
		"chart-id": 8484,
		"filter": "",
		"parentId": "8367",
		"children": [],
		"title": "Arbeitspendler",
		"subtitle": "Pooling 2016-2020",
		"lesehilfe": "Der durchschnittliche jährliche Saldo aus Zu- und Wegpendlern der Jahre 2016 bis 2020 ist für Basel-Stadt (+70 900) und Jura (+5 500) positiv, für Basel-Landschaft (-1 900) negativ. Werden die drei Kantone zusammen betrachtet, gibt es rund 74 500 mehr Zu- als Wegpendler.",
		"erlaeuterungen": "Zupendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von einer Wohnadresse in einem anderen Kanton zu ihrem Arbeitsplatz pendeln. Die Zupendler aus dem Ausland stammen aus der Grenzgängerstatistik des Bundesamtes für Statistik (Durchschnitt der Jahre 2016 bis 2020, jeweils 4. Quartal). Erwerbstätige ohne Angabe des Ortes, wo ihr Arbeitsweg beginnt, sind nicht enthalten.<br>Wegpendler: Erwerbstätige, die mindestens eine Stunde in der Woche arbeiten und von ihrer Wohnadresse zu einem Arbeitsplatz in einem anderen Kanton oder Land pendeln. Wegpendler mit unbekanntem Arbeitsort sind nicht enthalten.<br>Pooling: Um eine grössere Stichprobe zu erhalten, werden die Daten der Jahre 2016 bis 2020 zusammen ausgewertet. Die Zahlen können als Mittelwert über diese fünf Jahre interpretiert werden. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Folglich gibt es innerhalb des Poolingzeitraums 2016-2020 einen methodischen Bruch.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Arbeitspendler",
		"thema": "11 Verkehr",
		"unterthema": "Pendler",
		"kuerzel": "I.11.5.08484",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1-8",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:32",
		"id": 8484
	},
	{
		"template": "template001_print",
		"data-id": 8485,
		"chart-id": 8485,
		"filter": "",
		"parentId": "8368",
		"children": [],
		"title": "Entwicklung Tertiärquote",
		"subtitle": "",
		"lesehilfe": "Der Anteil von Personen, die einen Bildungsabschluss auf Niveau Tertiärstufe haben, liegt in Basel-Stadt am höchsten (2020: 50,9%). Basel-Landschaft liegt bei 40,7%, Jura bei 23,9%. Der Wert für die ganze Schweiz beträgt 40,1%.",
		"erlaeuterungen": "Der Indikator zeigt den prozentualen Anteil der Personen mit höchstem Bildungsabschluss Tertiärstufe an der ständigen Wohnbevölkerung ab 25 Jahren. Diese Altersgruppe hat in der Regel eine erste Ausbildung abgeschlossen und ist damit bereit für den Arbeitsmarkt. Personen mit einem Bildungsniveau auf Tertiärstufe haben eine höhere Berufsbildung oder eine Hochschule erfolgreich absolviert. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe von jährlich rund 5 000 in Basel-Stadt wohnhaften Personen ab 15 Jahren und sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die <a href='http://www.statistik.bs.ch/grundlagen/glossar/?5b3731f0=true' target='_blank'>Konfidenzintervalle</a> auf dem 95%-Niveau. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden. Da die Frage zur höchsten abgeschlossenen Ausbildung im Fragebogen der Strukturerhebung 2020 verändert wurde, ist die Veränderung zwischen 2020 und den Vorjahren mit Vorsicht zu interpretieren.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Tertiärquote",
		"thema": "15 Bildung",
		"unterthema": "Bildungsniveau",
		"kuerzel": "I.15.6.08485",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.2-1",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.2 Bildung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:34",
		"id": 8485
	},
	{
		"template": "template001_print",
		"data-id": 8486,
		"chart-id": 8486,
		"filter": "",
		"parentId": "8369",
		"children": [],
		"title": "Entwicklung Abschlussquote der Hochschulen",
		"subtitle": "",
		"lesehilfe": "Den höchsten Anteil neuer Absolventen weist 2021 mit 34,2% der Kanton Jura auf. In Basel-Stadt beträgt der Wert 25,2%, im Kanton Basel-Landschaft 31,4%. Im Schweizer Durchschnitt gibt es 32,7% neue Absolventen an den schweizerischen Hochschulen im Verhältnis zur gleichaltrigen Wohnbevölkerung.",
		"erlaeuterungen": "Anteil der neuen Absolventinnen und Absolventen: Lizenziat/Diplom UH, Diplom FH, Bachelor (UH, FH, PH) an den schweizerischen Hochschulen im Verhältnis zur gleichaltrigen Wohnbevölkerung. Rückwirkende Korrekturen sind möglich.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Bildungsperspektiven, Studierende und Abschlüsse der Hochschulen (SHIS-studex)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Abschlussquote der Hochschulen",
		"thema": "15 Bildung",
		"unterthema": "Bildungsabschlüsse",
		"kuerzel": "I.15.7.08486",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.2-2",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.2 Bildung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:34",
		"id": 8486
	},
	{
		"template": "template001_print",
		"data-id": 8487,
		"chart-id": 8487,
		"filter": "",
		"parentId": "8370",
		"children": [],
		"title": "Exporte und Importe",
		"subtitle": "Anteil am nominalen BIP, 2021",
		"lesehilfe": "2021 betragen die Exporte aus Basel-Stadt 204,4% und die Importe 91,9% des kantonalen BIP. Beide Werte sind im regionalen Vergleich am höchsten. Die Exporte aus dem Kanton Basel-Landschaft entsprechen 28,0% des BIP; diejenige aus dem Jura betragen 49,9% des BIP. Der Wert der Exporte aus der Gesamtschweiz beträgt 35,5% des BIP.",
		"erlaeuterungen": "Nominaler Wert der Exporte und der Importe von Waren, Total ohne Edelmetalle, Edel- und Schmucksteine, Kunstgegenstände und Antiquitäten, im Verhältnis zum nominalen regionalen Bruttoinlandprodukt (BIP). Die kantonale Aussenhandelstatistik wurde 2020 revidiert. Neu wird die Adresse des Unternehmens, welches die Waren aus- oder einführt, berücksichtig. Die revidierten Werte sind ab 2016 verfügbar. Sie sind mit früher publizierten Daten nicht vergleichbar.",
		"quellenangabe": [
			"BAK Economics",
			"Eidgenössische Zollverwaltung (EZV)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Exporte und Importe",
		"thema": "06 Industrie, Dienstleistungen",
		"unterthema": "Aussenhandel",
		"kuerzel": "I.06.4.08487",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "4-1",
		"stufe1": "4. Aussenhandel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:06",
		"id": 8487
	},
	{
		"template": "line001_print",
		"data-id": 8488,
		"chart-id": 8488,
		"filter": "",
		"parentId": "8371",
		"children": [],
		"title": "Entwicklung Exporte",
		"subtitle": "indexiert (2016 = 100)",
		"lesehilfe": "Von 2016 bis 2021 haben die nominalen Warenexporte aus Basel-Stadt um über 46% zugenommen. Von 2020 bis 2021 betrug der Zuwachs knapp 15%. Auch im Kanton Basel-Landschaft sowie im Kanton Jura gab es nach dem Exportrückgang im 2020 im letzten Jahr wieder ein Plus. Im Kanton Basel-Landschaft stiegen die Exporte leicht um 0,7%, im Jura um 29%. Somit liegen die nominalen Warenexporte aller drei Kantone höher als 2016. Für die gesamte Region BS/BL/Ju ergibt sich im Zeitraum 2016-2021 ein Wachstum von fast 41%, für die gesamte Schweiz von über 23%.",
		"erlaeuterungen": "Entwicklung des nominalen Werts der Warenexporte ins Ausland. Total ohne Edelmetalle, Edel- und Schmucksteine, Kunstgegenstände und Antiquitäten. Die kantonale Aussenhandelstatistik wurde 2020 revidiert. Neu wird die Adresse des Unternehmens, welches die Waren aus- oder einführt, berücksichtig. Die revidierten Werte sind ab 2016 verfügbar. Sie sind mit früher publizierten Daten nicht vergleichbar.",
		"quellenangabe": [
			"Eidgenössische Zollverwaltung (EZV)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Exporte",
		"thema": "06 Industrie, Dienstleistungen",
		"unterthema": "Aussenhandel",
		"kuerzel": "I.06.4.08488",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "4-2",
		"stufe1": "4. Aussenhandel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:07",
		"id": 8488
	},
	{
		"template": "line001_print",
		"data-id": 8489,
		"chart-id": 8489,
		"filter": "",
		"parentId": "8372",
		"children": [],
		"title": "Entwicklung Logiernächte",
		"subtitle": "indexiert, 2014 = 100",
		"lesehilfe": "Zwischen 2014 und 2019 haben die Logiernächte in Basel-Stadt zugenommen, insgesamt um 22,4%. In den Jahren 2020 und 2021 wurden im Kanton Basel-Stadt (46,9 bzw. 67,5 Indexpunkte) und Basel-Landschaft (47,9 bzw. 59,9 Indexpunkte) pandemiebedingte sehr tiefe Werte verzeichnet. Im Kanton Jura stieg 2021 die Zahl der Übernachtungen um 17,0%. Der Wert der gesamten Schweiz sank um 17,7%. <br>Zu den Logiernächtezahlen und der Bedeutung der Parahotellerie im Kanton Jura bitte die Erläuterungen und methodischen Hinweise beachten.",
		"erlaeuterungen": "Logiernächte der geöffneten Hotels und Kurbetriebe. Seit 2017 einschliesslich 14 Betriebe der Schweizer Jugendherbergen, deren Merkmale den Kriterien der NOGA (Allgemeine Systematik der Wirtschaftszweige) für Hotels und ähnliche Unterkünfte weitgehend entsprechen.<br>Die Parahotellerie ist in dieser Auswertung nicht erfasst, sie hat insbesondere im Kanton Jura eine grosse Bedeutung.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Beherbergungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Logiernächte",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kuerzel": "I.10.1.08489",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "5-2",
		"stufe1": "5. Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_00_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:13",
		"id": 8489
	},
	{
		"title": "Entwicklung Anzahl Logiernächte",
		"subtitle": "",
		"kuerzel": "",
		"kuerzelKunde": "5-1",
		"description": "Entwicklung Anzahl Logiernächte",
		"thema": "10 Tourismus",
		"unterthema": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-07-09T16:25:59.5959",
		"stufe1": "5. Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "In den drei Kantonen Basel-Stadt, Basel-Landschaft und Jura wurden im Jahr 2018 zusammen fast 1,8 Mio. Logiernächte verzeichnet. Der grösste Teil fiel mit fast 1,4 Mio. auf die baselstädtischen Beherbergungsbetriebe. Im Kanton Basel-Landschaft wurden rund 285 000, im Jura knapp 102 000 Logiernächte gebucht. Während in Basel-Stadt die Übernachtungszahl seit 2014 stark zunahm, ging sie in den beiden anderen Kantonen etwas zurück.<br>Zu den Logiernächtezahlen und der Bedeutung der Parahotellerie im Kanton Jura bitte die Erläuterungen und methodischen Hinweise beachten. Es gibt im Jura nach Auskunft des Kantons mehr als 2,5-mal so viele Logiernächte aus dem Bereich der Parahotellerie als aus den der Auswertung zugrundeliegenden Betrieben.",
		"erlaeuterungen": "Logiernächte der geöffneten Hotels und Kurbetriebe. Seit 2017 einschliesslich 14 Betriebe der Schweizer Jugendherbergen, deren Merkmale den Kriterien der NOGA (Allgemeine Systematik der Wirtschaftszweige) für Hotels und ähnliche Unterkünfte weitgehend entsprechen.<br>Die Parahotellerie ist in dieser Auswertung nicht erfasst, sie hat insbesondere im Kanton Jura eine grosse Bedeutung. Laut Informationen des Kanton Jura sind die Übernachtungszahlen in der Parahotellerie dort stark gestiegen. So resultierte insgesamt ein Anstieg der Übernachtungszahlen im Jura zwischen 2014 und 2018 um 10,8% (statt eines Rückgangs um 3,6%).",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "05_00_00_00_00_001",
		"parentId": 8373,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Beherbergungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8490,
		"chart-id": 8490,
		"filter": "",
		"id": 8490
	},
	{
		"template": "line001_print",
		"data-id": 8491,
		"chart-id": 8491,
		"filter": "",
		"parentId": "8431",
		"children": [],
		"title": "Entwicklung Wohnbevölkerung im Alter 15 bis 64 Jahre; BS, BL und JU",
		"subtitle": "indexiert (2017 = 100)",
		"lesehilfe": "Im regionalen Vergleich BS/BL/JU hat die 15- bis 64-jährige Wohnbevölkerung zwischen 2017 und 2021 in den Kantonen Basel-Stadt (+0,6%) und Basel-Landschaft zugenommen (+0,1%). Im Kanton Jura ist die Zahl der 15- bis 64-Jährigen hingegen um -1,1% zurückgegangen.",
		"erlaeuterungen": "Ständige Wohnbevölkerung per 31. Dezember.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Bevölkerung und der Haushalte (STATPOP)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Wohnbevölkerung im Alter 15 bis 64 Jahre; BS, BL und JU",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08491",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.3-1",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.3 Bevölkerung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_03_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:37",
		"id": 8491
	},
	{
		"template": "line001_print",
		"data-id": 8492,
		"chart-id": 8492,
		"filter": "",
		"parentId": "8432",
		"children": [],
		"title": "Entwicklung Wohnbevölkerung im Alter 15 bis 64 Jahre, BS/BL/JU und Schweiz",
		"subtitle": "indexiert (2017 = 100)",
		"lesehilfe": "In der Gesamtschweiz nahm die Zahl der 15- bis 64-Jährigen zwischen 2017 und 2021 um 1,6% zu. In der Region BS/BL/JU fiel das Wachstum moderater aus (+0,1%). Dies liegt u. a. daran, dass dort die Zahl der 15- bis 64-Jährigen in den Jahren 2018 und 2021 abnahm.",
		"erlaeuterungen": "Ständige Wohnbevölkerung per 31. Dezember.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Bevölkerung und der Haushalte (STATPOP)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Entwicklung Wohnbevölkerung im Alter 15 bis 64 Jahre, BS/BL/JU und Schweiz",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08492",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.3-2",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.3 Bevölkerung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_03_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:38",
		"id": 8492
	},
	{
		"template": "template001_print",
		"data-id": 8493,
		"chart-id": 8493,
		"filter": "",
		"parentId": "8433",
		"children": [],
		"title": "Altersklassen von 15 bis 64 Jahren; BS, BL und JU",
		"subtitle": "Anteil an der Gesamtbevölkerung, 2021",
		"lesehilfe": "Die Altersklassen zwischen 15 und 64 Jahren weisen regional sehr unterschiedliche Anteile an der jeweiligen Gesamtbevölkerung auf. So leben in Basel-Stadt vergleichsweise wenige Jugendliche und junge Erwachsene. Die 25- bis 44-Jährigen sind hingegen überdurchschnittlich gut vertreten. In den höheren Altersklassen ab 45 Jahren gleichen sich die Anteile wieder an, wobei der Kanton Basel-Landschaft bei den Altersklassen ab 45 Jahren insgesamt höhere Anteile und damit eine ältere Erwerbsbevölkerung aufweist.",
		"erlaeuterungen": "Ständige Wohnbevölkerung per 31. Dezember.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Bevölkerung und der Haushalte (STATPOP)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Altersklassen von 15 bis 64 Jahren; BS, BL und JU",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08493",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.3-3",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.3 Bevölkerung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_03_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:38",
		"id": 8493
	},
	{
		"template": "template001_print",
		"data-id": 8494,
		"chart-id": 8494,
		"filter": "",
		"parentId": "8434",
		"children": [],
		"title": "Altersklassen von 15 bis 64 Jahren; BS/BL/JU und Schweiz",
		"subtitle": "Anteil an der Gesamtbevölkerung, 2021",
		"lesehilfe": "Die Anteile der Altersklassen der 15- bis 54-Jährigen an der Gesamtbevölkerung sind in der Region BS/BL/JU leicht niedriger als in der Gesamtschweiz. Am grössten sind Unterschiede zwischen der Region BS/BL/JU und der Gesamtschweiz bei den 20- bis 24-Jährigen und den 25- bis 29-Jährigen.",
		"erlaeuterungen": "Ständige Wohnbevölkerung per 31. Dezember.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Bevölkerung und der Haushalte (STATPOP)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Altersklassen von 15 bis 64 Jahren; BS/BL/JU und Schweiz",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08494",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.3-4",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.3 Bevölkerung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_03_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:39",
		"id": 8494
	},
	{
		"template": "line001_print",
		"data-id": 8495,
		"chart-id": 8495,
		"filter": "",
		"parentId": "8435",
		"children": [],
		"title": "Entwicklung Altersquotient; BS, BL und JU",
		"subtitle": "Verhältnis der über 64-Jährigen zu den 20- bis 64-Jährigen",
		"lesehilfe": "Der Kanton Basel-Landschaft weist mit 38,3 im Jahr 2020 den höchsten Altersquotienten der Region BS/BL/JU auf, gefolgt von Jura mit 37,1 und Basel-Stadt mit 31,3. Während die Altersquotienten in den Kantonen Basel-Landschaft und Jura seit 2016 gestiegen sind, ist der Altersquotient in Basel-Stadt zurückgegangen.",
		"erlaeuterungen": "Ständige Wohnbevölkerung per 31. Dezember. Der Altersquotient beschreibt das Verhältnis der Personen im Alter von 65 oder mehr Jahren zu jenen im erwerbsfähigen Alter zwischen 20 und 64 Jahren. Das Verhältnis wird pro 100 Personen zwischen 20 und 64 Jahren ausgewiesen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Bevölkerung und der Haushalte (STATPOP)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Altersquotient; BS, BL und JU",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08495",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.3-5",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.3 Bevölkerung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_03_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:40",
		"id": 8495
	},
	{
		"template": "template001_print",
		"data-id": 8496,
		"chart-id": 8496,
		"filter": "",
		"parentId": "8436",
		"children": [],
		"title": "Entwicklung Altersquotient; BS/BL/JU und Schweiz",
		"subtitle": "Verhältnis der über 64-Jährigen zu den 20- bis 64-Jährigen",
		"lesehilfe": "Die Region BS/BL/JU weist mit 36,1 einen höheren Altersquotienten auf als die Gesamtschweiz (31,1). Im Vergleich zu 2016 ist der Altersquotient der Region BS/BL/JU um 1,8 Punkte gestiegen, jener der Schweiz um 1,9 Punkte.",
		"erlaeuterungen": "Ständige Wohnbevölkerung per 31. Dezember. Der Altersquotient beschreibt das Verhältnis der Personen im Alter von 65 oder mehr Jahren zu jenen im erwerbsfähigen Alter zwischen 20 und 64 Jahren. Das Verhältnis wird pro 100 Personen zwischen 20 und 64 Jahren ausgewiesen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Bevölkerung und der Haushalte (STATPOP)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Entwicklung Altersquotient; BS/BL/JU und Schweiz",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.08496",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.3-6",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.3 Bevölkerung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_03_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:41",
		"id": 8496
	},
	{
		"title": "Neugegründete Unternehmen",
		"subtitle": "2014-2017",
		"kuerzel": "",
		"kuerzelKunde": "1.3-1",
		"description": "Neugegründete Unternehmen",
		"thema": "06 Industrie, Dienstleistungen",
		"unterthema": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-07-09T16:26:02.022",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.3 Unternehmen und Beschäftigte",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Über die Jahre 2014 bis 2017 sind in der Region BS/BL/JU insgesamt rund 10 000 neue Unternehmen gegründet worden – je ca. 4 500 in den beiden Basel und rund 1 000 im Jura. Der überwiegende Teil der Neugründungen ist im Dienstleistungssektor angesiedelt. Deren Anteil bewegt sich zwischen 91% in Basel-Stadt und 81% im Jura.",
		"erlaeuterungen": "Erfasst werden nur tatsächlich neu entstandene Unternehmen (d. h. keine Berücksichtigung von neuen Unternehmen aus Fusionen, Übernahmen, Spaltungen oder Restrukturierungen) mit marktwirtschaftlicher Tätigkeit (ohne Holdinggesellschaften) im Industrie- und Dienstleistungssektor.",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "01_03_00_00_00_001",
		"parentId": 8437,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensdemografie (UDEMO)"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8497,
		"chart-id": 8497,
		"filter": "",
		"id": 8497
	},
	{
		"template": "template001_print",
		"data-id": 8498,
		"chart-id": 8498,
		"filter": "",
		"parentId": "8438",
		"children": [],
		"title": "Beschäftigte nach Branche",
		"subtitle": "2020",
		"lesehilfe": "In Basel-Stadt sind rund 82% der Beschäftigten in einer Dienstleistungsbranche tätig und damit deutlich mehr als im Baselbiet (72%) oder im Jura (56%). Im Industriesektor ist für Basel-Stadt die Chemie- und Pharmabranche von besonderer Bedeutung. Am gewichtigsten ist der Industriesektor jedoch für den Kanton Jura mit einem Anteil von 37% der Beschäftigten (verglichen mit 26% in BL bzw. 18% in BS). Dabei ist insbesondere die Investitionsgüterindustrie zentral. Auch der Landwirtschaftssektor hat im Jura mit 7% einen höheren Beschäftigtenanteil als in den beiden Basel.",
		"erlaeuterungen": "Gezählt werden alle Beschäftigten (inkl. Selbstständigerwerbende), welche sozialversicherungspflichtig sind (ab Jahreseinkommen von 2 300 Franken) und ihre Tätigkeit in einer Arbeitsstätte mit Standort in BS/BL/JU verrichten (unabhängig vom Hauptsitz des Gesamtunternehmens).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Beschäftigte nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08498",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.3-4",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.3 Unternehmen und Beschäftigte",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:18:58",
		"id": 8498
	},
	{
		"template": "template001_print",
		"data-id": 8499,
		"chart-id": 8499,
		"filter": "",
		"parentId": "8439",
		"children": [],
		"title": "Arbeitsstätten nach Branche",
		"subtitle": "2020",
		"lesehilfe": "Rund 91% der Arbeitsstätten in Basel-Stadt sind in einer Dienstleistungsbranche angesiedelt. Im Baselbiet und im Jura liegt dieser Anteil deutlich tiefer bei 79% bzw. 65%. In allen drei Kantonen sind dabei insbesondere der Handel, das Gesundheitswesen sowie die freiberuflichen, wissenschaftlichen und technischen Dienstleistungen am gewichtigsten. Während in Basel-Stadt die Landwirtschaft grössenmässig keine Bedeutung hat, finden sich im Jura ähnlich viele Arbeitsstätten in der Landwirtschaft wie in der Industrie.",
		"erlaeuterungen": "Erfasst werden alle Arbeitsstätten mit Standort in BS/BL/JU (unabhängig vom Hauptsitz des Gesamtunternehmens), die für Beschäftigte Sozialversicherungsbeiträge abrechnen bzw. alle Beschäftigten (inkl. Selbstständigerwerbende), welche sozialversicherungspflichtig sind (ab Jahreseinkommen von 2 300 Franken).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Arbeitsstätten nach Branche",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08499",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.3-3",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.3 Unternehmen und Beschäftigte",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:18:58",
		"id": 8499
	},
	{
		"template": "template001_print",
		"data-id": 8500,
		"chart-id": 8500,
		"filter": "",
		"parentId": "8440",
		"children": [],
		"title": "Durchschnittliche Zahl der Beschäftigten pro Arbeitsstätte",
		"subtitle": "2020",
		"lesehilfe": "In einer Baselbieter Arbeitsstätte sind im Durchschnitt 7,8 Personen beschäftigt. Dieser Wert liegt nahe am gesamtschweizerischen Durchschnitt voni 7,6. Im Jura liegt der Wert etwas tiefer bei 6,8 Beschäftigten, da dort u. a. die Landwirtschaft mit typischerweise kleineren Arbeitsstätten eine höhere Bedeutung hat. In Basel-Stadt hingegen fällt die durchschnittliche Arbeitsstättengrösse mit 11,0 Beschäftigten deutlich höher aus, was mit den grösseren Arbeitsstätten in der Industrie und im Speziellen in der Chemie-/Pharmabranche erklärt werden kann.",
		"erlaeuterungen": "Erfasst werden alle Arbeitsstätten mit Standort in BS/BL/JU (unabhängig vom Hauptsitz des Gesamtunternehmens), die für Beschäftigte Sozialversicherungsbeiträge abrechnen bzw. alle Beschäftigten (inkl. Selbstständigerwerbende), welche sozialversicherungspflichtig sind (ab Jahreseinkommen von 2 300 Franken).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Durchschnittliche Zahl der Beschäftigten pro Arbeitsstätte",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08500",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.3-5",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.3 Unternehmen und Beschäftigte",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:18:59",
		"id": 8500
	},
	{
		"template": "template001_print",
		"data-id": 8501,
		"chart-id": 8501,
		"filter": "",
		"parentId": "8441",
		"children": [],
		"title": "Veränderung der Beschäftigtenzahl",
		"subtitle": "2020 gegenüber 2014",
		"lesehilfe": "Zwischen 2014 und 2020 ist die Zahl der Beschäftigten in der Region BS/BL/JU insgesamt um 1,1% gewachsen und damit weniger stark als in der Gesamtschweiz (+4,8%). Das Beschäftigungswachstum liegt im Jura (+4,4%), in Basel-Landschaft (+3,2%) und in Basel-Stadt (-1,2%) unter dem Schweizer Wert.",
		"erlaeuterungen": "Gezählt werden alle Beschäftigten (inkl. Selbstständigerwerbende), welche sozialversicherungspflichtig sind (ab Jahreseinkommen von 2 300 Franken) und ihre Tätigkeit in einer Arbeitsstätte mit Standort in BS/BL/JU verrichten (unabhängig vom Hauptsitz des Gesamtunternehmens).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Veränderung der Beschäftigtenzahl",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08501",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.3-7",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.3 Unternehmen und Beschäftigte",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:01",
		"id": 8501
	},
	{
		"title": "Entwicklung monatliche Arbeitslosenquoten",
		"subtitle": "",
		"kuerzel": "",
		"kuerzelKunde": "2.1-4",
		"description": "Entwicklung monatliche Arbeitslosenquoten",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"aktualisierungsdatum": "2020-07-07T09:09:36.3636",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die durchschnittlichen Arbeitslosenquoten in den Kantonen BS, BL und JU haben sich seit 2014 ähnlich entwickelt: Nach einem Anstieg bis 2016 hat sich die Arbeitslosigkeit im Jahr 2017 und insbesondere 2018 wieder reduziert. Das Niveau fällt jedoch unterschiedlich aus. Während sich die Arbeitslosenquote im Kanton Basel-Landschaft unter dem Schweizer Durchschnitt bewegt, fällt die Arbeitslosigkeit in Basel-Stadt und im Jura höher aus. Zuletzt im Dezember 2019 lagen die Arbeitslosenquoten bei 2,0% (BL), 3,1% (BS) und 4,0% (JU). <br>Die höhere Quote des Kantons Jura hat unter anderem mit der unterschiedlichen Berechnungsmethode zu tun; siehe auch die Erläuterungen und methodischen Hinweise. Die Kurven sind deshalb nicht direkt vergleichbar.",
		"erlaeuterungen": "Arbeitslosenquote gemäss SECO, welche nur die Anzahl der Arbeitslosen berücksichtigt, die in den regionalen Arbeitsvermittlungszentren angemeldet sind. Im Kanton Jura werden dadurch auch die Arbeitslosen gezählt, welche Sozialhilfe beziehen. In BS und BL werden diese von anderen Organisationen betreut und werden daher nicht in der Berechnung miteinbezogen. Dieser organisatorische Unterschied führt zu einem verzerrten Vergleich.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_01_00_00_00_004",
		"parentId": 8442,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Staatssekretariat für Wirtschaft SECO, Arbeitslosenstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8502,
		"chart-id": 8502,
		"filter": "",
		"id": 8502
	},
	{
		"title": "Entwicklung Steuerertrag pro Kopf der Wohnbevölkerung",
		"subtitle": "in Franken",
		"kuerzel": "",
		"kuerzelKunde": "3-1",
		"description": "Entwicklung Steuerertrag pro Kopf der Wohnbevölkerung",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"aktualisierungsdatum": "2020-07-09T16:26:04.044",
		"stufe1": "3. Öffentliche Finanzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Der Steuerertrag pro Kopf liegt im Baselbiet 2017 mit etwas über 8 000 Franken im gesamtschweizerischen Durchschnitt. Im Jura beträgt der Wert etwas mehr als 6 000 Franken. Den höchsten Steuerertrag pro Person erzielt Basel-Stadt mit rund 14 000 Franken. Verglichen mit 2014 hat sich der Steuerertrag pro Kopf in den beiden Basel erhöht und im Jura leicht reduziert.",
		"erlaeuterungen": "Steuerertrag der Kantone und ihrer Gemeinden nach national vergleichbaren Kriterien (FS-Modell). Im Steuerertrag enthalten sind die direkten Steuern der natürlichen Personen (Einkommens-, Vermögens- und Quellensteuer) und der juristischen Personen (Gewinn- und Kapitalsteuer).",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "03_00_00_00_00_001",
		"parentId": 8443,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Bevölkerung und der Haushalte (STATPOP)",
			"Eidgenössische Finanzverwaltung, Finanzstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8503,
		"chart-id": 8503,
		"filter": "",
		"id": 8503
	},
	{
		"title": "Anteil Steuerertrag nach natürlichen und juristischen Personen",
		"subtitle": "2017",
		"kuerzel": "",
		"kuerzelKunde": "3-2",
		"description": "Anteil Steuerertrag nach natürlichen und juristischen Personen",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"aktualisierungsdatum": "2020-07-09T16:26:04.044",
		"stufe1": "3. Öffentliche Finanzen",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Im schweizerischen Vergleich haben die Steuererträge der juristischen Personen im Kanton Basel-Stadt eine überdurchschnittliche Bedeutung. Deren Anteil liegt bei 30%, verglichen mit 18% in der Gesamtschweiz. Im Baselbiet tragen umgekehrt die natürlichen Personen einen überdurchschnittlichen Anteil an den Steuererträgen von 88% (Schweiz: 82%). Im Jura entsprechen die Anteile in etwa dem Schweizer Durchschnitt.",
		"erlaeuterungen": "Steuerertrag der Kantone und ihrer Gemeinden nach national vergleichbaren Kriterien (FS-Modell). Im Steuerertrag enthalten sind die direkten Steuern der natürlichen Personen (Einkommens-, Vermögens- und Quellensteuer) und der juristischen Personen (Gewinn- und Kapitalsteuer).",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "03_00_00_00_00_002",
		"parentId": 8444,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Eidgenössische Finanzverwaltung, Finanzstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8504,
		"chart-id": 8504,
		"filter": "",
		"id": 8504
	},
	{
		"template": "template001_print",
		"data-id": 8505,
		"chart-id": 8505,
		"filter": "",
		"parentId": "8445",
		"children": [],
		"title": "Entwicklung Abschlussquote der Sekundarstufe II",
		"subtitle": "",
		"lesehilfe": "Der Anteil der Jugendlichen, die bis zum 25. Altersjahr einen Erstabschluss der Sekundarstufe II erworben haben, war 2020 im Kanton Basel-Landschaft mit 89,0% am höchsten. Er lag damit unter dem Schweizer Schnitt von 90,2%. Den tiefsten Wert aller Kantone wies mit 84,0% der Kanton Basel-Stadt auf.",
		"erlaeuterungen": "Bei der Berechnung werden die folgenden Abschlüsse berücksichtigt: - Berufliche Grundbildung: eidgenössische Fähigkeitszeugnisse und Berufsatteste gemäss der Statistik der beruflichen Grundbildung (SBG); - Allgemeinbildung: gymnasiale Maturitätszeugnisse, Fachmittelschulausweise und Abschlüsse der internationalen Schulen in der Schweiz gemäss der Statistik der Bildungsabschlüsse (SBA). Die Referenzbevölkerung besteht aus allen Personen, die im Alter des Beendens der obligatorischen Schule in der Schweiz wohnten. Ausgenommen sind Grenzgängerinnen und Grenzgänger sowie Personen, die im Zuge der jüngsten Zuwanderung nach beendeter obligatorischer Schulzeit in die Schweiz gekommen sind. Jugendliche, die das Land vor dem Erwerb eines Abschlusses auf der Sekundarstufe II verlassen haben, werden ebenfalls nicht berücksichtigt. Ausserdem werden bei der Abschlussquote nur Personen bis zu einem Alter von 25 Jahren betrachtet. Für eine bessere Stabilität der Ergebnisse wird ein Dreijahresdurchschnitt berechnet. Die Quote für das Jahr t entspricht folglich dem Durchschnitt der für die Jahre t-1, t und t+1 erhaltenen Werte.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Längsschnittanalysen im Bildungsbereich (LABB)"
		],
		"externalLinks": [
			"Weiterführende Informationen zum Thema finden Sie auf der <a href = 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bildung-wissenschaft/bildungsindikatoren/themen/bildungserfolg/abschlussquote-sekii.html' target = '_blank'>Homepage des Bundesamtes für Statistik</a>"
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Entwicklung Abschlussquote der Sekundarstufe II",
		"thema": "15 Bildung",
		"unterthema": "Bildungsabschlüsse",
		"kuerzel": "I.15.7.08505",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.2-3",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.2 Bildung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:35",
		"id": 8505
	},
	{
		"template": "template001_print",
		"data-id": 8506,
		"chart-id": 8506,
		"filter": "",
		"parentId": "8446",
		"children": [],
		"title": "Entwicklung Nettoerwerbstätigenquote der 50- bis 64-Jährigen",
		"subtitle": "",
		"lesehilfe": "Die Nettoerwerbstätigenquote der im Kanton Basel-Stadt wohnhaften 50- bis 64-Jährigen liegt im Jahr 2020 bei 68,7%. Das 95%-Vertrauensintervall für diese Quote liegt zwischen 66,0% und 71,4%. Im Kanton Basel-Landschaft liegt die Quote bei 72,9% und im Kanton Jura bei 75,0%. Der Wert für die Schweiz beträgt 74,8%.",
		"erlaeuterungen": "Anteil der erwerbstätigen Wohnbevölkerung an der erwerbsfähigen Wohnbevölkerung (50 bis 64 Jahre; Nettoerwerbstätigenquote) in Prozent. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe (in Basel-Stadt zum Beispiel jährlich rund 5 000 dort wohnhafte Personen, für die Schweiz rund 270 000 Personen, jeweils ab 15 Jahren) und sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Entwicklung Nettoerwerbstätigenquote der 50- bis 64-Jährigen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.08506",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1-1",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:25",
		"id": 8506
	},
	{
		"template": "template001_print",
		"data-id": 8507,
		"chart-id": 8507,
		"filter": "",
		"parentId": "8447",
		"children": [],
		"title": "Entwicklung Nettoerwerbstätigenquote der Frauen",
		"subtitle": "",
		"lesehilfe": "Im Jahr 2020 beträgt die Nettoerwerbstätigenquote der im Kanton Basel-Stadt wohnhaften Frauen 68,7%. Das 95%-Vertrauensintervall für diese Quote liegt zwischen 66,5% und 70,9%. Im Kanton Basel-Landschaft liegt die Quote bei 69,4% und im Kanton Jura bei 66,6%. Der Wert für die Schweiz beträgt 70,6%.",
		"erlaeuterungen": "Anteil der erwerbstätigen Wohnbevölkerung an der erwerbsfähigen Wohnbevölkerung (50 bis 64 Jahre; Nettoerwerbstätigenquote) in Prozent. Die Ergebnisse beruhen auf der Hochrechnung einer Stichprobe (in Basel-Stadt zum Beispiel jährlich rund 5 000 dort wohnhafte Personen, für die Schweiz rund 270 000 Personen, jeweils ab 15 Jahren) und sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle auf dem 95%-Niveau. Das Konfidenzintervall gibt den Bereich an, der den wahren Wert mit einer Wahrscheinlichkeit von 95% umfasst. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung ab dem Jahr 2018 können die Ergebnisse nur bedingt mit denen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton",
			"Schweiz"
		],
		"description": "Entwicklung Nettoerwerbstätigenquote der Frauen",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Erwerbspersonen",
		"kuerzel": "I.03.1.08507",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1-2",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:28",
		"id": 8507
	},
	{
		"template": "line001_print",
		"data-id": 8508,
		"chart-id": 8508,
		"filter": "",
		"parentId": "8462",
		"children": [],
		"title": "Entwicklung Importe",
		"subtitle": "indexiert (2016 = 100)",
		"lesehilfe": "Der Wert der Warenimporte aus dem Ausland ist in Basel-Stadt zwischen 2016 und 2021 um über 30% gestiegen. Im Kanton Basel-Landschaft liegt der Wert über 24% höher als 2016. Im Jura ist der Wert nach einem Rückgang 2020 wieder gestiegen. Für die gesamte Region BS/BL/JU ergibt sich eine Zunahme um rund 29% seit 2016, für die gesamte Schweiz von ca. 16%.",
		"erlaeuterungen": "Entwicklung des nominalen Werts der Warenimporte aus dem Ausland. Total ohne Edelmetalle, Edel- und Schmucksteine, Kunstgegenstände und Antiquitäten. Die kantonale Aussenhandelstatistik wurde 2020 revidiert. Neu wird die Adresse des Unternehmens, welches die Waren aus- oder einführt, berücksichtig. Die revidierten Werte sind ab 2016 verfügbar. Sie sind mit früher publizierten Daten nicht vergleichbar.",
		"quellenangabe": [
			"Eidgenössische Zollverwaltung (EZV)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Importe",
		"thema": "06 Industrie, Dienstleistungen",
		"unterthema": "Aussenhandel",
		"kuerzel": "I.06.4.08508",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "4-3",
		"stufe1": "4. Aussenhandel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_00_00_00_00_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:20:08",
		"id": 8508
	},
	{
		"template": "line001_print",
		"data-id": 8864,
		"chart-id": 8864,
		"filter": "",
		"parentId": "8863",
		"children": [],
		"title": "Anteil Grenzgänger an der Beschäftigung",
		"subtitle": "2022, 4. Quartal",
		"lesehilfe": "Im Kanton Jura kommen rund 24 Grenzgänger auf 100 Stellen (Beschäftigungsstand: 2020). Auch der Anteil in den Kantonen Basel-Stadt (19%) und Basel-Landschaft (16%) ist im Vergleich zur gesamten Schweiz (7%) deutlich höher.",
		"erlaeuterungen": "Grenzgänger: Einwohnerinnen und Einwohner von EU- und EFTA-Staaten mit dauerhafter Aufenthaltsbewilligung haben die Möglichkeit, als Grenzgänger in der Schweiz zu arbeiten. Beschäftigte (besetzte Stellen): Als Beschäftigte gelten Personen, die eine Tätigkeit ausüben und die einen AHV-pflichtigen Lohn von mindestens 2 300 Franken pro Jahr erhalten.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)",
			"Bundesamt für Statistik (BFS), Grenzgängerstatistik (GGS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteil Grenzgänger an der Beschäftigung",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Ausländische Erwerbstätige",
		"kuerzel": "I.03.5.08864",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "2.1-6",
		"stufe1": "2. Arbeitsmarkt, Bildung und Bevölkerung",
		"stufe2": "2.1 Arbeitsmarkt",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:30",
		"id": 8864
	},
	{
		"title": "Entwicklung Handelsbilanz",
		"subtitle": "in Mio. Franken",
		"kuerzel": "I.06.4.08874",
		"kuerzelKunde": "4-4",
		"description": "Entwicklung Handelsbilanz",
		"thema": "06 Industrie, Dienstleistungen",
		"unterthema": "Aussenhandel",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-07-09T16:26:07.077",
		"stufe1": "4. Aussenhandel",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die Handelsbilanz im Kanton Basel-Landschaft steigt 2018 auf 26,6 Milliarden Franken, während sie in Basel-Stadt 14,7 Milliarden beträgt und im Jura bei null liegt. In der Schweiz insgesamt war die Handelsbilanz 2017 und 2018 rückläufig und liegt 2018 bei 31,4 Milliarden Franken.",
		"erlaeuterungen": "Die Handelsbilanz entspricht der Differenz zwischen den nominalen Exporten und den nominalen Importen im Warenhandel.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "04_00_00_00_00_004",
		"parentId": 8868,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Eidgenössische Zollverwaltung (EZV)"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8874,
		"chart-id": 8874,
		"filter": "",
		"id": 8874
	},
	{
		"title": "Entwicklung Bettenangebot",
		"subtitle": "",
		"kuerzel": "I.10.1.08876",
		"kuerzelKunde": "5-3",
		"description": "Entwicklung Bettenangebot",
		"thema": "10 Tourismus",
		"unterthema": "Hotellerie",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-07-09T16:26:07.077",
		"stufe1": "5. Tourismus",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "In den drei Kantonen Basel-Stadt, Basel-Landschaft und Jura wurden im Jahr 2018 zusammen fast 12 900 Betten angeboten. Mit Abstand die meisten bot Basel-Stadt mit über 9 000 an. Das Bettenangebot nahm in Basel-Stadt seit 2014 um fast 33% zu. In Basel-Landschaft und im Jura wurden in diesem Zeitraum Rückgänge verzeichnet (-5,5% auf 2 300 und -12,3% auf 1 500). <br>Zur Bedeutung der Parahotellerie im Kanton Jura bitte die Erläuterungen und methodischen Hinweise beachten.",
		"erlaeuterungen": "Anzahl angebotene Betten der geöffneten Hotels und Kurbetriebe. Seit 2017 einschliesslich 14 Betriebe der Schweizer Jugendherbergen, deren Merkmale den Kriterien der NOGA (Allgemeine Systematik der Wirtschaftszweige) für Hotels und ähnliche Unterkünfte weitgehend entsprechen. <br>Die Parahotellerie ist in dieser Auswertung nicht erfasst, sie hat insbesondere im Kanton Jura eine grosse Bedeutung.",
		"template": "template001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "05_00_00_00_00_003",
		"parentId": 8873,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Beherbergungsstatistik"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8876,
		"chart-id": 8876,
		"filter": "",
		"id": 8876
	},
	{
		"title": "Entwicklung Neugründungsrate",
		"subtitle": "Anteil am Unternehmensbestand",
		"kuerzel": "I.06.2.08972",
		"kuerzelKunde": "1.3-2",
		"description": "Entwicklung Neugründungsrate",
		"thema": "06 Industrie, Dienstleistungen",
		"unterthema": "Neugründungen",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-07-09T16:26:08.088",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.3 Unternehmen und Beschäftigte",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die Neugründungsrate misst den Anteil aller in einem Jahr neugegründeten Unternehmen am Total der im selben Jahr aktiven Unternehmen. Dieser Anteil war mit Ausnahme des Kantons JU im Jahr 2014 besonders hoch und hat sich seither reduziert. 2014 war die Neugründungsrate in der Region BS/BL/JU mit 8,3% höher als in der Gesamtschweiz, seither jedoch sind die Werte unterhalb des schweizweiten Niveaus gefallen. Zuletzt im Jahr 2017 lag die Quote bei 6,5% (BS/BL/JU) resp. 7,1% (CH).",
		"erlaeuterungen": "Erfasst werden nur tatsächlich neuentstandene Unternehmen (d. h. keine Berücksichtigung von neuen Unternehmen aus Fusionen, Übernahmen, Spaltungen oder Restrukturierungen) mit marktwirtschaftlicher Tätigkeit (ohne Holdinggesellschaften) im Industrie- und Dienstleistungssektor.",
		"template": "line001_print",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "01_03_00_00_00_002",
		"parentId": 8969,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensdemografie (UDEMO)"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 8972,
		"chart-id": 8972,
		"filter": "",
		"id": 8972
	},
	{
		"template": "line001_print",
		"data-id": 8973,
		"chart-id": 8973,
		"filter": "",
		"parentId": "8970",
		"children": [],
		"title": "Entwicklung Beschäftigung",
		"subtitle": "",
		"lesehilfe": "Basel-Stadt zählt rund 189 000 Beschäftigte und damit fast so viele wie die beiden Kantone Basel-Landschaft und Jura zusammen. Die Beschäftigung in der Region BS/BL/JU hat im Jahr 2020 gegenüber dem Vorjahr um 1,1% abgenommen.",
		"erlaeuterungen": "Erfasst werden alle Arbeitsstätten mit Standort in BS/BL/JU (unabhängig vom Hauptsitz des Gesamtunternehmens), die für Beschäftigte Sozialversicherungsbeiträge abrechnen bzw. alle Beschäftigten (inkl. Selbstständigerwerbende), welche sozialversicherungspflichtig sind (ab Jahreseinkommen von 2 300 Franken).",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Unternehmensstruktur (STATENT)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Entwicklung Beschäftigung",
		"thema": "03 Arbeit, Erwerb",
		"unterthema": "Beschäftigte",
		"kuerzel": "I.03.2.08973",
		"kennzahlenset": "Wirtschaftsbericht BS_BL_JU (Print)",
		"kuerzelKunde": "1.3-6",
		"stufe1": "1. Bruttoinlandprodukt und Unternehmensbewegungen",
		"stufe2": "1.3 Unternehmen und Beschäftigte",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_03_00_00_00_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-07T08:19:00",
		"id": 8973
	}
];