var indikatorensetData = [
	{
		"template": "template001",
		"data-id": 7595,
		"chart-id": 4135,
		"filter": "",
		"parentId": "4135",
		"children": [],
		"title": "Nettowohnungsproduktion",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Nettowohnungsproduktion lag 2021 bei 977 Einheiten. Dies vor allem dank einer wiederum hohen Neubauproduktion sowie eines stark positiven Umbausaldos.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettowohnungsproduktion",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.07595",
		"kennzahlenset": "Wohnbaustatistik",
		"kuerzelKunde": "01",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-02-24T09:16:49",
		"id": 7595
	},
	{
		"template": "template001",
		"data-id": 7596,
		"chart-id": 4136,
		"filter": "",
		"parentId": "4136",
		"children": [],
		"title": "Umgebaute Wohnungen",
		"subtitle": "nach Art des Umbaus, Basel-Stadt",
		"lesehilfe": "Seit 2011 ist der Umbausaldo positiv. Die hohen Werte 2014, 2019 und 2021 sind auf die grosse Anzahl Umnutzungen gewerblich genutzter Räume zu Wohnungen zurückzuführen. 2020 trug unter anderem der Dachstockausbau wesentlich zum positiven Umbausaldo bei.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Umgebaute Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.07596",
		"kennzahlenset": "Wohnbaustatistik",
		"kuerzelKunde": "02",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-02-24T09:16:50",
		"id": 7596
	},
	{
		"template": "template001",
		"data-id": 7597,
		"chart-id": 5817,
		"filter": "",
		"parentId": "5817",
		"children": [],
		"title": "Nettowohnungsproduktion",
		"subtitle": "nach Wohnviertel, Basel-Stadt, 2012-2021",
		"lesehilfe": "Die Nettowohnungsproduktion war in den letzten zehn Jahren im Wohnviertel Rosental besonders hoch. Auf dieses Wohnviertel entfielen rund 22% der gesamtkantonalen Nettoproduktion. Die Nettowohnungsproduktion ist insgesamt vor allem auf grosse Arealentwicklungen zurückzuführen und in kleinerem Masse auf Erneuerungen bzw. Verdichtungen im Bestand.",
		"erlaeuterungen": "Die Nettowohnungsproduktion setzt sich wie folgt zusammen: Neugebaute Wohnungen minus abgebrochene Wohnungen plus Saldo aus Umbauten (kann positiv oder negativ sein).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Wohnviertel"
		],
		"description": "Nettowohnungsproduktion",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.07597",
		"kennzahlenset": "Wohnbaustatistik",
		"kuerzelKunde": "03",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-02-24T09:16:50",
		"id": 7597
	},
	{
		"template": "template001",
		"data-id": 7598,
		"chart-id": 4137,
		"filter": "",
		"parentId": "4137",
		"children": [],
		"title": "Neuerstellte Wohnungen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Mit 851 Einheiten war die Neubauproduktion 2021 wiederum überdurchschnittlich hoch. Der Zehnjahresdurchschnitt stieg dadurch weiter.",
		"erlaeuterungen": "Es werden nur neuerstellte Wohnungen in Neubauten berücksichtigt. Neue Wohnungen aus Umbauten sind nicht enthalten. Die Neubauprognose wird aufgrund der baubegonnenen Projekte und der voraussichtlichen Baudauer hochgerechnet. Der Durchschnitt der Neubauproduktion errechnet sich aus dem arithmetischen Mittel der Neubauten der dargestellten Jahre (exklusive Neubauprognose).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Neuerstellte Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.07598",
		"kennzahlenset": "Wohnbaustatistik",
		"kuerzelKunde": "04",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-02-24T09:16:50",
		"id": 7598
	},
	{
		"template": "line001",
		"data-id": 7599,
		"chart-id": 7599,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mittlere Fläche neuerstellter Wohnungen",
		"subtitle": "in Quadratmeter nach Zimmerzahl, Basel-Stadt",
		"lesehilfe": "Die durchschnittlichen Wohnungsflächen der Neubauwohnungen sind 2021 in allen Zimmerzahlkategorien ausser bei den Wohnungen mit 6 und mehr Zimmern grösser als die Werte im Gesamtbestand.",
		"erlaeuterungen": "Als Wohnungsfläche gelten sämtliche bewohnbaren Flächen einer Wohnung, also die Summe der Flächen sämtlicher Zimmer, Küchen, Kochnischen, Badezimmer, Toilettenräume, Abstellräume, Gänge, Veranden etc. einer Wohnung (ohne Terrassen oder offene Balkone).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Baustatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittlere Fläche neuerstellter Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.07599",
		"kennzahlenset": "Wohnbaustatistik",
		"kuerzelKunde": "05",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-02-24T09:16:51",
		"id": 7599
	},
	{
		"template": "template001",
		"data-id": 7601,
		"chart-id": 7601,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Neuerstellte Wohnungen nach Zimmerzahl",
		"subtitle": "in Prozent, Basel-Stadt",
		"lesehilfe": "In den letzten zehn Jahren waren Zwei- oder Dreizimmerwohnungen die häufigsten Kategorien der Neubauwohnungen. Durchschnittlich betrug ihr Anteil rund zwei Drittel aller neuerstellten Wohnungen.",
		"erlaeuterungen": "Es werden die neuerstellten Wohnungen in Neubauten gezählt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Baustatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Neuerstellte Wohnungen nach Zimmerzahl",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.07601",
		"kennzahlenset": "Wohnbaustatistik",
		"kuerzelKunde": "06",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-02-24T09:16:51",
		"id": 7601
	},
	{
		"template": "line001",
		"data-id": 9465,
		"chart-id": 9465,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anteile von Genossenschaftswohnungen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Der Anteil der Genossenschaftswohnungen an allen Wohnungen betrug von 2013 bis 2021 durchschnittlich knapp 11%. Bei den in diesem Zeitraum neuerstellten Logis lag er mit 13% leicht höher. 2017, 2018 und 2021 waren überdurchschnittlich ergiebige Jahre für den genossenschaftlichen Wohnungsbau. Dagegen waren die Anteile 2013 bis 2016 gering.",
		"erlaeuterungen": "Es werden beim Bestand nur Wohnungen berücksichtigt, welche am Stichtag (31.12.) durch mindestens eine Person belegt waren.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Baustatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anteile von Genossenschaftswohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.09465",
		"kennzahlenset": "Wohnbaustatistik",
		"kuerzelKunde": "07",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-02-24T09:16:51",
		"id": 9465
	}
];