var indikatorensetData = [
	{
		"template": "befragungen001",
		"data-id": 4127,
		"chart-id": 4127,
		"filter": "",
		"parentId": null,
		"children": [
			9385,
			9442
		],
		"title": "Zufriedenheit mit dem Wohnungsangebot",
		"subtitle": "«Wie zufrieden sind Sie mit dem Wohnungsangebot?», Basel-Stadt",
		"lesehilfe": "17,9% der Befragten sind 2019 mit dem Wohnungsangebot sehr zufrieden und 34,8% eher zufrieden. Gegenüber 2015 ist die Zufriedenheit der Befragten wieder gestiegen, nachdem 2015 erstmals ein Rückgang erfolgt war.",
		"erlaeuterungen": "Alle vier Jahre (bis 2007 alle zwei) wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt. Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit dem Wohnungsangebot",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.4127",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "0.1.A",
		"stufe1": "Leitgedanke",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2022-12-22T10:09:16",
		"id": 4127
	},
	{
		"template": "line001",
		"data-id": 4128,
		"chart-id": 4128,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mietpreisentwicklung",
		"subtitle": "in Franken, Wohnungen nach Zimmerzahl, Basel-Stadt",
		"lesehilfe": "Die Monatsmiete einer 5-Zimmer-Wohnung betrug im Mai 2006 im Durchschnitt 2 017 Franken, im Mai 2023 durchschnittlich 2 291 Franken.",
		"erlaeuterungen": "Abgebildet sind Bestandsmieten. Die Mietpreisangaben stützen sich auf systematische Stichprobenerhebungen, die 5% der Miet- und Genossenschaftswohnungen umfassen. Die Angaben beziehen sich auf die Mietpreiserhebung im Mai des jeweiligen Jahres. Wohnungen mit mehr als 5 Zimmern werden in der Abbildung nicht berücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Mietpreiserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mietpreisentwicklung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Mietpreise",
		"kuerzel": "I.09.3.4128",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "0.1.B-1",
		"stufe1": "Leitgedanke",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-06-06T08:19:52",
		"id": 4128
	},
	{
		"template": "line001",
		"data-id": 4129,
		"chart-id": 4129,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mietpreisentwicklung der Leerwohnungen",
		"subtitle": "nach Zimmerzahl, Basel-Stadt",
		"lesehilfe": "Bei den 2- und 3-Zimmer-Wohnungen, zu denen zwei Drittel der Leerwohnungen gehören, sind die mittleren Mietpreise der Leerwohnungen 2023 leicht gesunken.",
		"erlaeuterungen": "Ohne Wohnungen mit Zwischennutzung (eingeschränkte Mieterrechte, besonders günstig), ohne möblierte Wohnungen (besonders teuer) und mit Genossenschaftswohnungen. Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird. Bei den 5-Zimmer-Wohnungen kommt es aufgrund des kleinen Stichprobenumfangs zu grösseren Schwankungen bzw. können Werte aus Datenschutzgründen teilweise (z. B. 2014) nicht ausgewiesen werden.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mietpreisentwicklung der Leerwohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.04129",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "0.1.B-2",
		"stufe1": "Leitgedanke",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-08-18T10:17:39",
		"id": 4129
	},
	{
		"title": "Mietpreisentwicklung der 3-Zimmer-Wohnungen",
		"subtitle": "Basel-Stadt",
		"kuerzel": "I.09.3.4130",
		"kuerzelKunde": "0.1.B-3",
		"description": "Mietpreisentwicklung der 3-Zimmer-Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Mietpreise",
		"kennzahlenset": "Wohnraumentwicklung",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-06-04T08:24:18.1818",
		"stufe1": "Leitgedanke",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Die Nettomietpreise der Genossenschaftswohnungen waren in den letzten 10 Jahren im Durchschnitt ein Drittel günstiger als die Mietpreise der übrigen Mietwohnungen.",
		"erlaeuterungen": "Abgebildet sind Bestandsmieten. Die Linien zeigen jeweils den ungewichteten Durchschnitt der Wohnungsmieten. Die Punkte zeigen gewichtete Durchschnittsmietpreise, die anhand der im Gebäude- und Wohnungsregister auftretenden Häufigkeit von Wohnungen (Stand November 2015) berechnet werden. Die Mietpreisangaben stützen sich auf systematische Stichprobenerhebungen, die 5% der Miet- und Genossenschaftswohnungen umfassen. Die Angaben beziehen sich auf die Mietpreiserhebung im Mai des jeweiligen Jahres.",
		"template": "line001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "01_00_00_00_00_000",
		"parentId": null,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Mietpreiserhebung"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 4130,
		"chart-id": 4130,
		"filter": "",
		"id": 4130
	},
	{
		"template": "template001",
		"data-id": 4131,
		"chart-id": 4131,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnungsbelegung",
		"subtitle": "nach Belegungsart, Basel-Stadt",
		"lesehilfe": "Von den belegten Wohnungen im Kanton sind über alle abgebildeten Jahre hinweg  73% Mietwohnungen, 11% Genossenschaftswohnungen und 15% Eigentümerwohnungen.",
		"erlaeuterungen": "Die Daten beziehen sich auf die belegten Wohnungen (Haushalte). Unter sonstigen Wohnungen werden Notwohnungen der Sozialhilfe, subventionierte Wohnungen gemeinnütziger Institutionen, Dienst- und Abwartswohnungen gezählt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungsbelegung",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.4131",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "0.1.C",
		"stufe1": "Leitgedanke",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "01_00_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-11T08:32:30",
		"id": 4131
	},
	{
		"template": "stock001",
		"data-id": 4132,
		"chart-id": 4132,
		"filter": "",
		"parentId": null,
		"children": [
			6143,
			6297,
			7773,
			8417
		],
		"title": "Bevölkerungsbestand am Jahresende",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Zwischen dem 31.12.2013 und dem 31.12.2023 nahm die Bevölkerung im Kanton Basel-Stadt von 195 459 auf 206 308 Personen zu.",
		"erlaeuterungen": "Angaben zur Erhebung der Bevölkerungszahlen: 1774-1847: Kantonale Volkszählungen; 1850-1900: Eidgenössische Volkszählungen; 1901-2011: Fortschreibung der kantonalen Bevölkerungsstatistik; ab 2012: Auswertungen aus dem kantonalen Einwohnerregister.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [
			"Weitere Informationen zur Bevölkerungsstatistik finden Sie auf der Seite <a href = 'https://www.statistik.bs.ch/haeufig-gefragt/einwohner/zentrale-begriffe-einwohner.html' target = '_blank'>Einwohner&nbsp;-&nbsp;Zentrale Begriffe</a>."
		],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bevölkerungsbestand am Jahresende",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.04132",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "1.1.A",
		"stufe1": "Ziel 1: Gesellschaftspolitik",
		"stufe2": "1.1 Bevölkerung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_01_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-01-25T09:05:59",
		"id": 4132
	},
	{
		"template": "template001",
		"data-id": 4133,
		"chart-id": 4133,
		"filter": "",
		"parentId": null,
		"children": [
			9383,
			9440
		],
		"title": "Wohnungen nach Zimmerzahl",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Seit 2010 ist der gesamte Wohnungsbestand leicht und stetig auf 116 007 im Jahr 2023 gestiegen. Am stärksten war das Wachstum in diesem Zeitraum bei den Fünf- bzw. Zweizimmerwohnungen (+13,1% auf 7 181 bzw. +12,5% auf 27 820), am geringsten bei den Wohnungen mit sechs und mehr Zimmern (+8,3% auf 457).",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungen nach Zimmerzahl",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.04133",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "1.2.A",
		"stufe1": "Ziel 1: Gesellschaftspolitik",
		"stufe2": "1.2 Wohnraum erhalten und erneuern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-02-26T08:30:42",
		"id": 4133
	},
	{
		"template": "template001",
		"data-id": 4134,
		"chart-id": 4134,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnungsbestand nach Zimmerzahl und Wohnfläche",
		"subtitle": "Basel-Stadt, 2023",
		"lesehilfe": "2023 sind die Wohnungen zwischen 70 und 99 Quadratmetern Wohnfläche am zahlreichsten (34%). Bei den Dreizimmerwohnungen macht diese Kategorie sogar 63% aus.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungsbestand nach Zimmerzahl und Wohnfläche",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.4134",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "1.2.B",
		"stufe1": "Ziel 1: Gesellschaftspolitik",
		"stufe2": "1.2 Wohnraum erhalten und erneuern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-11T08:32:35",
		"id": 4134
	},
	{
		"template": "template001",
		"data-id": 4135,
		"chart-id": 4135,
		"filter": "",
		"parentId": null,
		"children": [
			5816,
			6248,
			7595,
			9384,
			9441
		],
		"title": "Nettowohnungsproduktion",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Nettowohnungsproduktion lag 2023 bei 865 Einheiten; dies vor allem dank  hoher Neubauproduktion und Umbautätigkeit.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Nettowohnungsproduktion",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.4135",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "1.2.C-1",
		"stufe1": "Ziel 1: Gesellschaftspolitik",
		"stufe2": "1.2 Wohnraum erhalten und erneuern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-02-26T08:30:43",
		"id": 4135
	},
	{
		"template": "template001",
		"data-id": 4136,
		"chart-id": 4136,
		"filter": "",
		"parentId": null,
		"children": [
			7596
		],
		"title": "Umgebaute Wohnungen",
		"subtitle": "nach Art des Umbaus, Basel-Stadt",
		"lesehilfe": "Seit 2011 ist der Umbausaldo positiv. Die hohen Werte 2014 und 2019 bis 2022 sind auf die grosse Anzahl Umnutzungen gewerblich genutzter Räume zu Wohnungen zurückzuführen. 2014, 2019 und 2021 wurden vor allem Bürogebäude umgenutzt, während 2020 Dachstockausbauten und 2022 die Umnutzung eines Hotels und eines Spitals wesentlich zum hohen Umbaugewinn beitrugen.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Umgebaute Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.4136",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "1.2.C-2",
		"stufe1": "Ziel 1: Gesellschaftspolitik",
		"stufe2": "1.2 Wohnraum erhalten und erneuern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-11T08:32:35",
		"id": 4136
	},
	{
		"template": "template001",
		"data-id": 4137,
		"chart-id": 4137,
		"filter": "",
		"parentId": null,
		"children": [
			7598
		],
		"title": "Neuerstellte Wohnungen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Mit 778 Einheiten war die Neubauproduktion 2023 wiederum hoch. Der Zehnjahresdurchschnitt stieg dadurch weiter an.",
		"erlaeuterungen": "Berücksichtigt werden nur neuerstellte Wohnungen in Neubauten. Neue Wohnungen aus Umbauten sind nicht enthalten. Die Neubauprognose wird aufgrund der baubegonnenen Projekte und der voraussichtlichen Baudauer hochgerechnet. Der Durchschnitt der Neubauproduktion errechnet sich aus dem arithmetischen Mittel der Neubauten der dargestellten Jahre (exklusive Neubauprognose).",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Neuerstellte Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.04137",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "1.2.E",
		"stufe1": "Ziel 1: Gesellschaftspolitik",
		"stufe2": "1.2 Wohnraum erhalten und erneuern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-11T08:32:36",
		"id": 4137
	},
	{
		"template": "template001",
		"data-id": 4138,
		"chart-id": 4138,
		"filter": "",
		"parentId": null,
		"children": [
			5195,
			8909
		],
		"title": "Leerwohnungen und Leerwohnungsquote (LWQ) nach Zimmerzahl",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Leerwohnungsquote (LWQ) erreichte im Jahr 2014 mit 0,2% ihren Tiefstwert innerhalb des Beobachtungszeitraums. Danach ist die LWQ bis 2022 auf 1,2% gestiegen und 2023 leicht auf 1,1% gesunken.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungen und Leerwohnungsquote (LWQ) nach Zimmerzahl",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.04138",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "1.2.F-1",
		"stufe1": "Ziel 1: Gesellschaftspolitik",
		"stufe2": "1.2 Wohnraum erhalten und erneuern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-08-18T10:17:40",
		"id": 4138
	},
	{
		"template": "template001",
		"data-id": 4139,
		"chart-id": 4139,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Leerwohnungen und Leerwohnungsquote nach Wohnungsgrösse",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2023 weisen Wohnungen mit einer Fläche von weniger als 30m² die höchste Leerwohnungsquote auf. Der tiefste Wert wird mit 0,6% bei Wohnungen ab 150 m² gemessen.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerwohnungen und Leerwohnungsquote nach Wohnungsgrösse",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "I.09.2.04139",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "1.2.F-2",
		"stufe1": "Ziel 1: Gesellschaftspolitik",
		"stufe2": "1.2 Wohnraum erhalten und erneuern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_02_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-08-18T10:17:41",
		"id": 4139
	},
	{
		"template": "line001",
		"data-id": 4140,
		"chart-id": 4140,
		"filter": "",
		"parentId": null,
		"children": [
			5815,
			6027,
			6247,
			8919
		],
		"title": "Mittlere Wohnfläche pro Person",
		"subtitle": "in m², Basel-Stadt",
		"lesehilfe": "2023 beträgt die mittlere Wohnfläche pro Person in Basel-Stadt 41,5 m². Zuvor nahm sie bis 2010 auf 42,1 m² zu und sank zwischenzeitlich auf 41,0 m².",
		"erlaeuterungen": "Stand jeweils per Jahresende. Ab 2012 kantonale Registerauswertungen, frühere Werte wurden auf Basis der Volkszählungen 1980, 1990 und 2000 berechnet.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik",
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mittlere Wohnfläche pro Person",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.4140",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "1.3.A",
		"stufe1": "Ziel 1: Gesellschaftspolitik",
		"stufe2": "1.3 Wohnraumnutzung",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_03_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-02-26T08:30:44",
		"id": 4140
	},
	{
		"template": "template001",
		"data-id": 4141,
		"chart-id": 4141,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Haushalte nach Art des Haushalts",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Haushaltsstruktur weist in den letzten Jahren keine grossen Veränderungen auf. Einpersonenhaushalte machen 2022 47% aus, 40% sind Familienhaushalte und 13% werden der Kategorie Andere Haushalte zugeordnet.",
		"erlaeuterungen": "Personen, die in der gleichen Wohnung leben, bilden einen Haushalt. Haushalte werden unterteilt in Privathaushalte und Kollektivhaushalte. Hier werden nur Privathaushalte betrachtet. Die Kategorie Andere Haushalte umfasst Mehrpersonenhaushalte wie Wohngemeinschaften und unverheiratete Paare ohne ein gemeinsames Kind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Haushalte nach Art des Haushalts",
		"thema": "01 Bevölkerung",
		"unterthema": "Haushalte",
		"kuerzel": "I.01.2.4141",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "1.4.A1",
		"stufe1": "Ziel 1: Gesellschaftspolitik",
		"stufe2": "1.4 Familiengerechter Wohnraum",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-09T08:19:56",
		"id": 4141
	},
	{
		"template": "template001",
		"data-id": 4142,
		"chart-id": 4142,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Familienhaushalte nach Zusammensetzung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Der Anteil kinderloser Familienhaushalte an allen Familienhaushalten sank von 40% im Jahr 2013 auf 36% im Jahr 2022.",
		"erlaeuterungen": "Personen, die in derselben Wohnung leben, bilden einen Haushalt. Haushalte werden unterteilt in Privathaushalte und Kollektivhaushalte. Hier wird nur die Untergruppe Familienhaushalte der Privathaushalte betrachtet.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Familienhaushalte nach Zusammensetzung",
		"thema": "01 Bevölkerung",
		"unterthema": "Haushalte",
		"kuerzel": "I.01.2.4142",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "1.4.A2",
		"stufe1": "Ziel 1: Gesellschaftspolitik",
		"stufe2": "1.4 Familiengerechter Wohnraum",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-09T08:19:57",
		"id": 4142
	},
	{
		"template": "template001",
		"data-id": 4143,
		"chart-id": 4143,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Genossenschaftswohnungen und ihr Anteil am Wohnungsbestand",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die 11 461 Genossenschaftswohnungen, welche 2023 im Kanton bewohnt sind, entsprechen einem Anteil am Gesamtbestand von gut 11%.",
		"erlaeuterungen": "Berücksichtigt werden Wohnungen, welche am Stichtag (31.12.) durch mindestens eine Person belegt sind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Genossenschaftswohnungen und ihr Anteil am Wohnungsbestand",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.4143",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "1.4.B",
		"stufe1": "Ziel 1: Gesellschaftspolitik",
		"stufe2": "1.4 Familiengerechter Wohnraum",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_04_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-11T08:32:36",
		"id": 4143
	},
	{
		"title": "Zufriedenheit von Familien mit dem Wohnungsangebot",
		"subtitle": "«Wie zufrieden sind Sie mit dem Wohnungsangebot?», Basel-Stadt",
		"kuerzel": "I.50.1.4144",
		"kuerzelKunde": "1.4.C",
		"description": "Zufriedenheit von Familien mit dem Wohnungsangebot",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kennzahlenset": "Wohnraumentwicklung",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-06-22T18:08:22.2222",
		"stufe1": "Ziel 1: Gesellschaftspolitik",
		"stufe2": "1.4 Familiengerechter Wohnraum",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Etwas mehr als die Hälfte der befragten Familien ist mit dem Wohnungsangebot im Kanton Basel-Stadt sehr oder eher zufrieden. Seit der ersten Bevölkerungsbefragung im Jahr 2003 ist der Anteil der Zufriedenen bis 2011 stetig gewachsen, bevor 2015 ein Rückgang erfolgte. Gegenüber 2015 ist die Zufriedenheit 2019 wieder gestiegen.",
		"erlaeuterungen": "Alle vier Jahre (bis 2007 alle zwei) wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt. Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"template": "befragungen001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "02_04_00_00_00_000",
		"parentId": null,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 4144,
		"chart-id": 4144,
		"filter": "",
		"id": 4144
	},
	{
		"template": "line001",
		"data-id": 4145,
		"chart-id": 4145,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohneigentumsquote",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Eigentumsquote beträgt seit 2012 rund 15%.",
		"erlaeuterungen": "Die Wohneigentumsquote wird als Anteil Wohnungen, welche durch den Gebäude- oder Wohnungseigentümer selber bewohnt sind, an den bewohnten Wohnungen berechnet. Die Daten 1990 und 2000 stammen aus den eidg. Volkszählungen. Seit 2012 kann die Eigentumsquote jährlich registerbasiert ausgewiesen werden.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohneigentumsquote",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.4145",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "1.6.A",
		"stufe1": "Ziel 1: Gesellschaftspolitik",
		"stufe2": "1.6 Förderung von Wohneigentum",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "02_06_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-11T08:32:37",
		"id": 4145
	},
	{
		"template": "template001",
		"data-id": 4146,
		"chart-id": 4146,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnungen mit 4 oder mehr Zimmern",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Der Anteil von Wohnungen mit 4 oder mehr Zimmern nahm von 2000 bis 2014 zu. Bis 2022 war ein leichter Rückgang zu verzeichnen. 2023 hat sich der Anteil stabilisiert.",
		"erlaeuterungen": "",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungen mit 4 oder mehr Zimmern",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "I.09.1.4146",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "2.1.A",
		"stufe1": "Ziel 2: Fiskalpolitik",
		"stufe2": "2.1 Grosszügiger Wohnraum",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_01_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2024-03-11T08:32:38",
		"id": 4146
	},
	{
		"template": "template001",
		"data-id": 4147,
		"chart-id": 4147,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Saldo des Steuerertrages von Zu- und Wegzügern",
		"subtitle": "Basel-Stadt, in Mio. Franken",
		"lesehilfe": "Seit 2009 ist der Saldo des Steuerertrages bei den Zugezogenen höher als bei den Wegzügern. Zuletzt betrug der Wert 4,7 Mio. Franken.",
		"erlaeuterungen": "Beim Steuerverfahren der ordentlichen Veranlagung ist für die kantonale Steuerpflicht der Wohnsitz am 31. Dezember massgebend. Es liegen daher im Wegzugskanton in der Regel keine Steuerdaten für das Jahr des Wegzugs vor. Deshalb ist für Wegziehende jeweils der Steuerertrag des Vorjahres abgebildet. Für die Zugezogenen und die ganzjährig Niedergelassenen werden die Steuerdaten des Berichtsjahres verwendet. <br>Aufgrund verschiedener methodischer Besonderheiten sind quellenbesteuerte Personen in dieser Auswertung zunächst nicht berücksichtig. Erst wenn sie nachträglich ordentlich veranlagt werden (zum Beispiel bei Einkünften von mehr als 120 000 Franken pro Jahr) oder die Niederlassungsbewilligung erhalten und deshalb ins ordentliche Verfahren wechseln, werden sie als Zuzug gezählt und in die Auswertung miteinbezogen – auch wenn sie schon länger im Kanton wohnhaft sind.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Steuerstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Saldo des Steuerertrages von Zu- und Wegzügern",
		"thema": "18 Öffentliche Finanzen",
		"unterthema": "Steuern",
		"kuerzel": "I.18.2.4147",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "2.1.B",
		"stufe1": "Ziel 2: Fiskalpolitik",
		"stufe2": "2.1 Grosszügiger Wohnraum",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_01_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-11-27T09:43:13",
		"id": 4147
	},
	{
		"template": "line001",
		"data-id": 4148,
		"chart-id": 4148,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Erwachsene Einwohner mit Hauptwohnsitz in Basel-Stadt",
		"subtitle": "",
		"lesehilfe": "Die Anzahl volljähriger Personen mit Hauptwohnsitz im Kanton Basel-Stadt hat im Jahr 2022 auf 169 344 zugenommen. Die volljährigen Personen mit Hauptwohnsitz im Kanton Basel-Stadt versteuern ihr Einkommen oder ihr Vermögen in der Regel in Basel-Stadt.",
		"erlaeuterungen": "Für den Indikator werden Personen ab 18 Jahren mit dem Meldeverhältnis «Hauptwohnsitz in Basel-Stadt» und den Bevölkerungstypen «Nichtständige Wohnbevölkerung» und «Ständige Wohnbevölkerung» berücksichtigt. Zur ständigen Wohnbevölkerung am Hauptwohnsitz gehören in einer baselstädtischen Gemeinde niedergelassene Schweizer (einschliesslich Personen, die ausserhalb von Basel-Stadt Wochenaufenthalter sind), Ausländer mit einer Aufenthalts- oder Niederlassungsbewilligung für mindestens 12 Monate, Ausländer mit einer nach Kurzaufenthaltsbewilligungen kumulierten Aufenthaltsdauer von mindestens 12 Monaten sowie Personen im Asylprozess mit einer Gesamtaufenthaltsdauer von mindestens 12 Monaten. Zur nichtständigen Wohnbevölkerung am Hauptwohnsitz gehören Ausländer mit einer Kurzaufenthaltsbewilligung für weniger als 12 Monate sowie Personen im Asylprozess mit einer Gesamtaufenthaltsdauer von weniger als 12 Monaten. Die Wohnbevölkerung am Nebenwohnsitz besteht aus Personen, die in Basel-Stadt Wochenaufenthalter sind (mit hinterlegtem Heimatausweis) und ihren Hauptwohnsitz anderswo haben.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Statistik der Bevölkerung und der Haushalte (STATPOP)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Erwachsene Einwohner mit Hauptwohnsitz in Basel-Stadt",
		"thema": "01 Bevölkerung",
		"unterthema": "Bestand und Struktur",
		"kuerzel": "I.01.1.4148",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "2.2.A",
		"stufe1": "Ziel 2: Fiskalpolitik",
		"stufe2": "2.2 Anteil an Hauptwohnsitznehmern",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "03_02_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-12-29T10:29:47",
		"id": 4148
	},
	{
		"template": "template001",
		"data-id": 4149,
		"chart-id": 4149,
		"filter": "",
		"parentId": null,
		"children": [
			9386,
			9443
		],
		"title": "Freiraumfläche und Anteil an der Gesamtfläche",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2022 betrugen die Freiraumflächen insgesamt 93,82 ha (2,54% der Kantonsfläche). Die Zunahme gegenüber 2021 erfolgte u.a. aufgrund der Öffnung des Novartis Campus und somit der dortigen Parkanlage für die Öffentlichkeit. Im Jahr 2013 reduzierten sich die Freiraumflächen vorübergehend aufgrund von Schulhauserweiterungen auf Kosten von Sportanlagen sowie der Umgestaltung der Voltamatte bis auf rund 83,9 Hektar. Die Öffnung des Schwarzparks für die Bevölkerung sorgte 2014 für einen Sprung auf 88,5 Hektar.",
		"erlaeuterungen": "Zu den Freiraumflächen zählen Parkanlagen, Spielplätze und Rasenflächen von Sportanlagen. Die Angaben basieren auf der Datenebene «Bodenbedeckung» der Amtlichen Vermessung des Kantons Basel-Stadt, in welcher Flächen von mind. 100 m<sup>2</sup> geführt werden. Diese werden bei Bedarf oder spätestens in einem Turnus von 6 bis 12 Jahren mit einer periodischen Nachführung aktualisiert. Befestigte Objekte wie Gebäude, Strassenräume oder öffentliche Pärke werden detaillierter erfasst und bei baulichen Änderungen nachgeführt.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Freiraumfläche und Anteil an der Gesamtfläche",
		"thema": "02 Raum, Umwelt",
		"unterthema": "Räumliche Gliederung und Bodennutzung",
		"kuerzel": "I.02.1.4149",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "3.2.A",
		"stufe1": "Ziel 3: Raumplanung",
		"stufe2": "3.2 Freiräume",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_02_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-03-27T09:08:28",
		"id": 4149
	},
	{
		"template": "befragungen001",
		"data-id": 4150,
		"chart-id": 4150,
		"filter": "",
		"parentId": null,
		"children": [
			5819,
			6251,
			9388,
			9445
		],
		"title": "Zufriedenheit mit Grünanlagen und Parks am Wohnort",
		"subtitle": "«Wie zufrieden sind Sie mit den Grünanlagen und Parks an Ihrem Wohnort?», Basel-Stadt, 2019",
		"lesehilfe": "85,9% der 2019 Befragten sind mit den Grünanlagen und Parks an ihrem Wohnort eher bis sehr zufrieden.",
		"erlaeuterungen": "Alle vier Jahre wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt. Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Zufriedenheit mit Grünanlagen und Parks am Wohnort",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kuerzel": "I.50.1.4150",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "3.2.B",
		"stufe1": "Ziel 3: Raumplanung",
		"stufe2": "3.2 Freiräume",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "04_02_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2021-12-23T02:25:00",
		"id": 4150
	},
	{
		"title": "Zufriedenheit mit Gestaltung und Erhaltung von Gebäuden und Strassenbild",
		"subtitle": "«Wie zufrieden sind Sie mit der Gestaltung und Erhaltung von Gebäuden und Strassenbild?», Basel-Stadt",
		"kuerzel": "I.50.1.4151",
		"kuerzelKunde": "3.3.A",
		"description": "Zufriedenheit mit Gestaltung und Erhaltung von Gebäuden und Strassenbild",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kennzahlenset": "Wohnraumentwicklung",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-06-22T18:08:23.2323",
		"stufe1": "Ziel 3: Raumplanung",
		"stufe2": "3.3 Städtebauliche Qualität",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "23,6% der im Jahr 2019 Befragten zeigen sich mit der Gestaltung und Erhaltung von Gebäuden und Strassenbild sehr zufrieden und 52,9% eher zufrieden. Insgesamt 15,5% sind damit eher nicht oder sehr unzufrieden.",
		"erlaeuterungen": "Alle vier Jahre (bis 2007 alle zwei) wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt.",
		"template": "befragungen001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "04_03_00_00_00_000",
		"parentId": null,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 4151,
		"chart-id": 4151,
		"filter": "",
		"id": 4151
	},
	{
		"template": "line001",
		"data-id": 4153,
		"chart-id": 4153,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Ausbezahlte Familienmietzinsbeiträge",
		"subtitle": "Basel-Stadt, in Franken",
		"lesehilfe": "Die ausbezahlten Familienmietzinsbeiträge betragen 2022 rund 11,3 Mio. Franken. Sie sind nach zuvor kontinuierlichem Anstieg das zweite Jahr in Folge gesunken.",
		"erlaeuterungen": "Anspruch auf Familienmietzinsbeiträge können Familien in bescheidenen wirtschaftlichen Verhältnissen geltend machen. Es muss mindestens ein minderjähriges oder sich in Erstausbildung befindendes Kind unter 25 Jahren im gleichen Haushalt leben. Grundvoraussetzung für den Bezug ist der Wohnsitz im Kanton Basel-Stadt, wobei das Gesetz eine Wohnsitzdauer von 5 Jahren ohne Unterbruch verlangt. Es genügt, wenn eine Person bzw. ein Elternteil diese Bedingung erfüllt.<br>Die Höhe des Zuschusses ist abhängig von der Anzahl Personen, der Anzahl Zimmer, dem Mietzins sowie dem Jahreseinkommen und Vermögen der wirtschaftlichen Haushaltseinheit.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Amt für Sozialbeiträge Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Ausbezahlte Familienmietzinsbeiträge",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.4153",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "4.1.B",
		"stufe1": "Ziel 4: Sozialpolitik",
		"stufe2": "4.1 Unterstützung Benachteiligter",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_01_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-05-22T02:05:16",
		"id": 4153
	},
	{
		"template": "template001",
		"data-id": 4154,
		"chart-id": 4154,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Bestand an Notwohnungen und ihre Belegung",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die wenigen Notwohnungen – 2022 machten sie 0,17% des Wohnungsbestandes aus – waren immer zu mindestens 86% belegt. In den Jahren 2013, 2014 und 2021 betrug die Belegung sogar mehr als 95%. Durch Aufstockungen bestehender Blockrandsiedlungen und Erweiterung des Portfolios konnte das Angebot bis 2022 um knapp 100 Logis erhöht werden.",
		"erlaeuterungen": "Belegung Ende Jahr gemäss Mietverträgen der Sozialhilfe.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Sozialhilfe Basel"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bestand an Notwohnungen und ihre Belegung",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialhilfe und Notwohnen",
		"kuerzel": "I.13.3.4154",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "4.1.E",
		"stufe1": "Ziel 4: Sozialpolitik",
		"stufe2": "4.1 Unterstützung Benachteiligter",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "05_01_00_00_00_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-06-07T08:10:27",
		"id": 4154
	},
	{
		"title": "Zufriedenheit mit Einrichtungen und Angeboten für behinderte Menschen",
		"subtitle": "«Wie zufrieden sind Sie mit den Einrichtungen und Angeboten für behinderte Menschen?», Basel-Stadt",
		"kuerzel": "I.50.1.4155",
		"kuerzelKunde": "4.2.A",
		"description": "Zufriedenheit mit Einrichtungen und Angeboten für behinderte Menschen",
		"thema": "50 Befragungen",
		"unterthema": "Bevölkerungsbefragung",
		"kennzahlenset": "Wohnraumentwicklung",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2020-06-22T18:08:24.2424",
		"stufe1": "Ziel 4: Sozialpolitik",
		"stufe2": "4.2 Wohnraum für Betagte und Behinderte",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "14,0% der im Jahr 2019 Befragten zeigen sich mit den Einrichtungen und Angeboten für behinderte Menschen sehr zufrieden und 27,9% eher zufrieden. Insgesamt 8,7% der Befragten sind damit eher oder sehr unzufrieden. Aufgrund der Änderungen der Befragungsmethodik hat der Anteil der Kategorie «Weiss nicht» deutlich zugenommen.",
		"erlaeuterungen": "Alle vier Jahre (bis 2007 alle zwei) wird im Kanton Basel-Stadt eine Bevölkerungsbefragung durchgeführt. Die Befragung richtet sich an volljährige Personen mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind. 2019 wurde die Befragung erstmals in schriftlicher Form (Papier- bzw. Onlinefragebogen) durchgeführt. In den Vorjahren wurde die Befragung telefonisch durchgeführt.<br>Es werden nur die Antworten zur Zufriedenheit jener Befragten berücksichtigt, welche zuvor eine Angabe zur Wichtigkeit des jeweiligen Aspektes gemacht haben.",
		"template": "befragungen001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "05_02_00_00_00_000",
		"parentId": null,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Bevölkerungsbefragung"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 4155,
		"chart-id": 4155,
		"filter": "",
		"id": 4155
	},
	{
		"title": "Zufriedenheit mit altersangepasster Einrichtung des Wohngebäudes",
		"subtitle": "«Wie zufrieden sind Sie mit der altersangepassten Einrichtung des Wohngebäudes?», Basel-Stadt",
		"kuerzel": "I.50.4.4156",
		"kuerzelKunde": "4.2.C",
		"description": "Zufriedenheit mit altersangepasster Einrichtung des Wohngebäudes",
		"thema": "50 Befragungen",
		"unterthema": "Befragung 55 plus",
		"kennzahlenset": "Wohnraumentwicklung",
		"raeumlicheGliederung": [
			"Kanton"
		],
		"aktualisierungsdatum": "2021-01-13T13:36:02.022",
		"stufe1": "Ziel 4: Sozialpolitik",
		"stufe2": "4.2 Wohnraum für Betagte und Behinderte",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"lesehilfe": "Seit 2011 sind gut zwei Drittel der Befragten mit der altersangepassten Einrichtung des Wohngebäudes eher bis sehr zufrieden.",
		"erlaeuterungen": "Seit 2011 wird alle vier Jahre im Kanton Basel-Stadt die Bevölkerungsbefragung 55plus durchgeführt. Die Befragung richtet sich an Personen im Alter von mindestens 55 Jahren mit Schweizer Bürgerrecht sowie Ausländerinnen und Ausländer mit Ausweis B oder C, die seit mindestens einem Jahr in Basel-Stadt wohnhaft sind.",
		"template": "befragungen001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"orderKey": "05_02_00_00_00_000",
		"parentId": null,
		"children": [],
		"renderLink": [],
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, kantonale Befragung 55plus"
		],
		"datenInChartIntegriert": false,
		"externalLinks": [
			""
		],
		"data-id": 4156,
		"chart-id": 4156,
		"filter": "",
		"id": 4156
	},
	{
		"template": "template001",
		"data-id": 9292,
		"chart-id": 9292,
		"filter": "",
		"parentId": "4152",
		"children": [],
		"title": "Haushalte mit Familienmietzinsbeiträgen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Anzahl der mit Familienmietzinsbeiträgen unterstützten Haushalte geht seit 2019 nach zuvor kontinuierlichem Anstieg zurück. Ende 2022 beziehen 2 151 Haushalte Familienmietzinsbeiträge. Dies entspricht 2,1% aller Haushalte im Kanton Basel-Stadt.",
		"erlaeuterungen": "Die Familienmietzinsbeitragsquote errechnet sich als Quotient der Anzahl Haushalte mit Mietzinsbeiträgen an der Gesamtzahl Haushalte (exklusive Haushalte in Wohnungen ohne Kocheinrichtung) per 31. Dezember.<br>Anspruch auf Familienmietzinsbeiträge können Familien in bescheidenen wirtschaftlichen Verhältnissen geltend machen. Es muss mindestens ein minderjähriges oder sich in Erstausbildung befindendes Kind unter 25 Jahren im gleichen Haushalt leben. Grundvoraussetzung für den Bezug ist der Wohnsitz im Kanton Basel-Stadt, wobei das Gesetz eine Wohnsitzdauer von 5 Jahren ohne Unterbruch verlangt. Es genügt, wenn eine Person bzw. ein Elternteil diese Bedingung erfüllt.<br>Die Höhe des Zuschusses ist abhängig von der Anzahl Personen, der Anzahl Zimmer, dem Mietzins sowie dem Jahreseinkommen und Vermögen der wirtschaftlichen Haushaltseinheit.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Basler Informationssystem Sozialleistungen (BISS)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Haushalte mit Familienmietzinsbeiträgen",
		"thema": "13 Soziale Sicherheit",
		"unterthema": "Sozialleistungen",
		"kuerzel": "I.13.2.09292",
		"kennzahlenset": "Wohnraumentwicklung",
		"kuerzelKunde": "4.1.A",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_000",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2023-05-22T02:05:16",
		"id": 9292
	}
];