var indikatorensetData = [
	{
		"template": "line001",
		"data-id": 22288,
		"chart-id": 22288,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Schweizer Mietpreisindizes im Vergleich",
		"subtitle": "indexiert (Basis Mai 2000 = 100)",
		"lesehilfe": "Der Mietpreisindex von Basel-Stadt liegt bei 139 Punkten, die Nettomieten sind damit von Mai 2000 bis Mai 2025 um 39 Prozent gestiegen.",
		"erlaeuterungen": "Indexstand im Mai des jeweiligen Jahres, Referenzzeitpunkt ist Mai des Jahres 2000. Die Indizes unterscheiden sich methodisch, bezüglich Stichprobengrösse und Erhebungsvorgehen. Die unterschiedlichen zeitlichen Entwicklungen sind daher mit Vorsicht zu interpretieren.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Mietpreiserhebung",
			"Statistik Stadt Zürich, Mietpreisindex",
			"Bundesamt für Statistik (BFS), Mietpreisindex",
			"Office cantonal de la statistique Genève, Loyers"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Schweizer Mietpreisindizes im Vergleich",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Mietpreise",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "001-1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_001",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-07-10T08:04:15",
		"id": 22288
	},
	{
		"template": "template001",
		"data-id": 22289,
		"chart-id": 22289,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mietpreise nach Quartil",
		"subtitle": "Nettomietpreise in Franken pro m<sup>2</sup> Wohnfläche, Basel-Stadt, 2015 - 2023",
		"lesehilfe": "Der Median der Preise von Mietwohnungen lag im Jahr 2023 bei geschätzt 19,7 Franken pro m<sup>2</sup>. Das erste Quartil lag bei 16,3 Franken pro m<sup>2</sup>; das bedeutet, dass ein Viertel aller Mieten unter und drei Viertel über diesem Preis lagen. Das dritte Quartil stand bei bei 23,4 Franken pro m<sup>2</sup>. Alle drei Quartilsmieten sind kontinuierlich gestiegen.",
		"erlaeuterungen": "Der m<sup>2</sup>-Preis bezieht sich auf die Nettomiete, dividiert durch die Wohnfläche. Quartile sind die drei Werte einer Häufigkeitsverteilung (hier Nettomietpreise pro m<sup>2</sup>), die diese in vier gleich grosse Bereiche teilen: 25% aller Fälle liegen im Bereich bis zum 1. Quartil der Verteilung. Die Daten stammen aus der Strukturerhebung und beruhen auf der Hochrechnung einer Stichprobe; sie sind folglich mit einer gewissen Unsicherheit behaftet. Aufgrund von Änderungen in der Erhebungsmethode und der Gewichtung können die Ergebnisse nur bedingt mit jenen vor 2018 verglichen werden.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mietpreise nach Quartil",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Mietpreise",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "001-2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_002",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-07-10T08:04:20",
		"id": 22289
	},
	{
		"template": "template001",
		"data-id": 22290,
		"chart-id": 22290,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Mietpreise nach Dauer des Mietverhältnisses",
		"subtitle": "Nettomietpreise in Franken pro m<sup>2</sup> Wohnfläche, Basel-Stadt, 2020 - 2023",
		"lesehilfe": "Die Einzugsmieten (neue Mietverhältnisse innerhalb der letzten 2 Jahre) von Wohnungen im Kanton Basel-Stadt betrugen im Jahr 2023 im Schnitt 21,4 Franken pro m<sup>2</sup> (95%-Konfidenzintervall: 20,9 - 21,9 Franken pro m<sup>2</sup>). Die Mieten von älteren Mietverhältnissen lagen durchschnittlich bei 18,5 Franken pro m<sup>2</sup>. Die Mieten von neueren Mietverhältnissen lagen somit 15,7% über denjenigen von älteren Mietverhältnissen.",
		"erlaeuterungen": "Der m<sup>2</sup>-Preis bezieht sich auf die Nettomiete, dividiert durch die Wohnfläche. Als Einzugsmieten gelten die in den letzten zwei Jahren abgeschlossenen Mietverträge. Bestandesmieten gelten für Mietverhältnisse, die bereits länger als zwei Jahre dauern. Die Daten stammen aus der Strukturerhebung und beruhen auf der Hochrechnung einer Stichprobe; sie sind folglich mit einer gewissen Unsicherheit behaftet. Die schwarzen Fehlerbalken zeigen die Konfidenzintervalle, welche den wahren Wert mit einer Wahrscheinlichkeit von 95% umfassen.",
		"quellenangabe": [
			"Bundesamt für Statistik (BFS), Strukturerhebung (SE)"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Mietpreise nach Dauer des Mietverhältnisses",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Mietpreise",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "001-3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_003",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-07-10T08:04:24",
		"id": 22290
	},
	{
		"template": "template001",
		"data-id": 22291,
		"chart-id": 22291,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Leerkündigungen",
		"subtitle": "Anzahl betroffene Wohnungen, Basel-Stadt",
		"lesehilfe": "Im Jahr 2019 wurden für 480 Wohnungen Leerkündigungen aufgrund eines Umbaus registriert – die Zahl ist gegen Ende des Beobachtungszeitraums deutlich rückläufig. Für 219 weitere erfolgte eine Leerkündigung aufgrund eines Abbruchs. Auch hier ist seit 2019 ein deutlicher Rückgang sichtbar.",
		"erlaeuterungen": "Die Auswertung erfolgt anhand der im Gebäude- und Wohnungsregister (GWR) hinterlegten Bautätigkeit sowie Belegungsangaben aus dem Einwohnerregister. Um für die Auswertung berücksichtigt werden zu können, muss ein Gebäude beim <i>Umbau</i> seit mindestens 15 Jahren bestehen und zwei Jahre vor Baubeginn über mindestens vier Wohnungen verfügen. Damit die Wohnungen als von Leerkündigungen betroffen gezählt werden, müssen 90% der Mieterschaft (relativ zu den Bewohnenden zwei Jahre vor Baubeginn) ein Jahr nach Bauvollendung  weniger als 2 Jahre in der Liegenschaft angemeldet sein. Ein <i>Abbruch</i> hat stets den Auszug der kompletten Mieterschaft zur Folge, wobei hier der Wohnungsbestand drei Jahre vor Baubeginn als Grundlage dient. Die verwendeten Registerangaben geben keinen Aufschluss darüber, welche Partei das Mietverhältnis beendet hat und aus welchem Grund. Auch wird nicht berücksichtigt, ob das Mietverhältnis befristet oder unbefristet war. Das Jahr bezeichnet das Jahr des Baubeginns.<br><br>Datenstand ist Mitte Juni 2025. Aufgrund der Zählweise, die sich auf ein Jahr nach Bauvollendung bezieht, werden nur Werte bis 2023 publiziert. Bei überdurchschnittlich langen Bauprojekten können sich die Werte der letzten Jahre (insbesondere die Leerkündigungen nach Umbau 2023) bei einer Aktualisierung erhöhen, da diese Projekte allenfalls hinzukommen.<br><br>Weitere Informationen zur Methode finden sich hier: <a href='https://statistik.bs.ch/artikel/leerkuendigungen' target='_blank'>Leerkündigungen</a>",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik",
			"Bevölkerungsdienste und Migration Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Leerkündigungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "001-4",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_004",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-07-07T01:16:04",
		"id": 22291
	},
	{
		"template": "template001",
		"data-id": 22292,
		"chart-id": 22292,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Baugesuche für Sanierungen, Umbau oder Renovation",
		"subtitle": "Wohngebäude nach Datum der Baueingabe, Basel-Stadt",
		"lesehilfe": "Seit der zweiten Jahreshälfte 2022 ist ein Einbruch bei Baugesuchen für Sanierung, Umbau oder Renovation festzustellen. Die Anzahl der nicht unter die Wohnschutzgesetzgebung fallenden Projekte war weniger stark rückläufig. Kurz davor, im Jahr 2021 und im 1. Halbjahr 2022, ist ein deutlicher Anstieg von Baugesuchen sichtbar, welche unter die Wohnschutzgesetzgebung gefallen wären.",
		"erlaeuterungen": "\"Unter Wohnschutzgesetzgebung fallende Projekte\" bezeichnet Projekte, die potentiell unter den Wohnraumschutz fallen (oder vor Inkrafttreten hätten fallen können), also Projekte mit mehr als 3 Wohnungen pro Gebäude und mit mehrheitlicher Wohnnutzung. Dabei ausgeschlossen sind Projekte von Genossenschaften. <br>Ausgewertet sind Baueingaben (Baubegehren sowie vereinfachte und technische Baubegehren) mit Schlagwort \"Umbau/Sanierung/Renovation\" in Zusammenhang mit Wohngebäuden nach Datum der Baueingabe. Umbau-, Sanierungs- und Renovationsprojekte ohne Baubewilligungspflicht fallen nicht unter die Auswertung. Die Verordnung zum Wohnraumschutz ist am 28. Mai 2022 in Kraft getreten. H1 oder H2 bezeichnen das erste beziehungsweise das zweite Halbjahr eines Jahres.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Baugesuche für Sanierungen, Umbau oder Renovation",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_005",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-07-10T08:04:27",
		"id": 22292
	},
	{
		"template": "template001",
		"data-id": 22293,
		"chart-id": 22293,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Sanierungsvolumen in Franken",
		"subtitle": "Projektgesamtkosten nach Datum der Baueingabe, Basel-Stadt",
		"lesehilfe": "Die in Baugesuchen für Sanierungen, Umbauten und Renovationen angegebenen Projektgesamtkosten sind insbesondere im Jahr 2021 deutlich gestiegen, ehe sie ab der zweiten Hälfte 2022 wieder deutlich zurückgingen. Der Effekt ist weniger deutlich bei Projekten, die nicht von der geänderten Gesetzgebung betroffenen sind.",
		"erlaeuterungen": "\"Unter Wohnschutzgesetzgebung fallende Projekte\" bezeichnet Projekte, die potentiell unter den Wohnraumschutz fallen (oder vor Inkrafttreten hätten fallen können), also Projekte mit mehr als 3 Wohnungen pro Gebäude und mit mehrheitlicher Wohnnutzung. Dabei ausgeschlossen sind Projekte von Genossenschaften. \nAusgewertet sind Baueingaben (Baubegehren sowie vereinfachte und technische Baubegehren) mit Schlagwort \"Umbau/Sanierung/Renovation\" in Zusammenhang mit Wohngebäuden nach Datum der Baueingabe. Umbau-, Sanierungs- und Renovationsprojekte ohne Baubewilligungspflicht fallen nicht unter die Auswertung. Die Verordnung zum Wohnraumschutz ist am 28. Mai 2022 in Kraft getreten. H1 oder H2 bezeichnen das erste beziehungsweise das zweite Halbjahr eines Jahres.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Sanierungsvolumen in Franken",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-2",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_006",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-07-10T08:04:34",
		"id": 22293
	},
	{
		"template": "template001",
		"data-id": 22294,
		"chart-id": 22294,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Umwandlungen in Stockwerkeigentum",
		"subtitle": "Betroffene Stammparzellen, Gebäude und Wohnungen, Basel-Stadt",
		"lesehilfe": "Die Anzahl in Stockwerkeigentum umgewandelter Stammparzellen steigt bereits in der zweiten Jahreshälfte 2021 auf 25. In der ersten Jahreshälfte 2022 springt sie dann auf 207, bevor sie wieder auf ein deutlich tieferes Niveau sinkt. Entsprechend verhält sich die Entwicklung der auf diesen Parzellen liegenden Anzahl Wohnungen, welche in der ersten Jahreshälfte 2022 mit 1 800 ihren absoluten Höchstwert erreicht. Wichtig ist hier zu beachten, dass diese Wohnungen in vielen Fällen weitherin Mietwohnungen sein können, die auf Parzellen mit begründetem Stockwerkeigentum vermietet werden.",
		"erlaeuterungen": "Anzahl Stammparzellen gemäss Grundbuch, auf denen Stockwerkeigentum begründet wurde, und auf denen Wohngebäude mit Wohnungen gemäss Gebäude- und Wohnungsregister existieren. Begründungen vor Gebäudeerstellung werden nicht berücksichtigt. Neubauten sind berücksichtigt falls das Stockwerkeigentum mit oder nach der Bauvollendung begründet wurde. Unberücksichtigt sind zudem Mansarden bzw. bewohnbare Einzelzimmer, Alters- und Genossenschaftswohnungen sowie Büros, Garagen, Lager, Ateliers und andere nicht zum Wohnen genutzte Einheiten. Die Verordnung zum Wohnraumschutz ist am 28. Mai 2022 in Kraft getreten. H1 oder H2 bezeichnen das erste beziehungsweise das zweite Halbjahr eines Jahres.",
		"quellenangabe": [
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Umwandlungen in Stockwerkeigentum",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-3",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_007",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-07-10T08:04:38",
		"id": 22294
	},
	{
		"template": "template001",
		"data-id": 22295,
		"chart-id": 22295,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Fördervolumen Gebäudeprogramm",
		"subtitle": "Auszahlungen pro Jahr für Wärmedämmung, in Franken, Basel-Stadt",
		"lesehilfe": "Die jährlich im Rahmen des Gebäudeprogramms von Kanton und Bund ausbezahlten Förderbeiträge für die Wärmedämmung von Bestandsgebäuden (Einfamilien- und Mehrfamilienhäuser) haben sich im Kanton Basel-Stadt seit 2017 von gut 1,8 Mio. Franken auf knapp 3,4 Mio. Franken erhöht. Bei Mehrfamilienhäusern ist ein starker Anstieg zu verzeichnen, während sich die Entwicklung bei Einfamilienhäusern auf stabilem Niveau bewegt.",
		"erlaeuterungen": "Gemäss Gebäudeprogramm von Kanton und Bund ausbezahlte Förderbeiträge nach Gebäudekategorie. Die Auszahlung der Fördergelder erfolgt nach Abschluss der Sanierung, zwischen Förderzusage und Auszahlung können mehrere Jahre vergehen. Weitere Informationen zum Gebäudeprogramm finden sich hier: <a href='https://www.dasgebaeudeprogramm.ch/de' target='_blank'>Gebäudeprogramm</a>",
		"quellenangabe": [
			"Gebäudeprogramm"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Fördervolumen Gebäudeprogramm",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-4",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_008",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-07-10T08:04:42",
		"id": 22295
	},
	{
		"template": "template001",
		"data-id": 22296,
		"chart-id": 22296,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Abgebrochene Wohnungen",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "In den letzten 10 Jahren wurden im Durchschnitt jährlich rund 110 Wohnungen abgebrochen. Im Jahr 2024 war die Anzahl abgebrochener Wohnungen mit 77 unterdurchschnittlich.",
		"erlaeuterungen": "Abgebrochene Wohnungen nach Jahr des Abbruchs.Zwischen Bewilligung für den Abbruch und erfolgtem Abbruch können mehrere Jahre liegen. Bei den Zahlen der Jahre 2023 und 2024 handelt es sich somit auch um Abbruchprojekte, die noch vor der Inkraftsetzung der Wohnraumschutzbestimmungen am 28. Mai 2022 bewilligt wurden.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Abgebrochene Wohnungen",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-6",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_010",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-07-10T08:04:48",
		"id": 22296
	},
	{
		"template": "template001",
		"data-id": 22297,
		"chart-id": 22297,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Wohnungsneubau",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Die Anzahl der neugebauten Wohnungen lag 2024 bei 151 Einheiten und damit deutlich unter dem Wert der Vorjahre. Vor allem aus Arealentwicklungen resultierten nur sehr wenige neue Wohnungen.",
		"erlaeuterungen": "Als Arealentwicklungen werden Areale bezeichnet, auf denen ein massgeblicher Gewinn an Wohnraum im Vergleich zur vorherigen Nutzung resultiert. Zu den grössten Arealentwicklungen der letzten Jahre gehören beispielsweise Projekte auf den Arealen Erlenmatt, Westfeld und Lysbüchel (Volta Nord) sowie das Meret Oppenheim Hochhaus. Grössere Ersatzneubauten (z.B. der Claraturm) werden hier ebenfalls zu den Arealentwicklungen gezählt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Wohnungsneubau",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-7",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_011",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-07-10T08:04:52",
		"id": 22297
	},
	{
		"template": "template001",
		"data-id": 22298,
		"chart-id": 22298,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Baubewilligte Wohnungen und Gebäude",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "Im Jahr 2024 wurden 442 Neubauwohnungen bewilligt. Nach einer Phase mit weniger Bewilligungen (2021–2023) liegt dieser Wert im Durchschnitt der vorangegangenen zehn Jahre.",
		"erlaeuterungen": "Gezählt werden bewilligte Wohnungen und bewohnbare Gebäude in Neubauprojekten, nach Jahr der Baubewilligung. Umbauprojekte mit Wohnungszuwachs werden nicht berücksichtigt.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Gebäude- und Wohnungsstatistik"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Baubewilligte Wohnungen und Gebäude",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-8",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_012",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-07-10T08:04:56",
		"id": 22298
	},
	{
		"template": "line001",
		"data-id": 22299,
		"chart-id": 22299,
		"filter": "",
		"parentId": "7586",
		"children": [],
		"title": "Leerwohnungsquote in Grossstädten und in der Schweiz",
		"subtitle": "",
		"lesehilfe": "Mit der vor rund 20 Jahren einsetzenden Zunahme der Wohnbevölkerung sank auch die Basler Leerwohnungsquote bis 2017 auf das Niveau der anderen grossen Schweizer Städte. Seit 2019 weist die Stadt Basel eine höhere Leerwohnungsquote auf als die anderen Grossstädte.",
		"erlaeuterungen": "Eine Wohnung gilt als leerstehend, wenn sie am Stichtag 1. Juni bezogen werden könnte und zur Dauermiete von mindestens drei Monaten oder zum Kauf angeboten wird.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt, Leerstandserhebung"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Gemeinde",
			"Schweiz"
		],
		"description": "Leerwohnungsquote in Grossstädten und in der Schweiz",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Leerstand",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-9",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_013",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-09-12T11:18:12",
		"id": 22299
	},
	{
		"template": "line001",
		"data-id": 22300,
		"chart-id": 12722,
		"filter": "",
		"parentId": "12722",
		"children": [],
		"title": "Bodenpreisindex",
		"subtitle": "indexiert (Basis 2014 = 100), Basel-Stadt",
		"lesehilfe": "Der Index für Einfamilienhaus-Grundstücke erreichte im Jahr 2023 den Stand von 168 Punkten, was einem prozentualen Anstieg von 68% gegenüber dem Basisjahr 2014 entspricht. Bei den Mehrfamilienhaus-Grundstücken lag er bei 218 Punkten.",
		"erlaeuterungen": "Das methodische Vorgehen ist im <a href='https://statistik.bs.ch/files/berichte-analysen/Methodenbericht-Bodenpreisindex.pdf' target='_blank'>Methodenbericht</a> beschrieben.",
		"quellenangabe": [
			"Statistisches Amt Basel-Stadt",
			"Grundbuch- und Vermessungsamt Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Bodenpreisindex",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Grundstückhandel",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-10",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_014",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-07-10T08:04:31",
		"id": 22300
	},
	{
		"template": "template001",
		"data-id": 22301,
		"chart-id": 22301,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Anzahl Gesuche Wohnschutzkommission (WSK)",
		"subtitle": "Basel-Stadt",
		"lesehilfe": "2024 gab es 124 Prüfungs- und Bewilligungsverfahren für Umbauten, Renovationen und Sanierungen. 18 Gesuche wurden für die Begründung von Stockwerkeigentum eingereicht und 3 Gesuche für die Festlegung von maximalen Nettomietzinsen bei Abbruch und Ersatzneubau.",
		"erlaeuterungen": "Ausgewiesen werden die jährlich neu bei der WSK eintreffenden Gesuche. Für Sanierungs-, Renovations- und Umbauvorhaben, die nach Wohnraumfördergesetz (WRFG) bewilligungspflichtig sind, kommen <a href='https://www.bs.ch/regierungsrat/staatskanzlei/staatliche-stelle-fuer-wohnraumschutz/verfahren/sanierung-renovation-und-umbau' target='_blank'>unterschiedliche Verfahren</a> zur Anwendung.",
		"quellenangabe": [
			"Staatskanzlei Basel-Stadt"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Anzahl Gesuche Wohnschutzkommission (WSK)",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "003-1",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_015",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-07-10T08:05:05",
		"id": 22301
	},
	{
		"template": "template001",
		"data-id": 22326,
		"chart-id": 22326,
		"filter": "",
		"parentId": null,
		"children": [],
		"title": "Förderzusagen Gebäudeprogramm",
		"subtitle": "Verpflichtungen pro Jahr für Wärmedämmung, indexiert (Basis 2017 = 100), Basel-Stadt",
		"lesehilfe": "Zwischen 2017 und 2023 haben die zugesagten Förderbeiträge für Wärmedämmungen schweizweit um 13% zugenommen. Im Kanton Basel-Stadt haben sich die Beiträge bis 2021 fast verzweieinhalbfacht. 2022 gingen sie stark zurück, nahmen 2023 aber wieder deutlich zu.",
		"erlaeuterungen": "Gemäss <a href='https://www.dasgebaeudeprogramm.ch/de' target='_blank'>Gebäudeprogramm</a> zugesagte Förderbeiträge, indexiert auf das Jahr 2017.",
		"quellenangabe": [
			"Gebäudeprogramm"
		],
		"externalLinks": [],
		"renderLink": [],
		"raeumlicheGliederung": [
			"Kanton"
		],
		"description": "Förderzusagen Gebäudeprogramm",
		"thema": "09 Bau-, Wohnungswesen",
		"unterthema": "Gebäude und Wohnungen",
		"kuerzel": "",
		"kennzahlenset": "Wohnraumschutz",
		"kuerzelKunde": "002-5",
		"stufe1": "",
		"stufe2": "",
		"stufe3": "",
		"stufe4": "",
		"stufe5": "",
		"orderKey": "_009",
		"darstellungsart": "Diagramm",
		"printformat": "",
		"datenInChartIntegriert": false,
		"aktualisierungsdatum": "2025-07-10T08:04:45",
		"id": 22326
	}
];